### ISSUE TITLE
PathTerminator is not right

### ISSUE THREAD

**Issue by valour01** [angr/angr#1019]
I am using CFGAccurate to analysis a binary. Below is apart of the binary code
```
.text:0000B5D4 loc_B5D4                                ; CODE XREF: sub_B264:loc_B5D0↑j
.text:0000B5D4                 LDR     R0, [R11,#var_A4]
.text:0000B5D8                 STR     R0, [R11,#var_C4]
.text:0000B5DC                 LDR     R0, [R11,#var_C4] ; s
.text:0000B5E0                 BL      strlen
.text:0000B5E4                 ADD     R0, R0, #1
.text:0000B5E8                 STR     R0, [R11,#var_C8]
.text:0000B5EC                 LDR     R0, [R11,#var_C8]
.text:0000B5F0                 ADD     R0, R0, #7
.text:0000B5F4                 BIC     R0, R0, #7
.text:0000B5F8                 SUB     R0, SP, R0
.text:0000B5FC                 MOV     SP, R0
```

Angr could locate the node 0xb5d4. However, it thinks the node at 0xb5e4 is the PathTerminator.
```
In [8]: cfg.get_any_node(0xb5d4)
Out[8]: <CFGNode 0xb5d4[16]>
```

```
In [9]: cfg.get_any_node(0xb5e4)
Out[9]: <CFGNode PathTerminator 0xb5e4>
```

I don't think this is a right behavior. Can anyone give some suggestions or need further information. Many Thanks

**Comment by cq674350529** [comment]
In `CFGAccurate._get_simsuccessors()`, there are many exception handlers which create `PathTerminator`.  Maybe you should look if any exception occurs when get successors during  `CFGAccurate` analysis.

**Comment by valour01** [comment]
@cq674350529  Thanks for your suggestions.

I looked into the log of angr. And it seems that the pathteminator is caused by a SimError.
```
  8707 Caught a SimError during CFG recovery. Don't panic, this is usually expected.
  8708 Traceback (most recent call last):                                                                                                                                       
  8709   File "/home/linux/angr-dev/angr/angr/analyses/cfg/cfg_accurate.py", line 2704, in _get_simsuccessors
  8710     opt_level=self._iropt_level)
  8711   File "/home/linux/angr-dev/angr/angr/factory.py", line 61, in successors
  8712     return self.project.engines.successors(*args, **kwargs)
  8713   File "/home/linux/angr-dev/angr/angr/engines/hub.py", line 44, in successors
  8714     r = engine.process(state, **kwargs)
  8715   File "/home/linux/angr-dev/angr/angr/engines/vex/engine.py", line 120, in process
  8716     opt_level=opt_level)        
  8717   File "/home/linux/angr-dev/angr/angr/engines/engine.py", line 59, in process
  8718     self._process(new_state, successors, *args, **kwargs)
  8719   File "/home/linux/angr-dev/angr/angr/engines/vex/engine.py", line 170, in _process
  8720     self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
  8721   File "/home/linux/angr-dev/angr/angr/engines/vex/engine.py", line 280, in _handle_irsb
  8722     exit_stmt_idx='default', exit_ins_addr=state.scratch.ins_addr)
  8723   File "/home/linux/angr-dev/angr/angr/engines/successors.py", line 116, in add_successor
  8724     self._preprocess_successor(state, add_guard=add_guard)
  8725   File "/home/linux/angr-dev/angr/angr/engines/successors.py", line 153, in _preprocess_successor
  8726     self._manage_callstack(state)
  8727   File "/home/linux/angr-dev/angr/angr/engines/successors.py", line 184, in _manage_callstack
  8728     stack_ptr=state.se.eval(state.regs._sp),
  8729   File "/home/linux/angr-dev/angr/angr/state_plugins/solver.py", line 705, in eval
  8730     return self.eval_upto(e, 1, **kwargs)[0]
  8731   File "/home/linux/angr-dev/angr/angr/state_plugins/solver.py", line 688, in eval_upto
  8732     cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
  8733   File "/home/linux/angr-dev/angr/angr/state_plugins/solver.py", line 155, in concrete_shortcut_tuple
  8734     return f(self, *args, **kwargs)
  8735   File "/home/linux/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 53, in ast_stripper
  8736     return f(*new_args, **new_kwargs)
  8737   File "/home/linux/angr-dev/angr/angr/state_plugins/solver.py", line 86, in wrapped_f
  8738     return f(*args, **kwargs)   
  8739   File "/home/linux/angr-dev/angr/angr/state_plugins/solver.py", line 480, in _eval
  8740     return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  8741   File "/home/linux/angr-dev/claripy/claripy/frontend_mixins/concrete_handler_mixin.py", line 7, in eval
  8742     return super(ConcreteHandlerMixin, self).eval(e, n, **kwargs)
  8743   File "/home/linux/angr-dev/claripy/claripy/frontend_mixins/constraint_filter_mixin.py", line 40, in eval
  8744     return super(ConstraintFilterMixin, self).eval(e, n, extra_constraints=ec, **kwargs)
  8745   File "/home/linux/angr-dev/claripy/claripy/frontend_mixins/sat_cache_mixin.py", line 56, in eval
  8746     extra_constraints=extra_constraints, **kwargs
  8747   File "/home/linux/angr-dev/claripy/claripy/frontend_mixins/simplify_helper_mixin.py", line 13, in eval
  8748     return super(SimplifyHelperMixin, self).eval(e, n, *args, **kwargs)
  8749   File "/home/linux/angr-dev/claripy/claripy/frontend_mixins/constraint_expansion_mixin.py", line 12, in eval
  8750     **kwargs                    
  8751   File "/home/linux/angr-dev/claripy/claripy/frontends/composite_frontend.py", line 281, in eval
  8752     self._ensure_sat(extra_constraints=extra_constraints)
  8753   File "/home/linux/angr-dev/claripy/claripy/frontends/composite_frontend.py", line 259, in _ensure_sat
  8754     raise UnsatError("CompositeSolver is already unsat")
  8755 SimUnsatError: ('Got an unsat result', <class 'claripy.errors.UnsatError'>, UnsatError('CompositeSolver is already unsat',))
  8756 SimProcedure PathTerminator [0xb5e4 | 0xae0c->0xb264]
```

Anyone know the reason why this exception is raised? Maybe some constraints could not be solved?

**Comment by cq674350529** [comment]
What do you want to do when using `CFGAccurate` to analyze the binary? If possible, you should attach the binary and the corresponding scripts, thus someone else can give more specific suggestions.

**Comment by ltfish** [comment]
```
  8727   File "/home/linux/angr-dev/angr/angr/engines/successors.py", line 184, in _manage_callstack
  8728     stack_ptr=state.se.eval(state.regs._sp),
```

The problem is that in `CFGAccurate` states might go unsat (which is totally expected), but starting from some time ago (in one of the angr refactors I think) we cannot reason about the value of an AST using an unsat state, _even when the AST itself is concrete_.

I'll have to talk to @zardus to see the best way to fix this. @valour01 Can you please provide your binary so we can reproduce and fix this issue?

**Comment by valour01** [comment]
@ltfish  Thanks for your help
Attached [cp-strip.zip](https://github.com/angr/angr/files/2066836/cp-strip.zip)

Besides,  the newest version of angr (dev version) could not analysis the binary due to the following exception
```
File "/home/jmh/PycharmProjects/generate.py/generate_cfg.py", line 4, in <module>
    cfg = p.analyses.CFGAccurate(starts = [p.entry])
  File "/home/jmh/Downloads/angr-dev/angr/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/jmh/Downloads/angr-dev/angr/angr/analyses/cfg/cfg_accurate.py", line 278, in __init__
    self._analyze()
  File "/home/jmh/Downloads/angr-dev/angr/angr/analyses/forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "/home/jmh/Downloads/angr-dev/angr/angr/analyses/forward_analysis.py", line 677, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/jmh/Downloads/angr-dev/angr/angr/analyses/forward_analysis.py", line 700, in _process_job_and_get_successors
    new_jobs = self._handle_successor(job, successor, successors)
  File "/home/jmh/Downloads/angr-dev/angr/angr/analyses/cfg/cfg_accurate.py", line 1677, in _handle_successor
    suc_jumpkind)
  File "/home/jmh/Downloads/angr-dev/angr/angr/analyses/cfg/cfg_accurate.py", line 2811, in _create_new_call_stack
    sp = se.eval_one(all_jobs[-1].regs.sp, default=0)
  File "/home/jmh/Downloads/angr-dev/angr/angr/state_plugins/solver.py", line 721, in eval_one
    return self.eval_exact(e, 1, **{k: v for (k, v) in kwargs.iteritems() if k != 'default'})[0]
  File "/home/jmh/Downloads/angr-dev/angr/angr/state_plugins/solver.py", line 772, in eval_exact
    r = self.eval_upto(e, n + 1, **kwargs)
  File "/home/jmh/Downloads/angr-dev/angr/angr/state_plugins/solver.py", line 689, in eval_upto
    cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
  File "/home/jmh/Downloads/angr-dev/angr/angr/state_plugins/solver.py", line 155, in concrete_shortcut_tuple
    return f(self, *args, **kwargs)
  File "/home/jmh/Downloads/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 53, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/home/jmh/Downloads/angr-dev/angr/angr/state_plugins/solver.py", line 86, in wrapped_f
    return f(*args, **kwargs)
  File "/home/jmh/Downloads/angr-dev/angr/angr/state_plugins/solver.py", line 481, in _eval
    return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/jmh/Downloads/angr-dev/claripy/claripy/frontend_mixins/concrete_handler_mixin.py", line 7, in eval
    return super(ConcreteHandlerMixin, self).eval(e, n, **kwargs)
  File "/home/jmh/Downloads/angr-dev/claripy/claripy/frontend_mixins/constraint_filter_mixin.py", line 40, in eval
    return super(ConstraintFilterMixin, self).eval(e, n, extra_constraints=ec, **kwargs)
  File "/home/jmh/Downloads/angr-dev/claripy/claripy/frontends/light_frontend.py", line 42, in eval
    raise ClaripyFrontendError("Light solver can't handle this eval().")
angr.errors.SimSolverModeError: ('Translated claripy error:', <class 'claripy.errors.ClaripyFrontendError'>, ClaripyFrontendError("Light solver can't handle this eval().",))
```
I use the dev version which is downloaded about two month ago so that you may be able to reproduce this problem. Feel free if you need any other information. Many Thanks

**Comment by ltfish** [comment]
> the newest version of angr (dev version) could not analysis the binary due to the following exception

It should've been solved by [this PR](https://github.com/angr/angr/pull/1024) two days ago. Please pull angr again.

**Comment by ltfish** [comment]
I couldn't not reproduce your issue on the latest angr.

```
ipdb> cfg.get_any_node(0xb5e4).block.pp()
0xb5e4: add     r0, r0, #1
0xb5e8: str     r0, [fp, #-0xc8]
0xb5ec: ldr     r0, [fp, #-0xc8]
0xb5f0: add     r0, r0, #7
0xb5f4: bic     r0, r0, #7
0xb5f8: sub     r0, sp, r0
0xb5fc: mov     sp, r0
0xb600: str     r0, [fp, #-0xcc]
0xb604: ldr     r4, [fp, #-0xcc]
0xb608: ldr     r1, [fp, #-0xc4]
0xb60c: ldr     r2, [fp, #-0xc8]
0xb610: mov     r0, r4
0xb614: bl      #0x98c8
```

Maybe the issue has been fixed at one point. Let me know if there are more problems.

**Comment by valour01** [comment]
@ltfish I pulled the newest version of angr and the problem is fixed. Thank you very much
