### ISSUE TITLE
How to use exploration techniques Threading?

### ISSUE THREAD

**Issue by Youlor** [angr/angr#1032]
Hello!
When I use `Threading` , get an error:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.1\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.1\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "G:/python/AngrTest/CoreTest.py", line 13, in <module>
    simgr.explore(find=0x4011D3, num_find=3)
  File "C:\python27-x64\lib\site-packages\angr-7.8.2.21-py2.7.egg\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\python27-x64\lib\site-packages\angr-7.8.2.21-py2.7.egg\angr\sim_manager.py", line 242, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr-7.8.2.21-py2.7.egg\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\python27-x64\lib\site-packages\angr-7.8.2.21-py2.7.egg\angr\sim_manager.py", line 265, in run
    self.step(stash=stash, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr-7.8.2.21-py2.7.egg\angr\misc\hookset.py", line 57, in __call__
    result = next_hook(self.func.im_self, *args, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr-7.8.2.21-py2.7.egg\angr\exploration_techniques\explorer.py", line 100, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr-7.8.2.21-py2.7.egg\angr\misc\hookset.py", line 57, in __call__
    result = next_hook(self.func.im_self, *args, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr-7.8.2.21-py2.7.egg\angr\exploration_techniques\threading.py", line 34, in step
    tsimgr = simgr.copy(stashes=dict(simgr.stashes))
TypeError: copy() got an unexpected keyword argument 'stashes'
```
My Code:
```
    main_opts = {'custom_base_addr': 0x00400000, 'custom_entry_point': 0x401270}
    proj = angr.Project('CrackMe2.exe', auto_load_libs=False, main_opts=main_opts)
    simgr = proj.factory.simgr()
    simgr.use_technique(angr.exploration_techniques.Threading())
    simgr.explore(find=0x4011D3, num_find=3)  # There cause error
```
So, How to use `Threading` ? Thanks!

**Comment by rhelmot** [comment]
Threading is broken as of #888.

cc @danse-macabre

**Comment by danse-macabre** [comment]
I'm sorry, I didn't have a chance to look into the problem yet. I'll do my best to fix the technique sometime this week.

**Comment by rhelmot** [comment]
Threading is fixed as of https://github.com/angr/angr/pull/3462
