### ISSUE TITLE
CFGAccurate() throws a SimEngineError error

### ISSUE THREAD

**Issue by GodsJoy** [angr/angr#1064]
It first gives a bunch of warnings then terminates with a SimEngineError error.
Sample of warnings:
angr.procedures.definitions | unsupported syscall: readlink
angr.state_plugins.callstack | Returning to an unexpected address 0xa226040

Here is the full error backtrace:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/analysis.py", line 96, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_accurate.py", line 279, in __init__
    self._analyze()
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 508, in _analyze
    self._analysis_core_baremetal()
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 618, in _analysis_core_baremetal
    self._pre_job_handling(job_info.job)
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_accurate.py", line 1209, in _pre_job_handling
    ins_addr=src_ins_addr, stmt_idx=src_exit_stmt_idx)
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_accurate.py", line 1911, in _update_function_transition_graph
    )._get_block(ret_addr).codenode if ret_addr else None
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/knowledge_plugins/functions/function.py", line 194, in _get_block
    block = self._project.factory.block(addr, size=size, byte_string=byte_string)
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/factory.py", line 332, in block
    backup_state=backup_state, opt_level=opt_level, num_inst=num_inst, traceflags=traceflags
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/block.py", line 60, in __init__
    traceflags=traceflags)
  File "/home/rukayat/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/engines/vex/engine.py", line 461, in lift
    raise SimEngineError("No bytes in memory for block starting at %#x." % addr)
angr.errors.SimEngineError: No bytes in memory for block starting at 0x5.

**Comment by ltfish** [comment]
Can you please upload the binary so that I can test and diagnose the issue?

**Comment by GodsJoy** [comment]
Okay. I will do that.

On Jun 20, 2018 1:39 PM, "Fish" <notifications@github.com> wrote:

Can you please upload the binary so that I can test and diagnose the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/angr/angr/issues/1064#issuecomment-398835731>, or mute
the thread

**Comment by GodsJoy** [comment]
Here is one of the binaries that this error was thrown on
[nodeO2.tar.gz](https://github.com/angr/angr/files/2120552/nodeO2.tar.gz)

**Comment by GodsJoy** [comment]
I just did.
