### ISSUE TITLE
CFGFast fails when resolving jump tables

### ISSUE THREAD

**Issue by KevOrr** [angr/angr#1075]
```AttributeError                            Traceback (most recent call last)
<ipython-input-34-34d0f86d8755> in <module>()
----> 1 cfg = p.analyses.CFGFast()

/home/kevin/.local/lib/python2.7/site-packages/angr/analyses/analysis.pyc in __call__(self, *args, **kwargs)
    106 
    107         oself._show_progressbar = show_progressbar
--> 108         oself.__init__(*args, **kwargs)
    109         return oself
    110 

/home/kevin/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.pyc in __init__(self, binary, regions, pickle_intermediate_results, symbols, function_prologues, resolve_indirect_jumps, force_segment, force_complete_scan, indirect_jump_target_limit, collect_data_references, extra_cross_references, normalize, start_at_entry, function_starts, extra_memory_regions, data_type_guessing_handlers, arch_options, indirect_jump_resolvers, base_state, exclude_sparse_regions, skip_specific_regions, heuristic_plt_resolving, start, end, **extra_arch_options)
    905 
    906         # Start working!
--> 907         self._analyze()
    908 
    909     #

/home/kevin/.local/lib/python2.7/site-packages/angr/analyses/forward_analysis.pyc in _analyze(self)
    550             # An example is the CFG recovery.
    551 
--> 552             self._analysis_core_baremetal()
    553 
    554         else:

/home/kevin/.local/lib/python2.7/site-packages/angr/analyses/forward_analysis.pyc in _analysis_core_baremetal(self)
    651 
    652             if not self._job_info_queue:
--> 653                 self._job_queue_empty()
    654 
    655             if not self._job_info_queue:

/home/kevin/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.pyc in _job_queue_empty(self)
   1381         # Try to see if there is any indirect jump left to be resolved
   1382         if self._resolve_indirect_jumps and self._indirect_jumps_to_resolve:
-> 1383             jump_targets = list(set(self._process_indirect_jumps()))
   1384 
   1385             for addr, func_addr, source_addr, jumpkind in jump_targets:

/home/kevin/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.pyc in _process_indirect_jumps(self)
   2545                     continue
   2546 
-> 2547                 resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
   2548                 if resolved:
   2549                     resolved_by = resolver

/home/kevin/.local/lib/python2.7/site-packages/angr/analyses/cfg/indirect_jump_resolvers/jumptable.pyc in resolve(self, cfg, addr, func_addr, block, jumpkind)
    146             for r in slicecutor.reached_targets:
    147                 try:
--> 148                     succ = project.factory.successors(r)
    149                 except (AngrError, SimError):
    150                     # oops there are errors

/home/kevin/.local/lib/python2.7/site-packages/angr/factory.pyc in successors(self, *args, **kwargs)
     59         """
     60 
---> 61         return self.project.engines.successors(*args, **kwargs)
     62 
     63     def blank_state(self, **kwargs):

/home/kevin/.local/lib/python2.7/site-packages/angr/engines/hub.pyc in successors(self, state, addr, jumpkind, default_engine, procedure_engine, engines, **kwargs)
    126         for engine in engines:
    127             if engine.check(state, **kwargs):
--> 128                 r = engine.process(state, **kwargs)
    129                 if r.processed:
    130                     return r

/home/kevin/.local/lib/python2.7/site-packages/angr/engines/vex/engine.pyc in process(self, state, irsb, skip_stmts, last_stmt, whitelist, inline, force_addr, insn_bytes, size, num_inst, traceflags, thumb, opt_level, **kwargs)
    133                 traceflags=traceflags,
    134                 thumb=thumb,
--> 135                 opt_level=opt_level)
    136 
    137     def _check(self, state, *args, **kwargs):

/home/kevin/.local/lib/python2.7/site-packages/angr/engines/engine.pyc in process(***failed resolving arguments***)
     53         successors = new_state._inspect_getattr('sim_successors', successors)
     54         try:
---> 55             self._process(new_state, successors, *args, **kwargs)
     56         except SimException:
     57             if o.EXCEPTION_HANDLING not in old_state.options:

/home/kevin/.local/lib/python2.7/site-packages/angr/engines/vex/engine.pyc in _process(self, state, successors, irsb, skip_stmts, last_stmt, whitelist, insn_bytes, size, num_inst, traceflags, thumb, opt_level)
    183 
    184             try:
--> 185                 self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
    186             except SimReliftException as e:
    187                 state = e.state

/home/kevin/.local/lib/python2.7/site-packages/angr/engines/vex/engine.pyc in _handle_irsb(self, state, successors, irsb, skip_stmts, last_stmt, whitelist)
    255                 state.scratch.stmt_idx = stmt_idx
    256                 state._inspect('statement', BP_BEFORE, statement=stmt_idx)
--> 257                 self._handle_statement(state, successors, stmt)
    258                 state._inspect('statement', BP_AFTER)
    259             except UnsupportedDirtyError:

/home/kevin/.local/lib/python2.7/site-packages/angr/engines/vex/engine.pyc in _handle_statement(self, state, successors, stmt)
    374             exit_state = state.copy()
    375             successors.add_successor(exit_state, s_stmt.target, s_stmt.guard, s_stmt.jumpkind,
--> 376                                      exit_stmt_idx=state.scratch.stmt_idx, exit_ins_addr=state.scratch.ins_addr)
    377 
    378             # Do our bookkeeping on the continuing state

/home/kevin/.local/lib/python2.7/site-packages/angr/engines/successors.pyc in add_successor(self, state, target, guard, jumpkind, add_guard, exit_stmt_idx, exit_ins_addr, source)
    114         state.scratch.exit_ins_addr = exit_ins_addr
    115 
--> 116         self._preprocess_successor(state, add_guard=add_guard)
    117 
    118         if state.history.jumpkind == 'Ijk_SigFPE_IntDiv' and o.PRODUCE_ZERODIV_SUCCESSORS not in state.options:

/home/kevin/.local/lib/python2.7/site-packages/angr/engines/successors.pyc in _preprocess_successor(self, state, add_guard)
    148         # apply the guard constraint and new program counter to the state
    149         if add_guard:
--> 150             state.add_constraints(state.scratch.guard)
    151         # trigger inspect breakpoints here since this statement technically shows up in the IRSB as the "next"
    152         state.regs.ip = state.scratch.target

/home/kevin/.local/lib/python2.7/site-packages/angr/sim_state.pyc in add_constraints(self, *args, **kwargs)
    328         if o.ABSTRACT_SOLVER in self.options and len(args) > 0:
    329             for arg in args:
--> 330                 if self.solver.is_false(arg):
    331                     self._satisfiable = False
    332                     return

/home/kevin/.local/lib/python2.7/site-packages/angr/state_plugins/solver.pyc in concrete_shortcut_not_bool(self, *args, **kwargs)
    133         v = _concrete_bool(args[0])
    134         if v is None:
--> 135             return f(self, *args, **kwargs)
    136         else:
    137             return not v

/home/kevin/.local/lib/python2.7/site-packages/angr/state_plugins/sim_action_object.pyc in ast_stripper(*args, **kwargs)
     51         new_args = _raw_ast(args)
     52         new_kwargs = _raw_ast(kwargs)
---> 53         return f(*new_args, **new_kwargs)
     54     return ast_stripper
     55 

/home/kevin/.local/lib/python2.7/site-packages/angr/state_plugins/solver.pyc in wrapped_f(*args, **kwargs)
     84     def wrapped_f(*args, **kwargs):
     85         try:
---> 86             return f(*args, **kwargs)
     87         except claripy.UnsatError:
     88             e_type, value, traceback = sys.exc_info()

/home/kevin/.local/lib/python2.7/site-packages/angr/state_plugins/solver.pyc in is_false(self, e, extra_constraints, exact)
    586                 assert ar is False
    587             return ar
--> 588         return self._solver.is_false(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
    589 
    590     @timed_function

/home/kevin/.local/lib/python2.7/site-packages/claripy/frontend_mixins/concrete_handler_mixin.pyc in is_false(self, e, **kwargs)
     58             return not c
     59         else:
---> 60             return super(ConcreteHandlerMixin, self).is_false(e, **kwargs)

/home/kevin/.local/lib/python2.7/site-packages/claripy/frontend_mixins/constraint_filter_mixin.pyc in is_false(self, e, extra_constraints, **kwargs)
     62     def is_false(self, e, extra_constraints=(), **kwargs):
     63         ec = self._constraint_filter(extra_constraints)
---> 64         return super(ConstraintFilterMixin, self).is_false(e, extra_constraints=ec, **kwargs)
     65 
     66 from ..errors import UnsatError, ClaripyValueError

/home/kevin/.local/lib/python2.7/site-packages/claripy/frontends/light_frontend.pyc in is_false(self, e, extra_constraints, exact)
     75     def is_false(self, e, extra_constraints=(), exact=None):
     76         try:
---> 77             return self._solver_backend.is_false(e)
     78         except BackendError:
     79             l.info("Light solver can't handle this is_false().")

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in is_false(self, e, extra_constraints, solver, model_callback)
    289             return self._false_cache[e.cache_key]
    290         except KeyError:
--> 291             f = self._is_false(self.convert(e), extra_constraints=extra_constraints, solver=solver, model_callback=model_callback)
    292             self._false_cache[e.cache_key] = f
    293             if f is True:

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/backend_vsa.pyc in convert(self, expr)
     96 
     97     def convert(self, expr):
---> 98         return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
     99 
    100     def _convert(self, a):

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert(self, expr)
    159                 else:
    160                     try:
--> 161                         r = self.call(expr.op, expr.args)
    162                     except BackendUnsupportedError:
    163                         r = self.default_op(expr)

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in call(self, op, args)
    193         :return:   A backend object representing the result.
    194         """
--> 195         converted = self.convert_list(args)
    196 
    197         if op in self._op_raw:

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert_list(self, args)
    181 
    182     def convert_list(self, args):
--> 183         return [ self.convert(a) for a in args ]
    184 
    185     #

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/backend_vsa.pyc in convert(self, expr)
     96 
     97     def convert(self, expr):
---> 98         return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
     99 
    100     def _convert(self, a):

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert(self, expr)
    159                 else:
    160                     try:
--> 161                         r = self.call(expr.op, expr.args)
    162                     except BackendUnsupportedError:
    163                         r = self.default_op(expr)

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in call(self, op, args)
    193         :return:   A backend object representing the result.
    194         """
--> 195         converted = self.convert_list(args)
    196 
    197         if op in self._op_raw:

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert_list(self, args)
    181 
    182     def convert_list(self, args):
--> 183         return [ self.convert(a) for a in args ]
    184 
    185     #

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/backend_vsa.pyc in convert(self, expr)
     96 
     97     def convert(self, expr):
---> 98         return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
     99 
    100     def _convert(self, a):

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert(self, expr)
    159                 else:
    160                     try:
--> 161                         r = self.call(expr.op, expr.args)
    162                     except BackendUnsupportedError:
    163                         r = self.default_op(expr)

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in call(self, op, args)
    193         :return:   A backend object representing the result.
    194         """
--> 195         converted = self.convert_list(args)
    196 
    197         if op in self._op_raw:

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert_list(self, args)
    181 
    182     def convert_list(self, args):
--> 183         return [ self.convert(a) for a in args ]
    184 
    185     #

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/backend_vsa.pyc in convert(self, expr)
     96 
     97     def convert(self, expr):
---> 98         return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
     99 
    100     def _convert(self, a):

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert(self, expr)
    159                 else:
    160                     try:
--> 161                         r = self.call(expr.op, expr.args)
    162                     except BackendUnsupportedError:
    163                         r = self.default_op(expr)

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in call(self, op, args)
    193         :return:   A backend object representing the result.
    194         """
--> 195         converted = self.convert_list(args)
    196 
    197         if op in self._op_raw:

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert_list(self, args)
    181 
    182     def convert_list(self, args):
--> 183         return [ self.convert(a) for a in args ]
    184 
    185     #

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/backend_vsa.pyc in convert(self, expr)
     96 
     97     def convert(self, expr):
---> 98         return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
     99 
    100     def _convert(self, a):

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in convert(self, expr)
    159                 else:
    160                     try:
--> 161                         r = self.call(expr.op, expr.args)
    162                     except BackendUnsupportedError:
    163                         r = self.default_op(expr)

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/__init__.pyc in call(self, op, args)
    197         if op in self._op_raw:
    198             # the raw ops don't get the model, cause, for example, Z3 stuff can't take it
--> 199             obj = self._op_raw[op](*converted)
    200         elif not op.startswith("__"):
    201             l.debug("backend has no operation %s", op)

/home/kevin/.local/lib/python2.7/site-packages/claripy/backends/backend_vsa.pyc in LShR(expr, shift_amount)
    320     @staticmethod
    321     def LShR(expr, shift_amount):
--> 322         return expr.LShR(shift_amount)
    323 
    324     @staticmethod

AttributeError: 'ValueSet' object has no attribute 'LShR'
```

**Comment by ltfish** [comment]
Is the binary available?

**Comment by KevOrr** [comment]
Possibly. I forgot to mention that this is on f8304c4b1f0097a721a6692b02a45cabaae137c5

**Comment by ltfish** [comment]
> Possibly.

Can you please share the binary so I can debug the issue? Thanks.

**Comment by ltfish** [comment]
Thank you for sharing the binary (and the loader). How much memory did it take for you to generate a CFG on this binary?

**Comment by KevOrr** [comment]
Yeah it ended up using a lot of memory before it hit that error. I think it was ~15GiB. It took about 10 hours to hit that error, but that could've been because I ran out of RAM and started swapping. Testing now on a machine with 32 GiB.

**Comment by ltfish** [comment]
This single binary has made me to improve both the memory usage and speed of CFG... if you can, please use the latest version of angr before testing it again.

**Comment by KevOrr** [comment]
Oh awesome! Will do, thanks

**Comment by KevOrr** [comment]
So it ran for about 50 minutes, got up to about 8.6GiB, and then segfaulted. I know that's probably not very helpful haha. I have a core dump? It's about 250MiB though

**Comment by ltfish** [comment]
Two things:

- 50 minutes is really long. I will work on speeding it up in the near future, but before that, can you try setting `force_complete_scan=False` and see if it's faster?
- 8.6 GB is kinda fine, but there is still room for improvement. I've been looking for ways to have a swap for this Python process or something...

**Comment by ltfish** [comment]
Oh, if you can, you should use PyPy. It's a lot faster than CPython.

**Comment by KevOrr** [comment]
Okay,so I re-ran it in python-debug overnight, and it got to 11.8GiB before hitting this error:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 909, in __init__
    self._analyze()
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 653, in _analysis_core_baremetal
    self._job_queue_empty()
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1385, in _job_queue_empty
    jump_targets = list(set(self._process_indirect_jumps()))
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 2549, in _process_indirect_jumps
    resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 160, in resolve
    succ = project.factory.successors(r)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/factory.py", line 61, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/engines/vex/engine.py", line 135, in process
    opt_level=opt_level)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/engines/vex/engine.py", line 185, in _process
    self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/engines/vex/engine.py", line 295, in _handle_irsb
    exit_stmt_idx='default', exit_ins_addr=state.scratch.ins_addr)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/engines/successors.py", line 116, in add_successor
    self._preprocess_successor(state, add_guard=add_guard)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/engines/successors.py", line 157, in _preprocess_successor
    self._manage_callstack(state)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/engines/successors.py", line 206, in _manage_callstack
    while state.se.is_true(state.regs._sp > state.callstack.top.stack_ptr):
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 125, in concrete_shortcut_bool
    return f(self, *args, **kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/state_plugins/sim_action_object.py", line 53, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 86, in wrapped_f
    return f(*args, **kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 565, in is_true
    return self._solver.is_true(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/frontend_mixins/concrete_handler_mixin.py", line 53, in is_true
    return super(ConcreteHandlerMixin, self).is_true(e, **kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 60, in is_true
    return super(ConstraintFilterMixin, self).is_true(e, extra_constraints=ec, **kwargs)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/frontends/light_frontend.py", line 70, in is_true
    return self._solver_backend.is_true(e)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/__init__.py", line 266, in is_true
    t = self._is_true(self.convert(e), extra_constraints=extra_constraints, solver=solver, model_callback=model_callback)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/backend_vsa.py", line 98, in convert
    return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/__init__.py", line 161, in convert
    r = self.call(expr.op, expr.args)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/__init__.py", line 195, in call
    converted = self.convert_list(args)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/__init__.py", line 183, in convert_list
    return [ self.convert(a) for a in args ]
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/backend_vsa.py", line 98, in convert
    return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/__init__.py", line 161, in convert
    r = self.call(expr.op, expr.args)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/__init__.py", line 199, in call
    obj = self._op_raw[op](*converted)
  File "/home/kevin/Downloads/python-debug/venv/lib/python2.7/site-packages/claripy/backends/backend_vsa.py", line 89, in _op_or
    return reduce(operator.__or__, args)
TypeError: unsupported operand type(s) for |: 'ValueSet' and 'StridedInterval'
```

This was on all the latest versions of angr, cle, pyvex, archinfo, pyvex, andd their dependencies as of ~9pm EDT last night. I can't say how long it took to hit that, but it was more than 2 hours.

I'll try on pypy and setting `force_complete_scan=False`.

**Comment by ltfish** [comment]
Just a heads-up, I'm working hard to reduce the memory usage and improve the speed of CFGFast so that it can work reasonably well on this binary...

The most recent PR that will help a bit is https://github.com/angr/pyvex/pull/135.

**Comment by KevOrr** [comment]
Hey! With `force_complete_scan=True` it doesn't throw any exceptions! Using pypy and angr/pyvex#135, it's only using 10 GiB and only took about 13 minutes. Yay!

Profile results and some warnings with tracebacks are [here](https://gist.github.com/KevOrr/4493382ce65ebdc8e6a52251bf07b3cc).
