### ISSUE TITLE
CFGFast SimValueError 

### ISSUE THREAD

**Issue by Kingloko** [angr/angr#1088]
I see its just a warning, but wanted to make sure its not a critical error given the traceback dump . 
```
WARNING | 2018-06-25 14:08:49,318 | angr.engines.vex.engine | 0x515cfc hit an error while analyzing statement 66
Traceback (most recent call last):
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/engine.py", line 257, in _handle_irsb
    self._handle_statement(state, successors, stmt)
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/engine.py", line 363, in _handle_statement
    s_stmt = translate_stmt(stmt, state)
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/statements/__init__.py", line 29, in translate_stmt
    s.process()
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/statements/base.py", line 37, in process
    self._execute()
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/statements/wrtmp.py", line 6, in _execute
    data = self._translate_expr(self.stmt.data)
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/statements/base.py", line 44, in _translate_expr
    e = translate_expr(expr, self.state)
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/expressions/__init__.py", line 14, in translate_expr
    e.process()
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/expressions/base.py", line 35, in process
    self._execute()
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/expressions/op.py", line 12, in _execute
    exprs = self._translate_exprs(self._expr.args)
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/expressions/base.py", line 83, in _translate_exprs
    return [ self._translate_expr(e) for e in exprs ]
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/expressions/base.py", line 76, in _translate_expr
    e = translate_expr(expr, self.state)
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/expressions/__init__.py", line 14, in translate_expr
    e.process()
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/expressions/base.py", line 35, in process
    self._execute()
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/engines/vex/expressions/rdtmp.py", line 11, in _execute
    self.expr = self.state.scratch.tmp_expr(self._expr.tmp)
  File "/home/evyatar/.virtualenvs/angr/local/lib/python2.7/site-packages/angr-7.8.6.16-py2.7.egg/angr/state_plugins/scratch.py", line 93, in tmp_expr
    'slicing.' % tmp
SimValueError: VEX temp variable 99 does not exist. This is usually the result of an incorrect slicing.
```

**Comment by ltfish** [comment]
Don't worry about it. It can surely be improved by improving the slicing code, but as you can see, the exception is properly handled.

**Comment by ltfish** [comment]
If you post the binary, we can look into it when we have time.

**Comment by Kingloko** [comment]
Awesome! Thanks. Feel free to close.
