### ISSUE TITLE
Why so many errors when constructing CFG and VFG?

### ISSUE THREAD

**Issue by zhaoguixu** [angr/angr#109]
Hi,

I am new in angr. I just try to construct the cfg and vfg for gzip, but it gives me lots of confusing errors. 

Constructing cfg:
```python
proj = angr.Project('.../164.gzip/src/gzip', load_options={'auto_load_libs': False})
main = proj.loader.main_bin.get_symbol("main")
start_state = proj.factory.blank_state(addr=main.addr)
cfg = proj.analyses.CFG(fail_fast=True, starts=[main.addr], initial_state=start_state)
```
Then, it gives mes lots of 

```
WARNING | 2016-05-11 22:46:52,736 | simuvex.vex.irop | IROp error (for operation Iop_DivModS64to32)
Traceback (most recent call last):
  File "/home/gui/Pythons/virtualenvs/python2.7.6-binalysis/lib/python2.7/site-packages/simuvex/vex/irop.py", line 831, in translate
    return operations[op].calculate( *s_args)
  File "/home/gui/Pythons/virtualenvs/python2.7.6-binalysis/lib/python2.7/site-packages/simuvex/vex/irop.py", line 353, in calculate
    raise SimOperationError("divide by zero!")
SimOperationError: divide by zero!
```

Next, I try 
```python
vfg = b.analyses.VFG(cfg, function_start=main.addr, interfunction_level=3)
```
It prompts endless
```
WARNING | 2016-05-11 23:01:51,911 | simuvex.plugins.abstract_memory | Converting an SI to address. This may implies an imprecise analysis (e.g. skipping functions) or a bug/"feature" in the program itself.
ERROR   | 2016-05-11 23:01:51,959 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_825_32{UNINITIALIZED}>.
WARNING | 2016-05-11 23:01:51,993 | simuvex.plugins.abstract_memory | Converting an SI to address. This may implies an imprecise analysis (e.g. skipping functions) or a bug/"feature" in the program itself.
ERROR   | 2016-05-11 23:01:51,959 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_825_32{UNINITIALIZED}>.
WARNING | 2016-05-11 23:01:51,993 | simuvex.plugins.abstract_memory | Converting an SI to address. This may implies an imprecise analysis (e.g. skipping functions) or a bug/"feature" in the program itself.
ERROR   | 2016-05-11 23:01:52,051 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_827_32{UNINITIALIZED}>.
WARNING | 2016-05-11 23:01:52,081 | simuvex.plugins.abstract_memory | Converting an SI to address. This may implies an imprecise analysis (e.g. skipping functions) or a bug/"feature" in the program itself.
ERROR   | 2016-05-11 23:01:52,137 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_829_32{UNINITIALIZED}>.
WARNING | 2016-05-11 23:01:52,170 | simuvex.plugins.abstract_memory | Converting an SI to address. This may implies an imprecise analysis (e.g. skipping functions) or a bug/"feature" in the program itself.
...
```
When I try:
```python
vfg = proj.analyses.VFG(cfg, interfunction_level=3)
```

It gives me a traceback,

```
TypeError                                 Traceback (most recent call last)
...

/home/gui/Pythons/virtualenvs/python2.7.6-binalysis/lib/python2.7/site-packages/angr/analyses/vfg.pyc in _handle_entry(self, entry_wrapper, exit_targets, pending_returns, tracing_times, retn_target_sources)
    434 
    435         # Execute this basic block with input state, and get a new SimRun object
--> 436         simrun, error_occured, restart_analysis = self._get_simrun(input_state, current_path, addr)
    437 
    438         if restart_analysis:

/home/gui/Pythons/virtualenvs/python2.7.6-binalysis/lib/python2.7/site-packages/angr/analyses/vfg.pyc in _get_simrun(self, state, current_path, addr)
    980 
    981         try:
--> 982             sim_run = self.project.factory.sim_run(current_path.state, jumpkind=jumpkind)
    983         except simuvex.SimUninitializedAccessError as ex:
    984             l.error("Found an uninitialized access (used as %s) at expression %s.", ex.expr_type, ex.expr)

/home/gui/Pythons/virtualenvs/python2.7.6-binalysis/lib/python2.7/site-packages/angr/factory.pyc in sim_run(self, state, addr, jumpkind, **block_opts)
    123                     sim_proc_class.__name__, addr)
    124             state._inspect('call', BP_BEFORE, function_name=sim_proc_class.__name__)
--> 125             r = sim_proc_class(state, addr=addr, sim_kwargs=kwargs)
    126             state._inspect('call', BP_AFTER, function_name=sim_proc_class.__name__)
    127             l.debug("... %s created", r)

/home/gui/Pythons/virtualenvs/python2.7.6-binalysis/lib/python2.7/site-packages/simuvex/s_procedure.pyc in __init__(self, state, ret_to, stmt_from, convention, arguments, sim_kwargs, run_func_name, **kwargs)
     65 
     66         run_func = getattr(self, run_func_name)
---> 67         r = run_func(*args, **self.kwargs)
     68 
     69         if (self.overriding_no_ret is False) or \

/home/gui/Pythons/virtualenvs/python2.7.6-binalysis/lib/python2.7/site-packages/simuvex/procedures/libc___so___6/strlen.pyc in run(self, s)
     30                 r, c, i = self.state.memory.find(s, self.state.se.BVV(0, 8), max_str_len, max_symbolic_bytes=max_symbolic_bytes)
     31 
---> 32                 self.max_null_index = max(self.max_null_index + i)
     33 
     34                 # Convert r to the same region as s

TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

It makes me quite confused with these errors. Anyone can tell me whats wrong with my code? How to make vfg usable?

Any help is appreciated.
Thanks.

**Comment by ltfish** [comment]
You can safely ignore all warnings and errors printed out by the logging system. Those logs are meant for debugging purposes, and they are all handled by CFG or VFG already.

Only the last one is a real bug. Apparently `i` is a list, while line 32 expects it to be an int. I thought this bug has been fixed before, but somehow it shows up here. I'll look into it.

**Comment by zhaoguixu** [comment]
The second seems never stopped while it gives endless error messages when I set the logger to ERROR level.

How can that be a normal behavior?


```
ERROR   | 2016-05-12 14:58:48,207 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3389_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:48,973 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3391_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:49,749 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3393_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:50,623 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3395_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:51,462 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3397_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:52,235 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3399_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:53,027 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3401_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:53,864 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3403_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:54,654 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3405_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:55,523 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3407_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:56,415 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3409_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:57,578 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3411_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:58,402 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3413_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:58:59,195 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3415_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:00,107 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3417_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:01,353 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3419_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:02,192 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3421_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:03,096 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3423_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:04,018 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3425_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:04,979 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3427_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:05,874 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3429_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:06,837 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3431_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:07,845 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3433_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:09,188 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3435_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:10,765 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3437_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:11,974 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3439_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:13,053 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3441_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:14,311 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3443_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:15,271 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3445_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:16,092 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3447_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:16,970 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3449_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:17,893 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3451_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:18,779 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3453_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:19,657 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3455_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:20,896 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3457_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:21,735 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3459_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:22,897 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3461_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:23,797 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3463_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:25,066 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3465_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:26,456 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3467_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:27,459 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3469_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:28,669 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3471_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:29,508 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3473_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:30,368 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3475_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:31,223 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3477_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:32,353 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3479_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:33,914 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3481_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:34,813 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3483_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:36,669 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3485_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:37,511 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3487_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:38,450 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3489_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:39,827 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3491_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:40,739 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3493_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:41,680 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3495_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:42,649 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3497_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:43,758 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3499_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:44,742 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3501_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:45,733 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3503_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:46,642 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3505_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:47,488 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3507_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:48,681 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3509_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:49,518 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3511_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:50,350 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3513_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:51,349 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3515_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:52,181 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3517_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:53,000 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3519_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:53,882 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3521_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:54,689 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3523_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:55,508 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3525_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:56,304 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3527_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:57,162 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3529_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:57,958 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3531_32{UNINITIALIZED}>.
ERROR   | 2016-05-12 14:59:59,112 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3533_32{UNINITIALIZED}>.
...
```

**Comment by zhaoguixu** [comment]
I have uploaded my target binary and src files here([https://drive.google.com/open?id=0B2mRHPLoS9i4VTdtQXR2OGNwWjg]). I would be very appreciated if  you can have a test.

**Comment by rhelmot** [comment]
@ltfish, who designed these analyses, has a bit of a habit of using ERROR log messages to describe when analysis finds behavior which differs from the expectation of what a well-behaved program should look like, according to the abstraction that the analysis imposes over a program. This could indicate a bug in the program, a bug in the analysis, or a bug-free program which does not fit into the analysis' abstraction.

We agreed a bit ago that we should only be using ERROR log messages when you want bugs reported, so I think another thing to do before closing this issue is for those errors to be downgraded to warnings :P

**Comment by zhaoguixu** [comment]
The main issue is it never wants to stop. 
logger.debug should be better for internal developing use. Massive error logs prompted to users make the tool a sense of unusable, although how much I want to successfully use angr not so angrily, such a cool tool implemented by Python. :)

**Comment by ltfish** [comment]
Those error logs will be downgraded to warnings.

> `ERROR   | 2016-05-12 14:58:48,207 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV32 stack_0x8049f9d_pre_-98_3389_32{UNINITIALIZED}>.`

However, this indicates a real problem happening in VFG. It's either because of a bug in the analysis, or because your target program is not well-formed (i.e. performing VSA on it will yield weird and unexpected results).

**Comment by ltfish** [comment]
> The main issue is it never wants to stop.

This is another issue with the VFG. I also noticed this behavior some time ago. Based on my speculation, it was introduced by some underlying changes in memory model of SimuVEX before, which causes `SimState.merge()` to always succeed (instead of saying two states are identical and no merge occurred). I'll take a look at this issue after DEFCON quals.

**Comment by ltfish** [comment]
> logger.debug should be better for internal developing use.

For internal development, we need to differentiate common debugging outputs from warnings and errors. Warnings and errors usually indicate something very unexpected or bad has happened. Please let me know if there is any elegant solution to only use `logger.debug` while debugging logs are split based on their severity.

> Massive error logs prompted to users make the tool a sense of unusable, although how much I want to successfully use angr not so angrily...

Sorry :-(

**Comment by marcusp46** [comment]
Is the SimOperationError a resolved issue?  I encountered this on a CFGAccurate run.  Thanks.

**Comment by ltfish** [comment]
You shouldn't see those warnings anymore. If you do, please let me know which line in `CFGAccurate` prints that out.
