### ISSUE TITLE
How to get concrete solutions for floating-point symbols

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#112]
Hi

I want to test a function which accepts floating-point variables as inputs. So I symbolize the floating-point variables by `claripy.FPS`. The caller object succesfully find all feasible paths. However, how can I get the concrete solution for floating-point symbols corresponding to each path? From the manual and the source code of `solver.py`, I find functions like `any_str`, `any_int`, but I do not find functions like `any_float`.

Thanks

**Comment by rhelmot** [comment]
`any_int` will give you a float when the node you pass it is fp-typed

**Comment by brokendragon** [comment]
@rhelmot `any_int` produces an exception. Below is the tested program
```
#include <stdio.h>
int test(float x, float y)
{
  if(x == y + 3.1) return 0;
  else return 1;
}
void main()
{
  float x = 0, y = 0;
  printf("%ld\n", sizeof(float));
  test(x, y);
}
```
```
Below is the command
import angr
import claripy
b = angr.Project("fp")
cfg = b.analyses.CFG(keep_state=True)
target_func = cfg.kb.functions.function(name="test")
print target_func
x = angr.claripy.FPS('x', claripy.FSORT_DOUBLE)
y = angr.claripy.FPS('y', claripy.FSORT_DOUBLE)
p = b.factory.path()
c = b.surveyors.Caller(0x400536, [x, y], start=p) #0x400536 is the address of function test
print tuple(c.iter_returns())
print c #3 path can be found
s = c.found[0].state
print s.se
print s.se.any_int(x)
print s.se.any_int(y)
```
And below is the result
```
Function test [0x400536]
  Syscall: False
  SP difference: 0
  Has return: True
  Returning: True
  Arguments: reg: [], stack: [0L]
  Blocks: [0x400560, 0x400572, 0x400566, 0x40056d, 0x400536]
  Calling convention: System V AMD64 - AMD64 []
((<BV64 0x1>, <Path with 2 runs (at 0x400440)>), (<BV64 0x1>, <Path with 3 runs (at 0x400440)>), (<BV64 0x0>, <Path with 4 runs (at 0x400440)>))
<Explorer with paths: 0 active, 0 spilled, 0 deadended, 0 errored, 0 unconstrained, 3 found, 0 avoided, 0 deviating, 0 looping, 0 lost>
<simuvex.plugins.solver.SimSolver object at 0x7f7100284c30>
Traceback (most recent call last):
  File "test_fp.py", line 20, in <module>
    print s.se.any_int(x)
  File "/home/ct/angr-dev/simuvex/simuvex/plugins/solver.py", line 330, in any_int
    ans = self.any_n_int(e, 1, extra_constraints=extra_constraints)
  File "/home/ct/angr-dev/simuvex/simuvex/plugins/solver.py", line 351, in any_n_int
    return list(self.eval(e, n, extra_constraints=extra_constraints, exact=exact))
  File "/home/ct/angr-dev/simuvex/simuvex/plugins/solver.py", line 77, in autoed_f
    return ast_stripping_op(f, self, *args, **kwargs)
  File "/home/ct/angr-dev/simuvex/simuvex/plugins/solver.py", line 47, in ast_stripping_op
    r = _actual_ast_stripping_op(f, *args, **kwargs)
  File "/home/ct/angr-dev/simuvex/simuvex/s_action_object.py", line 36, in ast_stripping_op
    return f(*new_args, **new_kwargs)
  File "/home/ct/angr-dev/simuvex/simuvex/plugins/solver.py", line 84, in wrapped_f
    return f(self, *args, **kwargs)
  File "/home/ct/angr-dev/simuvex/simuvex/plugins/solver.py", line 248, in eval
    return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/ct/angr-dev/claripy/claripy/frontends/caching_frontend.py", line 344, in eval
    self._eval(e, n_lacking, extra_constraints=solver_extra_constraints, exact=exact, cache=cache)
  File "/home/ct/angr-dev/claripy/claripy/frontends/full_frontend.py", line 91, in _eval
    return self._solver_backend.eval(e, n, extra_constraints=extra_constraints, result=self.result, solver=self._get_solver())
  File "/home/ct/angr-dev/claripy/claripy/backend.py", line 472, in eval
    return self._eval(self.convert(expr, result=result if n == 1 else None), n, result=result, extra_constraints=self.convert_list(extra_constraints, result=result), solver=solver)
  File "/home/ct/angr-dev/claripy/claripy/backend.py", line 166, in convert
    r = self.call(expr.op, expr.args, result=result)
  File "/home/ct/angr-dev/claripy/claripy/backends/backend_z3.py", line 263, in call
    return Backend.call(self, *args, **kwargs)
  File "/home/ct/angr-dev/claripy/claripy/backend.py", line 203, in call
    raise BackendError("backend has no operation %s" % op)
simuvex.s_errors.SimSolverModeError: ('Translated claripy error:', <class 'claripy.errors.ClaripyFrontendError'>, ClaripyFrontendError("Backend error during eval: <class 'claripy.errors.BackendError'>('backend has no operation FP')",))
```

**Comment by rhelmot** [comment]
so.... it's very possible you're running into the issue that the current version of angr doesn't support passing floating point arguments or return values. (the implementation for that is in the pipeline internally) However, I don't think that that by itself would cause that error.

@zardus, this one is on you :-)

**Comment by rhelmot** [comment]
This was fixed in the linked issue :)
