### ISSUE TITLE
Exception raised when running a DeepState example

### ISSUE THREAD

**Issue by agroce** [angr/angr#1132]
May be a DeepState bug, but reporting here in case it rings any bells:

1.  Install deepstate (https://github.com/trailofbits/deepstate)
2.  Build https://github.com/agroce/testfs
3.  It produces some reasonable output but also:

```
WARNING | 2018-07-18 01:28:47,394 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
INFO    | 2018-07-18 01:29:49,446 | deepstate.angr | Running 1 tests across 1 workers
ERROR   | 2018-07-18 02:17:38,675 | deepstate.angr | Uncaught exception: 
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/deepstate/main_angr.py", line 290, in do_run_test
    test_manager.run()
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/misc/immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/misc/immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/sim_manager.py", line 341, in step
    successors = self.step_state(state, successor_func, **run_args)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/sim_manager.py", line 362, in step_state
    successors = self.successors(state, successor_func, **run_args)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/sim_manager.py", line 401, in successors
    return self._project.factory.successors(state, **run_args)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/factory.py", line 61, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/engines/hook.py", line 51, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/engines/procedure.py", line 31, in process
    force_addr=force_addr)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/engines/procedure.py", line 65, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/root/.local/lib/python2.7/site-packages/angr-7.8.7.1-py2.7.egg/angr/sim_procedure.py", line 169, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "build/bdist.linux-x86_64/egg/deepstate/main_angr.py", line 157, in run
    DeepAngr(procedure=self).api_assume(arg, expr_ea, file_ea, line)
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 438, in api_assume
    expr, _ = self.read_c_string(expr_ea, concretize=False)
  File "build/bdist.linux-x86_64/egg/deepstate/common.py", line 145, in read_c_string
    assert isinstance(ea, (int, long))
AssertionError
```

**Comment by rhelmot** [comment]
This looks like a deepstate bug. If I had to guess it would be that someone forgot to convert from AST to int before calling `api_assume` in the running simprocedure.

**Comment by agroce** [comment]
Thanks!

**Comment by agroce** [comment]
(yes, it was our problem)
