### ISSUE TITLE
ClaripyOperationError raised while using step() 

### ISSUE THREAD

**Issue by yichuanyanyu26** [angr/angr#1136]
Hello,

I'm trying to use the simulation managers to step through the program to generate possible paths and build a set of paths. However, there are unknown problems that lead to simulation manager not able to reach all the paths.   
```

init_state_s = proj.factory.entry_state(args = args, add_options = add_options_s)
se_state = proj.factory.path(init_state_s) 
simgr = proj.factory.simulation_manager(init_state_s)
simgr.active
nextpaths = init_state_s.step()
init_state_s = nextpaths.successors[0]
simgr.run(n=1,step_func=self.conc_step_func)
target_addr = simgr.active[0].addr
```
And I get the output like so: 
```
DEBUG   | 2018-07-19 14:42:50,972 | find_newpath | staticmap[3421] = ff
DEBUG   | 2018-07-19 14:42:50,972 | find_newpath | path 9000038 has matched
DEBUG   | 2018-07-19 14:42:50,972 | find_newpath | path 9000038 has tested by afl
WARNING | 2018-07-19 14:42:50,982 | angr.state_plugins.posix | Trying to open unknown file id:000001,src:000000,op:flip1,pos:0,+cov - created a symbolic file since ALL_FILES_EXIST is set
WARNING | 2018-07-19 14:42:50,995 | angr.state_plugins.posix | Trying to open unknown file id:000001,src:000000,op:flip1,pos:0,+cov - created a symbolic file since ALL_FILES_EXIST is set
DEBUG   | 2018-07-19 14:42:50,998 | find_newpath | step_count: 22 size: 1 se_state: 9000038
DEBUG   | 2018-07-19 14:42:50,998 | find_newpath | nextpath: 80485d6 target_addr: 80485d6
DEBUG   | 2018-07-19 14:42:50,999 | find_newpath | staticmap[825c] = ff
DEBUG   | 2018-07-19 14:42:50,999 | find_newpath | path 80485d6 has matched
DEBUG   | 2018-07-19 14:42:50,999 | find_newpath | path 80485d6 has tested by afl
DEBUG   | 2018-07-19 14:42:51,017 | find_newpath | step_count: 23 size: 1 se_state: 80485d6
DEBUG   | 2018-07-19 14:42:51,017 | find_newpath | nextpath: 80485e6 target_addr: 80485e6
DEBUG   | 2018-07-19 14:42:51,017 | find_newpath | staticmap[e170] = ff
DEBUG   | 2018-07-19 14:42:51,017 | find_newpath | path 80485e6 has matched
DEBUG   | 2018-07-19 14:42:51,018 | find_newpath | path 80485e6 has tested by afl
DEBUG   | 2018-07-19 14:42:51,036 | find_newpath | step_count: 24 size: 1 se_state: 80485e6
DEBUG   | 2018-07-19 14:42:51,036 | find_newpath | nextpath: 8048410 target_addr: 8048410
DEBUG   | 2018-07-19 14:42:51,036 | find_newpath | staticmap[f6e] = ff
DEBUG   | 2018-07-19 14:42:51,036 | find_newpath | path 8048410 has matched
DEBUG   | 2018-07-19 14:42:51,037 | find_newpath | path 8048410 has tested by afl
DEBUG   | 2018-07-19 14:42:51,042 | find_newpath | step_count: 25 size: 1 se_state: 8048410
DEBUG   | 2018-07-19 14:42:51,042 | find_newpath | nextpath: 9000018 target_addr: 9000018
DEBUG   | 2018-07-19 14:42:51,042 | find_newpath | staticmap[3421] = ff
DEBUG   | 2018-07-19 14:42:51,042 | find_newpath | path 9000018 has matched
DEBUG   | 2018-07-19 14:42:51,042 | find_newpath | path 9000018 has tested by afl
Traceback (most recent call last):
  File "np.py", line 499, in <module>
    main(sys.argv)
  File "np.py", line 496, in main
    pf.execute_one_file(args.inputfile)
  File "np.py", line 310, in execute_one_file
    nextpaths = init_state_s.step()
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/sim_state.py", line 406, in step
    return self.project.factory.successors(self, **kwargs)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/factory.py", line 61, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/engines/hook.py", line 51, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/engines/procedure.py", line 31, in process
    force_addr=force_addr)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/engines/procedure.py", line 65, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/sim_procedure.py", line 169, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/procedures/libc/fread.py", line 21, in run
    ret = simfd.read(dst, size * nm)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/storage/file.py", line 575, in read
    self.state.memory.store(pos, data, size=realsize)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/storage/memory.py", line 552, in store
    self._store(request)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/state_plugins/symbolic_memory.py", line 725, in _store
    store_list = self._store_fully_concrete(req.actual_addresses[0], req.size, req.data, req.endness, req.condition)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/state_plugins/symbolic_memory.py", line 770, in _store_fully_concrete
    data = data[len(data)-1:len(data)-size*self.state.arch.byte_width:]
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/claripy/ast/bv.py", line 70, in __getitem__
    return Extract(left, right, self)
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/claripy/operations.py", line 54, in _op
    raise ClaripyOperationError(msg)
claripy.errors.ClaripyOperationError: Extract low must be <= high

How to solve this problem? Thanks

Best Regards

**Comment by bingosxs** [comment]
```
  File "/home/canicula/.virtualenvs/env2/local/lib/python2.7/site-packages/angr/state_plugins/symbolic_memory.py", line 770, in _store_fully_concrete
    data = data[len(data)-1:len(data)-size*self.state.arch.byte_width:]
 
```
The index range is 
`len(data)-1` ,    `len(data)-size*self.state.arch.byte_width`

if size*self.state.arch.byte_width > 1, the latter is smaller than the former.

Therefore 
`claripy.errors.ClaripyOperationError: Extract low must be <= high`
is triggered.

Any way to solve this issue?

**Comment by rhelmot** [comment]
You have it backwards, BV slicing is BV[high:low]. This is probably an issue where size = 0.

**Comment by rhelmot** [comment]
Can you please provide the binary to reproduce this? I am confused how this could happen since we explicitly guard against that condition.
