### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by B1gtang** [angr/angr#115]
```
 ~/ uname -a
Darwin Bigtang-2.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
 ~/ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/usr/local/lib/python2.7/site-packages/angr/project.py", line 10, in <module>
    import cle
  File "/usr/local/lib/python2.7/site-packages/cle/__init__.py", line 4, in <module>
    from .loader import *
  File "/usr/local/lib/python2.7/site-packages/cle/loader.py", line 6, in <module>
    import claripy
  File "/usr/local/lib/python2.7/site-packages/claripy/__init__.py", line 16, in <module>
    from . import backends as _backends_module
  File "/usr/local/lib/python2.7/site-packages/claripy/backends/__init__.py", line 1, in <module>
    from .backend_z3 import BackendZ3
  File "/usr/local/lib/python2.7/site-packages/claripy/backends/backend_z3.py", line 45, in <module>
    z3.init(z3_path)
  File "/usr/local/lib/python2.7/site-packages/z3core.py", line 84, in init
    _lib.Z3_param_descrs_get_documentation.restype = ctypes.c_char_p
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fd9584c0fd0, Z3_param_descrs_get_documentation): symbol not found
>>>
```

**Comment by rhelmot** [comment]
How did you install angr? Did you compile z3 on your own; what version did you use?

**Comment by B1gtang** [comment]
@rhelmot 
 ~/ sudo  pip install angr-only-z3-custom
 ~/ sudo  pip install z3
 ~/ z3 -h
Z3 [version 4.4.2 - 64 bit]. (C) Copyright 2006-2014 Microsoft Corp.

**Comment by rhelmot** [comment]
Both of those seem alright to me. I've never seen this kind of error before, and I don't know what factors you being on os x could have on the installation. :( It looks like the python bindings successfully loaded the z3 core, but then failed when trying to get a certain symbol, which indicates a version mismatch between your python bindings and your core.

Have you ever installed z3 from a source other than angr-only-z3 custom?

**Comment by B1gtang** [comment]
@rhelmot yes,i installed z3.

**Comment by rhelmot** [comment]
My best guess is that the z3 python bindings are picking up a different version of libz3.so than they expect.

Try totally uninstalling z3, deleting every libz3.so on your system, cleaning your python/site-packages directory of any file with z3 in its name, and then reinstalling angr-only-z3-custom.

**Comment by B1gtang** [comment]
It's fixed.
Thanks.

**Comment by trufae** [comment]
the z3 lib that expects is not in the dyld-library-path, use this env var to fix:
```
$ DYLD_LIBRARY_PATH=/Library/Python/2.7/site-packages/z3/lib/ python
Python 2.7.10 (default, May 26 2015, 13:01:57)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>>
```
