### ISSUE TITLE
SimIRSBNoDecodeError when using step

### ISSUE THREAD

**Issue by yichuanyanyu26** [angr/angr#1152]
Hello,

There is a problem when I use step just like:
```

import angr

proj=angr.Project('intov4',auto_load_libs=False)

state = proj.factory.entry_state()
simgr = proj.factory.simulation_manager(state)
state.step()
print simgr.active
```
And, 
```
WARNING | 2018-07-26 04:02:30,641 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
Traceback (most recent call last):
  File "n.py", line 10, in <module>
    state.step()
  File "/home/vagrant/.virtualenvs/env1/local/lib/python2.7/site-packages/angr/sim_state.py", line 406, in step
    return self.project.factory.successors(self, **kwargs)
  File "/home/vagrant/.virtualenvs/env1/local/lib/python2.7/site-packages/angr/factory.py", line 61, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/env1/local/lib/python2.7/site-packages/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/vagrant/.virtualenvs/env1/local/lib/python2.7/site-packages/angr/engines/vex/engine.py", line 135, in process
    opt_level=opt_level)
  File "/home/vagrant/.virtualenvs/env1/local/lib/python2.7/site-packages/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/env1/local/lib/python2.7/site-packages/angr/engines/vex/engine.py", line 165, in _process
    "(%#x, your_function, length=length_of_instruction)." % (addr, addr))
angr.errors.SimIRSBNoDecodeError: IR decoding error at 0x8048470. You can hook this instruction with a python replacement using project.hook(0x8048470, your_function, length=length_of_instruction).
``` 

The environment is,

```
Package          Version      
---------------- -------------
ailment          7.8.6.16     
ana              0.5          
angr             7.8.7.1      
archinfo         7.8.7.1      
bitstring        3.1.5        
cachetools       2.1.0        
capstone         3.0.5        
cffi             1.11.5       
claripy          7.8.6.16     
cle              7.8.7.1      
cooldict         1.2          
decorator        4.3.0        
dpkt-fix         1.7          
future           0.16.0       
futures          3.2.0        
gitdb2           2.0.4        
GitPython        2.1.11       
idalink          0.11         
mulpyplexer      0.8          
networkx         2.1          
pefile           2017.11.5    
pip              18.0         
pkg-resources    0.0.0        
plumbum          1.6.6        
progressbar      2.5          
pycparser        2.18         
pyelftools       0.24         
pyvex            7.8.7.1      
rpyc             4.0.1        
setuptools       40.0.0       
smmap2           2.0.4        
sortedcontainers 1.5.10       
unicorn          1.0.1        
wheel            0.31.1       
z3-solver        4.5.1.0.post2
```
The program can run at
`Linux sihai 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` 

 but cannot run at
 
`Linux vagrant 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:34:49 UTC 2016 i686 i686 i686 GNU/Linux`

How to solve this problem? Thanks

**Comment by rhelmot** [comment]
angr doesn’t execute things on your host processor directly, so the ability
to run the binary natively has no affect on whether instructions can be
processed by angr. It has to do with what VEX supports. Can you please open
the binary in a disassembler and show us the instruction at the given
address? In the meantime, you can use the workaround described in the error
message.
