### ISSUE TITLE
CFGAccurate problem

### ISSUE THREAD

**Issue by xiaoxing521** [angr/angr#1192]
[rawdec.zip](https://github.com/angr/angr/files/2362950/rawdec.zip)

I analyzed an .obj file and created a CFG from an address (for example, 0x400030), but an error occurred. The error message is as follows.

```
>>> import angr
>>> proj = angr.Project('./rawdec.o',load_options = {'auto_load_libs': False})
WARNING | 2018-09-08 10:03:31,763 | cle.relocations | Unknown reloc 4 on AMD64
WARNING | 2018-09-08 10:03:31,766 | cle.relocations | Unknown reloc 9 on AMD64
WARNING | 2018-09-08 10:03:31,774 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
>>> start_state = proj.factory.blank_state(addr = 0x400030)
>>> cfg = proj.analyses.CFGAccurate(context_sensitivity_level=2, fail_fast = True, starts = [0x400030], initial_state = start_state,keep_state = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xu/angr-dev/angr/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/xu/angr-dev/angr/angr/analyses/cfg_accurate.py", line 250, in __init__
    self._analyze()
  File "/home/xu/angr-dev/angr/angr/analyses/forward_analysis.py", line 228, in _analyze
    self._pre_entry_handling(entry_info.entry)
  File "/home/xu/angr-dev/angr/angr/analyses/cfg_accurate.py", line 1098, in _pre_entry_handling
    ins_addr=src_ins_addr, stmt_idx=src_exit_stmt_idx)
  File "/home/xu/angr-dev/angr/angr/analyses/cfg_accurate.py", line 1807, in _update_function_transition_graph
    )._get_block(ret_addr).codenode if ret_addr else None
  File "/home/xu/angr-dev/angr/angr/knowledge/function.py", line 170, in _get_block
    block = self._project.factory.block(addr)
  File "/home/xu/angr-dev/angr/angr/lifter.py", line 158, in lift
    raise AngrMemoryError("No bytes in memory for block starting at %#x." % addr)
angr.errors.AngrMemoryError: No bytes in memory for block starting at 0x400903.
```

**Comment by xiaoxing521** [comment]
The function name can be seen in IDA, but ang can only get sub_XXXX. What is the reason?

```
>>> cfg = proj.analyses.CFGFast()
>>> proj.kb.functions.items()
[(4194304, <Function sub_400000 (0x400000)>), (4194416L, <Function sub_400070 (0x400070)>), (4194462L, <Function sub_40009e (0x40009e)>), (4194565L, <Function sub_400105 (0x400105)>), (4194963L, <Function sub_400293 (0x400293)>), (4194987L, <Function sub_4002ab (0x4002ab)>), (4194996L, <Function sub_4002b4 (0x4002b4)>), (4195010L, <Function sub_4002c2 (0x4002c2)>), (4195037L, <Function sub_4002dd (0x4002dd)>), (4195263L, <Function sub_4003bf (0x4003bf)>), (4195675L, <Function sub_40055b (0x40055b)>), (4195896L, <Function sub_400638 (0x400638)>), (4196120L, <Function sub_400718 (0x400718)>), (4196146L, <Function sub_400732 (0x400732)>), (4196330L, <Function sub_4007ea (0x4007ea)>), (4196366L, <Function sub_40080e (0x40080e)>), (4196800L, <Function sub_4009c0 (0x4009c0)>), (4196805L, <Function sub_4009c5 (0x4009c5)>), (4196981L, <Function sub_400a75 (0x400a75)>), (4197203L, <Function sub_400b53 (0x400b53)>), (4197331L, <Function sub_400bd3 (0x400bd3)>), (4197511L, <Function sub_400c87 (0x400c87)>)]
```
The function name obtained by IDA analysis is as follows：
![image](https://user-images.githubusercontent.com/30718493/45249467-5b497b80-b353-11e8-9329-5b3c9e6890b8.png)

**Comment by ltfish** [comment]
I don't think angr currently supports parsing debugging information from object files, nor does it really support loading object files in general. In this case, it assumes that the function at 0x400030 must exist in the binary you provided, but it's not the case. You may add the support for loading and building a CFG for object files if you want though.

Did you try CFGFast?

**Comment by xiaoxing521** [comment]
The function at 0x400030 exists in the binary file I provided. I tried CFGAccurate and some of the target files are supported, but I can't get the function name in the original file. How do I add support for CFG that loads and builds object files?
