### ISSUE TITLE
fail to handle linux syscall open when target binary is static build + angr BYPASS_UNSUPPORTED_SYSCALL enabled

### ISSUE THREAD

**Issue by fastbins** [angr/angr#120]
run this : 

```
cat > test.c << EOF
#include <fcntl.h>
int main()
{
    int fd = open("/test.c", O_RDONLY);
    close(fd);
    return 0;
}
EOF

gcc -o test test.c -static
mkdir angr-chroot

cat > test.py << EOF
import angr
import simuvex
p = angr.Project('test')
files = {}
state = p.factory.entry_state(fs=files, concrete_fs=True, chroot="angr-chroot/", add_options={"BYPASS_UNSUPPORTED_SYSCALL"})
pg = p.factory.path_group(state)
while 1:
  pg.step()
EOF

python test.py
```

and get this: 

```

ERROR   | 2016-05-26 22:39:56,664 | simuvex.procedures.syscalls | no syscall 63 for arch AMD64
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    pg.step()
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 529, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 341, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 289, in _one_path_step
    successors = a.step(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path.py", line 507, in step
    self._make_sim_run()
  File "/usr/local/lib/python2.7/dist-packages/angr/path.py", line 533, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 112, in sim_run
    return SimProcedures['syscalls']['handler'](state, addr=addr, ret_to=state.ip)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.4.28-py2.7.egg/simuvex/s_procedure.py", line 67, in __init__
    r = run_func(*args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.4.28-py2.7.egg/simuvex/procedures/syscalls/handler.py", line 77, in run
    self._syscall = simuvex.SimProcedures[syscall_lib][self.callname](self.state, ret_to=self.state.regs.ip, convention=cc)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.4.28-py2.7.egg/simuvex/s_procedure.py", line 67, in __init__
    r = run_func(*args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.4.28-py2.7.egg/simuvex/procedures/syscalls/open.py", line 11, in run
    return self.state.posix.open(path, flags)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.4.28-py2.7.egg/simuvex/plugins/posix.py", line 151, in open
    elif self.concrete_fs and not os.path.abspath(name).startswith("/dev"):
  File "/usr/lib/python2.7/posixpath.py", line 367, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.4.28-py2.7.egg/simuvex/s_action_object.py", line 78, in __getattr__
    f = getattr(self.ast, attr)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 806, in __getattr__
    raise AttributeError(a)
AttributeError: startswith
```

the type of "name" is BVV SAO (not str).

**Comment by ltfish** [comment]
The bug is in posix file system implementation in SimuVEX. We will fix it.

> `ERROR   | 2016-05-26 22:39:56,664 | simuvex.procedures.syscalls | no syscall 63 for arch AMD64`

It has nothing to do with the exception you see.

**Comment by iamahuman** [comment]
That's probably the `uname` syscall used by libc initialization. I've encountered that once, too. (I just stubbed it out with fake uname and it worked pretty well)
