### ISSUE TITLE
import angr failed

### ISSUE THREAD

**Issue by futex** [angr/angr#1217]
Hello,
When i import angr i have this error:

`Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/angr/__init__.py", line 12, in <module>
    from .sim_procedure import SimProcedure
  File "/usr/local/lib/python2.7/dist-packages/angr/sim_procedure.py", line 403, in <module>
    from angr.sim_type import SimTypePointer
  File "/usr/local/lib/python2.7/dist-packages/angr/sim_type.py", line 1158, in <module>
    from .state_plugins.view import SimMemView
  File "/usr/local/lib/python2.7/dist-packages/angr/state_plugins/__init__.py", line 3, in <module>
    from .libc import *
  File "/usr/local/lib/python2.7/dist-packages/angr/state_plugins/libc.py", line 271, in <module>
    from angr.sim_state import SimState
  File "/usr/local/lib/python2.7/dist-packages/angr/sim_state.py", line 11, in <module>
    from archinfo import arch_from_id
  File "/usr/local/lib/python2.7/dist-packages/archinfo/__init__.py", line 8, in <module>
    from .arch_amd64    import ArchAMD64
  File "/usr/local/lib/python2.7/dist-packages/archinfo/arch_amd64.py", line 29, in <module>
    class ArchAMD64(Arch):
  File "/usr/local/lib/python2.7/dist-packages/archinfo/arch_amd64.py", line 186, in ArchAMD64
    ks_arch = _keystone.KS_ARCH_X86
AttributeError: 'module' object has no attribute 'KS_ARCH_X86'
`

**Comment by rhelmot** [comment]
You seem to have a module named keystone installed which isn’t the real
keystone library. Do you have any idea why this would be?

**Comment by futex** [comment]
I have only these libs:
`keystone                           13.0.0        
keystoneauth1                      3.4.0         
keystonemiddleware                 4.21.0        
python-keystoneclient              3.15.0        
`
