### ISSUE TITLE
SimSymbolicMemory improperly handling unaligned memory access

### ISSUE THREAD

**Issue by guanleustc** [angr/angr#1227]
*Disclaimer: The angr suite is maintained by a small team of volunteers. While we cannot guarantee any timeliness for fixes and enhancements, we will do our best. For more real-time help with angr, from us and the community, join our [Slack.](http://angr.io/invite/)*

---

**Describe the bug**
Please include a clear and concise description of what the bug is.
_read_from function of SimSymbolicMemory cannot deal with unaligned memory access when multiple items are returned from self.mem.load_objects. For example, assuming memory are 4 byte aligned, when reading from 0x2000479b for 2 bytes, 2 mo starting from 0x20004798 and  0x2000479c are returned. Currently the way handling  "missing bytes at the beginning" has a bug, which leads to list index out of range in _fill_missing. In particular, the end_addr argument becomes -3 when invoking _fill_missing. To address the issue, change the condition from
`last_missing != addr - 1 `
to 
`last_missing > addr - 1`.

**Environment Information**
Many common issues are caused by problems with the local Python environment.
Before submitting, double-check that your versions of all modules in the angr suite (angr, cle, pyvex, ...) are up to date.
Please include the output of `python -m angr.misc.bug_report` here.

> Traceback (most recent call last):
  File "./src/concolic/concolic/peripheral.py", line 210, in hw_read
    simgr.step(step_func = utils.Step_Hook.concolic_step_func)
  File "./src/angr-dev/angr/angr/misc/immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "./src/angr-dev/angr/angr/sim_manager.py", line 341, in step
    successors = self.step_state(state, successor_func, **run_args)
  File "./src/angr-dev/angr/angr/sim_manager.py", line 362, in step_state
    successors = self.successors(state, successor_func, **run_args)
  File "./src/angr-dev/angr/angr/sim_manager.py", line 401, in successors
    return self._project.factory.successors(state, **run_args)
  File "./src/angr-dev/angr/angr/factory.py", line 61, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "./src/angr-dev/angr/angr/engines/hub.py", line 134, in successors
    r = engine.process(state, **kwargs)
  File "./src/angr-dev/angr/angr/engines/vex/engine.py", line 135, in process
    opt_level=opt_level)
  File "./src/angr-dev/angr/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "./src/angr-dev/angr/angr/engines/vex/engine.py", line 185, in _process
    self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
  File "./src/angr-dev/angr/angr/engines/vex/engine.py", line 257, in _handle_irsb
    self._handle_statement(state, successors, stmt)
  File "./src/angr-dev/angr/angr/engines/vex/engine.py", line 363, in _handle_statement
    s_stmt = translate_stmt(stmt, state)
  File "./src/angr-dev/angr/angr/engines/vex/statements/__init__.py", line 29, in translate_stmt
    s.process()
  File "./src/angr-dev/angr/angr/engines/vex/statements/base.py", line 37, in process
    self._execute()
  File "./src/angr-dev/angr/angr/engines/vex/statements/loadg.py", line 17, in _execute
    read_expr = self.state.memory.load(addr.expr, read_size, endness=self.stmt.end, condition=guard.expr != 0)
  File "./src/angr-dev/angr/angr/storage/memory.py", line 760, in load
    events=not disable_actions, ret_on_segv=ret_on_segv)
  File "./src/angr-dev/angr/angr/state_plugins/symbolic_memory.py", line 539, in _load
    read_value = self._read_from(addrs[0], size, inspect=inspect, events=events)
  File "./src/angr-dev/angr/angr/state_plugins/symbolic_memory.py", line 491, in _read_from
    fill_mo = self._fill_missing(start_addr, end_addr, inspect=inspect, events=events)
  File "./src/angr-dev/angr/angr/state_plugins/symbolic_memory.py", line 455, in _fill_missing
    b = self.state.se.Concat(*all_missing) if len(all_missing) > 1 else all_missing[0]
IndexError: list index out of range

**To Reproduce**
Please include *both a script to reproduce the crash, and attach the binary used, if possible*

**Additional context**

**Comment by rhelmot** [comment]
I can't reproduce this issue, can you please provide some sort of script to trigger the crash?

**Comment by rhelmot** [comment]
Okay!!! That took forever, but I finally reproduced your issue. This is actually not an issue in the place you've patched it, since `load_objects` is supposed to have the invariant that none of the objects it returns should have `mo_addr < addr`. I actually couldn't reproduce it because this is actually a bug in `TreePage`, which is not the default page implementation, for not maintaining this invariant. I'll push a fix soon.

**Comment by rhelmot** [comment]
In the future: you _really_ need to provide a testcase to reproduce. If it's caused by some other tool, you need to isolate what feature of the tool is doing it and then write a script that exercises angr in that capacity without the tool.

**Comment by guanleustc** [comment]
Sorry about that. 

If the invariant holds, my fix is not necessary. And yes, I used `TreePage` which should be the root cause. Should you insert an assert about the invariant (`assert(mo_addr >= addr)`) so that new users can quickly identify the root cause?

**Comment by rhelmot** [comment]
Yep - for sure. I've added a help-wanted issue for this, since this sort of thing would be great for introducing someone to angr.
