### ISSUE TITLE
When call VFG analysis, an error raises

### ISSUE THREAD

**Issue by winter2020** [angr/angr#1248]
**Describe the bug**

When call VFG analysis an "AttributeError" raises

**Environment Information**

```
angr environment report
=============================
Date: 2018-10-12 12:24:14.561294
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
######## angr #########
Python found it in /usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr
Pip version angr 8.18.10.5
Couldn't find git info
######## ailment #########
Python found it in /home/wgh/.local/lib/python3.5/site-packages/ailment
Pip version ailment 8.18.10.5
Couldn't find git info
######## cle #########
Python found it in /usr/local/lib/python3.5/dist-packages/cle-8.18.10.5-py3.5.egg/cle
Pip version cle 8.18.10.5
Couldn't find git info
######## pyvex #########
Python found it in /home/wgh/.local/lib/python3.5/site-packages/pyvex
Pip version pyvex 8.18.10.5
Couldn't find git info
######## claripy #########
Python found it in /home/wgh/.local/lib/python3.5/site-packages/claripy
Pip version claripy 8.18.10.5
Couldn't find git info
######## archinfo #########
Python found it in /home/wgh/.local/lib/python3.5/site-packages/archinfo
Pip version archinfo 8.18.10.5
Couldn't find git info
######## ana #########
Python found it in /home/wgh/.local/lib/python3.5/site-packages/ana
Pip version ana 0.5
Couldn't find git info
######## z3 #########
Python found it in /home/wgh/.local/lib/python3.5/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/wgh/.local/lib/python3.5/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
unicorn: <CDLL '/home/wgh/.local/lib/python3.5/site-packages/unicorn/lib/libunicorn.so', handle 2148920 at 0x7fc427469198>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fc4286460f0>
angr: <CDLL '/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/lib/angr_native.so', handle 269b180 at 0x7fc425b7eda0>
z3: <CDLL '/home/wgh/.local/lib/python3.5/site-packages/z3/lib/libz3.so', handle 31b11e0 at 0x7fc4242e6358>
```

**To Reproduce**

```
#!/usr/bin/env python
import os
import sys 
import time
import logging


import nose
import angr
import claripy


def check(binary_path):
    proj = angr.Project(binary_path, use_sim_procedures=True, default_analysis_mode='symbolic_approximating', auto_load_libs=False)
    cfg = proj.analyses.CFGEmulated(keep_state=True, context_sensitivity_level=2)
    entry_node = cfg.get_any_node(proj.entry)
    vfg = proj.analyses.VFG(cfg, function_start=proj.entry, context_sensitivity_level=2, interfunction_level=4, remove_options={angr.options.OPTIMIZE_IR})


if __name__ == '__main__':
    test_program = './test'
    if len(sys.argv) > 1:  
        test_program = sys.argv[1]

    if  not os.path.isfile(test_program):
        print ('File %s does not exist!' %test_program)
        exit(0)

    check(test_program)
```

```
Traceback (most recent call last):
  File "checker.py", line 29, in <module>
    check(test_program)
  File "checker.py", line 17, in check
    vfg = proj.analyses.VFG(cfg, function_start=proj.entry, context_sensitivity_level=2, interfunction_level=4, remove_options={angr.options.OPTIMIZE_IR})
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/analyses/vfg.py", line 359, in __init__
    self._analyze()
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/analyses/forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/analyses/forward_analysis.py", line 662, in _analysis_core_baremetal
    self._pre_job_handling(job_info.job)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/analyses/vfg.py", line 654, in _pre_job_handling
    job.sim_successors, _, restart_analysis = self._get_simsuccessors(input_state, addr)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/analyses/vfg.py", line 1338, in _get_simsuccessors
    sim_successors = self.project.factory.successors(state, jumpkind=jumpkind, num_inst=num_inst)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/factory.py", line 48, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/engines/hook.py", line 51, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/engines/procedure.py", line 31, in process
    force_addr=force_addr)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/engines/procedure.py", line 65, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/sim_procedure.py", line 173, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/procedures/glibc/__libc_start_main.py", line 132, in run
    self.call(self.init, (self.argc, self.argv, self.envp), 'after_init')
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/sim_procedure.py", line 356, in call
    cc.setup_callsite(call_state, ret_addr, args)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/calling_conventions.py", line 560, in setup_callsite
    self.return_addr.set_value(state, ret_addr, stack_base=stack_base)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/calling_conventions.py", line 136, in set_value
    state.memory.store(stack_base + self.stack_offset, value, endness=endness, size=value.length//8)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/storage/memory.py", line 556, in store
    self._store(request)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/state_plugins/abstract_memory.py", line 399, in _store
    address_wrappers = self.normalize_address(req.addr, is_write=True, convert_to_valueset=False)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/state_plugins/abstract_memory.py", line 350, in normalize_address
    addr_with_regions = self._normalize_address_type(addr)
  File "/usr/local/lib/python3.5/dist-packages/angr-8.18.10.5-py3.5.egg/angr/state_plugins/abstract_memory.py", line 392, in _normalize_address_type
    return addr_e._model_vsa.items()
  File "/usr/local/lib/python3.5/dist-packages/claripy-8.18.10.5-py3.5.egg/claripy/ast/base.py", line 951, in __getattr__
AttributeError: items
```

**Comment by ltfish** [comment]
Can you please post the binary you were working with?

**Comment by benben2301** [comment]
Just a hello world. 

[test.zip](https://github.com/angr/angr/files/2486155/test.zip)
`#include <stdio.h>

int main() {
    printf("Hello world!");
    return 0;
}
`

**Comment by ZhangZhuoSJTU** [comment]
Similar error when calling `VSA_DDG`
