### ISSUE TITLE
VariableRecovery fails with "AttributeError: value"

### ISSUE THREAD

**Issue by mephi42** [angr/angr#1264]
```
import angr
p = angr.Project('/tmp/a.out')
cfg = p.analyses.CFG()
vr = p.analyses.VariableRecovery(cfg.functions.function(name='main'))
```

for the following code

```
        .globl main
main:
        mov     (%rbx),%rsi
        mov     %rbx,%rdi
        vzeroupper
        callq   *0x8(%rsi)
        mov     %rbp,%rdi
        callq   _Unwind_Resume@plt
```

fails with

```
Traceback (most recent call last):
  File "angr-dev/blah.py", line 4, in <module>
    vr = p.analyses.VariableRecovery(cfg.functions.function(name='main'))
  File "angr-dev/angr/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "angr-dev/angr/angr/analyses/variable_recovery/variable_recovery.py", line 416, in __init__
    self._analyze()
  File "angr-dev/angr/angr/analyses/forward_analysis.py", line 557, in _analyze
    self._analysis_core_graph()
  File "angr-dev/angr/angr/analyses/forward_analysis.py", line 580, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
  File "angr-dev/angr/angr/analyses/variable_recovery/variable_recovery.py", line 461, in _run_on_node
    concrete_state = state.get_concrete_state(node.addr)
  File "angr-dev/angr/angr/analyses/variable_recovery/variable_recovery.py", line 62, in get_concrete_state
    if s.ip._model_concrete.value == addr:
  File "angr-dev/claripy/claripy/ast/base.py", line 951, in __getattr__
    raise AttributeError(a)
AttributeError: value
```

**Comment by rhelmot** [comment]
can I have some compilation instructions for that snippet? trying to compile it with gcc does not reproduce your issue, as cfgaccurate is unable to find main.

**Comment by mephi42** [comment]
I just compiled it with gcc. Here is the resulting binary: [angr-1264.tar.gz](https://github.com/angr/angr/files/2494986/angr-1264.tar.gz).
