### ISSUE TITLE
python3 threading issue

### ISSUE THREAD

**Issue by bannsec** [angr/angr#1277]
**Describe the bug**
When attempting to `import angr` from inside gdb compiled with python3, i get the following error:

```
python-interactive
>>> import angrTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/angr/angr-dev/angr/angr/__init__.py", line 41, in <module>
    from .project import *
  File "/home/angr/angr-dev/angr/angr/project.py", line 665, in <module>
    from .factory import AngrObjectFactory
  File "/home/angr/angr-dev/angr/angr/factory.py", line 292, in <module>
    from .sim_manager import SimulationManager
  File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 811, in <module>
    from .exploration_techniques import ExplorationTechnique, Veritesting, Threading, Explorer
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/__init__.py", line 155, in <module>
    from .threading import Threading
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/threading.py", line 2, in <module>
    import concurrent.futures
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

Also note:
```
ldd /opt/binutils-gdb/gdb/gdb
        linux-vdso.so.1 (0x00007ffc5d5a7000)
        libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007efebb729000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007efebb4ff000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efebb2fb000)
        libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0 (0x00007efebac47000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efebaa28000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efeba68a000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007efeba458000)
        libbabeltrace.so.1 => /usr/lib/x86_64-linux-gnu/libbabeltrace.so.1 (0x00007efeba24b000)
        libbabeltrace-ctf.so.1 => /usr/lib/x86_64-linux-gnu/libbabeltrace-ctf.so.1 (0x00007efeb9ffb000)
        libipt.so.1 => /usr/lib/x86_64-linux-gnu/libipt.so.1 (0x00007efeb9de9000)
        libmpfr.so.6 => /usr/lib/x86_64-linux-gnu/libmpfr.so.6 (0x00007efeb9b69000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efeb9778000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efebc273000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007efeb955b000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007efeb9358000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007efeb9042000)
        libdw.so.1 => /usr/lib/x86_64-linux-gnu/libdw.so.1 (0x00007efeb8df6000)
        libelf.so.1 => /usr/lib/x86_64-linux-gnu/libelf.so.1 (0x00007efeb8bdc000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007efeb89d5000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007efeb8754000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007efeb84e2000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007efeb82bc000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007efeb80ac000)
```

This issue does not happen when just importing directly from python.

**Environment Information**
This is from the latest mechaphish docker image:

```
python -m angr.misc.bug_report
angr environment report
=============================
Date: 2018-10-28 22:49:52.628265
Running in virtual environment at /home/angr/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.6 (default, Sep 12 2018, 18:26:19)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
######## angr #########
Python found it in /home/angr/angr-dev/angr/angr
Pip version angr 8.18.10.5
Git info:
        Current commit 61c6fec90f2439838851292283d665f2f6fe7695 from branch master
        Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/ailment
Pip version ailment 8.18.10.5
Couldn't find git info
######## cle #########
Python found it in /home/angr/angr-dev/cle/cle
Pip version cle 8.18.10.5
Git info:
        Current commit 1ec59c9729908d79b0392d95b89bb02e914e54e6 from branch master
        Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/angr/angr-dev/pyvex/pyvex
Pip version pyvex 8.18.10.5
Git info:
        Current commit 4068dd6e93ec4a8ab442d28ad89be5c664551738 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/angr/angr-dev/claripy/claripy
Pip version claripy 8.18.10.5
Git info:
        Current commit 12566a262fcb8791d81d1434f9932e6f53542dd7 from branch master
        Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/angr/angr-dev/archinfo/archinfo
Pip version archinfo 8.18.10.5
Git info:
        Current commit 8f8d8d2eadd4a769e3f85f6deccd27cb9c4fab44 from branch master
        Checked out from remote origin: https://github.com/angr/archinfo
######## ana #########
Python found it in /home/angr/angr-dev/ana/ana
Pip version ana 0.5
Git info:
        Current commit 48657dc6500e33f5818b98003f1f179bfe03e1cc from branch master
        Checked out from remote origin: https://git:@github.com/zardus/ana
######## z3 #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.2
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/angr/angr-dev/angr/angr/lib/angr_native.so', handle 1c91240 at 0x7fc2bbb214a8>
unicorn: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 197b580 at 0x7fc2be90b4a8>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fc2bf85a748>
z3: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 2258db0 at 0x7fc2c263bf28>
```

**To Reproduce**
Easiest way to reproduce would likely be through my `autoPwn` docker image (currently where i'm seeing it). Note, at time of submitting this bug report, the current version is re-building, so you should make sure you have at least version `ba2qivjrzeg3kgnre4hwi4a`

```
sudo docker run -it --rm bannsec/autopwn

$ /opt/binutils-gdb/gdb/gdb
> python-interactive
>>> import angr
```

**Additional context**

**Comment by rhelmot** [comment]
The issue is definitely that somehow you have installed a version of concurrent.futures which is incompatible with python 3. I guess we can remove that dependency since it's just a backport for python 2 (right? I'm pretty sure that's what this is), but in the meantime you should track down who has that version dependency.

**Comment by bannsec** [comment]
I guess so? The weird thing is, it seems the same library should be used by the following:

```
(angr) angr@autopwn:~/.virtualenvs/angr$ python --version
Python 3.6.6
(angr) angr@autopwn:~/.virtualenvs/angr$ python -c "import angr"
```

That loads just fine.

**Comment by rhelmot** [comment]
https://pypi.org/project/futures/

"It should not be installed on Python 3, although there should be no harm in doing so, as the standard library takes precedence over third party libraries."

Something about this is being fucked up by the gdb setup. I wish I could tell who is installing concurrent.futures, but `find -name 'setup.py' | xargs grep futures` in the container yields nothing. Must be one of our/your dependencies.

**Comment by bannsec** [comment]
Yeah i honestly can't find the setup requirement either. And it's in a python 3 virtual env, so pip should get the right (or at least non-python3 broken) version automagically i believe..

Anyway, can we just replace that concurrent.futures Thread stuff in threading.py exploration technique with normal python3 threading?

Side question -- Do you actually see gains from that? With python's threading not really being multi-threading. Seems like you'd want it to actually be multi-processing instead.

**Comment by rhelmot** [comment]
funny story, the threading technique is actually broken right now. see #1032. cc @danse-macabre. You could probably just comment out that import in your install.

The threading technique is nominally designed to see gains in circumstances where the bulk of the execution time is spent in either libvex, z3, or unicorn. Serialization between processes is expensive...
