### ISSUE TITLE
exceptions while run the whitehat_crypto400.py example

### ISSUE THREAD

**Issue by 0xIO007** [angr/angr#13]
I install the angr on a ubuntu 14.04. but while I run the example, it crashed with a exception. 
Please give me some suggestion. Thanks.  

DEBUG:angr.path_group:... path <Path with 26 runs (at 0x438fb0)> didn't match!
DEBUG:angr.path_group:... returning 0 matches and 1 non-matches
DEBUG:angr.path_group:Round 26: stepping <PathGroup with 1 active>
Traceback (most recent call last):
  File "whitehat_crypto400.py", line 57, in <module>
    pg.explore(find=0x4016A3).unstash(from_stash='found', to_stash='active')
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/path_group.py", line 731, in explore
    return self.step(n=n, step_func=explore_step_func, until=until_func, stash=stash)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/path_group.py", line 505, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/path_group.py", line 299, in _one_step
    successors = a.step(**kwargs)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/path.py", line 218, in step
    self._make_sim_run()
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/path.py", line 233, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/factory.py", line 111, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/factory.py", line 57, in sim_block
    **block_opts)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/lifter.py", line 111, in lift
    traceflags=traceflags)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/pyvex/__init__.py", line 106, in __init__
    self.statements = [ IRStmt.IRStmt._translate(c_irsb.stmts[i], self) for i in range(c_irsb.stmts_used) ]
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/pyvex/IRStmt/__init__.py", line 37, in _translate
    return stmt_class(c_stmt, irsb)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/pyvex/IRStmt/__init__.py", line 165, in __init__
    self.mAddr = IRExpr._translate(c_stmt.Ist.Dirty.details.mAddr, irsb)
  File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/pyvex/IRExpr/__init__.py", line 47, in _translate
    if c_expr[0] == ffi.NULL:
RuntimeError: cannot dereference null pointer from cdata 'IRExpr *'
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored

**Comment by 0xIO007** [comment]
File "/home/ahwei/.virtualenvs/angr/local/lib/python2.7/site-packages/pyvex/IRExpr/__init_.py", line 47, in _translate
if c_expr[0] == ffi.NULL:
~~~~~~~~~~~~~~~~~~

change if c_expr[0] == ffi.NULL: 
to if c_expr == ffi.NULL

it's can run with correct result. 
I'm not familiar with python.  I don't know the different between c_expr[0] and c_expr.

**Comment by rhelmot** [comment]
Thanks for tracking that down! I have absolutely no idea why that would have fixed anything, but I've pushed a variant on that change.

@zardus you should figure out if the fact that this happened indicates anything weird going on under the hood in vex or pyvex_c...

**Comment by haowayne** [comment]
Could anyone please explain the meaning of the 'unstash' used in the script? I can't find a specific explanation.

**Comment by rhelmot** [comment]
Unstash is the opposite of stash. Stash is to move some states from active to a given named stash. Unstash is to move them back.

Please open new issues to ask questions, instead of reusing the old issues.
