### ISSUE TITLE
WrTmp object has no attribute 'guard' when do CFGFast()

### ISSUE THREAD

**Issue by Airtnp** [angr/angr#1317]
Angr version:
    angr 8.18.10.25

The testing script:
```python

import os

import angr

test_location = str(os.path.dirname(os.path.realpath(__file__)))


def test():

    path = os.path.join(test_location, "tcpdump")
    p = angr.Project(path, auto_load_libs=False)

    # it should not crash
    _ = p.analyses.CFG()


if __name__ == "__main__":
    test()
```

The backtrace:

```

Traceback (most recent call last):
  File "test_cfg_tcpdump.py", line 19, in <module>
    test()
  File "test_cfg_tcpdump.py", line 15, in test
    _ = p.analyses.CFG()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg.py", line 55, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg_fast.py", line 1013, in __init__
    self._analyze()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/forward_analysis.py", line 653, in _analysis_core_baremetal
    self._job_queue_empty()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg_fast.py", line 1484, in _job_queue_empty
    self._process_unresolved_indirect_jumps()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg_base.py", line 2167, in _process_unresolved_indirect_jumps
    all_targets |= self._process_one_indirect_jump(jump)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg_base.py", line 2193, in _process_one_indirect_jump
    resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 70, in resolve
    max_level=3, base_state=self.base_state)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/blade.py", line 62, in __init__
    self._backward_slice()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/blade.py", line 275, in _backward_slice
    data.get('stmt_idx', None)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/blade.py", line 297, in _backward_slice_recursive
    if type(exit_stmt.guard) is pyvex.IRExpr.RdTmp:
AttributeError: 'WrTmp' object has no attribute 'guard'

```

The binary
[tcpdump.zip](https://github.com/angr/angr/files/2627368/tcpdump.zip)

It seems that the exit_stmt_idx given to _backward_slice_recursive is wrong and happens at address 0x4d594c (the block seems normal without operations like floating or simd)

**Comment by Airtnp** [comment]
https://github.com/angr/angr/issues/1172 seems unrelated to this problem

**Comment by ltfish** [comment]
https://github.com/angr/angr/commit/47fb5aad should have solved this issue. Can you please test the latest version of angr on GitHub?

**Comment by Airtnp** [comment]
Yes after applying this commit the CFG will not generate the error.
