### ISSUE TITLE
Trying to backward slice but getting nothing or a crash

### ISSUE THREAD

**Issue by canpadawan** [angr/angr#1320]
I am trying to backward slice a very simple program.
It took me some time to figure out the right options but I think its ok now and I get good results 
for x86_64. For the same code in aarch64, i get a crash.

I am trying to find what statements contribute to rdi
```asm
0x4004e0:	push	rbp
0x4004e1:	mov	rbp, rsp
0x4004e4:	sub	rsp, 0x20
0x4004e8:	mov	dword ptr [rbp - 0x14], edi
0x4004eb:	mov	qword ptr [rbp - 0x20], rsi
0x4004ef:	mov	qword ptr [rbp - 8], 0x601040
0x4004f7:	mov	rax, qword ptr [rbp - 8]
0x4004fb:	mov	rdi, rax
0x4004fe:	call	0x4004d6
```

We are looking for contribution to statement **35** of the block
```shell
IRSB {
...
   34 | ------ IMark(0x4004fb, 3, 0) ------
   35 | PUT(rdi) = t25
   36 | PUT(rip) = 0x00000000004004fe
}
```

with the following script, I get a crash during cdg building for aarch64 (gcc4.9 uclibc)

```python
import angr

b = angr.Project("test_x86_64", load_options={"auto_load_libs": False})

# trying to identify statements contributes to the value of RDI
IRSB_AD=0x4004e0
block = b.factory.block(IRSB_AD)
block.pp()
block.vex.pp()

cfg = b.analyses.CFGEmulated(context_sensitivity_level=2, keep_state=True, state_add_options=angr.sim_options.refs)
cdg = b.analyses.CDG(cfg)
ddg = b.analyses.DDG(cfg)
bs = b.analyses.BackwardSlice(cfg, cdg=cdg, ddg=ddg,
                              targets=[(cfg.get_any_node(IRSB_AD), 35)])
print("using BackwardSlice:\n%s" % bs.dbg_repr_run(IRSB_AD))

b = angr.Project("test_aarch64", load_options={"auto_load_libs": False})
cfg = b.analyses.CFGEmulated(context_sensitivity_level=2, keep_state=True, state_add_options=angr.sim_options.refs)
cdg = b.analyses.CDG(cfg)
# crashes in cdg
```

[The 2 testfiles are here](https://github.com/angr/angr/files/2649390/test_files.zip)

```shell
using BackwardSlice:
0x4004e0
-[  0] ------ IMark(0x4004e0, 1, 0) ------
-[  1] t0 = GET:I64(offset=56)
+[  2] t12 = GET:I64(offset=48)
+[  3] t11 = Sub64(t12,0x0000000000000008)
-[  4] PUT(offset=48) = t11
-[  5] STle(t11) = t0
-[  6] ------ IMark(0x4004e1, 3, 0) ------
-[  7] PUT(offset=56) = t11
-[  8] ------ IMark(0x4004e4, 4, 0) ------
-[  9] t2 = Sub64(t11,0x0000000000000020)
-[ 10] PUT(offset=144) = 0x0000000000000008
-[ 11] PUT(offset=152) = t11
-[ 12] PUT(offset=160) = 0x0000000000000020
-[ 13] PUT(offset=48) = t2
-[ 14] PUT(offset=184) = 0x00000000004004e8
-[ 15] ------ IMark(0x4004e8, 3, 0) ------
-[ 16] t14 = Add64(t11,0xffffffffffffffec)
-[ 17] t17 = GET:I64(offset=72)
-[ 18] t16 = 64to32(t17)
-[ 19] STle(t14) = t16
-[ 20] PUT(offset=184) = 0x00000000004004eb
-[ 21] ------ IMark(0x4004eb, 4, 0) ------
-[ 22] t18 = Add64(t11,0xffffffffffffffe0)
-[ 23] t20 = GET:I64(offset=64)
-[ 24] STle(t18) = t20
-[ 25] PUT(offset=184) = 0x00000000004004ef
-[ 26] ------ IMark(0x4004ef, 8, 0) ------
+[ 27] t21 = Add64(t11,0xfffffffffffffff8)
+[ 28] STle(t21) = 0x0000000000601040
-[ 29] PUT(offset=184) = 0x00000000004004f7
-[ 30] ------ IMark(0x4004f7, 4, 0) ------
+[ 31] t23 = Add64(t11,0xfffffffffffffff8)
+[ 32] t25 = LDle:I64(t23)
-[ 33] PUT(offset=16) = t25
-[ 34] ------ IMark(0x4004fb, 3, 0) ------
+[ 35] PUT(offset=72) = t25
-[ 36] PUT(offset=184) = 0x00000000004004fe
-[ 37] ------ IMark(0x4004fe, 5, 0) ------
-[ 38] t27 = Sub64(t2,0x0000000000000008)
-[ 39] PUT(offset=48) = t27
-[ 40] STle(t27) = 0x0000000000400503
-[ 41] t29 = Sub64(t27,0x0000000000000080)
-[ 42] ====== AbiHint(0xt29, 128, 0x00000000004004d6) ======
Chosen exits: default

...
Traceback (most recent call last):
  File "../networkx/classes/digraph.py", line 794, in successors
    return iter(self._succ[n])
KeyError: <angr.utils.graph.ContainerNode object at 0x7fd4f68da438>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test_backward.py", line 23, in <module>
    cdg = b.analyses.CDG(cfg)
  File "..angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "..angr/analyses/cdg.py", line 42, in __init__
    self._construct()
  File "..angr/analyses/cdg.py", line 101, in _construct
    self._pd_construct()
  File "..angr/analyses/cdg.py", line 148, in _pd_construct
    pdoms = PostDominators(self._acyclic_cfg, self._entry, successors_func=self._pd_graph_successors)
  File "..angr/utils/graph.py", line 174, in __init__
    self._construct(graph, entry_node)
  File "..angr/utils/graph.py", line 204, in _construct
    _prepared_graph, vertices, parent = self._prepare_graph(graph, entry_node)
  File "..angr/utils/graph.py", line 322, in _prepare_graph
    successors = new_graph.successors(node)
  File "../networkx/classes/digraph.py", line 796, in successors
    raise NetworkXError("The node %s is not in the digraph." % (n,))
networkx.exception.NetworkXError: The node <angr.utils.graph.ContainerNode object at 0x7fd4f68da438> is not in the digraph.

```

**Comment by canpadawan** [comment]
No, the PR was just to align the doc with the code.
