### ISSUE TITLE
CFGFast incurs AssertionError & ClaripyBackendError

### ISSUE THREAD

**Issue by Airtnp** [angr/angr#1329]
**Version**
https://github.com/angr/angr/commit/cf5374a554615242dd4fd92964c20920d7a9ffe4

**Test program**
```python
import os

import angr
from angr import SimProcedure
from angr.procedures import SIM_LIBRARIES, SIM_PROCEDURES

test_location = str(os.path.dirname(os.path.realpath(__file__)))


# A wrong implementation of this function. But why CFGFast asks for successors of this SimProcedure?
class __underflow(SimProcedure):
    def run(self, file_ptr):
        ch = '\n'
        self.inline_call(SIM_PROCEDURES['libc']['fputc'], ch, file_ptr)
        return self.state.solver.Unconstrained('__underflow', 32, uninitialized=False)


def test():
    path = os.path.join(test_location, "libc-2.27.so")
    p = angr.Project(path, auto_load_libs=False)
    # p.hook_symbol('__underflow', __underflow()) // uncomment will cause ClaripyBackendError
    # it should not crash
    _ = p.analyses.CFGFast(show_progressbar=True)


if __name__ == "__main__":
    test()
```

**binary**
[libc-2.27.zip](https://github.com/angr/angr/files/2668502/libc-2.27.zip)

## AssertionError

**Stacktrace**
```
Traceback (most recent call last):
  File "test_cfg_hook.py", line 27, in <module>
    test()
  File "test_cfg_hook.py", line 23, in test
    _ = p.analyses.CFGFast(show_progressbar=True)
  File "/home/lrxiao/hase/venv/lib/python3.6/site-packages/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/lrxiao/hase/venv/lib/python3.6/site-packages/angr/analyses/cfg/cfg_fast.py", line 1026, in __init__
    self._analyze()
  File "/home/lrxiao/hase/venv/lib/python3.6/site-packages/angr/analyses/forward_analysis.py", line 559, in _analyze
    self._post_analysis()
  File "/home/lrxiao/hase/venv/lib/python3.6/site-packages/angr/analyses/cfg/cfg_fast.py", line 1531, in _post_analysis
    self.make_functions()
  File "/home/lrxiao/hase/venv/lib/python3.6/site-packages/angr/analyses/cfg/cfg_base.py", line 1437, in make_functions
    blockaddr_to_function
  File "/home/lrxiao/hase/venv/lib/python3.6/site-packages/angr/analyses/cfg/cfg_base.py", line 1741, in _process_irrational_function_starts
    self._merge_cfgnodes(cfgnode_0, cfgnode_1)
  File "/home/lrxiao/hase/venv/lib/python3.6/site-packages/angr/analyses/cfg/cfg_base.py", line 526, in _merge_cfgnodes
    assert cfgnode_0.addr + cfgnode_0.size == cfgnode_1.addr
AssertionError
```

It works well in 8.18.10.25

## ClaripyBackendError

**Stacktrace**
```

Traceback (most recent call last):         | Elapsed Time: 0:00:53 ETA:  0:01:29
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/frontends/light_frontend.py", line 40, in eval
    return tuple(self._solver_backend.eval(e, n))
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 447, in eval
    self.convert(expr), n, extra_constraints=self.convert_list(extra_constraints),
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 160, in convert
    r = self.call(expr.op, expr.args)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 194, in call
    converted = self.convert_list(args)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 182, in convert_list
    return [ self.convert(a) for a in args ]
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 182, in <listcomp>
    return [ self.convert(a) for a in args ]
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 160, in convert
    r = self.call(expr.op, expr.args)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 194, in call
    converted = self.convert_list(args)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 182, in convert_list
    return [ self.convert(a) for a in args ]
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 182, in <listcomp>
    return [ self.convert(a) for a in args ]
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 179, in convert
    return self._convert(expr)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/backend_concrete.py", line 87, in _convert
    raise BackendError("can't handle AST of type %s" % type(a))
claripy.errors.BackendError: can't handle AST of type <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 85, in wrapped_f
    return f(*args, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 478, in _eval
    return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/frontend_mixins/concrete_handler_mixin.py", line 7, in eval
    return super(ConcreteHandlerMixin, self).eval(e, n, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 40, in eval
    return super(ConstraintFilterMixin, self).eval(e, n, extra_constraints=ec, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/frontends/light_frontend.py", line 42, in eval
    raise ClaripyFrontendError("Light solver can't handle this eval().")
claripy.errors.ClaripyFrontendError: Light solver can't handle this eval().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/posix.py", line 311, in get_fd
    fd = self.state.solver.eval_one(fd)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 718, in eval_one
    return self.eval_exact(e, 1, **{k: v for (k, v) in kwargs.items() if k != 'default'})[0]
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 769, in eval_exact
    r = self.eval_upto(e, n + 1, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 686, in eval_upto
    cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 152, in concrete_shortcut_tuple
    return f(self, *args, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/sim_action_object.py", line 55, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 89, in wrapped_f
    raise SimSolverModeError("Claripy threw an error") from e
angr.errors.SimSolverModeError: Claripy threw an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 288, in is_false
    return self._false_cache[e.cache_key]
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/weakref.py", line 394, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f161d270ae8; to 'ASTCacheKey' at 0x7f161d2d69e8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_cfg_hook.py", line 27, in <module>
    test()
  File "test_cfg_hook.py", line 23, in test
    _ = p.analyses.CFGFast(show_progressbar=True)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg_fast.py", line 1013, in __init__
    self._analyze()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/forward_analysis.py", line 559, in _analyze
    self._post_analysis()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg_fast.py", line 1510, in _post_analysis
    self.make_functions()
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg_base.py", line 1375, in make_functions
    blockaddr_to_function
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/analyses/cfg/cfg_base.py", line 1553, in _process_irrational_functions
    b = self.project.factory.successors(tmp_state, jumpkind='Ijk_Boring')
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/factory.py", line 49, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/engines/hook.py", line 51, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/engines/procedure.py", line 31, in process
    force_addr=force_addr)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/engines/procedure.py", line 65, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/sim_procedure.py", line 174, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "test_cfg_hook.py", line 14, in run
    self.inline_call(SIM_PROCEDURES['libc']['fputc'], ch, file_ptr)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/sim_procedure.py", line 289, in inline_call
    return p.execute(self.state, None, arguments=e_args)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/sim_procedure.py", line 174, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/procedures/libc/fputc.py", line 15, in run
    simfd = self.state.posix.get_fd(fileno)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/posix.py", line 315, in get_fd
    if not self.state.solver.satisfiable():
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/sim_action_object.py", line 55, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 85, in wrapped_f
    return f(*args, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/angr/state_plugins/solver.py", line 619, in satisfiable
    return self._solver.satisfiable(extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 34, in satisfiable
    return super(ConstraintFilterMixin, self).satisfiable(extra_constraints=ec, **kwargs)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/frontends/light_frontend.py", line 85, in satisfiable
    reversed(self.constraints + list(extra_constraints))
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/frontends/light_frontend.py", line 84, in <genexpr>
    self._solver_backend.is_false(c) for c in
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 290, in is_false
    f = self._is_false(self.convert(e), extra_constraints=extra_constraints, solver=solver, model_callback=model_callback)
  File "/home/lrxiao/.pyenv/versions/3.6.1/lib/python3.6/site-packages/claripy/backends/__init__.py", line 152, in convert
    raise BackendError("%s can't handle operation %s (%s) due to a failed conversion on a child node" % (self, expr.op, expr.__class__.__name__))
claripy.errors.BackendError: <claripy.backends.backend_concrete.BackendConcrete object at 0x7f162d3b3400> can't handle operation __eq__ (Bool) due to a failed conversion on a child node
```

It doesn't work well even in 8.18.10.25. Seems the CFGFast asks for successors of a SimProcedure. Hook must be added after calling CFG?

**Comment by ltfish** [comment]
This is a different problem. Will get to this later today. Thanks for reporting!

**Comment by benben2301** [comment]
Encounter same AssertionError.

**Comment by ltfish** [comment]
You'll need PR #1334, #1335, #1336, and #1337. I will merge them in after they pass CI.

**Comment by ltfish** [comment]
I'm going to close this issue as it should have been resolved in the latest version of angr on GitHub. However, the attempt to resolve more jump tables in libc is making CFG generation much slower than before (on my laptop, it now takes 11 min, while taking 1.5 min before). I will profile jump table recovery in the next few days.
