### ISSUE TITLE
angr.errors.SimEngineError: No bytes in memory for block starting at 0x3000002.

### ISSUE THREAD

**Issue by benben2301** [angr/angr#1333]
When constructing CFG by CFGFast, encounter SimEngineError:

```
Traceback (most recent call last):
  File "cfg_fast.py", line 61, in <module>
    analyze(sys.argv[1])
  File "cfg_fast.py", line 30, in analyze
    cfg = proj.analyses.CFGFast()
  File "/home/wgh/angr-dev/angr/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/wgh/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1026, in __init__
    self._analyze()
  File "/home/wgh/angr-dev/angr/angr/analyses/forward_analysis.py", line 559, in _analyze
    self._post_analysis()
  File "/home/wgh/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1531, in _post_analysis
    self.make_functions()
  File "/home/wgh/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1439, in make_functions
    blockaddr_to_function
  File "/home/wgh/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1711, in _process_irrational_function_starts
    if block.vex.jumpkind not in ('Ijk_Boring', 'Ijk_InvalICache'):
  File "/home/wgh/angr-dev/angr/angr/block.py", line 152, in vex
    collect_data_refs=self._collect_data_refs,
  File "/home/wgh/angr-dev/angr/angr/engines/vex/engine.py", line 568, in lift
    raise SimEngineError("No bytes in memory for block starting at %#x." % addr)
angr.errors.SimEngineError: No bytes in memory for block starting at 0x3000002.

```
Python code:
```
#!/usr/bin/env python
import os
import sys
import angr
import claripy

def analyze(binary_path):
    proj = angr.Project(binary_path, use_sim_procedures=True, default_analysis_mode='symbolic', auto_load_libs=False)

    # CFG construction: fast
    cfg = proj.analyses.CFGFast()

    # VFG construction
    vfg = proj.analyses.VFG(cfg=cfg)

if __name__ == '__main__':
    analyze(sys.argv[1])
```
[gcc_base.zip](https://github.com/angr/angr/files/2678613/gcc_base.zip)

**Comment by ltfish** [comment]
PR #1335 fixes this bug. It will be merged in after CI passes.
