### ISSUE TITLE
FunctionDict only supports int as key type

### ISSUE THREAD

**Issue by benben2301** [angr/angr#1353]
Key type error during CFGEmulate
```
Traceback (most recent call last):
  File "/home/wgh/angr-dev/angr/angr/knowledge_plugins/functions/function_manager.py", line 25, in __getitem__
    return super(FunctionDict, self).__getitem__(addr)
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cfg_emul.py", line 62, in <module>
    analyze(sys.argv[1])
  File "cfg_emul.py", line 27, in analyze
    cfg = proj.analyses.CFGEmulated(keep_state=False, initial_state= entry_state, enable_advanced_backward_slicing=False, context_sensitivity_level=0)
  File "/home/wgh/angr-dev/angr/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/wgh/angr-dev/angr/angr/analyses/cfg/cfg_emulated.py", line 300, in __init__
    self._analyze()
  File "/home/wgh/angr-dev/angr/angr/analyses/forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "/home/wgh/angr-dev/angr/angr/analyses/forward_analysis.py", line 677, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/wgh/angr-dev/angr/angr/analyses/forward_analysis.py", line 695, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/home/wgh/angr-dev/angr/angr/analyses/cfg/cfg_emulated.py", line 1404, in _get_successors
    self._handle_job_without_successors(job, the_irsb, insn_addrs)
  File "/home/wgh/angr-dev/angr/angr/analyses/cfg/cfg_emulated.py", line 1853, in _handle_job_without_successors
    stmt_idx='default',
  File "/home/wgh/angr-dev/angr/angr/analyses/cfg/cfg_emulated.py", line 2018, in _update_function_transition_graph
    stmt_idx=stmt_idx,
  File "/home/wgh/angr-dev/angr/angr/knowledge_plugins/functions/function_manager.py", line 106, in _add_call_to
    dest_func = self._function_map[to_addr]
  File "/home/wgh/angr-dev/angr/angr/knowledge_plugins/functions/function_manager.py", line 28, in __getitem__
    raise TypeError("FunctionDict only supports int as key type")
TypeError: FunctionDict only supports int as key type

```

```
#!/usr/bin/env python
import sys 
import angr


def analyze(binary_path):
    proj = angr.Project(binary_path, use_sim_procedures=True, default_analysis_mode='symbolic', auto_load_libs=False)
    cfg = proj.analyses.CFGEmulated(keep_state=False, enable_advanced_backward_slicing=False, context_sensitivity_level=0)

if __name__ == '__main__':
   analyze(sys.argv[1])

```

[test_xxx.zip](https://github.com/angr/angr/files/2694222/test_xxx.zip)

**Comment by twizmwazin** [comment]
No longer relevant
