### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'spec_type'

### ISSUE THREAD

**Issue by cajun-rat** [angr/angr#1383]
**Describe the bug**

I'm getting the following crash when trying to run angr against a json parser:

```
python run.py 
WARNING | 2019-01-07 15:57:54,335 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2019-01-07 15:57:55,667 | angr.state_plugins.symbolic_memory | Register r15 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:57:55,668 | angr.state_plugins.symbolic_memory | Register r14 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:57:55,670 | angr.state_plugins.symbolic_memory | Register r13 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:57:55,671 | angr.state_plugins.symbolic_memory | Register r12 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:57:55,674 | angr.state_plugins.symbolic_memory | Register rbx has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:57:55,711 | angr.state_plugins.symbolic_memory | Register cc_ndep has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:59:00,198 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:00,583 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb69 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:00,613 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb99 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:06,698 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffeff40 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:59:06,701 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb09 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:07,417 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:07,941 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,190 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,207 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,229 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffeff40 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:59:08,232 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefad9 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:08,256 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffeff40 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:59:08,258 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb09 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:08,276 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,293 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,311 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffeff40 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:59:08,313 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb59 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:08,343 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,370 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,391 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,686 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,706 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,737 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:08,855 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb69 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:08,892 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb99 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:09,023 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:09,379 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:10,060 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb69 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:10,078 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb99 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:20,144 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefba9 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:23,665 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffeff40 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:59:23,667 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb09 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:23,770 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:24,291 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb69 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:24,334 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb99 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:24,746 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffeff40 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:59:24,749 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefb09 has an unspecified value; Generating an unconstrained value of 1 bytes.
WARNING | 2019-01-07 15:59:24,845 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:25,379 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefc24 has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-07 15:59:25,401 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffeff40 has an unspecified value; Generating an unconstrained value of 8 bytes.
WARNING | 2019-01-07 15:59:25,403 | angr.state_plugins.symbolic_memory | Memory address 0x7fffffffffefad9 has an unspecified value; Generating an unconstrained value of 1 bytes.
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    simgr.explore(find=local_assert.rebased_addr)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 238, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/exploration_techniques/explorer.py", line 97, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 382, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 421, in successors
    return self._project.factory.successors(state, **run_args)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/factory.py", line 49, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/engines/hook.py", line 51, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/engines/procedure.py", line 31, in process
    force_addr=force_addr)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/engines/procedure.py", line 65, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/sim_procedure.py", line 174, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/procedures/libc/sscanf.py", line 21, in run
    items = fmt_str.interpret(2, self.arg, addr=data)
  File "angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/procedures/stubs/format_parser.py", line 232, in interpret
    if fmt_spec.spec_type == b's':
AttributeError: 'bytes' object has no attribute 'spec_type'
```

I'm new to angr, so I might be doing something 'odd' with it. My code does the following:

```
proj = angr.Project('./test')
initial_state = proj.factory.entry_state(args=["./test"],
                                         remove_options={angr.options.LAZY_SOLVES})
local_assert = proj.loader.find_symbol('local_assert')
simgr = proj.factory.simulation_manager(initial_state)
simgr.explore(find=local_assert.rebased_addr)
```
**Environment Information**

angr environment report
=============================
Date: 2019-01-07 16:01:55.098408
Running in virtual environment at angr-playground/ex1-json/venv
Platform: linux-x86_64
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
######## angr #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr
Pip version angr 8.18.10.25
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######## ailment #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/ailment
Pip version ailment 8.18.10.25
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######## cle #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/cle
Pip version cle 8.18.10.25
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######## pyvex #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/pyvex
Pip version pyvex 8.18.10.25
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######## claripy #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/claripy
Pip version claripy 8.18.10.25
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######## archinfo #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/archinfo
Pip version archinfo 8.18.10.25
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######## ana #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/ana
Pip version ana 0.5
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######## z3 #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/z3
Pip version not found!
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######## unicorn #########
Python found it in angr-playground/ex1-json/venv/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.1
Git info:
	Current commit 362b3e4ae3caf0197aebc1c1ed609a8592b89cde from branch master
	Checked out from remote origin: git@github.com:cajun-rat/angr-playground.git
######### Native Module Info ##########
angr: <CDLL 'angr-playground/ex1-json/venv/lib/python3.6/site-packages/angr/lib/angr_native.so', handle 22c95b0 at 0x7fe0f5115438>
unicorn: <CDLL 'angr-playground/ex1-json/venv/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 1ed3130 at 0x7fe0fa54ccc0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fe0f8bb0f98>
z3: <CDLL 'angr-playground/ex1-json/venv/lib/python3.6/site-packages/z3/lib/libz3.so', handle 28cf660 at 0x7fe0f33c7278>

**To Reproduce**

```
git clone https://github.com/cajun-rat/angr-playground.git
cd angr-playground/ex1-json
python3 -m venv venv
. venv/bin/activate
pip install -r ../requirements.txt 
python3 run.py
=> AttributeError: 'bytes' object has no attribute 'spec_type'
```

The `test` binary was compiled from `test.cc` using gcc (both are included in https://github.com/cajun-rat/angr-playground/tree/master/ex1-json)

**Comment by rhelmot** [comment]
I believe this has been fixed on master but not released yet. I will
investigate more this afternoon.

**Comment by rhelmot** [comment]
Okay, yeah: this was fixed by https://github.com/angr/angr/pull/1258

**Comment by cajun-rat** [comment]
Thank you!  Do you want that example as a test case?

**Comment by rhelmot** [comment]
That would be fine, if you could rig it up so it's slightly more targeted than "run symbolic execution".

**Comment by cajun-rat** [comment]
I'm a total beginner with angr, so maybe I'll leave the test-case generation until I understand what is going on.  I retested and can confirm that this bug is fixed on current master. Cheers :)
