### ISSUE TITLE
 Igot  TypeError: copy() got an unexpected keyword argument 'stashes'

### ISSUE THREAD

**Issue by cbwang505** [angr/angr#1384]
i compilied the exe with this source code ,and run the test with these error,i  i use python 2.7 with angr  7.8.9.26,how to resolve this problem
```
#include "stdafx.h"
#include "string.h"

void success(){
	printf("success\n");
}
void failed(){
	printf("failed\n");
}
void next(char *pwd){
	if (!strcmp(pwd, "123456")){
		success();
	}
	else{
		failed();
	}
}

int _tmain(int argc, _TCHAR* argv[])
{
	
	printf("please input n\n");
	puts("this is puts\n");
	if (argc < 2)
	{
		failed();
		return 0;
	}
	if (!strcmp(argv[1], "jsk")){
		success();
	}
	else{
		failed();
	}
	return 0;

}
```
```
import angr
import claripy
from angr import *
import logging
import archinfo
logging.getLogger('angr.manager').setLevel(logging.DEBUG)
main_opts = {'custom_base_addr': 0x00400000, 'custom_entry_point': 0x0041111D}
p = Project("E:\\git\\vsprj\\ConsoleApplication2\\Debug\\ConsoleApplication2.exe",auto_load_libs=False, main_opts=main_opts)
# args = [ p.filename,claripy.BVS('arg1', 8)]
args = [ p.filename,'jsk']
state=p.factory.entry_state(args=args)
sm=p.factory.simulation_manager(state,threads=40)
sm.use_technique(angr.exploration_techniques.Oppologist())
res=sm.explore(find=0x004114F0,avoid=[0x00413414])
if len(res.found) > 0:
    print sm.found[0].solver.eval(args, cast_to=str)
```
```
C:\python27-x64\python.exe E:/git/PythonWorkSpace/test.py
WARNING | 2019-01-08 15:49:12,667 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
Traceback (most recent call last):
  File "E:/git/PythonWorkSpace/test.py", line 14, in <module>
    res=sm.explore(find=0x004114F0,avoid=[0x00413414])
  File "C:\python27-x64\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\python27-x64\lib\site-packages\angr\sim_manager.py", line 238, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\python27-x64\lib\site-packages\angr\sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\misc\hookset.py", line 57, in __call__
    result = next_hook(self.func.im_self, *args, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\exploration_techniques\explorer.py", line 99, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\misc\hookset.py", line 57, in __call__
    result = next_hook(self.func.im_self, *args, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\exploration_techniques\threading.py", line 32, in step
    tsimgr = simgr.copy(stashes=dict(simgr.stashes))
TypeError: copy() got an unexpected keyword argument 'stashes'

Process finished with exit code 1
```

**Comment by ltfish** [comment]
I think there is already an open issue for this bug, see https://github.com/angr/angr/issues/1032. I'll probably look into this issue later since it has been broken for a very long time.

Also, we have stopped supporting angr 7 since (roughly) a year ago. You should consider switching to Python 3 and angr 8.

**Comment by ltfish** [comment]
For now, you can disable multi-threading support in SimulationManager (don't specify `threads=40`).
