### ISSUE TITLE
cannot run test TypeError: <BV64 GetTickCount64_result_5_64> doesn't fit in an argument of size 4

### ISSUE THREAD

**Issue by cbwang505** [angr/angr#1387]
```
import nose
import angr
import claripy
from archinfo import ArchX86

import os




class StdcallStub1Arg(angr.SimProcedure):
    def run(self, arg1):
        return 0

def test_i386():
    after_puts = 0x40105b
    else_paths = [0x401062, 0x401009]

    p = angr.Project("D:\\dl\\simple_windows.exe", auto_load_libs=True)
    # p.hook_symbol("GetTickCount64", StdcallStub1Arg(cc=angr.calling_conventions.SimCCStdcall(ArchX86()),
    #     display_name="GetTickCount64"), replace=True) # stubbed until 64 bit return works

    s = p.factory.entry_state(args=( p.filename, "angr_can_windows?", claripy.BVS('arg1',64*8)))
    simgr = p.factory.simulation_manager(s)
    simgr.explore(find=after_puts, avoid=else_paths, num_find=1)
    nose.tools.assert_equal(len(simgr.avoid), 0)
    nose.tools.assert_greater(len(simgr.found), 0)
    for f in simgr.found:
        print f.posix.dumps(1)


if __name__ == "__main__":
    test_i386()
C:\python27-x64\python.exe E:/git/PythonWorkSpace/wintest.py
WARNING | 2019-01-08 16:56:24,684 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
C:\python27-x64\lib\site-packages\cle\loader.py:848: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if ilibname.strip('.0123456789') == spec.strip('.0123456789'):
Traceback (most recent call last):
  File "E:/git/PythonWorkSpace/wintest.py", line 33, in <module>
    test_i386()
  File "E:/git/PythonWorkSpace/wintest.py", line 25, in test_i386
    simgr.explore(find=after_puts, avoid=else_paths, num_find=1)
  File "C:\python27-x64\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\python27-x64\lib\site-packages\angr\sim_manager.py", line 238, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\python27-x64\lib\site-packages\angr\sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\misc\hookset.py", line 57, in __call__
    result = next_hook(self.func.im_self, *args, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\exploration_techniques\explorer.py", line 99, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\misc\hookset.py", line 60, in __call__
    result = self.func(*args, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\python27-x64\lib\site-packages\angr\sim_manager.py", line 341, in step
    successors = self.step_state(state, successor_func, **run_args)
  File "C:\python27-x64\lib\site-packages\angr\sim_manager.py", line 362, in step_state
    successors = self.successors(state, successor_func, **run_args)
  File "C:\python27-x64\lib\site-packages\angr\sim_manager.py", line 401, in successors
    return self._project.factory.successors(state, **run_args)
  File "C:\python27-x64\lib\site-packages\angr\factory.py", line 61, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\engines\hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\engines\hook.py", line 51, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\engines\procedure.py", line 31, in process
    force_addr=force_addr)
  File "C:\python27-x64\lib\site-packages\angr\engines\engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "C:\python27-x64\lib\site-packages\angr\engines\procedure.py", line 65, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "C:\python27-x64\lib\site-packages\angr\sim_procedure.py", line 172, in execute
    inst.ret(r)
  File "C:\python27-x64\lib\site-packages\angr\sim_procedure.py", line 312, in ret
    arg_types=[False]*self.num_args if self.cc.args is None else None)
  File "C:\python27-x64\lib\site-packages\angr\calling_conventions.py", line 577, in teardown_callsite
    self.set_return_val(state, return_val)
  File "C:\python27-x64\lib\site-packages\angr\calling_conventions.py", line 641, in set_return_val
    loc.set_value(state, betterval, endness='Iend_BE', stack_base=stack_base)
  File "C:\python27-x64\lib\site-packages\angr\calling_conventions.py", line 103, in set_value
    self.check_value(value)
  File "C:\python27-x64\lib\site-packages\angr\calling_conventions.py", line 61, in check_value
    raise TypeError("%s doesn't fit in an argument of size %d" % (value, self.size))
TypeError: <BV64 GetTickCount64_result_5_64> doesn't fit in an argument of size 4

Process finished with exit code 1

```

**Comment by rhelmot** [comment]
Agh. This is something I’ve been meaning to fix for a very long time. The “right” solution is to add a calling convention capability to store larger return values in multiple registers but it could be hacked around as well. I’ll fix this this week.

**Comment by cbwang505** [comment]
how to add a calling convention capability to store larger return values?

**Comment by rhelmot** [comment]
By changing angr/calling_convention.py. I will do this sometime this week.

**Comment by hsyhsw** [comment]
@cbwang505 @rhelmot Seems not applied to the repo. I'd hit exactly the same issue and found the following workaround. (up to 64 bit return val, at least) It is basically overriding `set_return_val` to support returning value using multi-reg assignment.
```python
class SimCCCdeclRefined(SimCCCdecl):
    def set_return_val(self, state, val, is_fp=None, size=None, stack_base=None):
        """
        Set the return value into the given state
        """
        ty = self.func_ty.returnty if self.func_ty is not None else None
        try:
            betterval = self._standardize_value(val, ty, state, None)
        except AttributeError:
            raise ValueError("Can't fit value %s into a return value" % repr(val))

        if self.ret_val is not None:
            loc = self.ret_val
        elif is_fp is not None:
            loc = self.FP_RETURN_VAL if is_fp else self.RETURN_VAL
        elif ty is not None:
            if isinstance(ty, SimTypeFloat):
                loc = self.FP_RETURN_VAL
            elif ty.size <= 32: # using eax when sizeof(ret_val) <= 32
                loc = SimRegArg('eax', 4)
            elif 33 <= ty.size <= 64: # using [eax:edx] when 33 <= sizeof(ret_val) <= 64
                loc = SimComboArg([SimRegArg('eax', 4), SimRegArg('edx', 4)])
            else:
                raise NotImplementedError("This SimCC doesn't know how to store this value - should be implemented")
        else:
            loc = self.FP_RETURN_VAL if self.is_fp_value(val) else self.RETURN_VAL

        if loc is None:
            raise NotImplementedError("This SimCC doesn't know how to store this value - should be implemented")
        loc.set_value(state, betterval, endness='Iend_BE', stack_base=stack_base)
```
