### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by tracquangthinh** [angr/angr#1390]
**Describe the bug**
TypeError: a bytes-like object is required, not 'str'

**Environment Information**
angr environment report
=============================
Date: 2019-01-09 23:05:05.235625
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
######## angr #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/angr
Pip version angr 8.18.10.25
Couldn't find git info
######## ailment #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/ailment
Pip version ailment 8.18.10.25
Couldn't find git info
######## cle #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/cle
Pip version cle 8.18.10.25
Couldn't find git info
######## pyvex #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/pyvex
Pip version pyvex 8.18.10.25
Couldn't find git info
######## claripy #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/claripy
Pip version claripy 8.18.10.25
Couldn't find git info
######## archinfo #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/archinfo
Pip version archinfo 8.18.10.25
Couldn't find git info
######## ana #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/ana
Pip version ana 0.5
Couldn't find git info
######## z3 #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/tracquangthinh/.local/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/lib/angr_native.so', handle 1bd1110 at 0x7f24e26737b8>
unicorn: <CDLL '/home/tracquangthinh/.local/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 17c9320 at 0x7f24e54a4470>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f24e60dc8d0>
z3: <CDLL '/home/tracquangthinh/.local/lib/python3.6/site-packages/z3/lib/libz3.so', handle 25a9790 at 0x7f24c6d2f978>

**To Reproduce**
```
import angr
p = angr.Project('./data/virus_example_4')
entry_state = p.factory.entry_state()
sm = p.factory.simulation_manager(entry_state)
sm.run()
```
```
WARNING | 2019-01-09 22:31:52,664 | angr.state_plugins.symbolic_memory | Register ebp has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-09 22:31:52,683 | angr.state_plugins.symbolic_memory | Register ebx has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-09 22:31:52,686 | angr.state_plugins.symbolic_memory | Register esi has an unspecified value; Generating an unconstrained value of 4 bytes.
WARNING | 2019-01-09 22:31:52,689 | angr.state_plugins.symbolic_memory | Register edi has an unspecified value; Generating an unconstrained value of 4 bytes.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/sim_manager.py", line 382, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/sim_manager.py", line 421, in successors
    return self._project.factory.successors(state, **run_args)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/factory.py", line 49, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/engines/hook.py", line 51, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/engines/procedure.py", line 31, in process
    force_addr=force_addr)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/engines/procedure.py", line 65, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/sim_procedure.py", line 174, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/procedures/win32/GetModuleHandle.py", line 11, in run
    return self.handle(self.state.mem[pointer].string.concrete)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/procedures/win32/GetModuleHandle.py", line 17, in handle
    obj = self.project.loader.find_object(module_name)
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/cle/loader.py", line 300, in find_object
    for ident in self._possible_idents(spec):
  File "/home/tracquangthinh/.local/lib/python3.6/site-packages/cle/loader.py", line 952, in _possible_idents
    yield os.path.basename(spec).split('.')[0]
TypeError: a bytes-like object is required, not 'str'
```

**Input**
Please be careful. It is a x86 malware.
[virus_example_4.zip](https://github.com/angr/angr/files/2741247/virus_example_4.zip)

**Comment by ltfish** [comment]
Should be a bug. Thanks for reporting.

Note to myself: We need a new angr release...

**Comment by tracquangthinh** [comment]
@ltfish Thank you for your feedback.
Do you have any idea to fix this bug?

**Comment by ltfish** [comment]
>   File "/home/tracquangthinh/.local/lib/python3.6/site-packages/angr/procedures/win32/GetModuleHandle.py", line 11, in run
>    return self.handle(self.state.mem[pointer].string.concrete)

`self.state.mem[pointer].string.concrete` is giving you a `bytes` object I think. You want to decode it and convert it to a string there. It would be great if you can submit a PR!
