### ISSUE TITLE
VariableRecoveryFast fails miserably on CGC binaries

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#1392]
**Describe the bug**
When trying to do `VariableRecovery` analysis on a cgc binary, angr breaks.
And the error message is like this
~~~
Traceback (most recent call last):
  File "/home/kylebot/.virtualenvs/angr/lib/python3.6/site-packages/networkx/classes/digraph.py", line 794, in successors
    return iter(self._succ[n])
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 5, in <module>
    proj.analyses.VariableRecoveryFast(proj.kb.functions[0x080481c0])
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 524, in __init__
    self._analyze()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/forward_analysis.py", line 545, in _analyze
    self._pre_analysis()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 532, in _pre_analysis
    self.initialize_dominance_frontiers()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_base.py", line 78, in initialize_dominance_frontiers
    df = self.project.analyses.DominanceFrontier(self.function)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/dominance_frontier.py", line 20, in __init__
    self._compute()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/dominance_frontier.py", line 32, in _compute
    doms = Dominators(g, self.function.startpoint)
  File "/home/kylebot/src/angr-dev/angr/angr/utils/graph.py", line 184, in __init__
    self._construct(graph, entry_node)
  File "/home/kylebot/src/angr-dev/angr/angr/utils/graph.py", line 214, in _construct
    _prepared_graph, vertices, parent = self._prepare_graph(graph, entry_node)
  File "/home/kylebot/src/angr-dev/angr/angr/utils/graph.py", line 286, in _prepare_graph
    successors = list(self._graph_successors(graph, node))
  File "/home/kylebot/src/angr-dev/angr/angr/utils/graph.py", line 201, in _graph_successors
    return graph.successors(node)
  File "/home/kylebot/.virtualenvs/angr/lib/python3.6/site-packages/networkx/classes/digraph.py", line 796, in successors
    raise NetworkXError("The node %s is not in the digraph." % (n,))
networkx.exception.NetworkXError: The node None is not in the digraph.
~~~

**To Reproduce**
all in https://gist.github.com/Kyle-Kyle/77a6b66adda24dfdc2ad006e1b5a2470

**Comment by ltfish** [comment]
Function 0x80481c0 is empty. I'm looking into why.

**Comment by ltfish** [comment]
Umm there is no function 0x80481c0... I'm going to fix the resiliency problem so nothing crashes if the function is empty, but you should be checking if the function exists or not before getting one and passing it in to VariableRecoveryFast.

**Comment by Kyle-Kyle** [comment]
I mean, function 0x080481c0 does exist in the binary. And I believe a Function instance has been created. And it has no nodes. I think it should be a bug not a question?

**Comment by Kyle-Kyle** [comment]
Oh. I'm sorry. The function does not exist.

**Comment by Kyle-Kyle** [comment]
~~~
 Unsupported statement type Exit.
Traceback (most recent call last):
  File "script.py", line 5, in <module>
    proj.analyses.VariableRecoveryFast(proj.kb.functions[0x080480A0])
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 524, in __init__
    self._analyze()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/forward_analysis.py", line 557, in _analyze
    self._analysis_core_graph()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/forward_analysis.py", line 580, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 594, in _run_on_node
    input_state = prev_state.merge(input_state, successor=node.addr)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 460, in merge
    merged_stack_region = self.stack_region.copy().replace(replacements).merge(other.stack_region,
  File "/home/kylebot/src/angr-dev/angr/angr/keyed_region.py", line 159, in copy
    kr._object_mapping = self._object_mapping.copy()
  File "/home/kylebot/.virtualenvs/angr/lib/python3.6/weakref.py", line 174, in copy
    for key, wr in self.data.items():
RuntimeError: dictionary changed size during iteration
~~~
This is the new error log if I change the address to 0x080480A0. Hopefully, I'm not doing anything stupid again.

**Comment by ltfish** [comment]
https://github.com/python/cpython/pull/11384
