### ISSUE TITLE
fail to print debug representation of backward slice

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#1395]
**Describe the bug**
When playing with `BackwardSlice`, it crashes.

**To Reproduce**
~~~
import angr
import logging
logging.getLogger('angr.analyses.backward_slice').setLevel('DEBUG')


b = angr.Project('/home/kylebot/src/angr-dev/angr-doc/examples/fauxware/fauxware', auto_load_libs=False)
cfg = b.analyses.CFGEmulated(keep_state=True,
                                 state_add_options=angr.sim_options.refs,
                                 context_sensitivity_level=2)
cdg = b.analyses.CDG(cfg)
ddg = b.analyses.DDG(cfg)
target_func = cfg.kb.functions.function(name="exit")
target_node = cfg.get_any_node(target_func.addr)

bs = b.analyses.BackwardSlice(cfg, cdg=cdg, ddg=ddg, targets=[ (target_node, -1) ])

print(bs.dbg_repr())
~~~

**Comment by Kyle-Kyle** [comment]
The code is actually almost copy-paste from angr.io. The binary is the fauxware example from angr-doc.

**Comment by ltfish** [comment]
What is the exception?

**Comment by Kyle-Kyle** [comment]
The error log is as follow:
~~~
Traceback (most recent call last):
  File "x.py", line 17, in <module>
    print(bs.dbg_repr())
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/backward_slice.py", line 117, in dbg_repr
    run_addrs = sorted(self.chosen_statements.keys())[ : max_display]
TypeError: '<' not supported between instances of 'NoneType' and 'int'
~~~
The problems is there is a `None:[None]` in `bs.chosen_statements`

**Comment by ltfish** [comment]
Yeah... it's a left-over from Python 2 to Python 3 transition I think. I'll fix this one (and your previous issue) tonight.

**Comment by Kyle-Kyle** [comment]
Thanks!
