### ISSUE TITLE
ImportError: cannot import name exploration_techniques

### ISSUE THREAD

**Issue by wireshrink** [angr/angr#144]
I installed angr on kali, created virtual environment, used workon angr, ran python, imported angr and received the following output:

```
(angr) root@kali:~# python
Python 2.7.11+ (default, Jun  2 2016, 19:34:15) 
[GCC 5.3.1 20160528] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/virtual_env/angr/local/lib/python2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/opt/virtual_env/angr/local/lib/python2.7/site-packages/angr/project.py", line 383, in <module>
    from .factory import AngrObjectFactory
  File "/opt/virtual_env/angr/local/lib/python2.7/site-packages/angr/factory.py", line 349, in <module>
    from .path_group import PathGroup
  File "/opt/virtual_env/angr/local/lib/python2.7/site-packages/angr/path_group.py", line 802, in <module>
    from . import exploration_techniques
ImportError: cannot import name exploration_techniques
```

What am I doing wrong ?

**Comment by zardus** [comment]
Sounds like our pip package is messed up! Let me fix it real quick.

**Comment by zardus** [comment]
I updated the angr package on pypi. Can you try `pip install -U angr` and see if it fixes the issue?

**Comment by wireshrink** [comment]
Wow, it was really quick - thanks, it works :)
