### ISSUE TITLE
Trace desynced on jumping into libc.so.6. Did you load the right version of this library?

### ISSUE THREAD

**Issue by yangshouguo** [angr/angr#1474]
i just used gcc compiler to compile the binary and the binary was able to run normally on the machine, but angr can not run it, and got the error below.

```
[<ELF Object memcpy, maps [0x8048000:0x804a023]>, <ELF Object libc-2.27.so, maps [0x9000000:0x91dba1b]>, <ELF Object ld-2.27.so, maps [0xa000000:0xa027937]>]
WARNING | 2019-03-14 08:45:59,831 | cle.loader | memcpy: base_addr was specified but the object is not PIC. specify force_rebase=True to override
WARNING | 2019-03-14 08:46:00,087 | concreteRun | loaded shared library memcpy
WARNING | 2019-03-14 08:46:00,087 | concreteRun | loaded shared library libc.so.6
WARNING | 2019-03-14 08:46:00,087 | concreteRun | loaded shared library ld-linux.so.2
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    test_ConcreteRun()
  File "test.py", line 16, in test_ConcreteRun
    cr = ConcreteRun(vul, input_string)
  File "/filetransfer/ysg_test/Crash_tracer/ConcreteRun.py", line 59, in __init__
    self.trace()
  File "/filetransfer/ysg_test/Crash_tracer/ConcreteRun.py", line 102, in trace
    simgr.run()
  File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 259, in run
    self.step(stash=stash, **kwargs)
  File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/tracer.py", line 115, in step
    return simgr.step(stash=stash, **kwargs)
  File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 343, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/tracer.py", line 133, in step_state
    self._update_state_tracking(succs[0])
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/tracer.py", line 204, in _update_state_tracking
    elif self._compare_addr(self._trace[idx + 1], state.addr):
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/tracer.py", line 275, in _compare_addr
    raise AngrTracerError("Trace desynced on jumping into %s. Did you load the right version of this library?" % current_bin.provides)
angr.errors.AngrTracerError: Trace desynced on jumping into libc.so.6. Did you load the right version of this library?
(angr) angr@905d94971841:/filetransfer/ysg_test$ Trace desynced on jumping into libc.so.6. Did you load the right version of this library?
```

**Comment by rhelmot** [comment]
Did you load the right version of libc? The library file needs to be the same between the trace recording and the trace following. You can test which libc angr has loaded with `project.loader.shared_objects['libc.so.6'].binary`.
