### ISSUE TITLE
virtualenv issue with binja plugin

### ISSUE THREAD

**Issue by h0rac** [angr/angr#1479]
*Disclaimer: The angr suite is maintained by a small team of volunteers. While we cannot guarantee any timeliness for fixes and enhancements, we will do our best. For more real-time help with angr, from us and the community, join our [Slack.](http://angr.io/invite/)*

---

**Describe the bug**

Traceback (most recent call last):
  File "/home/horac/.binaryninja/plugins/test_angr.py", line 4, in <module>
    proj = angr.Project('/home/horac/Research/firmware/MR200/fmk/rootfs/usr/bin/cli')
  File "/home/horac/Research/angr/lib/python3.5/site-packages/angr/project.py", line 120, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 125, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *force_load_libs)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 649, in _internal_load
    dep_obj = self._load_object_isolated(dep_spec)  # loading dependencies
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 703, in _load_object_isolated
    full_spec = self._search_load_path(spec) # this is allowed to cheat and do partial static loading
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 833, in _search_load_path
    backend_cls = self._static_backend(path)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 998, in _static_backend
    if rear.is_default and rear.is_compatible(stream):
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/backends/binja.py", line 170, in is_compatible
    if magic.startswith("SQLite format 3") and stream.name.endswith("bndb"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Python plugin 'test_angr' could not be loaded

**Environment Information**
Linux VM Ubuntu 16.04
Bug exist under virtualenv or outside, python 3.5. When trying use angr inside BinaryNinja

**To Reproduce**
import angr
proj = angr.Project('binaryname')

inside BinaryNinja python console or as plugin

**Comment by rhelmot** [comment]
This was resolved already, by https://github.com/angr/cle/pull/168. It is fixed on github but not on pypi. There will be a new release as soon as I'm not dying from school.
