### ISSUE TITLE
ld_path issue 

### ISSUE THREAD

**Issue by h0rac** [angr/angr#1482]
**Describe the bug**

ld_path is not working for Project constructor.

**proj = angr.Project(bv.file.filename, ld_path=[b'/home/horac/Research/firmware/fmk/rootfs/lib'], use_system_libs=False )**

```
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 125, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *force_load_libs)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 630, in _internal_load
    main_obj = self._load_object_isolated(main_spec)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 703, in _load_object_isolated
    full_spec = self._search_load_path(spec) # this is allowed to cheat and do partial static loading
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 831, in _search_load_path
    for path in self._possible_paths(spec):
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 893, in _possible_paths
    fullpath = os.path.realpath(os.path.join(libdir, spec))
  File "/home/horac/Research/angr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/horac/Research/angr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
**TypeError: Can't mix strings and bytes in path components**
```
**proj = angr.Project(bv.file.filename, load_options={'auto_load_libs':True, 'ld_path':(b'/home/horac/Research/firmware/fmk/rootfs/lib',)})**

```
    File "/home/horac/Research/binaryninja/plugins/../python/binaryninja/plugin.py", line 647, in run
    self.task.run()
  File "/home/horac/.binaryninja/plugins/wr941nd_poc.py", line 19, in run
    main(self.bv)
  File "/home/horac/.binaryninja/plugins/wr941nd_poc.py", line 59, in main
    proj = angr.Project(bv.file.filename, load_options={'auto_load_libs':True, 'ld_path':(b'/home/horac/Research/firmware/fmk/rootfs/lib',)})
  File "/home/horac/Research/angr/lib/python3.5/site-packages/angr/project.py", line 120, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 125, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *force_load_libs)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 630, in _internal_load
    main_obj = self._load_object_isolated(main_spec)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 703, in _load_object_isolated
    full_spec = self._search_load_path(spec) # this is allowed to cheat and do partial static loading
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 831, in _search_load_path
    for path in self._possible_paths(spec):
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 893, in _possible_paths
    fullpath = os.path.realpath(os.path.join(libdir, spec))
  File "/home/horac/Research/angr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/horac/Research/angr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```
When use string, I got error that bytes.. expected

**TypeError: a bytes-like object is required, not 'str'**

**Environment Information**
Linux/virtualenv

**To Reproduce**

use ld_path key in Project constructor

**Comment by h0rac** [comment]
Problems also exist when binary is in /lib directory, without any ld_path config added to Project

**Comment by rhelmot** [comment]
You're not supposed to provided paths as bytestrings. paths are human readable text, and are therefore unicode strings.

Also, I can't reproduce your issue with `/lib`. Loading `/lib/x86_64-linux-gnu/libc.so.6` works fine for me.

**Comment by h0rac** [comment]
Hi Thanks for answer, I found that this is binary dependent issue, but still this is weird, because one binary accept ld_path as string without issues, and second don't accept as string or bytes. I forgot to mention that these are MIPS ( do. not work) and MIPSEL(works) binaries

**Comment by rhelmot** [comment]
Very strange. If you have a binary that you think should load but doesn't, can you post it?

**Comment by h0rac** [comment]
https://drive.google.com/file/d/1AZLGxJjkmakC8rThMce7DRkNQmaE_wza/view?usp=sharing

**Comment by rhelmot** [comment]
This loads for me without issue. Can you provide the libraries it needs to link against?

**Comment by h0rac** [comment]
https://drive.google.com/drive/folders/13KndECO9k9A1B2ViLvpIybo1DZEyllJ5?usp=sharing

**Comment by h0rac** [comment]
Hmm, now I don't see errors but it looks like loading system libs for mips-gnu-linux  instead from path
OrderedDict([('httpd', <ELF Object httpd, maps [0x400000:0x5c7a77]>), ('libpthread.so.0', <ELF Object libpthread-2.23.so, maps [0x1000000:0x102c3bf]>), ('libc.so.6', <ELF Object libc-2.23.so, maps [0x2000000:0x217ef2f]>), ('librt.so.1', <ELF Object librt-2.23.so, maps [0x3000000:0x30172bf]>), ('libutil.so.1', <ELF Object libutil-2.23.so, maps [0x4000000:0x40120df]>), ('libgcc_s.so.1', <ELF Object libgcc_s.so.1, maps [0x5000000:0x50373ff]>), ('ld.so.1', <ELF Object ld-2.23.so, maps [0x6000000:0x6033ce3]>)])

should be libc.so.0 -> libuClibc-0.9.30.so

**Comment by h0rac** [comment]
When I change Project to not load system_libs it confirms that is not able to load from path

`proj = angr.Project(bv.file.filename,  ld_path=['/Research/firmware/WR941ND/fmk/rootfs/lib'], load_options={'auto_load_libs':True}, use_system_libs=False)`

`OrderedDict([('httpd', <ELF Object httpd, maps [0x400000:0x5c7a77]>)])`

**Comment by rhelmot** [comment]
so - I'm very confused about the barrage of different information you're giving me, but I did find a bug and I have a fix for it on the fix/decode_soname branch. Try that out and see what it does.

I can't reproduce any issue with use_system_libs:

```
[+] In [1]: import angr

[+] In [2]: dict(angr.Project('/tmp/httpd', ld_path=['/tmp/mips/lib'], use_system_libs=False).loader.shared_objects)
Out[2]: 
{'httpd': <ELF Object httpd, maps [0x400000:0x5c7a77]>,
 'ld-uClibc.so.0': <ELF Object ld-uClibc-0.9.30.so, maps [0x8000000:0x801513f]>,
 'libc.so.0': <ELF Object libuClibc-0.9.30.so, maps [0x2000000:0x2072baf]>,
 'libgcc_s.so.1': <ELF Object libgcc_s.so.1, maps [0x7000000:0x703ab7f]>,
 'libmsglog.so': <ELF Object libmsglog.so, maps [0x4000000:0x4010c5f]>,
 'libpthread.so.0': <ELF Object libpthread-0.9.30.so, maps [0x1000000:0x1023a6f]>,
 'librt.so.0': <ELF Object librt-0.9.30.so, maps [0x3000000:0x3010d53]>,
 'libutil.so.0': <ELF Object libutil-0.9.30.so, maps [0x5000000:0x5010f7b]>,
 'libwpa_ctrl.so': <ELF Object libwpa_ctrl.so, maps [0x6000000:0x6011f6f]>}
```

**Comment by h0rac** [comment]
I've tried use CLE separately in virtualenv

```
(angr) ➜  bin python
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cle
>>> ld = cle.Loader("httpd")
>>> ld.shared_objects
OrderedDict([('httpd', <ELF Object httpd, maps [0x400000:0x5c7a77]>), ('libpthread.so.0', <ELF Object libpthread-2.23.so, maps [0x1000000:0x102c3bf]>), ('libc.so.6', <ELF Object libc-2.23.so, maps [0x2000000:0x217ef2f]>), ('librt.so.1', <ELF Object librt-2.23.so, maps [0x3000000:0x30172bf]>), ('libutil.so.1', <ELF Object libutil-2.23.so, maps [0x4000000:0x40120df]>), ('libgcc_s.so.1', <ELF Object libgcc_s.so.1, maps [0x5000000:0x50373ff]>), ('ld.so.1', <ELF Object ld-2.23.so, maps [0x6000000:0x6033ce3]>)])
>>> 
```
and it is loading.. system libs instead the one from /lib

**Comment by rhelmot** [comment]
You didn't specify ld_path...

**Comment by h0rac** [comment]
```
>>> angr.Project('httpd', ld_path=['/home/horac/Research/firmware/WR941ND/fmk/rootfs/lib'], use_system_libs=False).loader.shared_objects
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/horac/Research/angr/lib/python3.5/site-packages/angr/project.py", line 120, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 125, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *force_load_libs)
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 649, in _internal_load
    dep_obj = self._load_object_isolated(dep_spec)  # loading dependencies
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 712, in _load_object_isolated
    for ident in self._possible_idents(full_spec): # also allowed to cheat
  File "/home/horac/Research/angr/lib/python3.5/site-packages/cle/loader.py", line 978, in _possible_idents
    yield soname.rstrip('.0123456789')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by rhelmot** [comment]
Like I said, 

> I have a fix for it on the fix/decode_soname branch of CLE. Try that out and see what it does.

**Comment by h0rac** [comment]
Thanks, works
