### ISSUE TITLE
Trace failed to synchronize during fast forward? You might want to unhook __libc_start_main

### ISSUE THREAD

**Issue by lzina** [angr/angr#1518]
Hi,
I am running shellphish/fuzzer/shellphuzz.py (driller + afl) on number of binaries in tiff-3.9.7.
Each time I get different errors form the **angr.errors.AngrTracerError** and don't know how to handle with them. I already searched the web but could not find any solution that can help me move on.

```
Traceback (most recent call last):
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/driller/local_callback.py", line 125, in <module>
    for new_input in d.drill_generator():
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/driller/driller_main.py", line 101, in drill_generator
    for i in self._drill_input():
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/driller/driller_main.py", line 141, in _drill_input
    simgr.step()
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/driller_core.py", line 39, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 115, in step
    return simgr.step(stash=stash, **kwargs)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 343, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 133, in step_state
    self._update_state_tracking(succs[0])
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 236, in _update_state_tracking
    self._fast_forward(state)
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 357, in _fast_forward
    raise AngrTracerError("Trace failed to synchronize during fast forward? You might want to unhook %s." % (self.project.hooked_by(state.history.addr).display_name))
**angr.errors.AngrTracerError: Trace failed to synchronize during fast forward? You might want to unhook __libc_start_main**.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 355, in _fast_forward
    target_idx = self._trace.index(target_addr, state.globals['trace_idx'] + 1)
**ValueError: 274888955232 is not in list**
```

please your help.
thanks!

**Comment by rhelmot** [comment]
This isn't nearly enough information to debug this. Can you post the binary you're analyzing, as well as all the libraries that show up when you run `ldd` on your binary?

**Comment by lzina** [comment]
Thanks for the reply.
The binary I am analyzing is tiff2pdf under tiff-3.9.7. 

`ldd` return the list below:
```
        linux-vdso.so.1 (0x00007ffd6cd15000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fad0ab3f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fad0a7a1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fad0a3b0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fad0afbb000)
```

the python test file is:
```
#!/usr/bin/env python

import driller

with open("tiff-file", "rb") as f:
    bytes_input = f.read()
d = driller.Driller("tiff2pdf",  # path to the target binary
                    bytes_input  # initial testcase
                    )
new_inputs = d.drill()
print(new_inputs)
```

As I told before, each time I get a different error which is a bit wired.
I run driller again and now the error is:
```
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 204, in _update_state_tracking
    elif self._compare_addr(self._trace[idx + 1], state.addr):
  File "/home/glass/PycharmProjects/driller_new/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 275, in _compare_addr
    raise AngrTracerError("Trace desynced on jumping into %s. Did you load the right version of this library?" % current_bin.provides)
angr.errors.AngrTracerError: Trace desynced on jumping into libc.so.6. Did you load the right version of this library?
```

Hope you have enough information.
Thanks again,

**Comment by lzina** [comment]
I forgot to mention that project.loader.shared_objects['libc.so.6'].binary is '/lib/x86_64-linux-gnu/libc-2.27.so' while 
```
/lib/x86_64-linux-gnu$ ls -al | grep libc
-rwxr-xr-x  1 root root 2030544 Apr 16  2018 libc-2.27.so
lrwxrwxrwx  1 root root      12 Oct 29 16:55 libc.so.6 -> libc-2.27.so
```

**Comment by rhelmot** [comment]
Please upload your specific copies of all those binaries, including your
libraries. I spent a while looking and couldn't find binaries for that
version of tiff...

**Comment by lzina** [comment]
[Issue.zip](https://github.com/angr/angr/files/3124782/Issue.zip)

**Comment by rhelmot** [comment]
I couldn't reproduce `you might want to unhook __libc_start_main` (which sometimes indicates there's a desync between which libc is being used in qemu and which one is being used in angr), but I got a `angr did not follow the trace` error, which I fixed in 4e2f97d56. However I then found another similar error which I tracked down to an issue involving angr's implementation of ifuncs and their interactions with normal hooks. I will eventually get to this, but it will take some work.

**Comment by bannsec** [comment]
Think i've run into the same issue with the gctf regex binary.

```AngrTracerError: Trace desynced on jumping into libc.so.6. Did you load the right version of this library?```

Used QEMU tracer to grab the trace and fed that into tracer exploration technique.

**Comment by rhelmot** [comment]
The advice above still applies. Make sure that qemu and angr are loading the same version of libc. As the error message says.

**Comment by lzina** [comment]
> Think i've run into the same issue with the gctf regex binary.
> 
> `AngrTracerError: Trace desynced on jumping into libc.so.6. Did you load the right version of this library?`
> 
> Used QEMU tracer to grab the trace and fed that into tracer exploration technique.

Can you please show example? I didn't understand what exactly to do.
