### ISSUE TITLE
unable to import angr

### ISSUE THREAD

**Issue by akibsayyed** [angr/angr#152]
hey guys

I have installed angr as specified in documentation. I am using ubuntu 14.04

I am getting following error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/project.py", line 10, in <module>
    import cle
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/cle/__init__.py", line 4, in <module>
    from .loader import *
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/cle/loader.py", line 805, in <module>
    from .tls import TLSObj
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/cle/tls.py", line 4, in <module>
    from .backends import Backend
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/cle/backends/__init__.py", line 4, in <module>
    import archinfo
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/archinfo/__init__.py", line 6, in <module>
    from .arch import *
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/archinfo/arch.py", line 1, in <module>
    import capstone as _capstone
  File "/root/.virtualenvs/angr/local/lib/python2.7/site-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

**Comment by rhelmot** [comment]
this falls under the "Can't import angr because of capstone" entry of the [install guide](http://docs.angr.io/INSTALL.html)

`pip install -I --no-use-wheel capstone`

**Comment by rhelmot** [comment]
did this resolve your issue?

**Comment by akibsayyed** [comment]
Yes it did solve my issue

**Comment by rhelmot** [comment]
Cool!
