### ISSUE TITLE
Give me a hand, please

### ISSUE THREAD

**Issue by wapen** [angr/angr#153]
I install angr in 64bit win7 with 64bit python V2.7.12, when analyses  pe file, sometimes have error: 
SimSolverModeError: ('Translated claripy error:', <class 'claripy.errors.ClaripyFrontendError'>, ClaripyFrontendError("Backend error during _max: <class 'claripy.errors.BackendError'>('unexpected type <type 'instance'> encountered in BackendZ3')",))

There's the traceback when run the example layer7_onlyone.exe:
WARNING | 2016-07-09 23:24:59,585 | [33mcle.pe[0m | [33mThe PE module is not
well-supported. Good luck![0m
Executing...
WARNING | 2016-07-09 23:25:00,677 | [31msimuvex.s_run[0m | [31mExit state has
 over 257 possible solutions. Likely unconstrained; skipping. <BV32 Reverse(symb
olic_read_reg_1c_13_32_31_32)>[0m
WARNING | 2016-07-09 23:25:01,066 | [31msimuvex.s_run[0m | [31mExit state has
 over 257 possible solutions. Likely unconstrained; skipping. <BV32 Reverse(symb
olic_read_reg_1c_13_32_34_32)>[0m
WARNING | 2016-07-09 23:25:02,970 | [31msimuvex.s_run[0m | [31mExit state has
 over 257 possible solutions. Likely unconstrained; skipping. <BV32 mem_7fff0000
_81_32>[0m
WARNING | 2016-07-09 23:25:05,792 | [31msimuvex.s_run[0m | [31mExit state has
 over 257 possible solutions. Likely unconstrained; skipping. <BV32 mem_7fff0000
_81_32>[0m
WARNING | 2016-07-09 23:25:07,961 | [31msimuvex.s_run[0m | [31mExit state has
 over 257 possible solutions. Likely unconstrained; skipping. <BV32 mem_7fff0000
_208_32>[0m
WARNING | 2016-07-09 23:25:11,598 | [31msimuvex.s_run[0m | [31mExit state has
 over 257 possible solutions. Likely unconstrained; skipping. <BV32 mem_7fff0000
_324_32>[0m
WARNING | 2016-07-09 23:25:12,019 | [31msimuvex.s_run[0m | [31mExit state has
 over 257 possible solutions. Likely unconstrained; skipping. <BV32 Reverse(symb
olic_read_reg_1c_325_32_327_32)>[0m
WARNING | 2016-07-09 23:25:12,051 | [34msimuvex.vex.irsb[0m | [34m<SimIRSB 0x
4010bc> hit an error while analyzing statement 22[0m
Traceback (most recent call last):
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\vex\irsb.py", line 98, in _handle_irsb
    self._handle_statements()
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\vex\irsb.py", line 224, in _handle_statements
    s_stmt = translate_stmt(self.irsb, stmt_idx, self.last_imark, self.state)
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\vex\statements\__init__.py", line 31, in translate_stmt
    s.process()
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\vex\statements\base.py", line 26, in process
    self._execute()
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\vex\statements\store.py", line 31, in _execute
    self.state.memory.store(addr.expr, data.expr, action=a, endness=self.stmt.endness)
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\storage\memory.py", line 429, in store
    self._store(request)
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\plugins\symbolic_memory.py", line 737, in _store
    req.actual_addresses = self.concretize_write_addr(req.addr)
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\plugins\symbolic_memory.py", line 495, in concretize_write_addr
    return self._concretize_addr(addr, strategy=strategy, limit=limit, approx_limit=approx_limit, action='store')
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\plugins\symbolic_memory.py", line 448, in _concretize_addr
    result = getattr(self, '_concretization_strategy_'+s)(v, limit, approx_limit)
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\s
imuvex\plugins\symbolic_memory.py", line 362, in _concretization_strategy_max
    return [self.state.se.max_int(v)]
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\plugins\solver.py", line 141, in concrete_shortcut_scalar
    return f(self, *args, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\s_action_object.py", line 53, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\plugins\solver.py", line 82, in wrapped_f
    return f(*args, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\simuvex-4.6.6.28-py2.7.egg\simuvex\plugins\solver.py", line 363, in max
    return self._solver.max(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "D:\projects\python\angr64\lib\site-packages\claripy\frontend_mixins\concrete_handler_mixin.py", line 30, in max
    return super(ConcreteHandlerMixin, self).max(e, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\claripy\frontend_mixins\constraint_filter_mixin.py", line 44, in max
    return super(ConstraintFilterMixin, self).max(e, extra_constraints=ec, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\claripy\frontend_mixins\simplify_helper_mixin.py", line 4, in max
    return super(SimplifyHelperMixin, self).max(*args, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\claripy\frontend_mixins\constraint_expansion_mixin.py", line 24, in max
    m = super(ConstraintExpansionMixin, self).max(e, extra_constraints=extra_constraints, exact=exact, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\claripy\frontends\composite_frontend.py", line 297, in max
    r = ms.max(e, extra_constraints=extra_constraints, exact=exact)
  File "D:\projects\python\angr64\lib\site-packages\claripy\frontend_mixins\model_cache_mixin.py", line 259, in max
    m = super(ModelCacheMixin, self).max(e, extra_constraints=extra_constraints, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\claripy\frontends\full_frontend.py", line 136, in max
    model_callback=self._model_hook
  File "D:\projects\python\angr64\lib\site-packages\claripy\backend.py", line 544, in max
    return self._max(self.convert(expr), result=result, extra_constraints=self.c
onvert_list(extra_constraints, result=result), solver=solver, model_callback=model_callback)
  File "D:\projects\python\angr64\lib\site-packages\claripy\backends\backend_z3.py", line 72, in z3_condom
    return f(*condom_args, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\claripy\backends\backend_z3.py", line 661, in _max
    solver.add(*[self.convert(e) for e in extra_constraints])
  File "D:\projects\python\angr64\lib\site-packages\claripy\backend.py", line 187, in convert
    return self._convert(expr, result=result)
  File "D:\projects\python\angr64\lib\site-packages\claripy\backends\backend_z3.py", line 72, in z3_condom
    return f(*condom_args, **kwargs)
  File "D:\projects\python\angr64\lib\site-packages\claripy\backends\backend_z3.py", line 296, in _convert
    raise BackendError("unexpected type %s encountered in BackendZ3" % type(obj)
)
SimSolverModeError: ('Translated claripy error:', <class 'claripy.errors.ClaripyFrontendError'>, ClaripyFrontendError("Backend error during _max: <class 'claripy.errors.BackendError'>('unexpected type <type 'instance'> encountered in BackendZ3')",))
Traceback (most recent call last):
  File "solve.py", line 83, in <module>
    print main()
  File "solve.py", line 64, in main
    final_state = r.errored[0].previous_run.initial_state
IndexError: list index out of range

**Comment by hypersimple** [comment]
How could you solve this?

**Comment by wapen** [comment]
sorry, I just saw your letter, I have del that post, and have you sole that now?


________________________________
发件人: hypersimple <notifications@github.com>
发送时间: 2016年11月5日 0:45
收件人: angr/angr
抄送: wapen; State change
主题: Re: [angr/angr] Give me a hand, please (#153)


How could you solve this?

―
