### ISSUE TITLE
CLE elf backend fails loading when specifying a PPC arch parameter in the `Project` constructor

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr#1553]
When explicitely specifying the architecture for a PPC binary (from the [angr/binaries](https://github.com/angr/binaries/tree/master/tests/ppc) repo), CLE blows up.

First, when I do not specify any architecture to the `Project` constructor, everything looks fine:

```python
>>> import angr
>>> project = angr.Project("binaries/tests/ppc/fauxware")
>>> project.loader
<Loaded fauxware, maps [0x10000000:0x15008000]>
```

But then, if I do add explicitely the `arch` parameter:
```python
>>> import angr
>>> from archinfo import ArchPPC32
>>> arch = ArchPPC32()
>>> project = angr.Project("binaries/tests/ppc/fauxware", arch=arch)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pamplemousse/Workspace/angr/angr/angr/project.py", line 118, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/home/pamplemousse/Workspace/angr/cle/cle/loader.py", line 128, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *preload_libs, preloading=True)
  File "/home/pamplemousse/Workspace/angr/cle/cle/loader.py", line 645, in _internal_load
    main_obj = self._load_object_isolated(main_spec)
  File "/home/pamplemousse/Workspace/angr/cle/cle/loader.py", line 748, in _load_object_isolated
    return backend_cls(full_spec, is_main_bin=self.main_object is None, loader=self, **options)
  File "/home/pamplemousse/Workspace/angr/cle/cle/backends/elf/elf.py", line 112, in __init__
    self.__register_segments()
  File "/home/pamplemousse/Workspace/angr/cle/cle/backends/elf/elf.py", line 501, in __register_segments
    self.__register_dyn(seg)
  File "/home/pamplemousse/Workspace/angr/cle/cle/backends/elf/elf.py", line 552, in __register_dyn
    self.dynsym, self.memory, AT.from_lva(self._dynamic['DT_GNU_HASH'], self).to_rva(), self.arch)
  File "/home/pamplemousse/Workspace/angr/cle/cle/backends/elf/hashtable.py", line 77, in __init__
    self.bloom = struct.unpack(fmt + fmtsz*self.maskwords, stream.read(self.c*self.maskwords//8))
struct.error: unpack requires a bytes object of length 67108864
```

I tried different PPC binaries, and got the same problem.
Other platforms seem fine, except `ArchPPC64`.
```
>>> arch64 = ArchPPC64()
>>> project = angr.Project('binaries/tests/ppc64/fauxware', arch=arch64)
<ERROR>
```

<details>
  <summary>My environment information</summary>

```
angr environment report
=============================
Date: 2019-05-01 12:50:32.921117
Running in virtual environment at /home/pamplemousse/Workspace/angr/venv
Platform: linux-x86_64
Python version: 3.5.6 (default, Aug  2 2018, 13:05:50) 
[GCC 7.3.0]
######## angr #########
Python found it in /home/pamplemousse/Workspace/angr/angr/angr
Pip version angr 8.19.4.5
Git info:
	Current commit 7e78a25b4a82278679748188ea5255f13ddb7b1e from branch documentation
Could not resolve tracking branch or remote info!
######## ailment #########
Python found it in /home/pamplemousse/Workspace/angr/venv/lib/python3.5/site-packages/ailment
Pip version ailment 8.19.4.5
Couldn't find git info
######## cle #########
Python found it in /home/pamplemousse/Workspace/angr/cle/cle
Pip version cle 8.19.4.5
Git info:
	Current commit 2cdd1523bc8d3b6a9d0a1368150129bd2bfa9ccc from branch master
	Checked out from remote origin: https://github.com/angr/cle.git
######## pyvex #########
Python found it in /home/pamplemousse/Workspace/angr/pyvex/pyvex
Pip version pyvex 8.19.4.5
Git info:
	Current commit c418edc1146982b2a0579bf56e5993c1c7046b19 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex.git
######## claripy #########
Python found it in /home/pamplemousse/Workspace/angr/claripy/claripy
Pip version claripy 8.19.4.5
Git info:
	Current commit 4ed61924880af1ea8fb778047d896ec0156412a6 from branch master
	Checked out from remote origin: https://github.com/angr/claripy.git
######## archinfo #########
Python found it in /home/pamplemousse/Workspace/angr/archinfo/archinfo
Pip version archinfo 8.19.4.5
Git info:
	Current commit fca8d2bf23044caf207e160b25a3809cbadfbec6 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo.git
######## z3 #########
Python found it in /home/pamplemousse/Workspace/angr/venv/lib/python3.5/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/pamplemousse/Workspace/angr/venv/lib/python3.5/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
z3: <CDLL '/home/pamplemousse/Workspace/angr/venv/lib/python3.5/site-packages/z3/lib/libz3.so', handle 3f85080 at 0x7fd93b1a0668>
unicorn: <CDLL '/home/pamplemousse/Workspace/angr/venv/lib/python3.5/site-packages/unicorn/lib/libunicorn.so', handle 2ce2d10 at 0x7fd940652d68>
angr: <CDLL '/home/pamplemousse/Workspace/angr/angr/angr/lib/angr_native.so', handle 38ba120 at 0x7fd941b54ef0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fd94199ea90>
```
</details>

**Comment by rhelmot** [comment]
that would be because this is a big endian PPC binary and the default PPC
arch from archinfo is little endian.

**Comment by Pamplemousse** [comment]
Ah, indeed.
When I explicitly specify the endianness, it works fine.

```python
>>> import angr
>>> from archinfo import ArchPPC32
>>> endness = archinfo.arch.Endness().BE
>>> arch = ArchPPC32(endness=endness)
>>> project = angr.Project('../binaries/tests/ppc/fauxware', arch=arch)
>>> project.loader
<Loaded fauxware, maps [0x10000000:0x15008000]>
```

Shouldn't this be read from the ELF file header though?
It has a field to signify little or big endian: [see wikipedia page for ELF](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format#File_header) .

**Comment by rhelmot** [comment]
Indeed. You have overridden that by specifying the arch (ISA + endness)
manually.
