### ISSUE TITLE
Oops! angr did not follow the trace

### ISSUE THREAD

**Issue by lzina** [angr/angr#1609]
Hi,
when running driller on afl test-cases, I get the following error for some inputs:
```
ERROR   | 2019-06-13 12:38:57,938 | angr.exploration_techniques.tracer | Trying to synchronize at %#x (%#x) but it does not appear in the trace?
Traceback (most recent call last):
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/local_callback.py", line 137, in <module>
    for new_input in results:
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/driller_main.py", line 101, in drill_generator
    for i in self._drill_input():
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/driller_main.py", line 141, in _drill_input
    simgr.step()
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File ~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/driller_core.py", line 39, in step
    simgr.step(stash=stash, **kwargs)
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 222, in step
    return simgr.step(stash=stash, **kwargs)
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 343, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 272, in step_state
    self._update_state_tracking(succs[0])
  File "~/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 436, in _update_state_tracking
    deviating_trace_idx=idx+1)
angr.exploration_techniques.tracer.TracerDesyncError: Oops! angr did not follow the trace
```
what does it means? 
thanks.

**Comment by rhelmot** [comment]
It means that angr's CPU emulation produced a different result for what the next address should be than qemu did, and we cannot continue. This can happen for an enormous number of reasons, most of which involve desyncs between qemu and angr. For example: differing cpuid or timestamp values. Bugs in angr's implementation of the elf loader or syscalls. Differing values in the environment or the auxiliary vector. Differing address space randomization.

There is not a catch-all solution to this, and it is one of the main barriers to driller being an actually useful technique.

**Comment by ymgh96** [comment]
I have the same problem but in running a CGC binary! Is it possible?

**Comment by rhelmot** [comment]
For a cgc binary it should be surmountable. Can you post a testcase to reproduce it @ymgh96 ?

**Comment by ymgh96** [comment]
> For a cgc binary it should be surmountable. Can you post a testcase to reproduce it @ymgh96 ?

I made a mistake! my binary was a linux compilation from CGC source code. I used from a CGC binary (that compile on DECREE) and my problem was solved.
Thank you.
