### ISSUE TITLE
When I create a cfg , I meet an OverflowError.

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#162]
Hi,
When I use CFGAccurate to create cfg on 64-bit Ubuntu 15.10, I get an OverflowError.However I can create it successfully on 32-bit Ubuntu 14.10.On 32-bit platform, I meet some message like  _Unsupported operation: Iop_Yl2xp1F64_.
Below is the error on 64-bit os.
```
WARNING | 2016-07-22 10:33:50,001 | simuvex.plugins.symbolic_memory | Concretizing symbolic length. Much sad; think about implementing.
WARNING | 2016-07-22 10:33:52,344 | simuvex.plugins.symbolic_memory | Concretizing symbolic length. Much sad; think about implementing.
WARNING | 2016-07-22 10:35:46,408 | simuvex.vex.irop | symbolic rounding mode found, using default
WARNING | 2016-07-22 10:35:46,700 | simuvex.vex.irop | symbolic rounding mode found, using default
WARNING | 2016-07-22 10:35:46,903 | simuvex.vex.irop | symbolic rounding mode found, using default
Traceback (most recent call last):
  File "./solver.py", line 86, in <module>
    Find_Func(File,proj)
  File "./solver.py", line 37, in Find_Func
    cfg=proj.analyses.CFGAccurate(keep_state=True)
  File "/home/ying/angr-dev/angr/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/ying/angr-dev/angr/angr/analyses/cfg_accurate.py", line 181, in __init__
    self._analyze()
  File "/home/ying/angr-dev/angr/angr/analyses/forward_analysis.py", line 186, in _analyze
    self._handle_entry(entry_info)
  File "/home/ying/angr-dev/angr/angr/analyses/forward_analysis.py", line 209, in _handle_entry
    self._pre_entry_handling(entry)
  File "/home/ying/angr-dev/angr/angr/analyses/cfg_accurate.py", line 853, in _pre_entry_handling
    simrun, error_occurred, _ = self._get_simrun(addr, entry.path, current_function_addr=entry.func_addr)
  File "/home/ying/angr-dev/angr/angr/analyses/cfg_accurate.py", line 2183, in _get_simrun
    sim_run = self.project.factory.sim_run(current_entry.state, jumpkind=jumpkind)
  File "/home/ying/angr-dev/angr/angr/factory.py", line 127, in sim_run
    r = sim_proc_class(state, addr=addr, sim_kwargs=kwargs)
  File "/home/ying/angr-dev/simuvex/simuvex/s_procedure.py", line 73, in __init__
    r = self._run(run_func, *args, syscall_name=syscall_name, **self.kwargs)
  File "/home/ying/angr-dev/simuvex/simuvex/s_procedure.py", line 116, in _run
    r = run_func(*args, **kwargs)
  File "/home/ying/angr-dev/simuvex/simuvex/procedures/libc___so___6/memset.py", line 65, in run
    self.state.memory.store(dst_addr, write_bytes)
  File "/home/ying/angr-dev/simuvex/simuvex/storage/memory.py", line 429, in store
    self._store(request)
  File "/home/ying/angr-dev/simuvex/simuvex/plugins/symbolic_memory.py", line 725, in _store
    max_bytes = len(req.data)/8
OverflowError: long int too large to convert to int
```
Below is the message on 32-bit os.
```
ERROR   | 2016-07-22 10:45:50,310 | simuvex.vex.irop | Unsupported operation: Iop_Yl2xp1F64
ERROR   | 2016-07-22 10:45:50,338 | simuvex.vex.irop | Unsupported operation: Iop_2xm1F64
ERROR   | 2016-07-22 10:45:50,346 | simuvex.vex.irop | Unsupported operation: Iop_ScaleF64
ERROR   | 2016-07-22 10:45:50,615 | simuvex.vex.irop | Unsupported operation: Iop_Yl2xF64
ERROR   | 2016-07-22 10:45:50,637 | simuvex.vex.irop | Unsupported operation: Iop_2xm1F64
ERROR   | 2016-07-22 10:45:50,646 | simuvex.vex.irop | Unsupported operation: Iop_ScaleF64
ERROR   | 2016-07-22 10:45:50,722 | simuvex.vex.irop | Unsupported operation: Iop_Yl2xp1F64
ERROR   | 2016-07-22 10:45:50,746 | simuvex.vex.irop | Unsupported operation: Iop_2xm1F64
ERROR   | 2016-07-22 10:45:50,755 | simuvex.vex.irop | Unsupported operation: Iop_ScaleF64
ERROR   | 2016-07-22 10:45:50,934 | simuvex.vex.irop | Unsupported operation: Iop_Yl2xF64
ERROR   | 2016-07-22 10:45:50,958 | simuvex.vex.irop | Unsupported operation: Iop_2xm1F64
ERROR   | 2016-07-22 10:45:51,239 | simuvex.vex.irop | Unsupported operation: Iop_ScaleF64
ERROR   | 2016-07-22 10:45:51,273 | simuvex.vex.irop | Unsupported operation: Iop_Yl2xp1F64
ERROR   | 2016-07-22 10:45:52,967 | simuvex.vex.irop | Unsupported operation: Iop_Yl2xF64
ERROR   | 2016-07-22 10:45:52,989 | simuvex.vex.irop | Unsupported operation: Iop_2xm1F64
ERROR   | 2016-07-22 10:45:52,998 | simuvex.vex.irop | Unsupported operation: Iop_ScaleF64
ERROR   | 2016-07-22 10:45:53,031 | simuvex.vex.irop | Unsupported operation: Iop_Yl2xp1F64
```
Here is the link of the tested program
[https://github.com/kbranigan/cJSON](url)

Here is the commands
```
proj = angr.Project('./json', load_options={'auto_load_libs': True})
cfg=proj.analyses.CFGAccurate(keep_state=True)
```
Thanks a lot!

**Comment by zardus** [comment]
Thanks for finding this bug! We're currently in a crazy CGC crunch, so it's likely that this won't get looked at until after DEFCON, but we'll definitely get to it!

**Comment by rhelmot** [comment]
Can you re-run this test? I just tried running CFGAccurate on the `test` program from cJSON, and it completed fine, just like your 32-bit example. It's possible this got fixed somehow in the CGC run-up.

**Comment by brokendragon** [comment]
@zardus @rhelmot Thanks for geting to it!
when I set ```keep_state=True```, I still get the OverflowError.However, if I set ```keep_state=False```,it like my  32-bit example and the OverflowError is disappeared.
