### ISSUE TITLE
Original block hit an unsupported error

### ISSUE THREAD

**Issue by lzina** [angr/angr#1644]
The binary I am analyzing is 'netstorage' from CGC binaries. (attached)
[issue3.zip](https://github.com/angr/angr/files/3365452/issue3.zip)
(Please put the include files in the right path (as mention below) in order to make it run for you.)

The binary is 32 bit and was compiled with "DARPA Challenges Sets for Linux, Windows, and macOS" => https://github.com/trailofbits/cb-multios

ldd return the list below:

```
glass@test:~/PycharmProjects/driller-afl/venv/test_cases$ ldd /cb-multios/build/challenges/netstorage/netstorage
        linux-gate.so.1 (0xf7fa7000)
        libcgc.so => /cb-multios/build/include/libcgc.so (0xf7f9d000)
        libtiny-AES128-C.so => /cb-multios/build/include/tiny-AES128-C/libtiny-AES128-C.so (0xf7f98000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7d9e000)
        /lib/ld-linux.so.2 (0xf7fa9000)
```

The python test file is:

```
#!/usr/bin/env python

import driller
import os

with open("test_case_for_driller", "rb") as f:
    bytes_input = f.read()

with open("fuzz_bitmap", "rb") as bitmap:
    fuzz_bitmap = bitmap.read()

d = driller.Driller("/cb-multios/build/challenges/netstorage/netstorage",  # path to the target binary
                    bytes_input,  # initial testcase
                    fuzz_bitmap)

new_inputs = d.drill()
print(new_inputs)
```

The error I get is:

```
ERROR   | 2019-07-07 12:11:36,290 | angr.exploration_techniques.oppologist | Original block hit an unsupported error
Traceback (most recent call last):
  File "/home/glass/PycharmProjects/driller-afl/venv/test_cases/drill_run.py", line 16, in <module>
    new_inputs = d.drill()
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/driller_main.py", line 85, in drill
    list(self._drill_input())
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/driller_main.py", line 141, in _drill_input
    simgr.step()
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/driller_core.py", line 39, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 225, in step
    return simgr.step(stash=stash, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 253, in step_state
    sat_succs = succs_dict[None]  # satisfiable states
KeyError: None
```

I appreciate your help.
Thanks!

**Comment by ltfish** [comment]
See my comment here: https://github.com/angr/angr/issues/1646#issuecomment-515689789. I do agree that we need a more user-friendly error message here though.
