### ISSUE TITLE
BUG! Please investigate the claim in the comment above me

### ISSUE THREAD

**Issue by lzina** [angr/angr#1646]
Hi,
when running driller on xmllint binary (attached), I get the following error:
[xmllint.zip](https://github.com/angr/angr/files/3367311/xmllint.zip)

```
Traceback (most recent call last):
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/local_callback.py", line 147, in <module>
    for new_input in d.drill_generator():
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/driller_main.py", line 101, in drill_generator
    for i in self._drill_input():
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/driller/driller_main.py", line 141, in _drill_input
    simgr.step()
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/driller_core.py", line 39, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 225, in step
    return simgr.step(stash=stash, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 275, in step_state
    self._update_state_tracking(succs[0])
  File "/home/glass/PycharmProjects/driller-afl/venv/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 386, in _update_state_tracking
    deviating_trace_idx=idx)
angr.exploration_techniques.tracer.TracerDesyncError: BUG! Please investigate the claim in the comment above me
```
What can be the problem?
Thanks!

**Comment by ltfish** [comment]
At this moment we are well aware of what's happening: Trace mismatches are caused by inaccuracies introduced by the limits on input bytes and/or the use of `SimProcedure`s. You may try to switch to permissive tracing mode in Tracer (by default it uses strict mode), but there is no guarantee that it will solve your problem. At the end of the day this problem is (most likely) not a bug in our implementation but an unresolvable issue in dealing with partial execution traces (traces without data logged).
