### ISSUE TITLE
Bug in angr when reading from /dev/stdin

### ISSUE THREAD

**Issue by abearcher** [angr/angr#1660]
---

**Describe the bug.**

When I import driller and try to read form stdin, there appears to be a bug in angr in angr/exploration_techniques/tracer.py

As can be seen below my binary reads from /dev/stdin, with it I can do:
```

(angr) angr@example:/mount/C_code$ sudo echo 20 | ./stdinReader 
20

End of file.
```

When running script s.py which uses the above binary with angr and driller, I get the error: 

```
(angr) angr@example:/mount/C_code$ python s.py 
WARNING | 2019-07-12 20:09:40,124 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2019-07-12 20:09:42,189 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
ERROR   | 2019-07-12 20:09:44,712 | angr.exploration_techniques.oppologist | Original block hit an unsupported error
Traceback (most recent call last):
  File "s.py", line 7, in <module>
    new_inputs = d.drill()
  File "/home/angr/angr-dev/driller/driller/driller_main.py", line 85, in drill
    list(self._drill_input())
  File "/home/angr/angr-dev/driller/driller/driller_main.py", line 141, in _drill_input
    simgr.step()
  File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/driller_core.py", line 39, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/tracer.py", line 225, in step
    return simgr.step(stash=stash, **kwargs)
  File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/exploration_techniques/tracer.py", line 253, in step_state
    sat_succs = succs_dict[None]  # satisfiable states
KeyError: None
```

Would appreciate any help. Thank you in advance.

**Environment Information.**

```
=============================
Date: 2019-07-12 20:03:21.901830
Running in virtual environment at /home/angr/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
######## angr #########
Python found it in /home/angr/angr-dev/angr/angr
Pip version angr 8.19.4.5
Git info:
	Current commit c101353a917e9b0b5f5e5c21587eed3cbe371a83 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/angr/angr-dev/ailment/ailment
Pip version ailment 8.19.4.5
Git info:
	Current commit 4e50d1ad6ec6184a3ac512c5f6bf1a298a9c6b8f from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/angr/angr-dev/cle/cle
Pip version cle 8.19.4.5
Git info:
	Current commit 71eeb501ded37846d16be76d43ba0734cdc307f2 from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/angr/angr-dev/pyvex/pyvex
Pip version pyvex 8.19.4.5
Git info:
	Current commit f2bcfc40256b7dad4dd12df9bba5a97e8617460f from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/angr/angr-dev/claripy/claripy
Pip version claripy 8.19.4.5
Git info:
	Current commit 574fc988bae91854e52b9357f82f2797b4ad26ce from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/angr/angr-dev/archinfo/archinfo
Pip version archinfo 8.19.4.5
Git info:
	Current commit 75c62c8c40b6635e555c23e85777cb74ef880fd0 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.2
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/angr/angr-dev/angr/angr/lib/angr_native.so', handle 31b8030 at 0x7fc19a33bf60>
unicorn: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 2932b80 at 0x7fc1992ebbe0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fc19a2dc860>
z3: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 3587f30 at 0x7fc19aa08d30>
```

**To Reproduce.**

binary: sample.c
```
#include <stdio.h>

int main(void) {

  FILE *fptr;

  int num;

  fptr = fopen("/dev/stdin", "r");

  fscanf(fptr, "%d", &num);


  if(num == 20)
      printf("%d\n", num);


  printf("\nEnd of file.\n");

  fclose(fptr);

  return 0;
}
```

script: s.py

```
import driller

d = driller.Driller("./djpegReader",  # path to the target binary
                    b"10" # AFL bitmap with no discovered transitions
                   )

new_inputs = d.drill()
print(new_inputs)


```

**Additional context.**

**Comment by ltfish** [comment]
See my comment here: https://github.com/angr/angr/issues/1646#issuecomment-515689789. It's very likely that this is not a bug but a fundamental limitation of the approach.
