### ISSUE TITLE
CFGFast crashes on opencv binaries

### ISSUE THREAD

**Issue by iamdeeban** [angr/angr#1711]
---

I am using  `cfg.jump_tables` command to dump jump tables from a particular binary. It works well for almost many binaries but crashed in some as provided in the link. I am not sure why it crashes especially these binaries. I have attached my script and binaries were angr crashes.

[Binaries link](https://drive.google.com/drive/folders/1WiGo3bp5jE6HP1nMbqfltOKqvU0d1qd7)

```
ERROR   | 2019-09-04 12:49:00,807 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03be4 of function 0xc03be1.
ERROR   | 2019-09-04 12:49:00,807 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03be5 of function 0xc03be5.
ERROR   | 2019-09-04 12:49:00,808 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03be6 of function 0xc03be6.
ERROR   | 2019-09-04 12:49:00,809 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03bed of function 0xc03be7.
ERROR   | 2019-09-04 12:49:00,810 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03bf2 of function 0xc03bee.
ERROR   | 2019-09-04 12:49:00,811 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03c0c of function 0xc03bf3.
ERROR   | 2019-09-04 12:49:00,812 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03c13 of function 0xc03c0d.
ERROR   | 2019-09-04 12:49:00,812 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03c18 of function 0xc03c14.
ERROR   | 2019-09-04 12:49:00,814 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03c27 of function 0xc03c19.
ERROR   | 2019-09-04 12:49:00,814 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03c28 of function 0xc03c28.
ERROR   | 2019-09-04 12:49:00,815 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03c29 of function 0xc03c29.
ERROR   | 2019-09-04 12:49:00,816 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03c2d of function 0xc03c2a.
ERROR   | 2019-09-04 12:49:00,816 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0xc03c2e of function 0xc03c2e.
Traceback (most recent call last):
  File "dump_jumptables.py", line 42, in <module>
    store_jumptables(line)
  File "dump_jumptables.py", line 20, in store_jumptables
    cfg = proj.analyses.CFGFast(show_progressbar=True)
  File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 626, in __init__
    self._analyze()
  File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis.py", line 583, in _analyze
    self._analysis_core_baremetal()
  File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis.py", line 684, in _analysis_core_baremetal
    self._job_queue_empty()
  File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1106, in _job_queue_empty
    self._process_unresolved_indirect_jumps()
  File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2143, in _process_unresolved_indirect_jumps
    all_targets |= self._process_one_indirect_jump(jump)
  File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2169, in _process_one_indirect_jump
    resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
  File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 442, in resolve
    if total_cases > self._max_targets:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Would be great to know your thoughts on this.

**Comment by ltfish** [comment]
I could not reproduce it. Which binary did you test on (there are two binaries in your provided Google Drive directory)? If possible, please run your script with `ipython --pdb` and then tell me what `addr` and `total_case` are where the TypeError is raised. Thank you in advance.

Also, there are *many* AVX512 instructions in libopencv_core.so.4.0.1. As of now, VEX does not support AVX512, which is why CFG recovery takes so long and generated many decoding errors on this binary.

**Comment by iamdeeban** [comment]
Thanks @ltfish. For both the binaries I am getting the same output. Based on your inputs I ran the script with `ipython <script> --pdb` and got the following outputs with different `addr` and `total_cases`. Please find them below.

![Screenshot from 2019-09-19 14-55-16](https://user-images.githubusercontent.com/45299442/65246164-4bc84b00-daee-11e9-8fe6-09bf46a5cec5.png)
![Screenshot from 2019-09-19 14-55-26](https://user-images.githubusercontent.com/45299442/65246174-4ec33b80-daee-11e9-9b0b-3f8da0ae70bf.png)

If I need to give more details or do something more please do let me know. Thank you.
