### ISSUE TITLE
`ReachingDefinitions` failing on a `Block`

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr#1714]
### Description

When passing only a `Block` to `ReachingDefinitions()`, [some `LiveDefinitions` declaration](https://github.com/angr/angr/blob/21e537cfa5f81b830faf575726eedbc0487a50f6/angr/analyses/reaching_definitions/reaching_definitions.py#L480-L481) down the line ends up failing.

Indeed, there are no check to verify if we are in the case of a `Block` or a `Function` analysis.

### Minimal working example

```python
import angr

project = angr.Project('../binaries/x86_64/all', load_options={'auto_load_libs': False})
cfg = project.analyses.CFGFast()
main_function = cfg.kb.functions['main']
code_block = main_function._addr_to_block_node[main_function.addr]
block = angr.block.Block(addr=0x42, byte_string=code_block.bytestr, project=project)

project.analyses.ReachingDefinitions(block)
```

gives me the following:

```python
Traceback (most recent call last):
  [...]
    project.analyses.ReachingDefinitions(block = block)
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/reaching_definitions/reaching_definitions.py", line 393, in __init__
    self._analyze()
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/forward_analysis.py", line 609, in _analyze
    self._analysis_core_graph()
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/forward_analysis.py", line 627, in _analysis_core_graph
    job_state = self._initial_abstract_state(n)
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/reaching_definitions/reaching_definitions.py", line 479, in _initial_abstract_state
    init_func=self._init_func, cc=self._cc, func_addr=self._function.addr)
AttributeError: 'NoneType' object has no attribute 'addr'
```

### Potential fix

This should solve the current problem, but wonder if that will not cause other trouble in some cases.

```python
func_addr = self._function.addr if self._function else None
return LiveDefinitions(
    self.project.arch,
    track_tmps=self._track_tmps,
    analysis=self,
    init_func=self._init_func,
    cc=self._cc,
    func_addr=func_addr
)
```

**Comment by Pamplemousse** [comment]
Ah! My bad.
This case was introduced by some refactoring.

Will fix / deal with that as discussed with @ltfish .
