### ISSUE TITLE
`_handle_WrTmp` in the VEX engine for `ReachingDefinitions` does not handle corner case

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr#1742]
**Describe the bug.**

The function `_handle_WrTmp`, in the VEX engine of the `ReachingDefinitions` analysis, can fail due to a `KeyError`.

Example, with a breakpoint set right before [`_handleWrTmp`'s guilty statement](https://github.com/angr/angr/blob/master/angr/analyses/reaching_definitions/engine_vex.py#L63):
```
ipdb> stmt.tmp
37
ipdb> self.tmps
{1: <angr.analyses.reaching_definitions.dataset.DataSet object at 0x7f3a099e2c50>, 0: <angr.analyses.reaching_definitions.dataset.DataSet object at 0x7f3a099e2d10>, 6: <angr.analyses.reaching_definitions.dataset.DataSet object at 0x7f3a09abe490>, 4: <angr.analyses.reaching_definitions.dataset.DataSet object at 0x7f3a0a099c50>, 7: <angr.analyses.reaching_definitions.dataset.DataSet object at 0x7f3a09abe310>, 34: <angr.analyses.reaching_definitions.dataset.DataSet object at 0x7f3a099f3e90>, 12: <angr.analyses.reaching_definitions.dataset.DataSet object at 0x7f3a09abed50>, 35: <angr.analyses.reaching_definitions.dataset.DataSet object at 0x7f3a0a099f10>}
```

The `stmt.tmp` is **not** in the list of `self.tmps`!

<details>
<summary>See full stack trace</summary>

```
Traceback (most recent call last):                                                                                                                                       
  File "/nix/store/mylvss4yxf3ljsyxh3wbyx2liy6x7gbr-python3-3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)                                                                                                                                                
  File "/nix/store/mylvss4yxf3ljsyxh3wbyx2liy6x7gbr-python3-3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)                                                                                                                                              
  File "/nix/store/mylvss4yxf3ljsyxh3wbyx2liy6x7gbr-python3-3.7.4/lib/python3.7/cProfile.py", line 185, in <module>
    main()                                                                                                                                                               
  File "/nix/store/mylvss4yxf3ljsyxh3wbyx2liy6x7gbr-python3-3.7.4/lib/python3.7/cProfile.py", line 178, in main
    runctx(code, globs, None, options.outfile, options.sort)                                                                                                             
  File "/nix/store/mylvss4yxf3ljsyxh3wbyx2liy6x7gbr-python3-3.7.4/lib/python3.7/cProfile.py", line 20, in runctx
    filename, sort)                                                                                                                                                      
  File "/nix/store/mylvss4yxf3ljsyxh3wbyx2liy6x7gbr-python3-3.7.4/lib/python3.7/profile.py", line 62, in runctx
    prof.runctx(statement, globals, locals)                                                                                                                              
  File "/nix/store/mylvss4yxf3ljsyxh3wbyx2liy6x7gbr-python3-3.7.4/lib/python3.7/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "case_studies/air_live_bu_2015.py", line 91, in <module>
    main()
  File "case_studies/air_live_bu_2015.py", line 85, in main
    run_rda_measurements_on_slices(cfg, slices)
  File "case_studies/air_live_bu_2015.py", line 57, in run_rda_measurements_on_slices
    slices
  File "case_studies/air_live_bu_2015.py", line 49, in _run_rda_measurements_for_one_sink
    visited_counts = _reaching_definitions(slice_for_sink, HANDLER)._run_nodes_count 
  File "case_studies/air_live_bu_2015.py", line 25, in _reaching_definitions
    observe_all=True
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/reaching_definitions/reaching_definitions.py", line 474, in __init__
    self._analyze()
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/forward_analysis/__init__.py", line 223, in _analyze
    self._analysis_core_graph()
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/forward_analysis/__init__.py", line 242, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/reaching_definitions/reaching_definitions.py", line 615, in _run_on_node
    state = engine.process(state, block=block, fail_fast=self._fail_fast)
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/reaching_definitions/engine_vex.py", line 32, in process
    self._process(state, None, block=kwargs.pop('block', None))
  File "/home/pamplemousse/Workspace/angr/angr/angr/engines/light/engine.py", line 69, in _process
    self._process_Stmt(whitelist=whitelist)
  File "/home/pamplemousse/Workspace/angr/angr/angr/engines/light/engine.py", line 90, in _process_Stmt
    self._handle_Stmt(stmt)
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/reaching_definitions/engine_vex.py", line 56, in _handle_Stmt
    super(SimEngineRDVEX, self)._handle_Stmt(stmt)
  File "/home/pamplemousse/Workspace/angr/angr/angr/engines/light/engine.py", line 106, in _handle_Stmt
    getattr(self, handler)(stmt)
  File "/home/pamplemousse/Workspace/angr/angr/angr/analyses/reaching_definitions/engine_vex.py", line 65, in _handle_WrTmp
    self.state.kill_and_add_definition(Tmp(stmt.tmp), self._codeloc(), self.tmps[stmt.tmp])
KeyError: 37
```
</details>

**To Reproduce.**

```
import angr

project = angr.Project('../binaries-private/operation-mango/air-live-bu-2015/cgi_test.cgi', auto_load_libs=False)
cfg = project.analyses.CFGFast()

sub_b21c = cfg.kb.functions.function(name='sub_b21c')
project.analyses.ReachingDefinitions(subject=sub_b21c)
```

**Additional context.**

`git blame` shows that it seems to have been introduced here: https://github.com/angr/angr/commit/683b0b28#diff-ce290d025f02353b5d86b685291655caR63 .

**Comment by rhelmot** [comment]
The reason is: when there is an unsupported operation expression handlers will return None. When WrTmp gets None as data result, it will not write anything into the tmps dict. The subclass does not expect this behavior.

My proposed fix is to move this logic from the rdtmp handler, indicating that unknown tmps should just be datasets with Undefined, to the wrtmp handler:

```python
        if tmp in self.tmps:
            return self.tmps[tmp]
        bits = expr.result_size(self.tyenv)
        return DataSet(undefined, bits)
```

**Comment by rhelmot** [comment]
or better yet, move it into `_expr` so that any handler which returns None automatically gets a correctly sized dataset filled with Undefined

**Comment by Pamplemousse** [comment]
@rhelmot , was interested into giving a go, and implement your last proposition.

However, `_expr` comes from `angr/engines/light/engine.py` whereas `Undefined` seems to be an RDA concept (i.e., in `angr/analyses/reaching_definitions/undefined.py`).

Unsure that a particular type should be returned by a generic mechanism.

**Comment by rhelmot** [comment]
You can override `_expr` in the vex engine for RDA and check if the result of the super-call is None.
