### ISSUE TITLE
Error in CFGFast with `cross_references = True`

### ISSUE THREAD

**Issue by bin2415** [angr/angr#1758]
---

**Describe the bug.**

I want to get all the cross references from CFGFast, but I got errors:

```
WARNING | 2019-10-18 11:29:35,346 | [36mcle.loader[0m | [36mThe main binary is a position-independent executable. It is being loaded with a base address of 0x400000.[0m
WARNING | 2019-10-18 11:29:35,362 | [32mangr.state_plugins.symbolic_memory[0m | [32mThe program is accessing memory or registers with an unspecified value. This could indicate unwanted behavior.[0m
WARNING | 2019-10-18 11:29:35,362 | [32mangr.state_plugins.symbolic_memory[0m | [32mangr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:[0m
WARNING | 2019-10-18 11:29:35,362 | [32mangr.state_plugins.symbolic_memory[0m | [32m1) setting a value to the initial state[0m
WARNING | 2019-10-18 11:29:35,362 | [32mangr.state_plugins.symbolic_memory[0m | [32m2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null[0m
WARNING | 2019-10-18 11:29:35,362 | [32mangr.state_plugins.symbolic_memory[0m | [32m3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY_REGISTERS}, to suppress these messages.[0m
WARNING | 2019-10-18 11:29:35,362 | [32mangr.state_plugins.symbolic_memory[0m | [32mFilling memory at 0x7fffffff with 8 unconstrained bytes referenced from 0x400535 (_start+0x5 in hello (0x535))[0m
ERROR   | 2019-10-18 11:29:35,439 | [34mangr.analyses.cfg.cfg_fast[0m | [34mError collecting XRefs for function _init.[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1269, in _do_full_xrefs
    prop = self.project.analyses.Propagator(func=f, base_state=state)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/propagator/propagator.py", line 199, in __init__
    graph_visitor = FunctionGraphVisitor(func, func_graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 210, in __init__
    self.reset()
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 113, in reset
    for i, n in enumerate(self.sort_nodes()):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 226, in sort_nodes
    sorted_nodes = CFGUtils.quasi_topological_sort_nodes(self.graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in quasi_topological_sort_nodes
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in <listcomp>
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
TypeError: cannot unpack non-iterable BlockNode object
ERROR   | 2019-10-18 11:29:35,445 | [34mangr.analyses.cfg.cfg_fast[0m | [34mError collecting XRefs for function deregister_tm_clones.[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1269, in _do_full_xrefs
    prop = self.project.analyses.Propagator(func=f, base_state=state)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/propagator/propagator.py", line 199, in __init__
    graph_visitor = FunctionGraphVisitor(func, func_graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 210, in __init__
    self.reset()
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 113, in reset
    for i, n in enumerate(self.sort_nodes()):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 226, in sort_nodes
    sorted_nodes = CFGUtils.quasi_topological_sort_nodes(self.graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in quasi_topological_sort_nodes
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in <listcomp>
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
TypeError: cannot unpack non-iterable BlockNode object
ERROR   | 2019-10-18 11:29:35,446 | [34mangr.analyses.cfg.cfg_fast[0m | [34mError collecting XRefs for function register_tm_clones.[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1269, in _do_full_xrefs
    prop = self.project.analyses.Propagator(func=f, base_state=state)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/propagator/propagator.py", line 199, in __init__
    graph_visitor = FunctionGraphVisitor(func, func_graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 210, in __init__
    self.reset()
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 113, in reset
    for i, n in enumerate(self.sort_nodes()):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 226, in sort_nodes
    sorted_nodes = CFGUtils.quasi_topological_sort_nodes(self.graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in quasi_topological_sort_nodes
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in <listcomp>
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
TypeError: cannot unpack non-iterable BlockNode object
ERROR   | 2019-10-18 11:29:35,447 | [34mangr.analyses.cfg.cfg_fast[0m | [34mError collecting XRefs for function __do_global_dtors_aux.[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1269, in _do_full_xrefs
    prop = self.project.analyses.Propagator(func=f, base_state=state)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/propagator/propagator.py", line 199, in __init__
    graph_visitor = FunctionGraphVisitor(func, func_graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 210, in __init__
    self.reset()
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 113, in reset
    for i, n in enumerate(self.sort_nodes()):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 226, in sort_nodes
    sorted_nodes = CFGUtils.quasi_topological_sort_nodes(self.graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in quasi_topological_sort_nodes
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in <listcomp>
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
TypeError: cannot unpack non-iterable BlockNode object
ERROR   | 2019-10-18 11:29:35,448 | [34mangr.analyses.cfg.cfg_fast[0m | [34mError collecting XRefs for function main.[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1269, in _do_full_xrefs
    prop = self.project.analyses.Propagator(func=f, base_state=state)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/propagator/propagator.py", line 199, in __init__
    graph_visitor = FunctionGraphVisitor(func, func_graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 210, in __init__
    self.reset()
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 113, in reset
    for i, n in enumerate(self.sort_nodes()):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 226, in sort_nodes
    sorted_nodes = CFGUtils.quasi_topological_sort_nodes(self.graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in quasi_topological_sort_nodes
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in <listcomp>
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
TypeError: cannot unpack non-iterable BlockNode object
ERROR   | 2019-10-18 11:29:35,449 | [34mangr.analyses.cfg.cfg_fast[0m | [34mError collecting XRefs for function __libc_csu_init.[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1269, in _do_full_xrefs
    prop = self.project.analyses.Propagator(func=f, base_state=state)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/propagator/propagator.py", line 199, in __init__
    graph_visitor = FunctionGraphVisitor(func, func_graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 210, in __init__
    self.reset()
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 113, in reset
    for i, n in enumerate(self.sort_nodes()):
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/forward_analysis.py", line 226, in sort_nodes
    sorted_nodes = CFGUtils.quasi_topological_sort_nodes(self.graph)
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in quasi_topological_sort_nodes
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
  File "/usr/local/lib/python3.7/dist-packages/angr/analyses/cfg/cfg_utils.py", line 151, in <listcomp>
    out_degree_zero_nodes = [node for (node, degree) in graph.out_degree() if degree == 0]
TypeError: cannot unpack non-iterable BlockNode object
```

**Environment Information.**

python3.7, Ubuntu 18.04. I compiled the binary by gcc-7.4.0. I installed the angr directly from the latest source code.

**To Reproduce.**

This is my script:

```python

import angr

if __name__ == '__main__':
    p = angr.Project("./hello", load_options={'auto_load_libs': False})
    cfg = p.analyses.CFGFast(cross_references = True)
```
The binary and log file:
[test.zip](https://github.com/angr/angr/files/3744688/test.zip)

**Additional context.**

**Comment by ltfish** [comment]
Thanks for reporting, but I cannot reproduce it on my machine.

Here are a couple of questions, hopefully they will help me understand what's going on in your environment.

- What's the version of networkx that you installed in your Python environment?
- Set a breakpoint before `cfg_utils.py` line 151, and see what `graph` is and what its type is.

Thanks!

**Comment by bin2415** [comment]
Thanks for your responding! I re-installed my `networkx` and it worked. My current version is 2.4.
