### ISSUE TITLE
I meet a SimMemoryAddressError

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#176]
Hi,
when I try to find a function in a progrom,angr can return me one found path.However,during the process，I get `SimMemoryAddressError: Unable to concretize address with the provided strategy.`The tested program is a Json resolver,below is some code in the tested program.(the whole teseted progrom is too large to post it)

```
    char buffer[1024] = {0};
    int fd;
    if ((fd = open(argv[1], O_RDONLY)) == -1) {
        printf("error");
    }   
    read(fd, buffer,1023);
    doit(buffer);
```

The `doit` function above parses a json file and some pointer operation involved. I deliver a conrete file name to argv[1] and below is the commands

```
p=proj.factory.path(args=["test_switch","./tests/test1"])
pg=proj.factory.path_group(p)
pg=pg.explore(find=0x401f51,num_find=1)
```

The WARNING is 

```
WARNING | 2016-08-10 11:18:56,822 | simuvex.vex.irsb | <SimIRSB 0x4022c7> hit an error while analyzing statement 8
Traceback (most recent call last):
  File "/home/ying/angr-dev/simuvex/simuvex/vex/irsb.py", line 98, in _handle_irsb
    self._handle_statements()
  File "/home/ying/angr-dev/simuvex/simuvex/vex/irsb.py", line 224, in _handle_statements
    s_stmt = translate_stmt(self.irsb, stmt_idx, self.last_imark, self.state)
  File "/home/ying/angr-dev/simuvex/simuvex/vex/statements/__init__.py", line 31, in translate_stmt
    s.process()
  File "/home/ying/angr-dev/simuvex/simuvex/vex/statements/base.py", line 26, in process
    self._execute()
  File "/home/ying/angr-dev/simuvex/simuvex/vex/statements/wrtmp.py", line 6, in _execute
    data = self._translate_expr(self.stmt.data)
  File "/home/ying/angr-dev/simuvex/simuvex/vex/statements/base.py", line 36, in _translate_expr
    e = translate_expr(expr, self.imark, self.stmt_idx, self.state)
  File "/home/ying/angr-dev/simuvex/simuvex/vex/expressions/__init__.py", line 14, in translate_expr
    e.process()
  File "/home/ying/angr-dev/simuvex/simuvex/vex/expressions/base.py", line 38, in process
    self._execute()
  File "/home/ying/angr-dev/simuvex/simuvex/vex/expressions/load.py", line 30, in _execute
    self.expr = self.state.memory.load(addr.expr, size, endness=self._expr.endness)
  File "/home/ying/angr-dev/simuvex/simuvex/storage/memory.py", line 612, in load
    a,r,c = self._load(addr_e, size_e, condition=condition_e, fallback=fallback_e)
  File "/home/ying/angr-dev/simuvex/simuvex/plugins/symbolic_memory.py", line 595, in _load
    addrs = self.concretize_read_addr(dst)
  File "/home/ying/angr-dev/simuvex/simuvex/plugins/symbolic_memory.py", line 515, in concretize_read_addr
    return self._concretize_addr(addr, strategy=strategy, limit=limit, approx_limit=approx_limit, action='load')
  File "/home/ying/angr-dev/simuvex/simuvex/plugins/symbolic_memory.py", line 466, in _concretize_addr
    raise SimMemoryAddressError("Unable to concretize address with the provided strategy.")
SimMemoryAddressError: Unable to concretize address with the provided strategy.
```

The WARNING appears in a pointer operation `ptr++;`(`ptr` is a pointer).
I want to know whether this WARNING significant impact angr‘s further explore? And under what circumstances，angr will give me this WARNING ? Is it the problem of my commands?

Thanks in advance!

**Comment by c3c** [comment]
Also interested in what generally causes this warning to be thrown and how to resolve it.

**Comment by zardus** [comment]
Could you check if this happens when the `LAZY_SOLVES` state option is removed? When it's present, we try to avoid doing constraint solves, but it's often necessary to do them during memory index resolution, so that's when the state tends to go unsat. In that case, this is not an error -- it's the state finally going unsat even though it was already supposed to be unsat.

**Comment by c3c** [comment]
I don't want to piggyback on @brokendragon's issue, but for me at least this happens regardless of the `LAZY_SOLVES` state option. I also see this happening for CTF challenges that angr does come up with a solution for in the end.

**Comment by gitttt** [comment]
Is this solved now? I got the same error:

`WARNING | 2016-09-22 09:32:53,938 | cle.pe | The PE module is not well-supported. Good luck!
WARNING | 2016-09-22 09:32:56,837 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 mem_7fff0198_12_32>
WARNING | 2016-09-22 09:32:57,008 | simuvex.vex.irsb | <SimIRSB 0x100800b1> hit an error while analyzing statement 7
Traceback (most recent call last):
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/irsb.py", line 98, in _handle_irsb
    self._handle_statements()
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/irsb.py", line 224, in _handle_statements
    s_stmt = translate_stmt(self.irsb, stmt_idx, self.last_imark, self.state)
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/statements/__init__.py", line 31, in translate_stmt
    s.process()
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/statements/base.py", line 26, in process
    self._execute()
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/statements/wrtmp.py", line 6, in _execute
    data = self._translate_expr(self.stmt.data)
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/statements/base.py", line 36, in _translate_expr
    e = translate_expr(expr, self.imark, self.stmt_idx, self.state)
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/expressions/__init__.py", line 14, in translate_expr
    e.process()
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/expressions/base.py", line 38, in process
    self._execute()
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/vex/expressions/load.py", line 30, in _execute
    self.expr = self.state.memory.load(addr.expr, size, endness=self._expr.endness)
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/storage/memory.py", line 612, in load
    a,r,c = self._load(addr_e, size_e, condition=condition_e, fallback=fallback_e)
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/plugins/symbolic_memory.py", line 595, in _load
    addrs = self.concretize_read_addr(dst)
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/plugins/symbolic_memory.py", line 515, in concretize_read_addr
    return self._concretize_addr(addr, strategy=strategy, limit=limit, approx_limit=approx_limit, action='load')
  File "/home/user/Exercises/Utils/angr-dev/simuvex/simuvex/plugins/symbolic_memory.py", line 466, in _concretize_addr
    raise SimMemoryAddressError("Unable to concretize address with the provided strategy.")
SimMemoryAddressError: Unable to concretize address with the provided strategy.
`

**Comment by brokendragon** [comment]
@gitttt In some cases ,removing `LAZY_SOLVES ` can solve the problem,but it does not work in other cases.

**Comment by ltfish** [comment]
This is not an issue, but mostly an expected output when `LAZY_SOLVES` is enabled. That is because we delay the constraint solving until we have to (e.g. when we resolve the range of a symbolic address), and if the state has already become unsat before that, the constraint solving will fail, and a `SimMemoryAddressError` will be raised. This is a non-issue, but I think the warning message can definitely be improved.

**Comment by brokendragon** [comment]
Will the `SimMemoryAddressError` affect speed of exploration?

**Comment by zardus** [comment]
The error itself should not. `LAZY_SOLVES` does, making it faster when constraints are very complex and slower when they are more simple.

When `LAZY_SOLVES` is off, this error can be caused by inaccurate SimProcedures adding constraints that make the state unsat. A path backtrace from a path that hits this error would make it easier to investigate this case.
