### ISSUE TITLE
Z3 solver issues on Windows

### ISSUE THREAD

**Issue by angrycodez** [angr/angr#1796]
Dear all,
I have a problem with the Z3 solver engine.
I use a simple script to analyse an ARM-binary, using simgr.explore(), which works just fine on my Linux-system, but when I run the same script on my Windows machine, I get the following error:

> Traceback (most recent call last):
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\sim_manager.py", line 238, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\misc\hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\exploration_techniques\explorer.py", line 96, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\misc\hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\sim_manager.py", line 382, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\sim_manager.py", line 421, in successors
    return self._project.factory.successors(state, **run_args)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\factory.py", line 54, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\engines\hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\engines\vex\engine.py", line 148, in process
    opt_level=opt_level)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\engines\engine.py", line 60, in process
    self._process(new_state, successors, *args, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\engines\vex\engine.py", line 199, in _process
    self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\engines\vex\engine.py", line 315, in _handle_irsb
    exit_stmt_idx=DEFAULT_STATEMENT, exit_ins_addr=state.scratch.ins_addr)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\engines\successors.py", line 125, in add_successor
    self._categorize_successor(state)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\engines\successors.py", line 257, in _categorize_successor
    elif o.LAZY_SOLVES not in state.options and not state.satisfiable():
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\sim_state.py", line 513, in satisfiable
    return self.solver.satisfiable(**kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\state_plugins\sim_action_object.py", line 57, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\state_plugins\solver.py", line 87, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\angr\state_plugins\solver.py", line 640, in satisfiable
    return self._solver.satisfiable(extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\frontend_mixins\constraint_filter_mixin.py", line 34, in satisfiable
    return super(ConstraintFilterMixin, self).satisfiable(extra_constraints=ec, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\frontend_mixins\sat_cache_mixin.py", line 45, in satisfiable
    extra_constraints=extra_constraints, **kwargs
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\frontends\composite_frontend.py", line 314, in satisfiable
    return all(s.satisfiable(exact=exact) for s in self._solver_list)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\frontends\composite_frontend.py", line 314, in <genexpr>
    return all(s.satisfiable(exact=exact) for s in self._solver_list)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\frontend_mixins\sat_cache_mixin.py", line 45, in satisfiable
    extra_constraints=extra_constraints, **kwargs
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\frontend_mixins\model_cache_mixin.py", line 240, in satisfiable
    return super(ModelCacheMixin, self).satisfiable(extra_constraints=extra_constraints, **kwargs)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\frontends\full_frontend.py", line 102, in satisfiable
    solver=self._get_solver(), model_callback=self._model_hook
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\backends\__init__.py", line 640, in satisfiable
    return self._satisfiable(extra_constraints=self.convert_list(extra_constraints), solver=solver, model_callback=model_callback)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\claripy\backends\backend_z3.py", line 747, in _satisfiable
    if solver.check() != z3.sat:
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\z3\z3.py", line 6657, in check
    r = Z3_solver_check_assumptions(self.ctx.ref(), self.solver, num, _assumptions)
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\z3\z3core.py", line 3727, in Z3_solver_check_assumptions
    r = _elems.f(a0, a1, a2, a3)
OSError: [WinError -529697949] Windows Error 0xe06d7363

and afterwards a lot of 

> Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1678, in do_it
    def do_it(self, dbg):
  File "C:\Users\z003j5jx\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 834, in start
    def start(self):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 797, in pydev_start_new_thread
    def pydev_start_new_thread(self, function, args=(), kwargs={}):
RuntimeError: can't start new thread

I think it's an error with the Z3 engine or the compatibility of Windows and Z3. I tried to reinstall angr and z3-solver as well as my whole pythoninterpreter, but the problem remains.

Does anybody have an idea how to solve this?

**Comment by ltfish** [comment]
Can you try a 64-bit Python install instead?

**Comment by angrycodez** [comment]
Hey thank you very much for the (fast) reply! Sorry for the late answer, but this issue is with my pc at work and I haven't been here the last week.
Anyway, somehow the 64-bit Verison of python solved the problem!
