### ISSUE TITLE
Result of massive experiment: exception AttributeError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1803]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a 7zip renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-AttributeError xz](https://user-images.githubusercontent.com/3453847/68734799-dc745200-0598-11ea-9959-1969ecca6912.png)

**Comment by mborgerson** [comment]
There appear to be at least 7 different attribute errors embedded in this log:

```
     35 AttributeError: 'Const' object has no attribute 'tmp'
     29 AttributeError: items
    327 AttributeError: 'NoneType' object has no attribute 'addr'
      1 AttributeError: 'NoneType' object has no attribute 'normalize'
      1 AttributeError: 'NoneType' object has no attribute 'object'
     12 AttributeError: 'NotImplementedType' object has no attribute 'raw_to_bv'
      1 KeyError: <weakref at 0x7f427a6f7e08; to 'ASTCacheKey' at 0x7f427a6ac4e0>
```

Package most affected: libc6-mipsn32_2.24-11+deb9u4_mips.deb (271 failures). Multiple architectures are affected.

<details><summary><pre>AttributeError: 'Const' object has no attribute 'tmp'</pre></summary>
<pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/c/coinst/coinst_1.9.3-1+b1_armhf.deb
### Binary: ./usr/bin/coinst-upgrades
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 346, in _analysis_core_baremetal
self._job_queue_empty()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1123, in _job_queue_empty
self._process_unresolved_indirect_jumps()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2185, in _process_unresolved_indirect_jumps
all_targets |= self._process_one_indirect_jump(jump)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2211, in _process_one_indirect_jump
resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 456, in resolve
r, targets = self._resolve(cfg, addr, func_addr, b)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 574, in _resolve
stmts_adding_base_addr, all_addr_holders)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 950, in _try_resolve_targets
jumptable_addr = self._parse_load_statement(load_stmt, state)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 1308, in _parse_load_statement
guard_tmp = load_stmt.guard.tmp
AttributeError: 'Const' object has no attribute 'tmp'
```
</pre>
</details>


<details>
<summary><pre>
AttributeError: items
</pre></summary><pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/q/qwt/libqwt-qt5-6_6.1.2-6_mips.deb
### Binary: ./usr/lib/libqwt-qt5.so.6.1.2
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 346, in _analysis_core_baremetal
self._job_queue_empty()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1123, in _job_queue_empty
self._process_unresolved_indirect_jumps()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2185, in _process_unresolved_indirect_jumps
all_targets |= self._process_one_indirect_jump(jump)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2211, in _process_one_indirect_jump
resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 456, in resolve
r, targets = self._resolve(cfg, addr, func_addr, b)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 564, in _resolve
simgr.run()
File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 260, in run
self.step(stash=stash, **kwargs)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
result = current_hook(self.func.__self__, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/exploration_techniques/explorer.py", line 96, in step
return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
return self.func(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 344, in step
successors = self.step_state(state, successor_func=successor_func, **run_args)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
result = current_hook(self.func.__self__, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/exploration_techniques/slicecutor.py", line 36, in step_state
stashes = simgr.step_state(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
return self.func(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 382, in step_state
successors = self.successors(state, successor_func=successor_func, **run_args)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
result = current_hook(self.func.__self__, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/exploration_techniques/slicecutor.py", line 86, in successors
return simgr.successors(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
return self.func(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 421, in successors
return self._project.factory.successors(state, **run_args)
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 148, in process
opt_level=opt_level)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 199, in _process
self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 278, in _handle_irsb
cont = self._handle_statement(state, successors, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 393, in _handle_statement
exit_data = stmt_handler(self, state, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/statements/wrtmp.py", line 4, in SimIRStmt_WrTmp
data = engine.handle_expression(state, stmt.data)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 454, in handle_expression
result = handler(self, state, expr)
File "/home/angr/angr-dev/angr/angr/engines/vex/expressions/load.py", line 27, in SimIRExpr_Load
result = state.memory.load(addr, size, endness=expr.endness)
File "/home/angr/angr-dev/angr/angr/storage/memory.py", line 772, in load
mem_read_condition=condition_e, mem_read_endness=endness,
File "/home/angr/angr-dev/angr/angr/sim_state.py", line 336, in _inspect
self.inspect.action(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/inspect.py", line 268, in action
bp.fire(self.state)
File "/home/angr/angr-dev/angr/angr/state_plugins/inspect.py", line 220, in fire
self.action(state)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 371, in hook_before
state.memory.store(addr, self._var, endness=state.arch.memory_endness)
File "/home/angr/angr-dev/angr/angr/storage/memory.py", line 572, in store
self._store(request) #will use state_plugins/symbolic_memory.py
File "/home/angr/angr-dev/angr/angr/state_plugins/abstract_memory.py", line 408, in _store
address_wrappers = self.normalize_address(req.addr, is_write=True, convert_to_valueset=False)
File "/home/angr/angr-dev/angr/angr/state_plugins/abstract_memory.py", line 356, in normalize_address
addr_with_regions = self._normalize_address_type(addr)
File "/home/angr/angr-dev/angr/angr/state_plugins/abstract_memory.py", line 401, in _normalize_address_type
return addr_e._model_vsa.items()
File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 1001, in __getattr__
raise AttributeError(a)
AttributeError: items
</pre></details>


<details>
<summary><pre>
AttributeError: 'NoneType' object has no attribute 'addr'
</pre></summary><pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/x/xalan/libxalan-c111_1.11-6_armhf.deb
### Binary: ./usr/lib/arm-linux-gnueabihf/libxalan-c.so.111.0
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 225, in _analyze
self._post_analysis()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1168, in _post_analysis
self.make_functions()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1280, in make_functions
blockaddr_to_function
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1581, in _process_irrational_function_starts
self._merge_cfgnodes(cfgnode_0, cfgnode_1)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 337, in _merge_cfgnodes
assert cfgnode_0.addr + cfgnode_0.size == cfgnode_1.addr
AttributeError: 'NoneType' object has no attribute 'addr'
</pre></details>


<details>
<summary><pre>
KeyError: weakref at 0x7f427a6f7e08; to 'ASTCacheKey' at 0x7f427a6ac4e0
AttributeError: 'NoneType' object has no attribute 'normalize'
</pre></summary><pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/p/p7zip/p7zip-full_16.02+dfsg-3+deb9u1_armhf.deb
### Binary: ./usr/lib/p7zip/7z.so
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 339, in is_false
return self._false_cache[e.cache_key]
File "/home/angr/.virtualenvs/angr/lib/python3.6/weakref.py", line 394, in __getitem__
return self.data[ref(key)]
KeyError: <weakref at 0x7f427a6f7e08; to 'ASTCacheKey' at 0x7f427a6ac4e0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 346, in _analysis_core_baremetal
self._job_queue_empty()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1123, in _job_queue_empty
self._process_unresolved_indirect_jumps()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2185, in _process_unresolved_indirect_jumps
all_targets |= self._process_one_indirect_jump(jump)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2211, in _process_one_indirect_jump
resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 456, in resolve
r, targets = self._resolve(cfg, addr, func_addr, b)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 564, in _resolve
simgr.run()
File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 260, in run
self.step(stash=stash, **kwargs)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
result = current_hook(self.func.__self__, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/exploration_techniques/explorer.py", line 96, in step
return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
return self.func(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 344, in step
successors = self.step_state(state, successor_func=successor_func, **run_args)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
result = current_hook(self.func.__self__, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/exploration_techniques/slicecutor.py", line 36, in step_state
stashes = simgr.step_state(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
return self.func(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 382, in step_state
successors = self.successors(state, successor_func=successor_func, **run_args)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 75, in __call__
result = current_hook(self.func.__self__, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/exploration_techniques/slicecutor.py", line 86, in successors
return simgr.successors(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/misc/hookset.py", line 80, in __call__
return self.func(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/sim_manager.py", line 421, in successors
return self._project.factory.successors(state, **run_args)
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 148, in process
opt_level=opt_level)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 199, in _process
self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 278, in _handle_irsb
cont = self._handle_statement(state, successors, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 430, in _handle_statement
exit_stmt_idx=state.scratch.stmt_idx, exit_ins_addr=state.scratch.ins_addr)
File "/home/angr/angr-dev/angr/angr/engines/successors.py", line 120, in add_successor
self._preprocess_successor(state, add_guard=add_guard)
File "/home/angr/angr-dev/angr/angr/engines/successors.py", line 155, in _preprocess_successor
state.add_constraints(state.scratch.guard)
File "/home/angr/angr-dev/angr/angr/sim_state.py", line 458, in add_constraints
if self.solver.is_false(arg):
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 134, in concrete_shortcut_not_bool
return f(self, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
return f(*new_args, **new_kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 87, in wrapped_f
return f(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 606, in is_false
return self._solver.is_false(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/concrete_handler_mixin.py", line 60, in is_false
return super(ConcreteHandlerMixin, self).is_false(e, **kwargs)
File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/constraint_filter_mixin.py", line 64, in is_false
return super(ConstraintFilterMixin, self).is_false(e, extra_constraints=ec, **kwargs)
File "/home/angr/angr-dev/claripy/claripy/frontends/light_frontend.py", line 77, in is_false
return self._solver_backend.is_false(e)
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 341, in is_false
f = self._is_false(self.convert(e), extra_constraints=extra_constraints, solver=solver, model_callback=model_callback)
File "/home/angr/angr-dev/claripy/claripy/backends/backend_vsa.py", line 102, in convert
return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 196, in convert
r = self._call(ast.op, args)
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 250, in _call
obj = self._op_raw[op](*args)
File "/home/angr/angr-dev/claripy/claripy/backends/backend_vsa.py", line 326, in LShR
return expr.LShR(shift_amount)
File "/home/angr/angr-dev/claripy/claripy/vsa/strided_interval.py", line 1147, in LShR
return self.rshift_logical(shift_amount)
File "/home/angr/angr-dev/claripy/claripy/vsa/strided_interval.py", line 19, in processor
return f(self, *args, **kwargs)
File "/home/angr/angr-dev/claripy/claripy/vsa/strided_interval.py", line 2230, in rshift_logical
ret.normalize()
AttributeError: 'NoneType' object has no attribute 'normalize'
</pre></details>


<details>
<summary><pre>
AttributeError: 'NoneType' object has no attribute 'object'
</pre></summary><pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/k/kdepim/knotes_16.04.3-4~deb9u1_armhf.deb
### Binary: ./usr/bin/knotes
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 346, in _analysis_core_baremetal
self._job_queue_empty()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1123, in _job_queue_empty
self._process_unresolved_indirect_jumps()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2185, in _process_unresolved_indirect_jumps
all_targets |= self._process_one_indirect_jump(jump)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2211, in _process_one_indirect_jump
resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 456, in resolve
r, targets = self._resolve(cfg, addr, func_addr, b)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 574, in _resolve
stmts_adding_base_addr, all_addr_holders)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 935, in _try_resolve_targets
succ = project.factory.successors(r, whitelist=whitelist, last_stmt=last_stmt)
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 148, in process
opt_level=opt_level)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 199, in _process
self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 278, in _handle_irsb
cont = self._handle_statement(state, successors, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 393, in _handle_statement
exit_data = stmt_handler(self, state, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/statements/wrtmp.py", line 4, in SimIRStmt_WrTmp
data = engine.handle_expression(state, stmt.data)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 454, in handle_expression
result = handler(self, state, expr)
File "/home/angr/angr-dev/angr/angr/engines/vex/expressions/load.py", line 27, in SimIRExpr_Load
result = state.memory.load(addr, size, endness=expr.endness)
File "/home/angr/angr-dev/angr/angr/storage/memory.py", line 772, in load
mem_read_condition=condition_e, mem_read_endness=endness,
File "/home/angr/angr-dev/angr/angr/sim_state.py", line 336, in _inspect
self.inspect.action(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/inspect.py", line 268, in action
bp.fire(self.state)
File "/home/angr/angr-dev/angr/angr/state_plugins/inspect.py", line 220, in fire
self.action(state)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 1196, in _init_registers_on_demand
state.registers.replace_all(read_addr, new_read_addr)
File "/home/angr/angr-dev/angr/angr/state_plugins/symbolic_memory.py", line 1199, in replace_all
return self.mem.replace_all(old, new)
File "/home/angr/angr-dev/angr/angr/storage/paged_memory.py", line 833, in replace_all
memory_objects = self.memory_objects_for_name(v)
File "/home/angr/angr-dev/angr/angr/storage/paged_memory.py", line 1006, in memory_objects_for_name
return {self[i] for i in self.addrs_for_name(n)}
File "/home/angr/angr-dev/angr/angr/storage/paged_memory.py", line 1006, in <setcomp>
return {self[i] for i in self.addrs_for_name(n)}
File "/home/angr/angr-dev/angr/angr/storage/paged_memory.py", line 974, in addrs_for_name
if n in self[e].object.variables: yield e
AttributeError: 'NoneType' object has no attribute 'object'
</pre></details>

<details>
<summary><pre>
AttributeError: 'NotImplementedType' object has no attribute 'raw_to_bv'
</pre></summary><pre>
############################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/b/binutils-avr/binutils-avr_2.26.20160125+Atmel3.5.3-1_armhf.deb
### Binary: ./usr/lib/avr/bin/as
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 225, in _analyze
self._post_analysis()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1168, in _post_analysis
self.make_functions()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1276, in make_functions
blockaddr_to_function
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1459, in _process_irrational_functions
b = self.project.factory.successors(tmp_state, jumpkind='Ijk_Boring')
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 148, in process
opt_level=opt_level)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 199, in _process
self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 278, in _handle_irsb
cont = self._handle_statement(state, successors, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 393, in _handle_statement
exit_data = stmt_handler(self, state, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/statements/wrtmp.py", line 4, in SimIRStmt_WrTmp
data = engine.handle_expression(state, stmt.data)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 454, in handle_expression
result = handler(self, state, expr)
File "/home/angr/angr-dev/angr/angr/engines/vex/expressions/op.py", line 14, in SimIRExpr_Op
result = translate(state, expr.op, exprs)
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1045, in translate
return translate_inner(state, simop, s_args)
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1052, in translate_inner
return irop.calculate(*s_args)
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 373, in calculate
return self.extend_size(self._calculate(args))
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 459, in _op_vector_float_mapped
return claripy.Concat(*(self._op_float_mapped(rm_part + ca).raw_to_bv() for ca in chopped_args))
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 459, in <genexpr>
return claripy.Concat(*(self._op_float_mapped(rm_part + ca).raw_to_bv() for ca in chopped_args))
AttributeError: 'NotImplementedType' object has no attribute 'raw_to_bv'
</pre></details>
