### ISSUE TITLE
Result of massive experiment: exception claripy.errors.BackendError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1804]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-claripy errors BackendError xz](https://user-images.githubusercontent.com/3453847/68734829-f9a92080-0598-11ea-955b-71e9793286b9.png)

**Comment by mborgerson** [comment]
Only MIPS/MIPSEL appears to be affected. 18 instances. There appears to be a cascading sequence of errors in the exception handling:

```
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/c/catdoc/catdoc_0.94.3~git20160113.dbc9ec6+dfsg-1+deb9u1_mipsel.deb
### Binary: ./usr/bin/catppt
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "/home/angr/angr-dev/claripy/claripy/frontends/light_frontend.py", line 40, in eval
return tuple(self._solver_backend.eval(e, n))
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 498, in eval
self.convert(expr), n, extra_constraints=self.convert_list(extra_constraints),
File "/home/angr/angr-dev/claripy/claripy/backends/backend_concrete.py", line 83, in convert
return super().convert(expr)
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 161, in convert
converted = self._convert(ast)
File "/home/angr/angr-dev/claripy/claripy/backends/backend_concrete.py", line 114, in _convert
raise BackendError("can't handle AST of type %s" % type(a))
claripy.errors.BackendError: can't handle AST of type <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 87, in wrapped_f
return f(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 499, in _eval
return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/concrete_handler_mixin.py", line 7, in eval
return super(ConcreteHandlerMixin, self).eval(e, n, **kwargs)
File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/constraint_filter_mixin.py", line 40, in eval
return super(ConstraintFilterMixin, self).eval(e, n, extra_constraints=ec, **kwargs)
File "/home/angr/angr-dev/claripy/claripy/frontends/light_frontend.py", line 42, in eval
raise ClaripyFrontendError("Light solver can't handle this eval().")
claripy.errors.ClaripyFrontendError: Light solver can't handle this eval().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/angr/angr-dev/angr/angr/state_plugins/posix.py", line 360, in get_fd
fd = self.state.solver.eval_one(fd)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 739, in eval_one
return self.eval_exact(e, 1, **{k: v for (k, v) in kwargs.items() if k != 'default'})[0]
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 790, in eval_exact
r = self.eval_upto(e, n + 1, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 707, in eval_upto
cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 154, in concrete_shortcut_tuple
return f(self, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
return f(*new_args, **new_kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 91, in wrapped_f
raise SimSolverModeError("Claripy threw an error") from e
angr.errors.SimSolverModeError: Claripy threw an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 339, in is_false
return self._false_cache[e.cache_key]
File "/home/angr/.virtualenvs/angr/lib/python3.6/weakref.py", line 394, in __getitem__
return self.data[ref(key)]
KeyError: <weakref at 0x7f7b357d9188; to 'ASTCacheKey' at 0x7f7b357df710>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 225, in _analyze
self._post_analysis()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1168, in _post_analysis
self.make_functions()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1276, in make_functions
blockaddr_to_function
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1459, in _process_irrational_functions
b = self.project.factory.successors(tmp_state, jumpkind='Ijk_Boring')
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hook.py", line 55, in process
return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/procedure.py", line 31, in process
force_addr=force_addr)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/procedure.py", line 59, in _process
inst = procedure.execute(state, successors, ret_to=ret_to)
File "/home/angr/angr-dev/angr/angr/sim_procedure.py", line 230, in execute
r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
File "/home/angr/angr-dev/angr/angr/procedures/libc/fputc.py", line 15, in run
simfd = self.state.posix.get_fd(fileno)
File "/home/angr/angr-dev/angr/angr/state_plugins/posix.py", line 364, in get_fd
if not self.state.solver.satisfiable():
File "/home/angr/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
return f(*new_args, **new_kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 87, in wrapped_f
return f(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 640, in satisfiable
return self._solver.satisfiable(extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/constraint_filter_mixin.py", line 34, in satisfiable
return super(ConstraintFilterMixin, self).satisfiable(extra_constraints=ec, **kwargs)
File "/home/angr/angr-dev/claripy/claripy/frontends/light_frontend.py", line 85, in satisfiable
reversed(self.constraints + list(extra_constraints))
File "/home/angr/angr-dev/claripy/claripy/frontends/light_frontend.py", line 84, in <genexpr>
self._solver_backend.is_false(c) for c in
File "/home/angr/angr-dev/claripy/claripy/backends/backend_concrete.py", line 196, in is_false
return super().is_false(e, extra_constraints=extra_constraints, solver=solver, model_callback=model_callback)
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 341, in is_false
f = self._is_false(self.convert(e), extra_constraints=extra_constraints, solver=solver, model_callback=model_callback)
File "/home/angr/angr-dev/claripy/claripy/backends/backend_concrete.py", line 83, in convert
return super().convert(expr)
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 167, in convert
"conversion on a child node" % (self, ast.op, ast.__class__.__name__))
claripy.errors.BackendError: <claripy.backends.backend_concrete.BackendConcrete object at 0x7f7b399cd768> can't handle operation __eq__ (Bool) due to a failed conversion on a child node
```
