### ISSUE TITLE
Result of massive experiment: exception claripy.errors.ClaripyBalancerError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1805]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-claripy errors ClaripyBalancerError xz](https://user-images.githubusercontent.com/3453847/68734851-075ea600-0599-11ea-879f-e56dd42b7af2.png)

**Comment by mborgerson** [comment]
12 instances. Only armel, armhf are affected.

There are two errors embedded here:

```
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/o/odb/odb_2.4.0-5+b1_armel.deb
### Binary: ./usr/lib/gcc/arm-linux-gnueabi/6/plugin/odb.so
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "/home/angr/angr-dev/claripy/claripy/balancer.py", line 151, in _reverse_comparison
new_op = opposites[a.op]
KeyError: 'If'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 346, in _analysis_core_baremetal
self._job_queue_empty()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1123, in _job_queue_empty
self._process_unresolved_indirect_jumps()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2185, in _process_unresolved_indirect_jumps
all_targets |= self._process_one_indirect_jump(jump)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2211, in _process_one_indirect_jump
resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 456, in resolve
r, targets = self._resolve(cfg, addr, func_addr, b)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 574, in _resolve
stmts_adding_base_addr, all_addr_holders)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 935, in _try_resolve_targets
succ = project.factory.successors(r, whitelist=whitelist, last_stmt=last_stmt)
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 148, in process
opt_level=opt_level)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 199, in _process
self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 278, in _handle_irsb
cont = self._handle_statement(state, successors, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 393, in _handle_statement
exit_data = stmt_handler(self, state, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/statements/loadg.py", line 23, in SimIRStmt_LoadG
read_expr = state.memory.load(addr, read_size, endness=stmt.end, condition=guard != 0)
File "/home/angr/angr-dev/angr/angr/storage/memory.py", line 789, in load
events=not disable_actions, ret_on_segv=ret_on_segv)
File "/home/angr/angr-dev/angr/angr/state_plugins/abstract_memory.py", line 444, in _load
address_wrappers = self.normalize_address(addr, is_write=False, condition=condition)
File "/home/angr/angr-dev/angr/angr/state_plugins/abstract_memory.py", line 351, in normalize_address
addr = self._apply_condition_to_symbolic_addr(addr, condition)
File "/home/angr/angr-dev/angr/angr/state_plugins/abstract_memory.py", line 501, in _apply_condition_to_symbolic_addr
_, converted = self.state.solver.constraint_to_si(condition)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 87, in wrapped_f
return f(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
return f(*new_args, **new_kwargs)
File "/home/angr/angr-dev/claripy/claripy/ast/bool.py", line 207, in constraint_to_si
satisfiable, replace_list = backends.vsa.constraint_to_si(expr)
File "/home/angr/angr-dev/claripy/claripy/backends/backend_vsa.py", line 428, in constraint_to_si
return Balancer(self, expr).compat_ret
File "/home/angr/angr-dev/claripy/claripy/balancer.py", line 25, in __init__
self._doit()
File "/home/angr/angr-dev/claripy/claripy/balancer.py", line 211, in _doit
truism = self._adjust_truism(truism)
File "/home/angr/angr-dev/claripy/claripy/balancer.py", line 256, in _adjust_truism
swapped = Balancer._reverse_comparison(t)
File "/home/angr/angr-dev/claripy/claripy/balancer.py", line 153, in _reverse_comparison
raise ClaripyBalancerError("unable to reverse comparison %s (missing from 'opposites')" % a.op)
claripy.errors.ClaripyBalancerError: unable to reverse comparison If (missing from 'opposites')
```
