### ISSUE TITLE
Result of massive experiment: exception claripy.errors.ClaripyTypeError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1806]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-claripy errors ClaripyTypeError xz](https://user-images.githubusercontent.com/3453847/68734862-13e2fe80-0599-11ea-9849-4ce020a2529f.png)

**Comment by mborgerson** [comment]
52 instances. Only armhf affected. There are uniq backtrace paths, but the error is the same.

```
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/j/jackd2/libjack-jackd2-0_1.9.10+20150825git1ed50c92~dfsg-5_armhf.deb
### Binary: ./usr/lib/arm-linux-gnueabihf/libjack.so.0.1.0
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 225, in _analyze
self._post_analysis()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1168, in _post_analysis
self.make_functions()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1276, in make_functions
blockaddr_to_function
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1459, in _process_irrational_functions
b = self.project.factory.successors(tmp_state, jumpkind='Ijk_Boring')
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 148, in process
opt_level=opt_level)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 199, in _process
self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 278, in _handle_irsb
cont = self._handle_statement(state, successors, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 393, in _handle_statement
exit_data = stmt_handler(self, state, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/statements/loadg.py", line 33, in SimIRStmt_LoadG
read_expr = state.solver.If(guard != 0, converted_expr, alt)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 87, in wrapped_f
return f(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
return f(*new_args, **new_kwargs)
File "/home/angr/angr-dev/claripy/claripy/ast/bool.py", line 99, in If
raise ClaripyTypeError("sized arguments to If must have the same length")
claripy.errors.ClaripyTypeError: sized arguments to If must have the same length
```


```
##############################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/p/pgn2web/pgn2web_0.4-1.1+b2_armhf.deb
### Binary: ./usr/bin/p2wgui
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 370, in _analysis_core_baremetal
self._process_job_and_get_successors(job_info)
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 388, in _process_job_and_get_successors
successors = self._get_successors(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1050, in _get_successors
jobs = self._scan_block(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1344, in _scan_block
entries = self._scan_irsb(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1537, in _scan_irsb
stmt_idx
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1705, in _create_jobs
target_addr, jumpkind, is_syscall=is_syscall
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1740, in _create_job_call
successors = self._simulate_block_with_resilience(tmp_state)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1859, in _simulate_block_with_resilience
successors = self.project.factory.successors(state, skip_stmts=stmt_idx)
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 148, in process
opt_level=opt_level)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 199, in _process
self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 278, in _handle_irsb
cont = self._handle_statement(state, successors, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 393, in _handle_statement
exit_data = stmt_handler(self, state, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/statements/loadg.py", line 33, in SimIRStmt_LoadG
read_expr = state.solver.If(guard != 0, converted_expr, alt)
File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 87, in wrapped_f
return f(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
return f(*new_args, **new_kwargs)
File "/home/angr/angr-dev/claripy/claripy/ast/bool.py", line 99, in If
raise ClaripyTypeError("sized arguments to If must have the same length")
claripy.errors.ClaripyTypeError: sized arguments to If must have the same length
```
