### ISSUE TITLE
Result of massive experiment: exception claripy.errors.ClaripyZeroDivisionError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1807]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-claripy errors ClaripyZeroDivisionError xz](https://user-images.githubusercontent.com/3453847/68734881-265d3800-0599-11ea-9246-bde789e87056.png)

**Comment by mborgerson** [comment]
Only amd64 affected. 2 instances.

```
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/d/dosbox/dosbox_0.74-4.2+deb9u2_amd64.deb
### Binary: ./usr/bin/dosbox
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 373, in calculate
return self.extend_size(self._calculate(args))
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 728, in _op_divmod
quotient = (args[0] // claripy.ZeroExt(self._from_size - self._to_size, args[1]))
File "/home/angr/angr-dev/claripy/claripy/operations.py", line 67, in _op
return return_type(name, fixed_args, **kwargs)
File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 153, in __new__
r = operations._handle_annotations(eb._abstract(eb.call(op, args)), args)
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 239, in call
return self._call(op, converted)
File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 259, in _call
obj = getattr(operator, op)(*args)
File "/home/angr/angr-dev/claripy/claripy/bv.py", line 42, in normalize_helper
return f(self, o)
File "/home/angr/angr-dev/claripy/claripy/bv.py", line 16, in compare_guard
return f(self, o)
File "/home/angr/angr-dev/claripy/claripy/bv.py", line 120, in __floordiv__
raise ClaripyZeroDivisionError()
claripy.errors.ClaripyZeroDivisionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 225, in _analyze
self._post_analysis()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1168, in _post_analysis
self.make_functions()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1276, in make_functions
blockaddr_to_function
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 1459, in _process_irrational_functions
b = self.project.factory.successors(tmp_state, jumpkind='Ijk_Boring')
File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
return self.project.engines.successors(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
r = engine.process(state, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 148, in process
opt_level=opt_level)
File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
self._process(new_state, successors, *args, **kwargs)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 199, in _process
self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 278, in _handle_irsb
cont = self._handle_statement(state, successors, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 393, in _handle_statement
exit_data = stmt_handler(self, state, stmt)
File "/home/angr/angr-dev/angr/angr/engines/vex/statements/wrtmp.py", line 4, in SimIRStmt_WrTmp
data = engine.handle_expression(state, stmt.data)
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 454, in handle_expression
result = handler(self, state, expr)
File "/home/angr/angr-dev/angr/angr/engines/vex/expressions/op.py", line 14, in SimIRExpr_Op
result = translate(state, expr.op, exprs)
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1045, in translate
return translate_inner(state, simop, s_args)
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1052, in translate_inner
return irop.calculate(*s_args)
File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 375, in calculate
raise SimZeroDivisionException("divide by zero!") from e
angr.errors.SimZeroDivisionException: divide by zero!
```
