### ISSUE TITLE
Result of massive experiment: exception IndexError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1808]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-IndexError xz](https://user-images.githubusercontent.com/3453847/68734896-307f3680-0599-11ea-80c8-939697d84a5c.png)

**Comment by mborgerson** [comment]
14 instances. 4 different errors. armhf, mips64el, mips, mipsel, amd64 affected.

```
      1 IndexError: 35
      1 IndexError: 59
      3 IndexError: list index out of range
      9 IndexError: tuple index out of range
```

<details><summary><pre>
      1 IndexError: 35
</pre></summary><pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/p/pulseaudio/pulseaudio_10.0-1+deb9u1_armhf.deb
### Binary: ./usr/lib/pulse-10.0/modules/module-ladspa-sink.so
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 370, in _analysis_core_baremetal
self._process_job_and_get_successors(job_info)
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 388, in _process_job_and_get_successors
successors = self._get_successors(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1050, in _get_successors
jobs = self._scan_block(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1344, in _scan_block
entries = self._scan_irsb(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1456, in _scan_irsb
addr, function_addr, cfg_node, irsb = self._generate_cfgnode(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 3353, in _generate_cfgnode
irsb = lifted_block.vex_nostmt
File "/home/angr/angr-dev/angr/angr/block.py", line 179, in vex_nostmt
collect_data_refs=self._collect_data_refs,
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 621, in lift
collect_data_refs=collect_data_refs,
File "/home/angr/angr-dev/pyvex/pyvex/lifting/__init__.py", line 152, in lift
collect_data_refs=collect_data_refs,
File "/home/angr/angr-dev/pyvex/pyvex/lifting/__init__.py", line 178, in lift
final_irsb.extend(more_irsb)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 211, in extend
convert_expr(e)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 196, in convert_expr
return RdTmp.get_instance(convert_tmp(expr_.tmp))
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 184, in convert_tmp
tmp_type = extendwith.tyenv.lookup(tmp)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 565, in lookup
raise IndexError(tmp)
IndexError: 35
</pre></details>



<details><summary><pre>
      1 IndexError: 59
</pre></summary><pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/g/gcl/gcl_2.6.12-47_armhf.deb
### Binary: ./usr/lib/gcl-2.6.12/unixport/saved_ansi_gcl
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 370, in _analysis_core_baremetal
self._process_job_and_get_successors(job_info)
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 388, in _process_job_and_get_successors
successors = self._get_successors(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1050, in _get_successors
jobs = self._scan_block(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1344, in _scan_block
entries = self._scan_irsb(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1456, in _scan_irsb
addr, function_addr, cfg_node, irsb = self._generate_cfgnode(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 3353, in _generate_cfgnode
irsb = lifted_block.vex_nostmt
File "/home/angr/angr-dev/angr/angr/block.py", line 179, in vex_nostmt
collect_data_refs=self._collect_data_refs,
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 621, in lift
collect_data_refs=collect_data_refs,
File "/home/angr/angr-dev/pyvex/pyvex/lifting/__init__.py", line 152, in lift
collect_data_refs=collect_data_refs,
File "/home/angr/angr-dev/pyvex/pyvex/lifting/__init__.py", line 178, in lift
final_irsb.extend(more_irsb)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 211, in extend
convert_expr(e)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 196, in convert_expr
return RdTmp.get_instance(convert_tmp(expr_.tmp))
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 184, in convert_tmp
tmp_type = extendwith.tyenv.lookup(tmp)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 565, in lookup
raise IndexError(tmp)
IndexError: 59
</pre></details>



<details><summary><pre>
      3 IndexError: list index out of range
</pre></summary><pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/g/gnat-mingw-w64/gnat-mingw-w64-i686_6.3.0-18+19.4+b3_armhf.deb
### Binary: ./usr/bin/i686-w64-mingw32-gnat-posix
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 370, in _analysis_core_baremetal
self._process_job_and_get_successors(job_info)
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 388, in _process_job_and_get_successors
successors = self._get_successors(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1050, in _get_successors
jobs = self._scan_block(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1344, in _scan_block
entries = self._scan_irsb(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1456, in _scan_irsb
addr, function_addr, cfg_node, irsb = self._generate_cfgnode(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 3353, in _generate_cfgnode
irsb = lifted_block.vex_nostmt
File "/home/angr/angr-dev/angr/angr/block.py", line 179, in vex_nostmt
collect_data_refs=self._collect_data_refs,
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 621, in lift
collect_data_refs=collect_data_refs,
File "/home/angr/angr-dev/pyvex/pyvex/lifting/__init__.py", line 152, in lift
collect_data_refs=collect_data_refs,
File "/home/angr/angr-dev/pyvex/pyvex/lifting/__init__.py", line 178, in lift
final_irsb.extend(more_irsb)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 211, in extend
convert_expr(e)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 196, in convert_expr
return RdTmp.get_instance(convert_tmp(expr_.tmp))
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 184, in convert_tmp
tmp_type = extendwith.tyenv.lookup(tmp)
File "/home/angr/angr-dev/pyvex/pyvex/block.py", line 566, in lookup
return self.types[tmp]
IndexError: list index out of range
</pre></details>



<details><summary><pre>
      9 IndexError: tuple index out of range
</pre></summary><pre>
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/p/polyml/polyml_5.6-8_mips64el.deb
### Binary: ./usr/bin/poly
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 370, in _analysis_core_baremetal
self._process_job_and_get_successors(job_info)
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 388, in _process_job_and_get_successors
successors = self._get_successors(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1050, in _get_successors
jobs = self._scan_block(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1344, in _scan_block
entries = self._scan_irsb(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1537, in _scan_irsb
stmt_idx
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1611, in _create_jobs
current_function_addr, stmt_idx)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2154, in _indirect_jump_encountered
ins_addr = cfg_node.instruction_addrs[-2]
IndexError: tuple index out of range
</pre></details>
