### ISSUE TITLE
Result of massive experiment: exception KeyError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1809]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-KeyError xz](https://user-images.githubusercontent.com/3453847/68734911-3c6af880-0599-11ea-8f8d-02c214601ff5.png)

**Comment by mborgerson** [comment]
Just one failure here:

```
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/h/hyperscan/libhyperscan4_4.4.1-1_amd64.deb
### Binary: ./usr/lib/libhs_runtime.so.4.4.1
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 346, in _analysis_core_baremetal
self._job_queue_empty()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1123, in _job_queue_empty
self._process_unresolved_indirect_jumps()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2185, in _process_unresolved_indirect_jumps
all_targets |= self._process_one_indirect_jump(jump)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2211, in _process_one_indirect_jump
resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 456, in resolve
r, targets = self._resolve(cfg, addr, func_addr, b)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 510, in _resolve
stmts_to_instrument, regs_to_initialize = self._jumptable_precheck(b)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 852, in _jumptable_precheck
engine.process(state, block=block, whitelist=stmt_whitelist)
File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 35, in process
self._process(state, None, block=kwargs.pop('block', None), whitelist=kwargs.pop('whitelist', None))
File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 69, in _process
self._process_Stmt(whitelist=whitelist)
File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 90, in _process_Stmt
self._handle_Stmt(stmt)
File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 106, in _handle_Stmt
getattr(self, handler)(stmt)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 147, in _handle_WrTmp
super()._handle_WrTmp(stmt)
File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 112, in _handle_WrTmp
data = self._expr(stmt.data)
File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 138, in _expr
return getattr(self, handler)(expr)
File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 175, in _handle_Unop
if simop is not None and simop.op_attrs['conversion']:
KeyError: 'conversion'
```
