### ISSUE TITLE
Result of massive experiment: exception TypeError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1810]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-TypeError xz](https://user-images.githubusercontent.com/3453847/68734928-47be2400-0599-11ea-92e5-dd8a7b19246c.png)

**Comment by mborgerson** [comment]
```
      6 TypeError: '<' not supported between instances of 'int' and 'NoneType'
      7 TypeError: '>' not supported between instances of 'NoneType' and 'int'
      1 TypeError: object of type 'NoneType' has no len()
```
```
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/a/aolserver4-nsopenssl/aolserver4-nsopenssl_3.0beta26-6_mipsel.deb
### Binary: ./usr/lib/aolserver4/bin/nsopenssl.so
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 225, in _analyze
self._post_analysis()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1241, in _post_analysis
r = self._tidy_data_references()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 2152, in _tidy_data_references
content_holder=content_holder)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 2232, in _guess_data_type
elfheader_sort, elfheader_size = self._guess_data_type_elfheader(data_addr, max_size)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 2359, in _guess_data_type_elfheader
if data_addr == obj.min_addr and 4 < max_size < 1000:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
```
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/g/ganeti/ganeti-haskell-2.15_2.15.2-7+deb9u3_amd64.deb
### Binary: ./usr/lib/ganeti/2.15/usr/sbin/ganeti-confd
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 370, in _analysis_core_baremetal
self._process_job_and_get_successors(job_info)
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 388, in _process_job_and_get_successors
successors = self._get_successors(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1050, in _get_successors
jobs = self._scan_block(job)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1344, in _scan_block
entries = self._scan_irsb(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1456, in _scan_irsb
addr, function_addr, cfg_node, irsb = self._generate_cfgnode(cfg_job, current_func_addr)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 3410, in _generate_cfgnode
and len(irsb_string) >= 2 \
TypeError: object of type 'NoneType' has no len()
```
```
################################################################################
### EVENT: CFG_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/k/ksh/ksh_93u+20120801-3.1_armhf.deb
### Binary: ./bin/ksh93
### Function: NONE - NONE
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 59, in doit_raw
cfg = elf.analyses.CFG(data_references=True, cross_references=True)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg.py", line 55, in __init__
CFGFast.__init__(self, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 643, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 218, in _analyze
self._analysis_core_baremetal()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 346, in _analysis_core_baremetal
self._job_queue_empty()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1123, in _job_queue_empty
self._process_unresolved_indirect_jumps()
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2185, in _process_unresolved_indirect_jumps
all_targets |= self._process_one_indirect_jump(jump)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2211, in _process_one_indirect_jump
resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 456, in resolve
r, targets = self._resolve(cfg, addr, func_addr, b)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 574, in _resolve
stmts_adding_base_addr, all_addr_holders)
File "/home/angr/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 981, in _try_resolve_targets
if total_cases > self._max_targets:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
