### ISSUE TITLE
Result of massive experiment: exception angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1812]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-angr analyses decompiler structured_codegen UnsupportedNodeTypeError xz](https://user-images.githubusercontent.com/3453847/68735001-8c49bf80-0599-11ea-9672-cabd2bc31cc1.png)

**Comment by mborgerson** [comment]
```
      6 angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError: Node type <class 'angr.analyses.decompiler.structured_codegen.CBinaryOp'> is not supported yet.
     21 angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError: Node type <class 'angr.analyses.decompiler.structured_codegen.CVariable'> is not supported yet.
      4 angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError: Node type <class 'angr.engines.light.data.ArithmeticExpression'> is not supported yet.
    663 angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError: Node type <class 'int'> is not supported yet.
```

```
################################################################################
### EVENT: DECOMPILER_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/g/glibc/libc6-x32_2.24-11+deb9u4_i386.deb
### Binary: ./libx32/libnsl-2.24.so
### Function: nis_print_group - 0x406610
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 73, in doit_raw
decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
self._decompile()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 36, in _decompile
codegen = self.project.analyses.StructuredCodeGenerator(self.func, s.result, cfg=self._cfg, kb=self.kb)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 859, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 863, in _analyze
obj = self._handle(self._sequence)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 971, in _handle_Condition
true_node=self._handle(condition_node.true_node) if condition_node.true_node else None,
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 943, in _handle_Code
return self._handle(code.node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 961, in _handle_Loop
return CDoWhileLoop(self._handle(loop_node.condition),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1114, in _handle_Expr_UnaryOp
return CUnaryOp(expr.op, self._handle(expr.operand),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1120, in _handle_Expr_BinaryOp
return CBinaryOp(expr.op, self._handle(expr.operands[0]), self._handle(expr.operands[1]),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1096, in _handle_Expr_Load
variable, offset = self._parse_load_addr(expr.addr)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 917, in _parse_load_addr
return self._parse_load_addr(expr.expr)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 898, in _parse_load_addr
expr = self._handle(addr)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 939, in _handle
raise UnsupportedNodeTypeError("Node type %s is not supported yet." % type(node))
angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError: Node type <class 'angr.analyses.decompiler.structured_codegen.CBinaryOp'> is not supported yet.
```

```
################################################################################
### EVENT: DECOMPILER_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/g/glibc/libc6-x32_2.24-11+deb9u4_i386.deb
### Binary: ./libx32/libnsl-2.24.so
### Function: yp_order - 0x404ae0
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 73, in doit_raw
decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
self._decompile()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 36, in _decompile
codegen = self.project.analyses.StructuredCodeGenerator(self.func, s.result, cfg=self._cfg, kb=self.kb)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 859, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 863, in _analyze
obj = self._handle(self._sequence)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 971, in _handle_Condition
true_node=self._handle(condition_node.true_node) if condition_node.true_node else None,
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 943, in _handle_Code
return self._handle(code.node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 970, in _handle_Condition
code = CIfElse(self._handle(condition_node.condition),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1120, in _handle_Expr_BinaryOp
return CBinaryOp(expr.op, self._handle(expr.operands[0]), self._handle(expr.operands[1]),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1096, in _handle_Expr_Load
variable, offset = self._parse_load_addr(expr.addr)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 917, in _parse_load_addr
return self._parse_load_addr(expr.expr)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 898, in _parse_load_addr
expr = self._handle(addr)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 939, in _handle
raise UnsupportedNodeTypeError("Node type %s is not supported yet." % type(node))
angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError: Node type <class 'angr.analyses.decompiler.structured_codegen.CVariable'> is not supported yet.

```

```
###############################################################################
### EVENT: DECOMPILER_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/w/wpa/wpasupplicant_2.4-1+deb9u4_amd64.deb
### Binary: ./sbin/wpa_cli
### Function: _wpa_ctrl_command - 0x407310
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 73, in doit_raw
decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
self._decompile()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 36, in _decompile
codegen = self.project.analyses.StructuredCodeGenerator(self.func, s.result, cfg=self._cfg, kb=self.kb)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 859, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 863, in _analyze
obj = self._handle(self._sequence)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 971, in _handle_Condition
true_node=self._handle(condition_node.true_node) if condition_node.true_node else None,
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 943, in _handle_Code
return self._handle(code.node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 971, in _handle_Condition
true_node=self._handle(condition_node.true_node) if condition_node.true_node else None,
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 943, in _handle_Code
return self._handle(code.node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 971, in _handle_Condition
true_node=self._handle(condition_node.true_node) if condition_node.true_node else None,
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 943, in _handle_Code
return self._handle(code.node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 970, in _handle_Condition
code = CIfElse(self._handle(condition_node.condition),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1120, in _handle_Expr_BinaryOp
return CBinaryOp(expr.op, self._handle(expr.operands[0]), self._handle(expr.operands[1]),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1091, in _handle_Expr_Load
offset = self._handle(expr.offset)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 939, in _handle
raise UnsupportedNodeTypeError("Node type %s is not supported yet." % type(node))
angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError: Node type <class 'angr.engines.light.data.ArithmeticExpression'> is not supported yet.
```

```
################################################################################
### EVENT: DECOMPILER_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/o/ocfs2-tools/ocfs2-tools_1.8.4-4+deb9u1_i386.deb
### Binary: ./usr/bin/o2info
### Function: get_fs_features_ioctl - 0x403040
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 73, in doit_raw
decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
self._decompile()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 36, in _decompile
codegen = self.project.analyses.StructuredCodeGenerator(self.func, s.result, cfg=self._cfg, kb=self.kb)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 859, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 863, in _analyze
obj = self._handle(self._sequence)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 950, in _handle_Sequence
lines.append(self._handle(node))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 970, in _handle_Condition
code = CIfElse(self._handle(condition_node.condition),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1120, in _handle_Expr_BinaryOp
return CBinaryOp(expr.op, self._handle(expr.operands[0]), self._handle(expr.operands[1]),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1120, in _handle_Expr_BinaryOp
return CBinaryOp(expr.op, self._handle(expr.operands[0]), self._handle(expr.operands[1]),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1120, in _handle_Expr_BinaryOp
return CBinaryOp(expr.op, self._handle(expr.operands[0]), self._handle(expr.operands[1]),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1139, in _handle_Expr_Convert
return CTypeCast(None, dst_type, self._handle(expr.operand))
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1120, in _handle_Expr_BinaryOp
return CBinaryOp(expr.op, self._handle(expr.operands[0]), self._handle(expr.operands[1]),
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 938, in _handle
return handler(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 1091, in _handle_Expr_Load
offset = self._handle(expr.offset)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structured_codegen.py", line 939, in _handle
raise UnsupportedNodeTypeError("Node type %s is not supported yet." % type(node))
angr.analyses.decompiler.structured_codegen.UnsupportedNodeTypeError: Node type <class 'int'> is not supported yet.
```
