### ISSUE TITLE
Result of massive experiment: exception angr.analyses.decompiler.structurer.EmptyBlockNotice during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1813]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-angr analyses decompiler structurer EmptyBlockNotice xz](https://user-images.githubusercontent.com/3453847/68735046-abe0e800-0599-11ea-8896-3a92e3ec0c68.png)

**Comment by mborgerson** [comment]
```
  14474 raise EmptyBlockNotice()
```

They all appear to be this same path:
```
################################################################################
### EVENT: DECOMPILER_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/s/strongswan/strongswan-libcharon_5.5.1-4+deb9u4_i386.deb
### Binary: ./usr/lib/ipsec/libcharon.so.0.0.0
### Function: authorize - 0x409fe0
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 73, in doit_raw
decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
self._decompile()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
self._analyze_cyclic()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 285, in _analyze_cyclic
loop_node = self._make_endless_loop(loop_head, loop_subgraph, successors)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 374, in _make_endless_loop
loop_body = self._to_loop_body_sequence(loop_head, loop_subgraph, loop_successors)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 454, in _to_loop_body_sequence
last_stmt = self._get_last_statement(node)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 782, in _get_last_statement
raise EmptyBlockNotice()
angr.analyses.decompiler.structurer.EmptyBlockNotice
```
