### ISSUE TITLE
Result of massive experiment: exception angr.errors.SimEngineError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1814]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-angr errors SimEngineError xz](https://user-images.githubusercontent.com/3453847/68735061-b602e680-0599-11ea-8eff-64d0a8754626.png)

**Comment by mborgerson** [comment]
```
   7734 ### EVENT: DECOMPILER_FAIL

   7734 angr.errors.SimEngineError: No bytes in memory for block starting at <addr>
```

```
################################################################################
### EVENT: DECOMPILER_FAIL
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/p/pytango/python3-tango_9.2.0-2_armel.deb
### Binary: ./usr/lib/python3/dist-packages/tango/_tango.cpython-35m-arm-linux-gnueabi.so
### Function: _ZN5boost7numeric20def_overflow_handlerclENS0_18range_check_resultE.isra.28 - 0x78d930
### Exception:
Traceback (most recent call last):
File "./process.py", line 21, in catcher
yield
File "./process.py", line 73, in doit_raw
decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
self._decompile()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 25, in _decompile
sp_tracker_track_memory=self._sp_tracker_track_memory)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 46, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 90, in _analyze
spt = self._track_stack_pointers()
File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 117, in _track_stack_pointers
spt = self.project.analyses.StackPointerTracker(self.function, regs, track_memory=self._sp_tracker_track_memory)
File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
oself.__init__(*args, **kwargs)
File "/home/angr/angr-dev/angr/angr/analyses/stack_pointer_tracker.py", line 267, in __init__
self._analyze()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 223, in _analyze
self._analysis_core_graph()
File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 242, in _analysis_core_graph
changed, output_state = self._run_on_node(n, job_state)
File "/home/angr/angr-dev/angr/angr/analyses/stack_pointer_tracker.py", line 403, in _run_on_node
for stmt in block.vex.statements:
File "/home/angr/angr-dev/angr/angr/block.py", line 155, in vex
collect_data_refs=self._collect_data_refs,
File "/home/angr/angr-dev/angr/angr/engines/vex/engine.py", line 606, in lift
raise SimEngineError("No bytes in memory for block starting at %#x." % addr)
angr.errors.SimEngineError: No bytes in memory for block starting at 0x78d9ac.
```
