### ISSUE TITLE
Result of massive experiment: exception angr.errors.SimOperationError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1815]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-angr errors SimOperationError xz](https://user-images.githubusercontent.com/3453847/68735085-c915b680-0599-11ea-95e3-57b361dca8c8.png)

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 25098

   11383 angr.errors.SimOperationError
   10365 angr.errors.SimOperationError: VEX output size doesn't match detected output size
    1976 angr.errors.SimOperationError: no implementation found for operation CmpLT
    1144 angr.errors.SimOperationError: no implementation found for operation CmpLE
     230 angr.errors.SimOperationError: no implementation found for operation CmpUN


Sample of angr.errors.SimOperationError (11383 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/j/jigit/libjte1_1.20-2+b1_arm64.deb
    ### Binary: ./usr/lib/libjte.so.1.0.0
    ### Function: mk_MD5Transform - 0x404fa8
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 25, in _decompile
    sp_tracker_track_memory=self._sp_tracker_track_memory)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 46, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 92, in _analyze
    self._convert_all()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 129, in _convert_all
    ail_block = self._convert(block_node)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 148, in _convert
    ail_block = ailment.IRSBConverter.convert(block.vex, self._ail_manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 252, in convert
    converted = VEXStmtConverter.convert(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 167, in convert
    return func(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 173, in WrTmp
    reg = VEXExprConverter.convert(stmt.data, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 38, in convert
    return func(expr, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 82, in Unop
    op_name = VEXExprConverter.generic_name_from_vex_op(expr.op)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 27, in generic_name_from_vex_op
    return vexop_to_simop(vex_op)._generic_name
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1031, in vexop_to_simop
    raise SimOperationError
    angr.errors.SimOperationError


Sample of angr.errors.SimOperationError: VEX output size doesn't match detected output size (10365 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/p/pd-py/pd-py_0.2.0+git20161103.1.d0e0648f-1_ppc64el.deb
    ### Binary: ./usr/lib/pd/extra/py/py.pd_linux
    ### Function: .LTHUNK3 - 0x410100
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 25, in _decompile
    sp_tracker_track_memory=self._sp_tracker_track_memory)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 46, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 92, in _analyze
    self._convert_all()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 129, in _convert_all
    ail_block = self._convert(block_node)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 148, in _convert
    ail_block = ailment.IRSBConverter.convert(block.vex, self._ail_manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 252, in convert
    converted = VEXStmtConverter.convert(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 167, in convert
    return func(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 173, in WrTmp
    reg = VEXExprConverter.convert(stmt.data, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 38, in convert
    return func(expr, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 102, in Binop
    op = VEXExprConverter.generic_name_from_vex_op(expr.op)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 27, in generic_name_from_vex_op
    return vexop_to_simop(vex_op)._generic_name
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1032, in vexop_to_simop
    res = SimIROp(op, **attrs)
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 219, in __init__
    raise SimOperationError("VEX output size doesn't match detected output size")
    angr.errors.SimOperationError: VEX output size doesn't match detected output size


Sample of angr.errors.SimOperationError: no implementation found for operation CmpLT (1976 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/r/ruby-rmagick/ruby-rmagick_2.16.0-2+b1_amd64.deb
    ### Binary: ./usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.3.0/RMagick2.so
    ### Function: blend_geometry.constprop.2 - 0x421540
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 25, in _decompile
    sp_tracker_track_memory=self._sp_tracker_track_memory)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 46, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 92, in _analyze
    self._convert_all()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 129, in _convert_all
    ail_block = self._convert(block_node)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 148, in _convert
    ail_block = ailment.IRSBConverter.convert(block.vex, self._ail_manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 252, in convert
    converted = VEXStmtConverter.convert(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 167, in convert
    return func(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 173, in WrTmp
    reg = VEXExprConverter.convert(stmt.data, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 38, in convert
    return func(expr, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 102, in Binop
    op = VEXExprConverter.generic_name_from_vex_op(expr.op)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 27, in generic_name_from_vex_op
    return vexop_to_simop(vex_op)._generic_name
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1032, in vexop_to_simop
    res = SimIROp(op, **attrs)
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 295, in __init__
    raise SimOperationError("no implementation found for operation {}".format(self._generic_name))
    angr.errors.SimOperationError: no implementation found for operation CmpLT


Sample of angr.errors.SimOperationError: no implementation found for operation CmpLE (1144 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/n/nvidia-texture-tools/libnvtt2_2.0.8-1+dfsg-8.1+b1_amd64.deb
    ### Binary: ./usr/lib/x86_64-linux-gnu/libnvmath.so.2.0.8
    ### Function: _ZL15planeBoxOverlapRKN2nv7Vector3ES2_S2_ - 0x401290
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 25, in _decompile
    sp_tracker_track_memory=self._sp_tracker_track_memory)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 46, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 92, in _analyze
    self._convert_all()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 129, in _convert_all
    ail_block = self._convert(block_node)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 148, in _convert
    ail_block = ailment.IRSBConverter.convert(block.vex, self._ail_manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 252, in convert
    converted = VEXStmtConverter.convert(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 167, in convert
    return func(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 173, in WrTmp
    reg = VEXExprConverter.convert(stmt.data, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 38, in convert
    return func(expr, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 102, in Binop
    op = VEXExprConverter.generic_name_from_vex_op(expr.op)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 27, in generic_name_from_vex_op
    return vexop_to_simop(vex_op)._generic_name
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1032, in vexop_to_simop
    res = SimIROp(op, **attrs)
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 295, in __init__
    raise SimOperationError("no implementation found for operation {}".format(self._generic_name))
    angr.errors.SimOperationError: no implementation found for operation CmpLE


Sample of angr.errors.SimOperationError: no implementation found for operation CmpUN (230 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/p/pcl/libpcl-visualization1.8_1.8.0+dfsg1-3+b2_amd64.deb
    ### Binary: ./usr/lib/x86_64-linux-gnu/libpcl_visualization.so.1.8.0
    ### Function: _ZNK5Eigen10MatrixBaseINS_5BlockIKNS_6MatrixIfLi4ELi1ELi0ELi4ELi1EEELi3ELi1ELb0EEEE10stableNormEv - 0x4ec2f0
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 25, in _decompile
    sp_tracker_track_memory=self._sp_tracker_track_memory)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 46, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 92, in _analyze
    self._convert_all()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 129, in _convert_all
    ail_block = self._convert(block_node)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 148, in _convert
    ail_block = ailment.IRSBConverter.convert(block.vex, self._ail_manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 252, in convert
    converted = VEXStmtConverter.convert(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 167, in convert
    return func(idx, stmt, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 173, in WrTmp
    reg = VEXExprConverter.convert(stmt.data, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 38, in convert
    return func(expr, manager)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 102, in Binop
    op = VEXExprConverter.generic_name_from_vex_op(expr.op)
    File "/home/angr/angr-dev/ailment/ailment/converter.py", line 27, in generic_name_from_vex_op
    return vexop_to_simop(vex_op)._generic_name
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 1032, in vexop_to_simop
    res = SimIROp(op, **attrs)
    File "/home/angr/angr-dev/angr/angr/engines/vex/irop.py", line 295, in __init__
    raise SimOperationError("no implementation found for operation {}".format(self._generic_name))
    angr.errors.SimOperationError: no implementation found for operation CmpUN
```
