### ISSUE TITLE
Result of massive experiment: exception AssertionError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1817]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-AssertionError xz](https://user-images.githubusercontent.com/3453847/68735128-ec406600-0599-11ea-900b-4ba607a5b18d.png)

SHAME

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 382380

  382374 AssertionError
       5 Arguments: ()
       1 AssertionError: <unprintable AssertionError object>


Sample of AssertionError (382374 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/d/diffutils/diffutils_3.5-3_i386.deb
    ### Binary: ./usr/bin/cmp
    ### Function: block_read - 0x405200
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 283, in _analyze_cyclic
    assert len(successors) <= 1
    AssertionError


Sample of Arguments: () (5 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/v/vflib3/vflib3_3.6.14.dfsg-3+nmu3_mipsel.deb
    ### Binary: ./usr/lib/libVFlib3.so.5.4.6
    ### Function: vf_sexp_cstring2list - 0x41f8b8
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 283, in _analyze_cyclic
    assert len(successors) <= 1
    AssertionError--- Logging error ---
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 283, in _analyze_cyclic
    assert len(successors) <= 1
    AssertionError
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/stopit/signalstop.py", line 29, in handle_timeout
    'value (%d seconds).' % self.seconds)
    stopit.utils.TimeoutException: Block exceeded maximum timeout value (5 seconds).
    Call stack:
    File "./process.py", line 97, in <module>
    if doit(_pkg_name, _elf_path, _dbg_path) == "TIMEOUT":
    File "./process.py", line 85, in doit
    return doit_raw(pkg_name, elf_path, dbg_path, timeout=timeout) #pylint:disable=unexpected-keyword-arg
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/stopit/utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
    File "./process.py", line 79, in doit_raw
    awesome_info(f"DECOMPILER_SUCCESS: {id_str}")
    File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
    File "./process.py", line 25, in catcher
    awesome_error(s, exc_info=True)
    File "./process.py", line 42, in awesome_error
    awesome_log(logging.ERROR, msg, **kwargs)
    File "./process.py", line 32, in awesome_log
    l.log(lvl, msg, **kwargs)
    File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
    File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
    File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
    File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
    File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
    File "/home/angr/angr-dev/angr/angr/misc/loggers.py", line 70, in emit
    super(CuteHandler, self).emit(record)
    Message: '\x1b[35mDECOMPILER_FAIL: function=vf_sexp_cstring2list address=0x41f8b8 progress=206/698 elf=./usr/lib/libVFlib3.so.5.4.6 dbg=./usr/lib/debug/.build-id/9b/ef4bd4f148f25cfa7eccaf947d553f42f1a897.debug pkg=http://cdn-fastly.deb.debian.org/debian/pool/main/v/vflib3/vflib3_3.6.14.dfsg-3+nmu3_mipsel.deb\x1b[0m'
    Arguments: ()


Sample of AssertionError: <unprintable AssertionError object> (1 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/liba/libapreq2/libapache2-request-perl_2.13-5+b1_mips.deb
    ### Binary: ./usr/lib/mips-linux-gnu/perl5/5.24/auto/APR/Request/Request.so
    ### Function: XS_APR__Request_upload_hook - 0x4052d8
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 283, in _analyze_cyclic
    assert len(successors) <= 1
    AssertionError: <unprintable AssertionError object>
```
