### ISSUE TITLE
Result of massive experiment: exception claripy.errors.ClaripyRecursionError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1819]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-claripy errors ClaripyRecursionError xz](https://user-images.githubusercontent.com/3453847/68735160-05491700-059a-11ea-8d18-078b15bde851.png)

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 51

      51 claripy.errors.ClaripyRecursionError: Recursion limit reached. Sorry about that.


Sample of claripy.errors.ClaripyRecursionError: Recursion limit reached. Sorry about that. (51 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/d/diffutils/diffutils_3.5-3_i386.deb
    ### Binary: ./usr/bin/cmp
    ### Function: proper_name_utf8 - 0x4037b0
    ### Exception:
    Traceback (most recent call last):
    File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 196, in convert
    r = self._call(ast.op, args)
    File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 259, in _call
    obj = getattr(operator, op)(*args)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 928, in __eq__
    a, b = _coerce_exprs(self, other)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 1094, in _coerce_exprs
    s = _coerce_expr_merge(s, b)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 1072, in _coerce_expr_merge
    s1 = a.sort()
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 3248, in sort
    return BitVecSortRef(Z3_get_sort(self.ctx_ref(), self.as_ast()), self.ctx)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 312, in __init__
    Z3_inc_ref(self.ctx.ref(), self.as_ast())
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 516, in as_ast
    return Z3_sort_to_ast(self.ctx_ref(), self.ast)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3core.py", line 2500, in Z3_sort_to_ast
    r = _elems.f(a0, a1)
    ctypes.ArgumentError: argument 2: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds).
    The above exception was the direct cause of the following exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 268, in _analyze
    self._analyze_acyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 294, in _analyze_acyclic
    self._recover_reaching_conditions()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 556, in _recover_reaching_conditions
    reaching_conditions[node] = self._simplify_condition(reaching_condition)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 932, in _simplify_condition
    claripy_simplified = claripy.simplify(cond)
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 1016, in simplify
    s = e._first_backend('simplify')
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 951, in _first_backend
    try: return getattr(b, what)(self)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 70, in z3_condom
    return f(*args, **kwargs)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 968, in simplify
    expr_raw = self.convert(expr)
    File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 209, in convert
    raise ClaripyRecursionError("Recursion limit reached. Sorry about that.") from e
    claripy.errors.ClaripyRecursionError: Recursion limit reached. Sorry about that.
```
