### ISSUE TITLE
Result of massive experiment: exception claripy.errors.ClaripyZ3Error during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1820]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-claripy errors ClaripyZ3Error xz](https://user-images.githubusercontent.com/3453847/68735207-2dd11100-059a-11ea-9e88-d18178eb61ed.png)

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 8

       8 claripy.errors.ClaripyZ3Error


Sample of claripy.errors.ClaripyZ3Error (8 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/s/samba/samba_4.5.16+dfsg-1+deb9u2_amd64.deb
    ### Binary: ./usr/lib/x86_64-linux-gnu/samba/libkdc-samba4.so.2.0.0
    ### Function: decode_DigestInitReply - 0x414f70
    ### Exception:
    Traceback (most recent call last):
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 70, in z3_condom
    return f(*args, **kwargs)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 975, in simplify
    s = boolref_tactics(expr_raw).as_expr()
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 7634, in as_expr
    return self[0].as_expr()
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 5452, in as_expr
    return And([ self.get(i) for i in range(len(self)) ], self.ctx)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 1713, in And
    args  = _coerce_expr_list(args, ctx)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 1113, in _coerce_expr_list
    alist = [ _py2expr(a, ctx) for a in alist ]
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 1113, in <listcomp>
    alist = [ _py2expr(a, ctx) for a in alist ]
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 2909, in _py2expr
    _z3_assert(False, "Python bool, int, long or float expected")
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 98, in _z3_assert
    raise Z3Exception(msg)
    z3.z3types.Z3Exception: Python bool, int, long or float expected
    The above exception was the direct cause of the following exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 268, in _analyze
    self._analyze_acyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 299, in _analyze_acyclic
    self._make_ites(seq)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 655, in _make_ites
    cond_ = claripy.simplify(claripy.Not(rcond_0) == rcond_1)
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 1016, in simplify
    s = e._first_backend('simplify')
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 951, in _first_backend
    try: return getattr(b, what)(self)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 72, in z3_condom
    raise ClaripyZ3Error() from ze
    claripy.errors.ClaripyZ3Error
```
