### ISSUE TITLE
Result of massive experiment: exception ctypes.ArgumentError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1821]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-ctypes ArgumentError xz](https://user-images.githubusercontent.com/3453847/68735221-3aee0000-059a-11ea-9bf6-366982189d00.png)

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 367

     191 ctypes.ArgumentError: argument 1: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds).
     164 ctypes.ArgumentError: argument 2: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds).
      12 ctypes.ArgumentError: argument 3: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds).


Sample of ctypes.ArgumentError: argument 1: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds). (191 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/s/searchmonkey/searchmonkey_0.8.1-9+b1_amd64.deb
    ### Binary: ./usr/bin/searchmonkey
    ### Function: dereferenceAbsolutes - 0x4211b0
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 285, in _analyze_cyclic
    loop_node = self._make_endless_loop(loop_head, loop_subgraph, successors)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 374, in _make_endless_loop
    loop_body = self._to_loop_body_sequence(loop_head, loop_subgraph, loop_successors)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 510, in _to_loop_body_sequence
    structurer = self.project.analyses.Structurer(region)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 268, in _analyze
    self._analyze_acyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 299, in _analyze_acyclic
    self._make_ites(seq)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 655, in _make_ites
    cond_ = claripy.simplify(claripy.Not(rcond_0) == rcond_1)
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 1016, in simplify
    s = e._first_backend('simplify')
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 951, in _first_backend
    try: return getattr(b, what)(self)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 70, in z3_condom
    return f(*args, **kwargs)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 975, in simplify
    s = boolref_tactics(expr_raw).as_expr()
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 7711, in __call__
    return self.apply(goal, *arguments, **keywords)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 7696, in apply
    goal = _to_goal(goal)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 7724, in _to_goal
    goal.add(a)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 5341, in add
    self.assert_exprs(*args)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 5305, in assert_exprs
    s    = BoolSort(self.ctx)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 1550, in BoolSort
    return BoolSortRef(Z3_mk_bool_sort(ctx.ref()), ctx)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 312, in __init__
    Z3_inc_ref(self.ctx.ref(), self.as_ast())
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 516, in as_ast
    return Z3_sort_to_ast(self.ctx_ref(), self.ast)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3core.py", line 2500, in Z3_sort_to_ast
    r = _elems.f(a0, a1)
    ctypes.ArgumentError: argument 1: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds).


Sample of ctypes.ArgumentError: argument 2: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds). (164 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/c/calcurse/calcurse_4.2.1-1.1_i386.deb
    ### Binary: ./usr/bin/calcurse
    ### Function: fork_exec - 0x429a30
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 268, in _analyze
    self._analyze_acyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 299, in _analyze_acyclic
    self._make_ites(seq)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 655, in _make_ites
    cond_ = claripy.simplify(claripy.Not(rcond_0) == rcond_1)
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 1016, in simplify
    s = e._first_backend('simplify')
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 951, in _first_backend
    try: return getattr(b, what)(self)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 70, in z3_condom
    return f(*args, **kwargs)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 986, in simplify
    o = self._abstract(s)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 70, in z3_condom
    return f(*args, **kwargs)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 392, in _abstract
    return self._abstract_internal(e.ctx.ctx, e.ast)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in _abstract_internal
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 426, in <listcomp>
    children = [ self._abstract_internal(ctx, z3.Z3_get_app_arg(ctx, ast, i), new_split_on) for i in range(num_args) ]
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 423, in _abstract_internal
    num_args = z3.Z3_get_app_num_args(ctx, ast)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3core.py", line 2715, in Z3_get_app_num_args
    r = _elems.f(a0, a1)
    ctypes.ArgumentError: argument 2: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds).


Sample of ctypes.ArgumentError: argument 3: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds). (12 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/g/gnupg2/gnupg_2.1.18-8~deb9u4_i386.deb
    ### Binary: ./usr/bin/gpgconf
    ### Function: strtokenize - 0x40c4d0
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 285, in _analyze_cyclic
    loop_node = self._make_endless_loop(loop_head, loop_subgraph, successors)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 374, in _make_endless_loop
    loop_body = self._to_loop_body_sequence(loop_head, loop_subgraph, loop_successors)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 510, in _to_loop_body_sequence
    structurer = self.project.analyses.Structurer(region)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 268, in _analyze
    self._analyze_acyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 299, in _analyze_acyclic
    self._make_ites(seq)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 655, in _make_ites
    cond_ = claripy.simplify(claripy.Not(rcond_0) == rcond_1)
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 1016, in simplify
    s = e._first_backend('simplify')
    File "/home/angr/angr-dev/claripy/claripy/ast/base.py", line 951, in _first_backend
    try: return getattr(b, what)(self)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 70, in z3_condom
    return f(*args, **kwargs)
    File "/home/angr/angr-dev/claripy/claripy/backends/backend_z3.py", line 975, in simplify
    s = boolref_tactics(expr_raw).as_expr()
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 7711, in __call__
    return self.apply(goal, *arguments, **keywords)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3.py", line 7701, in apply
    return ApplyResult(Z3_tactic_apply(self.ctx.ref(), self.tactic, goal.goal), self.ctx)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/z3core.py", line 3571, in Z3_tactic_apply
    r = _elems.f(a0, a1, a2)
    ctypes.ArgumentError: argument 3: <class 'stopit.utils.TimeoutException'>: Block exceeded maximum timeout value (5 seconds).
```
