### ISSUE TITLE
Result of massive experiment: exception IndexError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1823]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-IndexError xz](https://user-images.githubusercontent.com/3453847/68735253-5bb65580-059a-11ea-9a33-e7840143adb5.png)

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 3550

    3550 IndexError: list index out of range


Sample of IndexError: list index out of range (3550 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/libt/libtasn1-6/libtasn1-6_4.10-1.1+deb9u1_armel.deb
    ### Binary: ./usr/lib/arm-linux-gnueabi/libtasn1.so.6.5.3
    ### Function: _asn1_set_default_tag - 0x40abd0
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 287, in _analyze_cyclic
    loop_node = self._refine_loop(loop_node)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 385, in _refine_loop
    r, loop_node = self._refine_loop_while(loop_node)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 402, in _refine_loop_while
    first_node = loop_node.sequence_node.nodes[0]
    IndexError: list index out of range
```
