### ISSUE TITLE
Result of massive experiment: exception StopIteration during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1828]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is an xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.

![DECOMPILER_FAIL-StopIteration xz](https://user-images.githubusercontent.com/3453847/68735590-70471d80-059b-11ea-97cd-c8a6c4b786e8.png)

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 140

     140 StopIteration


Sample of StopIteration (140 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/c/calibre/calibre-bin_2.75.1+dfsg-1_mips.deb
    ### Binary: ./usr/lib/calibre/calibre/plugins/dukpy.so
    ### Function: duk_get_buffer - 0x425f6c
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 28, in _decompile
    ri = self.project.analyses.RegionIdentifier(self.func, graph=clinic.graph, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/region_identifier.py", line 156, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/region_identifier.py", line 193, in _analyze
    self._update_start_node(graph)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/region_identifier.py", line 207, in _update_start_node
    self._start_node = next(n for n in graph.nodes() if graph.in_degree(n) == 0)
    StopIteration
```
