### ISSUE TITLE
Result of massive experiment: exception stopit.utils.TimeoutException during function decompilation (decompiler timeout)

### ISSUE THREAD

**Issue by zardus** [angr/angr#1829]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is an xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-stopit utils TimeoutException xz](https://user-images.githubusercontent.com/3453847/68735608-7e953980-059b-11ea-98cb-1a9e71c39542.png)

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 9

       9 Arguments: ()


Sample of Arguments: () (9 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/w/wmtv/wmtv_0.6.6-1_armel.deb
    ### Binary: ./usr/bin/wmtv
    ### Function: DoFullScreen - 0x40596c
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 285, in _analyze_cyclic
    loop_node = self._make_endless_loop(loop_head, loop_subgraph, successors)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 374, in _make_endless_loop
    loop_body = self._to_loop_body_sequence(loop_head, loop_subg--- Logging error ---
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 31, in _decompile
    rs = self.project.analyses.RecursiveStructurer(ri.region, kb=self.kb)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 203, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 230, in _analyze
    st = self.project.analyses.Structurer(current_region, parent_map=parent_map)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 261, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 266, in _analyze
    self._analyze_cyclic()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 285, in _analyze_cyclic
    loop_node = self._make_endless_loop(loop_head, loop_subgraph, successors)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 374, in _make_endless_loop
    loop_body = self._to_loop_body_sequence(loop_head, loop_subgraph, loop_successors)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/structurer.py", line 501, in _to_loop_body_sequence
    raise Exception()
    Exception
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/stopit/signalstop.py", line 29, in handle_timeout
    'value (%d seconds).' % self.seconds)
    stopit.utils.TimeoutException: Block exceeded maximum timeout value (5 seconds).
    Call stack:
    File "./process.py", line 97, in <module>
    if doit(_pkg_name, _elf_path, _dbg_path) == "TIMEOUT":
    File "./process.py", line 85, in doit
    return doit_raw(pkg_name, elf_path, dbg_path, timeout=timeout) #pylint:disable=unexpected-keyword-arg
    File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/stopit/utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
    File "./process.py", line 79, in doit_raw
    awesome_info(f"DECOMPILER_SUCCESS: {id_str}")
    File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
    File "./process.py", line 25, in catcher
    awesome_error(s, exc_info=True)
    File "./process.py", line 42, in awesome_error
    awesome_log(logging.ERROR, msg, **kwargs)
    File "./process.py", line 32, in awesome_log
    l.log(lvl, msg, **kwargs)
    File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
    File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
    File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
    File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
    File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
    File "/home/angr/angr-dev/angr/angr/misc/loggers.py", line 70, in emit
    super(CuteHandler, self).emit(record)
    Message: '\x1b[35mDECOMPILER_FAIL: function=DoFullScreen address=0x40596c progress=36/74 elf=./usr/bin/wmtv dbg=./usr/lib/debug/.build-id/34/eaf9c68e8cd02c969f3953d751850cc9ba8047.debug pkg=http://cdn-fastly.deb.debian.org/debian/pool/main/w/wmtv/wmtv_0.6.6-1_armel.deb\x1b[0m'
    Arguments: ()
```
