### ISSUE TITLE
Result of massive experiment: exception ZeroDivisionError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1832]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![DECOMPILER_FAIL-ZeroDivisionError xz](https://user-images.githubusercontent.com/3453847/68735703-b8fed680-059b-11ea-9079-8ed6388a0452.png)

**Comment by mborgerson** [comment]
```
Summary
=====================================
Num records: 42

      42 ZeroDivisionError: integer division or modulo by zero


Sample of ZeroDivisionError: integer division or modulo by zero (42 occurences): 
    ### EVENT: DECOMPILER_FAIL
    ### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/m/movit/libmovit5_1.4.0-1_amd64.deb
    ### Binary: ./usr/lib/x86_64-linux-gnu/libmovit.so.5.0.0
    ### Function: _ZN5movit24SingleResamplePassEffectC2EPNS_14ResampleEffectE - 0x455ad0
    ### Exception:
    Traceback (most recent call last):
    File "./process.py", line 21, in catcher
    yield
    File "./process.py", line 73, in doit_raw
    decompilation = elf.analyses.Decompiler(cfg.functions[a], cfg=cfg)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 14, in __init__
    self._decompile()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/decompiler.py", line 25, in _decompile
    sp_tracker_track_memory=self._sp_tracker_track_memory)
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 46, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 96, in _analyze
    self._recover_and_link_variables()
    File "/home/angr/angr-dev/angr/angr/analyses/decompiler/clinic.py", line 237, in _recover_and_link_variables
    vr = self.project.analyses.VariableRecoveryFast(self.function, clinic=self, kb=tmp_kb)  # pylint:disable=unused-variable
    File "/home/angr/angr-dev/angr/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
    File "/home/angr/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 616, in __init__
    self._analyze()
    File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 223, in _analyze
    self._analysis_core_graph()
    File "/home/angr/angr-dev/angr/angr/analyses/forward_analysis/__init__.py", line 242, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
    File "/home/angr/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 700, in _run_on_node
    self._process_block(state, block)
    File "/home/angr/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 738, in _process_block
    processor.process(state, block=block, fail_fast=self._fail_fast)
    File "/home/angr/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 101, in process
    self._process(state, None, block=kwargs.pop('block', None))
    File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 530, in _process
    self._process_Stmt(whitelist=whitelist)
    File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 547, in _process_Stmt
    self._ail_handle_Stmt(stmt)
    File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 571, in _ail_handle_Stmt
    getattr(self, handler)(stmt)
    File "/home/angr/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 403, in _ail_handle_Assignment
    data = self._expr(stmt.src)
    File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 553, in _expr
    return getattr(self, handler)(expr)
    File "/home/angr/angr-dev/angr/angr/analyses/variable_recovery/variable_recovery_fast.py", line 470, in _ail_handle_BinaryOp
    r = super()._ail_handle_BinaryOp(expr)
    File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 617, in _ail_handle_BinaryOp
    return handler(expr)
    File "/home/angr/angr-dev/angr/angr/engines/light/engine.py", line 685, in _ail_handle_Div
    return expr_0 // expr_1
    ZeroDivisionError: integer division or modulo by zero
```
