### ISSUE TITLE
unicorn_engine: ValueError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by Phasip** [angr/angr#1841]
---

**Describe the bug.**
Unicorn_engine throws "ValueError: cannot fit 'int' into an index-sized integer"

Command:
`python3 ./main.py ./a.out`
Output:
```
...
I: 125
Traceback (most recent call last):
  File "/home/phasip/main.py", line 39, in <module>
    simgr.step()
  File "/home/phasip/angr-dev/angr/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/phasip/angr-dev/angr/angr/sim_manager.py", line 382, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
  File "/home/phasip/angr-dev/angr/angr/sim_manager.py", line 421, in successors
    return self._project.factory.successors(state, **run_args)
  File "/home/phasip/angr-dev/angr/angr/factory.py", line 54, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/phasip/angr-dev/angr/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/phasip/angr-dev/angr/angr/engines/unicorn.py", line 40, in process
    force_addr=force_addr)
  File "/home/phasip/angr-dev/angr/angr/engines/engine.py", line 60, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/phasip/angr-dev/angr/angr/engines/unicorn.py", line 133, in _process
    state.unicorn.finish()
  File "/home/phasip/angr-dev/angr/angr/state_plugins/unicorn_engine.py", line 1078, in finish
    self.state.history.recent_bbl_addrs = bbl_addrs[:self.steps]
ValueError: cannot fit 'int' into an index-sized integer
```

**Environment Information.**
Ubuntu 18.04.3 LTS \n \l

Attached in version_info is the current git revisions of all angr-dev installed modules

**To Reproduce.**
Run command above from attached files

**Additional context.**
[angr_bugreport2.tar.gz](https://github.com/angr/angr/files/3843626/angr_bugreport2.tar.gz)
Attachment contains binary, script and version information

**Comment by rhelmot** [comment]
fixed. thanks for reporting!
