### ISSUE TITLE
angr.errors.SimZeroDivisionException: divide by zero! when generating CFG

### ISSUE THREAD

**Issue by DongShuaike** [angr/angr#1877]
Hi, I met this problem when generating the cfg for a shared library on MIPS
The angr version I used is the latest copied from `angr-dev` repository.
The error message is as below
```
Traceback (most recent call last):
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/irop.py", line 377, in calculate
    return self.extend_size(self._calculate(args))
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/irop.py", line 731, in _op_divmod
    quotient = (args[0].SDiv(claripy.SignExt(self._from_size - self._to_size, args[1])))
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/claripy/operations.py", line 65, in _op
    return return_type(name, fixed_args, **kwargs)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/claripy/ast/base.py", line 152, in __new__
    r = operations._handle_annotations(eb._abstract(eb.call(op, args)), args)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/claripy/backends/__init__.py", line 238, in call
    return self._call(op, converted)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/claripy/backends/__init__.py", line 249, in _call
    obj = self._op_raw[op](*args)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/claripy/bv.py", line 40, in normalize_helper
    return f(self, o)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/claripy/bv.py", line 15, in compare_guard
    return f(self, o)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/claripy/bv.py", line 414, in SDiv
    raise ClaripyZeroDivisionError()
claripy.errors.ClaripyZeroDivisionError
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/analysis.py", line 109, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/cfg/cfg.py", line 55, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1074, in __init__
    self._analyze()
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/forward_analysis.py", line 583, in _analyze
    self._analysis_core_baremetal()
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/forward_analysis.py", line 708, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/forward_analysis.py", line 726, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1465, in _get_successors
    jobs = self._scan_block(job)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1741, in _scan_block
    entries = self._scan_irsb(cfg_job, current_func_addr)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1927, in _scan_irsb
    stmt_idx
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 2095, in _create_jobs
    target_addr, jumpkind, is_syscall=is_syscall
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 2130, in _create_job_call
    succ = next(iter(succ for succ in self.project.factory.successors(tmp_state).flat_successors
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/factory.py", line 54, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/engine.py", line 146, in process
    opt_level=opt_level)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/engine.py", line 60, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/engine.py", line 197, in _process
    self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/engine.py", line 276, in _handle_irsb
    cont = self._handle_statement(state, successors, stmt)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/engine.py", line 391, in _handle_statement
    exit_data = stmt_handler(self, state, stmt)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/statements/wrtmp.py", line 4, in SimIRStmt_WrTmp
    data = engine.handle_expression(state, stmt.data)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/engine.py", line 452, in handle_expression
    result = handler(self, state, expr)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/expressions/op.py", line 14, in SimIRExpr_Op
    result = translate(state, expr.op, exprs)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/irop.py", line 968, in translate
    return translate_inner(state, simop, s_args)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/irop.py", line 975, in translate_inner
    return irop.calculate(*s_args)
  File "/home/dsk/.virtualenvs/angr/local/lib/python3.7/site-packages/angr/engines/vex/irop.py", line 379, in calculate
    raise SimZeroDivisionException("divide by zero!") from e
angr.errors.SimZeroDivisionException: divide by zero!
```
The binary is uploaded below.
[libmidware.zip](https://github.com/angr/angr/files/3972445/libmidware.zip)

**Comment by DongShuaike** [comment]
Dear @rhelmot and @ltfish , sorry that I made a mistake of taking the wrong version of angr.

This has been solved using the latest angr-dev .
