### ISSUE TITLE
Possible Erroneous Error Messages

### ISSUE THREAD

**Issue by jpc0016** [angr/angr#1882]
---

As mentioned in Slack, I get this error message when loading a MIPS 32-bit little endian binary:

```
$ python3 solve.py 
ERROR   | 2019-12-19 14:34:38,037 | archinfo.arch | Please look up and add dynamic tag type 0x70000036 for MIPS32
ERROR   | 2019-12-19 14:34:38,270 | archinfo.arch | Please look up and add dynamic tag type 0x70000036 for MIPS32
WARNING | 2019-12-19 14:34:38,574 | angr.state_plugins.symbolic_memory | The program is accessing memory or registers with an unspecified value. This could indicate unwanted behavior.
WARNING | 2019-12-19 14:34:38,574 | angr.state_plugins.symbolic_memory | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2019-12-19 14:34:38,574 | angr.state_plugins.symbolic_memory | 1) setting a value to the initial state
WARNING | 2019-12-19 14:34:38,574 | angr.state_plugins.symbolic_memory | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2019-12-19 14:34:38,574 | angr.state_plugins.symbolic_memory | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY_REGISTERS}, to suppress these messages.
WARNING | 2019-12-19 14:34:38,574 | angr.state_plugins.symbolic_memory | Filling register s1 with 4 unconstrained bytes referenced from 0x400b98 (main+0x330 in ch27.bin (0x400b98))
WARNING | 2019-12-19 14:34:38,575 | angr.state_plugins.symbolic_memory | Filling register s0 with 4 unconstrained bytes referenced from 0x400b9c (main+0x334 in ch27.bin (0x400b9c))
WARNING | 2019-12-19 14:34:38,600 | angr.state_plugins.symbolic_memory | Filling register s8 with 4 unconstrained bytes referenced from 0x400870 (main+0x8 in ch27.bin (0x400870))
WARNING | 2019-12-19 14:34:38,606 | angr.state_plugins.symbolic_memory | Filling memory at 0x400d04 with 192 unconstrained bytes referenced from 0x4000000 (puts+0x0 in extern-address space (0x0))
WARNING | 2019-12-19 14:34:38,626 | angr.state_plugins.symbolic_memory | Filling memory at 0x400dc4 with 28 unconstrained bytes referenced from 0x4000000 (puts+0x0 in extern-address space (0x0))
WARNING | 2019-12-19 14:34:38,709 | angr.state_plugins.symbolic_memory | Filling memory at 0x7ffeff74 with 8 unconstrained bytes referenced from 0x40000a4 (strlen+0x0 in extern-address space (0xa4))
WARNING | 2019-12-19 14:34:38,709 | angr.state_plugins.symbolic_memory | Filling memory at 0x7ffeff48 with 32 unconstrained bytes referenced from 0x40000a4 (strlen+0x0 in extern-address space (0xa4))
WARNING | 2019-12-19 14:34:38,710 | angr.state_plugins.symbolic_memory | Filling memory at 0x7ffeff3c with 4 unconstrained bytes referenced from 0x40000a4 (strlen+0x0 in extern-address space (0xa4))
WARNING | 2019-12-19 14:34:38,710 | angr.state_plugins.symbolic_memory | Filling memory at 0x7ffeff34 with 4 unconstrained bytes referenced from 0x40000a4 (strlen+0x0 in extern-address space (0xa4))
Traceback (most recent call last):
  File "solve.py", line 40, in <module>
    main(sys.argv)
  File "solve", line 37, in main
    raise Exception('Could not find the solution')
Exception: Could not find the solution
```

This is a rootme challenge binary: https://www.root-me.org/en/Challenges/Cracking/ELF-MIPS-Basic-Crackme?lang=en
I only need to know if the binary loads correctly despite the two error lines.  If it loads correctly, the error output could be misleading.  Below is my code for context.

```
import angr
import sys
import monkeyhex

def main(argv):
    # initialize path to binary (string)
    path_to_binary = '/home/ch27.bin'

    # create project object
    project = angr.Project(path_to_binary, use_sim_procedures=True)

    # tell angr where to start executing the binary
    initial_state = project.factory.entry_state()

    # create simulation manager initialized with initial state
    simulation = project.factory.simgr(initial_state)

    # explore the simulation to find victory address
    print_good_address = 0x4007c0
    simulation.explore(find=print_good_address)

    # if a solution is found, a list of possible solutions will be set to solution_state
    if simulation.found:
        solution_state = simulation.found[0]

        # print string to stdin
        print(solution_state.posix.dumps(sys.stdin.fileno()))
    else:
        # show message if no solution found
        raise Exception('Could not find the solution')

if __name__ == '__main__':
    main(sys.argv)
```

**Comment by rhelmot** [comment]
Hi, sorry to take so long to get back to this, but some part of that website seems to be down, and even after making an account (...) I can't actually download the challenge. Can you please just upload the binary?
