### ISSUE TITLE
Fnsave not handled gracefully

### ISSUE THREAD

**Issue by edmcman** [angr/angr#1945]
---

**Describe the bug.**

angr throws an unexpected (to me) exception when encountering the fnsave dirty operation.

**Environment Information.**

```
(angr) ed@ed-Precision-7540:~/Documents/Angry-CodeReuse$ python -m angr.misc.bug_report
angr environment report
=============================
Date: 2020-01-28 16:38:59.278730
Running in virtual environment at /home/ed/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
######## angr #########
Python found it in /home/ed/Documents/angr-dev/angr/angr
Pip version angr 8.20.1.7
Git info:
	Current commit e8fce35efae0e82977cc3e2be78421d6494f9d20 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/ed/Documents/angr-dev/ailment/ailment
Pip version ailment 8.20.1.7
Git info:
	Current commit c696edc9f31ecccaaa36b1e40ca1bed6c9715242 from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/ed/Documents/angr-dev/cle/cle
Pip version cle 8.20.1.7
Git info:
	Current commit cef99a76c01ba24f89d9b3042ee7e06b1f625b17 from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/ed/Documents/angr-dev/pyvex/pyvex
Pip version pyvex 8.20.1.7
Git info:
	Current commit a4413e49420d108fef31c42286e8b80c57424807 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/ed/Documents/angr-dev/claripy/claripy
Pip version claripy 8.20.1.7
Git info:
	Current commit b6eabc37aed7c2989faf12406a247004b5849216 from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/ed/Documents/angr-dev/archinfo/archinfo
Pip version archinfo 8.20.1.7
Git info:
	Current commit 1db8e3c200e9346b2902b9d929bbd2676113b72e from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/ed/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/ed/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/ed/Documents/angr-dev/angr/angr/lib/angr_native.so', handle 3204220 at 0x7f3e9fa38358>
unicorn: <CDLL '/home/ed/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 29624c0 at 0x7f3ea582fa90>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f3ea67bdf28>
z3: <CDLL '/home/ed/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 2b8b800 at 0x7f3ea3681fd0>
```

**To Reproduce.**

``` python
#!/usr/bin/env python

import angr

proj = angr.Project('/bin/true')
st = proj.factory.blank_state(addr=0x4049d3)
st.step()
```
[true.zip](https://github.com/angr/angr/files/4124731/true.zip)

**Additional context.**

Here's the rather ugly error:
```
(angr) ed@ed-Precision-7540:~/Documents/Angry-CodeReuse$ python fnsave.py 
WARNING | 2020-01-28 16:37:28,226 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2020-01-28 16:37:28,794 | angr.state_plugins.symbolic_memory | The program is accessing memory or registers with an unspecified value. This could indicate unwanted behavior.
WARNING | 2020-01-28 16:37:28,794 | angr.state_plugins.symbolic_memory | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2020-01-28 16:37:28,794 | angr.state_plugins.symbolic_memory | 1) setting a value to the initial state
WARNING | 2020-01-28 16:37:28,794 | angr.state_plugins.symbolic_memory | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2020-01-28 16:37:28,795 | angr.state_plugins.symbolic_memory | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY_REGISTERS}, to suppress these messages.
WARNING | 2020-01-28 16:37:28,795 | angr.state_plugins.symbolic_memory | Filling register rbp with 8 unconstrained bytes referenced from 0x4049d3 (PLT.__cxa_finalize+0x32f3 in true (0x49d3))
Traceback (most recent call last):
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 257, in _perform_vex_stmt_Dirty_call
    func = getattr(dirty, func_name)
AttributeError: module 'angr.engines.vex.heavy.dirty' has no attribute 'amd64g_dirtyhelper_FNSAVE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/resilience.py", line 36, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 259, in _perform_vex_stmt_Dirty_call
    raise errors.UnsupportedDirtyError("Unsupported dirty helper %s" % func_name) from e
angr.errors.UnsupportedDirtyError: Unsupported dirty helper amd64g_dirtyhelper_FNSAVE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fnsave.py", line 7, in <module>
    st.step()
  File "/home/ed/Documents/angr-dev/angr/angr/sim_state.py", line 534, in step
    return self.project.factory.successors(self, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/factory.py", line 58, in successors
    return self.default_engine.process(*args, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/engine.py", line 143, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/syscall.py", line 18, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/hook.py", line 54, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/unicorn.py", line 90, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/soot/engine.py", line 64, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 135, in process_successors
    self.handle_vex_block(irsb)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/super_fastpath.py", line 19, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/slicing.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/actions.py", line 18, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/inspect.py", line 45, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/light.py", line 406, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/slicing.py", line 30, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/inspect.py", line 40, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/resilience.py", line 36, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 199, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/light.py", line 50, in _handle_vex_stmt
    handler(stmt)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/light.py", line 219, in _handle_vex_stmt_Dirty
    [self._analyze_vex_stmt_Dirty_arg(arg) for arg in stmt.args]
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/light.py", line 223, in _perform_vex_stmt_Dirty
    retval = self._perform_vex_stmt_Dirty_call(func_name, ty, args)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/actions.py", line 64, in _perform_vex_stmt_Dirty_call
    result = super()._perform_vex_stmt_Dirty_call(func_name, ty, exprs, func=None)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/inspect.py", line 15, in _perform_vex_stmt_Dirty_call
    retval = super()._perform_vex_stmt_Dirty_call(func_name, ty, args, func=func)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/light/resilience.py", line 40, in inner
    v = getattr(self, handler)(*iargs, **ikwargs)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/resilience.py", line 29, in _check_unsupported_dirty
    return self.__make_default(retty, o.UNSUPPORTED_BYPASS_ZERO_DEFAULT not in self.state.options, 'unsupported_' + func_name)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/heavy/resilience.py", line 10, in __make_default
    return symbol(ty, name)
  File "/home/ed/Documents/angr-dev/angr/angr/engines/vex/claripy/datalayer.py", line 26, in symbol
    return claripy.BVS(name, pyvex.get_type_size(ty))
  File "/home/ed/Documents/angr-dev/pyvex/pyvex/const.py", line 366, in get_type_size
    m = type_str_re.match(ty)
TypeError: expected string or bytes-like object
```

**Comment by edmcman** [comment]
The problematic type is `None`.  Probably not too surprising.

**Comment by rhelmot** [comment]
the first two tracebacks are the correct error that should be thrown but I have no idea why this is then chaining into a pyvex error. I will investigate

**Comment by edmcman** [comment]
It looks like it might be trying to create a symbolic variable as a last resort, but the type is `None` so it fails?

**Comment by rhelmot** [comment]
Okay! there were two problems: 1) the logic for adding resilience to dirty helpers was inverted, and 2) the resilience logic couldn't handle dirty helpers with no return value. I have fixed both of them. Now, you should get a much nicer error `angr.errors.UnsupportedDirtyError: Unsupported dirty helper amd64g_dirtyhelper_FNSAVE` on the bottom, with `AttributeError: module 'angr.engines.vex.heavy.dirty' has no attribute 'amd64g_dirtyhelper_FNSAVE'` as its cause.

You can enable the state option `BYPASS_UNSUPPORTED_IRDIRTY` to just ignore this error.
