### ISSUE TITLE
Angr crashes after project.analyses.ROP()

### ISSUE THREAD

**Issue by tactfulsec** [angr/angr#1959]
I'm trying out angr for the first time in order to help me build an AEG engine. If you could please review this stack trace and my attempts at remediation that would be much appreciated.

```
awile@pwn:~$ python
Python 2.7.17 (default, Jan 19 2020, 19:54:54) 
[GCC 9.2.1 20200110] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr, angrop
WARNING | 2020-02-08 15:34:32,558 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
>>> p = angr.Project("/home/awile/chall")
>>> rop = p.analyses.ROP()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/awile/.local/lib/python2.7/site-packages/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/awile/.local/lib/python2.7/site-packages/angrop/rop.py", line 75, in __init__
    self._ret_locations = self._get_ret_locations()
  File "/home/awile/.local/lib/python2.7/site-packages/angrop/rop.py", line 343, in _get_ret_locations
    return self._get_ret_locations_by_string()
  File "/home/awile/.local/lib/python2.7/site-packages/angrop/rop.py", line 395, in _get_ret_locations_by_string
    read_bytes = self.project.loader.memory.load(segment.min_addr, num_bytes)
AttributeError: 'Clemory' object has no attribute 'load'
```

I've followed guidance from other posts suggesting to uninstall and remove pyelftools 0.25 and replace with 0.24 but that did not solve the problem. Tried uninstalling angr altogether and reinstalling but no dice. Please advise. 

Thank you in advance.

**Comment by rhelmot** [comment]
This is because you are using python 2. The year is 2020. Python 2 is dead.

Specifically, there is a verion mismatch between angrop and CLE. angrop is trying to use a newer CLE api than can be installed in a python 2 environment.

**Comment by tactfulsec** [comment]
Tried both, python2 and 3 and neither worked.

**Comment by rhelmot** [comment]
Then show me a traceback from python3

**Comment by tactfulsec** [comment]
`Python 3.7.6 (default, Jan 19 2020, 22:34:52) 
[GCC 9.2.1 20200117] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr, angrop
/usr/lib/python3/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/awile/.local/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py
  tree = Parsing.p_module(s, pxd, full_module_name)

print
/home/awile/.pyxbld/temp.linux-x86_64-3.7/pyrex/pysmt/smtlib/parser/parser.c:52156:1: fatal error: error writing to /tmp/ccUAc0K2.s: No space left on device
52156 | }
      | ^
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/awile/.local/lib/python3.7/site-packages/angr/__init__.py", line 30, in <module>
    from .sim_procedure import SimProcedure
  File "/home/awile/.local/lib/python3.7/site-packages/angr/sim_procedure.py", line 5, in <module>
    from cle import SymbolType
  File "/home/awile/.local/lib/python3.7/site-packages/cle/__init__.py", line 18, in <module>
    from .loader import *
  File "/home/awile/.local/lib/python3.7/site-packages/cle/loader.py", line 14, in <module>
    import claripy
  File "/home/awile/.local/lib/python3.7/site-packages/claripy/__init__.py", line 21, in <module>
    from . import backends as _backends_module
  File "/home/awile/.local/lib/python3.7/site-packages/claripy/backends/__init__.py", line 785, in <module>
    from .backend_smtlib import BackendSMTLibBase
  File "/home/awile/.local/lib/python3.7/site-packages/claripy/backends/backend_smtlib.py", line 3, in <module>
    from pysmt.shortcuts import Symbol, String, StrConcat, NotEquals, \
  File "/home/awile/.local/lib/python3.7/site-packages/pysmt/shortcuts.py", line 38, in <module>
    import pysmt.smtlib.parser
  File "/home/awile/.local/lib/python3.7/site-packages/pysmt/smtlib/parser/__init__.py", line 91, in <module>
    pyxbuild_dir=build_dir)
  File "/usr/lib/python3/dist-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/lib/python3/dist-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by rhelmot** [comment]
That's a bug in what appears to be... pysmt? Trying to compile extensions at runtime and failing? The relevant line appears to be `fatal error: error writing to /tmp/ccUAc0K2.s: No space left on device`
