### ISSUE TITLE
AttributeError: 'Clemory' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Trolldemorted** [angr/angr#1971]
**Describe the bug.**
A call to a state's memory's dbg_print function throws this stacktrace:
```                                                                                                                                                                                             
Traceback (most recent call last):
  File "verification/main.py", line 23, in <module>
    main_state.memory.dbg_print()
  File "/home/benni/.local/lib/python3.6/site-packages/angr/state_plugins/symbolic_memory.py", line 1154, in dbg_print
    for i, addr in enumerate(self.mem.keys()):
  File "/home/benni/.local/lib/python3.6/site-packages/angr/storage/paged_memory.py", line 656, in keys
    sofar.update(self._memory_backer.keys())
AttributeError: 'Clemory' object has no attribute 'keys'
```

**Environment Information.**
Ubuntu18, Python3
```
angr environment report
=============================
Date: 2020-02-22 10:48:46.105736
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
######## angr #########
Python found it in /home/benni/.local/lib/python3.6/site-packages/angr
Pip version angr 8.20.1.7
Couldn't find git info
######## ailment #########
Python found it in /home/benni/.local/lib/python3.6/site-packages/ailment
Pip version ailment 8.20.1.7
Couldn't find git info
######## cle #########
Python found it in /home/benni/.local/lib/python3.6/site-packages/cle
Pip version cle 8.20.1.7
Couldn't find git info
######## pyvex #########
Python found it in /home/benni/.local/lib/python3.6/site-packages/pyvex
Pip version pyvex 8.20.1.7
Couldn't find git info
######## claripy #########
Python found it in /home/benni/.local/lib/python3.6/site-packages/claripy
Pip version claripy 8.20.1.7
Couldn't find git info
######## archinfo #########
Python found it in /home/benni/.local/lib/python3.6/site-packages/archinfo
Pip version archinfo 8.20.1.7
Couldn't find git info
######## z3 #########
Python found it in /home/benni/.local/lib/python3.6/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/benni/.local/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/benni/.local/lib/python3.6/site-packages/angr/lib/angr_native.so', handle 22b7390 at 0x7f3387d224a8>
unicorn: <CDLL '/home/benni/.local/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 1a3dec0 at 0x7f3386c8ad68>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f3387c61668>
z3: <CDLL '/home/benni/.local/lib/python3.6/site-packages/z3/lib/libz3.so', handle 1c57ba0 at 0x7f3384b227b8>
```

**To Reproduce.**
```
addr_start = 0x000131CB
addr_mem = 0x40000000
addr_uart = 0x09000000
addr_device = 0x000000000a003e00

project = angr.Project('foobar')

main_state = project.factory.blank_state(addr=addr_start)
main_state.memory.map_region(addr_mem, 0x1000000, 7)
main_state.memory.map_region(addr_uart, 1024, 7)
main_state.memory.map_region(addr_device, 1024, 7)
main_state.memory.dbg_print()
```

**Additional context.**
This looks like a new variant of #608 (which can be closed?).

**Comment by ltfish** [comment]
I think it's because `SimMemory.dbg_print()` has never been fixed after a very early-on refactor. No one seems to be using it anyway. @rhelmot maybe we can actually implement it properly after you are done with your memory factor?

**Comment by Trolldemorted** [comment]
was this fixed?

**Comment by rhelmot** [comment]
It seems like this method was removed, so yes :)
