### ISSUE TITLE
CFGFast: removing already removed node in _remove_redundant_overlapping_blocks

### ISSUE THREAD

**Issue by quoscient** [angr/angr#199]
The line https://github.com/angr/angr/blob/fb96563836d42e006dbc03bacac1e859519bc55f/angr/analyses/cfg_fast.py#L2535 crashes angr if `b` was removed already. I assume this issue is related to https://github.com/angr/angr/issues/198

The traceback is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/angr-dev/angr/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/user/angr-dev/angr/angr/analyses/cfg_fast.py", line 674, in __init__
    self._analyze()
  File "/home/user/angr-dev/angr/angr/analyses/forward_analysis.py", line 203, in _analyze
    self._post_analysis()
  File "/home/user/angr-dev/angr/angr/analyses/cfg_fast.py", line 1068, in _post_analysis
    self._remove_redundant_overlapping_blocks()
  File "/home/user/angr-dev/angr/angr/analyses/cfg_fast.py", line 2560, in _remove_redundant_overlapping_blocks
    self.graph.remove_node(b)
  File "/home/user/.virtualenvs/angr-dev2/local/lib/python2.7/site-packages/networkx/classes/digraph.py", line 461, in remove_node
    raise NetworkXError("The node %s is not in the digraph."%(n,))
networkx.exception.NetworkXError: The node <CFGNode 0x1001e4d0 (1) [0]> is not in the digraph.
```

**Comment by zardus** [comment]
Fish, is this fixed?
