### ISSUE TITLE
Unknown CFI opcode: 0x2e

### ISSUE THREAD

**Issue by bannsec** [angr/angr#1997]
**Describe the bug.**
When loading specific 32bit ELF binaries, I get the following error

```
WARNING | 2020-03-16 14:18:12,023 | cle.backends.elf.elf | An exception occurred in pyelftools when loading FDE information.
Traceback (most recent call last):
  File "/home/angr/angr-dev/cle/cle/backends/elf/elf.py", line 446, in _load_function_hints_from_fde
    for entry in dwarf.EH_CFI_entries():
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/elftools/dwarf/dwarfinfo.py", line 191, in EH_CFI_entries
    return cfi.get_entries()
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/elftools/dwarf/callframe.py", line 71, in get_entries
    self.entries = self._parse_entries()
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/elftools/dwarf/callframe.py", line 80, in _parse_entries
    entries.append(self._parse_entry_at(offset))
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/elftools/dwarf/callframe.py", line 153, in _parse_entry_at
    entry_structs, self.stream.tell(), end_offset)
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/elftools/dwarf/callframe.py", line 228, in _parse_instructions
    dwarf_assert(False, 'Unknown CFI opcode: 0x%x' % opcode)
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/elftools/common/utils.py", line 83, in dwarf_assert
    _assert_with_exception(cond, msg, DWARFError)
  File "/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/elftools/common/utils.py", line 109, in _assert_with_exception
    raise exception_type(msg)
elftools.common.exceptions.DWARFError: Unknown CFI opcode: 0x2e
```

While the error comes from pyelftools, I'm unable to reproduce the error directly with pyelftools using the commands from the exception. I'm not sure why it seems to only manifest in angr's loading process but i've been running into this one more lately.

**Environment Information.**
```
angr environment report
=============================
Date: 2020-03-16 14:24:03.106188
Running in virtual environment at /home/angr/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
######## angr #########
Python found it in /home/angr/angr-dev/angr/angr
Pip version angr 8.20.1.7
Git info:
        Current commit cd55e94af4762022c273c95203595107a674993f from branch master
        Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/angr/angr-dev/ailment/ailment
Pip version ailment 8.20.1.7
Git info:
        Current commit c696edc9f31ecccaaa36b1e40ca1bed6c9715242 from branch master
        Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/angr/angr-dev/cle/cle
Pip version cle 8.20.1.7
Git info:
        Current commit c2f69fe466924bec508bd6cd5e01e8bd26ed10e7 from branch master
        Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/angr/angr-dev/pyvex/pyvex
Pip version pyvex 8.20.1.7
Git info:
        Current commit f4753f85a8c18dae9dbb32301f8a7804efd36491 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/angr/angr-dev/claripy/claripy
Pip version claripy 8.20.1.7
Git info:
        Current commit b6eabc37aed7c2989faf12406a247004b5849216 from branch master
        Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/angr/angr-dev/archinfo/archinfo
Pip version archinfo 8.20.1.7
Git info:
        Current commit c505b444d67fcea216b4af7b0fdcf58b587a02ce from branch master
        Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.2
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/angr/angr-dev/angr/angr/lib/angr_native.so', handle 18036e0 at 0x7f426ee0cb00>
unicorn: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle f530a0 at 0x7f426ddbfcc0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f426ed53128>
z3: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 1197eb0 at 0x7f426ad0fcc0>
```

**To Reproduce.**
```python
proj = angr.Project("./test") # This causes the error
```

**Additional context.**
Attaching an example file that causes this. It so far seems to only hit 32-bit ELF. When I try doing the "dwarf.EH_CFI_entries()" directly with pyelftools, i don't see the same error.
[test.zip](https://github.com/angr/angr/files/4338647/test.zip)

**Comment by rhelmot** [comment]
This is known, and is caused by load_debug_info=True, a new option. I recently switched the default of that option to False because I anticipated too many people complaining about these errors, which we specifically catch and suppress because they are so common.
