### ISSUE TITLE
Can't handle operation If (BV) due to a failed conversion on a child node

### ISSUE THREAD

**Issue by expend20** [angr/angr#2078]
**Describe the bug.**

Sup guys :) I was just playing recent CTF with angr and got this issue:
```
[...]
  File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 498, in eval
    self.convert(expr), n, extra_constraints=self.convert_list(extra_constraints),
  File "/home/angr/angr-dev/claripy/claripy/backends/backend_concrete.py", line 83, in convert
    return super().convert(expr)
  File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 167, in convert
    "conversion on a child node" % (self, ast.op, ast.__class__.__name__))
claripy.errors.BackendError: <claripy.backends.backend_concrete.BackendConcrete object at 0x7f9ca2544288> can't handle operation If (BV) due to a failed conversion on a child node
(angr) angr@a946f0672b27:~$
```

The idea was just to run analysis until the state is forked and always pursue the first possible state as next one. This strategy actually worked well (angr found "H_" as a valid input which is correct indeed, but the original flag is 33 byte long). ~~But nowadays authors of the challenges include some relatively heavy calculations in order to cut off cheaters who prefer solving it automatically :-P~~. So, the amount of calculations grows with the size of input exponentially. The following scripts runs for ~30 minutes, and gives the error above. Here is the full log:

```
(angr) angr@a946f0672b27:~$ python s.py
start:  <SimState @ 0x4000000>
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{( ,@ @PA0b@@@P@ @ @  @ @ @]A\x00'
b'pctf{                 @          \x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{`X(J @PWpka@@Pg@@  @  @ @@O@\x00'
b'pctf{( ,@ @PA0b@@@P@ @ @  @ @ @]A\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{(uaqp @Z0AjF@Rm8 @@ @   @ K0\x00'
b'pctf{`X(J @PWpka@@Pg@@  @  @ @@O@\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{(""7%PTy>)r&0VW0r  @  @@  +F\x00'
b'pctf{(uaqp @Z0AjF@Rm8 @@ @   @ K0\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{BNfv7#PAbAm]D,M68P@ @@ @  Sb\x00'
b'pctf{(""7%PTy>)r&0VW0r  @  @@  +F\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b"pctf{%0X$'[7_$9[te$U9Tv @@@@@@@g@\x00"
b'pctf{BNfv7#PAbAm]D,M68P@ @@ @  Sb\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{#LPtqOasZIG/xrK.:|l: @@   GL\x00'
b"pctf{%0X$'[7_$9[te$U9Tv @@@@@@@g@\x00"
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{YA[KF\\yVW|WLpOVYXofvu     ,n\x00'
b'pctf{#LPtqOasZIG/xrK.:|l: @@   GL\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{sq"!&Q)n2AHep4}.480-(L  @@:`\x00'
b'pctf{YA[KF\\yVW|WLpOVYXofvu     ,n\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b"pctf{)o[<QbQ@##f6OK,.:P+2 t' @@bA\x00"
b'pctf{sq"!&Q)n2AHep4}.480-(L  @@:`\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{,g6N,"bLn-TN>P%7=;qS1}K; `cO\x00'
b"pctf{)o[<QbQ@##f6OK,.:P+2 t' @@bA\x00"
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{4GE)b-XAz+;VUMtoOVtQH!va= V)\x00'
b'pctf{,g6N,"bLn-TN>P%7=;qS1}K; `cO\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{H&u+^Tx*_+MDM}@"HzuT_b\'Ii6+F\x00'
b'pctf{4GE)b-XAz+;VUMtoOVtQH!va= V)\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{WJnCc{NLSQeB{Rt\\mYdJp@L\\{a.N\x00'
b'pctf{H&u+^Tx*_+MDM}@"HzuT_b\'Ii6+F\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{KRDM\\@`\\@,VvqT& (_!gT cq3)GG\x00'
b'pctf{WJnCc{NLSQeB{Rt\\mYdJp@L\\{a.N\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{I}u$59h-DR<,J/s2MLKrZ}vi`w~5\x00'
b'pctf{KRDM\\@`\\@,VvqT& (_!gT cq3)GG\x00'
multiple paths: [<SimState @ 0x4008c3>, <SimState @ 0x40089d>]
choosing first...
b'pctf{1.*.\\PL3h.15b!8@nKciyZ>IPxld\x00'
b'pctf{I}u$59h-DR<,J/s2MLKrZ}vi`w~5\x00'
Traceback (most recent call last):
  File "s.py", line 45, in <module>
    succ = state.step()
  File "/home/angr/angr-dev/angr/angr/sim_state.py", line 534, in step
    return self.project.factory.successors(self, **kwargs)
  File "/home/angr/angr-dev/angr/angr/factory.py", line 54, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/angr/angr-dev/angr/angr/engines/unicorn.py", line 40, in process
    force_addr=force_addr)
  File "/home/angr/angr-dev/angr/angr/engines/engine.py", line 60, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/engines/unicorn.py", line 120, in _process
    state.unicorn.setup()
  File "/home/angr/angr-dev/angr/angr/state_plugins/unicorn_engine.py", line 902, in setup
    self.set_regs()
  File "/home/angr/angr-dev/angr/angr/state_plugins/unicorn_engine.py", line 1122, in set_regs
    uc.reg_write(self._uc_const.UC_X86_REG_EFLAGS, self.state.solver.eval(flags))
  File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 724, in eval
    return self.eval_upto(e, 1, **kwargs)[0]
  File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 707, in eval_upto
    cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
  File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 154, in concrete_shortcut_tuple
    return f(self, *args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 87, in wrapped_f
    return f(*args, **kwargs)
  File "/home/angr/angr-dev/angr/angr/state_plugins/solver.py", line 499, in _eval
    return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/concrete_handler_mixin.py", line 7, in eval
    return super(ConcreteHandlerMixin, self).eval(e, n, **kwargs)
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/constraint_filter_mixin.py", line 40, in eval
    return super(ConstraintFilterMixin, self).eval(e, n, extra_constraints=ec, **kwargs)
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/sat_cache_mixin.py", line 56, in eval
    extra_constraints=extra_constraints, **kwargs
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/simplify_helper_mixin.py", line 13, in eval
    return super(SimplifyHelperMixin, self).eval(e, n, *args, **kwargs)
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/constraint_expansion_mixin.py", line 12, in eval
    **kwargs
  File "/home/angr/angr-dev/claripy/claripy/frontends/composite_frontend.py", line 320, in eval
    r = ms.eval(e, n, extra_constraints=extra_constraints, exact=exact)
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/sat_cache_mixin.py", line 56, in eval
    extra_constraints=extra_constraints, **kwargs
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/model_cache_mixin.py", line 272, in eval
    return tuple( r[0] for r in ModelCacheMixin.batch_eval(self, [e], n=n, **kwargs) )
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/model_cache_mixin.py", line 243, in batch_eval
    results = self._get_batch_solutions(asts, n=n, extra_constraints=extra_constraints)
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/model_cache_mixin.py", line 218, in _get_batch_solutions
    results.add(m.eval_list(asts))
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/model_cache_mixin.py", line 71, in eval_list
    return tuple(self.eval_ast(c) for c in asts)
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/model_cache_mixin.py", line 71, in <genexpr>
    return tuple(self.eval_ast(c) for c in asts)
  File "/home/angr/angr-dev/claripy/claripy/frontend_mixins/model_cache_mixin.py", line 58, in eval_ast
    return backends.concrete.eval(new_ast, 1)[0]
  File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 498, in eval
    self.convert(expr), n, extra_constraints=self.convert_list(extra_constraints),
  File "/home/angr/angr-dev/claripy/claripy/backends/backend_concrete.py", line 83, in convert
    return super().convert(expr)
  File "/home/angr/angr-dev/claripy/claripy/backends/__init__.py", line 167, in convert
    "conversion on a child node" % (self, ast.op, ast.__class__.__name__))
claripy.errors.BackendError: <claripy.backends.backend_concrete.BackendConcrete object at 0x7f9ca2544288> can't handle operation If (BV) due to a failed conversion on a child node
(angr) angr@a946f0672b27:~$
```

Here is the script:

```python
import logging
import angr
import claripy

if __name__ == '__main__':

    #logging.getLogger('angr.sim_manager').setLevel('DEBUG')

    proj = angr.Project("./reee")

    LEN = 33 + 1 #5+21+2 
    
    input_chars = claripy.BVS('flag', 8*LEN)
    
    argv = [proj.filename]
    argv.append(input_chars)

    state = proj.factory.full_init_state(args=argv, add_options=angr.options.unicorn, remove_options={angr.options.LAZY_SOLVES})

    prefix = bytes("pctf{".encode("utf-8"))
    for i, char in enumerate(input_chars.chop(bits=8)):

        if i < len(prefix):
            state.add_constraints(char == prefix[i]) 
        if i == LEN - 1:
            state.add_constraints(char == b"\x00") # this may be redundant
        else:
            state.add_constraints(
                char <= claripy.BVV(b'\x7e'), 
                char >= claripy.BVV(b'\x20'))

    print("start: ", state)
    while True:
        succ = state.step()
        if len(succ.successors) == 2:

            print("multiple paths:", succ.successors)
            print("choosing first...")
        
            state1, state2 = succ.successors
            print(state1.solver.eval(input_chars, cast_to=bytes))
            print(state2.solver.eval(input_chars, cast_to=bytes))

            succ.successors[0] = state1
        elif len(succ.successors) == 0:
            break
        elif len(succ.successors) > 2:
            print("more than 2 paths:", succ.successors)
            break

        state = succ.successors[0]
        
    print("done 5 + dump1")
    print(state.posix.dumps(1))
    print(state.solver.eval(input_chars, cast_to=bytes))
```

PS: Just in case you need the correct flag: `pctf{ok_nothing_too_fancy_there!}` and here is the z3 solver:

```python
from z3 import *

targetBytes = "485F36353525142C1D01032D0C6F35617E340A44242C4A4619595B0E787429132C004889C2488955E848837DE800740CBFD1094000E8DBFAFFFF"
targetBytes = bytes().fromhex(targetBytes)
print("targetBytes = %x" % len(targetBytes))

prefix = bytes("pctf{".encode("utf-8"))

for LEN in range(0x6, len(targetBytes)):

    print("trying %d as a length..." % LEN)

    sol = Solver()

    flag0 = [BitVec("%d"%i, 32) for i in range(LEN)]
    

    for i in range(0, len(prefix)):
        sol.add(flag0[i] == prefix[i])
    
    for i in range(len(prefix), LEN):
        sol.add(And([flag0[i] >= 0x20, flag0[i] <= 0x7f]))

    flag = [f for f in flag0]
    
    prevXor = 0x50
    for i in range(0x539):
        for j in range(len(flag)):
            flag[j] = prevXor ^ flag[j]
            prevXor ^= flag[j]

    for i in range(LEN):
        sol.add(flag[i] == targetBytes[i])

    if sol.check() != sat:
        print(":(")
        continue
        
    print(":)")
    m = sol.model()
    
    outFlag = bytearray(0)
    for f in flag0:
        outFlag.append(m[f].as_long())

    print(outFlag)
    break
```

**Environment Information.**

```
(angr) angr@a946f0672b27:~$ python -m angr.misc.bug_report
angr environment report
=============================
Date: 2020-04-21 18:45:11.461296
Running in virtual environment at /home/angr/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
######## angr #########
Python found it in /home/angr/angr-dev/angr/angr
Pip version angr 8.19.10.30
Git info:
        Current commit 6c0675c4552e1f18bbc6105550e2c14687ee39dd from branch master
        Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/angr/angr-dev/ailment/ailment
Pip version ailment 8.19.10.30
Git info:
        Current commit 3fa97beb3d515eb5e38314d1885e518c726fe6d6 from branch master
        Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/angr/angr-dev/cle/cle
Pip version cle 8.19.10.30
Git info:
        Current commit 4f103baa5022726df414c9e29f8c32915d413c17 from branch master
        Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/angr/angr-dev/pyvex/pyvex
Pip version pyvex 8.19.10.30
Git info:
        Current commit be46d7fb329c2d4825c65cf7893e321b4ee85b8a from branch master
        Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/angr/angr-dev/claripy/claripy
Pip version claripy 8.19.10.30
Git info:
        Current commit 8dbacc31a7ff1aab401dfe9b0eec4bc3f0ed4023 from branch master
        Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/angr/angr-dev/archinfo/archinfo
Pip version archinfo 8.19.10.30
Git info:
        Current commit 10ad12e696ae72a91c4833707b851bdc80771122 from branch master
        Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.2
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/angr/angr-dev/angr/angr/lib/angr_native.so', handle 33b0df0 at 0x7f45b88070b8>
unicorn: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 2b34660 at 0x7f45b775c0b8>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f45b8739320>
z3: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 2d4a440 at 0x7f45b471c898>
```

**To Reproduce.**

Here is the binary [reee.txt](https://github.com/angr/angr/files/4512120/reee.txt). Just run the script above against this binary and wait for... ~30 minutes. If you want to speed it up a bit, here is slightly simplified version of the script which triggers the same bug:

```python
import logging
import angr
import claripy

if __name__ == '__main__':

    #logging.getLogger('angr.sim_manager').setLevel('DEBUG')

    proj = angr.Project("./reee")

    LEN = 10
    
    input_chars = claripy.BVS('flag', 8*LEN)
    
    argv = [proj.filename]
    argv.append(input_chars)

    state = proj.factory.full_init_state(args=argv, add_options=angr.options.unicorn, remove_options={angr.options.LAZY_SOLVES})

    # prefix = bytes("pctf{".encode("utf-8"))
    for i, char in enumerate(input_chars.chop(bits=8)):
    #     if i < len(prefix):
    #         state.add_constraints(char == prefix[i]) 
    #     if i == LEN - 1:
    #         state.add_constraints(char == b"\x00") # this may be redundant
    #     else:
        state.add_constraints(
            char <= claripy.BVV(b'\x7e'), 
            char >= claripy.BVV(b'\x20'))

    print("start: ", state)
    while True:
        succ = state.step()
        if len(succ.successors) == 2:

            print("multiple paths:", succ.successors)
            print("choosing first...")
        
            state1, state2 = succ.successors
            print(state1.solver.eval(input_chars, cast_to=bytes))
            print(state2.solver.eval(input_chars, cast_to=bytes))

            succ.successors[0] = state1
        elif len(succ.successors) == 0:
            break
        elif len(succ.successors) > 2:
            print("more than 2 paths:", succ.successors)
            break

        state = succ.successors[0]
        
    print("done 5 + dump1")
    print(state.posix.dumps(1))
    print(state.solver.eval(input_chars, cast_to=bytes))
```

**Additional context.**

The angr was able to run through the most "heavy" calculations and get to the final checks, but it seems something went wrong during solving equations. 

Thanks!

**Comment by rhelmot** [comment]
I believe I've fixed this. idk why this hasn't popped up sooner.
