### ISSUE TITLE
Old behavior of merging deprecated?

### ISSUE THREAD

**Issue by joebb97** [angr/angr#2084]
Hi there, I asked about this in the angr slack and was directed to file an issue here.

My school project group and I are attempting to update the memory plugin from this repo: https://github.com/anrddh/memsight (which is our fork of https://github.com/season-lab/memsight) to `python3` and the latest version of `angr`. The upstream is still on `python2.7`  and `angr==7.7.12.16` with some patches applied from what was presumably a dev branch of the angr repo at the time. Our fork is using `angr==8.20.1.7`

So far we’ve been able get all of their existing tests passing except for their test which handles memory merging functionality of their plugin from turning on `veritesting` in `angr`

The source code for this binary looks like this, symbolic execution is started at `foobar`:
```
int foobar(int n) {
	int i;
	int sum = 0;
	for (i = 0; i < n; i++)
		sum = i;
	return sum;
}

int main() {
	int res = foobar(100);
	return 0;
}
```

The test attempts to make sure that multiple values of `sum` and `i` are considered, and the source for the test is given below. It defines an address to start and stop execution at in the binary, as well as some actions to do before and after symbolic execution is performed.

```
import claripy

def start():
    return 0x4004d6

def end():
    return [0x4004ff]

def avoid():
    return []

def do_start(state):
    params = {}
    state.regs.edi = claripy.BVS('edi_i', 32)
    params['edi'] = state.regs.edi
    params['veritesting'] = True
    state.solver.add(params['edi'] < 9)
    return params

def do_end(state, params, pg, verbose=True):

    n = state.memory.load(state.regs.rbp - 4, 4).reversed

    o = state.solver.Concat(params['edi'], n)
    sol = state.solver.eval_upto(o, 10)
    import ctypes
    eax = []
    edi = []
    for k in range(len(sol)):
        edi.append(ctypes.c_int((sol[k] & (0xFFFFFFFF << 32)) >> 32).value)
        eax.append(ctypes.c_int(sol[k] & 0xFFFFFFFF).value)

    assert len(edi) == 9
    assert len(set(eax)) == 8

    if verbose:
        print("I: " + str(edi))
        print("SUM:" + str(eax))
```

I read the [docs](https://docs.angr.io/extending-angr/state_plugins) about merging and common_ancestor and find it to be very contradictory to what the `memsight` authors' code assumes/asserts. Memsight’s merging code can be found [here](https://github.com/season-lab/memsight/blob/master/memory/range_fully_symbolic_memory.py) at line 1291 and 1328 (if you would like me to include it here, let me know).

Mainly, they only handle 1 other state being merged at a time, and also assert that a common ancestor is passed to the merge function. I don't know how this used to work based on the current docs, but their tests certainly passed with these assertions in the old version of angr.

I think our problem might be unexpected or deprecated behavior in `most_mergable`  in `state_hierarchy.py:199`  in `angr` . Mainly, in running this merging test with the old version of `angr` and `memsight`, the first time `most_mergable` runs, `self._graph` is populated and finds a common ancestor, but in our updated version, the first time this `most_mergable` runs the for loop body doesn’t execute because `self._graph` isn’t populated, and thus no common ancestor is found.

Whether this^ is a bug or not, I don't know, but it seems to me like there should be a common ancestor found in this test case. Was hoping to get some insight on what should be done here. Thanks for any help you can provide, I greatly appreciate it

**Comment by joebb97** [comment]
Here's the output of running this test with the old version of `memsight` and `angr`:
```
→ python run.py 1 tests/binary/merge
WARNING | 2020-04-24 18:23:53,385 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
Veritesting: True
depth=1 <SimulationManager with 1 active>
depth=2 <SimulationManager with 1 active>
Reached the target
<SimulationManager with 1 found>
I: [0, 2, 3, 4, 5, 6, 1, 7, 8]
SUM:[0, 1, 2, 3, 4, 5, 0, 6, 7]
Memory footprint:       100 MB
```

And here's the big chunky traceback we're currently getting:
```
→ python run.py 1 tests/binary/merge
CRITICAL | 2020-04-24 18:20:43,309 | angr.sim_state | The name state.se is deprecated; please use state.solver.
Veritesting: True
depth=1 <SimulationManager with 1 active>
WARNING | 2020-04-24 18:20:43,325 | angr.state_plugins.symbolic_memory | The program is accessing memory or registers with an unspecified value. This could indicate unwanted behavior.
WARNING | 2020-04-24 18:20:43,325 | angr.state_plugins.symbolic_memory | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2020-04-24 18:20:43,325 | angr.state_plugins.symbolic_memory | 1) setting a value to the initial state
WARNING | 2020-04-24 18:20:43,325 | angr.state_plugins.symbolic_memory | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2020-04-24 18:20:43,325 | angr.state_plugins.symbolic_memory | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY_REGISTERS}, to suppress these messages.
WARNING | 2020-04-24 18:20:43,326 | angr.state_plugins.symbolic_memory | Filling register rbp with 8 unconstrained bytes referenced from 0x4004d6 (foobar+0x0 in merge (0x4004d6))
WARNING | 2020-04-24 18:20:43,329 | angr.state_plugins.symbolic_memory | Filling register 76 with 4 unconstrained bytes referenced from 0x4004da (foobar+0x4 in merge (0x4004da))
depth=2 <SimulationManager with 1 active>
WARNING | 2020-04-24 18:20:43,364 | angr.state_plugins.symbolic_memory | Filling register rax with 8 unconstrained bytes referenced from 0x4004f7 (foobar+0x21 in merge (0x4004f7))
Deprecation warning: Use self.model.get_any_node() instead of get_any_node
WARNING | 2020-04-24 18:20:43,749 | angr.sim_manager | Cannot find states with common history line to merge. Fall back to the naive merging strategy and merge all states.
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    explorer.run(mem_memory=mem_memory, reg_memory=reg_memory)
  File "/home/vagrant/memsight/executor/executor.py", line 141, in run
    pg.explore(avoid=self.avoid, find=self.end, n=1)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/sim_manager.py", line 238, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/exploration_techniques/explorer.py", line 96, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/exploration_techniques/veritesting.py", line 21, in step_state
    vt = self.project.analyses.Veritesting(state, **self.options)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/analyses/analysis.py", line 111, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/analyses/veritesting.py", line 223, in __init__
    self.result, self.final_manager = self._veritesting()
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/analyses/veritesting.py", line 235, in _veritesting
    new_manager = self._execute_and_merge(s)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/analyses/veritesting.py", line 345, in _execute_and_merge
    manager = self._join_merge_points(manager, merge_points)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/analyses/veritesting.py", line 413, in _join_merge_points
    manager.merge(stash='merge_tmp')
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/sim_manager.py", line 641, in merge
    m = self._merge_states(g) if merge_func is None else merge_func(*g)
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/sim_manager.py", line 717, in _merge_states
    m, _, _ = s.merge(*states[1:])
  File "/home/vagrant/.virtualenvs/memsight/lib/python3.6/site-packages/angr/sim_state.py", line 665, in merge
    their_filled_plugins, merge_conditions, common_ancestor=plugin_common_ancestor,
  File "/home/vagrant/memsight/memory/range_fully_symbolic_memory.py", line 74, in wrap
    result = func(*args, **kwargs)
  File "/home/vagrant/memsight/memory/range_fully_symbolic_memory.py", line 1300, in merge
    assert common_ancestor is not None
AssertionError
```

**Comment by ltfish** [comment]
I don't have time to look into this today, but just want to check with you: Are you aware of [this PR](https://github.com/angr/angr/pull/1605)?

**Comment by joebb97** [comment]
No problem, and no I had no clue that existed but looks like it could be useful. Sorry I didn't find that on my first stab and thanks for mentioning it!

**Comment by joebb97** [comment]
From that pull request I think the two items
> Some things that are TODO:
> 
> * [ ]  Support multiple states in merge
> * [ ]  Support no common ancestor in merge

Are precisely the root of the problem I'm encountering

**Comment by ltfish** [comment]
@rhelmot do you think the new memory model will make implementing the above features easier? Feel free to say "I don't know" if you haven't thought about it.

**Comment by rhelmot** [comment]
They will certainly simplify the implementation of memsight by allowing the parts that are irrelevant to the actual model to be factored out into mixins (which are by and large already implemented) but this issue has to do with totally orthogonal problems.
