### ISSUE TITLE
analysis of ios dylib error

### ISSUE THREAD

**Issue by wondayer** [angr/angr#2098]
Connected to pydev debugger (build 201.6668.115)
WARNING | 2020-04-29 14:28:30,688 | cle.backends.macho | The Mach-O backend is not well-supported. Good luck!
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/wxl2578/PycharmProjects/ollvm-angr/main.py", line 353, in <module>
    project = angr.Project('./WeChat', load_options={'auto_load_libs': False})
  File "/usr/local/lib/python3.7/site-packages/angr/project.py", line 121, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/usr/local/lib/python3.7/site-packages/cle/loader.py", line 127, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *preload_libs, preloading=True)
  File "/usr/local/lib/python3.7/site-packages/cle/loader.py", line 646, in _internal_load
    main_obj = self._load_object_isolated(main_spec)
  File "/usr/local/lib/python3.7/site-packages/cle/loader.py", line 749, in _load_object_isolated
    return backend_cls(full_spec, is_main_bin=self.main_object is None, loader=self, **options)
  File "/usr/local/lib/python3.7/site-packages/cle/backends/macho/macho.py", line 155, in __init__
    self._parse_mod_funcs()
  File "/usr/local/lib/python3.7/site-packages/cle/backends/macho/macho.py", line 197, in _parse_mod_funcs
    parse_mod_funcs_internal(sec, self.mod_init_func_pointers)
  File "/usr/local/lib/python3.7/site-packages/cle/backends/macho/macho.py", line 188, in parse_mod_funcs_internal
    addr = self._unpack_with_byteorder(fmt, "".join(self.memory.load(i, size)))[0]
TypeError: sequence item 0: expected str instance, int found

**Comment by wondayer** [comment]
Upgrade to the latest success
