### ISSUE TITLE
Angrdb Dump Failed

### ISSUE THREAD

**Issue by cxm95** [angr/angr#2101]
---

**Describe the bug.**

When I tried to save the ADB file, a bug is triggered.
The binary file is attached.

```
proj = angr.Project(binary_path, load_options={'auto_load_libs': False})
cfg = proj.analyses.CFG(show_progressbar=True)
db = AngrDB(proj)
db.dump(db_file)
```

```
  File "angr/angr/angrdb/db.py", line 36, in open_db
    yield Session
  File "angr/angr/angrdb/db.py", line 143, in dump
    KnowledgeBaseSerializer.dump(session, self.project.kb)
  File "angr/angr/angrdb/serializers/kb.py", line 36, in dump
    FunctionManagerSerializer.dump(session, db_kb, kb.functions)
  File "angr/angr/angrdb/serializers/funcs.py", line 29, in dump
    blob=func.serialize(),
  File "angr/angr/serializable.py", line 37, in serialize
    return self.serialize_to_cmessage().SerializeToString()
  File "angr/angr/knowledge_plugins/functions/function.py", line 388, in serialize_to_cmessage
    return FunctionParser.serialize(self)
  File "angr/angr/knowledge_plugins/functions/function_parser.py", line 58, in serialize
    edge.jumpkind = func_edge_type_to_pb(value)
TypeError: None has type NoneType, but expected one of: int, long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fuzz_driver.py", line 474, in <module>
    db.dump(db_file)
  File "angr/angr/angrdb/db.py", line 145, in dump
    self.update_dbinfo(session)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "angr/angr/angrdb/db.py", line 40, in open_db
    raise AngrDBError(str(ex))
angr.errors.AngrDBError: None has type NoneType, but expected one of: int, long
```

**Environment Information.**

latest version of angr with python3 (virtualenv)

**To Reproduce.**

**Additional context.**

[adb_failed_bin.zip](https://github.com/angr/angr/files/4561800/adb_failed_bin.zip)

**Comment by ltfish** [comment]
Thanks for reporting! It is a bug indeed.
