### ISSUE TITLE
CFGFast fails when `auto_load_libs` is set to True

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#2128]
~~~
WARNING | 2020-05-08 10:41:53,346 | angr.analyses.cfg.cfg_fast | "auto_load_libs" is enabled. With libraries loaded in project, CFGFast will cover libraries, which may take significantly more time than expected. You may reload the binary with "auto_load_libs" disabled, or specify "regions" to limit the scope of CFG recovery.
WARNING | 2020-05-08 10:41:55,780 | claripy.vsa.strided_interval | Reversing a real strided-interval <32>0x1[0x0, 0xdffffff]R(uninit) is bad
Traceback (most recent call last):
  File "script.py", line 3, in <module>
    proj.analyses.CFGFast()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/analysis.py", line 111, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 652, in __init__
    self._analyze()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py", line 216, in _analyze
    self._analysis_core_baremetal()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py", line 344, in _analysis_core_baremetal
    self._job_queue_empty()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/cfg/cfg_fast.py", line 1152, in _job_queue_empty
    self._process_unresolved_indirect_jumps()
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2349, in _process_unresolved_indirect_jumps
    all_targets |= self._process_one_indirect_jump(jump)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 2375, in _process_one_indirect_jump
    resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 479, in resolve
    r, targets = self._resolve(cfg, addr, func_addr, b)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 597, in _resolve
    stmts_adding_base_addr, all_addr_holders)
  File "/home/kylebot/src/angr-dev/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 984, in _try_resolve_targets
    assert len(stmts_adding_base_addr) == 1  # Making sure we are only dealing with one operation here
AssertionError
~~~

Everything needed is in https://gist.github.com/Kyle-Kyle/b5d354b804871c2f7f24a1dd04d9340a

**Comment by Kyle-Kyle** [comment]
@ltfish

**Comment by Kyle-Kyle** [comment]
it does not crash anymore
