### ISSUE TITLE
Unsupported operand types for dll files

### ISSUE THREAD

**Issue by sogun3** [angr/angr#213]
Hi, I am trying to analyze a dll file with CFGAccurate, but I got a confusing error:
```
WARNING | 2016-09-16 17:33:07,613 | cle.pe | The PE module is not well-supported. Good luck!
Traceback (most recent call last):
  File "angrTest.py", line 23, in <module>
    keep_state = True, starts = list(proj.kb.functions))
  File "/home/brenda/virtualenvs/angr/local/lib/python2.7/site-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/brenda/virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 237, in __init__
    self._analyze()
  File "/home/brenda/virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 192, in _analyze
    self._handle_entry(entry_info)
  File "/home/brenda/virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 215, in _handle_entry
    self._pre_entry_handling(entry)
  File "/home/brenda/virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 940, in _pre_entry_handling
    simrun, error_occurred, _ = self._get_simrun(addr, entry.path, current_function_addr=entry.func_addr)
  File "/home/brenda/virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 2304, in _get_simrun
    opt_level=self._iropt_level
  File "/home/brenda/virtualenvs/angr/local/lib/python2.7/site-packages/angr/factory.py", line 173, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/home/brenda/virtualenvs/angr/local/lib/python2.7/site-packages/angr/factory.py", line 103, in sim_block
    block_opts['max_size'] -= new_ip - addr
TypeError: unsupported operand type(s) for -=: 'NoneType' and 'long'
```

The following is my code:
```
import angr
proj = angr.Project("HelloWorld.dll",load_options={'auto_load_libs': False},  use_sim_procedures=True,
                                   default_analysis_mode='symbolic')
cfg = proj.analyses.CFG(collect_data_references = True, extra_cross_references == True)

cfg_accu = proj.analyses.CFGAccurate(context_sensitivity_level = 3,iropt_level=1, keep_state = True, starts = list(proj.kb.functions))

```
What are the possible sources of errors? And since the error is a type error, I am not sure whether the error is 'NoneType' or 'Long' in new_ip or addr.

Thanks!

**Comment by rhelmot** [comment]
idk if fish will need it to fix your bug, but could you attach `HelloWorld.dll`?

**Comment by ltfish** [comment]
Wait, somehow I thought I have responded to this thread...

That should be a bug in CFGAccurate. I believe I can fix it even without the `HelloWorld.dll`.

**Comment by ltfish** [comment]
Umm sorry, this does not seem to be my issue though. The exception occurs in `AngrObjectFactory`. @brendabrandy Can  you please give me your `HelloWorld.dll`?

**Comment by brendabrandy** [comment]
How can I send the dll file to you? It seems that I can't upload the binary here

**Comment by ltfish** [comment]
Feel free to use any online file uploading service, or simply shoot an email to _fish <at> cs dot ucsb dot edu_.
