### ISSUE TITLE
Tracer fails if a library calls syscall stub from gdt during initialization

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#2136]
~~~
[<SimState @ 0x8108fd8>]
[<SimState @ 0x870008c>]
[<SimState @ 0x81096f0>]
[<SimState @ 0x870008c>]
[<SimState @ 0x8201eec>]
[<SimState @ 0x870008c>]
[<SimState @ 0x8202120>]
[<SimState @ 0x870008c>]
[<SimState @ 0x8318c00>]
[<SimState @ 0x870008c>]
[<SimState @ 0x83186a0>]
[<SimState @ 0x870008c>]
[<SimState @ 0x8318710>]
[<SimState @ 0x870008c>]
[<SimState @ 0x8504470>]
[<SimState @ 0x8700020>]
[<SimState @ 0x8900102>]
[<SimState @ 0x8504cfa>]
[<SimState @ 0x8700020>]
[<SimState @ 0x8900137>]
[<SimState @ 0x8504d4e>]
[<SimState @ 0x8700020>]
[<SimState @ 0x89000ae>]
[<SimState @ 0x8512601>]
[<SimState @ 0x851260c>, <SimState @ 0x85126c0>]
[<ELF Object orzhttpd, maps [0x8048000:0x804f8c7]>, <ELF Object libevent-2.1.so.6.0.2, maps [0x8100000:0x815e713]>, <ELF Object libexpat.so.1.6.7, maps [0x8200000:0x823104f]>, <ELF Object libc-2.27.so, maps [0x8300000:0x84dba1b]>, <ELF Object libpthread-2.27.so, maps [0x8500000:0x851e297]>, <ELF Object ld-2.27.so, maps [0x8600000:0x8627937]>, <ExternObject Object cle##externs, maps [0x8700000:0x8708000]>, <ELFTLSObjectV2 Object cle##tls, maps [0x8800000:0x8814808]>, <KernelObject Object cle##kernel, maps [0x8900000:0x8908000]>]
Traceback (most recent call last):
  File "script.py", line 16, in <module>
    simgr.use_technique(tech)
  File "/home/kylebot/src/angr-dev/angr/angr/sim_manager.py", line 189, in use_technique
    tech.setup(self)
  File "/home/kylebot/src/angr-dev/angr/angr/exploration_techniques/tracer.py", line 200, in setup
    raise AngrTracerError("Could not step to the first address of the trace - state split")
angr.errors.AngrTracerError: Could not step to the first address of the trace - state split
~~~
Everything needed to replicate this bug is at https://gist.github.com/Kyle-Kyle/6feb9a839f0129c11f0ae860c5810dfe

**Comment by Kyle-Kyle** [comment]
The root cause is one of the init functions in `libpthread` calls `_libc_sigaction` which executes this line:
~~~
.text:000125F5 mov     eax, 0AEh
.text:000125FA call    large dword ptr gs:10h
.text:00012601 resultvar = eax         ; unsigned int
.text:00012601 cmp     resultvar, 0FFFFF000h
.text:00012606 ja      loc_126C0
~~~
Basically, it dereferences a function pointer in gdt:
~~~
gef➤  x/10i 0xf7fd5070
   0xf7fd5070 <__kernel_vsyscall>:	push   ecx
   0xf7fd5071 <__kernel_vsyscall+1>:	push   edx
   0xf7fd5072 <__kernel_vsyscall+2>:	push   ebp
   0xf7fd5073 <__kernel_vsyscall+3>:	mov    ebp,esp
   0xf7fd5075 <__kernel_vsyscall+5>:	sysenter 
   0xf7fd5077 <__kernel_vsyscall+7>:	int    0x80
   0xf7fd5079 <__kernel_vsyscall+9>:	pop    ebp
   0xf7fd507a <__kernel_vsyscall+10>:	pop    edx
   0xf7fd507b <__kernel_vsyscall+11>:	pop    ecx
   0xf7fd507c <__kernel_vsyscall+12>:	ret
~~~
I'm not whether our gdt can handle that. And I have no idea how to fix it.

**Comment by Kyle-Kyle** [comment]
@rhelmot

**Comment by rhelmot** [comment]
Nothing here is related to the gdt; gs just points to the thread-local storage region. We already set `gs:10` to point to a `vsyscall` simprocedure. Idk what the issue is but I suspect it's just `sigaction` returning an unconstrained value because it is unimplemented or implemented imprecisely.

**Comment by Kyle-Kyle** [comment]
Oh ok. I will try to fix it. Thanks!
