### ISSUE TITLE
RepHook.run() in exploration_techniques/tracer.py can cause "args' length must all be equal" error for x86_64 binary

### ISSUE THREAD

**Issue by jrdavis** [angr/angr#2139]
---

**Describe the bug.**
When using angr 8.20.1.7 with Driller on a x86_64 ELF binary I get a ```claripy.errors.ClaripyOperationError: args' length must all be equal``` error. The issue appears to be how RepHook.run() handles ```rep stos[bwdq]``` and ```rep movs[bwdq]``` instructions, in particular the ```state.regs.rdi += size``` statements.

Error message and stack trace:
```
ERROR   | 2020-05-11 16:58:54,115 | angr.exploration_techniques.oppologist | Original block hit an unsupported error
Traceback (most recent call last):
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/exploration_techniques/oppologist.py", line 82, in successors
    return simgr.successors(state, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/sim_manager.py", line 421, in successors
    return self._project.factory.successors(state, **run_args)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/factory.py", line 54, in successors
    return self.default_engine.process(*args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/engines/vex/light/slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/engines/engine.py", line 143, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/engines/failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/engines/syscall.py", line 18, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/engines/hook.py", line 61, in process_successors
    return self.process_procedure(state, successors, procedure, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/engines/procedure.py", line 37, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/sim_procedure.py", line 230, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/procedures/stubs/UserHook.py", line 8, in run
    result = user_func(self.state)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 70, in run
    state.regs.rdi += size
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/state_plugins/sim_action_object.py", line 123, in wrapper
    return self._preserving_unbound(getattr(claripy.ast.BV, op_name), *args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/state_plugins/sim_action_object.py", line 90, in _preserving_unbound
    return ast_preserving_op(f, *((self,) + tuple(args)), **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/state_plugins/sim_action_object.py", line 46, in ast_preserving_op
    a = ast_stripping_op(f, *args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/state_plugins/sim_action_object.py", line 40, in ast_stripping_op
    return f(*new_args, **new_kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/claripy/operations.py", line 50, in _op
    raise ClaripyOperationError(msg)
claripy.errors.ClaripyOperationError: args' length must all be equal
Traceback (most recent call last):
  File "reptest.py", line 3, in <module>
    for _, new_input in driller.Driller('./reptest', b'\x01', b'\x00' * 65536).drill_generator():
  File "/home/james/.venv/angr/lib/python3.6/site-packages/driller/driller_main.py", line 101, in drill_generator
    for i in self._drill_input():
  File "/home/james/.venv/angr/lib/python3.6/site-packages/driller/driller_main.py", line 141, in _drill_input
    simgr.step()
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/exploration_techniques/driller_core.py", line 39, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 225, in step
    return simgr.step(stash=stash, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/sim_manager.py", line 344, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/james/.venv/angr/lib/python3.6/site-packages/angr/exploration_techniques/tracer.py", line 253, in step_state
    sat_succs = succs_dict[None]  # satisfiable states
KeyError: None
```

**Environment Information.**
```
angr environment report
=============================
Date: 2020-05-11 16:50:16.286570
Running in virtual environment at /home/james/.venv/angr
Platform: linux-x86_64
Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
######## angr #########
Python found it in /home/james/.venv/angr/lib/python3.6/site-packages/angr
Pip version angr 8.20.1.7
Couldn't find git info
######## ailment #########
Python found it in /home/james/.venv/angr/lib/python3.6/site-packages/ailment
Pip version ailment 8.20.1.7
Couldn't find git info
######## cle #########
Python found it in /home/james/.venv/angr/lib/python3.6/site-packages/cle
Pip version cle 8.20.1.7
Couldn't find git info
######## pyvex #########
Python found it in /home/james/.venv/angr/lib/python3.6/site-packages/pyvex
Pip version pyvex 8.20.1.7
Couldn't find git info
######## claripy #########
Python found it in /home/james/.venv/angr/lib/python3.6/site-packages/claripy
Pip version claripy 8.20.1.7
Couldn't find git info
######## archinfo #########
Python found it in /home/james/.venv/angr/lib/python3.6/site-packages/archinfo
Pip version archinfo 8.20.1.7
Couldn't find git info
######## z3 #########
Python found it in /home/james/.venv/angr/lib/python3.6/site-packages/z3
Pip version z3-solver 4.8.8.0
Couldn't find git info
######## unicorn #########
Python found it in /home/james/.venv/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/james/.venv/angr/lib/python3.6/site-packages/angr/lib/angr_native.so', handle 2f51e00 at 0x7f10d694f518>
unicorn: <CDLL '/home/james/.venv/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 26d2f70 at 0x7f10d58bb4a8>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f10d6888b38>
z3: <CDLL '/home/james/.venv/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 28e8030 at 0x7f10d364be10>
```

**To Reproduce.**
Run the following script (with [reptest.zip](https://github.com/angr/angr/files/4610667/reptest.zip)):
```
import driller

for _, new_input in driller.Driller('./reptest', b'\x01', b'\x00' * 65536).drill_generator():
    print(new_input)

```
**Additional context.**
I think I've fixed it locally with this patch, but I'm not sure if it's the best way to do it:
```
diff --git a/exploration_techniques/tracer.py.original b/exploration_techniques/tracer.py
index f4578f1..64d039e 100644
--- a/exploration_techniques/tracer.py.original
+++ b/exploration_techniques/tracer.py
@@ -59,16 +59,17 @@ class RepHook:
             else:
                 raise NotImplementedError("Unsupported mnemonic %s" % self.mnemonic)
 
-            size = state.regs.ecx * multiplier
+            size = (state.regs.ecx if state.arch.name == "X86" else state.regs.rcx) * multiplier
 
             memset = SIM_PROCEDURES['libc']["memset"]
             memset().execute(state, arguments=[dst, val, size])
 
             if state.arch.name == "X86":
                 state.regs.edi += size
+                state.regs.ecx = 0
             else:
                 state.regs.rdi += size
-            state.regs.ecx = 0
+                state.regs.rcx = 0
 
         elif self.mnemonic.startswith("movs"):
 
@@ -86,7 +87,7 @@ class RepHook:
             else:
                 raise NotImplementedError("Unsupported mnemonic %s" % self.mnemonic)
 
-            size = state.regs.ecx * multiplier
+            size = (state.regs.ecx if state.arch.name == "X86" else state.regs.rcx) * multiplier
 
             memcpy = SIM_PROCEDURES['libc']["memcpy"]
             memcpy().execute(state, arguments=[dst, src, size])
@@ -94,10 +95,11 @@ class RepHook:
             if state.arch.name == "X86":
                 state.regs.edi += size
                 state.regs.esi -= size
+                state.regs.ecx = 0
             else:
                 state.regs.rdi += size
                 state.regs.rsi -= size
-            state.regs.ecx = 0
+                state.regs.rcx = 0
 
         else:
             import ipdb; ipdb.set_trace()
```

**Comment by rhelmot** [comment]
Yep, that is a good patch. I'll apply it.
