### ISSUE TITLE
Angr not loading ELF file

### ISSUE THREAD

**Issue by M-Rai** [angr/angr#2214]
Hello to everyone!
I'm having a problem with loading an ELF file with angr. When i do:
`p = angr.Project("suit_update.elf")`
I receive the following message error from the library:

```
WARNING | 2020-06-22 11:01:18,804 | cle.backends.elf.elf | Segment PT_LOAD is empty at 0x20000378!
WARNING | 2020-06-22 11:01:18,804 | cle.backends.elf.elf | Segment PT_LOAD is empty at 0x20000000!
Traceback (most recent call last):
  File "/home/marco/.local/lib/python3.6/site-packages/cle/memory.py", line 250, in unpack
    start, backer = next(self.backers(addr))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/.local/lib/python3.6/site-packages/angr/project.py", line 128, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/home/marco/.local/lib/python3.6/site-packages/cle/loader.py", line 134, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *preload_libs, preloading=True)
  File "/home/marco/.local/lib/python3.6/site-packages/cle/loader.py", line 664, in _internal_load
    main_obj = self._load_object_isolated(main_spec)
  File "/home/marco/.local/lib/python3.6/site-packages/cle/loader.py", line 767, in _load_object_isolated
    return backend_cls(full_spec, is_main_bin=self.main_object is None, loader=self, **options)
  File "/home/marco/.local/lib/python3.6/site-packages/cle/backends/elf/elf.py", line 115, in __init__
    self.__register_sections()
  File "/home/marco/.local/lib/python3.6/site-packages/cle/backends/elf/elf.py", line 734, in __register_sections
    self.__register_relocs(sec_readelf)
  File "/home/marco/.local/lib/python3.6/site-packages/cle/backends/elf/elf.py", line 690, in __register_relocs
    reloc = self._make_reloc(readelf_reloc, symbol, dest_sec)
  File "/home/marco/.local/lib/python3.6/site-packages/cle/backends/elf/elf.py", line 401, in _make_reloc
    return RelocClass(self, symbol, address, addend)
  File "/home/marco/.local/lib/python3.6/site-packages/cle/backends/elf/relocation/elfreloc.py", line 16, in __init__
    self._addend = self.owner.memory.unpack_word(self.relative_addr)
  File "/home/marco/.local/lib/python3.6/site-packages/cle/memory.py", line 275, in unpack_word
    return self.unpack(addr, self._arch.struct_fmt(size=size, signed=signed, endness=endness))[0]
  File "/home/marco/.local/lib/python3.6/site-packages/cle/memory.py", line 252, in unpack
    raise KeyError(addr)
KeyError: 536762184
```

I'm using angr version 8.20.1.7, but the error emerges even with the last version. I tried even specifying the arch in load_opt but it doesn't resolve anything.
The ELF is an application/x-executable for the board "SAMR21-xpro", built for RIOT OS and following the example suit_update in the official github of RIOT (for more info: https://github.com/RIOT-OS/RIOT/tree/master/examples/suit_update).
This is the WeTransfer link for downloading the ELF file (github doesn't support it here):
https://we.tl/t-KnsS8uMfCc
Hope someone can help me.
Thanks in advance!

**Comment by rhelmot** [comment]
I pushed https://github.com/angr/cle/commit/8cfedc60f8cc219d450a8799c540a44649cd12cb which makes the loader at least not crash, though your binary is pretty seriously fucked up and even IDA complains badly about it. Let me know if the loaded result looks good to you with the new patch.

**Comment by M-Rai** [comment]
Sorry for the delay. Ok, the loader still print an error, but at least doesn't crash anymore. There's another problem btw, correlated to the first: I need to create a CFG, using angr function CFGFast, so if the app is not loaded correctly all the project won't work. Any suggestion on how to proceed in the meantime?

**Comment by ltfish** [comment]
> I need to create a CFG, using angr function CFGFast, so if the app is not loaded correctly all the project won't work

What objects are there after loading (`project.loader.all_objects`)? What objects do you expect to be present?

`CFGFast` only cares about two things: (a) bytes for all blocks are mapped to the correct (or expected) locations, and (b) VEX can correctly lift these bytes.
