### ISSUE TITLE
SimAbstractMemory pickle error

### ISSUE THREAD

**Issue by 0xling** [angr/angr#2240]
---

**Describe the bug.**

The exception is
```
Traceback (most recent call last):
  File "/test.py", line 10, in <module>
    memory = pickle.load(f)
  File "/pypy3.6-v7.3.1-linux64/lib-python/3/pickle.py", line 1571, in _load
    encoding=encoding, errors=errors).load()
  File "/pypy3.6-v7.3.1-linux64/lib-python/3/pickle.py", line 1070, in load
    dispatch[key[0]](self)
  File "/pypy3.6-v7.3.1-linux64/lib-python/3/pickle.py", line 1527, in load_build
    setstate(state)
  File "/pypy3.6-v7.3.1-linux64/site-packages/angr/sim_state.py", line 230, in __setstate__
    p.set_state(self)
  File "/pypy3.6-v7.3.1-linux64/site-packages/angr/state_plugins/abstract_memory.py", line 316, in set_state
    SimMemory.set_state(self, state)
  File "/pypy3.6-v7.3.1-linux64/site-packages/angr/storage/memory.py", line 350, in set_state
    stack_region_map, generic_region_map = self._temp_stack_region_map, self._temp_generic_region_map
AttributeError: 'SimAbstractMemory' object has no attribute '_temp_stack_region_map'
```

the source code is 
```
import pickle
import angr
binary = '/bin/ls'
proj = angr.Project(binary, load_options={'auto_load_libs': False})
state = proj.factory.blank_state(mode="static")
memory = state.memory
with open('state.cache', 'wb') as f:
    pickle.dump(memory, f, pickle.HIGHEST_PROTOCOL)
with open('state.cache', 'rb') as f:
    memory = pickle.load(f)
```

**Environment Information.**

angr v8.20.6.8

**To Reproduce.**

**Additional context.**

**Comment by Alexeyan** [comment]
Bug does not reproduce on upstream angr for me.
