### ISSUE TITLE
protobuf minimum version

### ISSUE THREAD

**Issue by mattypiper** [angr/angr#2290]
**Describe the bug.**

I think angr requires a minimum version of python protobuf.  It seems `serialized_options` was introduced somewhere around protobuf 3.6. I suggest adding a minimum version to the protobuf entry in [setup.py](https://github.com/angr/angr/blob/1b901f2734cfd4a51f7849c52da326aa773fac6e/setup.py#L159).

I resolved quickly using `python3 -m pip install -U protobuf`. This was a new angr installation on a system with an older protobuf, so pip could've upgraded protobuf when angr was installing.

Traceback is below for additional context.

```sh
mrt@host:~/angr$ python3 -c 'import angr'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/__init__.py", line 30, in <module>
    from .sim_procedure import SimProcedure
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/sim_procedure.py", line 511, in <module>
    from angr.sim_type import SimTypePointer
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/sim_type.py", line 1755, in <module>
    from .state_plugins.view import SimMemView
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/state_plugins/__init__.py", line 10, in <module>
    from .javavm_memory import *
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/state_plugins/javavm_memory.py", line 7, in <module>
    from ..engines.soot.values import (SimSootValue_ArrayRef,
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/engines/__init__.py", line 4, in <module>
    from .vex import HeavyVEXMixin, TrackActionsMixin, SimInspectMixin, HeavyResilienceMixin, SuperFastpathMixin
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/engines/vex/__init__.py", line 1, in <module>
    from .claripy import *
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/engines/vex/claripy/__init__.py", line 1, in <module>
    from .datalayer import ClaripyDataMixin
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/engines/vex/claripy/datalayer.py", line 5, in <module>
    from ..light import VEXMixin
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/engines/vex/light/__init__.py", line 1, in <module>
    from .light import VEXMixin
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 7, in <module>
    from ....utils.constants import DEFAULT_STATEMENT
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/utils/__init__.py", line 5, in <module>
    from . import enums_conv
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/utils/enums_conv.py", line 6, in <module>
    from ..protos.primitives_pb2 import Edge
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/protos/__init__.py", line 2, in <module>
    from . import primitives_pb2
  File "/home/mrt/.local/lib/python3.7/site-packages/angr/protos/primitives_pb2.py", line 21, in <module>

... snip ...

TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```

**Comment by ltfish** [comment]
Great suggestion. Sorry that I did not really think through the compatibility problem of protobuf. I will add a minimum version requirement.
