### ISSUE TITLE
Angr failing in DeepState (maybe not angr, but help appreciated)

### ISSUE THREAD

**Issue by agroce** [angr/angr#2317]
This issue:  https://github.com/trailofbits/deepstate/issues/359

involves an angr crash.  It's not just the user.  Building the DeepState docker, I run deepstate-angr on the simplest example we have, basically, and get the same issue:

```
user@528158112b6a:~/deepstate/build_deepstate/examples$ deepstate-angr ./Crash --output_test_dir angr_out
INFO:deepstate:Setting log level from DEEPSTATE_LOG: 2
INFO:deepstate.core.base:Setting log level from --min_log_level: 2
Traceback (most recent call last):
  File "/usr/local/bin/deepstate-angr", line 33, in <module>
    sys.exit(load_entry_point('deepstate==0.1', 'console_scripts', 'deepstate-angr')())
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/symex/angr.py", line 514, in main
    return main_unit_test(args, project)
  File "/usr/local/lib/python3.6/dist-packages/deepstate-0.1-py3.6.egg/deepstate/executors/symex/angr.py", line 434, in main_unit_test
    angr.options.STRICT_PAGE_ACCESS})
  File "/home/user/.local/lib/python3.6/site-packages/angr/factory.py", line 99, in entry_state
    return self.project.simos.state_entry(**kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/angr/simos/linux.py", line 321, in state_entry
    state.mem[sym.rebased_addr].long = val
  File "/home/user/.local/lib/python3.6/site-packages/angr/state_plugins/view.py", line 213, in __setattr__
    return self.__getattr__(k).store(v)
  File "/home/user/.local/lib/python3.6/site-packages/angr/state_plugins/view.py", line 269, in store
    return self._type.store(self.state, self._addr, value)
  File "/home/user/.local/lib/python3.6/site-packages/angr/sim_type.py", line 241, in store
    state.memory.store(addr, value, endness=store_endness)
  File "/home/user/.local/lib/python3.6/site-packages/angr/storage/memory.py", line 572, in store
    self._store(request) #will use state_plugins/symbolic_memory.py
  File "/home/user/.local/lib/python3.6/site-packages/angr/state_plugins/symbolic_memory.py", line 819, in _store
    self._insert_memory_object(store_item['value'], store_item['addr'], store_item['size'])
  File "/home/user/.local/lib/python3.6/site-packages/angr/state_plugins/symbolic_memory.py", line 836, in _insert_memory_object
    self.mem.store_memory_object(mo)
  File "/home/user/.local/lib/python3.6/site-packages/angr/storage/paged_memory.py", line 783, in store_memory_object
    self._apply_object_to_page(p, mo, overwrite=overwrite)
  File "/home/user/.local/lib/python3.6/site-packages/angr/storage/paged_memory.py", line 761, in _apply_object_to_page
    raise SimSegfaultError(mo.base, 'non-writable')
angr.errors.SimSegfaultException: 0x704a90 (non-writable)
```

I'm unfortunately not up enough on angr internals to guess what that means.  Any ideas?  The example runs fine with manticore, for what little that is worth...  Perhaps some divergence between how we call angr and current angr API, but maybe the error will give you experts some clue to help point us in the right direction!

**Comment by rhelmot** [comment]
What it "means" is that angr is emulating a segfault in the guest program - it wrote to read-only memory. In terms of how to debug this, the standard angr debugging advice applies; you should examine the address trace (state.history.descriptions.hardcopy) in a disassembler and figure out at what point the program started behaving erratically.

**Comment by zardus** [comment]
IIRC, DeepState uses partially-consistent starting states, right? If so,
you might want to disable strict memory setting. I'm on mobile, so I don't
have the actual setting name on me.

**Comment by agroce** [comment]
Do we do that @pgoodman -- on the starting states?

**Comment by agroce** [comment]
Thanks @rhelmot and @zardus.  on investigation, I think that is indeed what's going on here, but there are some deeper alignment drifts between DeepState usage and angr reality (some programs it should find interesting paths in, manticore does, and it doesn't -- probably because we are no longer handling angr exits properly, which is how this issue arose)
