### ISSUE TITLE
CFGFast can't generate graph

### ISSUE THREAD

**Issue by Bearshanjun** [angr/angr#2338]
hi
i want use CFGFast generate CFG
my code is:
```
proj=angr.Project('/opt/code_pngfix')
cfg = proj.analyses.CFGFast()
plot_cfg(cfg, "mycfg",asminst=True, remove_imports=True, remove_path_terminator=True)
```

but an error occurred:
```
"dot" with args ['-Tpng', '/tmp/tmpxlnjrrzm'] returned code: -9

stdout, stderr:
 b''
b''

Traceback (most recent call last):
  File "outputGraph.py", line 10, in <module>
    plot_cfg(cfg, "mycfg",asminst=True, remove_imports=True, remove_path_terminator=True)
  File "/opt/angr-utils/angrutils/visualize.py", line 34, in plot_cfg
    vis.process(cfg.graph) 
  File "/opt/bingraphvis/bingraphvis/base.py", line 310, in process
    return self.output.generate(graph)
  File "/opt/bingraphvis/bingraphvis/output.py", line 217, in generate
    dotfile.write("{}.{}".format(self.fname, self.format), format=self.format)
  File "/usr/local/lib/python3.6/dist-packages/pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "/usr/local/lib/python3.6/dist-packages/pydot.py", line 1945, in create
    assert process.returncode == 0, process.returncode
AssertionError: -9
```

can you give me some advice or hints.

thanks

**Comment by rhelmot** [comment]
`plot_cfg` is a tool that isn't part of angr, so this isn't something we can really help you with.

**Comment by ltfish** [comment]
You may want to use angr management instead.
