### ISSUE TITLE
Address 0x8100000 is already backed

### ISSUE THREAD

**Issue by JerryWang304** [angr/angr#2353]
---

**Describe the bug.**
```
After run angr.Project(), it failed :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangfeng/.local/lib/python3.8/site-packages/angr/project.py", line 224, in __init__
    self.simos.configure_project()
  File "/home/wangfeng/.local/lib/python3.8/site-packages/angr/simos/linux.py", line 45, in configure_project
    self._loader_addr = self.project.loader.extern_object.allocate()
  File "/home/wangfeng/.local/lib/python3.8/site-packages/cle/loader.py", line 223, in extern_object
    self._internal_load(self._extern_object)
  File "/home/wangfeng/.local/lib/python3.8/site-packages/cle/loader.py", line 774, in _internal_load
    self._map_object(obj)
  File "/home/wangfeng/.local/lib/python3.8/site-packages/cle/loader.py", line 876, in _map_object
    self.memory.add_backer(base_addr, obj.memory)
  File "/home/wangfeng/.local/lib/python3.8/site-packages/cle/memory.py", line 194, in add_backer
    raise ValueError("Address %#x is already backed!" % start)
ValueError: Address 0x8100000 is already backed!
```

**Environment Information.**

Python version 3.8.5
Angr version 9.0.4495

**To Reproduce.**

ELF file [test.elf.zip](https://github.com/angr/angr/files/5413176/test.elf.zip)
unzip test.elf.zip
```python
>>> import angr
>>> angr.Project("./test.elf")


```

**Additional context.**

**Comment by subwire** [comment]
@JerryWang304 took care of this with @ltfish , fix incoming, thanks for reporting!

**Comment by ltfish** [comment]
Should be fixed by that cle PR.
