### ISSUE TITLE
SimPackets stdin not compatible with %lu scanf format

### ISSUE THREAD

**Issue by Nathan-Huckleberry** [angr/angr#2369]
---

**Describe the bug.**

When using stdin as SimPackets, an error occurs if `scanf("%lu", &x);` is called.
```
Traceback (most recent call last):
  File "solve.py", line 56, in <module>
    sys.exit(main(sys.argv[1]))
  File "solve.py", line 34, in main
    sm.step()
  File "/home/huck/.local/lib/python3.8/site-packages/angr/sim_manager.py", line 346, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/sim_manager.py", line 383, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/sim_manager.py", line 422, in successors
    return self._project.factory.successors(state, **run_args)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/factory.py", line 60, in successors
    return self.default_engine.process(*args, **kwargs)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/engines/vex/light/slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/engines/engine.py", line 149, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/engines/failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/engines/syscall.py", line 18, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/engines/hook.py", line 61, in process_successors
    return self.process_procedure(state, successors, procedure, **kwargs)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/engines/procedure.py", line 37, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/sim_procedure.py", line 226, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/procedures/libc/scanf.py", line 18, in run
    items = fmt_str.interpret(1, self.arg, simfd=simfd)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/procedures/stubs/format_parser.py", line 280, in interpret
    status, i, num_bytes = self.parser._sim_atoi_inner(position, region, base=base, read_length=fmt_spec.length_spec)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/procedures/stubs/format_parser.py", line 531, in _sim_atoi_inner
    return strtol.strtol_inner(str_addr, self.state, region, base, True, read_length=read_length)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/procedures/libc/strtol.py", line 44, in strtol_inner
    condition, value, num_bytes = strtol._load_num_with_prefix(prefix, s, region, state, base, signed, read_length)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/procedures/libc/strtol.py", line 62, in _load_num_with_prefix
    condition, value, num_bytes = strtol._string_to_int(addr+length, state, region, base, signed, read_length)
  File "/home/huck/.local/lib/python3.8/site-packages/angr/procedures/libc/strtol.py", line 87, in _string_to_int
    expression, _ = strtol._char_to_val(region.load(s, 1), base)
AttributeError: 'SimPackets' object has no attribute 'load'
```
It seems like the string_to_int implementation expects a SimFile (or some other DefaultMemory) instead of SimPackets. I'm unsure whether this is intended behavior or not, but it seems unintentional. As far as I can tell, the code just loads the string address again without _really_ needing to.

**Environment Information.**

```
angr environment report
=============================
Date: 2020-10-29 00:51:50.492561
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.8.5 (default, Sep  5 2020, 10:50:12) 
[GCC 10.2.0]
######## angr #########
Python found it in /home/huck/.local/lib/python3.8/site-packages/angr
Pip version angr 9.0.4495
Couldn't find git info
######## ailment #########
Python found it in /home/huck/.local/lib/python3.8/site-packages/ailment
Pip version ailment 9.0.4495
Couldn't find git info
######## cle #########
Python found it in /home/huck/.local/lib/python3.8/site-packages/cle
Pip version cle 9.0.4495
Couldn't find git info
######## pyvex #########
Python found it in /home/huck/.local/lib/python3.8/site-packages/pyvex
Pip version pyvex 9.0.4495
Couldn't find git info
######## claripy #########
Python found it in /home/huck/.local/lib/python3.8/site-packages/claripy
Pip version claripy 9.0.4495
Couldn't find git info
######## archinfo #########
Python found it in /home/huck/.local/lib/python3.8/site-packages/archinfo
Pip version archinfo 9.0.4495
Couldn't find git info
######## z3 #########
Python found it in /home/huck/.local/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/huck/.local/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/huck/.local/lib/python3.8/site-packages/angr/lib/angr_native.so', handle 55eab4f48c20 at 0x7f89bd767700>
unicorn: <CDLL '/home/huck/.local/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 55eab40fa1f0 at 0x7f89dce315e0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f89ddc3b5b0>
z3: <CDLL '/home/huck/.local/lib/python3.8/site-packages/z3/lib/libz3.so', handle 55eab43664c0 at 0x7f89da6fad60>
```

**To Reproduce.**

Running `python3 solve.py mmaas-good` crashes
[files.zip](https://github.com/angr/angr/files/5456403/files.zip)

**Additional context.**

**Comment by Nathan-Huckleberry** [comment]
After further inspection it looks like I'm failing a check on `angr/procedures/stubs/format_parser.py:129`: `simfd.read_pos == len(simfd.read_storage.content)`

I'm guessing that reading a packet then constraining it before format string is called will cause `read_pos = 0`, but `simfd.read_storange.content = 1`. It's not clear to me why this check is needed.

**Comment by rhelmot** [comment]
I suppose the check is not necessary. The intention is based on the fact that the logic for performing scanf on a packet stream can be (is) optimized by orders of magnitude by assuming that there are no constraints on the input format, and as a result we can emulate scanf by constraining the input to be a serialization of the result instead of parsing the result from the input. I will remove the check, but if you put the wrong constraints on the input bad things will happen.
