### ISSUE TITLE
IndexError when creating CFGEmulated on ARM thumb binary

### ISSUE THREAD

**Issue by manuelmohr** [angr/angr#2448]
**Describe the bug.**
When running the CFGEmulated analysis on the attached ARM thumb binary, angr crashes with the following backtrace:

```
>>> import angr
>>> p = angr.Project("get")
>>> cfg = p.analyses.CFGEmulated()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/cfg/cfg_emulated.py", line 306, in __init__
    self._analyze()
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 216, in _analyze
    self._analysis_core_baremetal()
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 368, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 386, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/cfg/cfg_emulated.py", line 1295, in _get_successors
    resolved, resolved_targets, ij = self._indirect_jump_encountered(addr, cfg_node, irsb, func_addr,
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/cfg/cfg_base.py", line 2331, in _indirect_jump_encountered
    resolved, resolved_targets = self._resolve_indirect_jump_timelessly(addr, irsb, func_addr, jumpkind)
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/cfg/cfg_base.py", line 2274, in _resolve_indirect_jump_timelessly
    r, resolved_targets = res.resolve(self, addr, func_addr, block, jumpkind)
  File "/home/manuel/.virtualenvs/angr/lib/python3.8/site-packages/angr/analyses/cfg/indirect_jump_resolvers/arm_elf_fast.py", line 60, in resolve
    stmt = block.statements[stmt_idx]
IndexError: list index out of range
```

**Environment Information.**
```% pip show angr
Name: angr
Version: 9.0.5171
% python --version
Python 3.8.5
```

**To Reproduce.**
```
p = angr.Project("get")
cfg = p.analyses.CFGEmulated()
```

[get.zip](https://github.com/angr/angr/files/5754289/get.zip)

Binary is from this reduced test case:
```c
__attribute__((noinline)) int get(void)
{
    volatile int stuff[100] = { 0x1000 };
    return stuff[0];
}

int main(int argc, char **argv)
{
        get();
}
```

compiled with `arm-none-eabi-gcc -mthumb -g -O2 get.c --specs=nosys.specs -o get`.

**Additional context.**
Only breaks with `-mthumb`.  Works with `-marm`.

**Comment by ltfish** [comment]
Thanks for reporting!
