### ISSUE TITLE
 Mach-O (clang-1200.0.32.28) - IndexError: list index out of range

### ISSUE THREAD

**Issue by SajjadPourali** [angr/angr#2455]
Hello All,
 I have tried to recompile the `fauxware` example for macOS Big Sur, and I have got "IndexError: list index out of range" error.
```
bash-3.2$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
bash-3.2$ gcc fauxware.c -o fauxware
fauxware.c:29:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
1 warning generated.
bash-3.2$ python3 solve.py
WARNING | 2021-01-03 17:43:57,381 | cle.backends.macho.macho | The Mach-O backend is not well-supported. Good luck!
WARNING | 2021-01-03 17:43:57,394 | angr.storage.memory_mixins.default_filler_mixin | The program is accessing memory or registers with an unspecified value. This could indicate unwanted behavior.
WARNING | 2021-01-03 17:43:57,394 | angr.storage.memory_mixins.default_filler_mixin | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2021-01-03 17:43:57,394 | angr.storage.memory_mixins.default_filler_mixin | 1) setting a value to the initial state
WARNING | 2021-01-03 17:43:57,394 | angr.storage.memory_mixins.default_filler_mixin | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2021-01-03 17:43:57,394 | angr.storage.memory_mixins.default_filler_mixin | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
WARNING | 2021-01-03 17:43:57,395 | angr.storage.memory_mixins.default_filler_mixin | Filling register rbp with 8 unconstrained bytes referenced from 0x100003df0 (not part of a loaded object)
WARNING | 2021-01-03 17:43:57,399 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x0 with 8 unconstrained bytes referenced from 0x100003dff (not part of a loaded object)
WARNING | 2021-01-03 17:43:57,402 | angr.storage.memory_mixins.default_filler_mixin | Filling register rdi with 8 unconstrained bytes referenced from 0x100003e0d (not part of a loaded object)
WARNING | 2021-01-03 17:43:57,408 | angr.storage.memory_mixins.default_filler_mixin | Filling register rsi with 8 unconstrained bytes referenced from 0x100003e10 (not part of a loaded object)
Traceback (most recent call last):
  File "/Users/---/Desktop/angr-doc/examples/fauxware/solve.py", line 80, in <module>
    sys.stdout.buffer.write(basic_symbolic_execution())
  File "/Users/---/Desktop/angr-doc/examples/fauxware/solve.py", line 63, in basic_symbolic_execution
    input_0 = sm.active[0].posix.dumps(0)
IndexError: list index out of range
```
The binary has uploaded in the following URL:
https://ufile.io/h2x1594m

Thanks.

**Comment by ltfish** [comment]
Obviously there is no active states in the end. What do you see when you do `print(sm)`?

**Comment by SajjadPourali** [comment]
Yes, there is not any active state. The result of printing simulation_manager and its error message has mentioned in the following image:
<img width="1407" alt="Screen Shot 2021-01-07 at 14 04 23" src="https://user-images.githubusercontent.com/20374762/103882852-a4f82b80-50f1-11eb-96b9-aea64a7a3991.png">
