### ISSUE TITLE
CONSERVATIVE_READ_STRATEGY seems to cause a claripy error

### ISSUE THREAD

**Issue by r4dr3fr4d** [angr/angr#2471]
At this time I can only include the backtrace.

```
Traceback (most recent call last):
  File "/home/user/angr_pypy/site-packages/claripy/frontends/light_frontend.py", line 58, in min
    return self._solver_backend.min(e)
  File "/home/user/angr_pypy/site-packages/claripy/backends/__init__.py", line 565, in min
    return self._min(self.convert(expr), extra_constraints=self.convert_list(extra_constraints), solver=solver, model_callback=model_callback)
  File "/home/user/angr_pypy/site-packages/claripy/backends/backend_concrete.py", line 103, in convert
    return super().convert(expr)
  File "/home/user/angr_pypy/site-packages/claripy/backends/__init__.py", line 167, in convert
    "conversion on a child node" % (self, ast.op, ast.__class__.__name__))
claripy.errors.BackendError: <claripy.backends.backend_concrete.BackendConcrete object at 0x00007fe49dcd9ad0> can't handle operation __add__ (BV) due to a failed conversion on a child node

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/angr_pypy/site-packages/angr/state_plugins/solver.py", line 89, in wrapped_f
    return f(*args, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/state_plugins/solver.py", line 541, in min
    return self._solver.min(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/user/angr_pypy/site-packages/claripy/frontend_mixins/concrete_handler_mixin.py", line 37, in min
    return super(ConcreteHandlerMixin, self).min(e, **kwargs)
  File "/home/user/angr_pypy/site-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 52, in min
    return super(ConstraintFilterMixin, self).min(e, extra_constraints=ec, **kwargs)
  File "/home/user/angr_pypy/site-packages/claripy/frontends/light_frontend.py", line 60, in min
    raise ClaripyFrontendError("Light solver can't handle this min().")
claripy.errors.ClaripyFrontendError: Light solver can't handle this min().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./cgc_board.py", line 377, in <module>
    etn = et = run_path(e_test, test_path_read_kw)
  File "./cgc_board.py", line 75, in run_path
    succ = state.step()
  File "/home/user/angr_pypy/site-packages/angr/sim_state.py", line 587, in step
    return self.project.factory.successors(self, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/factory.py", line 60, in successors
    return self.default_engine.process(*args, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/engine.py", line 149, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/syscall.py", line 18, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/hook.py", line 54, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/unicorn.py", line 90, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/soot/engine.py", line 64, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/heavy.py", line 136, in process_successors
    self.handle_vex_block(irsb)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/super_fastpath.py", line 19, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/slicing.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/actions.py", line 30, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/inspect.py", line 45, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/light.py", line 446, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/slicing.py", line 30, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/inspect.py", line 40, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/resilience.py", line 36, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/heavy.py", line 202, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/light.py", line 51, in _handle_vex_stmt
    handler(stmt)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/light.py", line 188, in _handle_vex_stmt_WrTmp
    self._analyze_vex_stmt_WrTmp_data(stmt.data)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/light.py", line 184, in _analyze_vex_stmt_WrTmp_data
    def _analyze_vex_stmt_WrTmp_data(self, *a, **kw): return self. _handle_vex_expr(*a, **kw)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/inspect.py", line 31, in _handle_vex_expr
    return super()._handle_vex_expr(expr)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/light.py", line 55, in _handle_vex_expr
    result = handler(expr)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/light/light.py", line 87, in _handle_vex_expr_Load
    expr.end)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/actions.py", line 114, in _perform_vex_expr_Load
    result = super()._perform_vex_expr_Load(addr, ty, end, condition=condition, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/heavy.py", line 282, in _perform_vex_expr_Load
    result = super()._perform_vex_expr_Load(addr, ty, endness, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/claripy/datalayer.py", line 83, in _perform_vex_expr_Load
    res = super()._perform_vex_expr_Load(addr, ty, endness, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/engines/vex/heavy/heavy.py", line 29, in _perform_vex_expr_Load
    condition=condition)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/unwrapper_mixin.py", line 18, in load
    **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/name_resolution_mixin.py", line 57, in load
    return super().load(addr, size=size, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/bvv_conversion_mixin.py", line 29, in load
    return super().load(addr, size=size, fallback=fallback_bv, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/clouseau_mixin.py", line 86, in load
    **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/actions_mixin.py", line 13, in load
    r = super().load(addr, size=size, condition=condition, fallback=fallback, action=action, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/underconstrained_mixin.py", line 17, in load
    return super().load(addr, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/size_resolution_mixin.py", line 69, in load
    return super().load(addr, size=size, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/size_resolution_mixin.py", line 28, in load
    return super().load(addr, size=out_size, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/address_concretization_mixin.py", line 260, in load
    concrete_addrs = self._interleave_ints(sorted(self.concretize_read_addr(addr)))
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/address_concretization_mixin.py", line 228, in concretize_read_addr
    return self._apply_concretization_strategies(addr, strategies, 'load')
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/address_concretization_mixin.py", line 176, in _apply_concretization_strategies
    a = s.concretize(self, e)
  File "/home/user/angr_pypy/site-packages/angr/concretization_strategies/__init__.py", line 62, in concretize
    return self._concretize(memory, addr)
  File "/home/user/angr_pypy/site-packages/angr/concretization_strategies/range.py", line 13, in _concretize
    mn,mx = self._range(memory, addr)
  File "/home/user/angr_pypy/site-packages/angr/concretization_strategies/__init__.py", line 54, in _range
    return (self._min(memory, addr, **kwargs), self._max(memory, addr, **kwargs))
  File "/home/user/angr_pypy/site-packages/angr/concretization_strategies/__init__.py", line 28, in _min
    return memory.state.solver.min(addr, exact=kwargs.pop('exact', self._exact), **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/state_plugins/solver.py", line 146, in concrete_shortcut_scalar
    return f(self, *args, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/home/user/angr_pypy/site-packages/angr/state_plugins/solver.py", line 93, in wrapped_f
    raise SimSolverModeError("Claripy threw an error") from e
angr.errors.SimSolverModeError: Claripy threw an error
```

**Comment by r4dr3fr4d** [comment]
Also, it seems the option only gets recognized if added at state creation - not when using state.options.add().  But that would be a separate issue

**Comment by rhelmot** [comment]
Is this perhaps related to the thing I said on your other issue about using `options=` instead of `add_options=`

also there are a handful of state options that only take effect if they are used on state creation, this is expected behavior
