### ISSUE TITLE
Java Symblic Execution Example - Error

### ISSUE THREAD

**Issue by JeffersonDing** [angr/angr#2537]
---

I was testing the java symbolic execution examples from the official `angr-docs` repository and it ran into some errors. Here's is the prettified output:
```
Traceback (most recent call last):
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/vault-door-1/java_crackme1/solve.py", line 40, in <module>
    test()
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/vault-door-1/java_crackme1/solve.py", line 34, in test
    test_java_crackme1()
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/vault-door-1/java_crackme1/solve.py", line 12, in test_java_crackme1
    project = angr.Project(binary_path)
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/angr/lib/python3.9/site-packages/angr/project.py", line 131, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/angr/lib/python3.9/site-packages/cle/loader.py", line 138, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *preload_libs, *force_load_libs, preloading=(main_binary, *preload_libs))
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/angr/lib/python3.9/site-packages/cle/loader.py", line 657, in _internal_load
    obj = self._load_object_isolated(main_spec)
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/angr/lib/python3.9/site-packages/cle/loader.py", line 839, in _load_object_isolated
    result = backend_cls(binary, binary_stream, is_main_bin=self.main_object is None, loader=self, **options)
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/angr/lib/python3.9/site-packages/cle/backends/java/jar.py", line 42, in __init__
    super().__init__(jar_path, binary_stream,
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/angr/lib/python3.9/site-packages/cle/backends/java/soot.py", line 47, in __init__
    pysoot_lifter = Lifter(self.binary,
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/lifter.py", line 57, in __init__
    self._get_ir()
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/lifter.py", line 69, in _get_ir
    self.soot_wrapper.init(config)
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/jython_wrapper.py", line 86, in wrapper
    return self.remote_call((name, args, kwargs, ipc_options))
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/jython_wrapper.py", line 106, in remote_call
    type_res, buf = self._remote_call_int()
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/jython_wrapper.py", line 162, in _remote_call_int
    raise JythonClientException(estr)
pysoot.errors.JythonClientException: JYTHON SOCKET CLOSED
STDOUT:
b'Soot CUSTOM: Scene created! >>> 3
'
STDERR:
b'WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/jython_bin/jython.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
'b"DEBUG   | 2021-02-22 12:07:39,243 | pysoot.jython_runner | created class <class 'soot_manager.SootManager'>
"b"DEBUG   | 2021-02-22 12:07:39,259 | pysoot.jython_runner | received command: (u'__init__', ({u'ir_format': u'shimple', u'android_sdk': u'None', u'main_class': u'None', u'soot_classpath': u'/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/bin/jce.jar:/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/bin/rt.jar', u'input_format': u'jar', u'input_file': u'/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/vault-door-1/java_crackme1/crackme1.jar'},), {}, {u'return_pickle': False, u'save_pickle': None, u'return_result': True, u'split_results': 10})
"b'Traceback (most recent call last):
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/jython_runner.py", line 105, in <module>
    jc.main_loop()
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/jython_runner.py", line 48, in main_loop
    instance = created_class(*r[1], **r[2])
  File "/home/tydin/git_repo/CTF/Pico_CTF_2020_Archive/angr/pysoot/pysoot/soot_manager.py", line 40, in __init__
    self._create_scene(config)
  File "/home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot/pysoot/soot_manager.py", line 73, in _create_scene
    Scene.v().loadNecessaryClasses()
'b'\tat org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
\tat org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
\tat org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
\tat soot.asm.AsmClassSource.resolve(AsmClassSource.java:60)
\tat soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:236)
\tat soot.SootResolver.bringToHierarchy(SootResolver.java:209)
\tat soot.SootResolver.bringToSignatures(SootResolver.java:267)
\tat soot.SootResolver.processResolveWorklist(SootResolver.java:171)
\tat soot.SootResolver.resolveClass(SootResolver.java:134)
\tat soot.Scene.loadClass(Scene.java:876)
\tat soot.Scene.loadClassAndSupport(Scene.java:862)
\tat soot.Scene.loadNecessaryClasses(Scene.java:1616)
\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)

'b'java.lang.IllegalArgumentException: java.lang.IllegalArgumentException
'
```
I am really new to angr and I have no idea on how to solve this issue. I make sure that my dependencies are correct, according to the docs and here is the list:
```
Package           Version    Location
----------------- ---------- ----------------------------------------------------------
ailment           9.0.5903
angr              9.0.5903
archinfo          9.0.5903
bitstring         3.1.7
cachetools        4.2.1
capstone          4.0.2
cffi              1.14.5
claripy           9.0.5903
cle               9.0.5903
CppHeaderParser   2.7.4
cvc4-solver       1.6
decorator         4.4.2
dpkt              1.9.5
future            0.18.2
gitdb             4.0.5
GitPython         3.1.13
itanium-demangler 1.0
mulpyplexer       0.9
networkx          2.5
pefile            2019.4.18
pip               20.1.1
pkg-resources     0.0.0
plumbum           1.7.0
ply               3.11
progressbar2      3.53.1
protobuf          3.15.1
psutil            5.8.0
pycparser         2.20
pyelftools        0.27
PySMT             0.8.1.dev1 /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysmt
pysoot            7.7.12.1   /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr/pysoot
python-utils      2.5.6
pyvex             9.0.5903
rpyc              5.0.1
setuptools        44.0.0
six               1.15.0
smmap             3.0.5
sortedcontainers  2.3.0
unicorn           1.0.2rc4
wheel             0.34.2
z3-solver         4.8.10.0
```
Any help will be apperciated! 
Thanks!

**Comment by JeffersonDing** [comment]
I got it, I wasn't running the `angr-dev` repository. Thanks!

**Comment by JeffersonDing** [comment]
I installed the `dev` repo but this error is still present.

**Comment by twizmwazin** [comment]
Can you share another `pip freeze` of your virtualenv now that you have installed everything via angr-dev?

**Comment by JeffersonDing** [comment]
I was still testing around, here is my updated virtualenv environment 
So this is the state after using the `angr-dev` install script `./install.sh -i -e angrdev`. Then I manually install `pysoot` and the correct version of `pysmt` according to the docs.
Tried on both `Kali Linux` and `Ubuntu`

`pip list`
```
Package           Version        Location
----------------- -------------- --------------------------------------------------------------------
ailment           9.0.gitrolling /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/ailment
angr              9.0.gitrolling /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/angr
angr-targets      0.1            /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/angr-targets
angrop            9.0.gitrolling /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/angrop
archinfo          9.0.gitrolling /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/archinfo
archr             9.0.gitrolling /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/archr
astroid           2.5
avatar2           1.4.1
backcall          0.2.0
bitstring         3.1.7
cachetools        4.2.1
capstone          4.0.2
certifi           2020.12.5
cffi              1.14.5
chardet           4.0.0
claripy           9.0.gitrolling /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/claripy
cle               9.0.gitrolling /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/cle
configparser      5.0.1
coverage          5.4
CppHeaderParser   2.7.4
decorator         4.4.2
docker            4.4.3
dpkt              1.9.5
flaky             3.7.0
future            0.18.2
gitdb             4.0.5
GitPython         3.1.13
idna              2.10
intervaltree      3.1.0
ipdb              0.13.4
ipython           7.20.0
ipython-genutils  0.2.0
isort             5.7.0
itanium-demangler 1.0
jedi              0.18.0
keystone-engine   0.9.2
lazy-object-proxy 1.5.2
mccabe            0.6.1
monkeyhex         1.7.1          /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/monkeyhex
mulpyplexer       0.9            /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/mulpyplexer
nclib             1.0.0
networkx          2.5
nose              1.3.7
nose-timer        1.0.0
npyscreen         4.10.5
parse             1.19.0
parso             0.8.1
patchelf-wrapper  1.2.0
pefile            2019.4.18
pexpect           4.8.0
pickleshare       0.7.5
pip               21.0.1
pkg-resources     0.0.0
plumbum           1.7.0
ply               3.11
posix-ipc         1.0.5
progressbar       2.5
progressbar2      3.53.1
prompt-toolkit    3.0.16
protobuf          3.15.1
psutil            5.8.0
ptyprocess        0.7.0
pycparser         2.20
pyelftools        0.27
pygdbmi           0.10.0.0
Pygments          2.8.0
pylink-square     0.8.2
pylint            2.7.0
PySMT             0.8.1.dev1     /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/pysmt
pysoot            7.7.12.1       /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/pysoot
python-utils      2.5.6
pyusb             1.1.1
pyvex             9.0.gitrolling /home/tydin/git_repo/CTF/Pico_CTF_2019_Archive/angr-dev/pyvex
requests          2.25.1
rpyc              5.0.1
setuptools        44.0.0
shellphish-qemu   0.9.11
six               1.15.0
smmap             3.0.5
sortedcontainers  2.3.0
SQLAlchemy        1.3.23
toml              0.10.2
traitlets         5.0.5
unicorn           1.0.2rc4
urllib3           1.26.3
wcwidth           0.2.5
websocket-client  0.57.0
wheel             0.34.2
wrapt             1.12.1
z3-solver         4.8.10.0
```
`pip freeze`
```
-e git+https://github.com/angr/ailment@7db31a7b29910384062c358fb06c3250de2cddbb#egg=ailment
-e git+https://github.com/angr/angr@5fedfc280f605bd605c58ae1d608517d9569c774#egg=angr
-e git+https://github.com/angr/angr-targets@22805e8cfd36569e776f923978f92d6948804299#egg=angr_targets
-e git+https://github.com/angr/angrop@dbb26d25ac5161433fd550dffd590b6ca79dd864#egg=angrop
-e git+https://github.com/angr/archinfo@f5712a1fe0fbc315c4e9bbcf96582e139f745b33#egg=archinfo
-e git+https://github.com/angr/archr@2130e0a5766f042149683873f94d10f8118f159a#egg=archr
astroid==2.5
avatar2==1.4.1
backcall==0.2.0
bitstring==3.1.7
cachetools==4.2.1
capstone==4.0.2
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
-e git+https://github.com/angr/claripy@689506c9c834314f9a4ad6fe6ffcda7087f74c9c#egg=claripy
-e git+https://github.com/angr/cle@8e861c8e27f349b514b5b57bf1ee204fb96d5a3e#egg=cle
configparser==5.0.1
coverage==5.4
CppHeaderParser==2.7.4
decorator==4.4.2
docker==4.4.3
dpkt==1.9.5
flaky==3.7.0
future==0.18.2
gitdb==4.0.5
GitPython==3.1.13
idna==2.10
intervaltree==3.1.0
ipdb==0.13.4
ipython==7.20.0
ipython-genutils==0.2.0
isort==5.7.0
itanium-demangler==1.0
jedi==0.18.0
keystone-engine==0.9.2
lazy-object-proxy==1.5.2
mccabe==0.6.1
-e git+https://git:@github.com/rhelmot/monkeyhex@2718ae888d05c0827af3aca9bb46d25f773edfc2#egg=monkeyhex
-e git+https://git:@github.com/zardus/mulpyplexer@2f3c8761650b09a1ff8a14ef64c346ec0b610b42#egg=mulpyplexer
nclib==1.0.0
networkx==2.5
nose==1.3.7
nose-timer==1.0.0
npyscreen==4.10.5
parse==1.19.0
parso==0.8.1
patchelf-wrapper==1.2.0
pefile==2019.4.18
pexpect==4.8.0
pickleshare==0.7.5
pkg-resources==0.0.0
plumbum==1.7.0
ply==3.11
posix-ipc==1.0.5
progressbar==2.5
progressbar2==3.53.1
prompt-toolkit==3.0.16
protobuf==3.15.1
psutil==5.8.0
ptyprocess==0.7.0
pycparser==2.20
pyelftools @ git+https://github.com/eliben/pyelftools@46187f45f6085c8e28b7878c4058283d3ba5b812
pygdbmi==0.10.0.0
Pygments==2.8.0
pylink-square==0.8.2
pylint==2.7.0
-e git+https://github.com/pysmt/pysmt.git@6d792db47be5f8734db15848faca9bc6b770085e#egg=PySMT
-e git+https://github.com/angr/pysoot@d08dc569ec35796ccea5509b3e04b74967bcfd48#egg=pysoot
python-utils==2.5.6
pyusb==1.1.1
-e git+https://github.com/angr/pyvex@38af62047b8a7785feeee6b5f243ad1dbd7db1f6#egg=pyvex
requests==2.25.1
rpyc==5.0.1
shellphish-qemu==0.9.11
six==1.15.0
smmap==3.0.5
sortedcontainers==2.3.0
SQLAlchemy==1.3.23
toml==0.10.2
traitlets==5.0.5
unicorn==1.0.2rc4
urllib3==1.26.3
wcwidth==0.2.5
websocket-client==0.57.0
wrapt==1.12.1
z3-solver==4.8.10.0
```

**Comment by JeffersonDing** [comment]
Another thing is that after the default installation, i see that `six` is install under `pip list` but it says `module not found` when I import `angr`. What fixed it was to uninstall `six` and install it again. I wonder if that is related.
Thanks!

**Comment by rhelmot** [comment]
With respect to six, I suspect that this has something to do with https://github.com/pysmt/pysmt/issues/652. Not sure where that leaves us in terms of this issue. I encountered the same problem while trying to replicate your issue and your workaround worked fine.

However, I was not able to replicate the java class nonsense bug. here's my `pip freeze` of a fresh angr install which ran the example perfectly:

```
-e git+git@github.com:angr/ailment@7db31a7b29910384062c358fb06c3250de2cddbb#egg=ailment
-e git+git@github.com:angr/angr@c0a68b2b4078a35607c93974e709ef6901c8667a#egg=angr
-e git+git@github.com:angr/angr-targets@22805e8cfd36569e776f923978f92d6948804299#egg=angr_targets
-e git+git@github.com:angr/angrop@dbb26d25ac5161433fd550dffd590b6ca79dd864#egg=angrop
appdirs==1.4.3
-e git+git@github.com:angr/archinfo@f5712a1fe0fbc315c4e9bbcf96582e139f745b33#egg=archinfo
-e git+git@github.com:angr/archr@13877ee4bea2ad7ae63aeec3e4b36b3bb074254b#egg=archr
astroid==2.5.1
avatar2==1.4.3
backcall==0.2.0
bitstring==3.1.7
CacheControl==0.12.6
cached-property==1.5.2
cachetools==4.2.1
capstone==4.0.2
certifi==2019.11.28
cffi==1.14.5
chardet==3.0.4
-e git+git@github.com:angr/claripy@f1396ddc8f637f51a7c1328a627e26b56f6ce658#egg=claripy
-e git+git@github.com:angr/cle@4a7e4f7a6f1151f5587bf8bfa919da0064bd2449#egg=cle
colorama==0.4.3
configparser==5.0.2
contextlib2==0.6.0
coverage==5.5
CppHeaderParser==2.7.4
cvc4-solver==1.6
decorator==4.4.2
distlib==0.3.0
distro==1.4.0
docker==4.4.4
dpkt==1.9.5
flaky==3.7.0
future==0.18.2
gitdb==4.0.5
GitPython==3.1.14
greenlet==1.0.0
html5lib==1.0.1
idna==2.8
intervaltree==3.1.0
ipaddr==2.2.0
ipdb==0.13.6
ipython==7.21.0
ipython-genutils==0.2.0
isort==5.7.0
itanium-demangler==1.0
jedi==0.18.0
keystone-engine==0.9.2
lazy-object-proxy==1.5.2
lockfile==0.12.2
mccabe==0.6.1
-e git+https://git:@github.com/rhelmot/monkeyhex@2718ae888d05c0827af3aca9bb46d25f773edfc2#egg=monkeyhex
msgpack==0.6.2
-e git+https://git:@github.com/zardus/mulpyplexer@2f3c8761650b09a1ff8a14ef64c346ec0b610b42#egg=mulpyplexer
nclib==1.0.0
neovim==0.3.1
networkx==2.5
nose==1.3.7
nose-timer==1.0.0
npyscreen==4.10.5
packaging==20.3
parse==1.19.0
parso==0.8.1
patchelf-wrapper==1.2.0
pefile==2019.4.18
pep517==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
pkg-resources==0.0.0
plumbum==1.7.0
ply==3.11
posix-ipc==1.0.5
progress==1.5
progressbar==2.5
progressbar2==3.53.1
prompt-toolkit==3.0.16
protobuf==3.15.5
psutil==5.8.0
ptyprocess==0.7.0
pycparser==2.20
pyelftools==0.27
pygdbmi==0.10.0.0
Pygments==2.8.1
pylink-square==0.8.2
pylint==2.7.2
pynvim==0.4.3
pyparsing==2.4.6
-e git+https://github.com/pysmt/pysmt.git@6d792db47be5f8734db15848faca9bc6b770085e#egg=PySMT
-e git+git@github.com:angr/pysoot@d08dc569ec35796ccea5509b3e04b74967bcfd48#egg=pysoot
python-utils==2.5.6
pytoml==0.1.21
pyusb==1.1.1
-e git+git@github.com:angr/pyvex@38af62047b8a7785feeee6b5f243ad1dbd7db1f6#egg=pyvex
requests==2.22.0
retrying==1.3.3
rpyc==5.0.1
shellphish-qemu==0.11.0
six==1.15.0
smmap==3.0.5
sortedcontainers==2.3.0
SQLAlchemy==1.3.23
toml==0.10.2
traitlets==5.0.5
unicorn==1.0.2rc4
urllib3==1.25.8
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.58.0
wrapt==1.12.1
z3-solver==4.8.10.0
```

**Comment by JeffersonDing** [comment]
still cannot get it to work but I will post updates if I get any onto this thread. Here's the Java version I am using and I have tried multiple versions actually, including `JDK15` and `JDK8`
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.10+9-post-Debian-1, mixed mode, sharing)
```
