### ISSUE TITLE
Unable to load ARMHF libc6

### ISSUE THREAD

**Issue by telltail** [angr/angr#2563]
--

**Describe the bug.**

Hello, I am completely new user to angr, but am already impressed so far - thanks for all the hard work!

I'm trying to load the libc.so.6 file pulled from my Raspberry Pi 4 device, but immediately get an error during `configure_project` when attempting to write the `self._loader_lock_addr` value to memory

**Environment Information.**

I'm running my venv on Ubuntu 20.04.2 LTS with the following output from `pip freeze`
```
ailment==9.0.6421
angr==9.0.6421
archinfo==9.0.6421
bitstring==3.1.7
cachetools==4.2.1
capstone==4.0.2
cffi==1.14.5
claripy==9.0.6421
cle==9.0.6421
CppHeaderParser==2.7.4
decorator==4.4.2
dpkt==1.9.5
future==0.18.2
gitdb==4.0.5
GitPython==3.1.14
itanium-demangler==1.0
mulpyplexer==0.9
networkx==2.5
pefile==2019.4.18
plumbum==1.7.0
ply==3.11
progressbar2==3.53.1
protobuf==3.15.6
psutil==5.8.0
pycparser==2.20
pyelftools==0.27
PySMT==0.9.0
python-utils==2.5.6
pyvex==9.0.6421
rpyc==5.0.1
six==1.15.0
smmap==3.0.5
sortedcontainers==2.3.0
unicorn==1.0.2rc4
z3-solver==4.8.10.0
```

**To Reproduce.**

```python
import angr
import logging
logging.getLogger('angr').setLevel('DEBUG')

angr.Project('/path/to/project/rpi_armhf_libc.so.6')
```

Results in the following traceback:
```
INFO    | 2021-03-13 14:14:23,789 | angr.project | Loading binary /home/user/arm_bins/rpi4_armhf_libc.so.6
WARNING | 2021-03-13 14:14:24,225 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __libc_enable_secure
WARNING | 2021-03-13 14:14:24,225 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __pointer_chk_guard
WARNING | 2021-03-13 14:14:24,226 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __stack_chk_guard
WARNING | 2021-03-13 14:14:24,226 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: _dl_argv
WARNING | 2021-03-13 14:14:24,226 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
WARNING | 2021-03-13 14:14:24,236 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
INFO    | 2021-03-13 14:14:24,237 | angr.project | There are no simprocedures for missing library ld-linux-armhf.so.3 :(
INFO    | 2021-03-13 14:14:24,237 | angr.project | Using stub SimProcedure for unresolved __tls_get_addr
DEBUG   | 2021-03-13 14:14:24,237 | angr.project | hooking 0x600520 with <SimProcedure __tls_get_addr (stub)>
INFO    | 2021-03-13 14:14:24,237 | angr.project | Using stub SimProcedure for unresolved _dl_exception_create
DEBUG   | 2021-03-13 14:14:24,237 | angr.project | hooking 0x600524 with <SimProcedure _dl_exception_create (stub)>
INFO    | 2021-03-13 14:14:24,237 | angr.project | Using stub SimProcedure for unresolved __tunable_get_val
DEBUG   | 2021-03-13 14:14:24,237 | angr.project | hooking 0x600528 with <SimProcedure __tunable_get_val (stub)>
INFO    | 2021-03-13 14:14:24,237 | angr.project | Using stub SimProcedure for unresolved _dl_find_dso_for_object
DEBUG   | 2021-03-13 14:14:24,237 | angr.project | hooking 0x60052c with <SimProcedure _dl_find_dso_for_object (stub)>
INFO    | 2021-03-13 14:14:24,237 | angr.project | There are no simprocedures for missing library ld-linux-armhf.so.3 :(
DEBUG   | 2021-03-13 14:14:24,238 | angr.project | hooking 0xd01000 with <SimProcedure LinuxLoader>
DEBUG   | 2021-03-13 14:14:24,238 | angr.project | hooking 0xd01008 with <SimProcedure _dl_rtld_lock_recursive>
DEBUG   | 2021-03-13 14:14:24,238 | angr.project | hooking 0xd01010 with <SimProcedure _dl_rtld_unlock_recursive>
DEBUG   | 2021-03-13 14:14:24,238 | angr.project | hooking 0xd01018 with <SimProcedure ReturnUnconstrained>
DEBUG   | 2021-03-13 14:14:24,238 | angr.project | hooking 0xd01020 with <SimProcedure _dl_initial_error_catch_tsd>
DEBUG   | 2021-03-13 14:14:24,238 | angr.project | hooking 0xd01028 with <SimProcedure _vsyscall>
DEBUG   | 2021-03-13 14:14:24,239 | angr.project | hooking 0x600520 with <SimProcedure __tls_get_addr>
WARNING | 2021-03-13 14:14:24,239 | angr.project | Address is already hooked, during hook(0x600520, <SimProcedure __tls_get_addr>). Not re-hooking.
Traceback (most recent call last):
  File "/home/user/projects/example/reproduce.py", line 5, in <module>
    angr.Project('/home/user/arm_bins/rpi4_armhf_libc.so.6')
  File "/home/user/projects/example/venv/lib/python3.8/site-packages/angr/project.py", line 224, in __init__
    self.simos.configure_project()
  File "/home/user/projects/example/venv/lib/python3.8/site-packages/angr/simos/linux.py", line 79, in configure_project
    self.project.loader.memory.pack_word(_rtld_global.rebased_addr + 0x7E8, self._loader_lock_addr)
  File "/home/user/projects/example/venv/lib/python3.8/site-packages/cle/memory.py", line 122, in pack_word
    return self.pack(addr, self._arch.struct_fmt(size=size, signed=signed, endness=endness), data)
  File "/home/user/projects/example/venv/lib/python3.8/site-packages/cle/memory.py", line 100, in pack
    raise KeyError(addr) # pylint: disable=raise-missing-from
KeyError: 6293480
```
I believe the relevant ARMHF libc binaries can be directly downloaded [from this link](https://packages.debian.org/buster/armhf/libc-bin/download).

**Additional context.**

I have tried fiddling with various options (ie. `auto_load_libs`, `use_sim_procedures`, etc.), but to no avail.

Thanks in advance for any help or insight you can offer

**Comment by rhelmot** [comment]
Sorry for the delay. I've pushed something which should at least enable you to load these binaries without crashing. The part of the code which was being problematic was trying to set up an interface between libc and angr's pretend-version of the dynamic loader. It would take a lot of reverse engineering to figure out what the exact correct way to make this happen for your case would be, so I've just added a catch-all error handler.
