### ISSUE TITLE
simgr.step() --> symbolizer.py --> TypeError: '<=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by glamorous-noob** [angr/angr#2608]
**Describe the bug.**
As the title describes, impossible to do simgr.step() for a specific file I tested with as the following error is thrown:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\sim_manager.py", line 365, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\sim_manager.py", line 402, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\sim_manager.py", line 441, in successors
    return self._project.factory.successors(state, **run_args)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\factory.py", line 60, in successors
    return self.default_engine.process(*args, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\light\slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\engine.py", line 149, in process
    self.process_successors(self.successors, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\syscall.py", line 18, in process_successors
    return super().process_successors(successors, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\hook.py", line 54, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\unicorn.py", line 169, in process_successors
    return super().process_successors(successors, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\soot\engine.py", line 64, in process_successors
    return super().process_successors(successors, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 138, in process_successors
    self.handle_vex_block(irsb)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\heavy\super_fastpath.py", line 19, in handle_vex_block
    super().handle_vex_block(irsb)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\light\slicing.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\heavy\actions.py", line 30, in handle_vex_block
    super().handle_vex_block(irsb)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 45, in handle_vex_block
    super().handle_vex_block(irsb)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\light\light.py", line 446, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\light\slicing.py", line 30, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 40, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\light\resilience.py", line 36, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 204, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\light\light.py", line 51, in _handle_vex_stmt
    handler(stmt)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\light\light.py", line 196, in _handle_vex_stmt_Store
    self._perform_vex_stmt_Store(
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\heavy\actions.py", line 177, in _perform_vex_stmt_Store
    super()._perform_vex_stmt_Store(addr, data, end, action=a, condition=condition, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\claripy\datalayer.py", line 93, in _perform_vex_stmt_Store
    super()._perform_vex_stmt_Store(addr, data.raw_to_bv(), endness, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 35, in _perform_vex_stmt_Store
    self.state.memory.store(addr, data, endness=endness, action=action, inspect=inspect, condition=condition)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\storage\memory_mixins\unwrapper_mixin.py", line 8, in store
    return super().store(_raw_ast(addr), _raw_ast(data),
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\storage\memory_mixins\name_resolution_mixin.py", line 50, in store
    return super().store(addr, data, size=size, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\storage\memory_mixins\bvv_conversion_mixin.py", line 25, in store
    super().store(addr, data_bv, size=size, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\storage\memory_mixins\simplification_mixin.py", line 11, in store
    super().store(addr, real_data, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\storage\memory_mixins\clouseau_mixin.py", line 28, in store
    self.state._inspect('mem_write', BP_BEFORE,
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\sim_state.py", line 380, in _inspect
    self.inspect.action(*args, **kwargs)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\state_plugins\inspect.py", line 285, in action
    bp.fire(self.state)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\state_plugins\inspect.py", line 226, in fire
    self.action(state)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\state_plugins\symbolizer.py", line 12, in _mem_write_cb
    def _mem_write_cb(s): s.symbolizer._mem_write_callback()
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\state_plugins\symbolizer.py", line 61, in _mem_write_callback
    replacement_expr = self._resymbolize_data(byte_expr)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\state_plugins\symbolizer.py", line 184, in _resymbolize_data
    s = self._resymbolize_int(be, le, base, i*ws, skip)
  File "C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\state_plugins\symbolizer.py", line 159, in _resymbolize_int
    elif self._min_addr <= be < self._max_addr and self._should_symbolize(be):
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

**Environment Information.**
Running on Windows 10.
```
angr environment report
=============================
Date: 2021-04-16 20:18:57.818717
!!! runninng in global environment.  Are you sure? !!!
Platform: win-amd64
Python version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
######## angr #########
Python found it in C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr
Pip version angr 9.0.6790
Couldn't find git info
######## ailment #########
Python found it in C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\ailment
Pip version ailment 9.0.6790
Couldn't find git info
######## cle #########
Python found it in C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\cle
Pip version cle 9.0.6790
Couldn't find git info
######## pyvex #########
Python found it in C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\pyvex
Pip version pyvex 9.0.6790
Couldn't find git info
######## claripy #########
Python found it in C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\claripy
Pip version claripy 9.0.6790
Couldn't find git info
######## archinfo #########
Python found it in C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\archinfo
Pip version archinfo 9.0.6790
Couldn't find git info
######## z3 #########
Python found it in C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\z3
Pip version z3-solver 4.8.10.0
Couldn't find git info
######## unicorn #########
Python found it in C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL 'C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\angr\lib\angr_native.dll', handle 7ffdfc120000 at 0x1bf7e6fe130>
unicorn: <CDLL 'C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\lib\site-packages\unicorn\lib\unicorn.dll', handle 7ffddc470000 at 0x1bf7c5cecd0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x000001BF7C367970>
z3: <CDLL 'C:\Users\glamorous_noob\AppData\Local\Programs\Python\Python38\Lib\site-packages\z3\lib\libz3.dll', handle 7ffdcacf0000 at 0x1bf7d4e5880>
```

**To Reproduce.**
- Extract the attached file
[labyrevnt.tar.gz](https://github.com/angr/angr/files/6327263/labyrevnt.tar.gz)
- Load it using proj = angr.Project(<filename>)
- state = proj.factory.entry_state()
- simgr = proj.factory.simulation_manager(state)
- simgr.step()
- boom TypeError because self._min_addr in symbolizer.py is NoneType for some reason

**Additional context.**
If this is a real issue and not an environment-related issue, I would be willing to help if possible (but since I never coded in this repo I would be extremely slow)

**Comment by rhelmot** [comment]
![image](https://user-images.githubusercontent.com/2498805/116618718-45b66500-a8f4-11eb-824e-160a8e11a614.png)
Can you provide more context on how to reproduce the issue?

**Comment by glamorous-noob** [comment]
Alright, this is weird...
I tried to reproduce the error myself just now, and it didn't work.
I installed/updated a lot of stuff on my PC since then, including python libs and mingw-64 libs.
I think since I can't reproduce myself anymore, might as well close the issue.

Thanks a lot and sorry it turned out to be a waste of time
