### ISSUE TITLE
Concolic execution

### ISSUE THREAD

**Issue by stevenagy** [angr/angr#2786]
Hey all,

I'm trying to use angr for some concolic execution. From looking at some GitHub issues on here + the Driller source, my intuition is that to do this I must (1) get a basic block address trace, (2) feed this to an angr `Tracer` exploration technique and then (3) run the simulation manager. My current script resembles something like this:

```python
import angr

# Set up angr project; omit shared libraries to avoid state explosion.
proj = angr.Project('./bin', load_options={'auto_load_libs':False})

# Set up control-flow graph for symbol recovery.
cfg  = proj.analyses.CFG(fail_fast=True)

# Set up tracing exploration technique based on traced bb addrs (currently from objdump)
addrs = [0x401030, 0x40115f]
trace = angr.exploration_techniques.Tracer(trace=addrs, copy_states=True)

# Set up the starting simulation state.
start_state = proj.factory.entry_state(
                  mode        = 'tracing',
                  addr        = 0x401030,
                  args        = ['./bin', 'A'*50],
              )

# Set up simulation manager and run.
simgr = proj.factory.simulation_manager(start_state)
simgr.use_technique(trace)
simgr.run()
```

However, upon running this I'm getting errors like `ValueError: 4198464 is not in list`. Could anyone please point me to what I'm missing in my approach? 

Best,
-Steve

**Comment by rhelmot** [comment]
The default tracer configuration is designed to take a trace that includes the jump to the program's entry point. You can disable this behavior by setting `fast_forward_to_entry=False` in the Tracer constructor.

**Comment by stevenagy** [comment]
Thanks for the quick reply! I've since set that flag as suggested but am now getting the following error:
```
 You are attempting to use unicorn engine support even though it or the angr native layer isn't installed
```
I thought building from source would have installed the unicorn component?

**Comment by rhelmot** [comment]
post your `python -m angr.misc.bug_report`

**Comment by stevenagy** [comment]
```
$ python3 -m angr.misc.bug_report
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:635: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:637: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:639: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:635: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:637: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:639: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/angr/misc/bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2021-06-29 21:25:48.788566
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0]
######## angr #########
Python found it in /usr/local/lib/python3.8/dist-packages/angr
Pip version angr 9.0.gitrolling
Couldn't find git info
######## ailment #########
Python could not find ailment
######## cle #########
Python found it in /usr/local/lib/python3.8/dist-packages/cle-9.0.gitrolling-py3.8.egg/cle
Pip version cle 9.0.gitrolling
Couldn't find git info
######## pyvex #########
Python could not find pyvex
######## claripy #########
Python could not find claripy
######## archinfo #########
Python could not find archinfo
######## z3 #########
Python found it in /usr/local/lib/python3.8/dist-packages/z3_solver-4.8.10.0-py3.8-linux-x86_64.egg/z3
Pip version z3-solver 4.8.10.0
Couldn't find git info
######## unicorn #########
Python found it in /mnt/bigdata/angr/.eggs/unicorn-1.0.2rc4-py3.8-linux-x86_64.egg/unicorn
Pip version unicorn 1.0.2rc4
Git info:
	Current commit 952aa48d406839520028ce7347a7dc69e6dacf89 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######### Native Module Info ##########
angr: <CDLL '/usr/local/lib/python3.8/dist-packages/angr/lib/angr_native.so', handle 1ed5690 at 0x7ffff67423a0>
unicorn: <CDLL '/mnt/bigdata/angr/.eggs/unicorn-1.0.2rc4-py3.8-linux-x86_64.egg/unicorn/lib/libunicorn.so', handle efc5e0 at 0x7ffff5bf9ca0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7ffff6680250>
z3: <CDLL '/usr/local/lib/python3.8/dist-packages/z3_solver-4.8.10.0-py3.8-linux-x86_64.egg/z3/lib/libz3.so', handle 11552d0 at 0x7ffff5624460>
```

**Comment by stevenagy** [comment]
After re-installing (with `pip install .` -- was previously just doing `pythons setup.py install`) the packages not found in the log above, re-running that command returns the following:
```
$ python3 -m angr.misc.bug_report
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:635: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:637: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:639: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:635: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:637: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:639: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/angr/misc/bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2021-06-30 09:27:18.281634
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0]
######## angr #########
Python found it in /usr/local/lib/python3.8/dist-packages/angr
Pip version angr 9.0.gitrolling
Couldn't find git info
######## ailment #########
Python found it in /usr/local/lib/python3.8/dist-packages/ailment
Pip version ailment 9.0.gitrolling
Couldn't find git info
######## cle #########
Python found it in /usr/local/lib/python3.8/dist-packages/cle-9.0.gitrolling-py3.8.egg/cle
Pip version cle 9.0.gitrolling
Couldn't find git info
######## pyvex #########
Python found it in /usr/local/lib/python3.8/dist-packages/pyvex
Pip version pyvex 9.0.gitrolling
Couldn't find git info
######## claripy #########
Python found it in /usr/local/lib/python3.8/dist-packages/claripy
Pip version claripy 9.0.gitrolling
Couldn't find git info
######## archinfo #########
Python found it in /usr/local/lib/python3.8/dist-packages/archinfo
Pip version archinfo 9.0.gitrolling
Couldn't find git info
######## z3 #########
Python found it in /usr/local/lib/python3.8/dist-packages/z3_solver-4.8.10.0-py3.8-linux-x86_64.egg/z3
Pip version z3-solver 4.8.10.0
Couldn't find git info
######## unicorn #########
Python found it in /mnt/bigdata/angr/.eggs/unicorn-1.0.2rc4-py3.8-linux-x86_64.egg/unicorn
Pip version unicorn 1.0.2rc4
Git info:
	Current commit 952aa48d406839520028ce7347a7dc69e6dacf89 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######### Native Module Info ##########
angr: <CDLL '/usr/local/lib/python3.8/dist-packages/angr/lib/angr_native.so', handle 1c55f90 at 0x7fffcdad9bb0>
unicorn: <CDLL '/mnt/bigdata/angr/.eggs/unicorn-1.0.2rc4-py3.8-linux-x86_64.egg/unicorn/lib/libunicorn.so', handle e8a900 at 0x7ffff5474a60>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7ffff6690220>
z3: <CDLL '/usr/local/lib/python3.8/dist-packages/z3_solver-4.8.10.0-py3.8-linux-x86_64.egg/z3/lib/libz3.so', handle 1087e00 at 0x7ffff3804e80>
```

So it seems everything is installed fine. Now running my script (slightly expanded from the original one in my post) errors-out with the following:
```
$ python3 test.py
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:635: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:637: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:639: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:635: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:637: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.8/dist-packages/itanium_demangler-1.0-py3.8.egg/itanium_demangler/__init__.py:639: SyntaxWarning: "is not" with a literal. Did you mean "!="?
Traceback (most recent call last):
  File "test.py", line 65, in <module>
    main()
  File "test.py", line 59, in main
    simgr.run()
  File "/usr/local/lib/python3.8/dist-packages/angr/sim_manager.py", line 280, in run
    self.step(stash=stash, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/angr/exploration_techniques/tracer.py", line 311, in step
    return simgr.step(stash=stash, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/angr/misc/hookset.py", line 80, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/angr/sim_manager.py", line 365, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/usr/local/lib/python3.8/dist-packages/angr/misc/hookset.py", line 75, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/angr/exploration_techniques/tracer.py", line 350, in step_state
    self._update_state_tracking(sat_succs[0])
  File "/usr/local/lib/python3.8/dist-packages/angr/exploration_techniques/tracer.py", line 496, in _update_state_tracking
    raise TracerDesyncError('Oops! angr did not follow the trace',
angr.exploration_techniques.tracer.TracerDesyncError: Oops! angr did not follow the trace
```

**Comment by stevenagy** [comment]
My understanding (from https://github.com/angr/angr/issues/1609) is that this could be due to inconsistencies in the trace addresses versus what `simgr` sees. Yet I verified that the address of `main` from my trace matches that in angr's CFG. Any ideas?

**Comment by rhelmot** [comment]
The universal debugging technique for this error is to get a debug shell at the crash site (`ipython --pdb` is your friend) and compare the trace (`self._trace`) with the actual history of what the state did (`state.history.bbl_addrs.hardcopy` + `state.addr`). Something is happening to make the emulator go off on a different branch from what the trace says to do, and you have to reverse engineer the root cause of why that is.

**Comment by stevenagy** [comment]
If I understand correctly, the trace I'm passing in isn't matching the trace that the simgr emulator is itself seeing? This is probably expected as my "trace" was just a few bb addresses thrown together by hand.
 
What is the preferred way to generate a trace? I couldn't find much documentation angr's tracer -- presumably it uses QEMU while angr itself relies on Unicorn?

**Comment by rhelmot** [comment]
The preferred way to generate a trace is with the [archr](https://github.com/angr/archr) package, which attempts to closely replicate the environment between a QEMU tracer and the angr environment.

See [here](https://github.com/angr/angr/pull/2441) for a sample usage script and also a brief writeup on the current state of trying to trace linux binaries. It is, unfortunately, a little bleak. Some work has been put in since then to trace starting from a core dump, which should alleviate some of the issues, but I don't actually know how that works?

**Comment by stevenagy** [comment]
Cool! I put this together based on the code in your post:
```
    archr_target = archr.targets.LocalTarget("./"+bin_path, target_env=['PWD=' + os.getcwd(), 'LD_BIND_NOW=1'])
    archr_tracer_bow = archr.arsenal.QEMUTracerAnalyzer(archr_target)
    with archr_tracer_bow.fire_context() as flight:
        ch = flight.default_channel
        ch.write(b'')
        print(ch.read().decode())
    archr_trace_result = flight.result
    archr_technique    = archr_trace_result.tracer_technique(fast_foward_to_entry=False)
  ```
But this returns the following:
```
WARNING | 2021-07-01 09:42:19,732 | archr.target.flight | No actions specified, make sure this is what you want!
usage: qemu-x86_64 [options] program [arguments...]
Linux CPU emulator (compiled for x86_64 emulation)

Options and associated environment variables:

Argument      Env-variable      Description
-h                              print this help
-g port       QEMU_GDB          wait gdb connection to 'port'
-L path       QEMU_LD_PREFIX    set the elf interpreter prefix to 'path'
-s size       QEMU_STACK_SIZE   set the stack size to 'size' bytes
-cpu model    QEMU_CPU          select CPU (-cpu help for list)
-E var=value  QEMU_SET_ENV      sets targets environment variable (see below)
-U var        QEMU_UNSET_ENV    unsets targets environment variable (see below)
-0 argv0      QEMU_ARGV0        forces target process argv[0] to be 'argv0'
-r uname      QEMU_UNAME        set qemu uname release string to 'uname'
-B address    QEMU_GUEST_BASE   set guest_base address to 'address'
-R size       QEMU_RESERVED_VA  reserve 'size' bytes for guest virtual address space
-d item[,...] QEMU_LOG          enable logging of specified items (use '-d help' for a list of items)
-D logfile    QEMU_LOG_FILENAME write logs to 'logfile' (default stderr)
-p pagesize   QEMU_PAGESIZE     set the host page size to 'pagesize'
-singlestep   QEMU_SINGLESTEP   run in singlestep mode
-strace       QEMU_STRACE       log system calls
-seed         QEMU_RAND_SEED    Seed for pseudo-random number generator
-version      QEMU_VERSION      display version information and exit

Defaults:
QEMU_LD_PREFIX  = /usr/gnemul/qemu-x86_64
QEMU_STACK_SIZE = 8388608 byte

You can use -E and -U options or the QEMU_SET_ENV and
QEMU_UNSET_ENV environment variables to set and unset
environment variables for the target process.
It is possible to provide several variables by separating them
by commas in getsubopt(3) style. Additionally it is possible to
provide the -E and -U options multiple times.
The following lines are equivalent:
    -E var1=val2 -E var2=val2 -U LD_PRELOAD -U LD_DEBUG
    -E var1=val2,var2=val2 -U LD_PRELOAD,LD_DEBUG
    QEMU_SET_ENV=var1=val2,var2=val2 QEMU_UNSET_ENV=LD_PRELOAD,LD_DEBUG
Note that if you provide several changes to a single variable
the last change will stay in effect.

Traceback (most recent call last):
  File "test.py", line 70, in <module>
    main()
  File "test.py", line 39, in main
    print(ch.read().decode())
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/archr-9.0.gitrolling-py3.8.egg/archr/analyzers/qemu_tracer.py", line 156, in fire_context
    trace = self.target.retrieve_contents(target_trace_filename)
  File "/usr/local/lib/python3.8/dist-packages/archr-9.0.gitrolling-py3.8.egg/archr/targets/__init__.py", line 303, in retrieve_contents
    f.write(self.retrieve_tarball(target_path, dereference=True))
  File "/usr/local/lib/python3.8/dist-packages/archr-9.0.gitrolling-py3.8.egg/archr/targets/local_target.py", line 69, in retrieve_tarball
    t.add(target_path, arcname=os.path.basename(target_path.rstrip('/'))) # stupid docker compatibility --- it just uses the basename
  File "/usr/lib/python3.8/tarfile.py", line 1955, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python3.8/tarfile.py", line 1836, in gettarinfo
    statres = os.stat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tracer-7up5eqpm.trace'
```
It seems like QEMU is just printing its "help" screen here and thus isn't successfully running the target binary?

**Comment by stevenagy** [comment]
So I'm now attempting to run `angr.exploration_techniques.Tracer` on a block addr trace. As I'm having issues with archr I'm so far just tracing with PIN and filtering-out addrs outside the binary's `.TEXT` section.

My trace addrs list begins at `__libc_csu_init`. Running angr on this resulted in a `ValueError: 4198496 is not in list`; but as this is `__start`'s address (`0x401060`) I prepended this to my trace and re-ran, which showed the following:

```
ERROR   | 2021-07-13 22:21:26,765 | angr.exploration_techniques.tracer | Trying to synchronize at 0x40108e (0x40108e) but it does not appear in the trace?
```

So now adding-in _this_ address `0x40108e` to the trace (which doesn't make sense to me as it corresponds to a `hlt` insn in `_start`) causes angr to show the following:
```
  File "/usr/local/lib/python3.8/dist-packages/angr/exploration_techniques/tracer.py", line 478, in _update_state_tracking
    raise Exception("TODO")
Exception: TODO
```

For reference, this is my script:
```python
def read_trace_from_file(trace_path):
    trace_list = []
    with open(trace_path, "r") as trace_file:
        for line in trace_file.readlines():
            addr = int(line.strip(),16)
            trace_list.append(addr)
    return trace_list

def main():
    trace_addrs = read_trace_from_file("pin_trace.txt")
    angr_project = angr.Project('./sbof', load_options={'auto_load_libs':True}) 

    angr_trace = angr.exploration_techniques.Tracer( \
            trace=trace_addrs, \
            mode='strict', \
            resiliency=False, \
            copy_states=False, \
            fast_forward_to_entry=True, \
            aslr = False)

    start_state = angr_project.factory.entry_state(
                      mode        = 'tracing',
                      addr        = trace_addrs[0], 
                      args        = ['./sbof'],
                  )

    simgr = angr_project.factory.simulation_manager(start_state)
    simgr.use_technique(angr_trace)
    simgr.run()
    return

if (__name__ == "__main__"):
    main()
```

Any ideas where to go from here? I've attached the test binary ([sbof.zip](https://github.com/angr/angr/files/6813124/sbof.zip)) and sample trace ([pin_trace.txt](https://github.com/angr/angr/files/6813125/pin_trace.txt)) for reference. All help is appreciated.

**Comment by stevenagy** [comment]
So I managed to get the QEMU-based tracing working with archr. :) 

Now I'm a little unsure of how to work this into angr. From looking at the example you linked earlier, this is what I have so far:
```python
    logging.getLogger("archr.analyzers.qemu_tracer").setLevel("DEBUG")
    
    target = archr.targets.LocalTarget(["./sbof",'A'*120], target_env=[('PWD=%s'%os.getcwd()), 'LD_BIND_NOW=1'])
    tracer = archr.arsenal.QEMUTracerAnalyzer(target)

    with tracer.fire_context() as flight:
        ch = flight.default_channel
        ch.write('')
        print(ch.read().decode())
    
    technique = flight.result.tracer_technique(fast_forward_to_entry=False)

    scout_analyzer = archr.arsenal.DataScoutAnalyzer(target)
    angr_analyzer  = archr.arsenal.angrProjectAnalyzer(target, scout_analyzer)
    state_analyzer = archr.arsenal.angrStateAnalyzer(target, angr_analyzer).fire(add_options={angr.options.STRICT_PAGE_ACCESS, angr.options.CPUID_SYMBOLIC})
    
    angr_project = angr_analyzer.project
    start_state = state_analyzer

    simgr = angr_project.factory.simulation_manager(start_state)
    simgr.use_technique(technique)
    simgr.run()

    return
```
However it's returning the following error:
```
DEBUG   | 2021-07-14 16:59:55,780 | archr.analyzers.qemu_tracer | launch QEMU with command: /tmp/archr_local_b9kyzpyi/shellphish_qemu/fire /tmp/archr_local_b9kyzpyi/shellphish_qemu/shellphish-qemu-linux-x86_64 -C /tmp/tracer_target_srzuo063 -d nochain,exec,page -D /tmp/tracer-mh840_e5.trace -E LD_BIND_NOW=1 -- ./sbof AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
WARNING | 2021-07-14 16:59:55,785 | archr.target.flight | No actions specified, make sure this is what you want!

DEBUG   | 2021-07-14 16:59:55,840 | archr.analyzers.qemu_tracer | Detected the base address of the target at 0x401000
DEBUG   | 2021-07-14 16:59:55,868 | archr.analyzers.qemu_tracer | Detected the tainted fd to be 4
DEBUG   | 2021-07-14 16:59:55,868 | archr.analyzers.qemu_tracer | Detected the crashing address at 0x4141414141414141
DEBUG   | 2021-07-14 16:59:55,868 | archr.analyzers.qemu_tracer | Trace consists of 19346 basic blocks
Traceback (most recent call last):
  File "/home/snagy2/.local/lib/python3.8/site-packages/angr/exploration_techniques/tracer.py", line 851, in _fast_forward
    target_idx = self._trace.index(target_addr, state.globals['trace_idx'] + 1)
ValueError: 140737351843632 is not in list

The above exception was the direct cause of the following exception:
```

Some other questions I have are:
* If I'm trying to do concolic execution on the trace, what starting state should I be going for? I'm currently using archr's `angrStateAnalyzer` (like in https://github.com/angr/angr/pull/2441) but I'm unsure if this is the better option over angr's `factory.entry_state`. 
* Is `scout_analyzer` necessary for this? I noticed it's a required parameter for `angr_analyzer`, but I'm unsure if I should instead be initializing my own angr `project`.

**Comment by ltfish** [comment]
@stevenagy I'm happy to see that you have gone so far!

Symbolic tracing is a real pain point of angr (at least for now). While our approach worked quite well for CGC binaries, doing symbolic tracing on a full basic block trace for real-world binaries and hoping that the symbolic trace completely follows the concrete trace is extremely difficult, if possible at all. We are looking at integrating solutions that slices a concrete execution at runtime, so only instructions that touch symbolic input will be present in the trace. Some such solutions include QSym and libdft64 (from Angora fuzzer).

I feel you are better off switching to an alternative solution, such as QSym, Triton, etc. However, if you really want to try angr's full symbolic tracing on Linux binaries, here are a couple of suggestions:

- Don't try to trace through the Linux loader (ld.so) or __libc_start_main. While sometimes you may succeed, it's very likely that you'll see a divergence. You should enable SimProcedures for them (yes, angr tracer does sync concrete and symbolic traces across SimProcedures).
- Enable the permissive mode in angr tracer. It will try to re-sync the trace once a desync happens. Sometimes that helps.
- Take a look at archr and rex test cases (such as [this one](https://github.com/angr/archr/blob/master/tests/test_angr_tracing.py) and [this one](https://github.com/angr/rex/blob/master/tests/test_rex.py)). [Rex](https://github.com/angr/rex/blob/master/rex/crash.py) heavily uses angr tracer. Although its code quality is not what I'm proud of, it's the best example you can find about how to use angr tracer.

If you want more help or suggestions on your specific use case, I'm down to having a Zoom meeting soon! You may reach me at fishw <at> asu.edu.

**Comment by stevenagy** [comment]
@ltfish thanks for reaching out and explaining angr's current limitations. I will explore the other options you suggested, but will also keep angr in mind going forward -- the exec-slicing is intriguing. :)

Regarding your suggestions:
- What is the best way to omit tracing the Linux loader / libc_start_main? I could not find an example.
- Is permissive mode specific to `angr.exploration_techniques.tracer.TracingMode`? My current script is similar to that rex one you linked to (i.e., tracing is all archr-based), but I could not find an example of permissive mode in-use in the archr repo.

If a Zoom meeting is more preferable I'd be happy to set one up!

**Comment by calebh** [comment]
@ltfish Has the situation with regards to tracing/symbolic execution improved at all since your 2021 post? I see now that the QSym repo has been archived and is presumably no longer under active development.

One alternative implementation strategy I thought of is to abandon the emulation altogether (in QEMU or Unicorn) and instead use a concolic pruning strategy. Fix some concrete input `I`. Then run typical symbolic execution. At some branch point with children `L` and `R`, check if `I` satisfies `L.constraints` and `R.constraints`, and prune away the one that isn't satisfied.
