### ISSUE TITLE
KeyError 'eax' when working with ARM binary during CFGAccurate with backward slicing

### ISSUE THREAD

**Issue by ngboggs** [angr/angr#291]
I am seeing this error when I run a CFGAccurate on an arm binary with enable_advanced_backward_slicing=True. It looks like angr is looking for eax despite it being an ARM binary. I don't see this error when backward slicing is disabled.

p.arch correctly returns that it is an ARM binary.
```
p.arch
<Arch ARMEL (LE)>
```

I've included my code and environment below to aid in troubleshooting. 
Here are the full logs of stderr and the referenced json:
[full_logs_and_json.zip](https://github.com/angr/angr/files/650339/full_logs_and_json.zip)

Thanks!

## Error message

```
<...>
# This first exception is handled. I'm not sure if it's contirbuting to the issue or not
DEBUG   | 2016-12-13 21:03:30,055 | ^[[36mangr.analyses.cfg_accurate^[[0m | ^[[36mCaught a SimIRSBError during CFG recovery. Creating a PathTerminator.^[[0m
Traceback (most recent call last):
  File "/angr-dev/angr/angr/analyses/cfg_accurate.py", line 2531, in _get_simrun
    opt_level=self._iropt_level
  File "/angr-dev/angr/angr/factory.py", line 183, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/angr-dev/angr/angr/factory.py", line 105, in sim_block
    force_bbl_addr=force_bbl_addr)
  File "/angr-dev/simuvex/simuvex/vex/irsb.py", line 41, in __init__
    raise SimIRSBError("Empty IRSB passed to SimIRSB.")
SimIRSBError: Empty IRSB passed to SimIRSB.

< ... >

DEBUG   | 2016-12-13 21:06:23,175 | angr.analyses.ddg | Adding 1 new defitions for variable <Reg 80 4>.
DEBUG   | 2016-12-13 21:06:23,175 | angr.analyses.ddg | Adding 1 new defitions for variable <Reg 8 4>.
DEBUG   | 2016-12-13 21:06:23,175 | angr.analyses.ddg | Adding 1 new defitions for variable <Reg 24 4>.
DEBUG   | 2016-12-13 21:06:23,175 | angr.analyses.ddg | Adding 1 new defitions for variable <Stack sp-0x14, 4 bytes>.

# This one crashes angr
Traceback (most recent call last):
  File "cfg_accurate_backslice.py", line 10, in <module>
    cfg = p.analyses.CFGAccurate(starts=ida_funcs, enable_advanced_backward_slicing=True, keep_state=True)
  File "/angr-dev/angr/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/angr-dev/angr/angr/analyses/cfg_accurate.py", line 250, in __init__
    self._analyze()
  File "/angr-dev/angr/angr/analyses/forward_analysis.py", line 239, in _analyze
    self._handle_entry(entry_info)
  File "/angr-dev/angr/angr/analyses/forward_analysis.py", line 258, in _handle_entry
    successors = self._get_successors(entry)
  File "/angr-dev/angr/angr/analyses/cfg_accurate.py", line 1251, in _get_successors
    self._simrun_info_collection
  File "/angr-dev/angr/angr/analyses/cfg_accurate.py", line 2021, in _resolve_indirect_jumps
    more_successors = self._resolve_indirect_jump(cfg_node, simrun, func_addr)
  File "/angr-dev/angr/angr/analyses/cfg_accurate.py", line 2142, in _resolve_indirect_jump
    ddg = self.project.analyses.DDG(cfg=self, start=current_function_addr, call_depth=0)
  File "/angr-dev/angr/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/angr-dev/angr/angr/analyses/ddg.py", line 307, in __init__
    self._construct()
  File "/angr-dev/angr/angr/analyses/ddg.py", line 540, in _construct
    if variable.reg in (self.project.arch.registers['eax'][0],
KeyError: 'eax'
```

## Python code to reproduce the issue
```import angr
import json
import logging
from networkx.drawing.nx_agraph import write_dot
logging.getLogger('angr').setLevel(logging.DEBUG)
logging.getLogger('claripy').setLevel(logging.DEBUG)
logging.getLogger('simuvex').setLevel(logging.DEBUG)
p = angr.Project('/share/busybox', load_options={'auto_load_libs': False})
ida_funcs = json.load(open('/share/busybox_raspbian_archive_funcs.json', 'r'))
cfg = p.analyses.CFGAccurate(starts=ida_funcs, enable_advanced_backward_slicing=True, keep_state=True)
```

## Here is the busybox binary I am able to reproduce the error on:
```
http://snapshot.raspbian.org/201504210430/raspbian/pool/main/b/busybox/busybox-static_1.20.0-7_armhf.deb
mkdir -p /share/busybox
dpkg-deb -R busybox-static_1.20.0-7_armhf.deb /share/busybox
#The binary is then at /share/busybox/bin/busybox
```

## Here's the dockerfile I used for the test environment. It's just a base ubuntu 14 with the dependencies.
```
FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive
ENV PIP_NO_INPUT 1

#Clean stuff
RUN apt-get -y autoremove && apt-get -y clean && apt-get -y autoclean && rm -rf /var/cache/apt/archives/lists


#System Dependencies for building packages, etc
RUN apt-get -y update && apt-get install -y \
  git \
  build-essential \
  libxml2-dev \
  libxslt-dev \
  python-lxml \
  libxslt-dev \
  libhdf5-dev \
  libpq-dev \
  libssl-dev \
  libffi-dev \
  xterm \
  wget \
  python-dev \
  vim
RUN apt-get -y update && apt-get install -y python-dev libffi-dev build-essential virtualenvwrapper python2.7-dev libxml2-dev libxslt1-dev git cmake libreadline-dev libtool debootstrap debian-archive-keyring libglib2.0-dev libpixman-1-dev libqt4-dev graphviz-dev
#Install pip for python 2.7
RUN wget https://bootstrap.pypa.io/get-pip.py -P /tmp
RUN /usr/bin/python2.7 /tmp/get-pip.py
RUN pip install --upgrade pip

RUN pip install \
  ipython \
  futures \
  requests-futures \
  ipdb \
  virtualenvwrapper


```

## Here is my angr install steps after starting the docker.
```
chmod 777 /usr/share/virtualenvwrapper/virtualenvwrapper.sh
git clone https://github.com/angr/angr-dev
cd angr-dev
/usr/share/virtualenvwrapper/virtualenvwrapper.sh angr
./setup.sh

#Download busybox arm binary if not shared to docker instance
wget http://snapshot.raspbian.org/201504210430/raspbian/pool/main/b/busybox/busybox-static_1.20.0-7_armhf.deb
mkdir -p /share/busybox
dpkg-deb -R busybox-static_1.20.0-7_armhf.deb /share/busybox
```

**Comment by frapik99** [comment]
Hi @ngboggs,my 2 cents.. The DDG is under development so I think they are gonna fix it soon. In the mean time you could substitute ```eax``` with ```rax``` no?

**Comment by ngboggs** [comment]
A rough hack switching out the register names seems to prevent the exception. I'll keep an eye open for the new release!

**Comment by XingweiLin** [comment]
Hi,all
I get the newest release of angr,but this error is still exist.
And can you guys fix this bug?
Or can you guys guide me how to fix this error?

**Comment by ltfish** [comment]
This is an issue with data dependency analysis and it will be fixed in the new version of DDG. However, this is not a high-priority issue.

**Comment by XingweiLin** [comment]
DFG can be obtained in arm architecture.
And what's the difference between DDG and DFG in angr?

**Comment by ltfish** [comment]
DDG gives you a data dependence graph. No idea what DFG does.
