### ISSUE TITLE
MIPS stack unexpected SegFault

### ISSUE THREAD

**Issue by r4dr3fr4d** [angr/angr#2988]
```
proj = angr.Project("httpd", ld_path=ld_path, auto_load_libs=True, except_missing_libs=True)
s = proj.factory.blank_state(addr=0x408f90, add_options=[angr.options.STRICT_PAGE_ACCESS])
b = s.memory.load(s.regs.sp, 1)
```

Results in:
```
INFO    | 2021-12-07 10:59:26,997 | pyvex.lifting.libvex | Error occured while trying to decode MIPS32 DSP instruction.
Your platform probably doesn't support MIPS32 DSP ASE.

WARNING | 2021-12-07 10:59:27,944 | cle.backends.externs | Symbol type mismatch between export request and response for stderr. What's going on?
WARNING | 2021-12-07 10:59:27,959 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __ctype_tolower
WARNING | 2021-12-07 10:59:27,978 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __ctype_toupper
WARNING | 2021-12-07 10:59:27,983 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: __ctype_b
WARNING | 2021-12-07 10:59:28,294 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
Traceback (most recent call last):
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/paged_memory/page_backer_mixins.py", line 58, in _initialize_page
    backer_start, backer = next(backer_iter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test_mips.py", line 18, in <module>
    b = s.memory.load(s.regs.sp, 1)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/unwrapper_mixin.py", line 18, in load
    **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/name_resolution_mixin.py", line 57, in load
    return super().load(addr, size=size, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/bvv_conversion_mixin.py", line 29, in load
    return super().load(addr, size=size, fallback=fallback_bv, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/clouseau_mixin.py", line 58, in load
    **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/actions_mixin.py", line 13, in load
    r = super().load(addr, size=size, condition=condition, fallback=fallback, action=action, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/underconstrained_mixin.py", line 23, in load
    return super().load(addr, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/size_resolution_mixin.py", line 80, in load
    return super().load(addr, size=size, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/size_resolution_mixin.py", line 28, in load
    return super().load(addr, size=out_size, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/address_concretization_mixin.py", line 276, in load
    **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/address_concretization_mixin.py", line 260, in _load_one_addr
    sub_value = super().load(concrete_addr, size=size, condition=sub_condition, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/actions_mixin.py", line 66, in load
    return super().load(addr, action=action, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/conditional_store_mixin.py", line 7, in load
    res = super().load(addr, condition=condition, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py", line 129, in load
    page = self._get_page(pageno, False, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/paged_memory/privileged_mixin.py", line 17, in _get_page
    page = super()._get_page(pageno, writing, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py", line 71, in _get_page
    page = self._initialize_page(pageno, force_default=force_default, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/paged_memory/stack_allocation_mixin.py", line 62, in _initialize_page
    return super()._initialize_page(pageno, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/paged_memory/page_backer_mixins.py", line 60, in _initialize_page
    return super()._initialize_page(pageno, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/paged_memory/page_backer_mixins.py", line 184, in _initialize_page
    return super()._initialize_page(pageno, **kwargs)
  File "/home/user/angr_pypy/site-packages/angr/storage/memory_mixins/paged_memory/privileged_mixin.py", line 28, in _initialize_page
    raise SimSegfaultException(pageno * self.page_size, 'unmapped')
angr.errors.SimSegfaultException: 0x7fff0000 (unmapped)
```

I'm not sure if the first traceback is expected for a segfault exception, or if the stack isn't being set up properly?

**Comment by ltfish** [comment]
> s = proj.factory.blank_state(addr=0x408f90, add_options=[angr.options.STRICT_PAGE_ACCESS])

Do you have to enable `STRICT_PAGE_ACCESS`? The emulation or simulated memory management in angr may go haywire on non-x86 and non-x86-64 Linux ELFs (since we never fully tested them on other platforms). You should only enable `STRICT_PAGE_ACCESS` if you want to find memory corruption violations.

**Comment by r4dr3fr4d** [comment]
Perhaps, but not having it enabled results in https://github.com/angr/angr/issues/2989
