### ISSUE TITLE
win10 failed to install angr

### ISSUE THREAD

**Issue by wgf4242** [angr/angr#2990]
Seems like error with pyvex.
```
F:\Fshare\del1\vmware\test\del>pip install angr
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting angr
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/82/da/f9bddecbcc98b5c8ad7d7285e33d49030c6ce6f01f428f213a3d4a9f0130/angr-9.0.10730.tar.gz (2.7 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wgfabc\\AppData\\Local\\Temp\\pip-install-ckqa1j_p\\angr_b18b9b57dab241c69ebf626b20bc2679\\setup.py'"'"'; __file__='"'"'C:\\Users\\wgfabc\\AppData\\Local\\Temp\\pip-install-ckqa1j_p\\angr_b18b9b57dab241c69ebf626b20bc2679\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\wgfabc\AppData\Local\Temp\pip-pip-egg-info-qbz58vjh'
       cwd: C:\Users\wgfabc\AppData\Local\Temp\pip-install-ckqa1j_p\angr_b18b9b57dab241c69ebf626b20bc2679\
  Complete output (125 lines):

  Microsoft (R) 程序维护实用工具 14.00.24245.0 版
  版权所有 (C) Microsoft Corporation。  保留所有权利。

        cl /Ipub /Ipriv  /O2 /wd4715 /DPYVEX auxprogs\genoffsets.c  /Fo:auxprogs\genoffsets.o /Fe:auxprogs\genoffsets.exe
  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.00.24245 版
  版权所有(C) Microsoft Corporation。保留所有权利。

  genoffsets.c
  auxprogs\genoffsets.c(36): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory
  NMAKE : fatal error U1077: “"d:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.EXE"”: 返回代码“0x2”
  Stop.
  process_begin: CreateProcess(NULL, uname -s, ...) failed.
  make: Makefile-gcc:25: pipe: No error
  cc -Ipub -Ipriv -Wall -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wmissing-declarations -Wwrite-strings -Wformat -Wformat-security -std=gnu99 -fstrict-aliasing -fPIC -DPYVEX  -g -o auxprogs/genoffsets auxprogs/genoffsets.c
  process_begin: CreateProcess(NULL, cc -Ipub -Ipriv -Wall -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wmissing-declarations -Wwrite-strings -Wformat -Wformat-security -std=gnu99 -fstrict-aliasing -fPIC -DPYVEX -g -o auxprogs/genoffsets auxprogs/genoffsets.c, ...) failed.
  make (e=2): 系统找不到指定的文件。

  make: *** [Makefile-gcc:74: pub/libvex_guest_offsets.h] Error 2
  Traceback (most recent call last):
    File "d:\python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "d:\python\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "d:\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\wgfabc\AppData\Local\Temp\easy_install-up4wi_bs\pyvex-9.0.10730\setup.py", line 176, in run
      }
    File "d:\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\wgfabc\AppData\Local\Temp\easy_install-up4wi_bs\pyvex-9.0.10730\setup.py", line 148, in run
      'networkx>=2.0',
    File "d:\python\lib\distutils\cmd.py", line 335, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "d:\python\lib\distutils\util.py", line 303, in execute
      func(*args)
    File "C:\Users\wgfabc\AppData\Local\Temp\easy_install-up4wi_bs\pyvex-9.0.10730\setup.py", line 86, in _build_vex

  distutils.errors.LibError: Unable to build libVEX.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
      yield saved
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
      yield
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
      exec(code, globals, locals)
    File "C:\Users\wgfabc\AppData\Local\Temp\easy_install-up4wi_bs\pyvex-9.0.10730\setup.py", line 193, in <module>
    File "d:\python\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "d:\python\lib\distutils\core.py", line 163, in setup
      raise SystemExit("error: " + str(msg))
  SystemExit: error: Unable to build libVEX.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "d:\python\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
      run_setup(setup_script, args)
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
      raise
    File "d:\python\lib\contextlib.py", line 131, in __exit__
      self.gen.throw(type, value, traceback)
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
      yield
    File "d:\python\lib\contextlib.py", line 131, in __exit__
      self.gen.throw(type, value, traceback)
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
      saved_exc.resume()
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 141, in resume
      six.reraise(type, exc, self._tb)
    File "d:\python\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
      raise value.with_traceback(tb)
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
      yield saved
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
      yield
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "d:\python\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
      exec(code, globals, locals)
    File "C:\Users\wgfabc\AppData\Local\Temp\easy_install-up4wi_bs\pyvex-9.0.10730\setup.py", line 193, in <module>
    File "d:\python\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "d:\python\lib\distutils\core.py", line 163, in setup
      raise SystemExit("error: " + str(msg))
  SystemExit: error: Unable to build libVEX.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\wgfabc\AppData\Local\Temp\pip-install-ckqa1j_p\angr_b18b9b57dab241c69ebf626b20bc2679\setup.py", line 135, in <module>
      setup(
    File "d:\python\lib\site-packages\setuptools\__init__.py", line 144, in setup
      _install_setup_requires(attrs)
    File "d:\python\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "d:\python\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
      dist = best[req.key] = env.best_match(
    File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
      return self.obtain(req, installer)
    File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
      return installer(requirement)
    File "d:\python\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
      return cmd.easy_install(req)
    File "d:\python\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "d:\python\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "d:\python\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "d:\python\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "d:\python\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: Unable to build libVEX.
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/82/da/f9bddecbcc98b5c8ad7d7285e33d49030c6ce6f01f428f213a3d4a9f0130/angr-9.0.10730.tar.gz#sha256=966034dad27d9fb11acf371e789b88025246c6e0fadf773b07d644f16dc3b726 (from https://pypi.tuna.tsinghua.edu.cn/simple/angr/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5a/c9/28e15c57fdfb182f4fa24c202a83a5c6ac595f7fa36ccee8de5bde2b1e41/angr-9.0.10689.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wgfabc\\AppData\\Local\\Temp\\pip-install-ckqa1j_p\\angr_0ef3a17e94fa4f4dac736e0049226b7c\\setup.py'"'"'; __file__='"'"'C:\\Users\\wgfabc\\AppData\\Local\\Temp\\pip-install-ckqa1j_p\\angr_0ef3a17e94fa4f4dac736e0049226b7c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\wgfabc\AppData\Local\Temp\pip-pip-egg-info-4h53ihxt'
       cwd: C:\Users\wgfabc\AppData\Local\Temp\pip-install-ckqa1j_p\angr_0ef3a17e94fa4f4dac736e0049226b7c\
  Complete output (79 lines):
  Traceback (most recent call last):
    File "d:\python\lib\urllib\request.py", line 1319, in do_open
      h.request(req.get_method(), req.selector, req.data, headers,
    File "d:\python\lib\http\client.py", line 1230, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "d:\python\lib\http\client.py", line 1276, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "d:\python\lib\http\client.py", line 1225, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "d:\python\lib\http\client.py", line 1004, in _send_output
      self.send(msg)
    File "d:\python\lib\http\client.py", line 944, in send
      self.connect()
    File "d:\python\lib\site-packages\setuptools\ssl_support.py", line 173, in connect
      sock = socket.create_connection(
    File "d:\python\lib\socket.py", line 808, in create_connection
      raise err
    File "d:\python\lib\socket.py", line 796, in create_connection
      sock.connect(sa)
  TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 766, in open_url
      return open_with_auth(url, self.opener)
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 961, in _socket_timeout
      return func(*args, **kwargs)
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 1080, in open_with_auth
      fp = opener(request)
    File "d:\python\lib\urllib\request.py", line 525, in open
      response = self._open(req, data)
    File "d:\python\lib\urllib\request.py", line 542, in _open
      result = self._call_chain(self.handle_open, protocol, protocol +
    File "d:\python\lib\urllib\request.py", line 502, in _call_chain
      result = func(*args)
    File "d:\python\lib\site-packages\setuptools\ssl_support.py", line 160, in https_open
      return self.do_open(
    File "d:\python\lib\urllib\request.py", line 1322, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝 试失败。>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\wgfabc\AppData\Local\Temp\pip-install-ckqa1j_p\angr_0ef3a17e94fa4f4dac736e0049226b7c\setup.py", line 135, in <module>
      setup(
    File "d:\python\lib\site-packages\setuptools\__init__.py", line 144, in setup
      _install_setup_requires(attrs)
    File "d:\python\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "d:\python\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
      dist = best[req.key] = env.best_match(
    File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
      return self.obtain(req, installer)
    File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
      return installer(requirement)
    File "d:\python\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
      return cmd.easy_install(req)
    File "d:\python\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
      dist = self.package_index.fetch_distribution(
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 655, in fetch_distribution
      dist = find(requirement)
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 635, in find
      loc = self.download(dist.location, tmpdir)
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 579, in download
      found = self._download_url(scheme.group(1), spec, tmpdir)
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 824, in _download_url
      return self._attempt_download(url, filename)
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 830, in _attempt_download
      headers = self._download_to(url, filename)
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 729, in _download_to
      fp = self.open_url(url)
    File "d:\python\lib\site-packages\setuptools\package_index.py", line 779, in open_url
      raise DistutilsError("Download error for %s: %s"
  distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/a6/10/d29d04b177f7e59a8ebaf3da2b47c971b04750ccd652e730ca444d075d9e/pyvex-9.0.10730.tar.gz#sha256=d9c5db74fa966ac1a55ee971cbacc62909377a7b78751c105911b32a3defe8db: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/5a/c9/28e15c57fdfb182f4fa24c202a83a5c6ac595f7fa36ccee8de5bde2b1e41/angr-9.0.10689.tar.gz#sha256=00cb710c347eff349d723ff8dceb72dd9980c8f0732e9881459c08d36bd1d90d (from https://pypi.tuna.tsinghua.edu.cn/simple/angr/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/8c/4f/b74d4e8d09b483087f6f2fd7dc30361ce8320496274445505916a6ce4cae/angr-9.0.10651.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... canceled
ERROR: Operation cancelled by user
```

**Comment by ltfish** [comment]
Compilation issue. Make sure you have Visual Studio installed. Then open an x64 Native Tools Command Prompt for Visual Studio and install angr there.

**Comment by wgf4242** [comment]
> Compilation issue. Make sure you have Visual Studio installed. Then open an x64 Native Tools Command Prompt for Visual Studio and install angr there.

Thanks, solved.
I didn't use ` x64 Native Tools Command Prompt for Visual Studio`。

**Comment by wgf4242** [comment]
Another error.

```
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wgfabc\\AppData\\Local\\Temp\\pip-install-1393htwb\\angr_2c944ce046254d1889c8feda7e4c51b0\\setup.py'"'"'; __file__='"'"'C:\\Users\\wgfabc\\AppData\\Local\\Temp\\pip-install-1393htwb\\angr_2c944ce046254d1889c8feda7e4c51b0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\wgfabc\AppData\Local\Temp\pip-record-3jzctm2i\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python\Include\angr'
         cwd: C:\Users\wgfabc\AppData\Local\Temp\pip-install-1393htwb\angr_2c944ce046254d1889c8feda7e4c51b0\
    Complete output (4 lines):
    running install
    running build
    Building angr_native
    error: cannot load library 'd:\python\lib\site-packages\pyvex\lib\pyvex.dll': error 0xc1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wgfabc\\AppData\\Local\\Temp\\pip-install-1393htwb\\angr_2c944ce046254d1889c8feda7e4c51b0\\setup.py'"'"'; __file__='"'"'C:\\Users\\wgfabc\\AppData\\Local\\Temp\\pip-install-1393htwb\\angr_2c944ce046254d1889c8feda7e4c51b0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\wgfabc\AppData\Local\Temp\pip-record-3jzctm2i\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python\Include\angr' Check the logs for full command output.
```
