### ISSUE TITLE
A binary file cannot generate CFG using Emulated. The error message is “You can't fit a integral value of size 8 into an argument of size 4! ”

### ISSUE THREAD

**Issue by EudoraQR** [angr/angr#3029]
---

**Comment by EudoraQR** [comment]
Hi, developer
An error occurred when I used the CFGFast() function to generate a control flowchart, and the error was "You can't fit a integral value of size 8 into an argument of size 4!". Can you help me explain the cause of the error and provide a solution.
code
````
proj = angr.Project('libmedia.so', load_options={"auto_load_libs": False})
cfgs = proj.analyses.CFGFast(keep_state=True)
````

error
````
Traceback (most recent call last):
  File "xx/cfgGenerate.py", line 17, in <module>
    main()
  File "xx
[libmedia.zip](https://github.com/angr/angr/files/7769036/libmedia.zip)
/cfgGenerate.py", line 9, in main
    proj = angr.Project('libmedia.so', load_options={"auto_load_libs": False})
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\project.py", line 225, in __init__
    self._register_object(obj, sim_proc_arch)
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\project.py", line 356, in _register_object
    self.hook_symbol(export.rebased_addr, the_lib.get(export.name, sim_proc_arch))
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\procedures\definitions\__init__.py", line 326, in get
    return self.get_stub(name, arch)  # get_stub() might use the mangled name to derive the function prototype
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\procedures\definitions\__init__.py", line 346, in get_stub
    is_fp=[isinstance(arg, (SimTypeFloat, SimTypeDouble)) for arg in stub.cc.func_ty.args])
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\calling_conventions.py", line 533, in arg_locs
    return [session.next_arg(ifp, size=sz, ignore_real_args=ignore_real_args) for ifp, sz in zip(is_fp, sizes)]
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\calling_conventions.py", line 533, in <listcomp>
    return [session.next_arg(ifp, size=sz, ignore_real_args=ignore_real_args) for ifp, sz in zip(is_fp, sizes)]
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\calling_conventions.py", line 259, in next_arg
    arg = self.upsize_arg(arg, is_fp, size)
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\calling_conventions.py", line 264, in upsize_arg
    raise ValueError("You can't fit a integral value of size %d into an argument of size %d!" % (size, arg.size))
ValueError: You can't fit a integral value of size 8 into an argument of size 4!

Process finished with exit code 1
````
