### ISSUE TITLE
Reaching definitions analysis tries to subscript an FP object leading to TypeError

### ISSUE THREAD

**Issue by dnivra** [angr/angr#3070]
**Describe the bug.**

Reaching definitions analysis tries to subscript an FP object in [`_handle_Conversion`](https://github.com/angr/angr/blob/master/angr/analyses/reaching_definitions/engine_vex.py#L464) and encounters a `TypeError`. Here is traceback printed in console in angr-management:

```
Exception while running job "Variable Recovery":
Traceback (most recent call last):
  File "/home/dnivra/angr-dev/angr-management/angrmanagement/data/instance.py", line 270, in _worker
    result = job.run(self)
  File "/home/dnivra/angr-dev/angr-management/angrmanagement/data/jobs/job.py", line 42, in run
    return self._run(inst)
  File "/home/dnivra/angr-dev/angr-management/angrmanagement/data/jobs/variable_recovery.py", line 23, in _run
    inst.project.analyses.CompleteCallingConventions(
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/complete_calling_conventions.py", line 48, in __init__
    self._analyze()
  File "/home/dnivra/angr-dev/angr/angr/analyses/complete_calling_conventions.py", line 101, in _analyze
    cc_analysis = self.project.analyses.CallingConvention(func, cfg=self._cfg,
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/calling_convention.py", line 81, in __init__
    self._analyze()
  File "/home/dnivra/angr-dev/angr/angr/analyses/calling_convention.py", line 113, in _analyze
    callsite_facts = self._analyze_callsites(max_analyzing_callsites=3)
  File "/home/dnivra/angr-dev/angr/angr/analyses/calling_convention.py", line 242, in _analyze_callsites
    rda = self.project.analyses.ReachingDefinitions(
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/reaching_definitions.py", line 162, in __init__
    self._analyze()
  File "/home/dnivra/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py", line 240, in _analyze
    self._analysis_core_graph()
  File "/home/dnivra/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py", line 259, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/reaching_definitions.py", line 365, in _run_on_node
    state, self._visited_blocks, self._dep_graph = engine.process(
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/engine_vex.py", line 62, in process
    self._process(
  File "/home/dnivra/angr-dev/angr/angr/engines/light/engine.py", line 145, in _process
    self._process_Stmt(whitelist=whitelist)
  File "/home/dnivra/angr-dev/angr/angr/engines/light/engine.py", line 166, in _process_Stmt
    self._handle_Stmt(stmt)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/engine_vex.py", line 106, in _handle_Stmt
    super()._handle_Stmt(stmt)
  File "/home/dnivra/angr-dev/angr/angr/engines/light/engine.py", line 194, in _handle_Stmt
    getattr(self, handler)(stmt)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/engine_vex.py", line 113, in _handle_WrTmp
    data: MultiValues = self._expr(stmt.data)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/engine_vex.py", line 299, in _expr
    data = super()._expr(expr)
  File "/home/dnivra/angr-dev/angr/angr/engines/light/engine.py", line 232, in _expr
    return getattr(self, handler)(expr)
  File "/home/dnivra/angr-dev/angr/angr/engines/light/engine.py", line 294, in _handle_Unop
    return getattr(self, handler)(expr)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/engine_vex.py", line 464, in _handle_Conversion
    data.add(v[bits - 1:0])
TypeError: 'FP' object is not subscriptable
```

**Environment Information.**

I am running current HEAD of all repos. Including full environment information for completeness:

```
=============================
Date: 2022-01-08 16:19:36.532352
Running in virtual environment at /home/dnivra/.virtualenvs/angr-dev
Platform: linux-x86_64
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
######## angr #########
Python found it in /home/dnivra/angr-dev/angr/angr
Pip version angr 9.1.gitrolling
Git info:
        Current commit 4b04d56ace135018083d36d9083805be8146688b from branch master
        Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/dnivra/angr-dev/ailment/ailment
Pip version ailment 9.1.gitrolling
Git info:
        Current commit 638496df6547662517f5f524c9bde4b53fcbd176 from branch master
        Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/dnivra/angr-dev/cle/cle
Pip version cle 9.1.gitrolling
Git info:
        Current commit 7dea3e72a06c7596b9ef7b884c42cb19bca7620a from branch master
        Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/dnivra/angr-dev/pyvex/pyvex
Pip version pyvex 9.1.gitrolling
Git info:
        Current commit 91e5e27b804e3712899796b00814b2cb4f0855d8 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/dnivra/angr-dev/claripy/claripy
Pip version claripy 9.1.gitrolling
Git info:
        Current commit 4c961b4dc664706be8142fe4868f27655bc8da77 from branch master
        Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/dnivra/angr-dev/archinfo/archinfo
Pip version archinfo 9.1.gitrolling
Git info:
        Current commit bd84450115db29bef89022e3c63c7ea84facd46e from branch master
        Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/dnivra/.virtualenvs/angr-dev/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.14.0
Couldn't find git info
######## unicorn #########
Python found it in /home/dnivra/.virtualenvs/angr-dev/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/dnivra/angr-dev/angr/angr/state_plugins/../lib/angr_native.so', handle 27bd560 at 0x7f1eb18b3cd0>
unicorn: <CDLL '/home/dnivra/.virtualenvs/angr-dev/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 21689a0 at 0x7f1eb692a2b0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f1eb754fb50>
z3: NOT FOUND
```

**To Reproduce.**

Load [CROMU_00005](https://github.com/zardus/cgc-bins/blob/master/all_unpatched/CROMU_00005) into angr-management. The bug gets triggered when recovering variables.

**Comment by ltfish** [comment]
Thanks for reporting. This problem has been fixed on the wip/fp branch (with floating point support). Should be merged into angr within next week.

**Comment by dnivra** [comment]
Sharing info on another issue that seems similar to this one but occurs elsewhere in angr. This bug is also triggered when recovering variables in NRFIN_00016 CGC binary. I am not including full environment info: I am able to reproduce this when using current(as of writing) master branch of all repos. If full info is needed, I can share it. To reproduce the issue, simply load [NRFIN_00016](https://github.com/zardus/cgc-bins/blob/master/all_unpatched/NRFIN_00016) into angr-management.

Traceback:

```
Traceback (most recent call last):
  File "/home/dnivra/angr-dev/angr-management/angrmanagement/data/instance.py", line 275, in _worker
    result = job.run(self)
  File "/home/dnivra/angr-dev/angr-management/angrmanagement/data/jobs/job.py", line 42, in run
    return self._run(inst)
  File "/home/dnivra/angr-dev/angr-management/angrmanagement/data/jobs/variable_recovery.py", line 23, in _run
    inst.project.analyses.CompleteCallingConventions(
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 138, in __call__
    return w(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 122, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/complete_calling_conventions.py", line 48, in __init__
    self._analyze()
  File "/home/dnivra/angr-dev/angr/angr/analyses/complete_calling_conventions.py", line 101, in _analyze
    cc_analysis = self.project.analyses[CallingConventionAnalysis].prep(kb=self.kb)(func, cfg=self._cfg,
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 122, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/calling_convention.py", line 98, in __init__
    self._analyze()
  File "/home/dnivra/angr-dev/angr/angr/analyses/calling_convention.py", line 135, in _analyze
    callsite_facts = self._analyze_callsites(max_analyzing_callsites=3)
  File "/home/dnivra/angr-dev/angr/angr/analyses/calling_convention.py", line 268, in _analyze_callsites
    rda = self.project.analyses[ReachingDefinitionsAnalysis].prep()(
  File "/home/dnivra/angr-dev/angr/angr/analyses/analysis.py", line 122, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/reaching_definitions.py", line 162, in __init__
    self._analyze()
  File "/home/dnivra/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py", line 241, in _analyze
    self._analysis_core_graph()
  File "/home/dnivra/angr-dev/angr/angr/analyses/forward_analysis/forward_analysis.py", line 260, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/reaching_definitions.py", line 365, in _run_on_node
    state, self._visited_blocks, self._dep_graph = engine.process(
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/engine_vex.py", line 62, in process
    self._process(
  File "/home/dnivra/angr-dev/angr/angr/engines/light/engine.py", line 145, in _process
    self._process_Stmt(whitelist=whitelist)
  File "/home/dnivra/angr-dev/angr/angr/engines/light/engine.py", line 166, in _process_Stmt
    self._handle_Stmt(stmt)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/engine_vex.py", line 106, in _handle_Stmt
    super()._handle_Stmt(stmt)
  File "/home/dnivra/angr-dev/angr/angr/engines/light/engine.py", line 194, in _handle_Stmt
    getattr(self, handler)(stmt)
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/engine_vex.py", line 154, in _handle_Put
    self.state.add_use(MemoryLocation(SpOffset(self.arch.bits, stack_offset), 1), self._codeloc())
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/rd_state.py", line 410, in add_use
    self.codeloc_uses.update(self.get_definitions(atom))
  File "/home/dnivra/angr-dev/angr/angr/analyses/reaching_definitions/rd_state.py", line 421, in get_definitions
    yield from self.live_definitions.get_definitions(atom)
  File "/home/dnivra/angr-dev/angr/angr/knowledge_plugins/key_definitions/live_definitions.py", line 459, in get_definitions
    mv: MultiValues = self.stack_definitions.load(stack_addr, size=atom.size, endness=atom.endness)
  File "/home/dnivra/angr-dev/angr/angr/storage/memory_mixins/size_resolution_mixin.py", line 28, in load
    return super().load(addr, size=out_size, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py", line 143, in load
    out = self.PAGE_TYPE._compose_objects(vals, size, endness, memory=self, **kwargs)
  File "/home/dnivra/angr-dev/angr/angr/storage/memory_mixins/paged_memory/pages/cooperation.py", line 139, in _compose_objects
    chopped = o.bytes_at(
  File "/home/dnivra/angr-dev/angr/angr/storage/memory_object.py", line 80, in bytes_at
    thing = bv_slice(self.object, offset, length, self.endness == 'Iend_LE', self._byte_width)
  File "/home/dnivra/angr-dev/angr/angr/storage/memory_object.py", line 174, in bv_slice
    return value[bitstart - 1:bitstart - size * bw]
TypeError: 'FP' object is not subscriptable
```

**Comment by dnivra** [comment]
This error does not seem to occur as of angr-management 9.2.5. However, I am not sure if floating point support has been merged in and so unsure if this issue has been fixed.
