### ISSUE TITLE
SimState Merging: Attribute Error

### ISSUE THREAD

**Issue by NicolaasWeideman** [angr/angr#3127]
---

**Describe the bug.**

When merging multiple SimStates, the following error occurs:
```
Traceback (most recent call last):
  File "analyze.py", line 27, in <module>
    main()
  File "analyze.py", line 22, in main
    state, constraints, merge_occurred =  end_states[0].merge(end_states[1], merge_conditions=[state.solver.constraints for state in end_states])
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/angr/sim_state.py", line 720, in merge
    plugin_state_merged = our_filled_plugin.merge(
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/angr/state_plugins/solver.py", line 89, in wrapped_f
    return f(*args, **kwargs)
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/angr/state_plugins/solver.py", line 435, in merge
    merging_occurred, self._stored_solver = self._solver.merge(
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/claripy/frontends/composite_frontend.py", line 454, in merge
    _, merged_noncommon = combined_noncommons[0].merge(
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/claripy/frontends/full_frontend.py", line 236, in merge
    return self._solver_backend.__class__.__name__ == 'BackendZ3', ConstrainedFrontend.merge(
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/claripy/frontends/constrained_frontend.py", line 69, in merge
    options.append(And(*([v] + s.constraints)))
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/claripy/operations.py", line 53, in _op
    simp = _handle_annotations(simplifications.simpleton.simplify(name, fixed_args), args)
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/claripy/simplifications.py", line 41, in simplify
    return self._simplifiers[op](*args)
  File "/home/user/.virtualenvs/angr/lib/python3.8/site-packages/claripy/simplifications.py", line 389, in boolean_and_simplifier
    if fargs[0].args[0].symbolic:
AttributeError: 'int' object has no attribute 'symbolic'
```
Here is the merge statement:
```python
end_states[0].merge(end_states[1], merge_conditions=[state.solver.constraints for state in end_states])
```

**Environment Information.**

Here follows the output of `python -m angr.misc.bug_report`:
```
/home/user/.virtualenvs/angr/lib/python3.8/site-packages/angr/misc/bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2022-02-07 16:19:19.606925
Running in virtual environment at /home/user/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
######## angr #########
Python found it in /home/user/.virtualenvs/angr/lib/python3.8/site-packages/angr
Pip version angr 9.1.11611
Couldn't find git info
######## ailment #########
Python found it in /home/user/.virtualenvs/angr/lib/python3.8/site-packages/ailment
Pip version ailment 9.1.11611
Couldn't find git info
######## cle #########
Python found it in /home/user/.virtualenvs/angr/lib/python3.8/site-packages/cle
Pip version cle 9.1.11611
Couldn't find git info
######## pyvex #########
Python found it in /home/user/.virtualenvs/angr/lib/python3.8/site-packages/pyvex
Pip version pyvex 9.1.11611
Couldn't find git info
######## claripy #########
Python found it in /home/user/.virtualenvs/angr/lib/python3.8/site-packages/claripy
Pip version claripy 9.1.11611
Couldn't find git info
######## archinfo #########
Python found it in /home/user/.virtualenvs/angr/lib/python3.8/site-packages/archinfo
Pip version archinfo 9.1.11611
Couldn't find git info
######## z3 #########
Python found it in /home/user/.virtualenvs/angr/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.12.0
Couldn't find git info
######## unicorn #########
Python found it in /home/user/.virtualenvs/angr/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/user/.virtualenvs/angr/lib/python3.8/site-packages/angr/state_plugins/../lib/angr_native.so', handle 2c9fe60 at 0x7febff3934f0>
unicorn: <CDLL '/home/user/.virtualenvs/angr/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 2607b50 at 0x7fec03449820>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fec041dbd00>
z3: NOT FOUND
```

**To Reproduce.**

Here is a zip archive containing a minimal script and binary to reproduce the crash:
[files.zip](https://github.com/angr/angr/files/8019624/files.zip)

**Additional context.**

The binary is created for the ARM architecture.

**Comment by Hanseltu** [comment]
I encountered the same error in analyzing a binary in X86, where the binary is compiled with a higher optimization option (i.e., -O3, in both GCC and LLVM compiler) when compiling the source code, any solution by the way?  Thanks！

**Comment by ltfish** [comment]
This is definitely a bug. It's on my radar now.
