### ISSUE TITLE
Trouble using CFG

### ISSUE THREAD

**Issue by eQu1NoX** [angr/angr#32]
```python
>>> import angr
>>> proj = angr.Project('./test')
>>> cfg = proj.analyses.CFG();
No handlers could be found for logger "simuvex.plugins.solver"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/asdf/angr-master/venv/local/lib/python2.7/site-packages/angr/analysis.py", line 84, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/asdf/angr-master/venv/local/lib/python2.7/site-packages/angr/analyses/cfg.py", line 232, in __init__
    self._construct()
  File "/home/asdf/angr-master/venv/local/lib/python2.7/site-packages/angr/analyses/cfg.py", line 335, in _construct
    loaded_state = self.project.factory.entry_state(mode="fastpath")
  File "/home/asdf/angr-master/venv/local/lib/python2.7/site-packages/angr/factory.py", line 145, in entry_state
    return self._project._simos.state_entry(**kwargs)
  File "/home/asdf/angr-master/venv/local/lib/python2.7/site-packages/angr/simos.py", line 201, in state_entry
    state = super(SimLinux, self).state_entry(**kwargs)
  File "/home/asdf/angr-master/venv/local/lib/python2.7/site-packages/angr/simos.py", line 67, in state_entry
    return self.state_blank(**kwargs)
  File "/home/asdf/angr-master/venv/local/lib/python2.7/site-packages/angr/simos.py", line 193, in state_blank
    state.register_plugin('posix', SimStateSystem(fs=fs, concrete_fs=concrete_fs, chroot=chroot))
TypeError: __init__() got an unexpected keyword argument 'chroot'
```

**Comment by ltfish** [comment]
It seems to be a version mismatch. @rhelmot

**Comment by rhelmot** [comment]
This error would show up because your version of simuvex is out of date.

**Comment by zardus** [comment]
Indeed. There are a few options to fix this:

1. if you installed via pip, then `pip install -U angr` should update everything.
2. if you installed in development-mode via `angr-dev`, then `./git_all.sh pull` from the `angr-dev` directory should update everything.

**Comment by eQu1NoX** [comment]
Thank you @zardus @rhelmot @ltfish , appreciate it !
