### ISSUE TITLE
Little Engine Example Failing in conda environment

### ISSUE THREAD

**Issue by rchtsang** [angr/angr#3227]
---

**Describe the bug.**

The `solve.py` script from the little\_engine example (found [here](https://github.com/angr/angr-doc/tree/master/examples/b01lersctf2020_little_engine)) terminates with the following error:
```
File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/calling_conventions.py", line 1444, in _classify
    raise NotImplementedError("Ummmmm... not sure what goes here. report bug to @rhelmot")
NotImplementedError: Ummmmm... not sure what goes here. report bug to @rhelmot
```
The full trace and log output is in additional context. 

**Environment Information.**

2015 Macbook Pro macOS Mojave (10.14.6) (yes i know it's deprecated but embedded systems don't like new things pls don't hate me)

I am running from inside a conda environment that was created with the following steps:
```
mamba create -n angr
conda activate angr
mamba install -c conda-forge python=3.9 jupyterlab
UNICORN_QEMU_FLAGS="--python=/usr/bin/python" pip install unicorn=1.0.2rc4
pip install angr
PYVEX=`python3 -c 'import pyvex; print(pyvex.__path__[0])'`
UNICORN=`python3 -c 'import unicorn; print(unicorn.__path__[0])'`
ANGR=`python3 -c 'import angr; print(angr.__path__[0])'`

install_name_tool -change libunicorn.1.dylib "$UNICORN"/lib/libunicorn.dylib "$ANGR"/lib/angr_native.dylib
install_name_tool -change libpyvex.dylib "$PYVEX"/lib/libpyvex.dylib "$ANGR"/lib/angr_native.dylib
```

The output from `python -m angr.misc.bug_report`
```
/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/misc/bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2022-03-24 11:14:55.879387
!!! runninng in global environment.  Are you sure? !!!
Platform: macosx-10.9-x86_64
Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:27:48) 
[Clang 11.1.0 ]
######## angr #########
Python found it in /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr
Pip version angr 9.1.12332
Couldn't find git info
######## ailment #########
Python found it in /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/ailment
Pip version ailment 9.1.12332
Couldn't find git info
######## cle #########
Python found it in /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/cle
Pip version cle 9.1.12332
Couldn't find git info
######## pyvex #########
Python found it in /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/pyvex
Pip version pyvex 9.1.12332
Couldn't find git info
######## claripy #########
Python found it in /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/claripy
Pip version claripy 9.1.12332
Couldn't find git info
######## archinfo #########
Python found it in /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/archinfo
Pip version archinfo 9.1.12332
Couldn't find git info
######## z3 #########
Python found it in /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/z3
Pip version z3-solver 4.8.15.0
Couldn't find git info
######## unicorn #########
Python found it in /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/state_plugins/../lib/angr_native.dylib', handle 7fd17d542360 at 0x10cc9f670>
unicorn: <CDLL '/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/unicorn/lib/libunicorn.dylib', handle 7fd17f9d1190 at 0x1080de2b0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x1073bbd00>
z3: NOT FOUND
```

**To Reproduce.**

[little-engine.zip](https://github.com/angr/angr/files/8356832/little-engine.zip)
script and binary in above zip file
recreate by following environment creation steps listed above, navigating to little-engine directory, activating the conda environment with angr installed, and running `python3 solve.py`.

**Additional context.**

Full output
```
WARNING | 2022-03-24 10:57:26,337 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: _ZSt4cout
WARNING | 2022-03-24 10:57:26,338 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: _ZSt3cin
WARNING | 2022-03-24 10:57:26,339 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
WARNING | 2022-03-24 10:57:26,421 | angr.simos.simos | stdin is constrained to 302 bytes (has_end=True). If you are only providing the first 302 bytes instead of the entire stdin, please use stdin=SimFileStream(name='stdin', content=your_first_n_bytes, has_end=False).
WARNING | 2022-03-24 10:57:37,917 | angr.storage.memory_mixins.default_filler_mixin | The program is accessing memory with an unspecified value. This could indicate unwanted behavior.
WARNING | 2022-03-24 10:57:37,918 | angr.storage.memory_mixins.default_filler_mixin | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2022-03-24 10:57:37,918 | angr.storage.memory_mixins.default_filler_mixin | 1) setting a value to the initial state
WARNING | 2022-03-24 10:57:37,918 | angr.storage.memory_mixins.default_filler_mixin | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2022-03-24 10:57:37,918 | angr.storage.memory_mixins.default_filler_mixin | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
WARNING | 2022-03-24 10:57:37,918 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x7fffffffffeff8c with 4 unconstrained bytes referenced from 0x101419 (PLT._ZNSt9exceptionD1Ev+0x19f in engine (0x1419))
WARNING | 2022-03-24 10:57:38,687 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffffffffffffe8 with 8 unconstrained bytes referenced from 0x1016f0 (PLT._ZNSt9exceptionD1Ev+0x476 in engine (0x16f0))
WARNING | 2022-03-24 10:57:41,626 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffffffffffbef0 with 8 unconstrained bytes referenced from 0x1016f4 (PLT._ZNSt9exceptionD1Ev+0x47a in engine (0x16f4))
WARNING | 2022-03-24 10:57:42,913 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffff8000000018 with 1 unconstrained bytes referenced from 0x101705 (PLT._ZNSt9exceptionD1Ev+0x48b in engine (0x1705))
WARNING | 2022-03-24 10:57:43,109 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffff8000000023 with 1 unconstrained bytes referenced from 0x10170b (PLT._ZNSt9exceptionD1Ev+0x491 in engine (0x170b))
WARNING | 2022-03-24 10:57:43,209 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffff7fffffffe0 with 8 unconstrained bytes referenced from 0x101760 (PLT._ZNSt9exceptionD1Ev+0x4e6 in engine (0x1760))
WARNING | 2022-03-24 10:57:43,878 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x31 with 8 unconstrained bytes referenced from 0x101770 (PLT._ZNSt9exceptionD1Ev+0x4f6 in engine (0x1770))
WARNING | 2022-03-24 10:57:44,530 | angr.engines.successors | Exit state has over 256 possible solutions. Likely unconstrained; skipping. <BV64 mem_31_312_64{UNINITIALIZED}>
Traceback (most recent call last):
  File "/Users/rtsang/Documents/DavisResearch/tools/learn-angr/examples/basic/little-engine/solve.py", line 69, in <module>
    print(main())
  File "/Users/rtsang/Documents/DavisResearch/tools/learn-angr/examples/basic/little-engine/solve.py", line 48, in main
    sm.run()
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_manager.py", line 280, in run
    self.step(stash=stash, **kwargs)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_manager.py", line 365, in step
    successors = self.step_state(state, successor_func=successor_func, **run_args)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_manager.py", line 402, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_manager.py", line 441, in successors
    return self._project.factory.successors(state, **run_args)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/factory.py", line 60, in successors
    return self.default_engine.process(*args, **kwargs)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/vex/light/slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/engine.py", line 158, in process
    self.process_successors(self.successors, **kwargs)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/syscall.py", line 18, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/hook.py", line 61, in process_successors
    return self.process_procedure(state, successors, procedure, **kwargs)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/procedure.py", line 37, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to, arguments=arguments)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_procedure.py", line 240, in execute
    sim_args = [inst.cc.next_arg(inst.arg_session, ty).get_value(inst.state) for ty in inst.prototype.args]
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_procedure.py", line 240, in <listcomp>
    sim_args = [inst.cc.next_arg(inst.arg_session, ty).get_value(inst.state) for ty in inst.prototype.args]
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/calling_conventions.py", line 1344, in next_arg
    classification = self._classify(arg_type)
  File "/Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/calling_conventions.py", line 1444, in _classify
    raise NotImplementedError("Ummmmm... not sure what goes here. report bug to @rhelmot")
NotImplementedError: Ummmmm... not sure what goes here. report bug to @rhelmot
```

compared to the correct output (which i can produce on a separate linux machine) 
```
WARNING | 2022-03-24 10:51:18,252 | cle.backends.tls | The provided object has an invalid tls_data_size. Skip TLS loading.
WARNING | 2022-03-24 10:51:19,101 | angr.simos.simos | stdin is constrained to 302 bytes (has_end=True). If you are only providing the first 302 bytes instead of the entire stdin, please use stdin=SimFileStream(name='stdin', content=your_first_n_bytes, has_end=False).
WARNING | 2022-03-24 10:51:25,885 | angr.storage.memory_mixins.default_filler_mixin | The program is accessing memory with an unspecified value. This could indicate unwanted behavior.
WARNING | 2022-03-24 10:51:25,886 | angr.storage.memory_mixins.default_filler_mixin | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2022-03-24 10:51:25,886 | angr.storage.memory_mixins.default_filler_mixin | 1) setting a value to the initial state
WARNING | 2022-03-24 10:51:25,886 | angr.storage.memory_mixins.default_filler_mixin | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2022-03-24 10:51:25,886 | angr.storage.memory_mixins.default_filler_mixin | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
WARNING | 2022-03-24 10:51:25,886 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x7fffffffffeff8c with 4 unconstrained bytes referenced from 0x101419 (PLT._ZNSt9exceptionD1Ev+0x19f in engine (0x1419))
pctf{th3_m0d3rn_st34m_3ng1n3_w45_1nv3nt3d_1n_1698_buT_th3_b3st_0n3_in_1940}
Time elapsed: 211.38044095039368
```

Any help would be appreciated, but this isn't a critical issue since i know my machine is deprecated, and i can always run in a virtual machine

**Comment by rhelmot** [comment]
I'm unable to reproduce this issue in a conda env on linux... I'm pretty sure it has to do with macos, not conda. angr will pull from your operating system in order to do header preprocessing, which can then bubble up into calling convention ffi, but I'm not particularly sure how that's happening in this example.

One thing you can do to help me track this down is get a debug shell at the site of the exception (ipython --pdb) and print out the value of the `ty` variable.

**Comment by rchtsang** [comment]
Sorry for the delay.

Output below:
```py
$ ipython --pdb solve.py 
WARNING | 2022-03-31 16:42:55,169 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: _ZSt4cout
WARNING | 2022-03-31 16:42:55,170 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: _ZSt3cin
WARNING | 2022-03-31 16:42:55,171 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
WARNING | 2022-03-31 16:42:55,249 | angr.simos.simos | stdin is constrained to 302 bytes (has_end=True). If you are only providing the first 302 bytes instead of the entire stdin, please use stdin=SimFileStream(name='stdin', content=your_first_n_bytes, has_end=False).
WARNING | 2022-03-31 16:43:12,571 | angr.storage.memory_mixins.default_filler_mixin | The program is accessing memory with an unspecified value. This could indicate unwanted behavior.
WARNING | 2022-03-31 16:43:12,571 | angr.storage.memory_mixins.default_filler_mixin | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2022-03-31 16:43:12,571 | angr.storage.memory_mixins.default_filler_mixin | 1) setting a value to the initial state
WARNING | 2022-03-31 16:43:12,571 | angr.storage.memory_mixins.default_filler_mixin | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2022-03-31 16:43:12,571 | angr.storage.memory_mixins.default_filler_mixin | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
WARNING | 2022-03-31 16:43:12,572 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x7fffffffffeff8c with 4 unconstrained bytes referenced from 0x101419 (PLT._ZNSt9exceptionD1Ev+0x19f in engine (0x1419))
WARNING | 2022-03-31 16:43:13,192 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffffffffffffe8 with 8 unconstrained bytes referenced from 0x1016f0 (PLT._ZNSt9exceptionD1Ev+0x476 in engine (0x16f0))
WARNING | 2022-03-31 16:43:17,445 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffffffffffffff with 1 unconstrained bytes referenced from 0x1016f4 (PLT._ZNSt9exceptionD1Ev+0x47a in engine (0x16f4))
WARNING | 2022-03-31 16:43:17,446 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x0 with 7 unconstrained bytes referenced from 0x1016f4 (PLT._ZNSt9exceptionD1Ev+0x47a in engine (0x16f4))
WARNING | 2022-03-31 16:43:18,671 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xfffffffffffffffe with 1 unconstrained bytes referenced from 0x101705 (PLT._ZNSt9exceptionD1Ev+0x48b in engine (0x1705))
WARNING | 2022-03-31 16:43:18,941 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x9 with 1 unconstrained bytes referenced from 0x10170b (PLT._ZNSt9exceptionD1Ev+0x491 in engine (0x170b))
WARNING | 2022-03-31 16:43:19,157 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffffffffffffc6 with 8 unconstrained bytes referenced from 0x101760 (PLT._ZNSt9exceptionD1Ev+0x4e6 in engine (0x1760))
WARNING | 2022-03-31 16:43:20,100 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x31 with 8 unconstrained bytes referenced from 0x101770 (PLT._ZNSt9exceptionD1Ev+0x4f6 in engine (0x1770))
WARNING | 2022-03-31 16:43:21,016 | angr.engines.successors | Exit state has over 256 possible solutions. Likely unconstrained; skipping. <BV64 mem_31_313_64{UNINITIALIZED}>
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
File ~/Documents/DavisResearch/tools/learn-angr/examples/basic/little-engine/solve.py:69, in <module>
     67 if __name__ == "__main__":
     68     before = time.time()
---> 69     print(main())
     70     after = time.time()
     71     print("Time elapsed: {}".format(after - before))

File ~/Documents/DavisResearch/tools/learn-angr/examples/basic/little-engine/solve.py:48, in main()
     45 # Construct a SimulationManager to perform symbolic execution.
     46 # Step until there is nothing left to be stepped.
     47 sm = p.factory.simulation_manager(st)
---> 48 sm.run()
     50 #grab all finished states, that have the win function output in stdout
     51 y = []

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_manager.py:280, in SimulationManager.run(self, stash, n, until, **kwargs)
    278 for _ in (itertools.count() if n is None else range(0, n)):
    279     if not self.complete() and self._stashes[stash]:
--> 280         self.step(stash=stash, **kwargs)
    281         if not (until and until(self)):
    282             continue

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_manager.py:365, in SimulationManager.step(self, stash, n, selector_func, step_func, successor_func, until, filter_func, **run_args)
    361     continue
    363 pre_errored = len(self._errored)
--> 365 successors = self.step_state(state, successor_func=successor_func, **run_args)
    366 # handle degenerate stepping cases here. desired behavior:
    367 # if a step produced only unsat states, always add them to the unsat stash since this usually indicates a bug
    368 # if a step produced sat states and save_unsat is False, drop the unsats
    369 # if a step produced no successors, period, add the original state to deadended
    370 
    371 # first check if anything happened besides unsat. that gates all this behavior
    372 if not any(v for k, v in successors.items() if k != 'unsat') and len(self._errored) == pre_errored:
    373     # then check if there were some unsats

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_manager.py:402, in SimulationManager.step_state(self, state, successor_func, **run_args)
    398 """
    399 Don't use this function manually - it is meant to interface with exploration techniques.
    400 """
    401 try:
--> 402     successors = self.successors(state, successor_func=successor_func, **run_args)
    403     stashes = {None: successors.flat_successors,
    404                'unsat': successors.unsat_successors,
    405                'unconstrained': successors.unconstrained_successors}
    407 except (SimUnsatError, claripy.UnsatError) as e:

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_manager.py:441, in SimulationManager.successors(self, state, successor_func, **run_args)
    439 if successor_func is not None:
    440     return successor_func(state, **run_args)
--> 441 return self._project.factory.successors(state, **run_args)

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/factory.py:60, in AngrObjectFactory.successors(self, engine, *args, **kwargs)
     58 if engine is not None:
     59     return engine.process(*args, **kwargs)
---> 60 return self.default_engine.process(*args, **kwargs)

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/vex/light/slicing.py:19, in VEXSlicingMixin.process(self, skip_stmts, last_stmt, whitelist, *args, **kwargs)
     17 self._last_stmt = last_stmt
     18 self._whitelist = whitelist
---> 19 return super().process(*args, **kwargs)

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/engine.py:158, in SuccessorsMixin.process(***failed resolving arguments***)
    156 self.successors = new_state._inspect_getattr('sim_successors', self.successors)
    157 try:
--> 158     self.process_successors(self.successors, **kwargs)
    159 except SimException:
    160     if o.EXCEPTION_HANDLING not in old_state.options:

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/failure.py:21, in SimEngineFailure.process_successors(self, successors, **kwargs)
     18     terminator = SIM_PROCEDURES['stubs']['PathTerminator'](project=self.project)
     19     return self.process_procedure(state, successors, terminator, **kwargs)
---> 21 return super().process_successors(successors, **kwargs)

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/syscall.py:18, in SimEngineSyscall.process_successors(self, successors, **kwargs)
     16 # we have at this point entered the next step so we need to check the previous jumpkind
     17 if not state.history or not state.history.parent or not state.history.parent.jumpkind or not state.history.parent.jumpkind.startswith('Ijk_Sys'):
---> 18     return super().process_successors(successors, **kwargs)
     20 l.debug("Invoking system call handler")
     21 sys_procedure = self.project.simos.syscall(state)

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/hook.py:61, in HooksMixin.process_successors(self, successors, procedure, **kwargs)
     58 else:
     59     l.debug("Running %s (originally at %s)", repr(procedure), procedure.addr if procedure.addr is None else hex(procedure.addr))
---> 61 return self.process_procedure(state, successors, procedure, **kwargs)

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/engines/procedure.py:37, in ProcedureMixin.process_procedure(self, state, successors, procedure, ret_to, arguments, **kwargs)
     34     state.options.add(o.AUTO_REFS)
     36 # do it
---> 37 inst = procedure.execute(state, successors, ret_to=ret_to, arguments=arguments)
     38 successors.artifacts['procedure'] = inst
     40 if cleanup_options:

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_procedure.py:240, in SimProcedure.execute(self, state, successors, arguments, ret_to)
    238     inst.use_state_arguments = True
    239     inst.arg_session = inst.cc.arg_session(inst.prototype.returnty)
--> 240     sim_args = [inst.cc.next_arg(inst.arg_session, ty).get_value(inst.state) for ty in inst.prototype.args]
    241     inst.arguments = sim_args
    242 else:

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/sim_procedure.py:240, in <listcomp>(.0)
    238     inst.use_state_arguments = True
    239     inst.arg_session = inst.cc.arg_session(inst.prototype.returnty)
--> 240     sim_args = [inst.cc.next_arg(inst.arg_session, ty).get_value(inst.state) for ty in inst.prototype.args]
    241     inst.arguments = sim_args
    242 else:

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/calling_conventions.py:1344, in SimCCSystemVAMD64.next_arg(self, session, arg_type)
   1342 def next_arg(self, session, arg_type):
   1343     state = session.getstate()
-> 1344     classification = self._classify(arg_type)
   1345     try:
   1346         mapped_classes = []

File ~/miniconda3/envs/angr/lib/python3.9/site-packages/angr/calling_conventions.py:1444, in SimCCSystemVAMD64._classify(self, ty, chunksize)
   1442     return result
   1443 else:
-> 1444     raise NotImplementedError("Ummmmm... not sure what goes here. report bug to @rhelmot")

NotImplementedError: Ummmmm... not sure what goes here. report bug to @rhelmot
> /Users/rtsang/miniconda3/envs/angr/lib/python3.9/site-packages/angr/calling_conventions.py(1444)_classify()
   1442             return result
   1443         else:
-> 1444             raise NotImplementedError("Ummmmm... not sure what goes here. report bug to @rhelmot")
   1445 
   1446     def _flatten(self, ty) -> Optional[Dict[int,List[SimType]]]:

ipdb> ty
string_t&
```

**Comment by rhelmot** [comment]
ahhhh shit. I don't know how a SimTypeString could have ended up in here? Could you please try to trace back where that SimTypeString comes from? It probably is the instance in angr.sim_type.ALL_TYPES['string'], but I'd like to know who read that from the dict.

**Comment by rchtsang** [comment]
I still haven't figured that out yet (I haven't had much time to try to fix this lately) but I went back through the trace to where the SimTypeString shows up and printed some of the variables. I haven't taken too much time to get familiar with angr's source code so I'm not quite sure where how the `inst.prototype` fields get updated.

```py
168  	    def execute(self, state, successors=None, arguments=None, ret_to=None):
169  	        """
170  	        Call this method with a SimState and a SimSuccessors to execute the procedure.
171  	
172  	        Alternately, successors may be none if this is an inline call. In that case, you should
173  	        provide arguments to the function.
174  	        """
175  	        # fill out all the fun stuff we don't want to frontload
176  	        if self.addr is None and not state.regs._ip.symbolic:
177  	            self.addr = state.addr
178  	        if self.arch is None:
179  	            self.arch = state.arch
180  	        if self.project is None:
181  	            self.project = state.project
182  	        if self.cc is None:
183  	            if self.arch.name in DEFAULT_CC:
184  	                self.cc = DEFAULT_CC[self.arch.name](self.arch)
185  	            else:
186  	                raise SimProcedureError('There is no default calling convention for architecture %s.'
187  	                                        ' You must specify a calling convention.' % self.arch.name)
188  	        if self.prototype._arch is None:
189  	            self.prototype = self.prototype.with_arch(self.arch)
190  	
191  	        inst = copy.copy(self)
192  	        inst.state = state
193  	        inst.successors = successors
194  	        inst.ret_to = ret_to
195  	        inst.inhibit_autoret = False
196  	
197  	        # check to see if this is a syscall and if we should override its return value
198  	        if inst.is_syscall:
199  	            state.history.recent_syscall_count = 1
200  	
201  	        state._inspect(
202  	            'simprocedure',
203  	            BP_BEFORE,
204  	            simprocedure_name=inst.display_name,
205  	            simprocedure_addr=self.addr,
206  	            simprocedure=inst,
207  	            simprocedure_result=NO_OVERRIDE
208  	        )
209  	
210  	        r = state._inspect_getattr('simprocedure_result', NO_OVERRIDE)
211  	        if r is NO_OVERRIDE:
212  	            # get the arguments
213  	
214  	            # If the simprocedure is related to a Java function call the appropriate setup_args methos
215  	            # TODO: should we move this?
216  	            if self.is_java:
217  	                sim_args = self._setup_args(inst, state, arguments) #pylint:disable=assignment-from-no-return
218  	                self.use_state_arguments = False
219  	
220  	            # handle if this is a continuation from a return
221  	            elif inst.is_continuation:
222  	                if state.callstack.top.procedure_data is None:
223  	                    raise SimProcedureError("Tried to return to a SimProcedure in an inapplicable stack frame!")
224  	
225  	                saved_sp, sim_args, saved_local_vars, saved_lr, ideal_addr = state.callstack.top.procedure_data
226  	                if ideal_addr != inst.addr:
227  	                    raise SimShadowStackError("I can't emulate this consequence of stack smashing")
228  	                state.regs.sp = saved_sp
229  	                if saved_lr is not None:
230  	                    state.regs.lr = saved_lr
231  	                inst.arguments = sim_args
232  	                inst.use_state_arguments = True
233  	                inst.call_ret_expr = state.registers.load(state.arch.ret_offset, state.arch.bytes, endness=state.arch.register_endness)
234  	                for name, val in saved_local_vars:
235  	                    setattr(inst, name, val)
236  	            else:
237  	                if arguments is None:
238  	                    inst.use_state_arguments = True
239  	                    inst.arg_session = inst.cc.arg_session(inst.prototype.returnty)
240 B->	                    sim_args = [inst.cc.next_arg(inst.arg_session, ty).get_value(inst.state) for ty in inst.prototype.args]
241  	                    inst.arguments = sim_args
242  	                else:
243  	                    inst.use_state_arguments = False
244  	                    sim_args = arguments[:inst.num_args]
245  	                    inst.arguments = arguments
246  	                    inst.arg_session = 0
247  	
248  	            # run it
249  	            l.debug("Executing %s%s%s%s%s with %s, %s", *(inst._describe_me() + (sim_args, inst.kwargs)))
250  	            r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
251  	
252  	        state._inspect(
253  	            'simprocedure',
254  	            BP_AFTER,
255  	            simprocedure_result=r
256  	        )
257  	        r = state._inspect_getattr('simprocedure_result', r)
258  	
259  	        if inst.returns and inst.is_function and not inst.inhibit_autoret:
260  	            inst.ret(r)
261  	
262  	        return inst
(Pdb) p inst
<SimProcedure std::basic_istream<char, std::char_traits<char>>& std::operator>><char, std::char_traits<char>, std::allocator<char>>(std::basic_istream<char, std::char_traits<char>>, std::__cxx11::basic_string<std::basic_istream, char, std::allocator<char>>&) (stub)>
(Pdb) p inst.prototype.args
[struct std::basic_istream, string_t&]
(Pdb) p inst.prototype
(struct std::basic_istream, string_t&) -> struct std : : basic_istream std : :
```

I'll keep working on it when I have time, I'm mostly making this post so I don't forget what I saw.
