### ISSUE TITLE
 Unable to reach an address through symbolic execution

### ISSUE THREAD

**Issue by EudoraQR** [angr/angr#3275]
---

Hi,developer! I want to use symbolic execution to get all the constraints that need to go through to reach a certain address. When using the explore(find=xxx) function, the address is not found,but addresses that do not pass constraints can be found smoothly.

C coude:
````
#include<stdio.h>
int twice(int v) {
	return 2 * v;
}
void testme(int x, int y) {
        int z;
	z = twice(y);
	if (z == x) {
		if (x > y + 10)
			exit(-1);
			printf("ok");
	}
	else
	printf("no");
}
int main(int argc, char* argv[]){
	
	testme(argv[2],argv[3]);
	return 0;
}
````

using angr code :
````
import angr
import sys
import claripy

def main():
    argv1 = claripy.BVS("argv1", 100 * 8)
    argv2 = claripy.BVS("argv2", 100 * 8)
    project = angr.Project('testme_argv', load_options={"auto_load_libs": False})
    # initial_state = project.factory.entry_state()
    initial_state = project.factory.entry_state(args=["./testme_argv", claripy.BVS("argv1", 100 * 8), claripy.BVS("argv2", 100 * 8)])
    simulation = project.factory.simgr(initial_state)
    print_good_address =0x401070
    simulation.explore(find=print_good_address)
    Path_constrain_list=[]
    if simulation.found:
        solution_state = simulation.found[0]
        print(solution_state.history.jump_guards.hardcopy)
        for constrain in solution_state.history.jump_guards.hardcopy:
            if str(constrain)!="<Bool True>":
                Path_constrain_list.append(constrain)
        print(Path_constrain_list)

        print(solution_state.history.events.hardcopy)
        # print(solution_state.history.jumpkinds.hardcopy)

    else:
        raise Exception('Could not find the solution')  # 这是一个错误处理机制，也不是很懂，可以百度看看


if __name__ == '__main__':
    main()
````

results:
Traceback (most recent call last):
  File "E:/Code/xxx/find_SE.py", line 31, in <module>
    main()
  File "E:/Code/xxx/find_SE.py", line 27, in main
    raise Exception('Could not find the solution')  
Exception: Could not find the solution
[testme_argv.zip](https://github.com/angr/angr/files/8406566/testme_argv.zip)

**Comment by rhelmot** [comment]
Hi! There are a couple of problems in your code:

- Your code takes argv[2] and argv[3], but you are only providing argv[1] and argv[2]
- Your code directly passes argv[2] and argv[3] to testme, which expects ints, not char pointers

**Comment by EudoraQR** [comment]
I still get the same error after I modified the code
c code 
````
#include<stdio.h>
#include <string.h>
int twice(int v) {
	return 2 * v;
}
void testme(int x, int y) {
        int z;
	z = twice(y);
	if (z == x) {
		if (x > y + 10)
			exit(-1);
			printf("ok");
	}
	else
	printf("no");
}
int main(int argc, char* argv[]){
	if(strcmp(argv[1], "sjie") == 0) printf("equal");
	int x,y;
	testme(x,y);
	return 0;
}
````

using angr code
````
import angr
import sys
import claripy

def main():
    project = angr.Project('testme_argv', load_options={"auto_load_libs": False})
    # initial_state = project.factory.entry_state()
    initial_state = project.factory.entry_state(args=["./testme_argv", claripy.BVS("argv0", 100 * 8)])
    simulation = project.factory.simgr(initial_state)
    print_good_address =0x401090
    simulation.explore(find=print_good_address)
    Path_constrain_list=[]
    if simulation.found:
        solution_state = simulation.found[0]
        print(solution_state.history.jump_guards.hardcopy)
        for constrain in solution_state.history.jump_guards.hardcopy:
            if str(constrain)!="<Bool True>":
                Path_constrain_list.append(constrain)
        print(Path_constrain_list)

        print(solution_state.history.events.hardcopy)
        # print(solution_state.history.jumpkinds.hardcopy)

    else:
        raise Exception('Could not find the solution')


if __name__ == '__main__':
    main()

````

**Comment by rhelmot** [comment]
Now your code is accessing uninitialized variables, which is undefined behavior. You probably want `x = atoi(argv[1]); y = atoi(argv[2]);`?

**Comment by EudoraQR** [comment]
Thank you very much, the problem has been solved.I have a new doubt, what should I do if I want the function parameter to be initialized to a unique identifier(e.g.,arg0) when printing constraints.
My current results is
````
[<Bool strncmp_ret_7_64{UNINITIALIZED}[31:0] != 0x0>, <Bool ((if 0x7fffffffffffffff <= (if num_bytes_13_64 == 0x0 then 0x0 else (if num_bytes_13_64 == 0x1 then (0x0 .. 208 + argv1_1_8) else 0x0)) then 127 else 0)
````
I want the results
````
[<Bool arg0 != 0x0>,<Bool arg1....>
````

**Comment by ltfish** [comment]
I feel the only solution is manually parsing the list of constraints and generate properly named new constraints. You can also pre-populate the stack region in the initial state with BVS of your desired names so that you will see them in the final list of constraints.
