### ISSUE TITLE
Crash on multiple segments mapped at same address

### ISSUE THREAD

**Issue by bjorn3** [angr/angr#3295]
For context this happens on one of the tasks from a practice version of a CTF. This runs till the end of the month. You can download the executable from https://nl.cscg.live/tasks/backdoor. Ghidra doesn't have any problems with this executable by the way. I think the correct behavior is for the later segment to override all pages it (partially) covers from the earlier segment.

```
Exception while running job "Loading file":
Traceback (most recent call last):
  File "angrmanagement/data/instance.py", line 284, in _worker
  File "angrmanagement/data/jobs/job.py", line 45, in run
  File "angrmanagement/data/jobs/loading.py", line 60, in _run
  File "cle/loader.py", line 133, in __init__
  File "cle/loader.py", line 668, in _internal_load
  File "cle/loader.py", line 850, in _load_object_isolated
  File "cle/backends/elf/elf.py", line 149, in __init__
  File "cle/backends/elf/elf.py", line 741, in __register_segments
  File "cle/backends/elf/elf.py", line 472, in _load_segment
  File "cle/memory.py", line 186, in add_backer
ValueError: Address 0x4000 is already backed!
```

```
$ readelf --segments malicious_ping
Elf file type is DYN (Shared object file)
Entry point 0x6090
There are 16 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000012d8 0x00000000000012d8  R      0x8
  INTERP         0x0000000000001318 0x0000000000001318 0x0000000000001318
                 0x000000000000001c 0x000000000000001c  R      0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000031e8 0x00000000000031e8  R      0x1000
  LOAD           0x0000000000004000 0x0000000000004000 0x0000000000004000
                 0x000000000000a2d1 0x000000000000a2d1  R E    0x1000
  LOAD           0x000000000000f000 0x000000000000f000 0x000000000000f000
                 0x0000000000002fb8 0x0000000000002fb8  R      0x1000
  LOAD           0x0000000000012a98 0x0000000000013a98 0x0000000000013a98
                 0x0000000000000868 0x0000000000001a20  RW     0x1000
  LOAD           0x0000000000015000 0x0000000000004000 0x0000000000004000
                 0x000000000000a2e0 0x000000000000a2e0   WE    0x8
  LOAD           0x0000000000020000 0x0000000000040000 0x0000000000040000
                 0x000000000003ec60 0x000000000003ec60   W     0x8
  LOAD           0x000000000005f000 0x00000000000df000 0x00000000000df000
                 0x0000000000001000 0x0000000000001000   W     0x8
  LOAD           0x0000000000060000 0x0000000000160000 0x0000000000160000
                 0x00000000000bac20 0x00000000000bac20  R      0x1000
  DYNAMIC        0x0000000000012aa8 0x0000000000013aa8 0x0000000000013aa8
                 0x00000000000001e0 0x00000000000001e0  RW     0x8
  NOTE           0x0000000000060000 0x0000000000160000 0x0000000000160000
                 0x0000000000000084 0x0000000000000084  R      0x8
  GNU_PROPERTY   0x0000000000060000 0x0000000000160000 0x0000000000160000
                 0x0000000000000040 0x0000000000000040  R      0x8
  GNU_EH_FRAME   0x00000000000111b0 0x00000000000111b0 0x00000000000111b0
                 0x00000000000001bc 0x00000000000001bc  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x0000000000012a98 0x0000000000013a98 0x0000000000013a98
                 0x0000000000000568 0x0000000000000568  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .interp 
   02     .interp .gnu.hash .gnu.version_r .rela.plt 
   03     .init .plt .text .fini 
   04     .rodata .eh_frame_hdr .eh_frame 
   05     .init_array .fini_array .dynamic .got .data .bss 
   06     
   07     
   08     
   09     .note.gnu.property .note.gnu.build-id .note.ABI-tag .dynsym .dynstr .gnu.version .rela.dyn 
   10     .dynamic 
   11     .note.gnu.property .note.gnu.build-id .note.ABI-tag 
   12     .note.gnu.property 
   13     .eh_frame_hdr 
   14     
   15     .init_array .fini_array .dynamic .got 
```

Angr management downloaded from https://github.com/angr/angr-management/releases/tag/nightly-20220401.1

**Comment by rhelmot** [comment]
Your binary now loads just fine. Thanks for the report!

**Comment by OlfillasOdikno** [comment]
@rhelmot Is there some way to hide this issue since this is part of an ongoing competition.
