### ISSUE TITLE
`test_serialization.test_serialization` is failing on Ubuntu 20.04/Python 3.8 in CI

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr#3348]
```
======================================================================
ERROR: test_serialization.test_serialization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/archinfo/archinfo/build/src/angr/tests/test_serialization.py", line 98, in test_serialization
    internaltest_cfgfast(p)
  File "/__w/archinfo/archinfo/build/src/angr/tests/test_serialization.py", line 46, in internaltest_cfgfast
    cfg2 = pickle.load(state)
  File "/__w/archinfo/archinfo/build/virtualenv/lib/python3.8/site-packages/networkx/classes/reportviews.py", line 1290, in __setstate__
    self._adjdict = G._pred if hasattr(G, "pred") else G._adj
AttributeError: 'DiGraph' object has no attribute '_adj'

```

**Comment by rhelmot** [comment]
Seems to be new as of networkx 2.8.1: https://github.com/networkx/networkx/issues/5655
