### ISSUE TITLE
KeyError: 1L in __tls_get_addr.py

### ISSUE THREAD

**Issue by Phasip** [angr/angr#336]
Code is basically:

```
	state = proj.factory.call_state(func, result_addr, matrix_size, data, ret_addr=return_addr, add_options=simuvex.o.unicorn)
	state.options.discard("LAZY_SOLVES")
	at = len(data)-1
	for (min_val,max_val) in constraints:
		state.add_constraints(data[at:at-7] >= min_val)
		state.add_constraints(data[at:at-7] <= max_val)
		at = at - 8
	pg = proj.factory.path_group(state)
	pg.explore(find=return_addr)
```

Error I get is:

```
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    pg.explore(find=return_addr)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/path_group.py", line 806, in explore
    n=n)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/path_group.py", line 830, in run
    return self.step(n=n, step_func=step_func, until=until_func, stash=stash)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/path_group.py", line 520, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/path_group.py", line 311, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/path_group.py", line 208, in _one_path_step
    successors = a.step(**kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/path.py", line 202, in step
    self._make_successors(throw=throw)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/path.py", line 234, in _make_successors
    self._run = self._project.factory.successors(self.state, **self._run_args)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/factory.py", line 78, in successors
    r = engine.process(state, inline=inline,**kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/engines.py", line 143, in process
    force_addr=force_addr)
  File "/usr/local/lib/pypy2.7/dist-packages/simuvex/engines/procedure.py", line 34, in process
    force_addr=force_addr)
  File "/usr/local/lib/pypy2.7/dist-packages/simuvex/engines/engine.py", line 44, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/angr/engines.py", line 173, in _process
    return super(SimEngineHook, self)._process(state, successors, procedure, **kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/simuvex/engines/procedure.py", line 71, in _process
    procedure.execute(state, successors, ret_to=ret_to)
  File "/usr/local/lib/pypy2.7/dist-packages/simuvex/s_procedure.py", line 137, in execute
    r = run_func(*sim_args, **self.kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/simuvex/procedures/ld-linux-x86-64___so___2/__tls_get_addr.py", line 13, in run
    return self.state.posix.tls_modules[mod_id] + offset
KeyError: 1L
```

If i remove the line 
`	state.options.discard("LAZY_SOLVES")`
then i get no crash (before I exit the script for not terminating)

Happens with both python and pypy (I guess that's expected) - angr installed via pip yesterday.

**Comment by rhelmot** [comment]
Can you include the binary you're running on and a precise script to
reproduce this? This is probably a loading bug.

**Comment by Phasip** [comment]
Hey!
Thanks for looking at this, attached is the binary and script.
time until crash is ~30 sec on my laptop.

[angr_crash.tar.gz](https://github.com/angr/angr/files/724530/angr_crash.tar.gz)

**Comment by Phasip** [comment]
I also tried on the latest angr installed via angr-dev, same error, a bit longer runtime this time (might be other processes interfering)

```
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    (data,res,state) = run_func(len(matrix),matrix)
  File "main.py", line 65, in run_func
    pg.explore(find=return_addr)
  File "/vagrant/angr-dev/angr/angr/path_group.py", line 820, in explore
    n=n)
  File "/vagrant/angr-dev/angr/angr/path_group.py", line 844, in run
    return self.step(n=n, step_func=step_func, until=until_func, stash=stash)
  File "/vagrant/angr-dev/angr/angr/path_group.py", line 534, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/vagrant/angr-dev/angr/angr/path_group.py", line 318, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/vagrant/angr-dev/angr/angr/path_group.py", line 208, in _one_path_step
    successors = a.step(**kwargs)
  File "/vagrant/angr-dev/angr/angr/path.py", line 202, in step
    self._make_successors(throw=throw)
  File "/vagrant/angr-dev/angr/angr/path.py", line 234, in _make_successors
    self._run = self._project.factory.successors(self.state, **self._run_args)
  File "/vagrant/angr-dev/angr/angr/factory.py", line 78, in successors
    r = engine.process(state, inline=inline,**kwargs)
  File "/vagrant/angr-dev/angr/angr/engines.py", line 143, in process
    force_addr=force_addr)
  File "/vagrant/angr-dev/simuvex/simuvex/engines/procedure.py", line 34, in process
    force_addr=force_addr)
  File "/vagrant/angr-dev/simuvex/simuvex/engines/engine.py", line 44, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/vagrant/angr-dev/angr/angr/engines.py", line 173, in _process
    return super(SimEngineHook, self)._process(state, successors, procedure, **kwargs)
  File "/vagrant/angr-dev/simuvex/simuvex/engines/procedure.py", line 71, in _process
    procedure.execute(state, successors, ret_to=ret_to)
  File "/vagrant/angr-dev/simuvex/simuvex/s_procedure.py", line 137, in execute
    r = run_func(*sim_args, **self.kwargs)
  File "/vagrant/angr-dev/simuvex/simuvex/procedures/ld-linux-x86-64___so___2/__tls_get_addr.py", line 13, in run
    return self.state.posix.tls_modules[mod_id] + offset
KeyError: 1L
```

```
real	1m32.997s
user	1m13.128s
sys	0m7.764s
```

**Comment by Phasip** [comment]
One workaround seems to be to compile with `-static` this results in no found paths though
```
pypy main.py 
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    (data,res,state) = run_func(len(matrix),matrix)
  File "main.py", line 67, in run_func
    res = pg.found[0].state.memory.load(result_addr,result_len)
IndexError: list index out of range
```

One question I realized was that if I have access to the source, is there any compiler flags that will make angr angrier (or should I say happy?)

**Comment by ltfish** [comment]
I believe this is a problem in how `__tls_get_addr` is implemented. We will look into it.

**Comment by amtelekom** [comment]
Stumbled upon the same exception with multiple small binaries.
I've noticed that whenever this exception occurs for me, there is always a single path in the active stash with its current Position at a non-code location:
```
> pathg.active
[<Path with 10958 runs (at 0x10b6ac8)>,
 <Path with 10958 runs (at 0x10b6ac8)>,
 <Path with 10958 runs (at 0x10b6ac8)>,
 <Path with 10958 runs (at 0x10b6ac8)>,
 <Path with 10958 runs (at 0x70001b0)>]
```
Stepping this path causes the exception with exactly the same trace as above (except for my calling code), the others are fine.
There are no instructions loaded at that address, in fact, there's nothing at that address at all:
```
> badpath.state.se.any_n_int( badpath.state.memory.mem.load_bytes(0x70001b0, 0x10)[0][0].object ,10)
 [0L]
```
Is this just an effect of the path currently executing the Sim Procedure or related to this bug?

**Comment by rhelmot** [comment]
That's probably the location of the `__tls_get_addr` simprocedure. Verify via `project._sim_procedures[0x70001b0]`
