### ISSUE TITLE
Protobuf generated code needs update

### ISSUE THREAD

**Issue by mborgerson** [angr/angr#3360]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/mdecangr/__init__.py", line 1, in <module>
    from .service import AngrService
  File "/usr/local/lib/python3.8/dist-packages/mdecangr/service.py", line 4, in <module>
    import angr
  File "/usr/local/lib/python3.8/dist-packages/angr/__init__.py", line 22, in <module>
    from .utils.formatting import setup_terminal
  File "/usr/local/lib/python3.8/dist-packages/angr/utils/__init__.py", line 5, in <module>
    from . import enums_conv
  File "/usr/local/lib/python3.8/dist-packages/angr/utils/enums_conv.py", line 6, in <module>
    from ..protos.primitives_pb2 import Edge
  File "/usr/local/lib/python3.8/dist-packages/angr/protos/__init__.py", line 10, in <module>
    from . import primitives_pb2
  File "/usr/local/lib/python3.8/dist-packages/angr/protos/primitives_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by fmagin** [comment]
This also affects the PyPI release, so this currently completely breaks angr

**Comment by twizmwazin** [comment]
We should make sure the protobuf version is pinned, since I believe the pb2.py files are tied to the specific version of protoc being used.

**Comment by twizmwazin** [comment]
WIll merge https://github.com/angr/angr/pull/3364 once it passes CI. There is a scheduled release tomorrow and it'll then be fixed on PyPI.
