### ISSUE TITLE
SimCCO32LinuxSyscall error

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#3401]
angrop encountered a weird error when trying to symbolic execute some random instructions
~~~
Traceback (most recent call last):
  File "/home/kylebot/src/angr-dev/angrop/angrop/gadget_analyzer.py", line 59, in analyze_gadget
    final_state = rop_utils.step_to_unconstrained_successor(self.project, state=init_state)
  File "/home/kylebot/src/angr-dev/angrop/angrop/rop_utils.py", line 217, in step_to_unconstrained_successor
    return step_to_unconstrained_successor(project, succ.flat_successors[0],
  File "/home/kylebot/src/angr-dev/angrop/angrop/rop_utils.py", line 210, in step_to_unconstrained_successor
    succ = project.factory.successors(state)
  File "/home/kylebot/src/angr-dev/angr/angr/factory.py", line 60, in successors
    return self.default_engine.process(*args, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/engines/vex/light/slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/engines/engine.py", line 158, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/engines/failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/engines/syscall.py", line 38, in process_successors
    return self.process_procedure(state, successors, sys_procedure, **kwargs)
  File "/home/kylebot/src/angr-dev/angr/angr/engines/procedure.py", line 37, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to, arguments=arguments)
  File "/home/kylebot/src/angr-dev/angr/angr/sim_procedure.py", line 242, in execute
    sim_args = [inst.cc.next_arg(inst.arg_session, ty).get_value(inst.state) for ty in inst.prototype.args]
  File "/home/kylebot/src/angr-dev/angr/angr/sim_procedure.py", line 242, in <listcomp>
    sim_args = [inst.cc.next_arg(inst.arg_session, ty).get_value(inst.state) for ty in inst.prototype.args]
  File "/home/kylebot/src/angr-dev/angr/angr/calling_conventions.py", line 666, in next_arg
    raise ValueError(f"{self} doesn't know how to store large types. Consider overriding"
ValueError: <SimCCO32LinuxSyscall> doesn't know how to store large types. Consider overriding next_arg to implement its ABI logic
~~~

**Comment by rhelmot** [comment]
What syscall is this?

**Comment by Kyle-Kyle** [comment]
~~~
[nav] In [11]: init_state.block().pp()
3fdff190  sw      $s1, [$sp]
3fdff194  addiu   $v0, $zero, 0x109e
3fdff198  syscall 

[ins] In [12]: init_state.block().vex.pp()
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32

   00 | ------ IMark(0x3fdff190, 4, 0) ------
   01 | t2 = GET:I32(sp)
   02 | t1 = Add32(t2,0x00000018)
   03 | t3 = GET:I32(s1)
   04 | STbe(t1) = t3
   05 | ------ IMark(0x3fdff194, 4, 0) ------
   06 | PUT(v0) = 0x0000109e
   07 | ------ IMark(0x3fdff198, 4, 0) ------
   NEXT: PUT(pc) = 0x3fdff19c; Ijk_Sys_syscall
}
~~~
I'm not quite sure what syscall this is. I'll keep digging. BTW, the difference between the disassembly and the vex code is caused by https://github.com/angr/angr/issues/3403

**Comment by rhelmot** [comment]
fadvise64 it seems

**Comment by rhelmot** [comment]
Notes for myself whenever I get back to this:

- several syscall ABIs will pass 64 bit values in pairs of 32 bit registers. fewer will require that the syscall pair be aligned, so e.g. on fadvise64 it would be r0, r2:r3, ...
- mips o32 will pass additional syscall arguments on the stack
- I don't know whether it will enforce slot alignment for 64 bit values passed on the stack! does this even happen ever?
