### ISSUE TITLE
Unhandled ClaripyTypeError

### ISSUE THREAD

**Issue by yaroslav-o** [angr/angr#3407]
**Describe the bug.**

Suggested fix: https://github.com/angr/angr/pull/3406

claripy may throw `claripy.errors.ClaripyTypeError` and it may completely break analysis. Re-raising it as an expected exception `SimError` gracefully fails only part of analysis.

Discovered when processing some invalid (not instructions) data in a binary. Minimal reproduction example (cut from a large binary) is as follows:

```
import angr
import io

if __name__ == "__main__":
    binary = io.BytesIO(
        b'\x00\x00\x06\x41\x00\x00\x00\x00\x00\x40\x02\x40\x24\x00\x04\x00'
        b'\x45\x76\x65\x6E\x74\x20\x73\x65\x71\x3D\x25\x64\x20\x69\x6E\x64'
        b'\x65\x78\x3D\x25\x64\x20\x73\x74\x6F\x72\x65\x64\x21\x00\x45\x76'
        b'\x65\x6E\x74\x20\x6C\x6F\x67\x20\x77\x72\x69\x74\x65\x20\x71\x75'
        b'\x65\x75\x65\x20\x66\x75\x6C\x6C\x2C\x20\x64\x72\x6F\x70\x69\x6E'
        b'\x67\x20\x65\x76\x65\x6E\x74\x00\x45\x76\x65\x6E\x74\x20\x6C\x6F'
        b'\x67\x20\x69\x73\x20\x65\x6D\x70\x74\x79\x00\x45')

    project = angr.Project(
        binary,
        load_options={'auto_load_libs': False},
        main_opts={'backend': 'blob', 'arch': 'ARMCortexM', 'base_addr': 0x40000, 'entry_point': 0x40000})

    project.analyses.CFGFast()
```

Perhaps there is a root cause that needs to be fixed, but as this part of binary is not executable instructions - silencing it should be OK.
For reference, adding stacktrace, capstone disassembly, and IRSB dump. The failed statement in IRSB is at index 59.

Stacktrace:
```
Traceback (most recent call last):
  File "C:\main_dev.py", line 19, in <module>
    project.analyses.CFGFast()
  File "C:\angr\analyses\analysis.py", line 138, in __call__
    r = w(*args, **kwargs)
  File "C:\angr\analyses\analysis.py", line 122, in wrapper
    oself.__init__(*args, **kwargs)
  File "C:\angr\analyses\cfg\cfg_fast.py", line 757, in __init__
    self._analyze()
  File "C:\angr\analyses\forward_analysis\forward_analysis.py", line 236, in _analyze
    self._analysis_core_baremetal()
  File "C:\angr\analyses\forward_analysis\forward_analysis.py", line 383, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "C:\angr\analyses\forward_analysis\forward_analysis.py", line 401, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "C:\angr\analyses\cfg\cfg_fast.py", line 1268, in _get_successors
    jobs = self._scan_block(job)
  File "C:\angr\analyses\cfg\cfg_fast.py", line 1638, in _scan_block
    entries = self._scan_irsb(cfg_job, current_func_addr)
  File "C:\angr\analyses\cfg\cfg_fast.py", line 1886, in _scan_irsb
    new_jobs = self._create_jobs(target, jumpkind, function_addr, irsb, addr, cfg_node, ins_addr,
  File "C:\angr\analyses\cfg\cfg_fast.py", line 2062, in _create_jobs
    jobs += self._create_job_call(addr, irsb, cfg_node, stmt_idx, ins_addr, current_function_addr,
  File "C:\angr\analyses\cfg\cfg_fast.py", line 2100, in _create_job_call
    successors = self._simulate_block_with_resilience(tmp_state)
  File "C:\angr\analyses\cfg\cfg_fast.py", line 2226, in _simulate_block_with_resilience
    successors = self.project.factory.successors(state, skip_stmts=stmt_idx)
  File "C:\angr\factory.py", line 60, in successors
    return self.default_engine.process(*args, **kwargs)
  File "C:\angr\engines\vex\light\slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "C:\angr\engines\engine.py", line 159, in process
    self.process_successors(self.successors, **kwargs)
  File "C:\angr\engines\failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "C:\angr\engines\syscall.py", line 18, in process_successors
    return super().process_successors(successors, **kwargs)
  File "C:\angr\engines\hook.py", line 54, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "C:\angr\engines\unicorn.py", line 303, in process_successors
    return super().process_successors(successors, **kwargs)
  File "C:\angr\engines\soot\engine.py", line 65, in process_successors
    return super().process_successors(successors, **kwargs)
  File "C:\angr\engines\vex\heavy\heavy.py", line 151, in process_successors
    self.handle_vex_block(irsb)
  File "C:\angr\engines\vex\heavy\super_fastpath.py", line 24, in handle_vex_block
    super().handle_vex_block(irsb)
  File "C:\angr\engines\vex\light\slicing.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "C:\angr\engines\vex\heavy\actions.py", line 30, in handle_vex_block
    super().handle_vex_block(irsb)
  File "C:\angr\engines\vex\heavy\inspect.py", line 45, in handle_vex_block
    super().handle_vex_block(irsb)
  File "C:\angr\engines\vex\light\light.py", line 446, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "C:\angr\engines\vex\light\slicing.py", line 30, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "C:\angr\engines\vex\heavy\inspect.py", line 40, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "C:\angr\engines\vex\light\resilience.py", line 37, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "C:\angr\engines\vex\heavy\heavy.py", line 216, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "C:\angr\engines\vex\light\light.py", line 51, in _handle_vex_stmt
    handler(stmt)
  File "C:\angr\engines\vex\light\light.py", line 282, in _handle_vex_stmt_LoadG
    self._perform_vex_stmt_LoadG(
  File "C:\angr\engines\vex\claripy\datalayer.py", line 66, in _perform_vex_stmt_LoadG
    super()._perform_vex_stmt_LoadG(addr, alt, guard, dst, cvt, end)
  File "C:\angr\engines\vex\light\light.py", line 345, in _perform_vex_stmt_LoadG
    ite_result = self._perform_vex_stmt_LoadG_ite(guard, cvt_result, alt)
  File "C:\angr\engines\vex\light\light.py", line 291, in _perform_vex_stmt_LoadG_ite
    def _perform_vex_stmt_LoadG_ite(self, *a, **kw): return self. _perform_vex_expr_ITE(*a, **kw)
  File "C:\angr\engines\vex\heavy\actions.py", line 63, in _perform_vex_expr_ITE
    result = super()._perform_vex_expr_ITE(*exprs)
  File "C:\angr\engines\vex\claripy\datalayer.py", line 107, in _perform_vex_expr_ITE
    return claripy.If(cond != 0, ifTrue, ifFalse)
  File "C:\claripy\ast\bool.py", line 99, in If
    raise ClaripyTypeError("sized arguments to If must have the same length")
claripy.errors.ClaripyTypeError: sized arguments to If must have the same length

Process finished with exit code 1
```

Capstone disassembly:
```
0x4000c:	movs	r4, r4
0x4000e:	movs	r4, r0
0x40010:	strb	r5, [r0, #0x19]
0x40012:	ldr	r5, [r4, #0x64]
0x40014:	movs	r0, #0x74
0x40016:	str	r3, [r6, #0x54]
0x40018:	subs	r5, #0x71
0x4001a:	str	r5, [r4, #0x40]
0x4001c:	ldr	r0, [r4, #0x10]
0x4001e:	str	r6, [r5, #0x44]
0x40020:	ldrb	r5, [r4, #1]
0x40022:	movs	r5, #0x3d
0x40024:	movs	r0, #0x64
0x40026:	strb	r3, [r6, #0x11]
0x40028:	strb	r7, [r5, #9]
0x4002a:	str	r5, [r4, #0x44]
0x4002c:	movs	r1, r4
0x4002e:	strb	r5, [r0, #0x19]
0x40030:	ldr	r5, [r4, #0x64]
0x40032:	movs	r0, #0x74
0x40034:	ldr	r4, [r5, #0x74]
0x40036:	movs	r0, #0x67
0x40038:	strb	r7, [r6, #9]
0x4003a:	strb	r1, [r5, #0x11]
0x4003c:	movs	r0, #0x65
0x4003e:	strb	r1, [r6, #0x15]
0x40040:	strb	r5, [r4, #0x15]
0x40042:	movs	r0, #0x65
0x40044:	strb	r6, [r4, #0x15]
0x40046:	ldr	r4, [r5, #0x44]
0x40048:	movs	r0, #0x2c
0x4004a:	strb	r4, [r4, #9]
0x4004c:	strb	r7, [r5, #1]
0x4004e:	ldr	r1, [r5, #0x64]
0x40050:	movs	r0, #0x67
0x40052:	strb	r5, [r4, #0x19]
0x40054:	ldr	r5, [r4, #0x64]
0x40056:	lsls	r4, r6, #1
0x40058:	strb	r5, [r0, #0x19]
0x4005a:	ldr	r5, [r4, #0x64]
0x4005c:	movs	r0, #0x74
0x4005e:	ldr	r4, [r5, #0x74]
```

IRSB:
```
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I32 t10:Ity_I32 t11:Ity_I32 t12:Ity_I32 t13:Ity_I32 t14:Ity_I1 t15:Ity_I32 t16:Ity_I32 t17:Ity_I32 t18:Ity_I32 t19:Ity_I32 t20:Ity_I32 t21:Ity_I32 t22:Ity_I32 t23:Ity_I32 t24:Ity_I32 t25:Ity_I32 t26:Ity_I32 t27:Ity_I32 t28:Ity_I32 t29:Ity_I32 t30:Ity_I32 t31:Ity_I1 t32:Ity_I32 t33:Ity_I32 t34:Ity_I32 t35:Ity_I1 t36:Ity_I32 t37:Ity_I32 t38:Ity_I32 t39:Ity_I32 t40:Ity_I8 t41:Ity_I1 t42:Ity_I32 t43:Ity_I32 t44:Ity_I32 t45:Ity_I32 t46:Ity_I32 t47:Ity_I32 t48:Ity_I32 t49:Ity_I1 t50:Ity_I32 t51:Ity_I32 t52:Ity_I32 t53:Ity_I32 t54:Ity_I1 t55:Ity_I32 t56:Ity_I32 t57:Ity_I32 t58:Ity_I8 t59:Ity_I1 t60:Ity_I32 t61:Ity_I32 t62:Ity_I32 t63:Ity_I8 t64:Ity_I1 t65:Ity_I32 t66:Ity_I32 t67:Ity_I32 t68:Ity_I32 t69:Ity_I32 t70:Ity_I32 t71:Ity_I32 t72:Ity_I32 t73:Ity_I32 t74:Ity_I32 t75:Ity_I32 t76:Ity_I32 t77:Ity_I32 t78:Ity_I32 t79:Ity_I32 t80:Ity_I32 t81:Ity_I32 t82:Ity_I1 t83:Ity_I32 t84:Ity_I32 t85:Ity_I32 t86:Ity_I32 t87:Ity_I8 t88:Ity_I1 t89:Ity_I32 t90:Ity_I32 t91:Ity_I32 t92:Ity_I32 t93:Ity_I1 t94:Ity_I32 t95:Ity_I32 t96:Ity_I32 t97:Ity_I32 t98:Ity_I32 t99:Ity_I32 t100:Ity_I32 t101:Ity_I32 t102:Ity_I32 t103:Ity_I32 t104:Ity_I32 t105:Ity_I32 t106:Ity_I32 t107:Ity_I32 t108:Ity_I32 t109:Ity_I32 t110:Ity_I1 t111:Ity_I32 t112:Ity_I32 t113:Ity_I32 t114:Ity_I32 t115:Ity_I32 t116:Ity_I32 t117:Ity_I32 t118:Ity_I32 t119:Ity_I32 t120:Ity_I8 t121:Ity_I1 t122:Ity_I32 t123:Ity_I32 t124:Ity_I32 t125:Ity_I32 t126:Ity_I32 t127:Ity_I32 t128:Ity_I32 t129:Ity_I32 t130:Ity_I32 t131:Ity_I32 t132:Ity_I32 t133:Ity_I32 t134:Ity_I32 t135:Ity_I32 t136:Ity_I1 t137:Ity_I32 t138:Ity_I32 t139:Ity_I32 t140:Ity_I32 t141:Ity_I32 t142:Ity_I32 t143:Ity_I32 t144:Ity_I32 t145:Ity_I32 t146:Ity_I32 t147:Ity_I32 t148:Ity_I1 t149:Ity_I1

   00 | ------ IMark(0x4000c, 4, 0) ------
   01 | t7 = GET:I32(cc_op)
   02 | t8 = GET:I32(cc_dep1)
   03 | t9 = GET:I32(cc_dep2)
   04 | t10 = GET:I32(cc_ndep)
   05 | t11 = armg_calculate_condition(t7,t8,t9,t10):Ity_I32
   06 | t13 = GET:I32(r0)
   07 | t14 = CmpNE32(t11,0x00000000)
   08 | t12 = ITE(t14,0x00000000,t13)
   09 | PUT(r0) = t12
   10 | ------ IMark(0x40010, 0, 0) ------
   11 | ------ IMark(0x40010, 4, 0) ------
   12 | ------ IMark(0x40014, 4, 0) ------
   13 | t22 = GET:I32(cc_op)
   14 | t23 = Or32(t22,0x00000060)
   15 | t24 = GET:I32(cc_dep1)
   16 | t25 = GET:I32(cc_dep2)
   17 | t26 = GET:I32(cc_ndep)
   18 | t27 = armg_calculate_condition(t23,t24,t25,t26):Ity_I32
   19 | t28 = GET:I32(r3)
   20 | t29 = Sub32(t28,0x00000074)
   21 | t30 = GET:I32(r2)
   22 | t31 = CmpNE32(t27,0x00000000)
   23 | t32 = if (t31) ILGop_8Uto32(LDle(t29)) else t30
   24 | t33 = ITE(t31,t29,t28)
   25 | PUT(pc) = 0x00040018
   26 | ------ IMark(0x40018, 4, 0) ------
   27 | t34 = GET:I32(r5)
   28 | t35 = t31
   29 | if (t35) STle(t34) = t33
   30 | t36 = Sub32(t34,0x00000d71)
   31 | t37 = ITE(t31,t36,t34)
   32 | PUT(pc) = 0x0004001c
   33 | ------ IMark(0x4001c, 4, 0) ------
   34 | t38 = GET:I32(lr)
   35 | t39 = GET:I32(r6)
   36 | t40 = 32to8(t39)
   37 | t41 = t31
   38 | if (t41) STle(t38) = t40
   39 | t42 = Sub32(t38,0x00000920)
   40 | t43 = ITE(t31,t42,t38)
   41 | PUT(lr) = t43
   42 | PUT(pc) = 0x00040020
   43 | ------ IMark(0x40020, 4, 0) ------
   44 | t44 = Or32(t22,0x00000020)
   45 | t45 = armg_calculate_condition(t44,t24,t25,t26):Ity_I32
   46 | t46 = GET:I32(sp)
   47 | t47 = Sub32(t46,0x00000865)
   48 | t48 = GET:I32(r7)
   49 | t49 = CmpNE32(t45,0x00000000)
   50 | t50 = if (t49) ILGop_Ident32(LDle(t47)) else t48
   51 | PUT(r7) = t50
   52 | t51 = ITE(t49,t47,t46)
   53 | PUT(sp) = t51
   54 | PUT(pc) = 0x00040024
   55 | ------ IMark(0x40024, 4, 0) ------
   56 | t52 = Or32(t22,0x00000070)
   57 | t53 = armg_calculate_condition(t52,t24,t25,t26):Ity_I32
   59 | t55 = if (t54) ILGop_8Uto32(LDle(t33)) else t54                   <------ FAILS HERE
   58 | t54 = CmpNE32(t53,0x00000000)
   60 | t56 = Sub32(t33,0x00000064)
   61 | t57 = ITE(t54,t56,t33)
   62 | PUT(r3) = t57
   63 | PUT(pc) = 0x00040028
   64 | ------ IMark(0x40028, 4, 0) ------
   65 | t58 = 32to8(t50)
   66 | t59 = t31
   67 | if (t59) STle(t59) = t58
   68 | t60 = Sub32(t37,0x0000026f)
   69 | t61 = ITE(t31,t60,t37)
   70 | PUT(pc) = 0x0004002c
   71 | ------ IMark(0x4002c, 4, 0) ------
   72 | t62 = GET:I32(r0)
   73 | PUT(r5) = t61
   74 | t63 = 32to8(t62)
   75 | t64 = t54
   76 | if (t64) STle(t61) = t63
   77 | ------ IMark(0x40030, 4, 0) ------
   78 | t65 = GET:I32(r4)
   79 | t66 = Shl32(t61,0x04)
   80 | t67 = Shr32(t61,0x1c)
   81 | t68 = Or32(t67,t66)
   82 | t69 = Sub32(t68,t65)
   83 | t70 = ITE(t49,t69,t39)
   84 | t71 = ITE(t49,0x00000002,t22)
   85 | PUT(cc_op) = t71
   86 | t72 = ITE(t49,t68,t24)
   87 | PUT(cc_dep1) = t72
   88 | t73 = ITE(t49,t65,t25)
   89 | PUT(cc_dep2) = t73
   90 | t74 = ITE(t49,0x00000000,t26)
   91 | PUT(cc_ndep) = t74
   92 | ------ IMark(0x40034, 4, 0) ------
   93 | t75 = Or32(t71,0x00000020)
   94 | t76 = armg_calculate_condition(t75,t72,t73,t74):Ity_I32
   95 | t77 = GET:I32(r12)
   96 | t78 = Shl32(t77,0x02)
   97 | t79 = Shr32(t77,0x1e)
   98 | t80 = Or32(t79,t78)
   99 | t81 = Sub32(t80,t50)
   100 | t82 = CmpNE32(t76,0x00000000)
   101 | t83 = ITE(t82,t81,t70)
   102 | PUT(r6) = t83
   103 | PUT(pc) = 0x00040038
   104 | ------ IMark(0x40038, 4, 0) ------
   105 | t84 = Or32(t71,0x00000070)
   106 | t85 = armg_calculate_condition(t84,t72,t73,t74):Ity_I32
   107 | t86 = GET:I32(r9)
   108 | t87 = t58
   109 | t88 = CmpNE32(t85,0x00000000)
   110 | if (t88) STle(t86) = t87
   111 | t89 = Sub32(t86,0x00000277)
   112 | t90 = ITE(t88,t89,t86)
   113 | PUT(r9) = t90
   114 | PUT(pc) = 0x0004003c
   115 | ------ IMark(0x4003c, 4, 0) ------
   116 | t91 = GET:I32(r1)
   117 | t92 = Sub32(t91,0x00000065)
   118 | t93 = t88
   119 | t94 = if (t93) ILGop_8Uto32(LDle(t92)) else t55
   120 | PUT(r2) = t94
   121 | t95 = ITE(t88,t92,t91)
   122 | PUT(r1) = t95
   123 | ------ IMark(0x40040, 4, 0) ------
   124 | t96 = Shl32(t61,0x16)
   125 | t97 = Shr32(t61,0x0a)
   126 | t98 = Or32(t97,t96)
   127 | t99 = Sub32(t98,t61)
   128 | t100 = ITE(t82,t99,t50)
   129 | PUT(r7) = t100
   130 | ------ IMark(0x40044, 0, 0) ------
   131 | ------ IMark(0x40044, 4, 0) ------
   132 | ------ IMark(0x40048, 4, 0) ------
   133 | t101 = GET:I32(cc_op)
   134 | t102 = Or32(t101,0x00000070)
   135 | t103 = GET:I32(cc_dep1)
   136 | t104 = GET:I32(cc_dep2)
   137 | t105 = GET:I32(cc_ndep)
   138 | t106 = armg_calculate_condition(t102,t103,t104,t105):Ity_I32
   139 | t107 = GET:I32(r4)
   140 | t108 = Sub32(0x0000002c,t107)
   141 | t109 = GET:I32(r2)
   142 | t110 = CmpNE32(t106,0x00000000)
   143 | t111 = ITE(t110,t108,t109)
   144 | PUT(r2) = t111
   145 | ------ IMark(0x4004c, 0, 0) ------
   146 | ------ IMark(0x4004c, 4, 0) ------
   147 | ------ IMark(0x40050, 4, 0) ------
   148 | t112 = GET:I32(cc_op)
   149 | t113 = Or32(t112,0x00000070)
   150 | t114 = GET:I32(cc_dep1)
   151 | t115 = GET:I32(cc_dep2)
   152 | t116 = GET:I32(cc_ndep)
   153 | t117 = armg_calculate_condition(t113,t114,t115,t116):Ity_I32
   154 | t118 = GET:I32(r5)
   155 | t119 = GET:I32(r2)
   156 | t120 = 32to8(t119)
   157 | t121 = CmpNE32(t117,0x00000000)
   158 | if (t121) STle(t118) = t120
   159 | t122 = GET:I32(r7)
   160 | t123 = armg_calculate_flag_c(t112,t114,t115,t116):Ity_I32
   161 | t124 = Shr32(t122,0x01)
   162 | t125 = Shl32(t123,0x1f)
   163 | t126 = Or32(t125,t124)
   164 | t127 = Sub32(t118,t126)
   165 | t128 = ITE(t121,t127,t118)
   166 | PUT(r5) = t128
   167 | ------ IMark(0x40054, 4, 0) ------
   168 | t129 = armg_calculate_condition(t112,t114,t115,t116):Ity_I32
   169 | t130 = GET:I32(r4)
   170 | t131 = Shl32(t128,0x04)
   171 | t132 = Shr32(t128,0x1c)
   172 | t133 = Or32(t132,t131)
   173 | t134 = Sub32(t133,t130)
   174 | t135 = GET:I32(r6)
   175 | t136 = CmpNE32(t129,0x00000000)
   176 | t137 = ITE(t136,t134,t135)
   177 | PUT(r6) = t137
   178 | t138 = ITE(t136,0x00000002,t112)
   179 | PUT(cc_op) = t138
   180 | t139 = ITE(t136,t133,t114)
   181 | PUT(cc_dep1) = t139
   182 | t140 = ITE(t136,t130,t115)
   183 | PUT(cc_dep2) = t140
   184 | t141 = ITE(t136,0x00000000,t116)
   185 | PUT(cc_ndep) = t141
   186 | ------ IMark(0x40058, 0, 0) ------
   187 | ------ IMark(0x40058, 4, 0) ------
   188 | ------ IMark(0x4005c, 4, 0) ------
   189 | t142 = GET:I32(cc_op)
   190 | t143 = Or32(t142,0x00000060)
   191 | t144 = GET:I32(cc_dep1)
   192 | t145 = GET:I32(cc_dep2)
   193 | t146 = GET:I32(cc_ndep)
   194 | t147 = armg_calculate_condition(t143,t144,t145,t146):Ity_I32
   195 | t148 = 32to1(t147)
   196 | t149 = Not1(t148)
   197 | if (t149) { PUT(pc) = 0x40060; Ijk_Boring }
   NEXT: PUT(pc) = 0x00040060; Ijk_Sys_syscall
}
```

**Environment Information.**
```
> python -m angr.misc.bug_report
C:\angr\misc\bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2022-06-24 14:13:13.465078
Running in virtual environment at C:\angr_all
Platform: win-amd64
Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
######## angr #########
Python found it in C:\angr
Pip version angr 9.2.8.dev0
Couldn't find git info
######## ailment #########
Python found it in C:\ailment
Pip version ailment 9.2.8.dev0
Couldn't find git info
######## cle #########
Python found it in C:\cle
Pip version cle 9.2.8.dev0
Couldn't find git info
######## pyvex #########
Python found it in C:\pyvex
Pip version pyvex 9.2.8.dev0
Couldn't find git info
######## claripy #########
Python found it in C:\claripy
Pip version claripy 9.2.8.dev0
Couldn't find git info
######## archinfo #########
Python found it in C:\archinfo
Pip version archinfo 9.2.8.dev0
Couldn't find git info
######## z3 #########
Python found it in C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\z3
Pip version z3-solver 4.8.17.0
Couldn't find git info
######## unicorn #########
Python found it in C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL 'C:\angr\lib\angr_native.dll', handle 7ffd53130000 at 0x2ba7c269c00>
unicorn: <CDLL 'C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\unicorn\lib\unicorn.dll', handle 7ffd4eda0000 at 0x2ba7a0e18d0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x000002BA787CF4C0>
z3: NOT FOUND
```

**Comment by rhelmot** [comment]
The root cause has been fixed!

**Comment by Lukas-Dresel** [comment]
That's really weird actually, it looks like that if statement is using a temp variable before it was defined?? That's ... odd to say the least. I would guess that this is some other underlying bug at play, and would argue that we probably do want this to error out the full analysis as that should never happen.
