### ISSUE TITLE
Errors with CFGFast on binary with LDM instructions

### ISSUE THREAD

**Issue by YashasAndaluri** [angr/angr#3429]
Hello

Hello, I'm trying to analyze ARM binaries ([err-binaries.zip](https://github.com/angr/angr/files/9056127/err-binaries.zip)) using CFGFast.

proj = angr.Project(args.binary ,auto_load_libs=False, load_debug_info=True)
cfg = proj.analyses.CFGFast()

However, CFGFast encounters errors.

Some of the warnings printed:
```
WARNING | 2022-07-06 20:44:19,150 | pyvex.lifting.gym.arm_spotter | Spotting an LDM instruction at 0x19d784.  This is not fully tested.  Prepare for errors.
WARNING | 2022-07-06 20:44:19,236 | pyvex.lifting.gym.arm_spotter | Ignoring STMxx ^ instruction at 0x19d7c8. This mode is not implemented by VEX! See pyvex/lifting/gym/arm_spotter.py
```

Errors:
```
Traceback (most recent call last):
  File "$HOME/vexIR/angr-vex/angr-vex.py", line 156, in <module>
    main(outFile, args.vocabulary, args.dump_triplets)
  File "$HOME/vexIR/angr-vex/angr-vex.py", line 19, in main
    cfg = proj.analyses.CFGFast()
  File "$HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/angr/analyses/analysis.py", line 138, in __call__
    r = w(*args, **kwargs)
  File "$HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/angr/analyses/analysis.py", line 122, in wrapper
    oself.__init__(*args, **kwargs)
  File "$HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 756, in __init__
    self._analyze()
  File "$HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 243, in _analyze
    self._post_analysis()
  File "$HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1443, in _post_analysis
    self._remove_redundant_overlapping_blocks(function_alignment=4, is_arm=True)
  File "$HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 3224, in _remove_redundant_overlapping_blocks
    if b.instruction_addrs[0] not in a.instruction_addrs:
IndexError: list index out of range
```
```
Traceback (most recent call last):
  File "$HOME/vexIR/angr-vex/angr-vex.py", line 156, in <module>
    main(outFile, args.vocabulary, args.dump_triplets)
  File "$HOME/vexIR/angr-vex/angr-vex.py", line 19, in main
    cfg = proj.analyses.CFGFast()
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/analysis.py", line 138, in __call__
    r = w(*args, **kwargs)
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/analysis.py", line 122, in wrapper
    oself.__init__(*args, **kwargs)
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 756, in __init__
    self._analyze()
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 236, in _analyze
    self._analysis_core_baremetal()
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 383, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 401, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1267, in _get_successors
    jobs = self._scan_block(job)
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1637, in _scan_block
    entries = self._scan_irsb(cfg_job, current_func_addr)
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1815, in _scan_irsb
    self._process_block_arch_specific(addr, cfg_node, irsb, function_addr, caller_gp=caller_gp)
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 4324, in _process_block_arch_specific
    self._arm_track_lr_on_stack(addr, irsb, self.functions[func_addr])
  File "$HOME/miniconda3/envs/angr-test-latest/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 3752, in _arm_track_lr_on_stack
    if irsb.statements is None:
AttributeError: 'NoneType' object has no attribute 'statements'
```

Platform: linux-x86_64
Python version: 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0]
######## angr #########
Python found it in $HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/angr
Pip version angr 9.2.6
Couldn't find git info
######## ailment #########
Python found it in $HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/ailment
Pip version ailment 9.2.6
Couldn't find git info
######## cle #########
Python found it in $HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/cle
Pip version cle 9.2.6
Couldn't find git info
######## pyvex #########
Python found it in $HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/pyvex
Pip version pyvex 9.2.6
Couldn't find git info
######## claripy #########
Python found it in $HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/claripy
Pip version claripy 9.2.6
Couldn't find git info
######## archinfo #########
Python found it in $HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/archinfo
Pip version archinfo 9.2.6
Couldn't find git info
######## z3 #########
Python found it in $HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.17.0
Couldn't find git info
######## unicorn #########
Python found it in $HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '$HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/angr/state_plugins/../lib/angr_native.so', handle 56379a07a9b0 at 0x7f8c4a081b20>
unicorn: <CDLL '$HOME/miniconda3/envs/angr-3.8/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 563799a101b0 at 0x7f8c4eaf69a0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f8c4f6beb20>
z3: NOT FOUND

I encounter these errors on angr version 9.2.9 as well.

Any suggestions would help.

**Comment by wuruoyu** [comment]
I also encountered this issue. It would be great if someone can drop a quick fix. Thanks in advance!

**Comment by ltfish** [comment]
@wuruoyu do you need it for USENIX? I’ll work on it after the USENIX deadline if you don’t need it immediately.

**Comment by wuruoyu** [comment]
Hi @ltfish, actually I have bypassed this issue by limiting cfg recovery on the desired region. Thanks for asking and good luck with your USENIX submissions :)
