### ISSUE TITLE
AttributeError: 'Section' object has no attribute 'iter_tags'

### ISSUE THREAD

**Issue by asmitaj08** [angr/angr#3459]
---

Hi, 
I am using angr 9.2.3. I am getting error with some ELF files as shown below:

 `

> Traceback (most recent call last):
>   File "/home/xxxx/PycharmProjects/prName/test.py", line 151, in <module> 
>             pr = load_project(binary_path)
>   File "/home/xxxx/PycharmProjects/prName/test.py", line 19, in load_project
>     p = angr.Project(path, load_options={'auto_load_libs': False})
>   File "/home/xxxx/.virtualenvs/angr/prName/lib/python3.10/site-packages/angr/project.py", line 137, in __init__
>     self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
>   File "/home/xxxx/.virtualenvs/angr/prName/lib/python3.10/site-packages/cle/loader.py", line 133, in __init__
>     self.initial_load_objects = self._internal_load(main_binary, *preload_libs, *force_load_libs, preloading=(main_binary, *preload_libs))
>   File "/home/xxxx/.virtualenvs/angr/prName/lib/python3.10/site-packages/cle/loader.py", line 668, in _internal_load
>     obj = self._load_object_isolated(main_spec)
>   File "/home/xxxx/.virtualenvs/angr/prName/lib/python3.10/site-packages/cle/loader.py", line 850, in _load_object_isolated
>     result = backend_cls(binary, binary_stream, is_main_bin=self.main_object is None, loader=self, **options)
>   File "/home/xxxx/.virtualenvs/angr/prName/lib/python3.10/site-packages/cle/backends/elf/elf.py", line 57, in __init__
>     super().__init__(*args, **kwargs)
>   File "/home/xxxx/.virtualenvs/angr/prName/lib/python3.10/site-packages/cle/backends/elf/metaelf.py", line 53, in __init__
>     self.relro = get_relro(tmp_reader)
>   File "/home/xxxx/.virtualenvs/angr/prName/lib/python3.10/site-packages/cle/backends/elf/metaelf.py", line 39, in get_relro
>     flags = [tag for tag in dyn_sec.iter_tags() if tag.entry.d_tag == 'DT_FLAGS']
> AttributeError: 'Section' object has no attribute 'iter_tags'`

Any suggestions would be appreciated. Thank you!!

**Comment by rhelmot** [comment]
Can you please upload a binary which exhibits this behavior?
