### ISSUE TITLE
AttributeError: 'ELFSymbol' object has no attribute 'to_bv'

### ISSUE THREAD

**Issue by Phasip** [angr/angr#346]
Hello again!

As you saw I managed to work around the last issue, now I have a new.
I am not sure if this is because I'm doing something wrong or if its actually a angr issue.

Attached is the same script (minor changes) but with a binary compiled with -static and -fno-stack-protector (angr seems to like -fno-stack-protector )
[angr_elfsymbol_issue.tar.gz](https://github.com/angr/angr/files/736821/angr_elfsymbol_issue.tar.gz)

```
(angr-dev) ubuntu@ubuntu-xenial:/vagrant/angr_elfsymbol_issue$ time python main.py 
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    (data,res,state) = run_func(len(matrix),matrix)
  File "main.py", line 46, in run_func
    state = proj.factory.call_state(decode_func, result_addr, matrix_size, data, ret_addr=return_addr, add_options=simuvex.o.unicorn|set([simuvex.o.REPLACEMENT_SOLVER]))
  File "/vagrant/angr-dev/angr/angr/factory.py", line 195, in call_state
    return self._project._simos.state_call(addr, *args, **kwargs)
  File "/vagrant/angr-dev/angr/angr/simos.py", line 450, in state_call
    state = self.state_blank(addr=addr, **kwargs)
  File "/vagrant/angr-dev/angr/angr/simos.py", line 657, in state_blank
    state = super(SimLinux, self).state_blank(**kwargs) #pylint:disable=invalid-name
  File "/vagrant/angr-dev/angr/angr/simos.py", line 423, in state_blank
    state.regs.ip = addr
  File "/vagrant/angr-dev/simuvex/simuvex/plugins/view.py", line 59, in __setattr__
    return self.state.registers.store(k, v, inspect=inspect, disable_actions=disable_actions)
  File "/vagrant/angr-dev/simuvex/simuvex/storage/memory.py", line 478, in store
    data_e = self._convert_to_ast(data_e, size_e if isinstance(size_e, (int, long)) else None)
  File "/vagrant/angr-dev/simuvex/simuvex/storage/memory.py", line 389, in _convert_to_ast
    data_e = data_e.to_bv()
AttributeError: 'ELFSymbol' object has no attribute 'to_bv'

real	0m8.147s
user	0m1.176s
sys	0m4.044s
```

ps. Nice phrack article

**Comment by rhelmot** [comment]
Your issue is that you need to call `addr` or `rebased_addr` on the symbol you extract from the loader.

**Comment by rhelmot** [comment]
sorry, not call, access the property

**Comment by Phasip** [comment]
Oh shit, sorry - thought I checked that the code was still valid after that change.
