### ISSUE TITLE
Linux kernel simproc unlink, ValueError: Trying to store to location without specifying address

### ISSUE THREAD

**Issue by carter-yagemann** [angr/angr#3570]
The following line of the simproc for `unlink` appears to be buggy:
https://github.com/angr/angr/blob/a075f4e6b06788dccb36786015de1043db66de03/angr/procedures/linux_kernel/unlink.py#L20

## Environment

Debian Bullseye
Python 3.9.12 (PyPy 7.3.9)
angr 9.2.21

## Stack Trace
```
Traceback (most recent call last):
  File "/tmp/tmp.c6TL6CHyLN/./bug.py", line 22, in <module>
    s.step()
  File "/usr/local/lib/python3.9/dist-packages/angr/sim_state.py", line 592, in step
    return self.project.factory.successors(self, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/factory.py", line 60, in successors
    return self.default_engine.process(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/engines/vex/light/slicing.py", line 19, in process
    return super().process(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/engines/engine.py", line 158, in process
    self.process_successors(self.successors, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/engines/failure.py", line 21, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/engines/syscall.py", line 18, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/engines/hook.py", line 61, in process_successors
    return self.process_procedure(state, successors, procedure, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/engines/procedure.py", line 37, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to, arguments=arguments)
  File "/usr/local/lib/python3.9/dist-packages/angr/sim_procedure.py", line 252, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/procedures/posix/unlink.py", line 13, in run
    return self.inline_call(unlink_sys, path).ret_expr
  File "/usr/local/lib/python3.9/dist-packages/angr/sim_procedure.py", line 389, in inline_call
    return p.execute(self.state, None, arguments=e_args)
  File "/usr/local/lib/python3.9/dist-packages/angr/sim_procedure.py", line 252, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/angr/procedures/linux_kernel/unlink.py", line 20, in run
    return self.state.libc.ret_errno('ENOENT')
  File "/usr/local/lib/python3.9/dist-packages/angr/state_plugins/libc.py", line 265, in ret_errno
    self.errno = ival
  File "/usr/local/lib/python3.9/dist-packages/angr/state_plugins/libc.py", line 254, in errno
    self.state.mem[self.errno_location].int = val
  File "/usr/local/lib/python3.9/dist-packages/angr/state_plugins/view.py", line 216, in __setattr__
    return self.__getattr__(k).store(v)
  File "/usr/local/lib/python3.9/dist-packages/angr/state_plugins/view.py", line 267, in store
    raise ValueError("Trying to store to location without specifying address")
ValueError: Trying to store to location without specifying address
```

## Steps to Reproduce

```python
#!/usr/bin/python
import angr
import os

"""
//unlink.c
#include <unistd.h>

int main(int argc, char **argv) {
    unlink("./foobarbuzz");
    return 0;
}
"""
assert os.path.isfile('./unlink')

p = angr.Project('./unlink', auto_load_libs=False)
u = p.loader.find_symbol('unlink').rebased_addr
# ./foobarbuzz doesn't exist, so unlink should set ENOENT
s = p.factory.call_state(u, (b"./foobarbuzz"), concrete_fs=True)

# trigger bug
s.step()
```

1. Compile `unlink.c` (included in script comment, just a lazy way to setup a call state for `unlink`).
2. Run above script.

**Comment by carter-yagemann** [comment]
https://github.com/angr/angr/blob/4cd0f6099031e1a95e2878cbfa1731d957939519/tests/test_unlink.py#L3-L7

It looks like the test only passes because it manually sets an address for `errno_location`.

**Comment by rhelmot** [comment]
So... this is a very tricky problem. Techincally everything is working as intended - you're only supposed to be able to use libc functions from a state which has had libc_start_main run, which sets errno_location. I'm not sure what the best way to do that from a call_state is... If you want a stopgap, you can run a state through to main, stop it, and then use it as the base_state for creating your call_states?

**Comment by carter-yagemann** [comment]
Ah, I see. I wasn't aware of this behavior, but that makes sense. Thanks!
