### ISSUE TITLE
How to save angr symfile input ?

### ISSUE THREAD

**Issue by mehdighninoudev** [angr/angr#3576]
### Question

Hi, I am working on testing my program (opening and parsing files), however I have discovered an unconstrained path (unconstrained > 0). But the problem is that I want to save the input testcase (the symbolic file generated) which caused the crash.

How can I do that? I am using for exploration: sm.explore(find=detect_crash)
and to get the filename: filecrash = sm.one_found.fs.get(filename).concretize()
but what I want  is the symbolic file content and to save it. If possible can you help me about that? And Thank you so much

**Comment by ltfish** [comment]
```python
content = sm.one_found.posix.dumps(3)  # 3 is the file descriptor of your opened file
with open("dump.bin", "wb") as f:
    f.write(content)
```

**Comment by mehdighninoudev** [comment]
Okay, thank you so much for this help!

**Comment by mehdighninoudev** [comment]
when I try I got this error: AttributeError: 'NoneType' object has no attribute 'concretize'

**Comment by mehdighninoudev** [comment]
here is the error: 
```
TRUE CRASH
Traceback (most recent call last):
  File "symfile2.py", line 35, in <module>
    main()
  File "symfile2.py", line 29, in main
    content = sm.one_found.posix.dumps(3)
  File "/usr/local/lib/python3.8/dist-packages/angr/state_plugins/posix.py", line 612, in dumps
    return self.get_fd(fd).concretize(**kwargs)
AttributeError: 'NoneType' object has no attribute 'concretize'
```

**Comment by ltfish** [comment]
`3` is the example file descriptor that I used. I don't know what fds your tested program opened. You can take a look at `sm.one_found.posix.fd` (which is a dict) to see what files are open. `0` (stdin), `1` (stdout), and `2` (stderr) are always available.

If your tested program has closed the file, you can take a look at `sm.one_found.posix.closed_fds`.

**Comment by mehdighninoudev** [comment]
for my case I got these results: 
`{0: <angr.storage.file.SimFileDescriptorDuplex object at 0x7f78e2009700>, 1: <angr.storage.file.SimFileDescriptorDuplex object at 0x7f78e2009700>, 2: <angr.storage.file.SimFileDescriptor object at 0x7f78e2009160>}`

does that mean that I have 3 file descriptors used ?

**Comment by ltfish** [comment]
0 - 2 are stdin, stdout, and stderr.

It's entirely possible that angr found a path that opens and closes the file (in which case, you will see the closed file descriptor inside `sm.one_found.posix.closed_fds`), or it did not even find the path where the file was opened and parsed.

**Comment by mehdighninoudev** [comment]
okay I have a question please? 
does this code: `sm.one_found.fs.get(filename).concretize()` prints the content of the symbolic file ? (if found) ?
Or Am I wrong ?

**Comment by ltfish** [comment]
According to the API docs:

```python
    def concretize(self, **kwargs):
        """
        Return a concretizeation of the data in the underlying file. Has different return types to represent different
        data structures on a per-class basis.

        Any arguments passed to this will be passed onto state.solver.eval.
        """
```

`sm.one_found.fs.get(filename).concretize()` does print the concretized content of the symbolic file if the file exists in angr's emulated file system.

Regarding your second question: What you are feeding to your binary as an argument (I assume you are referring to command line arguments, i.e., argvs) depends on what your binary's main function expects.

**Comment by mehdighninoudev** [comment]
okay sure. Does deadended state means that the rip register is overwritten by user data ? Or something happened in cause of user data input ?

**Comment by ltfish** [comment]
> Does deadended state means that the rip register is overwritten by user data ?

No. Deadended states are states that angr cannot step forward. For example, when a program calls `exit()`, the corresponding state will be put into the deadended stash because there are no successors to that state.

States whose IP is overwritten by symbolic user data are often become _unconstrained_ states (and are put into the unconstrained stash), which means angr cannot constrain the IP to any concrete value.

**Comment by mehdighninoudev** [comment]
is there any script in the angr repo that shows symbolic execution for file format fuzzing ?
