### ISSUE TITLE
Crash in path_group.explore()

### ISSUE THREAD

**Issue by frapik99** [angr/angr#359]
Hi,
if I try to generate the path to the ```malloc``` function in the project that has the following C code:

```
#include<stdlib.h>
#include<stdio.h>
#include<string.h>

int main() {
        char c[100];
        FILE *fd = fopen("file","rb");
        memset(&c, 0x00, 100);
        fread(c, 5,4, fd);
        memset(&c, c[0], 5);
        malloc(3);
}
```

The presence of c[0] in the second ```memset``` generates the issue. Am i doing something wrong?

```
Traceback (most recent call last):
  ...
    path_group.explore(find=address)
  File "/home/frapik/Desktop/angr-dev/angr/angr/path_group.py", line 806, in explore
    n=n)
  File "/home/frapik/Desktop/angr-dev/angr/angr/path_group.py", line 830, in run
    return self.step(n=n, step_func=step_func, until=until_func, stash=stash)
  File "/home/frapik/Desktop/angr-dev/angr/angr/path_group.py", line 520, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/home/frapik/Desktop/angr-dev/angr/angr/path_group.py", line 311, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/home/frapik/Desktop/angr-dev/angr/angr/path_group.py", line 208, in _one_path_step
    successors = a.step(**kwargs)
  File "/home/frapik/Desktop/angr-dev/angr/angr/path.py", line 195, in step
    self._make_sim_run(throw=throw)
  File "/home/frapik/Desktop/angr-dev/angr/angr/path.py", line 226, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/home/frapik/Desktop/angr-dev/angr/angr/factory.py", line 166, in sim_run
    r = sim_proc_class(state, addr=addr, sim_kwargs=kwargs)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/simuvex/s_procedure.py", line 73, in __init__
    r = self._run(run_func, *args, syscall_name=syscall_name, **self.kwargs)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/simuvex/s_procedure.py", line 116, in _run
    r = run_func(*args, **kwargs)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/simuvex/procedures/libc___so___6/memset.py", line 60, in run
    if char._model_concrete.value == 0:
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/simuvex/s_action_object.py", line 87, in __getattr__
    f = getattr(self.ast, attr)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/claripy/ast/base.py", line 931, in __getattr__
    raise AttributeError(a)
AttributeError: value
```

Thanks

**Comment by rhelmot** [comment]
This is an actual bug! It looks like we assume in memset that if the number of bytes we are writing is concrete, then the value we are writing must be concrete also.

**Comment by rhelmot** [comment]
I just pushed what I think is a fix. It no longer crashes! Are the results what you expect?

**Comment by frapik99** [comment]
@rhelmot thanks, I''ll check ASAP. Should I install the latest angr or a specific PR?

**Comment by rhelmot** [comment]
Pull the latest simuvex master.

**Comment by frapik99** [comment]
OK, I'll go for ```pip install simuvex --upgrade``` or it is not pip installable yet?

**Comment by rhelmot** [comment]
We have not released it yet. You can do this, though:

`pip install git+git://github.com/angr/simuvex.git`

**Comment by frapik99** [comment]
I did it and I think I still have the same problem...

**Comment by rhelmot** [comment]
Did pip say that it actually installed something, or that simuvex was already up to date?

**Comment by frapik99** [comment]
@rhelmot you were right, I have removed and reinstalled simuvex using the command you suggest and all worked :)

Happy to have helped a bit.

Thanks
