### ISSUE TITLE
CFGAccurate failing

### ISSUE THREAD

**Issue by drone-rites** [angr/angr#360]
There were a number of small errors that prevented `CFGAccurate` from working in the current master. It seems to mostly be related to outdated code. I'm not sure my fixes are correct, but I pushed up a branch that resolves the issues I was seeing and allows me to generate a CFG from `CFGAccurate`.

[https://github.com/mattrepl/angr/tree/cfg_fix](https://github.com/mattrepl/angr/tree/cfg_fix)

**Comment by Lawliar** [comment]
Hi, there, I also encountered some errors when constructing a CFGAccurate.
I wonder if you had the same.
> ERROR   | 2017-03-08 20:45:11,582 | simuvex.vex.statements.dirty | Unsupported dirty helper amd64g_dirtyhelper_loadF80le
Traceback (most recent call last):
  File "inputs_gen.py", line 265, in <module>
    process(args.xml_file,binary_file=args.binary)
  File "inputs_gen.py", line 227, in process
    write_inputs(binary_file, addr, result_id,argv_count=argv_count,count = count)
  File "inputs_gen.py", line 78, in write_inputs
    CFGAccurate = p.analyses.CFGAccurate()
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 249, in __init__
    self._analyze()
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 228, in _analyze
    self._pre_entry_handling(entry_info.entry)
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 1071, in _pre_entry_handling
    sim_successors, error_occurred, _ = self._get_simsuccessors(addr, job, current_function_addr=job.func_addr)
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 2558, in _get_simsuccessors
    opt_level=self._iropt_level)
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/factory.py", line 78, in successors
    r = engine.process(state, inline=inline,**kwargs)
  File "/home/lcm/my_env/lib/python2.7/site-packages/simuvex/engines/vex/engine.py", line 101, in process
    opt_level=opt_level)
  File "/home/lcm/my_env/lib/python2.7/site-packages/simuvex/engines/engine.py", line 44, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/lcm/my_env/lib/python2.7/site-packages/simuvex/engines/vex/engine.py", line 134, in _process
    self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
  File "/home/lcm/my_env/lib/python2.7/site-packages/simuvex/engines/vex/engine.py", line 209, in _handle_irsb
    retval_size = stmt.result_size(state.scratch.tyenv) / 8
AttributeError: 'Dirty' object has no attribute 'result_size'

**Comment by rhelmot** [comment]
@Lawliar: your bug is due to an outdated version of simuvex. We will update the version on pip soon, but for now you can install from github.

**Comment by Lawliar** [comment]
@rhelmot Thank you very much for your timely reply. However as I uninstalled the simuvex which I had installed with pip and git clone from https://github.com/angr/simuvex.git and installed manually just now. I got another error which seems to be similar to the former.
Sorry to be inconvenient :-P
> ERROR   | 2017-03-08 21:57:42,695 | simuvex.vex.statements.dirty | Unsupported dirty helper amd64g_dirtyhelper_loadF80le
Traceback (most recent call last):
  File "inputs_gen.py", line 265, in <module>
    process(args.xml_file,binary_file=args.binary)
  File "inputs_gen.py", line 227, in process
    write_inputs(binary_file, addr, result_id,argv_count=argv_count,count = count)
  File "inputs_gen.py", line 78, in write_inputs
    CFGAccurate = p.analyses.CFGAccurate()
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 249, in __init__
    self._analyze()
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 228, in _analyze
    self._pre_entry_handling(entry_info.entry)
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 1071, in _pre_entry_handling
    sim_successors, error_occurred, _ = self._get_simsuccessors(addr, job, current_function_addr=job.func_addr)
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 2558, in _get_simsuccessors
    opt_level=self._iropt_level)
  File "/home/lcm/my_env/lib/python2.7/site-packages/angr/factory.py", line 78, in successors
    r = engine.process(state, inline=inline,**kwargs)
  File "/home/lcm/my_env/lib/python2.7/site-packages/simuvex-6.7.1.31-py2.7.egg/simuvex/engines/vex/engine.py", line 101, in process
    opt_level=opt_level)
  File "/home/lcm/my_env/lib/python2.7/site-packages/simuvex-6.7.1.31-py2.7.egg/simuvex/engines/engine.py", line 44, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/lcm/my_env/lib/python2.7/site-packages/simuvex-6.7.1.31-py2.7.egg/simuvex/engines/vex/engine.py", line 134, in _process
    self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
  File "/home/lcm/my_env/lib/python2.7/site-packages/simuvex-6.7.1.31-py2.7.egg/simuvex/engines/vex/engine.py", line 209, in _handle_irsb
    retval_size = state.scratch.tyenv.sizeof(stmt.tmp)
AttributeError: 'IRTypeEnv' object has no attribute 'sizeof'

**Comment by rhelmot** [comment]
The angr suite is heavily interlocked, and when you upgrade one component, you must upgrade all of them. This bug is due to an outdated pyvex.

**Comment by Lawliar** [comment]
@rhelmot thank your for your tip, I will look into it.
At the same time,I found something quite interesting that may be some food for thought.
As I test on coreutility-6.10, when constructing CFGAccurate, I got those errors.
But when testing coreutility-8.26, CFGAccurate construction worked out just fine.
Maybe it has sth to do with this?
By the way, I really appreciate your efforts on this awesome project.

**Comment by rhelmot** [comment]
Your error will arise only when certain kinds of unsupported dirty statements occur, for example, the rdtsc instruction. The exact version of coreutils has little to do with this, what matters is what instructions occur in the compiled binaries.

In the future, you should open a new issue for things like this instead of hijacking someone else's.
