### ISSUE TITLE
CFGFast | ERROR | It should be impossible

### ISSUE THREAD

**Issue by fishfacegit** [angr/angr#3630]
### Description

Hello,
I try to analyse **malware** and get the following error on creating a CFG for function discovery:

> 2022-11-25 01:03:24 | __main__ | INFO | creating BlockAnalysis for 935ffdf950ff6d381426e45dab74341c48646291c05233f864db0768e056f4db
> 2022-11-25 01:05:05 | __main__ | ERROR | It should be impossible
> Traceback (most recent call last):
>   File "/home/james/src/app.py", line 35, in <module>
>     ba = BlockAnalysis(binary)
>   File "/home/james/src/analysis/block/block_analysis.py", line 32, in __init__
>     self.project.analyses.CFGFast(data_references=False, skip_unmapped_addrs=False)
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/analysis.py", line 138, in __call__
>     r = w(*args, **kwargs)
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/analysis.py", line 122, in wrapper
>     oself.__init__(*args, **kwargs)
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/cfg/cfg_fast.py", line 756, in __init__
>     self._analyze()
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 241, in _analyze
>     self._analysis_core_baremetal()
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 365, in _analysis_core_baremetal
>     self._job_queue_empty()
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/cfg/cfg_fast.py", line 1369, in _job_queue_empty
>     self._process_unresolved_indirect_jumps()
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/cfg/cfg_base.py", line 2577, in _process_unresolved_indirect_jumps
>     all_targets |= self._process_one_indirect_jump(jump)
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/cfg/cfg_base.py", line 2611, in _process_one_indirect_jump
>     self._indirect_jump_unresolved(jump)
>   File "/home/james/.local/lib/python3.10/site-packages/angr/analyses/cfg/cfg_fast.py", line 2996, in _indirect_jump_unresolved
>     raise AngrCFGError('It should be impossible')
> angr.errors.AngrCFGError: It should be impossible

### Steps to reproduce the bug

```
loader = angr.cle.loader.Loader(BytesIO(binary), use_system_libs=False, auto_load_libs=False)
self.project = angr.Project(loader, use_sim_procedures=True, support_selfmodifying_code=True)
self.project.analyses.CFGFast(data_references=False, skip_unmapped_addrs=False)
```

### Additional context

Link to file: https://bazaar.abuse.ch/download/935ffdf950ff6d381426e45dab74341c48646291c05233f864db0768e056f4db
**Be careful, it's malware.**

**Comment by rhelmot** [comment]
Long story short static analysis and support_selfmodifying_code don't mix well. If you're just doing cfgfast, I recommend loading with that option turned off.

@ltfish we should probably add a modicum of optimization to vex or pyvex in the case that opt_level=0 so we don't see every single block as an indirect jump...
