### ISSUE TITLE
Possible bug: IROp error (for operation Iop_DivModU64to32)

### ISSUE THREAD

**Issue by frapik99** [angr/angr#366]
Hi,
loading ```ld-linux.so.2``` from my Ubuntu 64 bit I have the following error:

```
WARNING | 2017-02-16 20:11:37,807 | simuvex.vex.irop | IROp error (for operation Iop_DivModU64to32)
Traceback (most recent call last):
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/simuvex/engines/vex/irop.py", line 842, in translate
    return irop.calculate( *s_args)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/simuvex/engines/vex/irop.py", line 348, in calculate
    return self.extend_size(self._calculate(args))
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/simuvex/engines/vex/irop.py", line 693, in _op_divmod
    quotient = (args[0] / claripy.ZeroExt(self._from_size - self._to_size, args[1]))
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/claripy/operations.py", line 65, in _op
    return return_type(name, fixed_args, **kwargs)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/claripy/ast/base.py", line 128, in __new__
    r = operations._handle_annotations(eb._abstract(eb.call(op, args)), args)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/claripy/backends/__init__.py", line 208, in call
    obj = getattr(operator, op)(*converted)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/claripy/bv.py", line 38, in normalize_helper
    return f(self, o)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/claripy/bv.py", line 13, in compare_guard
    return f(self, o)
  File "/home/frapik/.virtualenvs/angr/local/lib/python2.7/site-packages/claripy/bv.py", line 117, in __div__
    raise ClaripyZeroDivisionError()
SimOperationError: ('Iop_DivModU64to32._calculate() raised exception', <class 'claripy.errors.ClaripyZeroDivisionError'>, ClaripyZeroDivisionError())
```
HTH

Thanks

**Comment by rhelmot** [comment]
That looks like a warning, not an error. The loading should have finished correctly. Do you experience any actual issues analyzing the binary?

If there is an issue, could you attach your `ld-linux.so.2`? I can't reproduce on my copy.

**Comment by frapik99** [comment]
@rhelmot, I tried again and it seems that it stuck somewhere and the CPU goes to 100%.

I have attached the file so you can reproduce it. [ld.zip](https://github.com/angr/angr/files/778570/ld.zip)

Can you also try with executable that use ```libzip``` or ```libpng``` for example with ```auto_load_libs``` set to ```True``` and see if it goes well?

Thanks
