### ISSUE TITLE
'DefaultMemory' object has no attribute 'set_stack_address_mapping'

### ISSUE THREAD

**Issue by smuthayan** [angr/angr#3661]
### Question

Hello! I have an error when executing the following python code:
It only fails when calling the VFG function and I can't figure out why. I apologize if the answer is obvious as I don't have a lot of experience with python.

```
import angr


proj = angr.Project("F:/analysis/driver.sys", load_options={'auto_load_libs':False}, main_opts={'base_addr': 0xFFFFF80539050000})
start_state = proj.factory.blank_state()
start_state.regs.rax = 0xfffff8053915c868
start_state.regs.rbx = 0xffffce0bda393000
start_state.regs.rcx = 0xffffce0bd8b9fa70
start_state.regs.rdx = 0xffffce0bda393000
start_state.regs.rsi = 0xffffce0bda907f90
start_state.regs.rdi = 0xffffce0bd8b9fa70
start_state.regs.rip = 0xfffff8053915c869
start_state.regs.rsp = 0xfffffc84f27d28f0
start_state.regs.rbp = 0xfffffc84f27d2a60
start_state.regs.r8 = 0x0000000000745720
start_state.regs.r9 = 0x0000000000000100
start_state.regs.r10 = 0x0000fffff8053915
start_state.regs.r11 = 0xffff9afaf8200000
start_state.regs.r12 = 0xffffbb8fe1a11110
start_state.regs.r13 = 0xffffffff80002a64
start_state.regs.r14 = 0x0000000000000000
start_state.regs.r15 = 0xffffce0bd8b9fa70
cfg = proj.analyses.CFGEmulated(keep_state=True, initial_state=start_state)
vfg = proj.analyses.VFG(cfg, start=0xfffff8053915c868,initial_state=start_state)
```

Error code:
```
WARNING | 2022-12-09 17:33:54,028 | angr.analyses.vfg | The given CFG is not normalized, which might impact the performance/accuracy of the VFG analysis.
Traceback (most recent call last):
  File "C:\Users\BubbaGanoosh\PycharmProjects\angrProject\main.py", line 27, in <module>
    vfg = proj.analyses.VFG(cfg, start=0xfffff8053915c868,initial_state=start_state)
  File "C:\Users\BubbaGanoosh\PycharmProjects\angrProject\venv\lib\site-packages\angr\analyses\analysis.py", line 138, in __call__
    r = w(*args, **kwargs)
  File "C:\Users\BubbaGanoosh\PycharmProjects\angrProject\venv\lib\site-packages\angr\analyses\analysis.py", line 122, in wrapper
    oself.__init__(*args, **kwargs)
  File "C:\Users\BubbaGanoosh\PycharmProjects\angrProject\venv\lib\site-packages\angr\analyses\vfg.py", line 364, in __init__
    self._analyze()
  File "C:\Users\BubbaGanoosh\PycharmProjects\angrProject\venv\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 229, in _analyze
    self._pre_analysis()
  File "C:\Users\BubbaGanoosh\PycharmProjects\angrProject\venv\lib\site-packages\angr\analyses\vfg.py", line 485, in _pre_analysis
    initial_state = self._prepare_initial_state(self._start, self._initial_state)
  File "C:\Users\BubbaGanoosh\PycharmProjects\angrProject\venv\lib\site-packages\angr\analyses\vfg.py", line 1195, in _prepare_initial_state
    state.memory.set_stack_address_mapping(sp_val,
AttributeError: 'DefaultMemory' object has no attribute 'set_stack_address_mapping'

Process finished with exit code 1
```

**Comment by rhelmot** [comment]
The states that vfg processes need special plugins attached in order to function. Try creating it with `mode="static"`.

ref: https://github.com/angr/angr/blob/master/angr/analyses/vfg.py#L1188

**Comment by ltfish** [comment]
Audrey is right. You'll want to create the state with `mode="state"`.
