### ISSUE TITLE
Exception: Internal error: cannot translate address

### ISSUE THREAD

**Issue by likaiam** [angr/angr#3670]
### Description

I was calling Angr for concolic execution and my subject program is sqlite.So the input is sql query.The following is log and stacktrace.
Drilling input: b"CREATE TABLE v0 ( v1 INTEGER ) ; SELECT v1 FROM v0 WHERE v1 = 'v0' AND ( v1 = 8 OR v1 =9223372036854775808 ) ORDER BY v1 ; SELECT v1, sum ( v1 ) OVER( PARTITION BY v1 ORDER BY v1 ) FROM v0 ; "
WARNING | 2022-12-19 13:43:46,883 | pyvex.lifting.gym.x86_spotter | The generalized AAM instruction is not supported by VEX, and is handled specially by pyvex. It has no flag handling at present.  See pyvex/lifting/gym/x86_spotter.py for details
WARNING | 2022-12-19 13:43:47,228 | cle.backends.tls | The provided object has an invalid tls_data_size. Skip TLS loading.
WARNING | 2022-12-19 13:43:49,888 | cle.backends.tls | The provided object has an invalid tls_data_size. Skip TLS loading.
Traceback (most recent call last): 
File "run_driller.py", line 70, in <module>
    main()
  File "run_driller.py", line 56, in main
    for _, new_input in Driller(binary, seed, fuzzer_bitmap).drill_generator():
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/driller/driller_main.py", line 101, in drill_generator
    for i in self._drill_input():
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/driller/driller_main.py", line 143, in _drill_input
    simgr.step()
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/misc/hookset.py", line 90, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/exploration_techniques/driller_core.py", line 39, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/misc/hookset.py", line 90, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/exploration_techniques/tracer.py", line 343, in step
    return simgr.step(stash=stash, syscall_data=self._syscall_data, fd_bytes=self._fd_bytes, **kwargs)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/misc/hookset.py", line 90, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/exploration_techniques/suggestions.py", line 41, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/misc/hookset.py", line 95, in __call__
    return self.func(*args, **kwargs)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/sim_manager.py", line 407, in step
    successors = self.step_state(state, successor_func=successor_func, error_list=error_list, **run_args)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/misc/hookset.py", line 90, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/exploration_techniques/tracer.py", line 406, in step_state
    self._update_state_tracking(succs[0])
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/exploration_techniques/tracer.py", line 574, in _update_state_tracking
    self._sync_return(state, idx)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/exploration_techniques/tracer.py", line 890, in _sync_return
    return self._sync(state, idx, ret_addr)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/exploration_techniques/tracer.py", line 893, in _sync
    addr_translated = self._translate_state_addr(addr)
  File "/home/linuxbrew/anaconda3/envs/driller/lib/python3.8/site-packages/angr/exploration_techniques/tracer.py", line 640, in _translate_state_addr
    raise Exception("Internal error: cannot translate address")
Exception: Internal error: cannot translate address

**Comment by ltfish** [comment]
Can you please more context (what you are symbolically executing/drilling, which address could not be translated, etc.) or a script to reproduce the issue? I cannot speculate the problem without more information.

**Comment by likaiam** [comment]
Actually,I was using Driller which using Angr as its concolic execution engine to fuzz sqlite(a database program. I don't konw whether Driller(Angr) support database program.The following is the log of directly fuzzing sqlite using driller.
![3971c3db330e43462ee4ec39a38518f](https://user-images.githubusercontent.com/44605008/208930827-aa6c9b36-cd74-4651-ad7d-e79c312755af.png)

**Comment by rhelmot** [comment]
Can you please get a debug shell at the site of the crash (`ipython --pdb myscript.py`) and print out the value of the obj variable (`p obj`)?

**Comment by likaiam** [comment]
sorry,I can't.
here is the docker I am using and it is the developer provides. 
https://hub.docker.com/r/zjuchenyuan/driller
When I tried to hybrid fuzz Mp3Gain(the example program)，it works.However,when I tried to fuzz sqlite(a database program),it reported the above errors.I don't konw whether Angr can be used to database program.

**Comment by rhelmot** [comment]
I can't spend the time to debug this for you unless you provide precise reproduction instructions, including both the script you're using to run angr and the binary you're analyzing.

There is nothing special about the class of "database programs" such that angr should not be able to analyze them.
