### ISSUE TITLE
cle is not importing BackedCGC

### ISSUE THREAD

**Issue by rustempasha** [angr/angr#37]
After installing all dependencies and dealling with the common package issues, I encountered
with the following issue;

Traceback (most recent call last):
  File "solve.py", line 3, in <module>
    import angr

 File "/usr/local/lib/python2.7/dist-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 322, in <module>
    from .simos import SimOS, os_mapping
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 12, in <module>
    from cle import MetaELF, BackedCGC
ImportError: cannot import name BackedCGC

Thanks.

**Comment by ekse** [comment]
This shouldn't be an issue anymore with an up to date version of CLE.

**Comment by rhelmot** [comment]
Pretty much? this was probably an issue with packaging and/or versioning. Re-open if you still need help :)
