### ISSUE TITLE
AssertionError when using CFGFast(normalize=True) on ARM binary

### ISSUE THREAD

**Issue by YashasAndaluri** [angr/angr#3759]
### Description

Hello, I'm trying to analyze basic blocks in an ARM binary using CFGFast with normalize=True. I get the following AssertionError with my binary as input:

```
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    cfg = proj.analyses.CFGFast(normalize=True)
  File "/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/analyses/analysis.py", line 144, in __call__
    r = w(*args, **kwargs)
  File "/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/analyses/analysis.py", line 129, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 851, in __init__
    self._analyze()
  File "/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 255, in _analyze
    self._post_analysis()
  File "/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1543, in _post_analysis
    self.make_functions()
  File "/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/analyses/cfg/cfg_base.py", line 1455, in make_functions
    removed_functions_b, adjusted_cfgnodes = self._process_irrational_function_starts(
  File "/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/analyses/cfg/cfg_base.py", line 1867, in _process_irrational_function_starts
    self._merge_cfgnodes(cfgnode_0, cfgnode_1)
  File "/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/analyses/cfg/cfg_base.py", line 381, in _merge_cfgnodes
    assert cfgnode_0.addr + cfgnode_0.size == cfgnode_1.addr
AssertionError
```

### Steps to reproduce the bug

Attaching script and binary to reproduce the AssertionError: 
[normalize_bug.zip](https://github.com/angr/angr/files/10472642/normalize_bug.zip)

To reproduce the error with angr-9.2.34: `python script.py bin.out`

### Environment

angr environment report
=============================
Date: 2023-01-21 14:59:44.998071
!!! running in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.8.16 (default, Jan 17 2023, 23:13:24) 
[GCC 11.2.0]
######## angr #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr
Pip version angr 9.2.34
Couldn't find git info
######## ailment #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/ailment
Pip version ailment 9.2.34
Couldn't find git info
######## cle #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/cle
Pip version cle 9.2.34
Couldn't find git info
######## pyvex #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/pyvex
Pip version pyvex 9.2.34
Couldn't find git info
######## claripy #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/claripy
Pip version claripy 9.2.34
Couldn't find git info
######## archinfo #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/archinfo
Pip version archinfo 9.2.34
Couldn't find git info
######## z3 #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/angr/state_plugins/../lib/angr_native.so', handle 2906430 at 0x7f634d4be880>
unicorn: <CDLL '/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/unicorn/lib/libunicorn.so.2', handle 227c660 at 0x7f6353d8a730>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f6353247eb0>
z3: <CDLL '/home/yashas/miniconda3/envs/angr-9.2.34/lib/python3.8/site-packages/z3/lib/libz3.so', handle 2635500 at 0x7f634f4a8c40>

**Comment by ltfish** [comment]
Thank you for reporting. Can we use your binary as a test case?

**Comment by YashasAndaluri** [comment]
Yes, the binary provided can be used as a test

**Comment by ltfish** [comment]
Awesome. Thanks a lot!
