### ISSUE TITLE
Genereate DDG Error

### ISSUE THREAD

**Issue by Sakaze** [angr/angr#376]
Hi, I have a Problem with the plot_ddg_eample.py file. I tried to plot a DDG for a simple main.  Generating a CFG works fine but an error occurs in the DDG generator.

`Traceback (most recent call last):
  File "plot_ddg_example.py", line 63, in <module>
    analyze(proj, main.addr,"testFuncMul")
  File "plot_ddg_example.py", line 17, in analyze
    plot_ddg_stmt(ddg.graph, "%s_ddg_stmt" % name, project=b)
  File "/AngreTestSo/angrutils/visualize.py", line 59, in plot_ddg_stmt
    vis.process(ddg_stmt)
  File "/AngreTestSo/bingraphvis/base.py", line 220, in process
    graph = self.pipeline.process()        
  File "/AngreTestSo/bingraphvis/base.py", line 203, in process
    c.render(n)
  File "/AngreTestSo/bingraphvis/base.py", line 105, in render
    self.gen_render(n)
  File "/AngreTestSo/bingraphvis/angr/content.py", line 225, in gen_render
    addr = node.simrun_addr
AttributeError: 'CodeLocation' object has no attribute 'simrun_addr'
`

I don't know why he is trying to access the 'simrun_addr' and what it is good for.
This Error occors even when I execute the example with the given sample.
What is 'simrun_addr' and how can i fix this Error?

**Comment by axt** [comment]
Hi. The `simrun_addr` property was renamed to `block_addr` recently. Your install of https://github.com/axt/angr-utils and/or  https://github.com/axt/bingraphvis is outdated, please install them from the latest HEAD, it shoud solve the problem.
