### ISSUE TITLE
Error with CFGFast(normalize=True) on ARM binary

### ISSUE THREAD

**Issue by YashasAndaluri** [angr/angr#3768]
### Description

Hello, I'm trying to analyze basic blocks in another ARM binary using CFGFast with normalize=True. 
After about 3 minutes, I get a KeyError with my binary:

```
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    cfg = proj.analyses.CFGFast(normalize=True)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/analysis.py", line 144, in __call__
    r = w(*args, **kwargs)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/analysis.py", line 129, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 851, in __init__
    self._analyze()
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 248, in _analyze
    self._analysis_core_baremetal()
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 372, in _analysis_core_baremetal
    self._job_queue_empty()
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1465, in _job_queue_empty
    self._process_unresolved_indirect_jumps()
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_base.py", line 2697, in _process_unresolved_indirect_jumps
    all_targets |= self._process_one_indirect_jump(jump)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_base.py", line 2723, in _process_one_indirect_jump
    resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 758, in resolve
    func = cfg.kb.functions[func_addr]
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/knowledge_plugins/functions/function_manager.py", line 320, in __getitem__
    raise KeyError(k)
KeyError: 1149280
```

I get a different error after applying changes in #3765 : 

```
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    cfg = proj.analyses.CFGFast(normalize=True)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/analysis.py", line 144, in __call__
    r = w(*args, **kwargs)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/analysis.py", line 129, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 757, in __init__
    self._analyze()
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 248, in _analyze
    self._analysis_core_baremetal()
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 396, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 414, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1268, in _get_successors
    jobs = self._scan_block(job)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1638, in _scan_block
    entries = self._scan_irsb(cfg_job, current_func_addr)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 1816, in _scan_irsb
    self._process_block_arch_specific(addr, cfg_node, irsb, function_addr, caller_gp=caller_gp)
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 4332, in _process_block_arch_specific
    self._arm_track_lr_on_stack(addr, irsb, self.functions[func_addr])
  File "/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/analyses/cfg/cfg_fast.py", line 3760, in _arm_track_lr_on_stack
    if irsb.statements is None:
AttributeError: 'NoneType' object has no attribute 'statements'
```

### Steps to reproduce the bug

Script and binary to reproduce the error:
[normalize_bug2.zip](https://github.com/angr/angr/files/10530578/normalize_bug2.zip)

To reproduce the error with angr-9.2.35: python script.py bin.out

### Environment

Date: 2023-01-29 19:25:31.592717
!!! running in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0]
######## angr #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr
Pip version angr 9.2.35
Couldn't find git info
######## ailment #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/ailment
Pip version ailment 9.2.35
Couldn't find git info
######## cle #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/cle
Pip version cle 9.2.35
Couldn't find git info
######## pyvex #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/pyvex
Pip version pyvex 9.2.35
Couldn't find git info
######## claripy #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/claripy
Pip version claripy 9.2.35
Couldn't find git info
######## archinfo #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/archinfo
Pip version archinfo 9.2.35
Couldn't find git info
######## z3 #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/angr/state_plugins/../lib/angr_native.so', handle 560a9bc1b810 at 0x7f9821654370>
unicorn: <CDLL '/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/unicorn/lib/libunicorn.so.2', handle 560a9b588ca0 at 0x7f98267cb340>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f9827369ac0>
z3: <CDLL '/home/yashas/miniconda3/envs/angr-9.2.35/lib/python3.8/site-packages/z3/lib/libz3.so', handle 560a9b9393e0 at 0x7f982359daf0>

**Comment by ch4rli3kop** [comment]
Hi I too have often encountered this problem when analyzing ARM binaries. I don't know why, but in my case I was able to solve it by loading the libraries used by the executable.

**Comment by ltfish** [comment]
Please give the above PR a try @ch4rli3kop .
