### ISSUE TITLE
Project fails for ElfCore due to duplicate/redundant backend

### ISSUE THREAD

**Issue by sahinburak** [angr/angr#3829]
### Description

I have a core file generated using `generate-core-file` by GDB v11 on a ARM device. The core file than analyzed by angr on a x86_64 machine.  the line for the angr project is `prj = angr.Project("./corefile", main_opts={"backend":"elfcore"})` or `prj = angr.Project("./corefile", main_opts={"backend":"elfcore"}, rebase_granularity=0x1000)`.

The error log:
```
WARNING  | cle.backends.elf.elfcore.__reload_children@362                      | Could not load /opt/?????/bin/????.bin (could not determine base); core may be incomplete
WARNING  | cle.backends.tls.elfcore_tls.__init__@12                            | TLS for coredumps won't be right for this arch - idk how to do it
Traceback (most recent call last):
  File "sil.py", line 2, in <module>
    prj = angr.Project("./core.861", main_opts={"backend":"elfcore"})
  File "/root/.virtualenvs/angr/lib/python3.8/site-packages/angr/project.py", line 238, in __init__
    self.simos.configure_project()
  File "/root/.virtualenvs/angr/lib/python3.8/site-packages/angr/simos/linux.py", line 132, in configure_project
    super().configure_project(syscall_abis)
  File "/root/.virtualenvs/angr/lib/python3.8/site-packages/angr/simos/userland.py", line 35, in configure_project
    self.kernel_base = self.project.loader.kernel_object.mapped_base
  File "/root/.virtualenvs/angr/lib/python3.8/site-packages/cle/loader.py", line 240, in kernel_object
    self._map_object(self._kernel_object)
  File "/root/.virtualenvs/angr/lib/python3.8/site-packages/cle/loader.py", line 912, in _map_object
    self.memory.add_backer(base_addr, obj.memory)
  File "/root/.virtualenvs/angr/lib/python3.8/site-packages/cle/memory.py", line 211, in add_backer
    raise ValueError("Address %#x is already backed!" % start)
ValueError: Address 0x0 is already backed!

```

Is there a easy way to bypass without breaking angr's internals? I'd like to continue to analyze the binaries till you release the fix.

**Comment by ltfish** [comment]
Can you share the file so that we can reproduce it?

**Comment by rhelmot** [comment]
I don't think this will be a difficult fix, but I will need to see the binary to do it.

**Comment by sahinburak** [comment]
Attached is a sample core file which angr creates the error above:
[core.2144.zip](https://github.com/angr/angr/files/10833155/core.2144.zip)

**Comment by rhelmot** [comment]
Fixed!
