### ISSUE TITLE
Flaky test case test_decompiling_dd_advance_input_after_read_error

### ISSUE THREAD

**Issue by ltfish** [angr/angr#3863]
### Description

This test case fails non-deterministically on angr CI. Output:

```
======================================================================
FAIL: test_decompiling_dd_advance_input_after_read_error (test_decompiler.TestDecompiler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/angr/angr/build/src/angr/tests/test_decompiler.py", line 60, in inner
    ret_vals.append(func(*args, decompiler_options=new_opts, **kwargs))
  File "/__w/angr/angr/build/src/angr/tests/test_decompiler.py", line 1890, in test_decompiling_dd_advance_input_after_read_error
    assert re.search(r"v\d=__errno_location\(\);\*\(v\d\)=input_seek_errno;", condensed)
AssertionError
```

**Comment by twizmwazin** [comment]
No longer applicable
