### ISSUE TITLE
TypeError: unsupported operand type(s) for //: 'RichR' and 'RichR

### ISSUE THREAD

**Issue by zwimer** [angr/angr#3901]
### Description

Loading a binary causes this traceback:
```
ERROR    | 2023-04-12 18:31:14,759 | angrmanagement.data.instance | Exception while running job "Variable Recovery":
Traceback (most recent call last):
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angrmanagement/data/instance.py", line 337, in _worker
    result = job.run(self)
             ^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angrmanagement/data/jobs/job.py", line 69, in run
    r = self._run(inst)
        ^^^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angrmanagement/data/jobs/variable_recovery.py", line 88, in _run
    self.ccc.work()
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/complete_calling_conventions.py", line 158, in work
    cc, proto, _ = self._analyze_core(func_addr)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/complete_calling_conventions.py", line 293, in _analyze_core
    _ = self.project.analyses[VariableRecoveryFast].prep(kb=self.kb)(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/analysis.py", line 128, in wrapper
    oself.__init__(*args, **kwargs)
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/variable_recovery/variable_recovery_fast.py", line 280, in __init__
    self._analyze()
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 253, in _analyze
    self._analysis_core_graph()
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 270, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/variable_recovery/variable_recovery_fast.py", line 416, in _run_on_node
    self._process_block(state, block)
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/variable_recovery/variable_recovery_fast.py", line 530, in _process_block
    processor.process(state, block=block, fail_fast=self._fail_fast)
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/variable_recovery/engine_base.py", line 87, in process
    self._process(state, None, block=kwargs.pop("block", None))
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/engines/light/engine.py", line 143, in _process
    self._process_Stmt(whitelist=whitelist)
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/variable_recovery/engine_vex.py", line 49, in _process_Stmt
    super()._process_Stmt(whitelist=whitelist)
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/engines/light/engine.py", line 163, in _process_Stmt
    self._handle_Stmt(stmt)
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/engines/light/engine.py", line 191, in _handle_Stmt
    getattr(self, handler)(stmt)
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/variable_recovery/engine_vex.py", line 72, in _handle_WrTmp
    super()._handle_WrTmp(stmt)
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/engines/light/engine.py", line 197, in _handle_WrTmp
    data = self._expr(stmt.data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/analyses/variable_recovery/engine_vex.py", line 141, in _expr
    r = super()._expr(expr)
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/engines/light/engine.py", line 228, in _expr
    return getattr(self, handler)(expr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/engines/light/engine.py", line 367, in _handle_Binop
    return getattr(self, handler)(expr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zwimer/.virtualenvs/zion/lib/python3.11/site-packages/angr/engines/light/engine.py", line 582, in _handle_Mod
    return expr_0 - (expr_1 // expr_1) * expr_1
                     ~~~~~~~^^~~~~~~~
TypeError: unsupported operand type(s) for //: 'RichR' and 'RichR'
```

### Steps to reproduce the bug

On macOS 13.3.1:
1. `pip install` in a new virtualenv
2. `angr-management`
3. `File -> Load a new Binary`
4. Load `/usr/bin/stapler`

### Environment

Version: 9.2.46
OS: macOS 13.3.1
Python: 3.11.3
Installed from pip in a new virtualenv

### Additional context

[The full log output](https://github.com/angr/angr/files/11217354/log.txt)

**Comment by zwimer** [comment]
[stapler.zip](https://github.com/angr/angr/files/11231828/stapler.zip)

**Comment by zwimer** [comment]
Attached above @ltfish
