### ISSUE TITLE
AssertionError assert node == self._addr_to_block_node[node.addr] generating CFGFast

### ISSUE THREAD

**Issue by roj4s** [angr/angr#408]
```
b1 = angr.Project(exe_1, load_options={'auto_load_libs': False})
cfg_1 = b1.analyses.CFGFast(fail_fast=True)
```

```
Traceback (most recent call last):
  File "/home/rojas/mestrado/angr_lab/main.py", line 41, in <module>
    cfg_1 = b1.analyses.CFGFast(fail_fast=True)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 741, in __init__
    self._analyze()
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 239, in _analyze
    self._handle_entry(entry_info)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 258, in _handle_entry
    successors = self._get_successors(entry)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 1082, in _get_successors
    return self._scan_block(addr, current_function_addr, jumpkind, src_node, src_ins_addr, src_stmt_idx)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 1343, in _scan_block
    previous_src_ins_addr, previous_src_stmt_idx)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 1449, in _scan_irsb
    self._function_add_node(addr, current_function_addr)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 3207, in _function_add_node
    self.kb.functions._add_node(function_addr, node)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/knowledge/function_manager.py", line 75, in _add_node
    dst_func._register_nodes(True, node)
  File "/home/rojas/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/knowledge/function.py", line 558, in _register_nodes
    assert node == self._addr_to_block_node[node.addr]
AssertionError
```

**Comment by ltfish** [comment]
I updated your issue to make it more readable. In fact, I just removed that assertion as we never triggered it before... how did you trigger it? Can you please provide us with your binary?

**Comment by roj4s** [comment]
I just executed the code provided with an instance of malware mutated with one of Zombi3's creations.

**Comment by ltfish** [comment]
It'll be great if you can post the exact binary somewhere so I can run the CFG on that binary and figure out why this bug happens. Otherwise I'll have to wait until someone triggers this issue next time and posts the binary he uses.

**Comment by roj4s** [comment]
Sure, give me a minute ...

**Comment by ltfish** [comment]
Thank you in advance!

I'm going to bed. Will look into this issue tomorrow!

**Comment by roj4s** [comment]
It's here: https://goo.gl/t3uZHR

**Comment by ltfish** [comment]
I debugged it, and found out the issue: `SimEngineVEX` will decode as many bytes as possible without considering section boundaries. It decodes a basic block starting from `0x4b8fe2` until `0x4b9001`. However, while `0x4b8fe2` is in `.code` section, `.data` section begins from `0x4b9000`.

`CFGFast` takes section boundaries into consideration, so it correctly terminates the basic block `0x4b8fe2` before reaching address `0x4b9000`.

Hence blocks of two different sizes are created (one is 31 bytes, the other is 30 bytes). The solution is to pass in a `size` to `SimEngineVEX.lift()` from angr - in this case specifically, from all places in `function_manager.py` where `self._kb._project.factory.snippet()` is called. I'll fix it when I have some free cycles.

Thanks again for providing the sample.

**Comment by ltfish** [comment]
Also you binary is really stressing `CFGFast`'s stupid implementation of memory coverage detection, as there are many nonconsecutive code blocks.

**Comment by roj4s** [comment]
That's because of trash code insertion metamorphic technique implemented in Zombi3's permutator. From your debug: can you tell if the file is executable, I mean, if it would execute successfully ?? Thanks.

**Comment by ltfish** [comment]
> From your debug: can you tell if the file is executable, I mean, if it would execute successfully ??

Are you asking me if the binary will execute fine on a real Windows system? Obviously I didn't try to run it... Why would I do so knowing it's a piece of malware?

**Comment by roj4s** [comment]
Yup sure, that's why I asked: "From your debug" lol. So you can't tell if it would execute nicely from your debug analysis? Thanks
