### ISSUE TITLE
Excessive extension of the zero_extend inside fgets

### ISSUE THREAD

**Issue by ch4rli3kop** [angr/angr#4154]
### Description

Hi, I found a bug in `/procedures/libc/fgets.py`.
The `zero_extend` expands the `size` variable to a larger size than it actually is.

https://github.com/angr/angr/blob/0932d21a027cc38945b989917d361758da15fec1/angr/procedures/libc/fgets.py#L16

For example, in an x86_64 binary, the `size` variable in `fgets` has a size of `BV64`, but the `zero_extend` function makes it `BV96`. The `size` variable is then passed to the `read_data` function, where it has a size of `BV96`. 

https://github.com/angr/angr/blob/0932d21a027cc38945b989917d361758da15fec1/angr/procedures/libc/fgets.py#L50

This `size` variable performs an operation on here with the `pos` variable whose size is `BV64`, and an error occurs because of the different size of the operation.

https://github.com/angr/angr/blob/0932d21a027cc38945b989917d361758da15fec1/angr/storage/file.py#L294

The traceback is as follows

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ch4rli3kop/code_snippets/angr/angr/storage/file.py", line 896, in read_data
    data, realsize, self._pos = self.file.read(self._pos, size)
  File "/Users/ch4rli3kop/code_snippets/angr/angr/storage/file.py", line 294, in read
    self._size = self.state.solver.If(size + pos > self._size, size + pos, self._size)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tangr/lib/python3.10/site-packages/claripy/operations.py", line 54, in _op
    raise ClaripyOperationError(msg)
claripy.errors.ClaripyOperationError: args' length must all be equal
```

The length of the `size` variable is same as `arch.bits` when testing arm32, arm64, x86, and x86-64

**Comment by ch4rli3kop** [comment]
here you go [test_file.zip](https://github.com/angr/angr/files/12602311/test_file.zip)

**Comment by mborgerson** [comment]
> here you go [test_file.zip](https://github.com/angr/angr/files/12602311/test_file.zip)

I tested the binary with basic exploration and did not encounter the same issue? Was the right binary sent? It appears this binary is for aarch64 architecture, but above x86-64 was mentioned specifically.

Can you also send whatever script you're testing with, and share your angr environment details (`python -m angr.misc.bug_report`).

**Comment by ch4rli3kop** [comment]
This happens when I intercept the `fgets` function. Does this behavior is intended when intercepting any functions? I've noticed that the `size` variable is `BV64` in a 64-bit architecture and `BV32` in a 32-bit architecture. In an unhooked environment, the `size` variable is `BV32` in a 64-bit architecture. Now that I look at it, I think this is the intended behavior.

```python
import angr

class fgets_summary(angr.SimProcedure):
    def run(self, dst, src, file_ptr):
        print(src)

proj = angr.Project('test.out', auto_load_libs=False)

proj.analyses.CFGFast(normalize=True)

proj.hook_symbol('fgets', fgets_summary())

state = proj.factory.entry_state()
simgr = proj.factory.simgr(state)
simgr.run()
# result:
# <BV64 0x61>
```





My environment is like below.

```shell
(angr) ---------------------------------------------------------------------------------------------------------------------------------
ch4rli3kop in [~] 9:51:33 › python3 -m angr.misc.bug_report
/home/ch4rli3kop/.local/lib/python3.10/site-packages/angr/misc/bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2023-09-19 09:51:40.496851
!!! running in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
######## angr #########
Python found it in /home/ch4rli3kop/.local/lib/python3.10/site-packages/angr
Pip version angr 9.2.66
Couldn't find git info
######## ailment #########
Python found it in /home/ch4rli3kop/.local/lib/python3.10/site-packages/ailment
Pip version ailment 9.2.66
Couldn't find git info
######## cle #########
Python found it in /home/ch4rli3kop/.local/lib/python3.10/site-packages/cle
Pip version cle 9.2.66
Couldn't find git info
######## pyvex #########
Python found it in /home/ch4rli3kop/.local/lib/python3.10/site-packages/pyvex
Pip version pyvex 9.2.66
Couldn't find git info
######## claripy #########
Python found it in /home/ch4rli3kop/.local/lib/python3.10/site-packages/claripy
Pip version claripy 9.2.66
Couldn't find git info
######## archinfo #########
Python found it in /home/ch4rli3kop/.local/lib/python3.10/site-packages/archinfo
Pip version archinfo 9.2.66
Couldn't find git info
######## z3 #########
Python found it in /home/ch4rli3kop/.local/lib/python3.10/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/ch4rli3kop/.local/lib/python3.10/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/ch4rli3kop/.local/lib/python3.10/site-packages/angr/state_plugins/../lib/angr_native.so', handle 561c6257cab0 at 0x7f8cb1786920>
unicorn: <CDLL '/home/ch4rli3kop/.local/lib/python3.10/site-packages/unicorn/lib/libunicorn.so.2', handle 561c61fd4a80 at 0x7f8cb4696cb0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f8cb536e1a0>
z3: <CDLL '/home/ch4rli3kop/.local/lib/python3.10/site-packages/z3/lib/libz3.so', handle 561c61c82850 at 0x7f8cb729e560>
```
