### ISSUE TITLE
Encountered error while analyzing mips64 program on x86 system

### ISSUE THREAD

**Issue by an-oo-na** [angr/angr#4172]
### Question

my system:
```Linux ubuntu 5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```

Program source code:
```
#include <stdio.h>
#include <stdlib.h>

int main(){
	char buf[100] = {0};
	int size = 0;
	printf("Hello: ");
	scanf("%d", &size);
	if(size < 0){
		printf("No, size must bigger than 0!\n");
		return -1;
	}else if(size < 100){
		printf("Yes, that's right!\n");
	} else {
		printf("That's crazy!\n");
	}
	size = fread(buf, size, 1, stdin);
	if(size < 0){
		printf("No, something wrong!\n");
		return -1;
	}else if(size < 100){
		printf("Yes, that's right!\n");
	} else {
		printf("That's crazy!\n");
	}
	
	printf("Thanks for your %s\n", buf);
	return 0;
}
```

my angr script:
```
import angr
import sys
import claripy

def main(argv):
  path_to_binary = './test.out'
#   path_to_binary = './111.out'
  project = angr.Project(path_to_binary)
  initial_state = project.factory.entry_state()
  simulation = project.factory.simgr(initial_state)

  def is_successful(state):
    # print(dir(state))
    stdout_output = state.posix.dumps(1)
    print("find: ",stdout_output,hex(state.addr))
    return b"Yes, that's right!" in stdout_output # :boolean

  def should_abort(state):
    stdout_output = state.posix.dumps(1)
    # print("avoid: " , stdout_output,hex(state.addr))
    return b"That's crazy!" in stdout_output  # :boolean

#   simulation.explore(find=is_successful, avoid=should_abort)
  simulation.explore(find=is_successful)

  if simulation.found:
    solution_state = simulation.found[0]
    print(solution_state.posix.dumps(0))
  else:
    raise Exception('Could not find the solution')

if __name__ == '__main__':
  main(sys.argv)
```

When I compile the program in mips64 operating system and use python script on x86 to analyze it, I get the following error:
```
ERROR    | 2023-09-17 19:29:27,895 | archinfo.arch  | Please look up and add dynamic tag type 0x70000036 for MIPS64
find:  b'' 0x120000a40
find:  b'' 0x120000a4c
find:  b'' 0x120143130
find:  b'' 0x120000de0
find:  b'' 0x1200011e4
find:  b'' 0x120001370
find:  b'' 0x1200014fc
find:  b'' 0x120001688
find:  b'' 0x120001814
find:  b'' 0x1200019a0
find:  b'' 0x120001b2c
find:  b'' 0x120001cb8
find:  b'' 0x120001e44
find:  b'' 0x120001fd0
find:  b'' 0x120002000
Traceback (most recent call last):
  File "/root/Documents/4.3/111.py", line 96, in <module>
    main(sys.argv)
  File "/root/Documents/4.3/111.py", line 93, in main
    raise Exception('Could not find the solution')
Exception: Could not find the solution
```
Why does the above error occur? How can i solve it?

**Comment by twizmwazin** [comment]
Sorry we couldn't get to your issue, please let us know if you still need help.
