### ISSUE TITLE
megatest: DECOMPILER_FAIL-TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by mborgerson** [angr/angr#4278]
### Description

```
### EVENT: DECOMPILER_FAIL
### Package: <standalone>
### Binary: samples/windows/drivers/winquic.sys
### Function: sub_1c001fecc
### Execption:
Traceback (most recent call last):
File "/megatest/analyze_binary.py", line 27, in catcher
yield
File "/megatest/analyze_binary.py", line 141, in _doit_core
decompilation = elf.analyses.Decompiler(func, cfg=cfg)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/decompiler.py", line 95, in __init__
self._decompile()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/decompiler.py", line 242, in _decompile
codegen = self.project.analyses.StructuredCodeGenerator(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 2342, in __init__
self._analyze()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 2408, in _analyze
self.regenerate_text()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 2431, in regenerate_text
) = self.render_text(self.cfunc)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 2441, in render_text
text = cfunc.c_repr(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 369, in c_repr
return "".join(mapper(self.c_repr_chunks(indent)))
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 283, in mapper
for s, obj in chunks:
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 582, in c_repr_chunks
yield from self.statements.c_repr_chunks(indent=indent + INDENT_DELTA)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 659, in c_repr_chunks
yield from stmt.c_repr_chunks(indent=indent, asexpr=asexpr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 926, in c_repr_chunks
yield from node.c_repr_chunks(indent=INDENT_DELTA + indent)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 659, in c_repr_chunks
yield from stmt.c_repr_chunks(indent=indent, asexpr=asexpr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 926, in c_repr_chunks
yield from node.c_repr_chunks(indent=INDENT_DELTA + indent)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 659, in c_repr_chunks
yield from stmt.c_repr_chunks(indent=indent, asexpr=asexpr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 659, in c_repr_chunks
yield from stmt.c_repr_chunks(indent=indent, asexpr=asexpr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 1251, in c_repr_chunks
yield from CExpression._try_c_repr_chunks(arg)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 640, in _try_c_repr_chunks
yield from expr.c_repr_chunks()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/structured_codegen/c.py", line 2039, in c_repr_chunks
if self.reference_values is not None and self._type is not None and self._type in self.reference_values:
File "/megatest/venv/lib/python3.10/site-packages/angr/sim_type.py", line 69, in __hash__
out ^= hash(getattr(self, attr))
File "/megatest/venv/lib/python3.10/site-packages/angr/sim_type.py", line 69, in __hash__
out ^= hash(getattr(self, attr))
TypeError: unhashable type: 'list'
```

### Environment

angr environment report
=============================
Date: 2023-11-07 00:59:29.806968
Running in virtual environment at /megatest/venv
Platform: linux-x86_64
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
######## angr #########
Python found it in /megatest/venv/lib/python3.10/site-packages/angr
Pip version angr 9.2.76.dev0
Couldn't find git info
######## ailment #########
Python found it in /megatest/venv/lib/python3.10/site-packages/ailment
Pip version ailment 9.2.76.dev0
Couldn't find git info
######## cle #########
Python found it in /megatest/venv/lib/python3.10/site-packages/cle
Pip version cle 9.2.76.dev0
Couldn't find git info
######## pyvex #########
Python found it in /megatest/venv/lib/python3.10/site-packages/pyvex
Pip version pyvex 9.2.76.dev0
Couldn't find git info
######## claripy #########
Python found it in /megatest/venv/lib/python3.10/site-packages/claripy
Pip version claripy 9.2.76.dev0
Couldn't find git info
######## archinfo #########
Python found it in /megatest/venv/lib/python3.10/site-packages/archinfo
Pip version archinfo 9.2.76.dev0
Couldn't find git info
######## z3 #########
Python found it in /megatest/venv/lib/python3.10/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /megatest/venv/lib/python3.10/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/megatest/venv/lib/python3.10/site-packages/angr/state_plugins/../lib/angr_native.so', handle 55ff3565abb0 at 0x7f6df72d69e0>
unicorn: <CDLL '/megatest/venv/lib/python3.10/site-packages/unicorn/lib/libunicorn.so.2', handle 55ff3509cef0 at 0x7f6dfa1a2470>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f6dfaea52d0>
z3: <CDLL '/megatest/venv/lib/python3.10/site-packages/z3/lib/libz3.so', handle 55ff34e0a950 at 0x7f6dfcbf4e20>

**Comment by twizmwazin** [comment]
Fixed in https://github.com/angr/angr/pull/4357
