### ISSUE TITLE
megatest: DECOMPILER_FAIL-AttributeError: 'NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by mborgerson** [angr/angr#4295]
### Description

```
### EVENT: DECOMPILER_FAIL
### Package: <standalone>
### Binary: samples/windows/drivers/snapman.sys
### Function: sub_140027158
### Execption:
Traceback (most recent call last):
File "/megatest/analyze_binary.py", line 27, in catcher
yield
File "/megatest/analyze_binary.py", line 141, in _doit_core
decompilation = elf.analyses.Decompiler(func, cfg=cfg)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/decompiler.py", line 95, in __init__
self._decompile()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/decompiler.py", line 156, in _decompile
clinic = self.project.analyses.Clinic(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 111, in __init__
self._analyze()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 285, in _analyze
ail_graph = self._run_simplification_passes(ail_graph, stage=OptimizationPassStage.AFTER_GLOBAL_SIMPLIFICATION)
File "/megatest/venv/lib/python3.10/site-packages/angr/utils/timing.py", line 43, in timed_func
return func(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 798, in _run_simplification_passes
a = pass_(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/optimization_passes/ite_region_converter.py", line 29, in __init__
self.analyze()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/optimization_passes/optimization_pass.py", line 71, in analyze
self._analyze(cache=cache)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/optimization_passes/ite_region_converter.py", line 38, in _analyze
ite_assign_regions = self._find_ite_assignment_regions()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/optimization_passes/ite_region_converter.py", line 89, in _find_ite_assignment_regions
elif child.addr == if_stmt.false_target.value:
AttributeError: 'NoneType' object has no attribute 'value'
```

### Environment

angr environment report
=============================
Date: 2023-11-07 00:59:29.806968
Running in virtual environment at /megatest/venv
Platform: linux-x86_64
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
######## angr #########
Python found it in /megatest/venv/lib/python3.10/site-packages/angr
Pip version angr 9.2.76.dev0
Couldn't find git info
######## ailment #########
Python found it in /megatest/venv/lib/python3.10/site-packages/ailment
Pip version ailment 9.2.76.dev0
Couldn't find git info
######## cle #########
Python found it in /megatest/venv/lib/python3.10/site-packages/cle
Pip version cle 9.2.76.dev0
Couldn't find git info
######## pyvex #########
Python found it in /megatest/venv/lib/python3.10/site-packages/pyvex
Pip version pyvex 9.2.76.dev0
Couldn't find git info
######## claripy #########
Python found it in /megatest/venv/lib/python3.10/site-packages/claripy
Pip version claripy 9.2.76.dev0
Couldn't find git info
######## archinfo #########
Python found it in /megatest/venv/lib/python3.10/site-packages/archinfo
Pip version archinfo 9.2.76.dev0
Couldn't find git info
######## z3 #########
Python found it in /megatest/venv/lib/python3.10/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /megatest/venv/lib/python3.10/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/megatest/venv/lib/python3.10/site-packages/angr/state_plugins/../lib/angr_native.so', handle 55ff3565abb0 at 0x7f6df72d69e0>
unicorn: <CDLL '/megatest/venv/lib/python3.10/site-packages/unicorn/lib/libunicorn.so.2', handle 55ff3509cef0 at 0x7f6dfa1a2470>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f6dfaea52d0>
z3: <CDLL '/megatest/venv/lib/python3.10/site-packages/z3/lib/libz3.so', handle 55ff34e0a950 at 0x7f6dfcbf4e20>

**Comment by twizmwazin** [comment]
Fixed in current version
