### ISSUE TITLE
megatest: DECOMPILER_FAIL-claripy.errors.ClaripyZeroDivisionError

### ISSUE THREAD

**Issue by mborgerson** [angr/angr#4302]
### Description

```
### EVENT: DECOMPILER_FAIL
### Package: <standalone>
### Binary: samples/windows/drivers/RTKVHD64.sys
### Function: sub_43e178
### Execption:
Traceback (most recent call last):
File "/megatest/analyze_binary.py", line 27, in catcher
yield
File "/megatest/analyze_binary.py", line 141, in _doit_core
decompilation = elf.analyses.Decompiler(func, cfg=cfg)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/decompiler.py", line 95, in __init__
self._decompile()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/decompiler.py", line 156, in _decompile
clinic = self.project.analyses.Clinic(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 111, in __init__
self._analyze()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 312, in _analyze
variable_kb = self._recover_and_link_variables(ail_graph, arg_list)
File "/megatest/venv/lib/python3.10/site-packages/angr/utils/timing.py", line 43, in timed_func
return func(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 1002, in _recover_and_link_variables
vr = self.project.analyses.VariableRecoveryFast(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/variable_recovery_fast.py", line 284, in __init__
self._analyze()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 252, in _analyze
self._analysis_core_graph()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 269, in _analysis_core_graph
changed, output_state = self._run_on_node(n, job_state)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/variable_recovery_fast.py", line 434, in _run_on_node
self._process_block(state, block)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/variable_recovery_fast.py", line 553, in _process_block
processor.process(state, block=block, fail_fast=self._fail_fast)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_base.py", line 87, in process
self._process(state, None, block=kwargs.pop("block", None))
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 800, in _process
self._process_Stmt(whitelist=whitelist)
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 816, in _process_Stmt
self._handle_Stmt(stmt)
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 866, in _handle_Stmt
getattr(self, old_handler)(stmt)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 46, in _ail_handle_Assignment
data = self._expr(stmt.src)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 191, in _expr
r = super()._expr(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 836, in _expr
return h(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 237, in _ail_handle_BinaryOp
r = super()._ail_handle_BinaryOp(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 949, in _ail_handle_BinaryOp
return handler(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 315, in _ail_handle_Add
r0 = self._expr(arg0)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 191, in _expr
r = super()._expr(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 836, in _expr
return h(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 237, in _ail_handle_BinaryOp
r = super()._ail_handle_BinaryOp(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 949, in _ail_handle_BinaryOp
return handler(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 371, in _ail_handle_Mul
r0 = self._expr(arg0)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 191, in _expr
r = super()._expr(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 836, in _expr
return h(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 237, in _ail_handle_BinaryOp
r = super()._ail_handle_BinaryOp(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/engines/light/engine.py", line 949, in _ail_handle_BinaryOp
return handler(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/variable_recovery/engine_ail.py", line 426, in _ail_handle_Div
quotient = r0.data / claripy.ZeroExt(from_size - to_size, r1.data)
File "/megatest/venv/lib/python3.10/site-packages/claripy/utils/deprecated.py", line 16, in inner
return func(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/claripy/operations.py", line 72, in _op
return return_type(name, fixed_args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/claripy/ast/base.py", line 203, in __new__
r = operations._handle_annotations(eb._abstract(eb.call(op, args)), args)
File "/megatest/venv/lib/python3.10/site-packages/claripy/backends/__init__.py", line 251, in call
return self._call(op, converted)
File "/megatest/venv/lib/python3.10/site-packages/claripy/backends/__init__.py", line 271, in _call
obj = getattr(operator, op)(*args)
File "/megatest/venv/lib/python3.10/site-packages/claripy/bv.py", line 45, in normalize_helper
return f(self, o)
File "/megatest/venv/lib/python3.10/site-packages/claripy/bv.py", line 17, in compare_guard
return f(self, o)
File "/megatest/venv/lib/python3.10/site-packages/claripy/bv.py", line 123, in __floordiv__
raise ClaripyZeroDivisionError()
claripy.errors.ClaripyZeroDivisionError
```

### Environment

angr environment report
=============================
Date: 2023-11-07 00:59:29.806968
Running in virtual environment at /megatest/venv
Platform: linux-x86_64
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
######## angr #########
Python found it in /megatest/venv/lib/python3.10/site-packages/angr
Pip version angr 9.2.76.dev0
Couldn't find git info
######## ailment #########
Python found it in /megatest/venv/lib/python3.10/site-packages/ailment
Pip version ailment 9.2.76.dev0
Couldn't find git info
######## cle #########
Python found it in /megatest/venv/lib/python3.10/site-packages/cle
Pip version cle 9.2.76.dev0
Couldn't find git info
######## pyvex #########
Python found it in /megatest/venv/lib/python3.10/site-packages/pyvex
Pip version pyvex 9.2.76.dev0
Couldn't find git info
######## claripy #########
Python found it in /megatest/venv/lib/python3.10/site-packages/claripy
Pip version claripy 9.2.76.dev0
Couldn't find git info
######## archinfo #########
Python found it in /megatest/venv/lib/python3.10/site-packages/archinfo
Pip version archinfo 9.2.76.dev0
Couldn't find git info
######## z3 #########
Python found it in /megatest/venv/lib/python3.10/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /megatest/venv/lib/python3.10/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/megatest/venv/lib/python3.10/site-packages/angr/state_plugins/../lib/angr_native.so', handle 55ff3565abb0 at 0x7f6df72d69e0>
unicorn: <CDLL '/megatest/venv/lib/python3.10/site-packages/unicorn/lib/libunicorn.so.2', handle 55ff3509cef0 at 0x7f6dfa1a2470>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f6dfaea52d0>
z3: <CDLL '/megatest/venv/lib/python3.10/site-packages/z3/lib/libz3.so', handle 55ff34e0a950 at 0x7f6dfcbf4e20>

**Comment by twizmwazin** [comment]
Fixed in current angr
