### ISSUE TITLE
megatest: DECOMPILER_FAIL-ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by mborgerson** [angr/angr#4308]
### Description

```
### EVENT: DECOMPILER_FAIL
### Package: <standalone>
### Binary: samples/windows/drivers/ahcache.sys
### Function: sub_1c0006dd4
### Execption:
Traceback (most recent call last):
File "/megatest/analyze_binary.py", line 27, in catcher
yield
File "/megatest/analyze_binary.py", line 141, in _doit_core
decompilation = elf.analyses.Decompiler(func, cfg=cfg)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/decompiler.py", line 95, in __init__
self._decompile()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/decompiler.py", line 156, in _decompile
clinic = self.project.analyses.Clinic(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 111, in __init__
self._analyze()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 227, in _analyze
ail_graph = self._simplify_blocks(
File "/megatest/venv/lib/python3.10/site-packages/angr/utils/timing.py", line 43, in timed_func
return func(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 655, in _simplify_blocks
simplified = self._simplify_block(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/clinic.py", line 693, in _simplify_block
simp = self.project.analyses.AILBlockSimplifier(
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
r = w(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
oself.__init__(*args, **kwargs)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/block_simplifier.py", line 100, in __init__
self._analyze()
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/block_simplifier.py", line 117, in _analyze
new_block = self._simplify_block_once(block)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/block_simplifier.py", line 199, in _simplify_block_once
new_block = self._peephole_optimize(new_block)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/block_simplifier.py", line 402, in _peephole_optimize
peephole_optimize_exprs(block, self._expr_peephole_opts)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/utils.py", line 472, in peephole_optimize_exprs
walker.walk(block)
File "/megatest/venv/lib/python3.10/site-packages/ailment/block_walker.py", line 58, in walk
self._handle_stmt(i, stmt, block)
File "/megatest/venv/lib/python3.10/site-packages/ailment/block_walker.py", line 190, in _handle_stmt
return handler(stmt_idx, stmt, block)
File "/megatest/venv/lib/python3.10/site-packages/ailment/block_walker.py", line 221, in _handle_Assignment
src = self._handle_expr(1, stmt.src, stmt_idx, stmt, block)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/utils.py", line 467, in _handle_expr
return ailment.AILBlockWalker._handle_expr(walker, expr_idx, expr, stmt_idx, stmt, block)
File "/megatest/venv/lib/python3.10/site-packages/ailment/block_walker.py", line 202, in _handle_expr
expr = handler(expr_idx, expr, stmt_idx, stmt, block)
File "/megatest/venv/lib/python3.10/site-packages/ailment/block_walker.py", line 431, in _handle_Convert
new_operand = self._handle_expr(expr_idx, expr.operand, stmt_idx, stmt, block)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/utils.py", line 455, in _handle_expr
r = expr_opt.optimize(expr, stmt_idx=stmt_idx, block=block)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/peephole_optimizations/const_mull_a_shift.py", line 27, in optimize
r = self.optimize_binaryop(expr)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/peephole_optimizations/const_mull_a_shift.py", line 44, in optimize_binaryop
divisor = self._check_divisor(pow(2, V), C, ndigits)
File "/megatest/venv/lib/python3.10/site-packages/angr/analyses/decompiler/peephole_optimizations/const_mull_a_shift.py", line 90, in _check_divisor
divisor_1 = 1 + (a // b)
ZeroDivisionError: integer division or modulo by zero
```

### Environment

angr environment report
=============================
Date: 2023-11-07 00:59:29.806968
Running in virtual environment at /megatest/venv
Platform: linux-x86_64
Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
######## angr #########
Python found it in /megatest/venv/lib/python3.10/site-packages/angr
Pip version angr 9.2.76.dev0
Couldn't find git info
######## ailment #########
Python found it in /megatest/venv/lib/python3.10/site-packages/ailment
Pip version ailment 9.2.76.dev0
Couldn't find git info
######## cle #########
Python found it in /megatest/venv/lib/python3.10/site-packages/cle
Pip version cle 9.2.76.dev0
Couldn't find git info
######## pyvex #########
Python found it in /megatest/venv/lib/python3.10/site-packages/pyvex
Pip version pyvex 9.2.76.dev0
Couldn't find git info
######## claripy #########
Python found it in /megatest/venv/lib/python3.10/site-packages/claripy
Pip version claripy 9.2.76.dev0
Couldn't find git info
######## archinfo #########
Python found it in /megatest/venv/lib/python3.10/site-packages/archinfo
Pip version archinfo 9.2.76.dev0
Couldn't find git info
######## z3 #########
Python found it in /megatest/venv/lib/python3.10/site-packages/z3
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /megatest/venv/lib/python3.10/site-packages/unicorn
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/megatest/venv/lib/python3.10/site-packages/angr/state_plugins/../lib/angr_native.so', handle 55ff3565abb0 at 0x7f6df72d69e0>
unicorn: <CDLL '/megatest/venv/lib/python3.10/site-packages/unicorn/lib/libunicorn.so.2', handle 55ff3509cef0 at 0x7f6dfa1a2470>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f6dfaea52d0>
z3: <CDLL '/megatest/venv/lib/python3.10/site-packages/z3/lib/libz3.so', handle 55ff34e0a950 at 0x7f6dfcbf4e20>

**Comment by twizmwazin** [comment]
Fixed in current angr
