### ISSUE TITLE
Unable to run CFGFast on statically linked binary

### ISSUE THREAD

**Issue by rakshithrevanna** [angr/angr#4364]
### Description

Hello,
I am learning binary analysis using angr tool. Recently I tried to carry out CFG generation using angr function analyses.CFGFast(). I'm using a statically linked binary with -no-pie parameter.
I need some guide to resolve the error I am encountering because I'm still getting a grip on the tool :)
I am encountering some issues as mentioned below in the code snippet.
```
 $ file programs/aes/crypt_and_hash
 programs/aes/crypt_and_hash: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=de778114c87cf7eb6b306774e06c05d5ccf95c9e, for GNU/Linux 3.2.0, not stripped
 $ python3
 Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
 Type "help", "copyright", "credits" or "license" for more information.
 >>> import angr
 >>> proj = angr.Project('programs/aes/crypt_and_hash', auto_load_libs=False)
 >>> proj.arch
 <Arch AMD64 (LE)>
 >>> cfg = proj.analyses.CFGFast()
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 216, in __call__
     r = w(*args, **kwargs)
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/analysis.py", line 201, in wrapper
     oself.__init__(*args, **kwargs)
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/cfg/cfg_fast.py", line 838, in __init__
     self._analyze()
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 247, in _analyze
     self._analysis_core_baremetal()
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 390, in _analysis_core_baremetal
     self._process_job_and_get_successors(job_info)
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 408, in _process_job_and_get_successors
     successors = self._get_successors(job)
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/cfg/cfg_fast.py", line 1335, in _get_successors
     jobs = self._scan_block(job)
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/cfg/cfg_fast.py", line 1792, in _scan_block
     entries = self._scan_procedure(cfg_job, current_func_addr)
   File "/home/rakshith/PycharmProjects/Angr-Experiment/venv/lib/python3.10/site-packages/angr/analyses/cfg/cfg_fast.py", line 1858, in _scan_procedure
     self.functions.contains_addr(cfg_job.src_node.addr)
 AttributeError: 'NoneType' object has no attribute 'addr'
 >>>
```

**Comment by jiliguluss** [comment]
> Yes, I found that version 9.2.69 works fine. However, starting from version 9.2.70, this issue persists. I didn't get time to look into the bug :)是的，我发现 9.2.69 版运行良好。但是，从版本 9.2.70 开始，此问题仍然存在。我没有时间研究这个错误:)

I am also troubled by this problem. I am using version 9.2.92.

**Comment by ltfish** [comment]
This is a dup of https://github.com/angr/angr/issues/4526 and has been fixed in https://github.com/angr/angr/pull/4529.
