### ISSUE TITLE
RuntimeError in `ddg.simplified_data_graph` and Proposed Fix

### ISSUE THREAD

**Issue by hwu71** [angr/angr#4396]
### Description

I encountered a RuntimeError while running `ddg.simplified_data_graph` in angr. The error message is: "RuntimeError: dictionary changed size during iteration."

I've identified a potential fix:
```
--- a/angr/analyses/ddg.py
+++ b/angr/analyses/ddg.py
@@ -1418,8 +1418,8 @@ class DDG(Analysis):
 
         for tmp_node in all_nodes:
             # remove each tmp node by linking their successors and predecessors directly
-            in_edges = graph.in_edges(tmp_node, data=True)
-            out_edges = graph.out_edges(tmp_node, data=True)
+            in_edges = list(graph.in_edges(tmp_node, data=True))
+            out_edges = list(graph.out_edges(tmp_node, data=True))
 
             for pred, _, _ in in_edges:
                 graph.remove_edge(pred, tmp_node)
```
However, I'm not completely sure if this is the best solution. Could you please review this fix? Thanks!

### Steps to reproduce the bug

How to reproduce: Modify `tests/analyses/test_ddg.py` by adding a line to call `ddg.simplified_data_graph`:
```
@@ -37,6 +37,7 @@ class TestDDG(unittest.TestCase):
         l.info("CFG generated in %f seconds.", duration)
 
         ddg = proj.analyses.DDG(cfg, start=cfg.functions["main"].addr)
+       g = ddg.simplified_data_graph
         # There should be at least 400 nodes
         assert len(ddg.graph) >= 400
```
Results:
```
======================================================================
ERROR: test_ddg_0 (__main__.TestDDG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../angr-dev/angr/tests/analyses/test_ddg.py", line 92, in test_ddg_0
    self.perform_one(binary_path)
  File ".../angr-dev/angr/tests/analyses/test_ddg.py", line 40, in perform_one
    g = ddg.simplified_data_graph
  File ".../angr-dev/angr/angr/analyses/ddg.py", line 570, in simplified_data_graph
    self._simplified_data_graph = self._simplify_data_graph(self.data_graph)
  File ".../angr-dev/angr/angr/analyses/ddg.py", line 1424, in _simplify_data_graph
    for pred, _, _ in in_edges:
  File ".../.virtualenvs/angr/lib/python3.8/site-packages/networkx/classes/reportviews.py", line 1018, in <genexpr>
    for k, dd in kd.items()
RuntimeError: dictionary changed size during iteration

----------------------------------------------------------------------
```

### Environment

tag = 9.2.82

**Comment by hahaleyile** [comment]
No further fixes?
