### ISSUE TITLE
Symbolic memory: unexpected load results

### ISSUE THREAD

**Issue by ercoppa** [angr/angr#444]
Hi,

I am playing with angr for a research project. Please, look at this script:
```
import angr
import simuvex
import claripy

binary = '/bin/ls' # we don't care for the binary, we just need an initial state
project = angr.Project(binary, load_options={'auto_load_libs' : False})

state = project.factory.entry_state(remove_options={simuvex.o.LAZY_SOLVES}, 
	add_options={simuvex.o.SYMBOLIC_WRITE_ADDRESSES}) # store range => 128, load range => 1024 

# an address which is in a valid region
start_addr = state.libc.heap_location 
state.libc.heap_location += 32 # mark 32 bytes as used 

# read/write 
assert state.se.any_int(state.memory.permissions(start_addr)) == 0x3
assert state.se.any_int(state.memory.permissions(start_addr + 1)) == 0x3
assert state.se.any_int(state.memory.permissions(start_addr + 2)) == 0x3

# initialize memory: 3 bytes starting at start_addr
state.memory.store(start_addr, claripy.BVV(0x0, 24), 3)

# a symbolic pointer that can be equal to [start_addr, start_addr + 1]
addr = claripy.BVS('addr', 64) 
state.se.add(addr >= start_addr)
state.se.add(addr <= start_addr + 1)
addrs = state.se.any_n_int(addr, 10)
assert len(addrs) == 2 and set(addrs) == set([start_addr, start_addr + 1])

val = 0xABCD

# symbolic store at addr
state.memory.store(addr, claripy.BVV(val, 16), 2)

# symbolic load at addr
res = state.memory.load(addr, 2)

# print res

res = state.se.any_n_int(res, 20) # up to 20 solutions
print "Obtained value(s): " + (' '.join(hex(x) for x in res))
print "Expected value:    " + hex(val)
 
assert len(res) == 1 and res[0] == val
```
Output:
```
Obtained value(s): 0xabcd 0xab00L
Expected value:    0xabcd
Traceback (most recent call last):
  File "run.py", line 43, in <module>
    assert len(res) == 1 and res[0] == val
AssertionError

```
I do not understand why I don't get what I expect (i.e., `res` should be always equal to the value of `val`). What am I missing? Is it an actual bug?

**Comment by ercoppa** [comment]
A real C code (`symbolic_access.c`) that shows the same issue:
```
#include <stdio.h>
#include <stdlib.h>

int foo(int * p, int x) {
	*p = x;
	return *p;
}

int bar(int i) {
	if (i < 0 || i > 1) return -1;
	char * b = malloc(8);
	int res = foo((int *)(b + i), 10);
	return res;
}

int main(int argc, char * argv[]) {
	if (argc != 2) return -1;
	int i = atoi(argv[1]);
	int res = bar(i);
	printf("res: %d\n", res);
	return 0;
}
```
Compiled as
```
gcc -o symbolic_access symbolic_access.c -m32
```
Script:
```
import angr
import struct
import claripy
import simuvex

project = angr.Project('symbolic_access', load_options={'auto_load_libs':False})

start =  0x804847d # start address of bar()
avoid = 0x804848f # uninteresting branches of bar() where -1 is returned
end = 0x804847c # ret of foo()

add_options=None
add_options={simuvex.o.SYMBOLIC_WRITE_ADDRESSES}
state = project.factory.blank_state(addr=start, remove_options={simuvex.o.LAZY_SOLVES}, add_options=add_options)

pg = project.factory.path_group(state, veritesting=False)

while len(pg.active) > 0:

	print pg
	pg.explore(avoid=avoid, find=end, n=1)

	if pg.found:
		state = pg.found[0].state
		v = state.regs.eax
		sol = state.se.any_n_int(v, 10)
		print "Expected value   : " + hex(10)
		print "Obtained value(s): " + ' '.join(hex(x) for x in sol)
		assert set(sol) == set([10])
		break
```
Output:
```
<PathGroup with 1 active>
<PathGroup with 1 avoid, 1 active>
<PathGroup with 2 avoid, 1 active>
<PathGroup with 2 avoid, 1 active>
<PathGroup with 2 avoid, 1 active>
<PathGroup with 2 avoid, 1 active>
Expected value   : 0xa
Obtained value(s): 0x180110aL 0xa 0x1980210aL 0x1180210aL 0x980210aL 0x180230aL 0x180030aL 0x180210aL 0x180010aL 0x180130aL
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    assert set(sol) == set([10])
AssertionError
```

**Comment by ltfish** [comment]
@ercoppa I'm a little confused. Doesn't `i` have two possible values 0 and 1 in function `bar`?

**Comment by ercoppa** [comment]
@ltfish Yes, but:

- if `i = 0` then `foo` writes `x` (`x=10`) at `b` and reads from `b` => it should return `x`
- if `i = 1` then `foo` writes `x` (`x=10`) at `b+1` and reads from `b+1` => it should return `x`

Am i right?

**Comment by ltfish** [comment]
Huh, it might be a bug in how symbolic memory accesses are handled. @zardus ?

**Comment by ercoppa** [comment]
#568 has fixed this issue. Thank you. I'am closing this discussion.

**Comment by ltfish** [comment]
Good to know!
