### ISSUE TITLE
Error occurs in decompilation when a struct is being handled

### ISSUE THREAD

**Issue by bluesadi** [angr/angr#4441]
### Description

This bug is found after angr's new type inference algorithm was deployed.

### Steps to reproduce the bug

```py
>>> import angr
>>> proj = angr.Project("target_o3", auto_load_libs=False)
>>> cfg = proj.analyses.CFGFast(normalize=True)
>>> decompiler = proj.analyses.Decompiler(cfg=cfg, func=0x408AA0)
```

```
Traceback (most recent call last):
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\decompiler\clinic.py", line 1154, in _recover_and_link_variables
    tp = self.project.analyses.Typehoon(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\analysis.py", line 216, in __call__
    r = w(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\analysis.py", line 201, in wrapper
    oself.__init__(*args, **kwargs)
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typehoon.py", line 62, in __init__
    self._analyze()
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typehoon.py", line 144, in _analyze
    self._specialize()
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typehoon.py", line 178, in _specialize
    specialized = self._specialize_struct(sol)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typehoon.py", line 186, in _specialize_struct
    specialized = self._specialize_struct(tc.basetype, memo={tc} if memo is None else memo | {tc})
                                                            ^^^^
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typeconsts.py", line 141, in __hash__
    return self._hash(set())
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typeconsts.py", line 135, in _hash
    return hash((type(self), self.basetype._hash(visited)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typeconsts.py", line 206, in _hash
    return hash((type(self), self._hash_fields(visited)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typeconsts.py", line 210, in _hash_fields
    tpl = tuple((k, self.fields[k]._hash(visited)) for k in keys)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yibol\Envs\angr\Lib\site-packages\angr\analyses\typehoon\typeconsts.py", line 210, in <genexpr>
    tpl = tuple((k, self.fields[k]._hash(visited)) for k in keys)
                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_hash'
```

### Environment

```
angr environment report
=============================
Date: 2024-02-02 15:00:37.892712
Running in virtual environment at C:\Users\yibol\Envs\angr
C:\Users\yibol\Envs\angr\Lib\site-packages\angr\misc\bug_report.py:88: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources  # pylint:disable=import-outside-toplevel
Platform: win-amd64
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
######## angr #########
Python found it in C:\Users\yibol\Envs\angr\Lib\site-packages\angr\__init__.py
Pip version angr 9.2.88
Couldn't find git info
######## ailment #########
Python found it in C:\Users\yibol\Envs\angr\Lib\site-packages\ailment\__init__.py
Pip version ailment 9.2.88
Couldn't find git info
######## cle #########
Python found it in C:\Users\yibol\Envs\angr\Lib\site-packages\cle\__init__.py
Pip version cle 9.2.88
Couldn't find git info
######## pyvex #########
Python found it in C:\Users\yibol\Envs\angr\Lib\site-packages\pyvex\__init__.py
Pip version pyvex 9.2.88
Couldn't find git info
######## claripy #########
Python found it in C:\Users\yibol\Envs\angr\Lib\site-packages\claripy\__init__.py
Pip version claripy 9.2.88
Couldn't find git info
######## archinfo #########
Python found it in C:\Users\yibol\Envs\angr\Lib\site-packages\archinfo\__init__.py
Pip version archinfo 9.2.88
Couldn't find git info
######## z3 #########
Python found it in C:\Users\yibol\Envs\angr\Lib\site-packages\z3\__init__.py
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in C:\Users\yibol\Envs\angr\Lib\site-packages\unicorn\__init__.py
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL 'C:\Users\yibol\Envs\angr\Lib\site-packages\angr\lib\angr_native.dll', handle 7fffd9fa0000 at 0x159177e74d0>
unicorn: <CDLL 'C:\Users\yibol\Envs\angr\Lib\site-packages\unicorn\lib\unicorn.dll', handle 7ff81f940000 at 0x15915477090>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x00000159150E8850>
z3: <CDLL 'C:\Users\yibol\Envs\angr\Lib\site-packages\z3\lib\libz3.dll', handle 7fffdb360000 at 0x15914d12b50>
```

**Comment by bluesadi** [comment]
[target_o3.zip](https://github.com/angr/angr/files/14145925/target_o3.zip)
