### ISSUE TITLE
angr.errors.SimSolverModeError: Claripy threw an error

### ISSUE THREAD

**Issue by DennyDai** [angr/angr#4449]
### Description

```python
Traceback (most recent call last):
  File "/home/[redacted]/angr/storage/memory_mixins/slotted_memory.py", line 81, in _single_load
    d = self.contents[addr]
KeyError: 24

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/[redacted]/claripy/frontends/light_frontend.py", line 42, in eval
    return tuple(self._solver_backend.eval(e, n))
  File "/home/[redacted]/claripy/backends/__init__.py", line 532, in eval
    self.convert(expr),
  File "/home/[redacted]/claripy/backends/backend_concrete.py", line 115, in convert
    return super().convert(expr)
  File "/home/[redacted]/claripy/backends/__init__.py", line 171, in convert
    converted = self._convert(ast)
  File "/home/[redacted]/claripy/backends/backend_concrete.py", line 136, in _convert
    raise BackendError("can't handle AST of type %s" % type(a))
claripy.errors.BackendError: can't handle AST of type <class 'NoneType'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/[redacted]/angr/state_plugins/solver.py", line 93, in wrapped_f
    return f(*args, **kwargs)
  File "/home/[redacted]/angr/state_plugins/solver.py", line 596, in _eval
    return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/[redacted]/claripy/frontend_mixins/concrete_handler_mixin.py", line 7, in eval
    return super().eval(e, n, **kwargs)
  File "/home/[redacted]/claripy/frontend_mixins/constraint_filter_mixin.py", line 40, in eval
    return super().eval(e, n, extra_constraints=ec, **kwargs)
  File "/home/[redacted]/claripy/frontends/light_frontend.py", line 44, in eval
    raise ClaripyFrontendError("Light solver can't handle this eval().") from e
claripy.errors.ClaripyFrontendError: Light solver can't handle this eval().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/han/purseclab/BinBench/evaluation_scripts/tooloutput_collector/han/angr_script.py", line 180, in <module>
    result = run_angr(sys.argv[1])
  File "/home/han/purseclab/BinBench/evaluation_scripts/tooloutput_collector/han/angr_script.py", line 14, in run_angr
    cfg = p.analyses.CFGFast(data_references=True, normalize=True)
  File "/home/[redacted]/angr/analyses/analysis.py", line 216, in __call__
    r = w(*args, **kwargs)
  File "/home/[redacted]/angr/analyses/analysis.py", line 201, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/[redacted]/angr/analyses/cfg/cfg_fast.py", line 844, in __init__
    self._analyze()
  File "/home/[redacted]/angr/analyses/forward_analysis/forward_analysis.py", line 247, in _analyze
    self._analysis_core_baremetal()
  File "/home/[redacted]/angr/analyses/forward_analysis/forward_analysis.py", line 390, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/home/[redacted]/angr/analyses/forward_analysis/forward_analysis.py", line 408, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/home/[redacted]/angr/analyses/cfg/cfg_fast.py", line 1341, in _get_successors
    jobs = self._scan_block(job)
  File "/home/[redacted]/angr/analyses/cfg/cfg_fast.py", line 1885, in _scan_block
    entries = self._scan_procedure(cfg_job, current_func_addr)
  File "/home/[redacted]/angr/analyses/cfg/cfg_fast.py", line 1972, in _scan_procedure
    new_exits = procedure.static_exits(blocks_ahead, cfg=self)
  File "/home/[redacted]/angr/procedures/posix/pthread.py", line 28, in static_exits
    irsb = self.project.factory.default_engine.process(state, b, force_addr=b.addr)
  File "/home/[redacted]/angr/engines/vex/light/slicing.py", line 20, in process
    return super().process(*args, **kwargs)
  File "/home/[redacted]/angr/engines/engine.py", line 163, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/[redacted]/angr/engines/failure.py", line 24, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/[redacted]/angr/engines/syscall.py", line 26, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/[redacted]/angr/engines/hook.py", line 56, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "/home/[redacted]/angr/engines/unicorn.py", line 389, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/[redacted]/angr/engines/soot/engine.py", line 68, in process_successors
    return super().process_successors(successors, **kwargs)
  File "/home/[redacted]/angr/engines/vex/heavy/heavy.py", line 174, in process_successors
    self.handle_vex_block(irsb)
  File "/home/[redacted]/angr/engines/vex/heavy/super_fastpath.py", line 25, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/[redacted]/angr/engines/vex/light/slicing.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/[redacted]/angr/engines/vex/heavy/actions.py", line 31, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/[redacted]/angr/engines/vex/heavy/inspect.py", line 49, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/home/[redacted]/angr/engines/vex/light/light.py", line 550, in handle_vex_block
    self._handle_vex_defaultexit(irsb.next, irsb.jumpkind)
  File "/home/[redacted]/angr/engines/vex/light/slicing.py", line 36, in _handle_vex_defaultexit
    super()._handle_vex_defaultexit(expr, jumpkind)
  File "/home/[redacted]/angr/engines/vex/light/light.py", line 553, in _handle_vex_defaultexit
    self._perform_vex_defaultexit(self._analyze_vex_defaultexit(expr) if expr is not None else None, jumpkind)
  File "/home/[redacted]/angr/engines/vex/heavy/actions.py", line 237, in _perform_vex_defaultexit
    super()._perform_vex_defaultexit(target, jumpkind)
  File "/home/[redacted]/angr/engines/vex/heavy/heavy.py", line 368, in _perform_vex_defaultexit
    self.successors.add_successor(
  File "/home/[redacted]/angr/engines/successors.py", line 131, in add_successor
    self._preprocess_successor(state, add_guard=add_guard)
  File "/home/[redacted]/angr/engines/successors.py", line 173, in _preprocess_successor
    self._manage_callstack(state)
  File "/home/[redacted]/angr/engines/successors.py", line 224, in _manage_callstack
    cur_sp = state.solver.max(state.regs._sp) if state.has_plugin("symbolizer") else state.regs._sp
  File "/home/[redacted]/angr/state_plugins/view.py", line 41, in __getattr__
    return state.registers.load(k, inspect=inspect, disable_actions=disable_actions, events=events)
  File "/home/[redacted]/angr/storage/memory_mixins/name_resolution_mixin.py", line 65, in load
    return super().load(named_addr, size=named_size if size is None else size, **kwargs)
  File "/home/[redacted]/angr/storage/memory_mixins/simple_interface_mixin.py", line 10, in load
    return super().load(
  File "/home/[redacted]/angr/storage/memory_mixins/clouseau_mixin.py", line 66, in load
    return super().load(addr, size=size, condition=condition, endness=endness, inspect=inspect, **kwargs)
  File "/home/[redacted]/angr/storage/memory_mixins/conditional_store_mixin.py", line 8, in load
    res = super().load(addr, condition=condition, **kwargs)
  File "/home/[redacted]/angr/storage/memory_mixins/slotted_memory.py", line 113, in load
    value = claripy.Concat(*(self._single_load(addr, offset, size) for addr, offset, size in accesses))
  File "/home/[redacted]/angr/storage/memory_mixins/slotted_memory.py", line 113, in <genexpr>
    value = claripy.Concat(*(self._single_load(addr, offset, size) for addr, offset, size in accesses))
  File "/home/[redacted]/angr/storage/memory_mixins/slotted_memory.py", line 83, in _single_load
    d = self._default_value(addr, self.width, self.variable_key_prefix + (addr,), **kwargs)
  File "/home/[redacted]/angr/storage/memory_mixins/default_filler_mixin.py", line 141, in _default_value
    return super()._default_value(addr, size, inspect=inspect, events=events, **kwargs)
  File "/home/[redacted]/angr/storage/memory_mixins/default_filler_mixin.py", line 85, in _default_value
    refplace_int = self.state.solver.eval(self.state._ip)
  File "/home/[redacted]/angr/state_plugins/solver.py", line 890, in eval
    return self.eval_upto(e, 1, cast_to, **kwargs)[0]
  File "/home/[redacted]/angr/state_plugins/solver.py", line 850, in eval_upto
    cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
  File "/home/[redacted]/angr/state_plugins/solver.py", line 171, in concrete_shortcut_tuple
    return f(self, *args, **kwargs)
  File "/home/[redacted]/angr/state_plugins/sim_action_object.py", line 61, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/home/[redacted]/angr/state_plugins/solver.py", line 97, in wrapped_f
    raise SimSolverModeError("Claripy threw an error") from e
angr.errors.SimSolverModeError: Claripy threw an error
```

### Steps to reproduce the bug

```python
import angr

p = angr.Project("52c33913cadd49acf7a1d0335951ba8af6374cf99ae110dcf1f7f19314092752", load_options={"auto_load_libs": False, 'main_opts': {'base_addr': 0x0}})
cfg = p.analyses.CFGFast(data_references=True, normalize=True)
p.analyses[angr.analyses.CompleteCallingConventionsAnalysis].prep()(recover_variables=True)
```

### Environment

```bash
$ python3 -m angr.misc.bug_report
angr environment report
=============================
Date: 2024-02-08 17:23:05.970696
Running in virtual environment at /home/[redacted]/angr
/home/[redacted]/angr/lib/python3.10/site-packages/angr/misc/bug_report.py:88: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources  # pylint:disable=import-outside-toplevel
Platform: linux-x86_64
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
######## angr #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/angr/__init__.py
Pip version angr 9.2.89
Couldn't find git info
######## ailment #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/ailment/__init__.py
Pip version ailment 9.2.89
Couldn't find git info
######## cle #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/cle/__init__.py
Pip version cle 9.2.89
Couldn't find git info
######## pyvex #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/pyvex/__init__.py
Pip version pyvex 9.2.89
Couldn't find git info
######## claripy #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/claripy/__init__.py
Pip version claripy 9.2.89
Couldn't find git info
######## archinfo #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/archinfo/__init__.py
Pip version archinfo 9.2.89
Couldn't find git info
######## z3 #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/z3/__init__.py
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/unicorn/__init__.py
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/[redacted]/angr/lib/python3.10/site-packages/angr/state_plugins/../lib/angr_native.so', handle 562fd072a940 at 0x7f8cbbf29f90>
unicorn: <CDLL '/home/[redacted]/angr/lib/python3.10/site-packages/unicorn/lib/libunicorn.so.2', handle 562fd0190540 at 0x7f8cbf067f70>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f8cbfde6920>
z3: <CDLL '/home/[redacted]/angr/lib/python3.10/site-packages/z3/lib/libz3.so', handle 562fcfe2f0b0 at 0x7f8cc1cf7be0>
```

### Additional context

Binary for reproducing the error:

[52c33913cadd49acf7a1d0335951ba8af6374cf99ae110dcf1f7f19314092752.zip](https://github.com/angr/angr/files/14215831/52c33913cadd49acf7a1d0335951ba8af6374cf99ae110dcf1f7f19314092752.zip)

**Comment by zardus** [comment]
Are these bugs the result of a analysis engine analyzing angr? Now we just need it to actually fix angr :P

**Comment by DennyDai** [comment]
Sadly we are just extracting information from lots of binaries using angr, no fancy analysis engine doing the magic for us. :(
