### ISSUE TITLE
false positive functions in `p.kb.functions`

### ISSUE THREAD

**Issue by DennyDai** [angr/angr#4450]
### Description

I was trying to decompile all the functions in the binary, and decompiling "function" at 0x2070 gives following exception:

```python
Traceback (most recent call last):
  File "/home/[redacted]/ailment/tagged_object.py", line 29, in __getattr__
    return self.tags[item]
KeyError: 'ret_exprs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/han/scratch/binbenchfeb7/_angr.py", line 17, in <module>
    p.analyses.Decompiler(func, cfg=cfg)
  File "/home/[redacted]/angr/analyses/analysis.py", line 216, in __call__
    r = w(*args, **kwargs)
  File "/home/[redacted]/angr/analyses/analysis.py", line 201, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/[redacted]/angr/analyses/decompiler/decompiler.py", line 97, in __init__
    self._decompile()
  File "/home/[redacted]/angr/analyses/decompiler/decompiler.py", line 206, in _decompile
    clinic.graph, ri = self._run_region_simplification_passes(
  File "/home/[redacted]/angr/utils/timing.py", line 43, in timed_func
    return func(*args, **kwargs)
  File "/home/[redacted]/angr/analyses/decompiler/decompiler.py", line 356, in _run_region_simplification_passes
    a = pass_(
  File "/home/[redacted]/angr/analyses/decompiler/optimization_passes/return_duplicator.py", line 70, in __init__
    self.analyze()
  File "/home/[redacted]/angr/analyses/decompiler/optimization_passes/optimization_pass.py", line 290, in analyze
    self._fixed_point_analyze(cache=cache)
  File "/home/[redacted]/angr/analyses/decompiler/optimization_passes/optimization_pass.py", line 325, in _fixed_point_analyze
    changes = self._analyze(cache=cache)
  File "/home/[redacted]/angr/analyses/decompiler/optimization_passes/return_duplicator.py", line 86, in _analyze
    endnode_regions = self._copy_connected_edge_components(endnode_regions, self.out_graph)
  File "/home/[redacted]/angr/analyses/decompiler/optimization_passes/return_duplicator.py", line 246, in _copy_connected_edge_components
    is_single_const_ret_region = self._is_simple_return_graph(region)
  File "/home/[redacted]/angr/analyses/decompiler/optimization_passes/return_duplicator.py", line 339, in _is_simple_return_graph
    ret_exprs = ret_stmt.ret_exprs
  File "/home/[redacted]/ailment/tagged_object.py", line 31, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'Jump' object has no attribute 'ret_exprs'
```

after checking the disasm, 0x2070 doesn't seems like a function start

```asm
.text:00002070 loc_2070:                               ; CODE XREF: quotearg_buffer_restyled+46E↑j
.text:00002070                                         ; DATA XREF: .rodata:jpt_206E↓o
.text:00002070                 test    [ebp+backslash_escapes], 1 ; jumptable 0000206E case 0
.text:00002074                 jz      loc_218D
.text:0000207A                 test    [ebp+elide_outer_quotes], 1
.text:0000207E                 jz      loc_2089
.text:00002084                 jmp     force_outer_quoting_style
```

### Steps to reproduce the bug

```python
import angr

p = angr.Project("hello_O0.o", load_options={"auto_load_libs": False, 'main_opts': {'base_addr': 0x0}})
cfg = p.analyses.CFGFast(data_references=True, normalize=True)
p.analyses[angr.analyses.CompleteCallingConventionsAnalysis].prep()(recover_variables=True)

for func in p.kb.functions.values():
    print(f"Function {hex(func.addr)}: {func.name}")

func = p.kb.functions[0x2070]
p.analyses.Decompiler(func, cfg=cfg)
```

### Environment

Binary:
[hello_O0.zip](https://github.com/angr/angr/files/14215898/hello_O0.zip)

**Comment by mahaloz** [comment]
@DennyDai, do you know for certain if that place should be a function or not? It looks like I just messed up some checks on duplication for functions ending in a jmp as an exit.

**Comment by DennyDai** [comment]
@mahaloz It shouldn't be a function. 0x2070 should be part of the function that starts at 0x1c00, which contains a jump table (for switch-case) that angr failed to resolve.

**Comment by mahaloz** [comment]
@DennyDai can you actually open another issue for the false positive function? Even without it being a false positive, it should not crash in the optimization loop. I'll use this issue to track that bug.

**Comment by DennyDai** [comment]
@mahaloz sure, I've opened #4460 just now, thanks for looking into this!
