### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_hash' when decompiling 

### ISSUE THREAD

**Issue by DennyDai** [angr/angr#4452]
### Description

```python
Traceback (most recent call last):
  File "/home/[redacted]/angr/analyses/decompiler/clinic.py", line 1154, in _recover_and_link_variables
    tp = self.project.analyses.Typehoon(
  File "/home/[redacted]/angr/analyses/analysis.py", line 216, in __call__
    r = w(*args, **kwargs)
  File "/home/[redacted]/angr/analyses/analysis.py", line 201, in wrapper
    oself.__init__(*args, **kwargs)
  File "/home/[redacted]/angr/analyses/typehoon/typehoon.py", line 62, in __init__
    self._analyze()
  File "/home/[redacted]/angr/analyses/typehoon/typehoon.py", line 144, in _analyze
    self._specialize()
  File "/home/[redacted]/angr/analyses/typehoon/typehoon.py", line 178, in _specialize
    specialized = self._specialize_struct(sol)
  File "/home/[redacted]/angr/analyses/typehoon/typehoon.py", line 186, in _specialize_struct
    specialized = self._specialize_struct(tc.basetype, memo={tc} if memo is None else memo | {tc})
  File "/home/[redacted]/angr/analyses/typehoon/typeconsts.py", line 141, in __hash__
    return self._hash(set())
  File "/home/[redacted]/angr/analyses/typehoon/typeconsts.py", line 135, in _hash
    return hash((type(self), self.basetype._hash(visited)))
  File "/home/[redacted]/angr/analyses/typehoon/typeconsts.py", line 207, in _hash
    return hash((type(self), self._hash_fields(visited)))
  File "/home/[redacted]/angr/analyses/typehoon/typeconsts.py", line 211, in _hash_fields
    tpl = tuple((k, self.fields[k]._hash(visited)) for k in keys)
  File "/home/[redacted]/angr/analyses/typehoon/typeconsts.py", line 211, in <genexpr>
    tpl = tuple((k, self.fields[k]._hash(visited)) for k in keys)
AttributeError: 'NoneType' object has no attribute '_hash'
```

### Steps to reproduce the bug

```python
import angr

p = angr.Project("procan_O0.o", load_options={"auto_load_libs": False, 'main_opts': {'base_addr': 0x0}})
cfg = p.analyses.CFGFast(data_references=True, normalize=True)
p.analyses[angr.analyses.CompleteCallingConventionsAnalysis].prep()(recover_variables=True)

func = p.kb.functions[0xf070]
p.analyses.Decompiler(func, cfg=cfg)
```

### Environment

```bash
$ python3 -m angr.misc.bug_report
angr environment report
=============================
Date: 2024-02-08 17:23:05.970696
Running in virtual environment at /home/[redacted]/angr
/home/[redacted]/angr/lib/python3.10/site-packages/angr/misc/bug_report.py:88: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources  # pylint:disable=import-outside-toplevel
Platform: linux-x86_64
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
######## angr #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/angr/__init__.py
Pip version angr 9.2.89
Couldn't find git info
######## ailment #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/ailment/__init__.py
Pip version ailment 9.2.89
Couldn't find git info
######## cle #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/cle/__init__.py
Pip version cle 9.2.89
Couldn't find git info
######## pyvex #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/pyvex/__init__.py
Pip version pyvex 9.2.89
Couldn't find git info
######## claripy #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/claripy/__init__.py
Pip version claripy 9.2.89
Couldn't find git info
######## archinfo #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/archinfo/__init__.py
Pip version archinfo 9.2.89
Couldn't find git info
######## z3 #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/z3/__init__.py
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/[redacted]/angr/lib/python3.10/site-packages/unicorn/__init__.py
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/[redacted]/angr/lib/python3.10/site-packages/angr/state_plugins/../lib/angr_native.so', handle 562fd072a940 at 0x7f8cbbf29f90>
unicorn: <CDLL '/home/[redacted]/angr/lib/python3.10/site-packages/unicorn/lib/libunicorn.so.2', handle 562fd0190540 at 0x7f8cbf067f70>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f8cbfde6920>
z3: <CDLL '/home/[redacted]/angr/lib/python3.10/site-packages/z3/lib/libz3.so', handle 562fcfe2f0b0 at 0x7f8cc1cf7be0>
```

### Additional context

[procan_O0.zip](https://github.com/angr/angr/files/14215947/procan_O0.zip)

**Comment by DennyDai** [comment]
sorry duplicated with #4441
