### ISSUE TITLE
`test_armhf_elf_static_using_armel_libc` failing on nightly CI

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr#4518]
### Description

```
======================================================================
ERROR: test_armhf_elf_static_using_armel_libc (tests.analyses.test_flirt.TestFlirt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/angr/angr/build/src/angr/tests/analyses/test_flirt.py", line 33, in test_armhf_elf_static_using_armel_libc
    proj.analyses.CFGFast(show_progressbar=False)
  File "/__w/angr/angr/build/src/angr/angr/analyses/analysis.py", line 216, in __call__
    r = w(*args, **kwargs)
  File "/__w/angr/angr/build/src/angr/angr/analyses/analysis.py", line 201, in wrapper
    oself.__init__(*args, **kwargs)
  File "/__w/angr/angr/build/src/angr/angr/analyses/cfg/cfg_fast.py", line 844, in __init__
    self._analyze()
  File "/__w/angr/angr/build/src/angr/angr/analyses/forward_analysis/forward_analysis.py", line 247, in _analyze
    self._analysis_core_baremetal()
  File "/__w/angr/angr/build/src/angr/angr/analyses/forward_analysis/forward_analysis.py", line 367, in _analysis_core_baremetal
    self._job_queue_empty()
  File "/__w/angr/angr/build/src/angr/angr/analyses/cfg/cfg_fast.py", line 1465, in _job_queue_empty
    self._process_unresolved_indirect_jumps()
  File "/__w/angr/angr/build/src/angr/angr/analyses/cfg/cfg_base.py", line 2859, in _process_unresolved_indirect_jumps
    all_targets |= self._process_one_indirect_jump(jump)
  File "/__w/angr/angr/build/src/angr/angr/analyses/cfg/cfg_base.py", line 2890, in _process_one_indirect_jump
    resolved, targets = resolver.resolve(
  File "/__w/angr/angr/build/src/angr/angr/analyses/cfg/indirect_jump_resolvers/const_resolver.py", line 108, in resolve
    func = cfg.functions[func_addr]
  File "/__w/angr/angr/build/src/angr/angr/knowledge_plugins/functions/function_manager.py", line 321, in __getitem__
    raise KeyError(k)
KeyError: 883185
```

### Environment

Nightly CI

### Additional context

Happened across windows/macos/linux, so unlikely to be random

**Comment by ltfish** [comment]
I've just fixed that in https://github.com/angr/angr/pull/4517. It should no longer fail starting from tonight.

**Comment by twizmwazin** [comment]
Seems unfixed unfortunately: https://github.com/angr/angr/actions/runs/8303814169/job/22728682294#step:5:181

**Comment by ltfish** [comment]
Yeah I saw. Will push a fix tonight.

**Comment by twizmwazin** [comment]
Seems fixed as of now.
