### ISSUE TITLE
KeyError: 'x86_cr0'

### ISSUE THREAD

**Issue by geemion** [angr/angr#46]
>>> p=angr.Project('/home/xx/project/fake')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 152, in __init__
    self._simos.configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 125, in configure_project
    super(SimLinux, self).configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 42, in configure_project
    self.proj.loader.perform_irelative_relocs(irelative_resolver)
  File "/usr/local/lib/python2.7/dist-packages/cle-4.5.11.23-py2.7.egg/cle/loader.py", line 704, in perform_irelative_relocs
    val = resolver_func(resolver)
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 31, in irelative_resolver
    val = resolver()
  File "/usr/local/lib/python2.7/dist-packages/angr/surveyors/caller.py", line 41, in call_get_return_val
    return self.get_call_results(*args)[0]
  File "/usr/local/lib/python2.7/dist-packages/angr/surveyors/caller.py", line 74, in get_call_results
    caller_end_unpruned = caller.step(until=lambda pg: len(pg.active) == 0, step_func=step_func if self._concrete_only else None).unstash(from_stash='deadended')
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 536, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 342, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 287, in _one_path_step
    successors = a.step(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path.py", line 221, in step
    self._make_sim_run()
  File "/usr/local/lib/python2.7/dist-packages/angr/path.py", line 246, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 117, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 59, in sim_block
    **block_opts)
  File "/usr/local/lib/python2.7/dist-packages/angr/lifter.py", line 116, in lift
    traceflags=traceflags)
  File "pyvex/__init__.py", line 136, in __init__
    c_irsb = pvc.vex_block_bytes(vex_arch, arch.vex_archinfo, c_bytes + bytes_offset, mem_addr, num_bytes, 1)
KeyError: 'x86_cr0'

**Comment by ltfish** [comment]
We are all very busy recently, so please give us several days before we can answer this. And I bet @rhelmot knows what's going on with that error.

Additionally, please provide the binary "fake" if you can.

**Comment by geemion** [comment]
ok.thank you 。the bin 'fake' is  a example
https://github.com/angr/angr-doc/tree/master/examples/asisctffinals2015_fake

**Comment by geemion** [comment]
i  ask the question at here （https://github.com/angr/pyvex/issues/20）also
