### ISSUE TITLE
fail to load a blob with Linux simos

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#4602]
### Description

```
    bio = io.BytesIO(b"\x58\xC3\x0F\x05") # pop rax; ret; syscall
    proj = angr.Project(bio, main_opts={'backend': 'blob', 'arch': 'amd64'}, simos='linux')
```
This will crash will the following message
```
Traceback (most recent call last):
  File "/home/kylebot/src/angr-dev/angrop/tests/test_backend.py", line 39, in <module>
    run_all()
  File "/home/kylebot/src/angr-dev/angrop/tests/test_backend.py", line 28, in run_all
    all_functions[f]()
  File "/home/kylebot/src/angr-dev/angrop/tests/test_backend.py", line 15, in test_blob
    proj = angr.Project(bio, main_opts={'backend': 'blob', 'arch': 'amd64'}, simos='linux')
  File "/home/kylebot/src/angr-dev/angr/build/__editable__.angr-9.2.98.dev0-py3-none-any/angr/project.py", line 258, in __init__
    self.simos.configure_project()
  File "/home/kylebot/src/angr-dev/angr/build/__editable__.angr-9.2.98.dev0-py3-none-any/angr/simos/linux.py", line 103, in configure_project
    tls_obj = self.project.loader.tls.new_thread()
  File "/home/kylebot/src/angr-dev/cle/build/__editable__.cle-9.2.98.dev0-py3-none-any/cle/backends/tls/tls_object.py", line 46, in new_thread
    thread = self._thread_cls(self)
  File "/home/kylebot/src/angr-dev/cle/build/__editable__.cle-9.2.98.dev0-py3-none-any/cle/backends/tls/tls_object.py", line 54, in _thread_cls
    raise NotImplementedError("This platform doesn't have an implementation of thread-local storage")
NotImplementedError: This platform doesn't have an implementation of thread-local storage
```

**Comment by ltfish** [comment]
This is fixed by #4603. Closed.
