### ISSUE TITLE
Failed to load a binary

### ISSUE THREAD

**Issue by Voxanimus** [angr/angr#4605]
### Description

I tried to load a binary and get this error:
```
  File "/usr/local/lib/python3.10/dist-packages/cle/memory.py", line 363, in load
    raise KeyError(addr)
KeyError: -32768
```

the thing is the the -32768 match is the opposite of the binary base address witch is 0x8000. I don't understand why I get this error and why the key is negative.

**Comment by Voxanimus** [comment]
Sure here it is:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/src/trustdymbex/__main__.py", line 347, in <module>
    main(sys.argv[1])
  File "/src/trustdymbex/__main__.py", line 325, in main
    runner: Runner = Runner(binary_path, report.base_address)
  File "/src/trustdymbex/__main__.py", line 122, in __init__
    self._p = Project(
  File "/usr/local/lib/python3.10/dist-packages/angr/project.py", line 224, in __init__
    self.simos.configure_project()
  File "/usr/local/lib/python3.10/dist-packages/angr/simos/linux.py", line 78, in configure_project
    tls_obj = self.project.loader.tls.new_thread()
  File "/usr/local/lib/python3.10/dist-packages/cle/backends/tls/__init__.py", line 33, in new_thread
    thread = self._thread_cls(self)
  File "/usr/local/lib/python3.10/dist-packages/cle/backends/tls/elf_tls.py", line 92, in __init__
    image = thread_manager.initialization_image(obj)
  File "/usr/local/lib/python3.10/dist-packages/cle/backends/tls/__init__.py", line 30, in initialization_image
    return obj.memory.load(obj.tls_data_start, obj.tls_data_size).ljust(obj.tls_block_size, b'\0')
  File "/usr/local/lib/python3.10/dist-packages/cle/memory.py", line 363, in load
    raise KeyError(addr)
KeyError: -32768
```

**Comment by rhelmot** [comment]
What architecture is this binary built for? it's for linux, right?

**Comment by Voxanimus** [comment]
Yap

**Comment by rhelmot** [comment]
those were two separate questions. what architecture is it for? amd64? mips? arm?

**Comment by Voxanimus** [comment]
It is arm but my bad it is not for linux, it is for android.

**Comment by twizmwazin** [comment]
Fixed in current version
