### ISSUE TITLE
Current usability of symbolic floating point numbers

### ISSUE THREAD

**Issue by burtonwilliamt** [angr/angr#466]
Hello!

I've been trying to dig into how much angr can do with floating point numbers. Specifically, I'm trying to create a claripy.FPS('arg1', claripy.FSORT_FLOAT) object and pass that into the argument of a function that takes a float and returns a float. I am trying to create an initial state using factory.call_state() which all works, but then when I try to explore to an address with a path_group, I get the error below.

I don't know if this is a duplicate, as it is rather similar to #112 but I can't tell if this problem is because FPS are not supported fully, or if I am doing something wrong.

My relevant code is:
```python
import angr
import claripy

p = angr.Project("./theBinary", load_options={'auto_load_libs':False})

arg1 = claripy.FPS('arg1', claripy.FSORT_FLOAT)

initial_state = p.factory.call_state(0x4004b6, arg1) #the base of the function is at 0x4004b6 
pg = p.factory.path_group(initial_state)

pg.explore(find=0x4004d8) #this is the location I am trying to go to
```

And the source for the binary:
```c
#include <stdio.h>
#include <stdlib.h>

float fn(float a){
	if(a == 0.1){
		return 0.1;
	}else{
		return 0.0;
	}
}

int main(int argc, char* argv[]){
	fn(4.2);
	return EXIT_SUCCESS;
}
```

The error I get:
```
Traceback (most recent call last):
  File "basic.py", line 17, in <module>
    pg.explore(find=0x4004d8)
  File "/usr/local/lib/python2.7/site-packages/angr/path_group.py", line 831, in explore
    n=n)
  File "/usr/local/lib/python2.7/site-packages/angr/path_group.py", line 855, in run
    return self.step(n=n, step_func=step_func, until=until_func, stash=stash)
  File "/usr/local/lib/python2.7/site-packages/angr/path_group.py", line 544, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/angr/path_group.py", line 329, in _one_step
    self._record_step_results(new_stashes, new_active, a, *r)
  File "/usr/local/lib/python2.7/site-packages/angr/path_group.py", line 249, in _record_step_results
    self._apply_filter_hooks(path,new_stashes,new_active)
  File "/usr/local/lib/python2.7/site-packages/angr/path_group.py", line 264, in _apply_filter_hooks
    goto = hook(path)
  File "/usr/local/lib/python2.7/site-packages/angr/exploration_techniques/explorer.py", line 98, in filter
    if not path.reachable:
  File "/usr/local/lib/python2.7/site-packages/angr/path.py", line 387, in reachable
    return self.history.reachable()
  File "/usr/local/lib/python2.7/site-packages/angr/path_history.py", line 153, in reachable
    self._satisfiable = self.state.se.satisfiable()
  File "/usr/local/lib/python2.7/site-packages/simuvex/s_action_object.py", line 53, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/usr/local/lib/python2.7/site-packages/simuvex/plugins/solver.py", line 86, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/simuvex/plugins/solver.py", line 449, in satisfiable
    return self._solver.satisfiable(extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/usr/local/lib/python2.7/site-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 34, in satisfiable
    return super(ConstraintFilterMixin, self).satisfiable(extra_constraints=ec, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/claripy/frontend_mixins/sat_cache_mixin.py", line 45, in satisfiable
    extra_constraints=extra_constraints, **kwargs
  File "/usr/local/lib/python2.7/site-packages/claripy/frontends/composite_frontend.py", line 278, in satisfiable
    return all(s.satisfiable(exact=exact) for s in self._solver_list)
  File "/usr/local/lib/python2.7/site-packages/claripy/frontends/composite_frontend.py", line 278, in <genexpr>
    return all(s.satisfiable(exact=exact) for s in self._solver_list)
  File "/usr/local/lib/python2.7/site-packages/claripy/frontend_mixins/sat_cache_mixin.py", line 45, in satisfiable
    extra_constraints=extra_constraints, **kwargs
  File "/usr/local/lib/python2.7/site-packages/claripy/frontend_mixins/model_cache_mixin.py", line 221, in satisfiable
    return super(ModelCacheMixin, self).satisfiable(extra_constraints=extra_constraints, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/claripy/frontends/full_frontend.py", line 91, in satisfiable
    solver=self._get_solver(), model_callback=self._model_hook
  File "/usr/local/lib/python2.7/site-packages/claripy/frontends/full_frontend.py", line 58, in _get_solver
    self._add_constraints()
  File "/usr/local/lib/python2.7/site-packages/claripy/frontends/full_frontend.py", line 66, in _add_constraints
    self._solver_backend.add(self._tls.solver, self.constraints, track=self._track)
  File "/usr/local/lib/python2.7/site-packages/claripy/backends/__init__.py", line 396, in add
    return self._add(s, self.convert_list(c), track=track)
  File "/usr/local/lib/python2.7/site-packages/claripy/backends/__init__.py", line 183, in convert_list
    return [ self.convert(a) for a in args ]
  File "/usr/local/lib/python2.7/site-packages/claripy/backends/__init__.py", line 153, in convert
    raise BackendError("%s can't handle operation %s (%s) due to a failed conversion on a child node" % (self, expr.op, expr.__class__.__name__))
simuvex.s_errors.SimSolverModeError: ('Translated claripy error:', <class 'claripy.errors.ClaripyFrontendError'>, ClaripyFrontendError("Backend error during solve: <class 'claripy.errors.BackendError'>('<claripy.backends.backend_z3.BackendZ3 object at 0x7fb558cd5dd0> can't handle operation __eq__ (Bool) due to a failed conversion on a child node')",))
```

**Comment by burtonwilliamt** [comment]
So I talked to @rhelmot in the #help channel over on the [slack](https://angr.slack.com/). Specifically you can see our discussion [here](https://angr.slack.com/archives/C3PSH3G13/p1495485354820307).

He updated claripy in angr/claripy@0c00f47286bdffc624263e216f3bb753a7367877, simuvex in angr/simuvex@3602763fe7b5532d2e654e94a5066be57730c77f, and angr in angr/angr@cc37ac72ab941425ecd0a284fc0cf81087307eca

**Comment by burtonwilliamt** [comment]
Everything seems to work the way I was expecting it to now.
