### ISSUE TITLE
ZeroDivisionError in CFGAccurate

### ISSUE THREAD

**Issue by ash09** [angr/angr#469]
Hi,
I think this is a bug in claripy.

```
cfg_f = proj.analyses.CFGAccurate(
	starts=[addr], 
	context_sensitivity_level=1, 
	call_depth=0, 
	normalize=True,
	enable_symbolic_back_traversal=True,
	enable_function_hints=True
)
Traceback (most recent call last):
  File "BB-weight.py", line 258, in <module>
    enable_function_hints=True
  File "/usr/local/lib/python2.7/dist-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_accurate.py", line 266, in __init__
    self._analyze()
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/forward_analysis.py", line 228, in _analyze
    self._pre_entry_handling(entry_info.entry)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_accurate.py", line 1103, in _pre_entry_handling
    sim_successors, error_occurred, _ = self._get_simsuccessors(addr, job, current_function_addr=job.func_addr)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_accurate.py", line 2702, in _get_simsuccessors
    opt_level=self._iropt_level)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 77, in successors
    r = engine.process(state, inline=inline,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/engines/vex/engine.py", line 101, in process
    opt_level=opt_level)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/engines/engine.py", line 44, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/engines/vex/engine.py", line 134, in _process
    self._handle_irsb(state, successors, irsb, skip_stmts, last_stmt, whitelist)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/engines/vex/engine.py", line 203, in _handle_irsb
    self._handle_statement(state, successors, stmt)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/engines/vex/engine.py", line 322, in _handle_statement
    exit_stmt_idx=state.scratch.stmt_idx, exit_ins_addr=state.scratch.ins_addr)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/engines/successors.py", line 108, in add_successor
    self._preprocess_successor(state, add_guard=add_guard)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/engines/successors.py", line 138, in _preprocess_successor
    state.add_constraints(state.scratch.guard)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/s_state.py", line 317, in add_constraints
    added = self.se.add(*constraints)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/s_action_object.py", line 53, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/plugins/solver.py", line 86, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/plugins/solver.py", line 456, in add
    return self._solver.add(cc)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/constraint_fixer_mixin.py", line 9, in add
    return super(ConstraintFixerMixin, self).add(constraints, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 27, in add
    return super(ConstraintFilterMixin, self).add(ec, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/constraint_deduplicator_mixin.py", line 38, in add
    added = super(ConstraintDeduplicatorMixin, self).add(filtered, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/sat_cache_mixin.py", line 26, in add
    added = super(SatCacheMixin, self).add(constraints, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/simplify_skipper_mixin.py", line 26, in add
    added = super(SimplifySkipperMixin, self).add(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontends/composite_frontend.py", line 241, in add
    child_added += self._add_dependent_constraints(names, set_constraints, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontends/composite_frontend.py", line 223, in _add_dependent_constraints
    added = s.add(constraints, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/constraint_deduplicator_mixin.py", line 38, in add
    added = super(ConstraintDeduplicatorMixin, self).add(filtered, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/sat_cache_mixin.py", line 26, in add
    added = super(SatCacheMixin, self).add(constraints, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/simplify_skipper_mixin.py", line 26, in add
    added = super(SimplifySkipperMixin, self).add(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/model_cache_mixin.py", line 135, in add
    still_valid = set(self._get_models(extra_constraints=added))
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/model_cache_mixin.py", line 194, in _get_models
    if m.eval_constraints(extra_constraints):
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/model_cache_mixin.py", line 54, in eval_constraints
    return all(self.eval_ast(c) for c in constraints)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/model_cache_mixin.py", line 54, in <genexpr>
    return all(self.eval_ast(c) for c in constraints)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/model_cache_mixin.py", line 50, in eval_ast
    new_ast = ast._replace(self.replacements, leaf_operation=self._leaf_op)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 596, in _replace
    new_a = a._replace(replacements=replacements, variable_set=variable_set, leaf_operation=leaf_operation)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 596, in _replace
    new_a = a._replace(replacements=replacements, variable_set=variable_set, leaf_operation=leaf_operation)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 596, in _replace
    new_a = a._replace(replacements=replacements, variable_set=variable_set, leaf_operation=leaf_operation)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 596, in _replace
    new_a = a._replace(replacements=replacements, variable_set=variable_set, leaf_operation=leaf_operation)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 596, in _replace
    new_a = a._replace(replacements=replacements, variable_set=variable_set, leaf_operation=leaf_operation)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 604, in _replace
    r = self.make_like(self.op, tuple(new_args))
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/bits.py", line 15, in make_like
    return Base.make_like(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 293, in make_like
    return type(self)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/ast/base.py", line 128, in __new__
    r = operations._handle_annotations(eb._abstract(eb.call(op, args)), args)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 199, in call
    obj = self._op_raw[op](*converted)
  File "/usr/local/lib/python2.7/dist-packages/claripy/bv.py", line 38, in normalize_helper
    return f(self, o)
  File "/usr/local/lib/python2.7/dist-packages/claripy/bv.py", line 13, in compare_guard
    return f(self, o)
  File "/usr/local/lib/python2.7/dist-packages/claripy/bv.py", line 393, in SDiv
    val = a//b if a*b>0 else (a+(-a%b))//b
ZeroDivisionError: long division or modulo by zero
```

**Comment by zardus** [comment]
Claripy is doing the right thing here (raising a ZeroDivision because the solution has it dividing by zero). However, either simuvex should catch that (and create a sigfpe exit) or CFGAccurate should catch it and ignore it. I'm leaning toward the former.

@fish, what do you think?

**Comment by ltfish** [comment]
This issue should have been fixed a long time ago... not sure why it regresses. Yan is right, the problem is in `CFGAccurate`, not claripy. I will take a look.
