### ISSUE TITLE
Concrete Execution of UPX and Themida Packed PE Binaries with angr Using unicorn_engine

### ISSUE THREAD

**Issue by alsgh5016** [angr/angr#4734]
### Question

Hi!
I am attempting to perform concrete execution (or emulate) of PE binaries (with obfuscation tools like UPX and Themida) using angr. Specifically, I am trying to utilize the unicorn engine integrated within angr.
However, I have encountered some issues during this process and would appreciate some clarification and assistance.

This is my current code.

```
import os
import sys
import angr
import argparse
import logging

logging.getLogger('angr').setLevel(logging.DEBUG)
logging.getLogger('angr.engines.engine').setLevel('DEBUG')
logging.getLogger('angr.engines.unicorn').setLevel(logging.DEBUG)

def parse_arguments(args=None):
    parser = argparse.ArgumentParser(description="PE Binary Emulation using angr and Unicorn")
    parser.add_argument('binary_path', help="Path to the PE binary file")
    parser.add_argument("--unicorn", action="store_true", default=False, help="Use the unicorn engine")
    return parser.parse_args(args)

def emulate_binary(options):
    loadOpt = {'main_opts':{'arch':'x86'}}
    proj = angr.Project(
        options.binary_path,
        load_options=loadOpt,
        auto_load_libs=False,
        selfmodifying_code=True,
        use_sim_procedures=False
    )
    print(f"Entry Point: {hex(proj.entry)}")

    state = proj.factory.entry_state(
        remove_options={angr.options.LAZY_SOLVES}
    )
    
    state.options.add(angr.sim_options.UNICORN)
    state.options.add(angr.sim_options.UNICORN_SYM_REGS_SUPPORT)
    state.options.add(angr.sim_options.UNICORN_ZEROPAGE_GUARD)
    state.options.add(angr.sim_options.UNICORN_TRACK_BBL_ADDRS)
    state.options.add(angr.sim_options.UNICORN_TRACK_STACK_POINTERS)

    state.options.add(angr.options.ZERO_FILL_UNCONSTRAINED_MEMORY)
    state.options.add(angr.options.SYMBOL_FILL_UNCONSTRAINED_MEMORY)
    state.options.add(angr.options.SYMBOL_FILL_UNCONSTRAINED_REGISTERS)

    sm = proj.factory.simulation_manager(state, save_unconstrained=True)

    def log_vex_ir(state):
        irsb = state.block().vex
        print("VEX IR for block at address 0x{:x}".format(state.addr))
        print(irsb.pp())
    
    state.inspect.b('irsb', when=angr.BP_BEFORE, action=log_vex_ir)

    simgr = proj.factory.simulation_manager(state)
    simgr.run()

    return

def main(args):
    options = parse_arguments(args)

    emulate_binary(options)
    return

# Example usage:
# args = ["./Pack-Test-x86_upx.exe", "--unicorn"]
# args = ["./Pack-Test-x86_protected.exe", "--unicorn"]
args = ["./Pack-Test-x86.exe", "--unicorn"]
main(args)
```

1. Issue with **angr.sim.option.UNICORN_SYM_REGS_SUPPORT**

I noticed that adding **angr.sim_options.UNICORN_SYM_REGS_SUPPORT** to the state's options is necessary for the unicorn_engine to perform mmap. However, when this option is added, the IRSB is not generated from the entry point.

I am curious to know:
  1. Why does adding this option cause the IRSB not to be generated from the entry point?
  2. What is the specific role of UNICORN_SYM_REGS_SUPPORT?
  3. Is this option essential for concrete execution using the Unicorn engine, or is it possible to execute without requiring mmap?

2. Different Errors based on sample binary

Additionally, I have observed that different errors occur depending on the specific sample binary being executed (e.g., normal PE files vs. UPX or Themida packed samples). I would like to undertand whether these issues are related to the nature of the target binaries themselves or if there might be an underlying problem in the angr implementation when handling these cases.

- Error duing emulation of UPX packed sample

```
Traceback (most recent call last):
  File "/mnt/ssd_1/workspace/angr-test/unicorn-tracing.py", line 89, in <module>
    main(args)
  File "/mnt/ssd_1/workspace/angr-test/unicorn-tracing.py", line 84, in main
    emulate_binary(options)
  File "/mnt/ssd_1/workspace/angr-test/unicorn-tracing.py", line 65, in emulate_binary
    simgr.run()
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_manager.py", line 362, in run
    self.step(stash=stash, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/misc/hookset.py", line 96, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/exploration_techniques/suggestions.py", line 43, in step
    simgr.step(stash=stash, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/misc/hookset.py", line 101, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_manager.py", line 471, in step
    successors = self.step_state(state, successor_func=successor_func, error_list=error_list, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_manager.py", line 512, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_manager.py", line 562, in successors
    return self._project.factory.successors(state, **run_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/slicing.py", line 20, in process
    return super().process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/engine.py", line 162, in process
    self.process_successors(self.successors, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/failure.py", line 24, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/syscall.py", line 26, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/hook.py", line 56, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/unicorn.py", line 389, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/soot/engine.py", line 68, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 174, in process_successors
    self.handle_vex_block(irsb)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/super_fastpath.py", line 25, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/slicing.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/actions.py", line 31, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/inspect.py", line 49, in handle_vex_block
    super().handle_vex_block(irsb)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/light.py", line 547, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/slicing.py", line 30, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/inspect.py", line 44, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/resilience.py", line 39, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 248, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/light.py", line 51, in _handle_vex_stmt
    handler(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/light.py", line 214, in _handle_vex_stmt_Store
    self._perform_vex_stmt_Store(
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/actions.py", line 212, in _perform_vex_stmt_Store
    super()._perform_vex_stmt_Store(addr, data, end, action=a, condition=condition, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/claripy/datalayer.py", line 108, in _perform_vex_stmt_Store
    super()._perform_vex_stmt_Store(addr, data.raw_to_bv(), endness, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 50, in _perform_vex_stmt_Store
    self.state.memory.store(
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/storage/memory_mixins/unwrapper_mixin.py", line 10, in store
    return super().store(
           ^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/storage/memory_mixins/name_resolution_mixin.py", line 60, in store
    return super().store(addr, data, size=size, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/storage/memory_mixins/bvv_conversion_mixin.py", line 26, in store
    super().store(addr, data_bv, size=size, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/storage/memory_mixins/simplification_mixin.py", line 13, in store
    super().store(addr, real_data, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/storage/memory_mixins/clouseau_mixin.py", line 54, in store
    self.state._inspect(
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_state.py", line 398, in _inspect
    self.inspect.action(*args, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/state_plugins/inspect.py", line 275, in action
    bp.fire(self.state)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/state_plugins/inspect.py", line 215, in fire
    self.action(state)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/unicorn.py", line 384, in _save_mem_write_addrs
    self._instr_mem_write_addrs.update(range(mem_write_addr, mem_write_addr + state.inspect.mem_write_length))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UberEngine' object has no attribute '_instr_mem_write_addrs'. Did you mean: '_save_mem_write_addrs'?

```

- Error duing emulation of Normal PE sample or Themida packed sample

```
Traceback (most recent call last):
  File "/mnt/ssd_1/workspace/angr-test/unicorn-tracing.py", line 90, in <module>
    main(args)
  File "/mnt/ssd_1/workspace/angr-test/unicorn-tracing.py", line 84, in main
    emulate_binary(options)
  File "/mnt/ssd_1/workspace/angr-test/unicorn-tracing.py", line 65, in emulate_binary
    simgr.run()
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_manager.py", line 362, in run
    self.step(stash=stash, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/misc/hookset.py", line 96, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/exploration_techniques/suggestions.py", line 43, in step
    simgr.step(stash=stash, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/misc/hookset.py", line 101, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_manager.py", line 471, in step
    successors = self.step_state(state, successor_func=successor_func, error_list=error_list, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_manager.py", line 512, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/sim_manager.py", line 562, in successors
    return self._project.factory.successors(state, **run_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/slicing.py", line 20, in process
    return super().process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/engine.py", line 162, in process
    self.process_successors(self.successors, **kwargs)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/failure.py", line 24, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/syscall.py", line 26, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/hook.py", line 56, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/unicorn.py", line 440, in process_successors
    self._execute_symbolic_instrs(syscall_data=syscall_data)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/unicorn.py", line 240, in _execute_symbolic_instrs
    self._execute_block_instrs_in_vex(block_details)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/unicorn.py", line 153, in _execute_block_instrs_in_vex
    super()._handle_vex_stmt(vex_stmt)  # pylint:disable=no-member
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/slicing.py", line 30, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/inspect.py", line 44, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/resilience.py", line 39, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 248, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/light/light.py", line 51, in _handle_vex_stmt
    handler(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/inspect.py", line 27, in _handle_vex_stmt_IMark
    super()._handle_vex_stmt_IMark(stmt)
  File "/mnt/ssd_1/workspace/angr-dev/angr/angr/engines/vex/heavy/heavy.py", line 268, in _handle_vex_stmt_IMark
    self.successors.artifacts["insn_addrs"].append(ins_addr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'insn_addrs'

```

Thank you for taking the time to read my question!

**Comment by rhelmot** [comment]
1. What are you observing that you are describing as `the IRSB not being generated`?
2. `UNICORN_SYM_REGS_SUPPORT` enables what I can best describe as advanced taint tracking for the purpose of letting registers continue to be symbolic while still executing through unicorn, by effectively storing the computations that are performed and applying them all at once after the execution is over.
3. It shouldn't have anything to do with mmap. unicorn support should be fully functional without it.
4. Both of those tracebacks look like legitimate angr issues.

I'm not sure whose responsibility it should be to fix this :) I'll talk with the rest of the team.

**Comment by alsgh5016** [comment]
I tried to emulate a PE binary with an EntryPoint at `0x7d80d8`, but the logs show that `angr.engines.vex.lifter` is starting to create the IRSB from `0x7d81a8` instead. Not only that, but the same issue occurs with all other PE binaries as well.

```
WARNING  | 2024-08-08 12:22:33,603 | angr.engines.vex.lifter | Self-modifying code is not always correctly optimized by PyVEX. To guarantee correctness, VEX optimizations have been disabled.
DEBUG    | 2024-08-08 12:22:33,603 | angr.engines.vex.lifter | Creating IRSB of <Arch X86 (LE)> at 0x7d81a8
DEBUG    | 2024-08-08 12:22:33,605 | angr.storage.memory_mixins.paged_memory.paged_memory_mixin | reg.load(0x18, 4, Iend_LE) = <BV32 0x7ffefeb8>
DEBUG    | 2024-08-08 12:22:33,606 | angr.state_plugins.unicorn_engine | Creating unicorn state
```

After the Creating unicorn state message, the errors I mentioned earlier are occurring.

Thank you for your response.

**Comment by rhelmot** [comment]
vex/irsb is the opposite of unicorn - it's only invoked when unicorn can't run. If you want a full execution trace in the logs you should enable logging at the INFO level for `angr.engines`.

**Comment by alsgh5016** [comment]
I am planning to use angr combined with unicorn for my project. To achieve this, I would like to address and fix the issue related to unicorn within the angr myself. Could you please provide some guidance or point me in the right direction on which parts of the code I should focus on to resolve this issue?

**Comment by iamahuman** [comment]
Also affects recent dc33 qual chall from NI: https://github.com/Nautilus-Institute/quals-2025/tree/main/nfuncs#sup

**Comment by rhelmot** [comment]
I have a lot of patches I did while working on nfuncs, I'll submit them soon
