### ISSUE TITLE
pcode cannot be loaded without a calling convention

### ISSUE THREAD

**Issue by sam-f0** [angr/angr#4764]
### Description

When loading a pcode binary, the `default_cc` resolution fails to handle not having a default calling convention set. It should be reasonable to not set a calling convention - much of `angr`'s functionality doesn't interact with stack frames or other constructs where the CC is required.

### Steps to reproduce the bug

```
import angr, cle, archinfo

loader = cle.Loader("memory.bin", main_opts={"backend": "blob"}, arch=archinfo.ArchPcode(language="TI_MSP430:LE:16:default"))
p = angr.Project(loader)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/angr/project.py", line 227, in __init__
    self.factory = AngrObjectFactory(self, default_engine=engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/angr/factory.py", line 39, in __init__
    register_pcode_arch_default_cc(project.arch)
  File "/usr/lib/python3.12/site-packages/angr/engines/pcode/cc.py", line 113, in register_pcode_arch_default_cc
    cc = default_cc(arch.name)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/angr/calling_conventions.py", line 2293, in default_cc
    return cc_map[alias][platform]
           ~~~~~~^^^^^^^
KeyError: 'ti_msp43016'
```
[memory.bin.zip](https://github.com/user-attachments/files/16711110/memory.bin.zip)

### Environment

```angr environment report
=============================
Date: 2024-08-08 13:26:00.957105
!!! running in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]
######## angr #########
Python found it in /usr/lib/python3.12/site-packages/angr/__init__.py
Pip version angr 9.2.81
Couldn't find git info
######## ailment #########
Python found it in /usr/lib/python3.12/site-packages/ailment/__init__.py
Pip version ailment 9.2.101
Couldn't find git info
######## cle #########
Python found it in /usr/lib/python3.12/site-packages/cle/__init__.py
Pip version cle 9.2.101
Couldn't find git info
######## pyvex #########
Python found it in /usr/lib/python3.12/site-packages/pyvex/__init__.py
Pip version pyvex 9.2.81
Couldn't find git info
######## claripy #########
Python found it in /usr/lib/python3.12/site-packages/claripy/__init__.py
Pip version claripy 9.2.101
Couldn't find git info
######## archinfo #########
Python found it in /usr/lib/python3.12/site-packages/archinfo/__init__.py
Pip version archinfo 9.2.102
Couldn't find git info
######## z3 #########
Python found it in /usr/lib/python3.12/site-packages/z3/__init__.py
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /usr/lib/python3.12/site-packages/unicorn/__init__.py
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/usr/lib/python3.12/site-packages/angr/state_plugins/../lib/angr_native.so', handle 59a4441ee9b0 at 0x7a387e2e08c0>
unicorn: <CDLL 'libunicorn.so.2', handle 59a443b9e410 at 0x7a38819dfad0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7a3881bf3b60>
z3: <CDLL '/usr/lib/libz3.so', handle 59a443793c00 at 0x7a38836139b0>
```

**Comment by sam-f0** [comment]
Fixed by https://github.com/angr/angr/pull/4765
