### ISSUE TITLE
pcode emulation of the MSP430 fails due to uppercase address space name

### ISSUE THREAD

**Issue by sam-f0** [angr/angr#4766]
### Description

The SLEIGH specification for the MSP430 uses uppercase `RAM` as the address space, but the pcode emulator assumes that the address space will be one of `ram` or `mem`. This causes `Attempted write to unhandled address space 'RAM'` errors.

### Steps to reproduce the bug

```
import angr
import archinfo
import cle

arch = archinfo.ArchPcode(language="TI_MSP430:LE:16:default")

# work around #1 
angr.calling_conventions.register_default_cc(
    arch.name, angr.calling_conventions.SimCCUsercall
)

loader = cle.Loader(
    "memory.bin",
    main_opts={
        "backend": "blob",
        "entry_point": 0x4400,
        "base_addr": 0x0,
        "segments": [(0x0, 0x0, 0x4FFF), (0x6000, 0x6000, 0xFFFF - 0x6000)],
    },
    arch=arch,
    rebase_granularity=0x100,
)
p = angr.Project(loader)

st = p.factory.entry_state()
sm = p.factory.simgr(st)

sm.run()

print(sm.errored)
print(sm.errored[0].reraise())
```
[memory.bin (1).zip](https://github.com/user-attachments/files/16711165/memory.bin.1.zip)

```
[<State errored with "Load from unhandled address space">]
Traceback (most recent call last):
  File "/home/user/scratch2.py", line 31, in <module>
    print(sm.errored[0].reraise())
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/sim_manager.py", line 964, in reraise
    raise self.error.with_traceback(self.traceback)
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/sim_manager.py", line 512, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/sim_manager.py", line 562, in successors
    return self._project.factory.successors(state, **run_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/engine.py", line 162, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/failure.py", line 24, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/syscall.py", line 26, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/hook.py", line 56, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/engine.py", line 106, in process_successors
    finished = self._process_irsb()
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/engine.py", line 165, in _process_irsb
    self.handle_pcode_block(self.state.scratch.irsb)
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/emulate.py", line 85, in handle_pcode_block
    self._execute_current_op()
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/emulate.py", line 124, in _execute_current_op
    handlers[self._current_behavior.opcode]()
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/emulate.py", line 293, in _execute_load
    raise AngrError("Load from unhandled address space")
angr.errors.AngrError: Load from unhandled address space

```

### Environment

```
angr environment report
=============================
Date: 2024-08-14 15:13:29.659302
Running in virtual environment at /home/user/brokenvenv
Platform: linux-x86_64
Python version: 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]
######## angr #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/angr/__init__.py
Pip version 9.2.115
Couldn't find git info
######## ailment #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/ailment/__init__.py
Pip version 9.2.115
Couldn't find git info
######## cle #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/cle/__init__.py
Pip version 9.2.115
Couldn't find git info
######## pyvex #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/pyvex/__init__.py
Pip version 9.2.115
Couldn't find git info
######## claripy #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/claripy/__init__.py
Pip version 9.2.115
Couldn't find git info
######## archinfo #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/archinfo/__init__.py
Pip version 9.2.115
Couldn't find git info
######## z3 #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/z3/__init__.py
Pip version 4.13.0.0
Couldn't find git info
######## unicorn #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/unicorn/__init__.py
Pip version 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/user/brokenvenv/lib/python3.12/site-packages/angr/lib/angr_native.so', handle 6541bddd0710 at 0x75bc9eef4da0>
unicorn: <CDLL '/home/user/brokenvenv/lib/python3.12/site-packages/unicorn/lib/libunicorn.so.2', handle 6541bd721e70 at 0x75bca24bb200>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x75bca30f7560>
z3: <CDLL '/home/user/brokenvenv/lib/python3.12/site-packages/z3/lib/libz3.so', handle 6541bd2837b0 at 0x75bca57e6450>
```

**Comment by sam-f0** [comment]
Fixed by https://github.com/angr/angr/pull/4767
