### ISSUE TITLE
pcode emulation of the MSP430 fails due to an argument size mismatch on the SUBPIECE instruction

### ISSUE THREAD

**Issue by sam-f0** [angr/angr#4772]
### Description

Some MSP430 instructions use the pcode `SUBPIECE` instruction with mismatched argument sizes. This is already handled in one direction (see [the implementation here.](https://github.com/angr/angr/blob/7251047a537eafe256d7e3a69288fbb5cb3113d2/angr/engines/pcode/behavior.py#L869) ), but if the other argument is longer, the shift fails and causes the state to error.

### Steps to reproduce the bug

```
import angr
import archinfo
import cle

arch = archinfo.ArchPcode(language="TI_MSP430:LE:16:default")

loader = cle.Loader(
    "memory.bin",
    main_opts={
        "backend": "blob",
        "entry_point": 0x4400,
        "base_addr": 0x0,
        "segments": [(0x0, 0x0, 0x4FFF), (0x6000, 0x6000, 0xFFFF - 0x6000)],
    },
    arch=arch,
    rebase_granularity=0x100,
)
p = angr.Project(loader)

st = p.factory.entry_state()
sm = p.factory.simgr(st)

sm.run()

print(sm.errored)
print(sm.errored[0].reraise())
```
[memory.bin (2).zip](https://github.com/user-attachments/files/16726363/memory.bin.2.zip)

```
WARNING  | 2024-08-23 08:30:33,930 | angr.factory   | Creating project with the experimental 'UberEnginePcode' engine
WARNING  | 2024-08-23 08:30:33,946 | angr.storage.memory_mixins.default_filler_mixin | The program is accessing register with an unspecified value. This could indicate unwanted behavior.
WARNING  | 2024-08-23 08:30:33,946 | angr.storage.memory_mixins.default_filler_mixin | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING  | 2024-08-23 08:30:33,947 | angr.storage.memory_mixins.default_filler_mixin | 1) setting a value to the initial state
WARNING  | 2024-08-23 08:30:33,947 | angr.storage.memory_mixins.default_filler_mixin | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING  | 2024-08-23 08:30:33,947 | angr.storage.memory_mixins.default_filler_mixin | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
WARNING  | 2024-08-23 08:30:33,947 | angr.storage.memory_mixins.default_filler_mixin | Filling register sr with 2 unconstrained bytes referenced from 0x4400 (offset 0x4400 in memory.bin (0x4400))
[<State errored with "args' length must all be equal">]
Traceback (most recent call last):
  File "/home/user/scratch2.py", line 34, in <module>
    print(sm.errored[0].reraise())
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/sim_manager.py", line 964, in reraise
    raise self.error.with_traceback(self.traceback)
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/sim_manager.py", line 512, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/sim_manager.py", line 562, in successors
    return self._project.factory.successors(state, **run_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/engine.py", line 162, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/failure.py", line 24, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/syscall.py", line 26, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/hook.py", line 56, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/engine.py", line 106, in process_successors
    finished = self._process_irsb()
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/engine.py", line 165, in _process_irsb
    self.handle_pcode_block(self.state.scratch.irsb)
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/emulate.py", line 85, in handle_pcode_block
    self._execute_current_op()
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/emulate.py", line 128, in _execute_current_op
    self._execute_binary()
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/emulate.py", line 276, in _execute_binary
    out = self._current_behavior.evaluate_binary(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/brokenvenv/lib/python3.12/site-packages/angr/engines/pcode/behavior.py", line 871, in evaluate_binary
    return (in1 >> (in2 * 8)) & (2 ** (size_out * 8) - 1)
            ~~~~^^~~~~~~~~~~
  File "/home/user/brokenvenv/lib/python3.12/site-packages/claripy/operations.py", line 52, in _op
    raise ClaripyOperationError(msg)
claripy.errors.ClaripyOperationError: args' length must all be equal
```

### Environment

```
angr environment report
=============================
Date: 2024-08-23 08:47:18.051310
Running in virtual environment at /home/user/brokenvenv
Platform: linux-x86_64
Python version: 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]
######## angr #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/angr/__init__.py
Pip version 9.2.115
Couldn't find git info
######## ailment #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/ailment/__init__.py
Pip version 9.2.115
Couldn't find git info
######## cle #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/cle/__init__.py
Pip version 9.2.115
Couldn't find git info
######## pyvex #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/pyvex/__init__.py
Pip version 9.2.115
Couldn't find git info
######## claripy #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/claripy/__init__.py
Pip version 9.2.115
Couldn't find git info
######## archinfo #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/archinfo/__init__.py
Pip version 9.2.115
Couldn't find git info
######## z3 #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/z3/__init__.py
Pip version 4.13.0.0
Couldn't find git info
######## unicorn #########
Python found it in /home/user/brokenvenv/lib/python3.12/site-packages/unicorn/__init__.py
Pip version 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/user/brokenvenv/lib/python3.12/site-packages/angr/lib/angr_native.so', handle 58f752d52460 at 0x740cdea69be0>
unicorn: <CDLL '/home/user/brokenvenv/lib/python3.12/site-packages/unicorn/lib/libunicorn.so.2', handle 58f7526d35f0 at 0x740ce1919490>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x740ce27ef8c0>
z3: <CDLL '/home/user/brokenvenv/lib/python3.12/site-packages/z3/lib/libz3.so', handle 58f752208ca0 at 0x740ce4fb6de0>
```

**Comment by sam-f0** [comment]
Fixed by https://github.com/angr/angr/pull/4773
