### ISSUE TITLE
Typo in VFG

### ISSUE THREAD

**Issue by tunefish** [angr/angr#482]
Hi,
I always get this KeyError in VFG:
```
>>>> vfg = proj.analyses.VFG(cfg=cfg, context_sensitivity_level=0, start=f_addrs[0])
WARNING | 2017-06-07 04:19:33,094 | angr.analyses.vfg | The given CFG is not normalized, which might impact the performance/accuracy of the VFG analysis.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pypy/site-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/opt/pypy/site-packages/angr/analyses/vfg.py", line 341, in __init__
    self._analyze()
  File "/opt/pypy/site-packages/angr/analyses/forward_analysis.py", line 500, in _analyze
    self._analysis_core_baremetal()
  File "/opt/pypy/site-packages/angr/analyses/forward_analysis.py", line 625, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/opt/pypy/site-packages/angr/analyses/forward_analysis.py", line 643, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/opt/pypy/site-packages/angr/analyses/vfg.py", line 683, in _get_successors
    self._thumb_addrs.update(job.sim_successors.artifacts['instruction_addrs'])
KeyError: 'instruction_addrs'
```

Replacing `instruction_addrs` with `insn_addrs` in vfg.py, line 683 (see simuvex.engines.vex.engine.py, line 221) seems to fix this bug for me.

Thanks

**Comment by ltfish** [comment]
That should be a legit fix. Thank you! Give us a PR!
