### ISSUE TITLE
TypeError when constructing CFG

### ISSUE THREAD

**Issue by dorottyapapp** [angr/angr#484]
Hi!

I'm trying to analyze ARM binaries. I load the binary with 
```
b = angr.Project(
        filename,
        load_options={
                 'auto_load_libs': True,
                 'except_missing_libs': True
         },
        use_sim_procedures=False
)
```
And tried to construct the CFG of the binary with `cfg = b.analyses.CFG()`. At this point, the program crashes with a `TypeError` and the following trace:
```
Traceback (most recent call last):
  File "main.py", line 54, in extract_external_functions
    cfg = b.analyses.CFG()
  File "/usr/local/lib/python2.7/dist-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg.py", line 56, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg_fast.py", line 741, in __init__
    self._analyze()
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/forward_analysis.py", line 239, in _analyze
    self._handle_entry(entry_info)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/forward_analysis.py", line 258, in _handle_entry
    successors = self._get_successors(entry)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg_fast.py", line 1082, in _get_successors
    return self._scan_block(addr, current_function_addr, jumpkind, src_node, src_ins_addr, src_stmt_idx)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg_fast.py", line 1343, in _scan_block
    previous_src_ins_addr, previous_src_stmt_idx)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg_fast.py", line 1466, in _scan_irsb
    self._process_block_arch_specific(addr, irsb, current_function_addr)
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg_fast.py", line 3625, in _process_block_arch_specific
    self._arm_track_read_lr_from_stack(addr, irsb, self.functions[func_addr])
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg_fast.py", line 3479, in _arm_track_read_lr_from_stack
    lr_on_stack_offset = memory_addr - last_sp
TypeError: unsupported operand type(s) for -: 'int' and 'tuple'
```

A sample triggering the exception: https://www.dropbox.com/s/0yl6394jsom4q4g/f7cf1e0d7756d1874630d0d697c3b0f3df0632500cff1845b6308b11059deb07.zip?dl=0

Could You look into this issue?

**Comment by ltfish** [comment]
Your dropbox account seems to have hit a traffic/download limit for today :-(

Feel free to send me the script + binary on Slack.

**Comment by rhelmot** [comment]
You can also just upload files to github issues!
