### ISSUE TITLE
SimEngineError when constructing CFG

### ISSUE THREAD

**Issue by dorottyapapp** [angr/angr#488]
I'm trying to analyze a MIPS R3000 binary with angr. I load the binary with

```
b = angr.Project(
        filename,
        load_options={
                 'auto_load_libs': True,
                 'except_missing_libs': True
         },
        use_sim_procedures=False
)
```
And tried to construct the CFG of the binary with `cfg = b.analyses.CFG()`. However, the analysis fails with a `simuvex.s_errors.SimEngineError: No bytes in memory for block starting at 0x2007d08.` The full trace:
```
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    if extract_external_functions(config.FOLDER + args.arch + "/", args.filename):
  File "main.py", line 55, in extract_external_functions
    cfg = b.analyses.CFG()
  File "/usr/local/lib/python2.7/dist-packages/angr-6.7.4.12-py2.7.egg/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr-6.7.4.12-py2.7.egg/angr/analyses/cfg/cfg.py", line 56, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr-6.7.4.12-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 770, in __init__
    self._analyze()
  File "/usr/local/lib/python2.7/dist-packages/angr-6.7.4.12-py2.7.egg/angr/analyses/forward_analysis.py", line 507, in _analyze
    self._post_analysis()
  File "/usr/local/lib/python2.7/dist-packages/angr-6.7.4.12-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 1274, in _post_analysis
    self._remove_redundant_overlapping_blocks()
  File "/usr/local/lib/python2.7/dist-packages/angr-6.7.4.12-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 2866, in _remove_redundant_overlapping_blocks
    vex_block = block.vex
  File "/usr/local/lib/python2.7/dist-packages/angr-6.7.4.12-py2.7.egg/angr/block.py", line 140, in vex
    arch=self.arch,
  File "/usr/local/lib/python2.7/dist-packages/simuvex-6.7.4.12-py2.7.egg/simuvex/engines/vex/engine.py", line 453, in lift
    raise SimEngineError("No bytes in memory for block starting at %#x." % addr)
simuvex.s_errors.SimEngineError: No bytes in memory for block starting at 0x2007d08.
```

The sample that triggers the issue: https://www.dropbox.com/s/1fyfmlxz7al1p1n/a60a11931e591e5d4586417dd1f3da218ab2eb194505de1aba6a901f12ae06dc.zip?dl=0

**Comment by ltfish** [comment]
Thanks for reporting. I really want to look into the issue, but your dropbox link does not work :-(

**Comment by dorottyapapp** [comment]
I sent the sample to You on slack.

**Comment by ltfish** [comment]
The fix is merged to master. Thank you!
