### ISSUE TITLE
AttributeError: 'SimSolver' object has no attribute 'SLT' on Gentoo linux

### ISSUE THREAD

**Issue by NAHTAIV3L** [angr/angr#4951]
### Description

when trying to run angr in a virtual environment on Gentoo linux, angr always fails with:
```
AttributeError: 'SimSolver' object has no attribute 'SLT'
```

### Steps to reproduce the bug

in a terminal on gentoo:
```
$ python -m venv venv
$ . venv/bin/activate
(venv) $ pip install setuptools angr
Collecting setuptools
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Collecting angr
  Using cached angr-9.2.122-py3-none-manylinux2014_x86_64.whl.metadata (4.7 kB)
-----------------removed to clean output-----------------------------
Installing collected packages: z3-solver, unicorn, sortedcontainers, pyelftools, ply, mulpyplexer, mpmath, itanium-demangler, bitarray, unique-log-filter, typing-extensions, sympy, smmap, setuptools, pyparsing, pygments, pycryptodome, pycparser, psutil, protobuf, pefile, numpy, networkx, mdurl, future, CppHeaderParser, capstone, cachetools, bitstring, archinfo, ailment, pydot, nampa, markdown-it-py, gitdb, claripy, cffi, cart, rich, pyvex, pyformlang, GitPython, cle, angr
Successfully installed CppHeaderParser-2.7.4 GitPython-3.1.43 ailment-9.2.122 angr-9.2.122 archinfo-9.2.122 bitarray-2.9.3 bitstring-4.2.3 cachetools-5.5.0 capstone-5.0.3 cart-1.2.2 cffi-1.17.1 claripy-9.2.122 cle-9.2.122 future-1.0.0 gitdb-4.0.11 itanium-demangler-1.1 markdown-it-py-3.0.0 mdurl-0.1.2 mpmath-1.3.0 mulpyplexer-0.9 nampa-0.1.1 networkx-3.4.1 numpy-2.1.2 pefile-2024.8.26 ply-3.11 protobuf-5.28.2 psutil-6.0.0 pycparser-2.22 pycryptodome-3.21.0 pydot-3.0.2 pyelftools-0.31 pyformlang-1.0.10 pygments-2.18.0 pyparsing-3.2.0 pyvex-9.2.122 rich-13.9.2 setuptools-75.1.0 smmap-5.0.1 sortedcontainers-2.4.0 sympy-1.13.3 typing-extensions-4.12.2 unicorn-2.0.1.post1 unique-log-filter-0.1.0 z3-solver-4.13.0.0
(venv) $ python
Python 3.12.6 (main, Oct 12 2024, 18:05:48) [GCC 13.3.1 20240614] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>> angr.Project("re400")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/project.py", line 258, in __init__
    self.simos.configure_project()
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/simos/linux.py", line 151, in configure_project
    super().configure_project(syscall_abis)
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/simos/userland.py", line 53, in configure_project
    super().configure_project()
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/simos/simos.py", line 73, in configure_project
    self.project.loader.perform_irelative_relocs(irelative_resolver)
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/cle/loader.py", line 697, in perform_irelative_relocs
    val = resolver_func(resolver)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/simos/simos.py", line 63, in irelative_resolver
    val = resolver(0) if isinstance(self.arch, ArchS390X) else resolver()
                                                               ^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/callable.py", line 75, in __call__
    self.perform_call(*args, prototype=prototype)
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/callable.py", line 104, in perform_call
    caller.run(step_func=step_func if self._concrete_only else None).unstash(from_stash="deadended")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/sim_manager.py", line 364, in run
    self.step(stash=stash, **kwargs)
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/misc/hookset.py", line 98, in __call__
    result = current_hook(self.func.__self__, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/exploration_techniques/suggestions.py", line 44, in step
    simgr.step(stash=stash, **kwargs)
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/misc/hookset.py", line 102, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/sim_manager.py", line 473, in step
    successors = self.step_state(state, successor_func=successor_func, error_list=error_list, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/sim_manager.py", line 514, in step_state
    successors = self.successors(state, successor_func=successor_func, **run_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/sim_manager.py", line 564, in successors
    return self._project.factory.successors(state, **run_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/engines/vex/light/slicing.py", line 21, in process
    return super().process(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/engines/engine.py", line 160, in process
    self.process_successors(self.successors, **kwargs)
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/engines/failure.py", line 25, in process_successors
    return super().process_successors(successors, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/engines/syscall.py", line 50, in process_successors
    return self.process_procedure(state, successors, sys_procedure, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/engines/procedure.py", line 40, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to, arguments=arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/sim_procedure.py", line 279, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/procedures/linux_kernel/iovec.py", line 41, in run
    if self.state.solver.is_true(self.state.solver.SLT(tmpres, 0)):
                                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SimSolver' object has no attribute 'SLT'
```

### Environment

```
angr environment report
=============================
Date: 2024-10-13 16:09:11.104256
Running in virtual environment at /home/nahtaiv3l/rpisec/re/venv
Platform: linux-x86_64
Python version: 3.12.6 (main, Oct 12 2024, 18:05:48) [GCC 13.3.1 20240614]
######## angr #########
Python found it in /home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/__init__.py
Pip version 9.2.122
Couldn't find git info
######## ailment #########
Python found it in /home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/ailment/__init__.py
Pip version 9.2.122
Couldn't find git info
######## cle #########
Python found it in /home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/cle/__init__.py
Pip version 9.2.122
Couldn't find git info
######## pyvex #########
Python found it in /home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/pyvex/__init__.py
Pip version 9.2.122
Couldn't find git info
######## claripy #########
Python found it in /home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/claripy/__init__.py
Pip version 9.2.122
Couldn't find git info
######## archinfo #########
Python found it in /home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/archinfo/__init__.py
Pip version 9.2.122
Couldn't find git info
######## z3 #########
Python found it in /home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/z3/__init__.py
Pip version 4.13.0.0
Couldn't find git info
######## unicorn #########
Python found it in /home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/unicorn/__init__.py
Pip version 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/angr/lib/angr_native.so', handle 55d75cf53a50 at 0x7fe7a3f759a0>
unicorn: <CDLL '/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/unicorn/lib/libunicorn.so.2', handle 55d75c8a9510 at 0x7fe7a6d41a90>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fe7a7df1ca0>
z3: <CDLL '/home/nahtaiv3l/rpisec/re/venv/lib/python3.12/site-packages/z3/lib/libz3.so', handle 55d75c415de0 at 0x7fe7aa5c8710>
```

**Comment by twizmwazin** [comment]
This is my fault, I'll have a fix up soon

**Comment by twizmwazin** [comment]
Fix merged to master, there should be a new release tomorrow and then you should be able to update with a `pip install -U angr`. Good luck with rpisec!
