### ISSUE TITLE
undefined symbol: LibVEX_ShowStats"

### ISSUE THREAD

**Issue by bynop** [angr/angr#50]
after update to latest version, no matter what i run example python code, it always show this error

Traceback (most recent call last):
  File "strcpy_test.py", line 11, in <module>
    import angr
  File "/usr/local/lib/python2.7/dist-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 10, in <module>
    import cle
  File "/usr/local/lib/python2.7/dist-packages/cle/__init__.py", line 6, in <module>
    from .loader import *
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 710, in <module>
    from .tls import TLSObj
  File "/usr/local/lib/python2.7/dist-packages/cle/tls.py", line 4, in <module>
    from .backends import Backend
  File "/usr/local/lib/python2.7/dist-packages/cle/backends/__init__.py", line 4, in <module>
    import archinfo
  File "/usr/local/lib/python2.7/dist-packages/archinfo/__init__.py", line 2, in <module>
    from .arch import *
  File "/usr/local/lib/python2.7/dist-packages/archinfo/arch.py", line 7, in <module>
    import pyvex as _pyvex
  File "/usr/local/lib/python2.7/dist-packages/pyvex/__init__.py", line 42, in <module>
    enums_to_ints = { _:getattr(pvc,_) for _ in dir(pvc) if isinstance(getattr(pvc,_), int) }
  File "/usr/local/lib/python2.7/dist-packages/pyvex/__init__.py", line 42, in <dictcomp>
    enums_to_ints = { _:getattr(pvc,_) for _ in dir(pvc) if isinstance(getattr(pvc,_), int) }
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 718, in __getattr__
    make_accessor(name)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 714, in make_accessor
    accessors[name](name)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 659, in accessor_function
    raise AttributeError('%s: %s' % (name, e))
AttributeError: LibVEX_ShowStats: "function 'LibVEX_ShowStats' not found in library '/usr/local/lib/pyvex_static.so': /usr/local/lib/pyvex_static.so: undefined symbol: LibVEX_ShowStats"

**Comment by rhelmot** [comment]
The stop-gap solution to this is to downgrade to the CFFI Python package version.... 1.3.1, I think it is? And then reinstall angr. 

@zardus this is a real problem that you're the only one who can fix in pyvex!!

**Comment by zardus** [comment]
Apparently I'm not as irreplaceable as previously thought :-)

@bynop, https://github.com/angr/pyvex/pull/23 seems to have fixed this issue. Can you confirm it works for you with the latest release of angr (`pip install -U angr`)?

**Comment by bynop** [comment]
@zardus @rhelmot  
thanks for you reply~~,after update to latest version, it works~~~:-)

**Comment by zardus** [comment]
Sweet!
