### ISSUE TITLE
C++using Python interpreter, calling Angr yields an error

### ISSUE THREAD

**Issue by qq415338269** [angr/angr#5038]
### Description

<html>
<body>
<p id="" style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 14px 0px 0px; scrollbar-width: none; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans CN&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 15px; line-height: 1.7; color: rgb(5, 7, 59); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(253, 253, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I have created an EXE project using Visual Studio 2022, where I have included the Python include directories, library directories, and linked the necessary<span> </span><code class=" inline" style="box-sizing: border-box; padding: 1px 4px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px 2px; scrollbar-width: none; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 12.75px; tab-size: 4; background-color: rgba(27, 31, 35, 0.05); border-radius: 3px;">.lib</code><span> </span>files. I am using a Python interpreter to call a Python script from within my C++ project. Everything works fine except when my Python script contains the line<span> </span><code class=" inline" style="box-sizing: border-box; padding: 1px 4px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px 2px; scrollbar-width: none; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 12.75px; tab-size: 4; background-color: rgba(27, 31, 35, 0.05); border-radius: 3px;">import angr</code>. When this line is present, I encounter an error.</p><p id="" style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 14px 0px 0px; scrollbar-width: none; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans CN&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 15px; line-height: 1.7; color: rgb(5, 7, 59); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(253, 253, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I have installed<span> </span><code class=" inline" style="box-sizing: border-box; padding: 1px 4px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px 2px; scrollbar-width: none; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 12.75px; tab-size: 4; background-color: rgba(27, 31, 35, 0.05); border-radius: 3px;">angr</code><span> </span>using Python, and I can use<span> </span><code class=" inline" style="box-sizing: border-box; padding: 1px 4px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px 2px; scrollbar-width: none; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 12.75px; tab-size: 4; background-color: rgba(27, 31, 35, 0.05); border-radius: 3px;">angr</code>'s functionality without any issues when running the script directly through Python. However, when called from my C++ project, it fails. Below is the error message:</p><pre style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 20px 0px; scrollbar-width: none; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 15px; overflow: auto; border-radius: 8px; display: block; position: relative; color: rgb(5, 7, 59); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 253, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="language-" style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px; scrollbar-width: none; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 1em; tab-size: 4;"><div class="code-header" style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px; scrollbar-width: none; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans CN&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot; !important; align-items: center; background: rgb(48, 49, 61); border-radius: 7px 7px 0px 0px; display: flex; height: 37px;"><span class="code-lang" style="box-sizing: border-box; padding: 0px 0px 0px 14px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px; scrollbar-width: none; font-family: &quot;PingFang SC&quot; !important; color: rgb(255, 255, 255); flex: 1 0 auto; font-size: 18px; font-weight: 600; letter-spacing: 0px; line-height: 26px; text-align: justify;"></span><span class="code-copy" style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px; scrollbar-width: none; font-family: PingFangSC-Regular; align-items: center; color: rgba(255, 255, 255, 0.7); display: flex; font-size: 12px; font-weight: 400; letter-spacing: 0px; line-height: 14px; text-align: justify; user-select: none;"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" viewBox="0 0 32 32"><path d="M28 1.333H9.333C8.597 1.333 8 1.93 8 2.667v4H4c-.736 0-1.333.597-1.333 1.333v14.667c0 .353.14.692.39.943l6.667 6.666c.25.25.589.39.943.39h12c.736 0 1.333-.596 1.333-1.333v-4h4c.736 0 1.333-.597 1.333-1.333V2.667c0-.737-.597-1.334-1.333-1.334zM9.333 26.115L7.22 24h2.114v2.115zm12 1.885H12v-5.333c0-.737-.597-1.334-1.333-1.334H5.333v-12h16V28zm5.334-5.333H24V8c0-.736-.597-1.333-1.333-1.333h-12V4h16v18.667z"></path></svg><span class="code-copy-text" style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px 20px 0px 7px; scrollbar-width: none; font-family: Consolas, Monaco, monospace !important;">复制代码</span></span></div><div class="code-wrapper" style="box-sizing: border-box; padding: 14px 14px 14px 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px; scrollbar-width: auto; font-family: Consolas, Monaco, monospace; background: rgb(20, 19, 27); line-height: 24px; overflow: auto;">
  | Traceback (most recent call last):
-- | --
  | File "D:\Code\TestProject\CppCallAngr\x64\Debug\PyClass.py", line 12, in <module>
  | import angr
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\angr\__init__.py", line 41, in <module>
  | from .sim_procedure import SimProcedure
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\angr\sim_procedure.py", line 9, in <module>
  | from cle import SymbolType
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\cle\__init__.py", line 13, in <module>
  | from .backends import (
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\cle\backends\__init__.py", line 5, in <module>
  | from .cartfile import CARTFile
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\cle\backends\cartfile.py", line 13, in <module>
  | import cart
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\cart\__init__.py", line 3, in <module>
  | from cart.cart import (
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\cart\cart.py", line 12, in <module>
  | from Crypto.Cipher import ARC4
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
  | from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 35, in <module>
  | raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | File "D:\Code\Python\PythonVenv\IdaVenv\Lib\site-packages\Crypto\Util\_raw_api.py", line 315, in load_pycryptodome_raw_lib
  | raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
  | OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb_d.cp311-win_amd64.pyd', Not found '_raw_ecb_d.pyd'

</div></code></pre><p id="" style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 14px 0px 0px; scrollbar-width: none; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans CN&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 15px; line-height: 1.7; color: rgb(5, 7, 59); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(253, 253, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I would appreciate any help in resolving this issue. Thank you!</p><hr style="box-sizing: content-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 20px 0px; scrollbar-width: none; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans CN&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(230, 230, 235); color: rgb(5, 7, 59); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(253, 253, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p id="" style="box-sizing: border-box; padding: 0px; -webkit-font-smoothing: antialiased; list-style: none; margin: 14px 0px 0px; scrollbar-width: none; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Ubuntu, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, &quot;Source Han Sans CN&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 15px; line-height: 1.7; color: rgb(5, 7, 59); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(253, 253, 254); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">When posting this question, make sure to mention any relevant details such as the Python version, the version of<span> </span><code class=" inline" style="box-sizing: border-box; padding: 1px 4px; -webkit-font-smoothing: antialiased; list-style: none; margin: 0px 2px; scrollbar-width: none; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 12.75px; tab-size: 4; background-color: rgba(27, 31, 35, 0.05); border-radius: 3px;">angr</code><span> </span>and its dependencies, the configuration of your Visual Studio project, and any steps you have already taken to try to solve the problem. This will help the community provide more targeted assistance.</p>
</body>
</html>

**Comment by qq415338269** [comment]
我知道哪里的问题了，我使用的是调试版本的vs2022和python，I know where the problem is now. I am using the debug version of vs2022 and Python,
