### ISSUE TITLE
angr.errors.SimMemoryError: Not enough data for store

### ISSUE THREAD

**Issue by XX-Official** [angr/angr#5049]
### Question

When I tried to decompile a binary, an error occured:
`File "...\Python310\lib\site-packages\angr\analyses\analysis.py", line 265, in __call__
    r = w(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\analyses\analysis.py", line 250, in wrapper
    oself.__init__(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 841, in __init__
    self._analyze()
  File "...\Python310\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 263, in _analyze
    self._analysis_core_baremetal()
  File "...\Python310\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 385, in _analysis_core_baremetal
    self._job_queue_empty()
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 1563, in _job_queue_empty
    self._process_unresolved_indirect_jumps()
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_base.py", line 2851, in _process_unresolved_indirect_jumps
    all_targets |= self._process_one_indirect_jump(jump)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_base.py", line 2882, in _process_one_indirect_jump
    resolved, targets = resolver.resolve(
  File "...\Python310\lib\site-packages\angr\analyses\cfg\indirect_jump_resolvers\const_resolver.py", line 113, in resolve
    prop = self.project.analyses.Propagator(
  File "...\Python310\lib\site-packages\angr\analyses\analysis.py", line 265, in __call__
    r = w(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\analyses\analysis.py", line 250, in wrapper
    oself.__init__(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\analyses\propagator\propagator.py", line 191, in __init__
    self._analyze()
  File "...\Python310\lib\site-packages\angr\analyses\propagator\propagator.py", line 413, in _analyze
    self._analysis_core_graph()
  File "...\Python310\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 285, in _analysis_core_graph
    changed, output_state = self._run_on_node(n, job_state)
  File "...\Python310\lib\site-packages\angr\analyses\propagator\propagator.py", line 295, in _run_on_node
    state = engine.process(
  File "...\Python310\lib\site-packages\angr\analyses\propagator\engine_base.py", line 48, in process
    self._process(state, None, block=kwargs.pop("block", None))
  File "...\Python310\lib\site-packages\angr\engines\light\engine.py", line 152, in _process
    self._process_Stmt(whitelist=whitelist)
  File "...\Python310\lib\site-packages\angr\engines\light\engine.py", line 172, in _process_Stmt
    self._handle_Stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\light\engine.py", line 202, in _handle_Stmt
    getattr(self, handler)(stmt)
  File "...\Python310\lib\site-packages\angr\analyses\propagator\engine_vex.py", line 166, in _handle_Put
    self.state.store_register(stmt.offset, size, data)
  File "...\Python310\lib\site-packages\angr\knowledge_plugins\propagations\states.py", line 515, in store_register
    self._registers.store(offset, value, size=size)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\size_resolution_mixin.py", line 57, in store
    raise SimMemoryError("Not enough data for store")
angr.errors.SimMemoryError: Not enough data for store`

While debugging this error, I discovered that a function named store is invoked to store a particular piece of data（class claripy.ast.bool.Bool）.
```
class SizeNormalizationMixin(MemoryMixin): 
    def store(self, addr, data, size=None, **kwargs):
        max_size = len(data) // self.state.arch.byte_width
        if size is None:
            out_size = max_size
        elif type(size) is int:
            out_size = size
        elif getattr(size, "op", None) == "BVV":
            out_size = size.args[0]
        else:
            raise Exception("Size must be concretely resolved by this point in the memory stack")
         ......

 size：16
 max_size = len(data) ；0
 out_size:16

if out_size > max_size:
   raise SimMemoryError("Not enough data for store")

What is the cause of this error and what measures should be taken to address it?

**Comment by XX-Official** [comment]
> It’s a bug. Do you have a binary for us to reproduce it?
Thanks for your reply.
Please download the file from this link:  https://downloads.rongcloud.cn/RongIMLib-Harmony-signed-V1.2.0-41.har.  After the download is completed, modify the file extension to.zip and then perform the unzipping operation. For the file within the unzipped folder that has no extension, append.zip to its name and subsequently conduct another unzipping process. The binary file can be found at package/libs/arm64 - v8a/librongimlib.so.

**Comment by XX-Official** [comment]
And when I tried to decompile another binary, a new error occured:
Traceback (most recent call last):
  File "D:\ProgramFiles\Python\Python310\lib\site-packages\claripy\frontend\light_frontend.py", line 51, in eval
    return tuple(self._solver_backend.eval(e, n))
  File "D:\ProgramFiles\Python\Python310\lib\site-packages\claripy\backends\backend.py", line 527, in eval
    self.convert(expr),
  File "D:\ProgramFiles\Python\Python310\lib\site-packages\claripy\backends\backend_vsa\backend_vsa.py", line 109, in convert
    return Backend.convert(self, claripy.excavate_ite(expr) if isinstance(expr, Base) else expr)
  File "D:\ProgramFiles\Python\Python310\lib\site-packages\claripy\backends\backend.py", line 173, in convert
    converted = self._convert(ast)
  File "D:\ProgramFiles\Python\Python310\lib\site-packages\claripy\backends\backend_vsa\backend_vsa.py", line 122, in _convert
    raise BackendError
claripy.errors.BackendError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\Python310\lib\site-packages\angr\state_plugins\solver.py", line 98, in wrapped_f
    return f(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\state_plugins\solver.py", line 539, in _eval
    return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "...\Python310\lib\site-packages\claripy\frontend\mixin\concrete_handler_mixin.py", line 13, in eval
    return super().eval(e, n, extra_constraints=extra_constraints, exact=exact)
  File "...\Python310\lib\site-packages\claripy\frontend\mixin\constraint_filter_mixin.py", line 45, in eval
    return super().eval(e, n, extra_constraints=ec, exact=exact)
  File "...\Python310\lib\site-packages\claripy\frontend\light_frontend.py", line 53, in eval
    raise ClaripyFrontendError("Light solver can't handle this eval().") from err
claripy.errors.ClaripyFrontendError: Light solver can't handle this eval().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "...\Python310\lib\site-packages\angr\analyses\analysis.py", line 265, in __call__
    r = w(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\analyses\analysis.py", line 250, in wrapper
    oself.__init__(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 841, in __init__
    self._analyze()
  File "...\Python310\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 263, in _analyze
    self._analysis_core_baremetal()
  File "...\Python310\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 385, in _analysis_core_baremetal
    self._job_queue_empty()
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 1563, in _job_queue_empty
    self._process_unresolved_indirect_jumps()
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_base.py", line 2851, in _process_unresolved_indirect_jumps
    all_targets |= self._process_one_indirect_jump(jump)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_base.py", line 2882, in _process_one_indirect_jump
    resolved, targets = resolver.resolve(
  File "...\Python310\lib\site-packages\angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 874, in resolve
    return self._resolve(
  File "...\Python310\lib\site-packages\angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 1066, in _resolve
    ret = self._try_resolve_targets_load(
  File "...\Python310\lib\site-packages\angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 1701, in _try_resolve_targets_load
    jump_base_addr.base_addr = state.solver.eval(state.scratch.temps[jump_base_addr.tmp_1])
  File "...\Python310\lib\site-packages\angr\state_plugins\solver.py", line 897, in eval
    return self.eval_upto(e, 1, cast_to, **kwargs)[0]
  File "...\Python310\lib\site-packages\angr\state_plugins\solver.py", line 857, in eval_upto
    cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
  File "...\Python310\lib\site-packages\angr\state_plugins\solver.py", line 167, in concrete_shortcut_tuple
    return f(self, *args, **kwargs)
  File "...\Python310\lib\site-packages\angr\state_plugins\sim_action_object.py", line 57, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "...\Python310\lib\site-packages\angr\state_plugins\solver.py", line 102, in wrapped_f
    raise SimSolverModeError("Claripy threw an error") from e
angr.errors.SimSolverModeError: Claripy threw an error

Can I consider that the cause of this error is that Claripy is unable to handle such a situation? Also, why does this error come up and how can I solve it?

**Comment by XX-Official** [comment]
Another error：

Traceback (most recent call last):
  File "...\test.py", line 21, in PrintFunc
    cfg = p.analyses.CFGFast(normalize=True)
  File "...\Python310\lib\site-packages\angr\analyses\analysis.py", line 265, in __call__
    r = w(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\analyses\analysis.py", line 250, in wrapper
    oself.__init__(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 841, in __init__
    self._analyze()
  File "...\Python310\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 263, in _analyze
    self._analysis_core_baremetal()
  File "...\Python310\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 408, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "...\Python310\lib\site-packages\angr\analyses\forward_analysis\forward_analysis.py", line 426, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 1443, in _get_successors
    jobs = self._scan_block(job)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 1980, in _scan_block
    entries = self._scan_irsb(cfg_job, current_func_addr)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 2244, in _scan_irsb
    new_jobs = self._create_jobs(target, jumpkind, function_addr, irsb, addr, cfg_node, ins_addr, stmt_idx)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 2384, in _create_jobs
    resolved_as_plt = self._resolve_plt(addr, irsb, ij)
  File "...\Python310\lib\site-packages\angr\analyses\cfg\cfg_fast.py", line 3076, in _resolve_plt
    simsucc = self.project.factory.default_engine.process(self._initial_state, irsb, force_addr=addr)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\slicing.py", line 21, in process
    return super().process(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\engine.py", line 160, in process
    self.process_successors(self.successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\failure.py", line 25, in process_successors
    return super().process_successors(successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\syscall.py", line 27, in process_successors
    return super().process_successors(successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\hook.py", line 57, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\unicorn.py", line 395, in process_successors
    return super().process_successors(successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\soot\engine.py", line 69, in process_successors
    return super().process_successors(successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 177, in process_successors
    self.handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\super_fastpath.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\slicing.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\actions.py", line 29, in handle_vex_block
    super().handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 50, in handle_vex_block
    super().handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 554, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\slicing.py", line 31, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 45, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\resilience.py", line 40, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 248, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 53, in _handle_vex_stmt
    handler(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 210, in _handle_vex_stmt_WrTmp
    self._perform_vex_stmt_WrTmp(stmt.tmp, self._analyze_vex_stmt_WrTmp_data(stmt.data))
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 202, in _analyze_vex_stmt_WrTmp_data
    return self._handle_vex_expr(*a, **kw)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 36, in _handle_vex_expr
    return super()._handle_vex_expr(expr)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 58, in _handle_vex_expr
    result = handler(expr)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 118, in _handle_vex_expr_Unop
    return self._handle_vex_expr_Op(expr)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 130, in _handle_vex_expr_Op
    return self._perform_vex_expr_Op(expr.op, [self._handle_vex_expr(arg) for arg in expr.args])
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 130, in <listcomp>
    return self._perform_vex_expr_Op(expr.op, [self._handle_vex_expr(arg) for arg in expr.args])
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 36, in _handle_vex_expr
    return super()._handle_vex_expr(expr)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 59, in _handle_vex_expr
    return self._instrument_vex_expr(result)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\actions.py", line 44, in _instrument_vex_expr
    return super()._instrument_vex_expr(result[0]), result[1]
  File "...\Python310\lib\site-packages\claripy\ast\bv.py", line 77, in __getitem__
    return Extract(int(rng), int(rng), self)
  File "...\Python310\lib\site-packages\claripy\operations.py", line 63, in _op
    raise ClaripyOperationError(msg)
claripy.errors.ClaripyOperationError: Extract bound must be less than BV size

I debugged this error and found that the current statement is t61 = 1Uto64(t62), and the parameters passed to the function ‘extract_check’ are:
high = 0
low = 0 
bv = <BV1 0> 
bv.size = 1

**Comment by XX-Official** [comment]
New error：

Traceback (most recent call last):
  File "...\Python310\lib\site-packages\angr\analyses\cfg\indirect_jump_resolvers\jumptable.py", line 1658, in _try_resolve_targets_load
    succ = project.factory.successors(r, whitelist=whitelist, last_stmt=last_stmt)
  File "...\Python310\lib\site-packages\angr\factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\slicing.py", line 21, in process
    return super().process(*args, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\engine.py", line 160, in process
    self.process_successors(self.successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\failure.py", line 25, in process_successors
    return super().process_successors(successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\syscall.py", line 27, in process_successors
    return super().process_successors(successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\hook.py", line 57, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\unicorn.py", line 395, in process_successors
    return super().process_successors(successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\soot\engine.py", line 69, in process_successors
    return super().process_successors(successors, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 177, in process_successors
    self.handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\super_fastpath.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\slicing.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\actions.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 51, in handle_vex_block
    super().handle_vex_block(irsb)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 549, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\slicing.py", line 31, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 45, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\resilience.py", line 40, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 248, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 54, in _handle_vex_stmt
    handler(stmt)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 205, in _handle_vex_stmt_WrTmp
    self._perform_vex_stmt_WrTmp(stmt.tmp, self._analyze_vex_stmt_WrTmp_data(stmt.data))
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 202, in _analyze_vex_stmt_WrTmp_data
    return self._handle_vex_expr(*a, **kw)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\inspect.py", line 36, in _handle_vex_expr
    return super()._handle_vex_expr(expr)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 58, in _handle_vex_expr
    result = handler(expr)
  File "...\Python310\lib\site-packages\angr\engines\vex\light\light.py", line 89, in _handle_vex_expr_Load
    return self._perform_vex_expr_Load(self._analyze_vex_expr_Load_addr(expr.addr), expr.ty, expr.end)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\actions.py", line 123, in _perform_vex_expr_Load
    result = super()._perform_vex_expr_Load(addr, ty, endness, condition=condition, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 356, in _perform_vex_expr_Load
    result = super()._perform_vex_expr_Load(addr, ty, endness, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\vex\claripy\datalayer.py", line 92, in _perform_vex_expr_Load
    res = super()._perform_vex_expr_Load(addr, ty, endness, **kwargs)
  File "...\Python310\lib\site-packages\angr\engines\vex\heavy\heavy.py", line 32, in _perform_vex_expr_Load
    return self.state.memory.load(
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\unwrapper_mixin.py", line 17, in load
    return super().load(
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\name_resolution_mixin.py", line 66, in load
    return super().load(addr, size=size, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\bvv_conversion_mixin.py", line 31, in load
    return super().load(addr, size=size, fallback=fallback_bv, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\clouseau_mixin.py", line 97, in load
    r = super().load(addr, size=size, condition=condition, endness=endness, inspect=inspect, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\actions_mixin.py", line 14, in load
    r = super().load(addr, size=size, condition=condition, fallback=fallback, action=action, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\underconstrained_mixin.py", line 27, in load
    return super().load(addr, size, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\size_resolution_mixin.py", line 93, in load
    return super().load(addr, size=size, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\size_resolution_mixin.py", line 31, in load
    return super().load(addr, size=out_size, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\actions_mixin.py", line 64, in load
    return super().load(addr, size, action=action, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\conditional_store_mixin.py", line 9, in load
    res = super().load(addr, size, condition=condition, **kwargs)
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\regioned_memory\regioned_memory_mixin.py", line 107, in load
    if (regioned_addrs_desc.cardinality > 1 and AVOID_MULTIVALUED_READS in self.state.options) or (
  File "...\Python310\lib\site-packages\angr\storage\memory_mixins\regioned_memory\abstract_address_descriptor.py", line 29, in cardinality
    n += si.cardinality
  File "...\Python310\lib\site-packages\claripy\ast\base.py", line 897, in cardinality
    return claripy.backends.any_backend.cardinality(self)
  File "...\Python310\lib\site-packages\claripy\backends\backend_any.py", line 74, in cardinality
    return self._first_backend(a, "cardinality")
  File "...\Python310\lib\site-packages\claripy\backends\backend_any.py", line 32, in _first_backend
    raise BackendError(f"All backends failed to {what}")
claripy.errors.BackendError: All backends failed to cardinality

The statement is t18 = LDle:I64(t39).

**Comment by XX-Official** [comment]
@ltfish Could you assist in resolving these three newly emerged issues?

**Comment by Ryan-hub-bit** [comment]
any update on this issue?
