### ISSUE TITLE
VFG: claripy.errors.ClaripyOperationError: args' length must all be equal

### ISSUE THREAD

**Issue by XX-Official** [angr/angr#5082]
### Question

When I attempted to conduct a VFG analysis on a binary file, an error occurred：

```
Traceback (most recent call last):
  File "… /angr/analyses/vfg.py", line 1431, in _get_simsuccessors
    sim_successors = self.project.factory.successors(state, jumpkind=jumpkind, num_inst=num_inst)
  File "…/angr/factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
  File "…/angr/engines/vex/light/slicing.py", line 21, in process
    return super().process(*args, **kwargs)
  File "…/angr/engines/engine.py", line 160, in process
    self.process_successors(self.successors, **kwargs)
  File "…/angr/engines/failure.py", line 25, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/syscall.py", line 27, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/hook.py", line 57, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "…/angr/engines/unicorn.py", line 395, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/soot/engine.py", line 69, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 175, in process_successors
    self.handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/super_fastpath.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/light/slicing.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/actions.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/inspect.py", line 51, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/light/light.py", line 549, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/slicing.py", line 31, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/heavy/inspect.py", line 46, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/resilience.py", line 40, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 247, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/light.py", line 53, in _handle_vex_stmt
    handler(stmt)
  File "…/angr/engines/vex/light/light.py", line 207, in _handle_vex_stmt_WrTmp
    self._perform_vex_stmt_WrTmp(stmt.tmp, self._analyze_vex_stmt_WrTmp_data(stmt.data))
  File "…/angr/engines/vex/light/light.py", line 202, in _analyze_vex_stmt_WrTmp_data
    return self._handle_vex_expr(*a, **kw)
  File "…/angr/engines/vex/heavy/inspect.py", line 37, in _handle_vex_expr
    return super()._handle_vex_expr(expr)
  File "…/angr/engines/vex/light/light.py", line 58, in _handle_vex_expr
    result = handler(expr)
  File "…/angr/engines/vex/light/light.py", line 89, in _handle_vex_expr_Load
    return self._perform_vex_expr_Load(self._analyze_vex_expr_Load_addr(expr.addr), expr.ty, expr.end)
  File "…/angr/engines/vex/heavy/actions.py", line 123, in _perform_vex_expr_Load
    result = super()._perform_vex_expr_Load(addr, ty, endness, condition=condition, **kwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 355, in _perform_vex_expr_Load
    result = super()._perform_vex_expr_Load(addr, ty, endness, **kwargs)
  File "…/angr/engines/vex/claripy/datalayer.py", line 92, in _perform_vex_expr_Load
    res = super()._perform_vex_expr_Load(addr, ty, endness, **kwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 32, in _perform_vex_expr_Load
    return self.state.memory.load(
  File "…/angr/storage/memory_mixins/unwrapper_mixin.py", line 17, in load
    return super().load(
  File "…/angr/storage/memory_mixins/name_resolution_mixin.py", line 66, in load
    return super().load(addr, size=size, **kwargs)
  File "…/angr/storage/memory_mixins/bvv_conversion_mixin.py", line 31, in load
    return super().load(addr, size=size, fallback=fallback_bv, **kwargs)
  File "…/angr/storage/memory_mixins/clouseau_mixin.py", line 68, in load
    return super().load(addr, size=size, condition=condition, endness=endness, inspect=inspect, **kwargs)
  File "…/angr/storage/memory_mixins/actions_mixin.py", line 14, in load
    r = super().load(addr, size=size, condition=condition, fallback=fallback, action=action, **kwargs)
  File "…/angr/storage/memory_mixins/underconstrained_mixin.py", line 27, in load
    return super().load(addr, size, **kwargs)
  File "…/angr/storage/memory_mixins/size_resolution_mixin.py", line 93, in load
    return super().load(addr, size=size, **kwargs)
  File "…/angr/storage/memory_mixins/size_resolution_mixin.py", line 31, in load
    return super().load(addr, size=out_size, **kwargs)
  File "…/angr/storage/memory_mixins/actions_mixin.py", line 64, in load
    return super().load(addr, size, action=action, **kwargs)
  File "…/angr/storage/memory_mixins/conditional_store_mixin.py", line 9, in load
    res = super().load(addr, size, condition=condition, **kwargs)
  File "…/angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py", line 150, in load
    val = val.union(new_val)
  File "…/claripy/operations.py", line 62, in _op
    raise ClaripyOperationError(msg)
claripy.errors.ClaripyOperationError: args' length must all be equal
Traceback (most recent call last):
  File "…/angr/analyses/vfg.py", line 1431, in _get_simsuccessors
    sim_successors = self.project.factory.successors(state, jumpkind=jumpkind, num_inst=num_inst)
  File "…/angr/factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
  File "…/angr/engines/vex/light/slicing.py", line 21, in process
    return super().process(*args, **kwargs)
  File "…/angr/engines/engine.py", line 160, in process
    self.process_successors(self.successors, **kwargs)
  File "…/angr/engines/failure.py", line 25, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/syscall.py", line 27, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/hook.py", line 57, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "…/angr/engines/unicorn.py", line 395, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/soot/engine.py", line 69, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 175, in process_successors
    self.handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/super_fastpath.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/light/slicing.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/actions.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/inspect.py", line 51, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/light/light.py", line 549, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/slicing.py", line 31, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/heavy/inspect.py", line 46, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/resilience.py", line 40, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 247, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/light.py", line 53, in _handle_vex_stmt
    handler(stmt)
  File "…/angr/engines/vex/light/light.py", line 207, in _handle_vex_stmt_WrTmp
    self._perform_vex_stmt_WrTmp(stmt.tmp, self._analyze_vex_stmt_WrTmp_data(stmt.data))
  File "…/angr/engines/vex/light/light.py", line 202, in _analyze_vex_stmt_WrTmp_data
    return self._handle_vex_expr(*a, **kw)
  File "…/angr/engines/vex/heavy/inspect.py", line 37, in _handle_vex_expr
    return super()._handle_vex_expr(expr)
  File "…/angr/engines/vex/light/light.py", line 58, in _handle_vex_expr
    result = handler(expr)
  File "…/angr/engines/vex/light/light.py", line 89, in _handle_vex_expr_Load
    return self._perform_vex_expr_Load(self._analyze_vex_expr_Load_addr(expr.addr), expr.ty, expr.end)
  File "…/angr/engines/vex/heavy/actions.py", line 123, in _perform_vex_expr_Load
    result = super()._perform_vex_expr_Load(addr, ty, endness, condition=condition, **kwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 355, in _perform_vex_expr_Load
    result = super()._perform_vex_expr_Load(addr, ty, endness, **kwargs)
  File "…/angr/engines/vex/claripy/datalayer.py", line 92, in _perform_vex_expr_Load
    res = super()._perform_vex_expr_Load(addr, ty, endness, **kwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 32, in _perform_vex_expr_Load
    return self.state.memory.load(
  File "…/angr/storage/memory_mixins/unwrapper_mixin.py", line 17, in load
    return super().load(
  File "…/angr/storage/memory_mixins/name_resolution_mixin.py", line 66, in load
    return super().load(addr, size=size, **kwargs)
  File "…/angr/storage/memory_mixins/bvv_conversion_mixin.py", line 31, in load
    return super().load(addr, size=size, fallback=fallback_bv, **kwargs)
  File "…/angr/storage/memory_mixins/clouseau_mixin.py", line 68, in load
    return super().load(addr, size=size, condition=condition, endness=endness, inspect=inspect, **kwargs)
  File "…/angr/storage/memory_mixins/actions_mixin.py", line 14, in load
    r = super().load(addr, size=size, condition=condition, fallback=fallback, action=action, **kwargs)
  File "…/angr/storage/memory_mixins/underconstrained_mixin.py", line 27, in load
    return super().load(addr, size, **kwargs)
  File "…/angr/storage/memory_mixins/size_resolution_mixin.py", line 93, in load
    return super().load(addr, size=size, **kwargs)
  File "…/angr/storage/memory_mixins/size_resolution_mixin.py", line 31, in load
    return super().load(addr, size=out_size, **kwargs)
  File "…/angr/storage/memory_mixins/actions_mixin.py", line 64, in load
    return super().load(addr, size, action=action, **kwargs)
  File "…/angr/storage/memory_mixins/conditional_store_mixin.py", line 9, in load
    res = super().load(addr, size, condition=condition, **kwargs)
  File "…/angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py", line 150, in load
    val = val.union(new_val)
  File "…/claripy/operations.py", line 62, in _op
    raise ClaripyOperationError(msg)
claripy.errors.ClaripyOperationError: args' length must all be equal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/angr/misc/plugins.py", line 252, in request_plugin
    return self._default_plugins[name]
KeyError: 'simos'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "…/angr/misc/plugins.py", line 77, in __getattr__
    return self.get_plugin(name)
  File "…/angr/sim_state.py", line 425, in get_plugin
    return super().get_plugin(name)
  File "…/angr/misc/plugins.py", line 161, in get_plugin
    plugin_cls: type[P] = self._active_preset.request_plugin(name)
  File "…/angr/misc/plugins.py", line 254, in request_plugin
    raise AngrNoPluginError(f"There is no plugin named {name}") from err
angr.errors.AngrNoPluginError: There is no plugin named simos

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "…/test.py", line 175, in <module>
    run(bin_path)
  File "…/test.py", line 59, in run_cj
    vfg = proj.analyses.VFG(
  File "…/angr/analyses/analysis.py", line 259, in __call__
    r = w(*args, **kwargs)
  File "…/angr/analyses/analysis.py", line 244, in wrapper
    oself.__init__(*args, **kwargs)
  File "…/angr/analyses/vfg.py", line 414, in __init__
    self._analyze()
  File "…/angr/analyses/forward_analysis/forward_analysis.py", line 263, in _analyze
    self._analysis_core_baremetal()
  File "…/angr/analyses/forward_analysis/forward_analysis.py", line 394, in _analysis_core_baremetal
    self._pre_job_handling(job_info.job)
  File "…/angr/analyses/vfg.py", line 717, in _pre_job_handling
    job.sim_successors, _, restart_analysis = self._get_simsuccessors(input_state, addr)
  File "…/angr/analyses/vfg.py", line 1444, in _get_simsuccessors
    sim_successors = ProcedureEngine().process(state, procedure=inst)
  File "…/angr/engines/engine.py", line 160, in process
    self.process_successors(self.successors, **kwargs)
  File "…/angr/engines/procedure.py", line 67, in process_successors
    self.process_procedure(self.state, successors, procedure, **kwargs)
  File "…/angr/engines/procedure.py", line 40, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to, arguments=arguments)
  File "…/angr/sim_procedure.py", line 205, in execute
    self.project.simos.name if self.project is not None and self.project.simos is not None else None
  File "…/angr/misc/plugins.py", line 79, in __getattr__
    raise AttributeError(name) from err
AttributeError: simos

I debugged this error and discovered that when processing the statement "t15 = LDle:I64(t26)", the issue arose.
expr.addr = <BV64 reg_x28_24_64 + 0x28>

def load(self, addr, size: BV | int | None = None, *, endness=None, condition: Bool | None = None, **kwargs):
  ..
  val = new_val if val is None else val.union(new_val)
  ...

  val = <BV64 global_0_25_64>
  new_val  = <BV56 global_0_25_64[63:8]>

The complete block is：

IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64 t3:Ity_I64 t4:Ity_I64 t5:Ity_I64 t6:Ity_I64 t7:Ity_I64 t8:Ity_I64 t9:Ity_I64 t10:Ity_I64 t11:Ity_I64 t12:Ity_I64 t13:Ity_I64 t14:Ity_I64 t15:Ity_I64 t16:Ity_I64 t17:Ity_I64 t18:Ity_I64 t19:Ity_I64 t20:Ity_I64 t21:Ity_I64 t22:Ity_I64 t23:Ity_I64 t24:Ity_I64 t25:Ity_I64 t26:Ity_I64 t27:Ity_I64 t28:Ity_I1 t29:Ity_I64 t30:Ity_I64 t31:Ity_I64 t32:Ity_I64 t33:Ity_I64 t34:Ity_I64 t35:Ity_I64 t36:Ity_I64 t37:Ity_I1 t38:Ity_I1

   00 | ------ IMark(0x457850, 4, 0) ------
   01 | t0 = GET:I64(xsp)
   02 | t2 = Sub64(t0,0x0000000000000040)
   03 | PUT(xsp) = t2
   04 | PUT(pc) = 0x0000000000457854
   05 | ------ IMark(0x457854, 4, 0) ------
   06 | t4 = Add64(t2,0x0000000000000030)
   07 | t22 = GET:I64(x29)
   08 | STle(t4) = t22
   09 | t23 = Add64(t4,0x0000000000000008)
   10 | t24 = GET:I64(x30)
   11 | STle(t23) = t24
   12 | ------ IMark(0x457858, 4, 0) ------
   13 | t9 = Add64(t2,0x0000000000000030)
   14 | PUT(x29) = t9
   15 | ------ IMark(0x45785c, 4, 0) ------
   16 | PUT(pc) = 0x0000000000457860
   17 | ------ IMark(0x457860, 4, 0) ------
   18 | t11 = Add64(t9,0xfffffffffffffff8)
   19 | STle(t11) = 0x0000000000457850
   20 | PUT(pc) = 0x0000000000457864
   21 | ------ IMark(0x457864, 4, 0) ------
   22 | t27 = GET:I64(x28)
   23 | t26 = Add64(t27,0x0000000000000028)
   24 | t15 = LDle:I64(t26)
   25 | PUT(x9) = t15
   26 | ------ IMark(0x457868, 4, 0) ------
   27 | PUT(cc_op) = 0x0000000000000004
   28 | PUT(cc_dep1) = t2
   29 | PUT(cc_dep2) = t15
   30 | PUT(cc_ndep) = 0x0000000000000000
   31 | PUT(pc) = 0x000000000045786c
   32 | ------ IMark(0x45786c, 4, 0) ------
   33 | t37 = CmpLT64U(t15,t2)
   34 | t36 = 1Uto64(t37)
   35 | t34 = t36
   36 | t38 = 64to1(t34)
   37 | t28 = t38
   38 | if (t28) { PUT(pc) = 0x45787c; Ijk_Boring }
   NEXT: PUT(pc) = 0x0000000000457870; Ijk_Boring
}
```

**Comment by XX-Official** [comment]
> What's the binary that you are analyzing? Looks like you successfully triggered a code path where project.simos is not set. Can you please post the binary?

I'm truly sorry. Owing to specific personal circumstances, I am unable to furnish this binary file. Nevertheless, during the process of attempting to rectify this error, I have come across several difficulties.
To begin with, I made an effort to comprehend the function
`def load(self, addr, size: BV | int | None = None, *, endness=None, condition: Bool | None = None, **kwargs)`
which is situated in /…/angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py.

In my perspective, the crux of this code can be described as follows: For every aw (where an aw represents an individual region), the function _region_load is called, aiming to load data (new_val) from the corresponding address. Subsequently, the value of val is updated accordingly.

To address the error "claripy.errors.ClaripyOperationError: args' length must all be equal", I have incorporated a judgment condition prior to the operation val.union(new_val).

```
if val is None:
     val = new_val
else:  
     if len(val) == len(new_val):
          val = val.union(new_val)
```

I discovered that when processing a statement, the process repeated for over 200 times, and the final val is
`<BV64 union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(union(…(union(0x2, 0x2)…), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2), 0x2)>`.

Simultaneously, a new error has cropped up instead.

```
Traceback (most recent call last):
  File "… /claripy/backends/backend.py", line 355, in is_false
    return self._false_cache[e.hash()]
KeyError: 10599235190095902109

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/claripy/algorithm/ite_relocation.py", line 61, in _excavate_ite
    ast = next(ast_queue[-1])
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/claripy/backends/backend.py", line 205, in convert
    r = op(ast)
  File "…/claripy/backends/backend_vsa/backend_vsa.py", line 429, in union
    converted_0 = self.convert(ast.args[0])
  File "…/claripy/backends/backend_vsa/backend_vsa.py", line 110, in convert
    return Backend.convert(self, claripy.excavate_ite(expr) if isinstance(expr, Base) else expr)
  File "…/claripy/algorithm/ite_relocation.py", line 158, in excavate_ite
    excavated = _excavate_ite(expr)
  File "…/claripy/algorithm/ite_relocation.py", line 95, in _excavate_ite
    excavated = op.swap_args(args, simplify=True)
  File "…/claripy/ast/base.py", line 839, in swap_args
    if len(self.args) == len(new_args) and all(a is b for a, b in zip(self.args, new_args, strict=False)):
RecursionError: maximum recursion depth exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "…/angr/state_plugins/solver.py", line 98, in wrapped_f
    return f(*args, **kwargs)
  File "…/angr/state_plugins/solver.py", line 662, in is_false
    return self._solver.is_false(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "…/claripy/frontend/mixin/concrete_handler_mixin.py", line 57, in is_false
    return super().is_false(e, extra_constraints=extra_constraints, exact=exact)
  File "…/claripy/frontend/mixin/constraint_filter_mixin.py", line 69, in is_false
    return super().is_false(e, extra_constraints=ec, exact=exact)
  File "…/claripy/frontend/light_frontend.py", line 88, in is_false
    return self._solver_backend.is_false(e)
  File "…/claripy/backends/backend.py", line 358, in is_false
    self.convert(e), extra_constraints=extra_constraints, solver=solver, model_callback=model_callback
  File "…/claripy/backends/backend_vsa/backend_vsa.py", line 110, in convert
    return Backend.convert(self, claripy.excavate_ite(expr) if isinstance(expr, Base) else expr)
  File "…/claripy/backends/backend.py", line 205, in convert
    r = op(ast)
  File "…/claripy/backends/backend_vsa/backend_vsa.py", line 429, in union
    converted_0 = self.convert(ast.args[0])
  File "…/claripy/backends/backend_vsa/backend_vsa.py", line 110, in convert
return Backend.convert(self, claripy.excavate_ite(expr) if isinstance(expr, Base) else expr)
…
File "…/claripy/backends/backend.py", line 205, in convert
    r = op(ast)
  File "…/claripy/backends/backend_vsa/backend_vsa.py", line 429, in union
    converted_0 = self.convert(ast.args[0])
  File "…/claripy/backends/backend_vsa/backend_vsa.py", line 110, in convert
    return Backend.convert(self, claripy.excavate_ite(expr) if isinstance(expr, Base) else expr)
  File "…/claripy/backends/backend.py", line 225, in convert
    raise ClaripyRecursionError("Recursion limit reached. Sorry about that.") from e
claripy.errors.ClaripyRecursionError: Recursion limit reached. Sorry about that.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "…/angr/analyses/vfg.py", line 1431, in _get_simsuccessors
    sim_successors = self.project.factory.successors(state, jumpkind=jumpkind, num_inst=num_inst)
  File "…/angr/factory.py", line 82, in successors
    return self.default_engine.process(*args, **kwargs)
  File "…/angr/engines/vex/light/slicing.py", line 21, in process
    return super().process(*args, **kwargs)
  File "…/angr/engines/engine.py", line 160, in process
    self.process_successors(self.successors, **kwargs)
  File "…/angr/engines/failure.py", line 25, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/syscall.py", line 27, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/hook.py", line 57, in process_successors
    return super().process_successors(successors, procedure=procedure, **kwargs)
  File "…/angr/engines/unicorn.py", line 395, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/soot/engine.py", line 69, in process_successors
    return super().process_successors(successors, **kwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 175, in process_successors
    self.handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/super_fastpath.py", line 26, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/light/slicing.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/actions.py", line 27, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/heavy/inspect.py", line 51, in handle_vex_block
    super().handle_vex_block(irsb)
  File "…/angr/engines/vex/light/light.py", line 549, in handle_vex_block
    self._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/slicing.py", line 31, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/heavy/inspect.py", line 46, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/resilience.py", line 40, in inner
    return getattr(super(VEXResilienceMixin, self), func)(*iargs, **ikwargs)
  File "…/angr/engines/vex/heavy/heavy.py", line 247, in _handle_vex_stmt
    super()._handle_vex_stmt(stmt)
  File "…/angr/engines/vex/light/light.py", line 53, in _handle_vex_stmt
    handler(stmt)
  File "…/angr/engines/vex/light/light.py", line 230, in _handle_vex_stmt_Exit
    self._perform_vex_stmt_Exit(
  File "…/angr/engines/vex/heavy/actions.py", line 221, in _perform_vex_stmt_Exit
    super()._perform_vex_stmt_Exit(guard, target, jumpkind)
  File "…/angr/engines/vex/heavy/heavy.py", line 314, in _perform_vex_stmt_Exit
    self.successors.add_successor(
  File "…/angr/engines/successors.py", line 132, in add_successor
    self._preprocess_successor(state, add_guard=add_guard)
  File "…/angr/engines/successors.py", line 167, in _preprocess_successor
    state.add_constraints(state.scratch.guard)
  File "../angr/sim_state.py", line 494, in add_constraints
    return self.solver.add(*constraints)
  File "…/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "…/angr/state_plugins/solver.py", line 98, in wrapped_f
    return f(*args, **kwargs)
  File "…/angr/state_plugins/solver.py", line 734, in add
    if self.is_false(arg):
  File "…/angr/state_plugins/solver.py", line 145, in concrete_shortcut_not_bool
    return f(self, *args, **kwargs)
  File "…/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "…/angr/state_plugins/solver.py", line 102, in wrapped_f
    raise SimSolverModeError("Claripy threw an error") from e
angr.errors.SimSolverModeError: Claripy threw an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/angr/misc/plugins.py", line 252, in request_plugin
    return self._default_plugins[name]
KeyError: 'simos'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "…/angr/misc/plugins.py", line 77, in __getattr__
    return self.get_plugin(name)
  File "…/angr/sim_state.py", line 425, in get_plugin
    return super().get_plugin(name)
  File "…/angr/misc/plugins.py", line 161, in get_plugin
    plugin_cls: type[P] = self._active_preset.request_plugin(name)
  File "…/angr/misc/plugins.py", line 254, in request_plugin
    raise AngrNoPluginError(f"There is no plugin named {name}") from err
angr.errors.AngrNoPluginError: There is no plugin named simos

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "…/Test_vfg.py", line 38, in run_cj
    vfg = proj.analyses.VFG(
  File "…/angr/analyses/analysis.py", line 259, in __call__
    r = w(*args, **kwargs)
  File "…/angr/analyses/analysis.py", line 244, in wrapper
    oself.__init__(*args, **kwargs)
  File "…/angr/analyses/vfg.py", line 414, in __init__
    self._analyze()
  File "…/angr/analyses/forward_analysis/forward_analysis.py", line 263, in _analyze
    self._analysis_core_baremetal()
  File "…/angr/analyses/forward_analysis/forward_analysis.py", line 394, in _analysis_core_baremetal
    self._pre_job_handling(job_info.job)
  File "…/angr/analyses/vfg.py", line 717, in _pre_job_handling
    job.sim_successors, _, restart_analysis = self._get_simsuccessors(input_state, addr)
  File "…/angr/analyses/vfg.py", line 1451, in _get_simsuccessors
    sim_successors = ProcedureEngine().process(state, procedure=inst)
  File "…/angr/engines/engine.py", line 160, in process
    self.process_successors(self.successors, **kwargs)
  File "…/angr/engines/procedure.py", line 67, in process_successors
    self.process_procedure(self.state, successors, procedure, **kwargs)
  File "…/angr/engines/procedure.py", line 40, in process_procedure
    inst = procedure.execute(state, successors, ret_to=ret_to, arguments=arguments)
  File "…/angr/sim_procedure.py", line 205, in execute
    self.project.simos.name if self.project is not None and self.project.simos is not None else None
  File "…/angr/misc/plugins.py", line 79, in __getattr__
    raise AttributeError(name) from err
AttributeError: simos
```

Why did such a situation arise? And how can I resolve this issue?
