### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by juneJuly** [angr/angr#515]
run example:
```
import angr
proj = angr.Project('./fauxware')
cfg = proj.analyses.CFG()
dict(proj.kb.functions)

```
then, got an error:
```
WARNING | 2017-07-04 11:30:54,475 | claripy | Claripy is setting the recursion limit to 15000. If Python segfaults, I am sorry.
WARNING | 2017-07-04 11:30:55,569 | angr.analyses.cfg_fast | "auto_load_libs" is enabled. With libraries loaded in project, CFGFast will cover libraries, which may take significantly more time than expected. You may reload the binary with "auto_load_libs" disabled, or specify "regions" to limit the scope of CFG recovery.

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    cfg = proj.analyses.CFG()
  File "/home/june/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/june/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg.py", line 56, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/home/june/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 770, in __init__
    self._analyze()
  File "/home/june/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 500, in _analyze
    self._analysis_core_baremetal()
  File "/home/june/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 601, in _analysis_core_baremetal
    self._job_queue_empty()
  File "/home/june/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1201, in _job_queue_empty
    jump_targets = list(set(self._process_indirect_jumps()))
  File "/home/june/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 2355, in _process_indirect_jumps
    resolvable, targets = self._resolve_jump_table_fast(jump.addr, jump.jumpkind)
  File "/home/june/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 2498, in _resolve_jump_table_fast
    stmt = block.statements[stmt_idx]
IndexError: list index out of range
```

shall i set some index limit? or some flag?
and what did the WANRING mean?

**Comment by juneJuly** [comment]
run 
```
import angr
proj = angr.Project('../defcamp_r100/r100')
cfg = proj.analyses.CFG()
dict(proj.kb.functions)
```
just got the same error, did i use angr in a wrong way?

**Comment by ltfish** [comment]
I'm pretty sure this is a bug, but I haven't get down to it yet. Thanks for providing a snippet to reproduce it!

**Comment by ltfish** [comment]
Oh, you want to load the project with `angr.Project('xxx', auto_load_libs=False)` so your CFG does not cover the entire libc. Some places in libc triggered that bug.

**Comment by juneJuly** [comment]
yeah, i think i had fixed this.
and ,maybe u should correct this page:


![1](https://user-images.githubusercontent.com/12068014/27819025-e7cc005a-60ca-11e7-88ad-fa860e8cf0bb.png)
