### ISSUE TITLE
pypy installation broken

### ISSUE THREAD

**Issue by humeafo** [angr/angr#517]
install current version of angr under pypy 5.8.0(virtualenv) on macos with following error:    

ar rcs libpyvex.a pyvex.o logging.o
    No handlers could be found for logger "cffier"
    IndexError('list index out of range',)
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/private/var/folders/fc/82tbrzf11rlbklr6c2rkt9l80000gn/T/pip-build-wQme6S/simuvex/setup.py", line 117, in <module>
        'simuvex': ['lib/*']
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/dist.py", line 320, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/dist.py", line 377, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/aaa/pyenvs/angrpypy/site-packages/pkg_resources/__init__.py", line 852, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/pkg_resources/__init__.py", line 1124, in best_match
        return self.obtain(req, installer)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/pkg_resources/__init__.py", line 1136, in obtain
        return installer(requirement)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/dist.py", line 445, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/command/easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/command/easy_install.py", line 880, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/command/easy_install.py", line 1119, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/command/easy_install.py", line 1105, in run_setup
        run_setup(setup_script, args)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/sandbox.py", line 257, in run_setup
        raise
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/sandbox.py", line 170, in save_modules
        saved_exc.resume()
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/sandbox.py", line 145, in resume
        six.reraise(type, exc, self._tb)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/Users/aaa/pyenvs/angrpypy/site-packages/setuptools/sandbox.py", line 48, in _execfile
        exec(code, globals, locals)
      File "/var/folders/fc/82tbrzf11rlbklr6c2rkt9l80000gn/T/easy_install-nlfxTo/pyvex-6.7.6.9/setup.py", line 147, in <module>
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/var/folders/fc/82tbrzf11rlbklr6c2rkt9l80000gn/T/easy_install-nlfxTo/pyvex-6.7.6.9/setup.py", line 122, in run
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/cmd.py", line 334, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/var/folders/fc/82tbrzf11rlbklr6c2rkt9l80000gn/T/easy_install-nlfxTo/pyvex-6.7.6.9/setup.py", line 104, in run
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/cmd.py", line 357, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/util.py", line 309, in execute
        func(*args)
      File "/var/folders/fc/82tbrzf11rlbklr6c2rkt9l80000gn/T/easy_install-nlfxTo/pyvex-6.7.6.9/setup.py", line 94, in _build_ffi
      File "/var/folders/fc/82tbrzf11rlbklr6c2rkt9l80000gn/T/easy_install-nlfxTo/pyvex-6.7.6.9/make_ffi.py", line 104, in doit
      File "/var/folders/fc/82tbrzf11rlbklr6c2rkt9l80000gn/T/easy_install-nlfxTo/pyvex-6.7.6.9/make_ffi.py", line 42, in find_good_scan
    IndexError: list index out of range

pip list results:
pip list

archinfo (6.7.6.9)
cffi (1.10.1)
greenlet (0.4.12)
pip (9.0.1)
pycparser (2.17)
readline (6.2.4.1)
setuptools (36.0.1)
wheel (0.29.0)

the problem exist when install separate simuvex or pyvex.

**Comment by zardus** [comment]
This should have *just* been fixed in git (https://github.com/angr/pyvex/pull/79). Can you try a development install and see if it works?

**Comment by humeafo** [comment]
it seems that it's the problem. the development install on my macosX failed as described in https://docs.angr.io/INSTALL.html, maybe the expected development env is ubuntu.
however it seems the same problem as described in angr/pyvex#79, so if it's ok, then this should be fixed.

**Comment by Qwaz** [comment]
Could you try the following method and share the result?

1. Activate your PyPy 5.8 virtualenv
2. Clone the pyvex repository `https://github.com/angr/pyvex`
3. `cd` into it and `python setup.py install`
4. `pip install angr`

**Comment by humeafo** [comment]
@Qwaz yes, manually install as your steps can solve the installation error.
