### ISSUE TITLE
KeyError: 18446744073709551615L in posix.py (279)

### ISSUE THREAD

**Issue by likebreath** [angr/angr#673]
I got an `KeyError`, when I applied angr on `id` from GNU CoreUtils [v6.10](https://ftp.gnu.org/gnu/coreutils/coreutils-6.10.tar.gz). I was using the [latest version](https://github.com/angr/angr/tree/e68a61ed652e9b74ace3f1315f18091b63ec87e4) of angr being setup by [angr-dev](https://github.com/angr/angr-dev/tree/55e85d03bbcc7e56e8f346fa4c2f72bef244545d).

## Script to Trigger the Error
```python
import angr, claripy

def exec_angr():
    target_exe = '/path/to/coreutils-6.10/exec/src/id'

    arguments = list()
    arguments.append('/path/to/coreutils-6.10/exec/src/id')

    files = {}
    files['/dev/stdin'] = angr.storage.file.SimFile('/dev/stdin', 'r', size = 8)

    files['/tmp/ramdisk/crete_sym_file_1'] = angr.storage.file.SimFile('/tmp/ramdisk/crete_sym_file_1', 'r', size = 8)
    arguments.append('/tmp/ramdisk/crete_sym_file_1')

    p = angr.Project(target_exe, load_options={'auto_load_libs':True})
    state = p.factory.entry_state(args=arguments, fs=files)
    sm = p.factory.simgr(state, save_unconstrained=True)
    sm.run()

if __name__ == '__main__':
    exec_angr()
```

## TraceBack
``` python
KeyError                                  Traceback (most recent call last)
/home/chenbo/crete/angr-dev/test-angr/replay_error_scripts/angr_error_auto.304.id.py in <module>()
     20 
     21 if __name__ == '__main__':
---> 22     exec_angr()

/home/chenbo/crete/angr-dev/test-angr/replay_error_scripts/angr_error_auto.304.id.py in exec_angr()
     17     state = p.factory.entry_state(args=arguments, fs=files)
     18     sm = p.factory.simgr(state, save_unconstrained=True)
---> 19     sm.run()
     20 
     21 if __name__ == '__main__':

/home/chenbo/crete/angr-dev/angr/angr/manager.pyc in run(self, stash, n, step_func)
    935 
    936         until_func = lambda pg: any(h(pg) for h in self._hooks_complete)
--> 937         return self.step(n=n, step_func=step_func, until=until_func, stash=stash)
    938 
    939 

/home/chenbo/crete/angr-dev/angr/angr/manager.pyc in step(self, n, selector_func, step_func, stash, successor_func, until, **kwargs)
    598             l.debug("Round %d: stepping %s", i, pg)
    599 
--> 600             pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, **kwargs)
    601             if step_func is not None:
    602                 pg = step_func(pg)

/home/chenbo/crete/angr-dev/angr/angr/manager.pyc in _one_step(self, stash, selector_func, successor_func, **kwargs)
    375         # each tick produces a dict of stashes. use _record_step_results to dump them into the result pool.
    376         for a in to_tick:
--> 377             result_stashes = self._one_state_step(a, successor_func=successor_func, **kwargs)
    378             self._record_step_results(new_stashes, new_active, result_stashes)
    379 

/home/chenbo/crete/angr-dev/angr/angr/manager.pyc in _one_state_step(self, a, successor_func, resilience, **kwargs)
    253                     ss = successor_func(a)
    254                 else:
--> 255                     ss = self._project.factory.successors(a, **kwargs)
    256 
    257                 new_stashes = self._make_stashes_dict(

/home/chenbo/crete/angr-dev/angr/angr/factory.pyc in successors(self, state, addr, jumpkind, inline, default_engine, engines, **kwargs)
     75         for engine in engines:
     76             if engine.check(state, inline=inline, **kwargs):
---> 77                 r = engine.process(state, inline=inline,**kwargs)
     78                 if r.processed:
     79                     break

/home/chenbo/crete/angr-dev/angr/angr/engines/syscall.pyc in process(self, state, **kwargs)
     15         sys_procedure = self.project._simos.syscall(state)
     16         addr = state.se.eval(state._ip)
---> 17         return self.project.factory.procedure_engine.process(state, sys_procedure, force_addr=addr)
     18 
     19     #

/home/chenbo/crete/angr-dev/angr/angr/engines/procedure.pyc in process(self, state, procedure, ret_to, inline, force_addr, **kwargs)
     32                 ret_to=ret_to,
     33                 inline=inline,
---> 34                 force_addr=force_addr)
     35 
     36     def _check(self, state, *args, **kwargs):

/home/chenbo/crete/angr-dev/angr/angr/engines/engine.pyc in process(***failed resolving arguments***)
     52         successors = new_state._inspect_getattr('sim_successors', successors)
     53         try:
---> 54             self._process(new_state, successors, *args, **kwargs)
     55         except SimException:
     56             if o.EXCEPTION_HANDLING not in old_state.options:

/home/chenbo/crete/angr-dev/angr/angr/engines/procedure.pyc in _process(self, state, successors, procedure, ret_to)
     66 
     67         # do it
---> 68         inst = procedure.execute(state, successors, ret_to=ret_to)
     69         successors.artifacts['procedure'] = inst
     70 

/home/chenbo/crete/angr-dev/angr/angr/sim_procedure.pyc in execute(self, state, successors, arguments, ret_to)
    155 
    156             # run it
--> 157             r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
    158 
    159         if inst.returns and (not inst.successors or len(inst.successors.successors) == 0):

/home/chenbo/crete/angr-dev/angr/angr/procedures/linux_kernel/fstat.pyc in run(self, fd, stat_buf)
      6 
      7     def run(self, fd, stat_buf):
----> 8         stat = self.state.posix.fstat(fd)
      9         # TODO: make arch-neutral
     10         self._store_amd64(stat_buf, stat)

/home/chenbo/crete/angr-dev/angr/angr/state_plugins/posix.pyc in fstat(self, fd)
    277         else:
    278             fd = self.state.se.eval(fd)
--> 279             mode = self.state.se.BVS('st_mode', 32) if not self.files[fd].name.startswith('/dev/') else self.state.se.BVV(0, 32)
    280             # return this weird bogus zero value to keep code paths in libc simple :\
    281 

KeyError: 18446744073709551615L
> /home/chenbo/crete/angr-dev/angr/angr/state_plugins/posix.py(279)fstat()
    277         else:
    278             fd = self.state.se.eval(fd)
--> 279             mode = self.state.se.BVS('st_mode', 32) if not self.files[fd].name.startswith('/dev/') else self.state.se.BVV(0, 32)
    280             # return this weird bogus zero value to keep code paths in libc simple :\
    281 
```

**Comment by zardus** [comment]
@likebreath, does this still happen?

**Comment by likebreath** [comment]
@zardus Sorry for the late reply. The message buried in my inbox. 

With the same test case, I still can reproduce this error with the latest version of angr (026382414b7f0445f4648bb6ff915c2f81769e19). Please let me know if you need any more information.

**Comment by danse-macabre** [comment]
I've also encountered a similar error while running the angr tests that use the SimulationManager.

It seems like, with `resilience` parameter set to `True`, the SimulationManager catches the KeyError exception, as could be seen in [503f51b](https://github.com/angr/angr/commit/503f51b5bc8c54d6a34f18622ce5372e70256d7e):

```python
@@ -271,7 +271,7 @@ 
def _one_state_step(self, a, successor_func=None, resilience=None, **kwargs):
                 self._hierarchy.simplify()
         except (AngrError, SimError, claripy.ClaripyError) as e:
             self.errored.append(ErrorRecord(a, e, sys.exc_info()[2]))
-        except (TypeError, ValueError, ArithmeticError, MemoryError) as e:
+        except (KeyError, IndexError, TypeError, ValueError, ArithmeticError, MemoryError) as e:
             if resilience is False or not self._resilience:
                 raise
             self.errored.append(ErrorRecord(a, e, sys.exc_info()[2]))
```

However, if we remove KeyError exception from the list of catchable exceptions, kind of similar error occurs in `test_accuracy.test_emulation`:

```
ERROR: test_accuracy.test_emulation(<Project /home/user/angr/tests/../../binaries/tests/ppc64/test_arrays>, 183, (285504656, 268436476, 268436328), False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/.virtualenv/angr/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/angr/tests/test_accuracy.py", line 22, in emulate
    pg2 = pg.step(until=lambda lpg: len(lpg.active) != 1)
  File "/home/user/angr/angr/manager.py", line 613, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, **kwargs)
  File "/home/user/angr/angr/manager.py", line 387, in _one_step
    result_stashes = self._one_state_step(a, successor_func=successor_func, **kwargs)
  File "/home/user/angr/angr/manager.py", line 265, in _one_state_step
    ss = self._project.factory.successors(a, **kwargs)
  File "/home/user/angr/angr/factory.py", line 81, in successors
    r = engine.process(state, inline=inline,**kwargs)
  File "/home/user/angr/angr/engines/syscall.py", line 35, in process
    return self.project.factory.procedure_engine.process(state, sys_procedure, force_addr=addr)
  File "/home/user/angr/angr/engines/procedure.py", line 34, in process
    force_addr=force_addr)
  File "/home/user/angr/angr/engines/engine.py", line 54, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/user/angr/angr/engines/procedure.py", line 68, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/home/user/angr/angr/sim_procedure.py", line 167, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/home/user/angr/angr/procedures/linux_kernel/fstat.py", line 8, in run
    stat = self.state.posix.fstat(fd)
  File "/home/user/angr/angr/state_plugins/posix.py", line 279, in fstat
    mode = self.state.se.BVS('st_mode', 32, key=('api', 'fstat', 'st_mode')) if not self.files[fd].name.startswith('/dev/') else self.state.se.BVV(0, 32)
KeyError: 18446744073692772144L
```

**Comment by rhelmot** [comment]
See my comment on https://github.com/angr/angr/issues/674#issuecomment-369008949
