### ISSUE TITLE
Capstone cannot import name arm

### ISSUE THREAD

**Issue by mdehavensift** [angr/angr#675]
When installing angr-7.7.9.21 using pip, importing angr fails with the error below. The version of capstone that is downloaded is capstone-3.0.4. If I manually install capstone-3.0.5rc2, as is specified in the requirements file for angr-6.7.4.12, importing angr works fine.

Should the requirements file for angr specify the version of capstone to be 3.0.5rc2? Currently, no version is specified for capstone and, for me at least, it appears to be getting an older version that does not work for angr.

```
>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/virtual-env/angr/local/lib/python2.7/site-packages/angr/__init__.py", line 26, in <module>
    from .project import *
  File "/home/user/virtual-env/angr/local/lib/python2.7/site-packages/angr/project.py", line 592, in <module>
    from .analyses.analysis import Analyses
  File "/home/user/virtual-env/angr/local/lib/python2.7/site-packages/angr/analyses/__init__.py", line 22, in <module>
    from .reassembler import Reassembler
  File "/home/user/virtual-env/angr/local/lib/python2.7/site-packages/angr/analyses/reassembler.py", line 9, in <module>
    import capstone
  File "/home/user/virtual-env/angr/local/lib/python2.7/site-packages/capstone/__init__.py", line 6, in <module>
    from . import arm, arm64, mips, ppc, sparc, systemz, x86, xcore
ImportError: cannot import name arm
```

**Comment by schieb** [comment]
`pip install -I --no-use-wheel capstone`

**Comment by ltfish** [comment]
I'm very tempted to release an `angr-capstone` package on PyPI. @rhelmot killed my crazy idea though.

**Comment by rhelmot** [comment]
I'd forgotten that we used to have the version number pinned to the rc version! Must have gotten lost in the big refactor somehow...

I just re-pinned it so this should be super-fixed next time we make a release. soon.
