### ISSUE TITLE
Error in Installation Process

### ISSUE THREAD

**Issue by miladkahsarialhadi** [angr/angr#686]
Hey, geeks. 

after installation angr in ubuntu 17, when I import it, It shows me an error.

>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c3phalex1n/Desktop/Environments/angr/local/lib/python2.7/site-packages/angr/__init__.py", line 26, in <module>
    from .project import *
  File "/home/c3phalex1n/Desktop/Environments/angr/local/lib/python2.7/site-packages/angr/project.py", line 592, in <module>
    from .analyses.analysis import Analyses
  File "/home/c3phalex1n/Desktop/Environments/angr/local/lib/python2.7/site-packages/angr/analyses/__init__.py", line 22, in <module>
    from .reassembler import Reassembler
  File "/home/c3phalex1n/Desktop/Environments/angr/local/lib/python2.7/site-packages/angr/analyses/reassembler.py", line 9, in <module>
    import capstone
  File "/home/c3phalex1n/Desktop/Environments/angr/local/lib/python2.7/site-packages/capstone/__init__.py", line 6, in <module>
    from . import arm, arm64, mips, ppc, sparc, systemz, x86, xcore
ImportError: cannot import name arm

**Comment by miladkahsarialhadi** [comment]
I fix the problem with running the following command in virtualenv.

 pip install -I --no-binary capstone

**Comment by rhelmot** [comment]
Yeah this is a known issue involving the fact that capstone has the weirdest release cycle imaginable. We did some interesting stuff in the packaging metadata recently, so next time we make a release to pypi, things should just work.

(to answer your original question, we don't have distribution on the debian/ubuntu repos because we don't have enough time to maintain it. additionally, we have to install a customized version of a library that is also distributed by valgrind, and the conflict between those might be awkward. finally, we depend on things (unicorn engine comes to mind) that aren't on debian/ubuntu.)
