### ISSUE TITLE
CFGAccurate bug

### ISSUE THREAD

**Issue by XiaoyuHe** [angr/angr#700]
When I analysis ffmpeg(n3.1.11) and run following command: 
       cfg = proj.analyses.CFGAccurate(keep_state=True)

Error occur:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/angr-dev/angr/angr/analyses/analysis.py", line 96, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/root/angr-dev/angr/angr/analyses/cfg/cfg_accurate.py", line 275, in __init__
    self._analyze()
  File "/root/angr-dev/angr/angr/analyses/forward_analysis.py", line 500, in _analyze
    self._analysis_core_baremetal()
  File "/root/angr-dev/angr/angr/analyses/forward_analysis.py", line 610, in _analysis_core_baremetal
    self._pre_job_handling(job_info.job)
  File "/root/angr-dev/angr/angr/analyses/cfg/cfg_accurate.py", line 1093, in _pre_job_handling
    sim_successors, exception_info, _ = self._get_simsuccessors(addr, job, current_function_addr=job.func_addr)
  File "/root/angr-dev/angr/angr/analyses/cfg/cfg_accurate.py", line 2673, in _get_simsuccessors
    opt_level=self._iropt_level)
  File "/root/angr-dev/angr/angr/factory.py", line 77, in successors
    r = engine.process(state, inline=inline,**kwargs)
  File "/root/angr-dev/angr/angr/engines/syscall.py", line 17, in process
    return self.project.factory.procedure_engine.process(state, sys_procedure, force_addr=addr)
  File "/root/angr-dev/angr/angr/engines/procedure.py", line 34, in process
    force_addr=force_addr)
  File "/root/angr-dev/angr/angr/engines/engine.py", line 54, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/root/angr-dev/angr/angr/engines/procedure.py", line 68, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/root/angr-dev/angr/angr/sim_procedure.py", line 164, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/root/angr-dev/angr/angr/procedures/linux_kernel/fstat.py", line 8, in run
    stat = self.state.posix.fstat(fd)
  File "/root/angr-dev/angr/angr/state_plugins/posix.py", line 279, in fstat
    mode = self.state.se.BVS('st_mode', 32) if not self.files[fd].name.startswith('/dev/') else self.state.se.BVV(0, 32)
  File "/root/angr-dev/angr/angr/state_plugins/sim_action_object.py", line 87, in __getattr__
    f = getattr(self.ast, attr)
  File "/root/angr-dev/claripy/claripy/ast/base.py", line 958, in __getattr__
    raise AttributeError(a)
AttributeError: startswith

**Comment by ltfish** [comment]
Thanks for reporting. Can you please give us the binary, so we can re-produce the issue?

**Comment by XiaoyuHe** [comment]
Thank you! .It's size is over 100M.

**Comment by ltfish** [comment]
Can you please upload it to Google Drive or DropBox?

Slack probably does not have a file size limit. Feel free to PM me the file on angr Slack.

**Comment by XiaoyuHe** [comment]
Wait a while. When the  upload is complete, I send to link to you.

**Comment by XiaoyuHe** [comment]
https://drive.google.com/open?id=0B_Z8IDR-q1pfNGhYbjdiZWc3cEk

**Comment by ltfish** [comment]
Downloaded. Thanks!
