### ISSUE TITLE
Iop_Sub64Fx2._calculate() errored

### ISSUE THREAD

**Issue by humeafo** [angr/angr#715]
the error message is following:

WARNING | 2017-10-18 19:29:15,714 | angr.engines.vex.irop | IROp error (for operation Iop_Sub64Fx2)
Traceback (most recent call last):
  File "/home/qlnx/mdev/symexec/angr/angr-dev/angr/angr/engines/vex/irop.py", line 909, in translate_inner
    return irop.calculate(*s_args)
  File "/home/qlnx/mdev/symexec/angr/angr-dev/angr/angr/engines/vex/irop.py", line 351, in calculate
    return self.extend_size(self._calculate(args))
  File "/home/qlnx/mdev/symexec/angr/angr-dev/angr/angr/engines/vex/irop.py", line 408, in _op_mapped
    return getattr(claripy.ast.BV, o)(*sized_args)
  File "/home/qlnx/mdev/symexec/angr/angr-dev/claripy/claripy/operations.py", line 46, in _op
    fixed_args = tuple(_type_fixer(args))
  File "/home/qlnx/mdev/symexec/angr/angr-dev/claripy/claripy/operations.py", line 23, in _type_fixer
    "{} arguments ({} given)".format(name, len(arg_types), len(args)))
SimOperationError: ('Iop_Sub64Fx2._calculate() raised exception', <class 'claripy.errors.ClaripyTypeError'>, ClaripyTypeError('Operation __sub__ takes exactly 2 arguments (3 given)',))

**Comment by rhelmot** [comment]
1) can you please provide the instruction which produced this error?
2) can you please run `python -m angr.misc.bug_report` and post the result here?

**Comment by humeafo** [comment]
1.the binary is https://github.com/zardus/cgc-bins/raw/master/all_unpatched/CROMU_00073 and faulting instruction is subpd

2.see the attached result
[angr.misc.bug_report.txt](https://github.com/angr/angr/files/1397673/angr.misc.bug_report.txt)

**Comment by rhelmot** [comment]
Looks like we're missing support for vectorized floating point operations. We dealt with this during CGC by disabling floating point support entirely and forcing any FP instruction to be concretized and run through unicorn via the [oppologist](https://github.com/angr/angr/blob/master/angr/exploration_techniques/oppologist.py).

I will have a fix shortly.
