### ISSUE TITLE
UnsatError("cached unsat")

### ISSUE THREAD

**Issue by ench4nt3r** [angr/angr#721]
Hi, When I use the following command, angr reported an exception.

```
>>> import angr
>>> import claripy
>>>
>>> p = angr.Project('./bcf')
>>> state = p.factory.entry_state(addr=0x80483F0)
>>> x = claripy.BVS('x', 4 * 8)
>>> y = claripy.BVS('y', 4 * 8)
>>> state.memory.store(0x0804A020, x)
>>> state.memory.store(0x0804A024, y)
>>>
>>> n = state.step()
>>> n
<IRSB from 0x80483f0: 1 sat 1 unsat>
>>> n.successors[0].ip
<BV32 0x8048444>
>>> n.unsat_successors[0].ip
<BV32 0x804843f>
>>>
>>> n.successors[0].se.eval(x)
0
>>> n.unsat_successors[0].se.eval(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 525, in eval
    return self.eval_upto(e, 1, **kwargs)[0]
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 508, in eval_upto
    cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 157, in concrete_shortcut_tuple
    return f(self, *args, **kwargs)
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/angr/state_plugins/sim_action_object.py", line 53, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 88, in wrapped_f
    return f(*args, **kwargs)
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 369, in _eval
    return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/claripy/frontend_mixins/concrete_handler_mixin.py", line 7, in eval
    return super(ConcreteHandlerMixin, self).eval(e, n, **kwargs)
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 40, in eval
    return super(ConstraintFilterMixin, self).eval(e, n, extra_constraints=ec, **kwargs)
  File "/home/ench4nt3r/python_env/local/lib/python2.7/site-packages/claripy/frontend_mixins/sat_cache_mixin.py", line 52, in eval
    if self._cached_satness is False: raise UnsatError("cached unsat")
angr.errors.SimUnsatError: ('Got an unsat result', <class 'claripy.errors.UnsatError'>, UnsatError('cached unsat',))
```
The following is the CFG of the `./bcf` binary file:
<img src="http://ww2.sinaimg.cn/large/0060lm7Tly1fksajkr1ilj30gh0z40u4.jpg"><img>

Thnks.

**Comment by ench4nt3r** [comment]
<table>
    <tr>
        <td><a href="https://docs.angr.io/docs/pathgroups.html">unsat</a>    </td>
    <td>If the save_unsat option is provided to the SimulationManager constructor, states that are determined to be unsatisfiable (i.e., they have constraints that are contradictory, like the input having to be both "AAAA" and "BBBB" at the same time) are placed here.</td>
    </tr>
</table>


Where unsat is the same as unsat_successors? That is,  `0x804843f` is unreachable?

**Comment by ench4nt3r** [comment]
It seems wrong, I was using sigmr implementation, unsat is empty.

```
>>> simgr = p.factory.simgr(state)
>>> simgr.active
[<SimState @ 0x80483f0>]
>>> simgr.step()
<SimulationManager with 1 active>
>>> simgr.active
[<SimState @ 0x8048444>]
>>> simgr.unsat
[]
>>>
```

**Comment by ltfish** [comment]
Use `simgr = p.factory.simgr(state, save_unsat=True)` and you will see the unsat state in `simgr.unsat` after symbolic execution.

**Comment by ench4nt3r** [comment]
@ltfish thnks.
