### ISSUE TITLE
Crash/Error during symbolic memory write/concretization

### ISSUE THREAD

**Issue by lordmoses** [angr/angr#743]
```
Ok, consider this loop which copies the value of al into [di], cx number of times. Somewhere close to the end of the loop, I got a weird error when I stepped. I know the error has to do with register di being symbolic, but can anybody give me more insight?

In [40]: p.factory.block(0x7fee8799496).pp()
0x7fee8799496:  rep stosb       byte ptr [rdi], al


In [12]: active_states[4].regs.rcx
Out[12]: <BV64 0x7>

In [14]: active_states[4].regs.rdi
Out[14]: <BV64 0xffffffffffffff75 + 0x0#40 .. (if (state_merge_4_31_16 == 0x1) then 28 else (if (state_merge_4_31_16 == 0x0) then 28 else 0)) .. (if (state_merge_4_31_16 == 0x1) then 237 else (if (state_m
erge_4_31_16 == 0x0) then 237 else 0)) .. (if (state_merge_4_31_16 == 0x1) then 88 else (if (state_merge_4_31_16 == 0x0) then 136 else 0))>

** I stepped the loop until this. Notice cx decremented from 7 to 1, and di incremented from 75 to 7c **

In [32]: active_states[4].regs.rcx
Out[32]: <BV64 0x1>

In [33]: active_states[4].regs.rdi
Out[33]: <BV64 0xffffffffffffff7b + 0x0#40 .. (if (state_merge_4_31_16 == 0x1) then 28 else (if (state_merge_4_31_16 == 0x0) then 28 else 0)) .. (if (state_merge_4_31_16 == 0x1) then 237 else (if (state_m
erge_4_31_16 == 0x0) then 237 else 0)) .. (if (state_merge_4_31_16 == 0x1) then 88 else (if (state_merge_4_31_16 == 0x0) then 136 else 0))>


** I stepped again, then got this error **


WARNING | 2017-11-04 19:27:07,471 | angr.engines.vex.engine | 0x7fee8799496 hit an error while analyzing statement 9
Traceback (most recent call last):
  File "/home/moses/angr-dev/angr/angr/engines/vex/engine.py", line 223, in _handle_irsb
    self._handle_statement(state, successors, stmt)
  File "/home/moses/angr-dev/angr/angr/engines/vex/engine.py", line 330, in _handle_statement
    s_stmt = translate_stmt(stmt, state)
  File "/home/moses/angr-dev/angr/angr/engines/vex/statements/__init__.py", line 29, in translate_stmt
    s.process()
  File "/home/moses/angr-dev/angr/angr/engines/vex/statements/base.py", line 20, in process
    self._execute()
  File "/home/moses/angr-dev/angr/angr/engines/vex/statements/store.py", line 28, in _execute
    self.state.memory.store(addr.expr, data.expr, action=a, endness=self.stmt.endness)
  File "/home/moses/angr-dev/angr/angr/storage/memory.py", line 535, in store
    self._store(request)
  File "/home/moses/angr-dev/angr/angr/state_plugins/symbolic_memory.py", line 676, in _store
    req.actual_addresses = self.concretize_write_addr(req.addr)
  File "/home/moses/angr-dev/angr/angr/state_plugins/symbolic_memory.py", line 406, in concretize_write_addr
    return self._apply_concretization_strategies(addr, strategies, 'store')
  File "/home/moses/angr-dev/angr/angr/state_plugins/symbolic_memory.py", line 388, in _apply_concretization_strategies
    "Unable to concretize address for %s with the provided strategies." % action
SimMemoryAddressError: Unable to concretize address for store with the provided strategies.```

**Comment by m1ghtym0** [comment]
The problem is that the concretization strategy can't get any solution for `rdi` in this case.
Can you give me the `active_state[4].memory.write_strategies`? And the output of `state.solver.eval_upto(active_state[4].regs.rdi, 10)`?

**Comment by lordmoses** [comment]
I send those to you when I reproduce the state I was in.
