### ISSUE TITLE
cfg_accurate: problem with __isoc99_scanf analysis

### ISSUE THREAD

**Issue by axt** [angr/angr#76]
Found some strange behavior:

This is the analysis:
```python
    start_state = b.factory.blank_state(addr=addr)
    start_state.stack_push(0x0)
    cfg = b.analyses.CFG(fail_fast=True, starts=[addr], initial_state=start_state, context_sensitivity_level=3, keep_state=True, call_depth=100)
```
For this input:
```c
#include <stdio.h>

int global;
int cmp() {
    return global >= 0 && global <= 100;
}

int main(int argc, char *argv[])
{
    int x;
    cmp();
    scanf("%d", &x);
    return 0;
}
```
It creates this graph:
(but only with `scanf`. If I replace `scanf` with `printf`, it doesn't produce pathterminator nodes)

![guebx_cfg_full](https://cloud.githubusercontent.com/assets/759365/14058746/04d4873a-f32b-11e5-9a91-3db7943a6964.png)

If I replace `global` with a stack variable:
```c
#include <stdio.h>

int global;
int cmp() {
      int a;return a >=0 && a < 100;
}

int main(int argc, char *argv[])
{
    int x;
    cmp();
    scanf("%d", &x);
    return 0;
}
```
It also works fine:
![gueby_cfg_full](https://cloud.githubusercontent.com/assets/759365/14058754/29db4820-f32b-11e5-82e8-962c00eb4357.png)

**Comment by ltfish** [comment]
When `keep_state=True`, SimProcedures will be executed when generating the CFG. I bet an exception is raised when executing SimProcedure `scanf`, and that's why a `PathTerminator` is created. Take a look at `CFGAccurate._get_simrun` and see what the exception is.

**Comment by axt** [comment]
I see. Setting the log level to `DEBUG` helps a lot. So this means, `claripy` can't resolve the constraint, and it is expected behavior. Thanks.

```
DEBUG   | 2016-03-26 23:57:15,301 | angr.analyses.cfg | Caught a SimError when during CFG recovery. Don't panic, this is usually expected.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg_accurate.py", line 2252, in _get_simrun
    sim_run = self.project.factory.sim_run(current_entry.state, jumpkind=jumpkind)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 125, in sim_run
    r = sim_proc_class(state, addr=addr, sim_kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/s_procedure.py", line 67, in __init__
    r = run_func(*args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/procedures/libc___so___6/__isoc99_scanf.py", line 27, in run
    self.state.posix.read_from(0, end - start)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/plugins/posix.py", line 191, in read_from
    return self.get_file(fd).read_from(length)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/storage/file.py", line 121, in read_from
    data = self.content.load(self.pos, read_length)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/storage/memory.py", line 589, in load
    a,r,c = self._load(addr_e, size_e, condition=condition_e, fallback=fallback_e)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/plugins/symbolic_memory.py", line 531, in _load
    _,max_size = self._symbolic_size_range(size)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/plugins/symbolic_memory.py", line 281, in _symbolic_size_range
    max_size = self.state.se.max_int(size)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/plugins/solver.py", line 73, in autoed_f
    return ast_stripping_op(f, self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/plugins/solver.py", line 43, in ast_stripping_op
    r = _actual_ast_stripping_op(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/s_action_object.py", line 36, in ast_stripping_op
    return f(*new_args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/plugins/solver.py", line 80, in wrapped_f
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-4.6.3.15-py2.7.egg/simuvex/plugins/solver.py", line 248, in max
    return self._solver.max(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontends/caching_frontend.py", line 503, in max
    m = self._max(e, extra_constraints=extra_constraints, exact=exact, cache=cache)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontends/full_frontend.py", line 107, in _max
    raise UnsatError("Unsat during _max()")
SimUnsatError: ('Got an unsat result', <class 'claripy.errors.UnsatError'>, UnsatError('Unsat during _max()',))
DEBUG   | 2016-03-26 23:57:15,323 | angr.analyses.cfg | Tracing a missing return exit (None -> None, None -> 0x8048461), 0x8048483 [normal]
```

**Comment by ltfish** [comment]
Right...

So the problem is that by default when `keep_state=True`, SimProcedures will be executed. However, in `fastpath` mode (the mode which CFG is generated with), many SimProcedures will simply fail. I may create a new option for users to control if SimProcedures should be executed or not.

**Comment by axt** [comment]
Thanks, for the clarification! Just run a quick test, no PathTerminators when `keep_state=False`! 
For me that is enough at the moment.

(I have no idea that the `keep_state=True` while not executing simprocedures makes sense or not :-) )

**Comment by ltfish** [comment]
> (I have no idea that the `keep_state=True` while not executing simprocedures makes sense or not :-) )

It depends on what you want from `CFGAccurate`. They might be useful sometimes. States from `CFGAccurate` is not faithful to the real execution anyways (since symbolic execution is not used).

I'll add that option later, so users can choose based on their needs!

**Comment by ViktorMKa** [comment]
Unrelated to the issue, but i'd like to know how you output these neat-looking graphs. What i get, using `nx.write_dot(cfg.graph, name)` and viewing with xdot is much less informative.

**Comment by ltfish** [comment]
@ViktorMKa : axt answered it in another issue. Check this out: https://github.com/axt/angr-utils
