### ISSUE TITLE
CFG() crashes with: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by HclX** [angr/angr#793]
I was analyzing an executable from LG G6 phone (lafd, AARCH64), and it crashed when trying to generate CFG:

Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>> p = angr.Project('./lafd')
>>> p.analyses.CFG()
WARNING | 2017-12-08 19:47:51,933 | angr.analyses.cfg.cfg_fast | "auto_load_libs" is enabled. With libraries loaded in project, CFGFast will cover libraries, which may take significantly more time than expected. You may reload the binary with "auto_load_libs" disabled, or specify "regions" to limit the scope of CFG recovery.
WARNING | 2017-12-08 19:47:55,003 | angr.procedures.definitions | unsupported syscall: sys_96
WARNING | 2017-12-08 19:47:55,005 | angr.procedures.definitions | unsupported syscall: sys_96
WARNING | 2017-12-08 19:47:55,006 | angr.procedures.definitions | unsupported syscall: sys_96
WARNING | 2017-12-08 19:47:55,024 | angr.procedures.definitions | unsupported syscall: sys_96
WARNING | 2017-12-08 19:47:55,025 | angr.procedures.definitions | unsupported syscall: sys_96
WARNING | 2017-12-08 19:47:55,081 | angr.procedures.definitions | unsupported syscall: sys_226
WARNING | 2017-12-08 19:47:55,082 | angr.procedures.definitions | unsupported syscall: sys_226
WARNING | 2017-12-08 19:47:55,083 | angr.procedures.definitions | unsupported syscall: sys_226
WARNING | 2017-12-08 19:47:55,084 | angr.procedures.definitions | unsupported syscall: sys_226
WARNING | 2017-12-08 19:47:55,085 | angr.procedures.definitions | unsupported syscall: sys_226
WARNING | 2017-12-08 19:47:55,108 | angr.procedures.definitions | unsupported syscall: sys_94
WARNING | 2017-12-08 19:47:55,109 | angr.procedures.definitions | unsupported syscall: sys_94
WARNING | 2017-12-08 19:47:55,110 | angr.procedures.definitions | unsupported syscall: sys_94
WARNING | 2017-12-08 19:47:55,111 | angr.procedures.definitions | unsupported syscall: sys_94
WARNING | 2017-12-08 19:47:55,112 | angr.procedures.definitions | unsupported syscall: sys_94
INFO    | 2017-12-08 19:47:55,246 | pyvex.lift.libvex | ARM64 front end: load_store

WARNING | 2017-12-08 19:47:55,327 | angr.procedures.definitions | unsupported syscall: sys_56
WARNING | 2017-12-08 19:47:55,329 | angr.procedures.definitions | unsupported syscall: sys_56
WARNING | 2017-12-08 19:47:55,329 | angr.procedures.definitions | unsupported syscall: sys_56
WARNING | 2017-12-08 19:47:55,330 | angr.procedures.definitions | unsupported syscall: sys_56
WARNING | 2017-12-08 19:47:55,332 | angr.procedures.definitions | unsupported syscall: sys_56
WARNING | 2017-12-08 19:47:55,350 | angr.procedures.definitions | unsupported syscall: sys_119
WARNING | 2017-12-08 19:47:55,351 | angr.procedures.definitions | unsupported syscall: sys_119
WARNING | 2017-12-08 19:47:55,352 | angr.procedures.definitions | unsupported syscall: sys_119
WARNING | 2017-12-08 19:47:55,353 | angr.procedures.definitions | unsupported syscall: sys_119
WARNING | 2017-12-08 19:47:55,357 | angr.procedures.definitions | unsupported syscall: sys_119
WARNING | 2017-12-08 19:47:55,454 | angr.procedures.definitions | unsupported syscall: sys_66
WARNING | 2017-12-08 19:47:55,455 | angr.procedures.definitions | unsupported syscall: sys_66
WARNING | 2017-12-08 19:47:55,456 | angr.procedures.definitions | unsupported syscall: sys_66
WARNING | 2017-12-08 19:47:55,457 | angr.procedures.definitions | unsupported syscall: sys_66
WARNING | 2017-12-08 19:47:55,458 | angr.procedures.definitions | unsupported syscall: sys_66
WARNING | 2017-12-08 19:47:55,473 | angr.procedures.definitions | unsupported syscall: sys_174
WARNING | 2017-12-08 19:47:55,474 | angr.procedures.definitions | unsupported syscall: sys_174
WARNING | 2017-12-08 19:47:55,475 | angr.procedures.definitions | unsupported syscall: sys_174
WARNING | 2017-12-08 19:47:55,480 | angr.procedures.definitions | unsupported syscall: sys_174
WARNING | 2017-12-08 19:47:55,484 | angr.procedures.definitions | unsupported syscall: sys_174
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/analysis.py", line 96, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg.py", line 58, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 810, in __init__
    self._analyze()
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 500, in _analyze
    self._analysis_core_baremetal()
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 625, in _analysis_core_baremetal
    self._process_job_and_get_successors(job_info)
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 643, in _process_job_and_get_successors
    successors = self._get_successors(job)
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1201, in _get_successors
    jobs = self._scan_block(addr, current_function_addr, jumpkind, src_node, src_ins_addr, src_stmt_idx)
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1475, in _scan_block
    previous_src_ins_addr, previous_src_stmt_idx)
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1647, in _scan_irsb
    stmt_idx
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1809, in _create_jobs
    target_addr, jumpkind, is_syscall=is_syscall
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1876, in _create_job_call
    succ = self.project.factory.successors(tmp_state).flat_successors[0]
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/factory.py", line 86, in successors
    self._fix_syscall_ip(r.successors[0])
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/factory.py", line 336, in _fix_syscall_ip
    stub = self._project._simos.syscall(state, allow_unsupported=bypass)
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/simos.py", line 328, in syscall
    num = self.syscall_library.maximum_syscall_number(self.arch.name) + 1 if self.syscall_library else 0
  File "/mnt/d/Linux/home/PyEnvs/angr/local/lib/python2.7/site-packages/angr/procedures/definitions/__init__.py", line 103, in maximum_syscall_number
    return max(self.syscall_number_mapping[arch_name])
ValueError: max() arg is an empty sequence

**Comment by rhelmot** [comment]
This was fixed with this commit: https://github.com/angr/angr/commit/60cde8916

The version installed with `pip install angr` is a little out of date. @ltfish can you _please_ do a release

**Comment by zardus** [comment]
I can do a release after SECCON if fish doesn't beat me to it.
