### ISSUE TITLE
'add_constraints' method missing when trying to execute GetTickCount

### ISSUE THREAD

**Issue by jean-quilbeuf** [angr/angr#795]
I compiled the following program using tcc, naming it getTickCount.exe
```c
#include <stdio.h>
#include <windows.h>
int main()
{
	DWORD start = GetTickCount(); // program starts
	printf("Current value of GetTickCount: %d\n", start);
	return 0;
}
```
I tried to execute it symbolically within angr (version 7.7.9.21 in pip), and got the following error:
```python
>>> import angr
>>> p = angr.Project('getTickCount.exe')
>>> p.factory.simulation_manager(p.factory.entry_state()).run()
WARNING | 2017-12-12 16:02:52,939 | angr.manager | No completion state defined for SimulationManager; stepping until all states deadend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/manager.py", line 937, in run
    return self.step(n=n, step_func=step_func, until=until_func, stash=stash)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/manager.py", line 600, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, **kwargs)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/manager.py", line 377, in _one_step
    result_stashes = self._one_state_step(a, successor_func=successor_func, **kwargs)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/manager.py", line 255, in _one_state_step
    ss = self._project.factory.successors(a, **kwargs)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/factory.py", line 77, in successors
    r = engine.process(state, inline=inline,**kwargs)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/engines/hook.py", line 49, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/engines/procedure.py", line 34, in process
    force_addr=force_addr)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/engines/engine.py", line 54, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/engines/procedure.py", line 68, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/sim_procedure.py", line 157, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/procedures/win32/sim_time.py", line 117, in run
    self.state.solver.add_constraints(val < 2**32)
  File "/home/quilbeuf/.virtualenvs/angr2/lib/python2.7/site-packages/angr/state_plugins/solver.py", line 275, in __getattr__
    f = getattr(claripy._all_operations, a)
AttributeError: 'module' object has no attribute 'add_constraints'
```
Using the USE_SYSTEM_TIMES options avoids the crash:
```python
>>> import angr
>>> p = angr.Project('getTickCount')
>>> s = p.factory.entry_state(add_options={angr.options.USE_SYSTEM_TIMES})
>>> p.factory.simulation_manager(s).run()
WARNING | 2017-12-12 16:21:02,695 | angr.manager | No completion state defined for SimulationManager; stepping until all states deadend
<SimulationManager with 1 deadended>
```

**Comment by schieb** [comment]
This issue has been fixed on master. I believe @ltfish will be making a new release soonish.

**Comment by ltfish** [comment]
A new PyPI release has been made a few days ago. I'm closing this issue.
