### ISSUE TITLE
SimSolverModeError during CFGFast()

### ISSUE THREAD

**Issue by ispoleet** [angr/angr#842]
Hi, I'm trying to calculate the CFG for the `bitcoind` binary, but I'm getting the following error:

```
In [1]: import angr

In [2]: project = angr.Project('bitcoind', load_options={'auto_load_libs': False})WARNING | 2018-01-31 11:11:53,236 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.

In [3]: CFG = project.analyses.CFGFast()
WARNING | 2018-01-31 11:13:21,548 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 global_c000000_17_64{UNINITIALIZED}>
[... TRUNCATED FOR BREVITY ...]
---------------------------------------------------------------------------
SimSolverModeError                        Traceback (most recent call last)
<ipython-input-3-0202d5970722> in <module>()
----> 1 CFG = project.analyses.CFGFast()

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/analysis.pyc in make_analysis(*args, **kwargs)
     94             oself._show_progressbar = show_progressbar
     95 
---> 96             oself.__init__(*args, **kwargs)
     97             return oself
     98 

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/cfg/cfg_fast.pyc in __init__(self, binary, regions, pickle_intermediate_results, symbols, function_prologues, resolve_indirect_jumps, force_segment, force_complete_scan, indirect_jump_target_limit, collect_data_references, extra_cross_references, normalize, start_at_entry, function_starts, extra_memory_regions, data_type_guessing_handlers, arch_options, indirect_jump_resolvers, base_state, exclude_sparse_regions, skip_specific_regions, heuristic_plt_resolving, start, end, **extra_arch_options)
    816 
    817         # Start working!
--> 818         self._analyze()
    819 
    820     #

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/forward_analysis.pyc in _analyze(self)
    506             # An example is the CFG recovery.
    507 
--> 508             self._analysis_core_baremetal()
    509 
    510         else:

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/forward_analysis.pyc in _analysis_core_baremetal(self)
    607 
    608             if not self._job_info_queue:
--> 609                 self._job_queue_empty()
    610 
    611             if not self._job_info_queue:

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/cfg/cfg_fast.pyc in _job_queue_empty(self)
   1293         # Try to see if there is any indirect jump left to be resolved
   1294         if self._resolve_indirect_jumps and self._indirect_jumps_to_resolve:
-> 1295             jump_targets = list(set(self._process_indirect_jumps()))
   1296 
   1297             for addr, func_addr, source_addr, jumpkind in jump_targets:

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/cfg/cfg_fast.pyc in _process_indirect_jumps(self)
   2458                     continue
   2459 
-> 2460                 resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
   2461                 if resolved:
   2462                     break

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/cfg/indirect_jump_resolvers/jumptable.pyc in resolve(self, cfg, addr, func_addr, block, jumpkind)
    195                 ij = cfg.indirect_jumps[addr]
    196                 ij.jumptable = True
--> 197                 ij.jumptable_addr = state.se.min(jump_addr)
    198                 ij.jumptable_targets = jump_table
    199                 ij.jumptable_entries = total_cases

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/state_plugins/solver.pyc in concrete_shortcut_scalar(self, *args, **kwargs)
    145         v = _concrete_value(args[0])
    146         if v is None:
--> 147             return f(self, *args, **kwargs)
    148         else:
    149             return v

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/state_plugins/sim_action_object.pyc in ast_stripper(*args, **kwargs)
     51         new_args = _raw_ast(args)
     52         new_kwargs = _raw_ast(kwargs)
---> 53         return f(*new_args, **new_kwargs)
     54     return ast_stripper
     55 

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/state_plugins/solver.pyc in wrapped_f(*args, **kwargs)
     86     def wrapped_f(*args, **kwargs):
     87         try:
---> 88             return f(*args, **kwargs)
     89         except claripy.UnsatError:
     90             e_type, value, traceback = sys.exc_info()

/usr/local/lib/python2.7/dist-packages/angr-7.7.9.21-py2.7.egg/angr/state_plugins/solver.pyc in min(self, e, extra_constraints, exact)
    391             assert ar <= er
    392             return ar
--> 393         return self._solver.min(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
    394 
    395     @timed_function

/usr/local/lib/python2.7/dist-packages/claripy-7.7.9.21-py2.7.egg/claripy/frontend_mixins/concrete_handler_mixin.pyc in min(self, e, **kwargs)
     35             return c
     36         else:
---> 37             return super(ConcreteHandlerMixin, self).min(e, **kwargs)
     38 
     39     def solution(self, e, v, **kwargs):

/usr/local/lib/python2.7/dist-packages/claripy-7.7.9.21-py2.7.egg/claripy/frontend_mixins/constraint_filter_mixin.pyc in min(self, e, extra_constraints, **kwargs)
     50     def min(self, e, extra_constraints=(), **kwargs):
     51         ec = self._constraint_filter(extra_constraints)
---> 52         return super(ConstraintFilterMixin, self).min(e, extra_constraints=ec, **kwargs)
     53 
     54     def solution(self, e, v, extra_constraints=(), **kwargs):

/usr/local/lib/python2.7/dist-packages/claripy-7.7.9.21-py2.7.egg/claripy/frontends/light_frontend.pyc in min(self, e, extra_constraints, exact)
     58             return self._solver_backend.min(e)
     59         except BackendError:
---> 60             raise ClaripyFrontendError("Light solver can't handle this min().")
     61 
[bitcoind.zip](https://github.com/angr/angr/files/1682407/bitcoind.zip)

     62     def solution(self, e, v, extra_constraints=(), exact=None):

SimSolverModeError: ('Translated claripy error:', <class 'claripy.errors.ClaripyFrontendError'>, ClaripyFrontendError("Light solver can't handle this min().",))
```

Could you please help me? `bitcoind` is attached.
[bitcoind.zip](https://github.com/angr/angr/files/1682414/bitcoind.zip)

**Comment by ltfish** [comment]
This issue should've been resolved in the latest version of angr and claripy. Please report back if it still happens to you. The related angr PR was #844.

**Comment by balbassam** [comment]
We are still getting issues with the latest versions of angr and claripy installed from git.


```
  File "/home/gh0s1/Documents/load.py", line 82, in __init__
   self.__cfg = self.__bin.analyses.CFGFast()
 File "/home/gh0s1/.local/lib/python2.7/site-packages/angr/analyses/analysis.py", line 96, in make_analysis
   oself.__init__(*args, **kwargs)
 File "/home/gh0s1/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 819, in __init__
   self._analyze()
 File "/home/gh0s1/.local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 515, in _analyze
   self._post_analysis()
 File "/home/gh0s1/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1369, in _post_analysis
   self._remove_redundant_overlapping_blocks()
 File "/home/gh0s1/.local/lib/python2.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 2610, in _remove_redundant_overlapping_blocks
   self.graph.remove_node(b)
 File "/home/gh0s1/.local/lib/python2.7/site-packages/networkx/classes/digraph.py", line 461, in remove_node
   raise NetworkXError("The node %s is not in the digraph."%(n,))
networkx.exception.NetworkXError: The node <CFGNode 0x8f1490L[2]> is not in the digraph.
```

The interesting note is that the address `0x8f1490L` is not an executable address when we looked at the binary.

**Comment by ltfish** [comment]
Now this is a different issue though. Do you mind opening a new issue, so this can be tracked more easily?

**Comment by balbassam** [comment]
Sure
