### ISSUE TITLE
Can angr be run on binary of a linux kernel (vmlinux)? 

### ISSUE THREAD

**Issue by nisalmenuka2** [angr/angr#845]
Out of curiosity, I tried to run Angr on Linux kernel binary.  I get the following error. What does "Ran out of room in address space" mean? 
Can Angr be used to analyze Linux kernel binary? For example, to generate CFG for vmlinux.

```
>>> b = angr.Project('vmlinux', load_options={'auto_load_libs': False})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 229, in __init__
    self._simos.configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 392, in configure_project
    super(SimLinux, self).configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 303, in configure_project
    super(SimUserland, self).configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 71, in configure_project
    self.return_deadend = self.project.loader.extern_object.allocate()
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 195, in extern_object
    self._map_object(self._extern_object)
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 583, in _map_object
    base_addr = self._find_safe_rebase_addr(obj_size)
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 641, in _find_safe_rebase_addr
    raise CLEOperationError("Ran out of room in address space")
cle.errors.CLEOperationError: Ran out of room in address space


```

**Comment by ltfish** [comment]
It seems that CLE fails to map the dummy extern object into the memory. My guess is that `vmlinux` stays in a very high memory region and somehow conflicts with the dummy extern object. This can be fixed I believe.
