### ISSUE TITLE
pefile not listed as a dependency

### ISSUE THREAD

**Issue by haxmeadroom** [angr/angr#88]
Any reason the module `pefile` isn't listed as a dependency here?

https://github.com/angr/angr/blob/master/setup.py

It's needed for the `exe` examples...

```
ERROR   | 2016-04-21 08:34:38,265 | cle.loader | Loading error when loading /home/w/proj/hoff/angr-dev/angr-doc/examples/whitehatvn2015_re40
0/re400.exe with backend PE
Traceback (most recent call last):
  File "/home/w/proj/hoff/angr-dev/cle/cle/loader.py", line 252, in load_object
    loaded = backend(path, compatible_with=compatible_with, filetype=filetype, is_main_bin=is_main_bin, **options)
  File "/home/w/proj/hoff/angr-dev/cle/cle/backends/pe.py", line 96, in __init__
    raise CLEError("Install the pefile module to use the PE backend!")
CLEError: Install the pefile module to use the PE backend!
```

**Comment by rhelmot** [comment]
see https://github.com/angr/angr/issues/77

**Comment by haxmeadroom** [comment]
Ah.. missed it. thanks.
