### ISSUE TITLE
Unexpected behavior with LAZY_SOLVES

### ISSUE THREAD

**Issue by jakkdu** [angr/angr#891]
Hi. I run [unbreakable script](https://github.com/angr/angr-doc/blob/master/examples/google2016_unbreakable_1/solve.py) without LAZY_SOLVES option.
Since LAZY_SOLVES is just optimization, angr should find the solution even it is slow if I turned off the option.
But angr could not find the path.

```py
adding BitVectors and constraints
creating path and explorer
running explorer
Traceback (most recent call last):
  File "solve.py", line 64, in <module>
    main()
  File "solve.py", line 55, in main
    flag = extract_memory(ex._f) # ex._f is equiv. to ex.found[0]
  File "/home/insu/projects/qsym-eval/tools/driller/driller-venv/local/lib/python2.7/site-packages/angr/surveyors/explorer.py", line 118, in _f
    return self.found[0]
IndexError: list index out of range
```

This is the exception that I got.

**Comment by bennofs** [comment]
I think this is because it hits a timeout if you don't enable `LAZY_SOLVES`:

```
DEBUG   | 2018-03-06 15:51:13,448 | angr.engines.vex.engine | IMark: 0x403304
<snip...>
DEBUG   | 2018-03-06 15:51:13,452 | angr.engines.vex.engine | <angr.engines.vex.engine.SimEngineVEX object at 0x000055
f4e7177b78> adding conditional exit
DEBUG   | 2018-03-06 15:51:13,452 | angr.state_plugins.solver | Creating SimSolverClaripy.
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.posix | <angr.state_plugins.posix.SimStateSystem object at 0x00
0055f4efcde8e0> setting state to <SimState @ 0x403304>
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.posix | ... file <angr.storage.file.SimFile object at 0x000055f
4efcde918> with fd 0
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.posix | ... file <angr.storage.file.SimFile object at 0x000055f
4efcde950> with fd 1
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.posix | ... file <angr.storage.file.SimFile object at 0x000055f
4efcdeb48> with fd 2
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.posix | ... file <angr.storage.file.SimFile object at 0x000055f
4efcde918> with fd /dev/stdin
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.posix | ... file <angr.storage.file.SimFile object at 0x000055f
4efcde950> with fd /dev/stdout
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.posix | ... file <angr.storage.file.SimFile object at 0x000055f
4efcdeb48> with fd /dev/stderr
DEBUG   | 2018-03-06 15:51:13,453 | ana.storable | Caching UUID 31abed34-4e31-4b3f-8bb4-b102fec205e8
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.inspect | Event exit (before) firing...
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.inspect | ... setting exit_target
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.inspect | ... setting exit_guard
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.inspect | ... setting exit_jumpkind
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.inspect | Event constraints (before) firing...
DEBUG   | 2018-03-06 15:51:13,453 | angr.state_plugins.inspect | ... setting added_constraints
DEBUG   | 2018-03-06 15:51:13,454 | claripy.frontends.frontend | ... splitted of size 1
DEBUG   | 2018-03-06 15:51:13,454 | claripy.frontends.frontend | ... processing constraint with 6 variables
DEBUG   | 2018-03-06 15:51:13,454 | claripy.frontends.composite_frontend | <SolverComposite 55f4efcdec60, 1 children>,
 solvers before: 51
DEBUG   | 2018-03-06 15:51:13,454 | claripy.frontends.composite_frontend | Adding 1 constraints to 6 names
DEBUG   | 2018-03-06 15:51:13,454 | claripy.frontends.composite_frontend | composite_solver._merged_solver_for() runni
ng with 6 names
DEBUG   | 2018-03-06 15:51:13,454 | claripy.frontends.composite_frontend | ... got one solver
DEBUG   | 2018-03-06 15:51:13,456 | claripy.frontends.composite_frontend | ... solvers after add: 1
DEBUG   | 2018-03-06 15:51:13,456 | angr.state_plugins.inspect | Event constraints (after) firing...
DEBUG   | 2018-03-06 15:51:13,456 | angr.state_plugins.inspect | Event reg_write (before) firing...
DEBUG   | 2018-03-06 15:51:13,456 | angr.state_plugins.inspect | ... setting reg_write_offset
DEBUG   | 2018-03-06 15:51:13,456 | angr.state_plugins.inspect | ... setting reg_write_length
DEBUG   | 2018-03-06 15:51:13,456 | angr.state_plugins.inspect | ... setting reg_write_expr
DEBUG   | 2018-03-06 15:51:13,456 | angr.state_plugins.symbolic_memory | Doing a store...
DEBUG   | 2018-03-06 15:51:13,457 | angr.state_plugins.symbolic_memory | ... done
DEBUG   | 2018-03-06 15:51:13,457 | angr.state_plugins.inspect | Event reg_write (after) firing...
DEBUG   | 2018-03-06 15:51:13,457 | claripy.frontends.composite_frontend | <SolverComposite 55f4efcdec60, 1 children>
checking satisfiability...
DEBUG   | 2018-03-06 15:51:13,468 | claripy.backends.backend_z3 | Doing a check!
DEBUG   | 2018-03-06 15:56:13,477 | claripy.backends.backend_z3 | Check result: unknown
```

I added a log statement to claripy that logs the solver result, and here the result is `unknown` which can happen if there is a timeout. This makes the state unsat from angr point of view, so it won't explore it further, missing the path that leads to success.

**Comment by Alexeyan** [comment]
Is there a a way to give the solver more time?

**Comment by bennofs** [comment]
I *think* you can set `state.se._solver.timeout`. Not sure if there's any better API to set that.

**Comment by rhelmot** [comment]
That's the best API, though we should really add a getter-setter on the state plugin itself...

Related: https://github.com/angr/claripy/issues/41

**Comment by jakkdu** [comment]
I thought that solving timeout is for each solving.
In lazy solve, it can solve the most complicated solution (i.e. the answer) without timeout.
Why does not use LAZY_SOLVES cause the problem?

**Comment by ltfish** [comment]
I don't have time to look into the script and the challenge, but my guess is that there is at least one path leads to generating a super complex set of constraints _before you reach the end of that path_, which times out the solver during constraint solving (cuz without `LAZY_SOLVES`, we have to solve at every single branching point), while enabling `LAZY_SOLVES` makes you go further on that path and leads to generating more constraints that simplifies the already-complicated set of constraints - yes, I'm not kidding, adding a constraint may make a complex constraint set simpler.

**Comment by jakkdu** [comment]
True. I think you are right. I think something happened in Z3.
If I give another constraints, then angr can solve the challenge without LAZY_SOLVES.
Here is my dirty test.

```py
import angr


START_ADDR = 0x4005bd # first part of program that does computation
AVOID_ADDR = 0x400850 # address of function that prints wrong
FIND_ADDR = 0x400830 # address of function that prints correct
INPUT_ADDR = 0x6042c0 # location in memory of user input
INPUT_LENGTH = 0xf2 - 0xc0 + 1 # derived from the first and last character
                               # reference in data

def extract_memory(state):
    """Convience method that returns the flag input memory."""
    return state.solver.eval(state.memory.load(INPUT_ADDR, INPUT_LENGTH), cast_to=str)

def char(state, n):
    """Returns a symbolic BitVector and contrains it to printable chars for a given state."""
    vec = state.solver.BVS('c{}'.format(n), 8, explicit_name=True)
    return vec, state.solver.And(vec >= ord(' '), vec <= ord('~'))

def main():
    p = angr.Project('unbreakable')

    print('adding BitVectors and constraints')
    state = p.factory.blank_state(addr=START_ADDR)
    prefix = "CTF{"
    for i in range(INPUT_LENGTH):
        c, cond = char(state, i)
        # the first command line argument is copied to INPUT_ADDR in memory
        # so we store the BitVectors for angr to manipulate
        state.memory.store(INPUT_ADDR + i, c)
        if i < len(prefix):
            state.add_constraints(c == ord(prefix[i]))
        #state.add_constraints(cond)

    print('creating path and explorer')
    ex = p.surveyors.Explorer(start=state, find=(FIND_ADDR,), avoid=(AVOID_ADDR,))

    print('running explorer')
    ex.run()

    flag = extract_memory(ex._f) # ex._f is equiv. to ex.found[0]
    print('found flag: {}'.format(flag))

    return flag

def test():
    assert main() == 'CTF{0The1Quick2Brown3Fox4Jumped5Over6The7Lazy8Fox9}'

if __name__ == '__main__':
    main()
```

**Comment by jakkdu** [comment]
This is a problem of z3 although I am not sure what's going on its internal. 
I think we can close this issue, and reopen if we want to investigate it further.
Would it be fine?

**Comment by rhelmot** [comment]
That would be fine.
