### ISSUE TITLE
angr.errors.AngrSyscallError: Unknown syscall jumpkind Ijk_EmWarn

### ISSUE THREAD

**Issue by OhioDuckFarmer** [angr/angr#971]
I was trying to following the angr tutorial section on the guinea pig Fauxware (both from an installation of the latest code via github and docker) but I am unable to run the Control-Flow Graph analysis:

    cfg = project.analyses.CFG()

however, the process errors out with the following:

    ERROR   | 2018-04-28 18:12:46,695 | angr.engines.vex.statements.dirty | Unsupported dirty helper amd64g_dirtyhelper_FSTENV
    ERROR   | 2018-04-28 18:12:46,696 | angr.engines.vex.statements.dirty | Unsupported dirty helper amd64g_dirtyhelper_FLDENV
    WARNING | 2018-04-28 18:12:46,704 | angr.procedures.definitions | unsupported syscall: rt_sigprocmask
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/analysis.py", line 96, in make_analysis
        oself.__init__(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg.py", line 58, in __init__
        CFGFast.__init__(self, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 819, in __init__
        self._analyze()
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/forward_analysis.py", line 508, in _analyze
        self._analysis_core_baremetal()
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/forward_analysis.py", line 633, in _analysis_core_baremetal
        self._process_job_and_get_successors(job_info)
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/forward_analysis.py", line 651, in _process_job_and_get_successors
        successors = self._get_successors(job)
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1210, in _get_successors
        jobs = self._scan_block(addr, current_function_addr, jumpkind, src_node, src_ins_addr, src_stmt_idx)
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1484, in _scan_block
        previous_src_ins_addr, previous_src_stmt_idx)
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1656, in _scan_irsb
        stmt_idx
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1818, in _create_jobs
        target_addr, jumpkind, is_syscall=is_syscall
      File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 1886, in _create_job_call
        syscall_stub = self.project.simos.syscall(succ)
      File "/usr/local/lib/python2.7/dist-packages/angr/simos/userland.py", line 55, in syscall
        abi = self.syscall_abi(state)
      File "/usr/local/lib/python2.7/dist-packages/angr/simos/linux.py", line 147, in syscall_abi
        raise AngrSyscallError("Unknown syscall jumpkind %s" % state.history.jumpkind)
    angr.errors.AngrSyscallError: Unknown syscall jumpkind Ijk_EmWarn

I am running angr on an Ubuntu 16.04 TLS system whose kernel information is:

    Linux devlinux 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rhelmot** [comment]
This is definitely a @ltfish bug. In the meantime you can almost certainly work around it by loading your project with `auto_load_libs=False`.

**Comment by OhioDuckFarmer** [comment]
Thanks!  I will give that a try.

**Comment by ltfish** [comment]
Is that an ARM binary? I think you were recovering CFG for the entire ARM libc...

Anyways I really did not handle the jumpkind `Ijk_EmWarn` anywhere. This should be fixed, indeed.

**Comment by OhioDuckFarmer** [comment]
I don't think it was an arm binary as it was in the x86_64 directory of the test files.  I can reboot my system and double check the file if you like

**Comment by ltfish** [comment]
That's fine. I think I can reproduce this issue by generating a CFG on an x86_64 libc shipped with Ubuntu 16.04.

**Comment by Airtnp** [comment]
Hi! Is there any workaround for this problem? I want to load libc library and use CFGFast().

**Comment by ltfish** [comment]
Sorry for the late response. Please see PR #1050.
